### ISSUE TITLE
consult-grep should support escaping the comma

### ISSUE THREAD

**Issue by minad** [minad/consult#100]
Right now comma is used to split the grep regexp and the filter regexp via comma. We need a possibility to escape the comma if it is used as part of the grep regexp. See `consult--async-input-split`.

Proposal: `\,`

**Comment by oantolin** [comment]
`\,` is the C way, `,,` would be the Pascal way. I guess C won, but I thought I'd mention another option.

**Comment by minad** [comment]
Well, elisp also has c-style escape sequences for characters, so I guess we just follow that? Also regexps use backslash for escaping.

**Comment by hmelman** [comment]
Would there be some way to use a key binding here?  Any string you use will possibly conflict with the grep regexp.  (I'd also love to use a binding for `consult-narrow-key`).  

Just playing with it (under selectrum) maybe TAB would be good, because the normal selectrum definition of TAB doesn't seem useful with consult-grep family commands.

**Comment by minad** [comment]
> Would there be some way to use a key binding here? Any string you use will possibly conflict with the grep regexp. (I'd also love to use a binding for consult-narrow-key).

\, would not conflict.

> Just playing with it (under selectrum) maybe TAB would be good, because the normal selectrum definition of TAB doesn't seem useful with consult-grep family commands.

I also thought about that, but I decided against a keybinding. I prefer the way it is implemented now.

**Comment by hmelman** [comment]
> `\,` would not conflict, I think.

Unless you were searching a code base for escaped commas. :)  And would the \ need to be escaped? :)

> I also thought about that, but I decided against a keybinding. I prefer the way it is implemented now.

Could describe your rationale?  I'm trying to understand what I'm missing.

**Comment by minad** [comment]
> Unless you were searching a code base for escaped commas. :) And would the \ need to be escaped? :)

Yes, but I guess then you already have to escape the backslash \\, and we could just ignore that!

> Could describe your rationale? I'm trying to understand what I'm missing.

I want a single search expression, one part being used by grep and one part being used by the completion-style filtering: `grep-regexp,filter-regexp`. I think this is a very convenient interface since you can easily edit both parts of the filter string without relying on special keybindings. It is just fundamental-mode editing. There has been some long discussion in #91, which you could check out, if you feel like it :)

**Comment by hmelman** [comment]
I'll take a look.  I will say it surprised me that consult-grep could do this, narrow after the search.  After thinking a little it made sense that a consult command would want to make use of incremental narrowing, but then you hit this interface issue.  

FWIW I don't think counsel allows filtering on its grep-like commands.  I wasn't a big user of them but a friend is.  I asked him and he said he would just choose an item from a small result set or go to ivy-occur for a large one.  Which is the way I used it too.

I'll go read #91 but my initial thoughts are: (1) I think I'd like a way to disable this, so I never need to think about escaping things and could just use it as I did counsel above; (2) Perhaps it could be the same as `counsel-narrow-key` so I don't have to think about two different special strings in consult input.

**Comment by minad** [comment]
> I'll take a look. I will say it surprised me that consult-grep could do this, narrow after the search. After thinking a little it made sense that a consult command would want to make use of incremental narrowing, but then you hit this interface issue.

Which interface issue? The escaping? This is a marginal issue at best.

> FWIW I don't think counsel allows filtering on its grep-like commands. I wasn't a big user of them but a friend is. I asked him and he said he would just choose an item from a small result set or go to ivy-occur for a large one. Which is the way I used it too.

Yes, but `consult-grep` is better :smile: You should try it, I find it very powerful. You just have two filtering steps and you can edit them as one. If you look at helm or orderless, these things are not that uncommon. You can use some special characters like ! to  mark some expressions, and here we are not doing anything hugely different - the comma is only a separator.

> I'll go read #91 but my initial thoughts are: (1) I think I'd like a way to disable this, so I never need to think about escaping things and could just use it as I did counsel above; (2) Perhaps it could be the same as counsel-narrow-key so I don't have to think about two different special strings in consult input.

I won't support a way to disable this. You should try to get accustomed to the interface. It is simple and easy to understand. If you still don't like it there are alternatives like `grep`, `project-find-regexp`, `vc-grep` and others. But I find these clumsy and prefer the `consult-grep` style now.

**Comment by oantolin** [comment]
Even with the built-in completion styles, this separate filtering step is pretty useful. For example, `partial-completion` will match `p-f-r` to `project-find-regexp` and is much less cumbersome than `p.*f.*r`. So if you use the `partial-completion` style, you can use `consult-grep` to find the definition of `project-find-regexp` with `defun,p-f-r`. Much better than having to type`defun.*p.*f.*.r`.

If you use the `orderless` completion style then it gets even better, since simulating out of order matching with regexps involves a factorial blowup in length!

**Comment by minad** [comment]
@oantolin I agree - it is good to have access to both filtering styles, in particular since orderless is so flexible. It would be a huge waste to not have access to this. Grep can be used for superficial filtering and then the power of orderless comes into play ensuring that our complexity stays polynomial ;)

**Comment by s-kostyaev** [comment]
> or go to ivy-occur for a large one. Which is the way I used it too.

Has consult the same ability? Create buffer with filtered results with one keybinding.

**Comment by minad** [comment]
> Has consult the same ability? Create buffer with filtered results with one keybinding.

Yes, via embark-occur.

**Comment by oantolin** [comment]
And I just added a grep exporter to Embark, @s-kostyaev, so if you use `embark-export` from `consult-grep` you get an honest grep mode buffer with the results. You can also use wgrep on that grep buffer to edit the results in place.

(Exporting to a grep mode buffer is in addition to `embark-occur` which @minad mentioned.)

**Comment by s-kostyaev** [comment]
Thank you for explanation. And for whis great packages. Will pay with `consult-ripgrep` and see if I can use it instead of `rg.el`. Probably I will use both.

**Comment by minad** [comment]
@s-kostyaev I think rg.el and `consult-ripgrep` may fulfill a slightly different purpose. If you use `consult-ripgrep` with selectrum for example you can go to a full blown buffer using embark-occur+wgrep, so for me this `consult-ripgrep` and friends is probably sufficient. But I guess there are more neat features in rg.el. If some could be adopted here with reasonable effort, please let us know!

**Comment by oantolin** [comment]
For one thing, I believe rg.el lets you change the directories searched. (I'm not completely sure, the ripgrep Emacs frontend I'm really familiar with is deadgrep).

**Comment by minad** [comment]
> For one thing, I believe rg.el lets you change the directories searched. (I'm not completely sure, the ripgrep Emacs frontend I'm really familiar with is deadgrep).

Yes, certainly. I think both these packages let you tweak some of the flags? We could allow modification of some flags via arguments to the consult-grep commands, such that it would at least be easy to write wrappers.

**Comment by s-kostyaev** [comment]
> For one thing, I believe rg.el lets you change the directories searched.

Yes. But almost every time I search in the project root directory.

**Comment by hmelman** [comment]
I'm also an rg.el user and will probably continue to use both.  I'll be sure to suggest additional features ;)  The rg results are shown in rg-mode which has a bunch of single bindings to rerun the search changing one thing (the term, from literal to regexp, the dir or project, etc.)  I'm not sure how they might apply.  Maybe the ability to toggle literal, regexp or extended regexp would be nice for consult.

**Comment by s-kostyaev** [comment]
Ability to modify some flags by embark would be also great. I will see if I can do some hacking with it.

**Comment by hmelman** [comment]
I've read #91.  Its a lot to take in without detailed knowledge of number of complex APIs. I do see my initials thoughts weren't novel.  I'll certainly try this filtering, you may have noticed I've been trying everything. :)  

1. Yes I think the separator character should be a defcustom.   I suspect users might have different preferences depending on what things they more commonly search.  Someone that searches .csv files will prefer something other than ,.
2. What motivated you to change it from ; to ,?   ; has the advantage that it is not a special character for regexps and it's less common in plain text.  it is a comment character in elisp, but do people search elisp for comments so much (and include the ;)?  I'd think it's usually symbols or tags like TODO.
3. I think you need some checks if the separator appears before `consult-grep-min-input` characters.  I tried grepping for ",ar" which appeared in a file, but couldn't, "\\,ar" failed too.  (Note: I had to escape the \\ here because it's an escape character in markdown, I almost missed it, so it's use might make reporting issues problematic.)
4. I had set `consult-narrow-key` to "|" with the idea of it matching a shell pipe for filtering and like it.  I don't think it's a good choice for grep input though.   I saw mentions of pipelines in the discussion, and I'm not sure what other similar kinds of things you're thinking of, but I recommend considering them all as a whole.  I think it would be complicated to remember (and learn) if various consult commands had lots of special characters to remember.  Particularly in combination with the various inputs (regexps, globbing) and matching styles that are involved.  

I'm still playing with it, but otherwise, the async stuff is working well for me.

If it's not on the list, I know at least one person that is waiting for a `consult-recoll`.

**Comment by minad** [comment]
> I've read #91. Its a lot to take in without detailed knowledge of number of complex APIs. I do see my initials thoughts weren't novel. I'll certainly try this filtering, you may have noticed I've been trying everything. :)

That's great. Thank you for your feedback!

1. We could make it a defcustom but for now I've been hesitant to do it. I see it as part of the "filter language", and searching csv is really the only use case where you would want to change it I guess. But then csv is not even , always, right? it can also be space or tab or semicolon? And csv is not that of a common use case? There is also `grep` and the possibility to escape as discussed in this issue. I want the common case to work well not every special case.
2. , is minimally easier to type and as you say, semicolon is the comment character. But comma and semicolon are both as good I guess. Which meaning does comma have in regexps?
3. Well, if the async part is too short, no search is started. Alternatively I could show some kind of message "enter more characters...". But where should this message appear? And I would probably find it very annoying, so it would need a timeout which means more complexity.
4. Pipe is not a good character for grep, I think. I like the pipe idea, but it is bad due to its regexp interaction. Narrowing and filtering are also sufficiently distinct such that we don't need to use the same character here. As I said, I see the comma as an extension of the filter language "grep-regexp,orderless-filter".

> I'm still playing with it, but otherwise, the async stuff is working well for me.

Good to hear!

> If it's not on the list, I know at least one person that is waiting for a consult-recoll.

Can you make a comment in the wishlist, such that everything is at one place. It also needs some description. What should that command do?

**Comment by hmelman** [comment]
1. Sure the common case should work well, but the special cases have to work too.  An escape character can do that, but everything adds a little more complexity.  Do you have other plans for this "filter language"? If not and it's just this separator then I think a defcustom is good.
2. semicolon is a home key, I'd argue it's a little easier to type than comma. Commas are used in repetition operators. `[a-c]{1,3}` will find any occurrance of a, b, or c at least one time, but up to three times.
3. But my search wasn't too short, I had three characters ",ar" and nothing happened.

I'll add it to the wishlist.  It's another search command geared towards documents.

**Comment by oantolin** [comment]
You could take inspiration from vi and sed and make the syntax `/grep-args/filter` where the `/` stands for any punctuation character, but the same one both times. You could even add the case `grep-args,filter` as long as grep-args does not start with punctuation.

**Comment by minad** [comment]
1. Escaping ensures that every case works at least. Gut @oantolin's sed/perl idea is maybe nicer!
2. Right, I forgot about these {,}. And it is layout dependent, so not really a good argument.
3. Only the part before the comma counts, since this is what triggers the async process.

**Comment by minad** [comment]
Now that I think about it, I have the following proposal.

1. Use a defcustom for a punctuation character.
2. Use this character as initial input
3. Implement the sed/perl syntax and remove support for a simple separator
4. Do not implement escaping

**Comment by hmelman** [comment]
For my point 3, how do I grep for ",ar".  That's my regexp.  What do I need to type to make that run?

**Comment by minad** [comment]
@hmelman this is obviously not yet possible. You need escaping for this.

**Comment by hmelman** [comment]
I tried "\\,ar" and it didn't work either.  Are you saying it should but isn't implemented yet?

**Comment by minad** [comment]
It is not yet implemented. See the title of this issue.

**Comment by hmelman** [comment]
Understood.

**Comment by oantolin** [comment]
> Now that I think about it, I have the following proposal.
> 
> 1. Use a defcustom for a punctuation character.
> 2. Use this character as initial input
> 3. Implement the sed/perl syntax and remove support for a simple separator
> 4. Do not implement escaping

This proposal seems fine to me. Using the character as initial input means you normally won't even have to type it. Personally, I'd also be OK with having to type the first character myself. Probably all the evil users would be fine with typing the first character too.

> But maybe it is just more confusing than a simple comma or semicolon?

Slightly, but @hmelman already needed to search for a comma. It's bound to happen, not often, but still. I do like sed/perl better than an escape mechanism.

> Alternatively implement a defcustom and add the perl/sed idea instead of escaping...

I'm confused, isn't this the same proposal?

**Comment by minad** [comment]
Sry because of the confusion, I meant having both possibilities as you suggested. Perl/sed + separator if first char is not punctuation. But I think it is better to just have a single way. I agree with you that perl/sed is better than writing many escapes. But note that perl also allows escaping 😆

**Comment by minad** [comment]
I implemented this "/async/filter" style now. I like in particular that the initial character gives a hint that something is going on, if you are not yet familiar with the command :)
