### ISSUE TITLE
consult-buffer only showing the active buffer

### ISSUE THREAD

**Issue by dpassen** [minad/consult#1012]
With 73971a47e12bfb54eaf72f0443a8095fa082607a, `consult-buffer` only displays the active buffer. Compare the output of `consult-buffer`:
<img width="377" alt="image" src="https://github.com/minad/consult/assets/997822/1eaf59a8-059d-4711-9a02-b9ac422428f1">
with the result of `kill-buffer`:
<img width="364" alt="image" src="https://github.com/minad/consult/assets/997822/e84bda5b-b295-47d3-8b20-985bcb89bbfe">

**Comment by lodenrogue** [comment]
Having the same issue on Mac OS X 14.4.1

**Comment by drcxd** [comment]
Same issue on Windows

**Comment by thanosapollo** [comment]
Same issue on GNU Guix, the issue seems to be with commit `73971a4`, going back to `369592f` or to version 1.5 `d8888bb` fixes the issue.

**Comment by minad** [comment]
Thanks! Turns out that my commit was incomplete - different from the code I had actually tested via `eval-defun`. The dangers of live development in Elisp...
