### ISSUE TITLE
consult-buffer with `display-buffer-alist`

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#1037]
I have the following `display-buffer-alist` for `eat` buffers.
```
(setq display-buffer-alist
        '(("^\\*eat\\*.*$"
           (display-buffer-reuse-window
            display-buffer-in-tab)
           (reusable-frames . t))))
```

when I open `consult-buffer`, eat buffers are previewed in a new tab which is then used for previewing other buffers. If I got back to eat, other tabs are created. When I `C-g` out of consult, the new tabs remain. 

Best case scenario would be that the new tab is displayed while previewing only eat buffers, but then is deleted for other buffers and when I cancel out of consult. Even ignoring `display-buffer-alist` while previewing would be better than the current situation?

Any ideas if this is possible?

**Comment by minad** [comment]
See #855. Improvements are planned.
