### ISSUE TITLE
Error running timer: (wrong-type-argument sequencep #<marker in no buffer>)

### ISSUE THREAD

**Issue by bhepple** [minad/consult#1038]
This is not a `consult` bug, but could look like that, so I thought I'd document it here for posterity.

The problem (indicated by the title's error message) was triggered by any operation involving registers and `consult` such as `window-configuration-to-register`

A `toggle-debug-on-error` trace will kinda sorta point the bone at `consult` (see below). Also, removing `consult` from the config makes the problem go away - that's why people might think it's a `consult` bug. By all means mark it as closed.

The **solution** in my case was to remove the ~/.emacs.d/.emacs.desktop file. Maybe that is something to add to the list of things to try when creating an issue for `consult`???

Here is the debug trace so that searches might find this item and the solution:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep #<marker in no buffer>)
  mapconcat(identity ("Unprintable entity" #<marker in no buffer>) "\n")
  #f(compiled-function (val) "Describe rectangle or window-configuration register VAL." #<bytecode 0x15170979202abd92>)(("Unprintable entity" #<marker in no buffer>))
  apply(#f(compiled-function (val) "Describe rectangle or window-configuration register VAL." #<bytecode 0x15170979202abd92>) ("Unprintable entity" #<marker in no buffer>) nil)
  consult-register--describe(("Unprintable entity" #<marker in no buffer>))
  consult-register-format((113 "Unprintable entity" #<marker in no buffer>))
  #f(compiled-function (reg) #<bytecode 0xa572da249a60c5>)((113 "Unprintable entity" #<marker in no buffer>))
  consult-register-window("*Register Preview*")
  apply(consult-register-window "*Register Preview*")
  register-preview("*Register Preview*")
  #f(compiled-function () #<bytecode 0x8ffcd4eea08701d>)()
  apply(#f(compiled-function () #<bytecode 0x8ffcd4eea08701d>) nil)
  timer-event-handler([t 26212 17529 511720 nil #f(compiled-function () #<bytecode 0x8ffcd4eea08701d>) nil nil 847000 nil])
  read-key-sequence-vector(#("Window configuration to register: " 0 34 (face minibuffer-prompt)) nil t)
  read-key(#("Window configuration to register: " 0 34 (face minibuffer-prompt)))
  register-read-with-preview("Window configuration to register: ")
  byte-code("\301\302!\10D\207" [current-prefix-arg register-read-with-preview "Window configuration to register: "] 2)
  #<subr call-interactively>(window-configuration-to-register nil nil)
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> window-configuration-to-register nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (window-configuration-to-register nil nil))
  call-interactively(window-configuration-to-register nil nil)
  command-execute(window-configuration-to-register)
```

**Comment by minad** [comment]
See https://github.com/minad/consult?tab=readme-ov-file#bug-reports. It seems you have the ido-cr completion system enabled, which is not supported by Consult.

**Comment by bhepple** [comment]
Thanks - I wasn't aware of having it there!!  I've removed it now.

I think what happened to me was I have some instability in XWayland which crashes sway occasionally and that may have corrupted the .desktop file. Weirdly wxPython apps call XWayland at startup although they run natively on wayland - that's what causes the instability in sway. A tangled web.
