### ISSUE TITLE
consult-buffer crashes emacs every time

### ISSUE THREAD

**Issue by babusri** [minad/consult#1067]
Using GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2023-07-30.

I typically use the built in package manager and have many packages like vertico, marginalia, consult.
consult-buffer used to crash emacs once in a while.

I then wanted to test this without other emacs packages.
So, I had a separate emacs directory where I used straight.el and had only one package, namely consult.

(straight-use-package 'consult)

To repeat, nothing else was installed.

I ran this with --init-directory.

I run ESX-x consult-buffer and emacs crashes. Happens every time.

**Comment by minad** [comment]
Hi! Emacs crashes should be reported upstream to the Emacs devs directly. Consult doesn't perform any unsafe operations, so this means that there is a bug in the Elisp runtime or display engine.
