### ISSUE TITLE
1. make-process default-directory needs trailing slash on mac, 2. pcase-let broken on emacs 28

### ISSUE THREAD

**Issue by jixiuf** [minad/consult#108]
With `consult-ripgrep-project-root` ,consult-ripgrep still search in current directory instead of project root.
```
(defun consult-ripgrep-project-root()
  (let ((consult-project-root-function  #'(lambda() (project-root (project-current t)))) )
    (call-interactively 'consult-ripgrep)))

```

**Comment by minad** [comment]
@jixiuf I cannot confirm this. Maybe project-root returns nil, then it will just use the current directory. Please ensure that you use the newest version and then test something like the following:

~~~ elisp
(let ((consult-project-root-function (lambda () "/etc")))
  (call-interactively #'consult-ripgrep))
~~~

**Comment by jixiuf** [comment]
> @jixiuf I cannot confirm this. Maybe project-root returns nil, then it will just use the current directory. Please ensure that you use the newest version and then test something like the following:
> 
> ```emacs-lisp
> (let ((consult-project-root-function (lambda () "/etc")))
>   (call-interactively #'consult-ripgrep))
> ```

I tried that , still does not work, the prompt changed to `Ripgrep in /etc` but ,it still search in current directory,
And My Emacs version GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H114))

**Comment by minad** [comment]
Please try `/etc/`! See https://emacs.stackexchange.com/questions/5735/temporarily-set-the-default-directory-for-start-process

**Comment by minad** [comment]
This seems to make a difference on mac. I will push a fix for this.

**Comment by jixiuf** [comment]
this works for emacs 27.1 on macOS, but doesn't work for emacs master.

**Comment by minad** [comment]
@jixiuf can you debug this? This is probably a mac specific upstream bug. Not the fault of consult.

**Comment by jixiuf** [comment]
this can be reproduced with
```
(pcase-let ((`(,default-directory) '( "/tmp/")))
    (call-interactively 'find-file)) ; doesn't change default-directory to "/tmp/"
```


```
(pcase-let ((`(,default-directory) '( "/tmp/")))
    (message default-directory) ;with this line the default-directory change to "/tmp/", don't not why
    (call-interactively 'find-file))
```

**Comment by minad** [comment]
@jixiuf seems like a pcase optimization bug. Can you report this upstream via emacs-report-bug?

**Comment by jixiuf** [comment]
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45619

**Comment by minad** [comment]
I decided to reopen this until it has been fixed upstream or until it is clear if I should do anything here.

**Comment by liebkne** [comment]
This may not be related, but it is about `pcase`. I got 

```
Redundant pcase pattern: `(,name ,pos ,fn \, args)
```

on 

```
GNU Emacs 27.1 (build 1, x86_64-apple-darwin20.1.0, Carbon Version 164 AppKit 2022.1) of 2020-11-15
```

when evaluating `consult.el`.

Also nothing happens when typing in `consult-ripgrep`

<img width="307" alt="Screen Shot 2021-01-04 at 9 41 22 PM" src="https://user-images.githubusercontent.com/5475262/103541019-acdb8400-4ed5-11eb-9e57-3c700eebe1c1.png">

**Comment by minad** [comment]
@liebkne no, this is another bug. Will be fixed soon.

**Comment by wakira** [comment]
seems unlikely that the behavior of `pcase-let` would change upstream.

**Comment by minad** [comment]
@wakira What do you mean? There is clearly an upstream bug here in Emacs 28. The following works in 27.1 but not in 28. This is some pcase optimization bug/lexical scoping bug it seems.

~~~ elisp
(pcase-let ((`(,default-directory) '( "/tmp/")))
    (call-interactively 'find-file)) ; doesn't change default-directory to "/tmp/"

(pcase-let ((`(,default-directory) '( "/tmp/")))
    (message default-directory) ;with this line the default-directory change to "/tmp/", don't not why
    (call-interactively 'find-file))
~~~

**Comment by wakira** [comment]
@minad see message#20. Anyway I think it's easier to just ditch `pcase-let` than persuading upstream to implement what they consider a "messy" behavior

> https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45619

**Comment by minad** [comment]
@wakira I am quite sure they will fix this. But if not, I can change my code as soon as Emacs 28 is released. I will not update my code in order to work well with broken unstable versions.

**Comment by ashton314** [comment]
@wakira I know this is a kluge, but if you change `consult--grep` to this:

```elisp
(defun consult--grep (prompt cmd dir initial)
  "Run grep CMD in DIR with INITIAL input.

PROMPT is the prompt string."
  (pcase-let ((`(,prompt . ,default-directory) (consult--directory-prompt prompt dir)))
    default-directory ; Kluge: Emacs 28 is optimizing default-directory's assignment away for some reason
    (consult--with-preview-files (open)
      (consult--jump
       (consult--read
        prompt
        (consult--grep-async cmd)
        :lookup (consult--grep-marker open)
        :preview (and consult-preview-grep (consult--preview-position))
        :initial (concat consult-async-default-split initial)
        :add-history (concat consult-async-default-split (thing-at-point 'symbol))
        :require-match t
        :category 'xref-location
        :history '(:input consult--grep-history)
        :sort nil)))))
```

Then it seems to work. 🤷🏼‍♂️ changing it locally might be the best solution for the time being.

(Appologies to @minad for befouling  your beautiful code with this kluge!)

**Comment by ashton314** [comment]
But *native comp!!*

 ;-P I was running on on 27.1 for a bit until I managed to get a semi-stable build of 28 on macOS working. Looking back, I was on 28 in part for the nice minibuffer annotations. With marginalia though… I could probably switch back without an issue. 🤔

**Comment by minad** [comment]
Well, I will probably switch to 28 as soon as native-comp hits master.

**Comment by minad** [comment]
The pcase documentation: https://www.gnu.org/software/emacs/manual/html_node/elisp/pcase-Macro.html

> Matches any expval, and additionally let-binds symbol to expval, such that this binding is available to body-forms (see Dynamic Binding).
>  If symbol is part of a sequencing pattern seqpat (e.g., by using and, below), the binding is also available to the portion of seqpat following the appearance of symbol. This usage has some caveats, see caveats. 

There is a link to "Dynamic Binding". I just read through the caveats section, all well and good. No mentioning that this is not supposed to work with dynamic bindings. In particular for `pcase-let` I find it very confusing if this would not work, since ideally `pcase-let` should just work as a drop in replacement for `let` with pattern matching. And if `pcase-let` works like `let` all the other binding forms should work in the same way, e.g., `pcase-lambda` etc.
