### ISSUE TITLE
The consult-theme command breaks when previewing the doom-homage themes

### ISSUE THREAD

**Issue by SlobDad** [minad/consult#1094]
I do not know if this is a bug with the doom-themes packages or consult, so I am submitting a report to both.

When scrolling through themes using consult-theme, the doom-homage-black-theme and doom-homage-white-theme (from doom-themes package) break the preview, and it gets stuck on that theme. And at least occasionally seems to break the ability to switch themes altogether, even by using other commands to do so.
This happens at least when visiting an org-mode buffer during the preview, not sure about others.
No error messages, but some of this from *Messages* might be related:
```
QuitWarning: setting attribute ‘:background’ of face ‘outline-1’: nil value is invalid, use ‘unspecified’ instead.
Error in post-command-hook (consult--preview-post-command-hook): (error "Invalid face box" :line-width -1 :color "#5B6268" :style 'released-button)
face-spec-set-2: Invalid face box: :line-width, -1, :color, "#5B6268", :style, 'released-button
```

**Comment by minad** [comment]
These are bugs in the themes. Link to the issue there: https://github.com/doomemacs/themes/issues/839
