### ISSUE TITLE
Interaction of consult-register-format with desktop-save-mode

### ISSUE THREAD

**Issue by bhepple** [minad/consult#1095]
I had a chance to look into #1038 again today and I have narrowed it down to the line in the recommended configuration for consult:

```
(setq register-preview-function #'consult-register-format)
```

Without that setting, I can use `(desktop-save-mode)` quite happily and my registers (including window configurations eg `C-x r w 0`) are saved and re-stored as usual.

With that setting, when I restart emacs with a window configuration stored in register-alist, I'm not able to do register operations and I get the message `Error running timer: wrong-type-argument sequencep #<marker at 33459 in config.el>`. I have to disable the use of consult-register-format in order to be able to use registers again.

In short, to invoke the problem:

```
enable (desktop-save-mode)
enable the use of consult-register-format as above
save window configuration in a register C-x r w 0
exit emacs C-x C-c
re-start emacs
try to use the register C-x r j 0
```
and I don't have ido-cr* enabled:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep #<marker at 33459 in config.el>)
  mapconcat(identity ("Unprintable entity" #<marker at 33459 in config.el>) "\n")
  #f(compiled-function (val) "Describe rectangle or window-configuration register VAL." #<bytecode -0x1f5af3e9f6890e6b>)(("Unprintable entity" #<marker at 33459 in config.el>))
  apply(#f(compiled-function (val) "Describe rectangle or window-configuration register VAL." #<bytecode -0x1f5af3e9f6890e6b>) ("Unprintable entity" #<marker at 33459 in config.el>) nil)
  consult-register--describe(("Unprintable entity" #<marker at 33459 in config.el>))
  consult-register-format((48 "Unprintable entity" #<marker at 33459 in config.el>))
  #f(compiled-function (reg) #<bytecode 0xa5a461d81ae985>)((48 "Unprintable entity" #<marker at 33459 in config.el>))
  consult-register-window("*Register Preview*")
  apply(consult-register-window "*Register Preview*")
  register-preview("*Register Preview*")
  #f(compiled-function () #<bytecode 0x8fea117e270120d>)()
  apply(#f(compiled-function () #<bytecode 0x8fea117e270120d>) nil)
  timer-event-handler([t 26363 57761 987514 nil #f(compiled-function () #<bytecode 0x8fea117e270120d>) nil nil 658000 nil])
  read-key-sequence-vector(#("Jump to register: " 0 18 (face minibuffer-prompt)) nil t)
  read-key(#("Jump to register: " 0 18 (face minibuffer-prompt)))
  register-read-with-preview("Jump to register: ")
  byte-code("\301\302!\10D\207" [current-prefix-arg register-read-with-preview "Jump to register: "] 2)
  command-execute(jump-to-register)
```

**Comment by minad** [comment]
> Without that setting, I can use (desktop-save-mode) quite happily and my registers (including window configurations eg C-x r w 0) are saved and re-stored as usual.

This does not seem to be true. When I store window configurations in registers and then store the desktop file, the window configuration is stored as an invalid register, also in your case - see the `"Unprintable entity"`. This is what lead to a problem. I filter out invalid registers in https://github.com/minad/consult/commit/8f228cc1d48af9158c9ba71d2f20a9aaaf4daf7e.

**Comment by minad** [comment]
I decided to revert the commit again due to problems. It is not easily possible to filter out invalid registers in Consult, since registers can have many different formats, even user defined.

**Comment by bhepple** [comment]
I see. Thanks for your patience.

Indeed it seems there's a fundamental problem with saving window (and frame?) configurations in `savehist`, `desktop-save-mode` and `better-registers` (others ...???).

Unfortunately `consult-register-format` is vulnerable to invalid registers and the result is that the timer problem stops them being used at all. 

I will see if I can find anything else in `desktop-save-mode` - perhaps something to prevent it trying (and failing) to save window configs. There is https://debbugs.gnu.org/cgi/bugreport.cgi?bug=54140 but not quite the same. Nothing else seems on the money, so maybe I'll raise it there. 

Meanwhile I have the workaround not to use `consult-register-format`.

**Comment by minad** [comment]
Thanks for reporting this upstream. https://debbugs.gnu.org/cgi/bugreport.cgi?bug=73593
