### ISSUE TITLE
Generate texi file from readme

### ISSUE THREAD

**Issue by minad** [minad/consult#113]
Alternatives:
1. ~Maintain readme as texinfo~
2. Maintain readme as org instead and use the texinfo export

**Comment by oantolin** [comment]
Ooh, I didn't know there was an info exporter for Org. I'll use it for my packages: they all have Org readmes.

**Comment by minad** [comment]
I've not found melpa documentation for this but it seems if you put texi files in the repository they will be installed automatically.

**Comment by minad** [comment]
I added texi files to marginalia and consult. Let's see if this will work with melpa. It will probably require some tweaking of the readme.org in order to achieve the desired output.

**Comment by hmelman** [comment]
This is a good idea. Not sure if this is supposed to work yet, I updated via melpa today and the installed consult package has a .info but when I start Info I don't see it in the list of manuals.

**Comment by minad** [comment]
Maybe we should ask @purcell what is needed to make this work. Unfortunately I didn't find documentation regarding melpa info support, but maybe I missed it. I've seen texi files in other repositories however.

**Comment by okamsn** [comment]
In my experience, if you  just add the Info file to the repo, it get's installed correctly. Org has an command to export to Texinfo and make the Info file after.

I think some repos might use a Makefile to build Info files on install.

**Comment by hmelman** [comment]
I suspect you need a file named `dir` which is the info root.

**Comment by minad** [comment]
I thought a texi file is enough. I use the org texinfo export. And since @hmelman already found some info file it seems to work at least partially with the texi file.

**Comment by hmelman** [comment]
I think I was misunderstood.  See the elisp manual "Multi-file Packages" node.  The consult manual should be in an .info file, you have that.  To have it automatically installed you need another file at the same level, (oddly) named "dir" which is an Info directory, which is not a directory on the file  system but a file that Info uses to present the top level list of manuals.  The consult "dir" file needs some boiler plate at the top and the one menu line to be displayed in the Info top level menu (aka "Info directory").  That seems to be what ivy has.

**Comment by minad** [comment]
I don't understand, I am sorry. Swiper has a doc directory with a texi file. That's all I've seen. I see no dir file and no info file.

**Comment by hmelman** [comment]
Yes, I see what you describe browsing the swiper github repository.  I was describing seeing what is installed in my ~/.emacs.d/elpa/ after installing them.  There's and ivy.info and dir file in the ivy package the other two don't have the equivalents. I suspect the repository's doc/Makefile is doing the work here.  I think for a simple package you just need a dir file.

**Comment by hmelman** [comment]
Your `dir` file needs a line something like this:

    * Consult: (consult).                   Consult commands for better completion.

**Comment by hmelman** [comment]
The `ivy.info` file contains this, which is probably relevant.  I'm not sure what part of their build stuff extracts this to a `dir` file.

    @dircategory Emacs
    @direntry
    * Ivy: (ivy).           Using Ivy for completion.
    @end direntry

**Comment by minad** [comment]
@hmelman I added some pragmas to the org file and regenerated the texi. Let's hope that it works now :)

**Comment by hmelman** [comment]
Worked!

**Comment by minad** [comment]
Great! Now I guess the README.org needs some tweaks in order to result in a nice info file. Maybe some conditional disabling of sections...
