### ISSUE TITLE
Maybe remove default of current line from consult-line?

### ISSUE THREAD

**Issue by oantolin** [minad/consult#114]
It seems to me that having the current line as the first element of the future history in `consult-line` isn't super useful. To search for the symbol at point you currently have to press `M-n` twice. If you just remove `:default (car candidates)`, searching for the symbol at point takes only one `M-n`. But I'm not sure about the ramifications of removing the default, is it a bad idea?

**Comment by minad** [comment]
If we set a default then selectrum highlights the current line in the list of candidates. Maybe this is not very useful? But maybe people expect this? If I remove the default, I could also remove :default-top from the selectrum support and simplify how the line candidates are generated. From that perspective it would make sense to remove it. What is the behavior of swiper, just for reference?

**Comment by minad** [comment]
Swiper also seems to use the current line as default/preselect. Another option to mitigate the issue with symbol-at-point would be to remove :default from the :add-history list. See here: https://github.com/minad/consult/blob/1394d43289804bb05643fbb40581492c32de6a14/consult.el#L811-L813 Adding :default to :add-history is due to a proposal by @hmelman, see #96.

**Comment by oantolin** [comment]
Mmh, both things sound reasonable: (1) highlighting the current line (I think Swiper also does that, but it's been too long and I don't really remember), (2) having the default be the first element of the future history. But I don't like pressing `M-n` for the symbol at point. 😆 It's not clear what to do.

**Comment by oantolin** [comment]
Maybe having the default as the first element of the future history is the thing that should change. I don't think that's how completing-read usually works, is it? I think you get an empty future history even if you have a default. The default is used if the user presses `RET` with the minibuffer-contents empty.

**Comment by minad** [comment]
I am not sure. @hmelman thought it is useful since it allows to edit the default. I am not sure. Before #96 I didn't know about "future history"...

**Comment by oantolin** [comment]
Ah, the behavior of the default with respect to future history differs by completion UI: if you use the `DEF` argument of `completing-read`, under both default completion and icomplete `M-n` inserts that, even if it is not a member of `COLLECTION`! But under Selectrum `M-n` seems to put in the first candidate independently of whether you give a `DEF` or not and of whether it belongs to the collection or not.

By the way, I now have Selectrum installed and configured and I have a little command to choose a completion UI between Default, Icomplete, Embark Live Occur and Selectrum, so I can test in all four very simply. I should have done that a long time ago! There are all these cases where Selectrum does something "weird" (not really weird, but not standard, i.e., not what default tab completion or icomplete do --those two usually behave the same), and I didn't know what you Selectrum people were talking about. 😄

**Comment by minad** [comment]
I am also using such a toggler for icomplete-vertical and selectrum. Maybe I should add embark live occurr too!

**Comment by oantolin** [comment]
> I am not sure. @hmelman thought it is useful since it allows to edit the default. I am not sure. Before #96 I didn't know about "future history"...

He's right! It is useful and that is the reason: it lets you edit the default. It's just that in the case of `consult-line` edit the current line is not useful.

**Comment by minad** [comment]
Ok, so what shall we do? Remove it from the add-history. And add it where it is useful manually?

**Comment by oantolin** [comment]
I'd have to survey the defaults in consult, but it is possible that it's almost always useful to have it in add-history, in which case it would be annoying to remove it from there and add it manually almost every time...

**Comment by oantolin** [comment]
Also, pressing `M-n` twice is not really that bad. I'm not sure what should be done.

**Comment by oantolin** [comment]
Mmh, why is the implementation of `:add-history` so complicated, setting `minibuffer-default-add-function`? Can't you just call `completing-read` with a list as the `DEF` parameter?

**Comment by oantolin** [comment]
Ah, the simple implementation wouldn't work in Selectrum, right?

**Comment by minad** [comment]
No, lists as defaults does not work in icomplete either.

**Comment by minad** [comment]
There are not many defaults, so we could as well do it manually.

**Comment by oantolin** [comment]
It seems to work both in icomplete and default tab completion. I evaluated:

```elisp
(completing-read "Go: " '("a" "b" "c") nil nil nil nil '("d" "e"))
```

The first `M-n` inserts `d`, the second `M-n` inserts `e`, the third inserts `a`.

**Comment by hmelman** [comment]
I'm not sure I follow the nuances being described.  FWIW I came from ivy and wasn't a swiper user and now use selectrum but haven't use the others.  I like the paradigm of having a blank input and getting stuff at point via M-n, allowing editing.  My sense is if there are commands that want to do that faster they are commands that are named FOO-at-point, and that's fine.  

If we're only talking a different default for consult-line I could see that.  I'm not sure I see the benefit of it having an initial of the current line.

**Comment by oantolin** [comment]
> There are not many defaults, so we could as well do it manually.

That's a good option. The other viable option I see is removing the default for `consult-line`.

> If we're only talking a different default for consult-line I could see that. I'm not sure I see the benefit of it having an initial of the current line.

I think the only benefit is having Selectrum highlight the current line, @hmelman. That is a pretty nice benefit for Selectrum users, though.

**Comment by minad** [comment]
Well, I think first thing would then be to fix the default lists in selectrum. Then consult could remove add-history. But this would not fix this issue, @oantolin? We would always get the default then via M-n, but the behavior is at least consistent.

**Comment by minad** [comment]
> Well, I think first thing would then be to fix the default lists in selectrum. Then consult could remove add-history. But this would not fix this issue, @oantolin? We would always get the default then via M-n, but the behavior is at least consistent.

I am going forward with this - it is the only reasonable thing to do.

**Comment by hmelman** [comment]
> I think the only benefit is having Selectrum highlight the current line, @hmelman. That is a pretty nice benefit for Selectrum users, though.

Is that benefit you can use C-n/C-p to navigate to a nearby line?  If the point is to goto other lines, why is it nice to start with the current line?  So far my use consult-line has been to filter down lines with symbol like "defun", so I don't get see the benefit yet.

**Comment by oantolin** [comment]
> Is that benefit you can use C-n/C-p to navigate to a nearby line? If the point is to goto other lines, why is it nice to start with the current line? So far my use consult-line has been to filter down lines with symbol like "defun", so I don't get see the benefit yet.

This is a good point! How about this, @minad:

1. Keep the behavior of adding the default to future history.
2. Make the symbol at point the default for `current-line`.
3. Independently carry out your plan to change Selectrum for list-valued defaults, once that is finished, remove `:add-history` from Consult, and switch to list-valued defaults.

**Comment by oantolin** [comment]
Of course we should also double-check that list-valued defaults do what we want in icomplete, I seem to think they do and you, @minad, seemed to think they didn't.

**Comment by minad** [comment]
> Keep the behavior of adding the default to future history.

No, I guess this is fixed if we make it a list, right?

> Make the symbol at point the default for current-line.

No, in order to get this use a wrapper with initial set to the symbol at point.

> Independently carry out your plan to change Selectrum for list-valued defaults, once that is finished, remove :add-history from Consult, and switch to list-valued defaults.

No, I will remove it now and I will open an issue on the selectrum tracker.

:grin: 

> Of course we should also double-check that list-valued defaults do what we want in icomplete, I seem to think they do and you, @minad, seemed to think they didn't.

I am not familar with icomplete. I used ido forever and recently switched to selectrum. I just rechecked and it seems correct what you said. Also the read-from-minibuffer docs say so.

**Comment by oantolin** [comment]
😆 OK. I don't think I need a wrapper, I can live with `M-n M-n`.

**Comment by oantolin** [comment]
😆 OK. Sounds like nice consistent behavior. So the plane is that eventually `M-x consult-line RET M-n M-n` would again search for the symbol at point in Selectrum, right?

**Comment by minad** [comment]
There is one problem though - if we use the default to overwrite the history we lose quite a bit of flexibility. For example consult-outline uses the symbol at point for the history. But I don't want it as default - it also wouldn't work since it violates require-match.

So maybe I should take back my three No! And we do the following:

* Keep add-history
* Remove default from add-history (do not add it automatically by default)
* Manually add default to add-history where we want it

**Comment by minad** [comment]
So I think now my verdict is rather that using lists as default is bad and shouldn't be used. All these type errors everywhere.

Having a nice and clean separate add-history is better!

**Comment by oantolin** [comment]
I'll post a quick list of Consult commands that use `:default` or `:add-history` in a minute. There aren't many.

😆 Strongly typed Emacs for the win. (Although, I'm enjoying using embark-become and embark-occur as actions... 🤷)

**Comment by minad** [comment]
> (Although, I'm enjoying using embark-become and embark-occur as actions... shrug)

As I argued this is all nice and sound in the IO monad :stuck_out_tongue_closed_eyes:

**Comment by hmelman** [comment]
IIUC, `selectrum-completing-read` doesn't behave the same as `completing-read` wrt defaults and initial and future history and it probably should.  If there's a good argument for it not to, I'd like to understand that, otherwise it seems to me to be a selectrum bug?

From my (limited) experience it's rare but allowed for future history to have more than one value.  So I could see an argument for optimizing the api for that.

**Comment by oantolin** [comment]
Here's a survey of commands in consult with either `:default` or `:add-history`:

| Command                 | Default             | Add History                     |
|-------------------------|---------------------|---------------------------------|
| consult-outline         |                     | symbol at point                 |
| consult-line            | current line        | symbol at point, isearch string |
| consult-apropos         | symbol at point     |                                 |
| consult-complex-command | first history item  |                                 |
| consult-theme           | first enabled theme |                                 |
| consult-imenu           |                     | symbol at point                 |
| consult-*grep           |                     | symbol at point                 |
| consult-{fd,find}       |                     | symbol at point                 |

**Comment by minad** [comment]
> IIUC, selectrum-completing-read doesn't behave the same as completing-read wrt defaults and initial and future history and it probably should. If there's a good argument for it not to, I'd like to understand that, otherwise it seems to me to be a selectrum bug?

Yes, it is a selectrum bug. But from my perspective here, I don't intend to use this particular aspect of the API so I don't feel strongly about this. But we should open an issue nevertheless.

**Comment by oantolin** [comment]
So I think if you go with the "don't automatically add default to future history plan", the only places that would need manual intervention would be:

- `consult-apropos`: put in symbol at point in `:add-history`
- `consult-theme`: put all of `custom-enabled-themes` (not just the `car`) in `:add-history`

Everything else can stay the same, no?

**Comment by minad** [comment]
> consult-theme: put all of custom-enabled-themes (not just the car) in :add-history

What would be the purpose of that?

**Comment by oantolin** [comment]
> > consult-theme: put all of custom-enabled-themes (not just the car) in :add-history
 
> What would be the purpose of that?

Ah, sorry. I thought `consult-theme` toggled themes but it doesn't, it disables *all* themes and enables one. Now that I know that, I think probably only `(car custom-enabled-themes)` should be in `:add-history`.

**Comment by hmelman** [comment]
As I understand it, the general emacs paradigm seems to be, when you invoke a command it's ready for you to type your input.  Even if there is initial input, it tends be prefix and it's ready for you to type your input.  grep is a good example.  There's stuff there, but you're still supposed to input your pattern and if you want you can edit the initial prefix.   Otherwise without initial, the input is blank and if you hit RET the default is used.  That's what happens with vanilla `switch-to-buffer` where the default is mru but you can type to select any.  If you want to see or edit the default you hit M-n.  Nicer completion systems than vanilla show other candidates and highlight the default but the input is left blank. The idea is you don't have to delete the initial to use something else.  Other *-at-point or *-dwim commands assume an initial input and just run but don't give you chance to edit it.

I like this behavior.  I care less about what api is used to achieve it but would think if it could be the same one used by `completing-read` that would be ideal.
