### ISSUE TITLE
Setting scroll-margin to something greater than 0 obscures first saved register binding 

### ISSUE THREAD

**Issue by alternateved** [minad/consult#1144]
Hello!

I have noticed that below configuration would obscure first saved register binding:
```lisp
(require 'package)
(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))

(setopt scroll-margin 2)

(use-package consult
  :ensure t
  :bind ("M-'" . consult-register-store)
  :custom (register-preview-function #'consult-register-format))
```

I'm not sure if this is trivial to fix or if the only solution would be to not set scroll-margin to anything other than 0. Default register preview seems to handle that case well.

**Comment by minad** [comment]
I fixed this for `consult-register-window`. It only works if you use the advice though.

**Comment by alternateved** [comment]
Thank you, that works well.
