### ISSUE TITLE
Setting consult-async-min-input to 0 doesn't work

### ISSUE THREAD

**Issue by lrustand** [minad/consult#1149]
As the title says, setting `consult-async-min-input` to 0 does not actually work as described. Even though I set it to 0 the effective minimum input is 1, not 0. I still have to enter at least one character before any results are shown.

**Comment by minad** [comment]
Thanks, I clarified this in the documentation. An asynchronous process is only started if there is at least a single character input.

**Comment by minad** [comment]
I wonder what you are using Consult for if you want empty input. All existing Consult commands start some search and require input. If they would start immediately with empty input, Emacs would immediately go to its knees. `consult-ripgrep` would spit out all the lines of all files,  `consult-line-multi` would spit out all the lines of all buffers and so on.

**Comment by lrustand** [comment]
Why did you close this? The problem is not fixed.

> I wonder what you are using Consult for if you want empty input. All existing Consult commands start some search and require input. If they would start immediately with empty input, Emacs would immediately go to its knees. consult-ripgrep would spit out all the lines of all files, consult-line-multi would spit out all the lines of all buffers and so on.

It is for a custom source I'm making. It looks very sad when it comes up empty, and the source itself does produce useful candidates with no input, so I would like to populate the candidates list. This also lets me see which candidates are at the top of the list without guessing on some input first to see them. I understand that several (most?) of the existing consult commands probably wouldn't like it though

**Comment by minad** [comment]
> Why did you close this? The problem is not fixed.

Because there is no bug. Consult has always worked like this. Empty input is not supported.

> It is for a custom source I'm making. It looks very sad when it comes up empty, and the source itself does produce useful candidates with no input, so I would like to populate the candidates list. 

I see. But if the completion command can provide candidates for empty input, it shouldn't be an asynchronous command in the first place? I assume that you want to combine partially static and partially dynamic candidates. This relates to https://github.com/minad/consult/discussions/1148.

**Comment by lrustand** [comment]
> I see. But if the completion command can provide candidates for empty input, it shouldn't be an asynchronous command in the first place? I assume that you want to combine partially static and partially dynamic candidates. This relates to #1148.

No, it can't be a static source because it is fetching results from a sqlite database that can be 500+ mb. It is not a good idea to fetch the whole database first and then do the filtering afterwards. It always shows just a small number of entries from the database, and updates which entries to show based on user input.

> Because there is no bug. Consult has always worked like this. Empty input is not supported.

That is a weird way of defining a bug. Just because it has always been like this doesn't mean it is not a bug or shouldn't be fixed.

**Comment by minad** [comment]
> No, it can't be a static source because it is fetching results from a sqlite database that can be 500+ mb. It is not a good idea to fetch the whole database first and then do the filtering afterwards. It always shows just a small number of entries from the database, and updates which entries to show based on user input.

Hmm, this is the scenario I had assumed. Basically a mix of multiple dynamic or static scenarios. The static part is the one which can be obtained quickly and immediately. Unfortunately Consult doesn't support mixing such different source types yet. This may happen in the future.

> That is a weird way of defining a bug. Just because it has always been like this doesn't mean it is not a bug or shouldn't be fixed.

All Consult commands require input, so limitations on the input had always been in place. But in principle I am okay with lifting this, if it can be done without breaking existing functionality.

**Comment by lrustand** [comment]
> All Consult commands require input, so limitations on the input had always been in place. But in principle I am okay with lifting this, if it can be done without breaking existing functionality.

A non-invasive way of doing this could be to add a new option to consult--read or consult--dynamic-collection?

**Comment by minad** [comment]
I've implemented support for empty async input. Hopefully the change doesn't break other packages. This change may also help when mixed async/static sources may get implemented at some point.

**Comment by lrustand** [comment]
That's great, thanks!
