### ISSUE TITLE
Allow adjustments to async process arguments

### ISSUE THREAD

**Issue by minad** [minad/consult#115]
Original comment by @gagbo in #91 

> I think I’m just missing a way to pass rg command line arguments, but I guess that’s just something to handle in the processing of  the async-part.

> For example, I might want to pass a flag to search with/without case-sensitivity, in hidden files, or only searching in files matching a certain type/extension.

> I’ll try to see how I can make it work when it comes up again in my daily usage

**Comment by minad** [comment]
`consult--async-process` already takes a function as argument to compute the command line parameters. However `consult--grep-async` and `consult--find-async` take lists as of now. If we change this such that they also take functions, we would ensure that the arguments are always reevaluated. If we overwrite the arguments, e.g., consult--grep-command, via setq-local in the minibuffer via some command bound in the minibuffer keymap, we would allow changes of command line flags.

~~~ elisp
(defun grep-case-sensitive ()
   (interactive)
   (setq-local consult--grep-command ...) ;; this would work with reevaluation of command arguments
   ;; this does not exist yet, we need some way to access the current async function
   ;; alternative enforce the refresh in the post-command-hook
   (consult--async-refresh))
~~~

**Comment by gagbo** [comment]
[Ivy](https://github.com/abo-abo/swiper/blob/d2891aab7b816aebf21ebd01ce33933a6ac6244f/counsel.el#L3186) does a split on `--` and passes the command arguments as `extra-rg-args` (to be honest the code is not 100% clear to me, that’s just what I understand from using it and looking at the source code, but I don’t see the actual split there, even if it’s mentioned in the docstring)

So maybe it could only be a matter of generalizing the split logic (that currently uses comma) and split the `async-filter` part on `--` in the function that would be built for `consult--grep-async`

**Comment by minad** [comment]
@gagbo that could also be a possibility. What I had in mind goes in the direction of hiding the exact flags and making some toggles a available. Do you prefer passing the flags? The split could be performed in the lambdas in consult--grep-async for example.

**Comment by minad** [comment]
@gagbo Is this what you had in mind? I think it works quite well. The syntax is a bit heavy, but this is a special use case, so it won't hurt too much.

Example: `#defun -- -v#`

**Comment by gagbo** [comment]
> Example: `#defun -- -v#`

Yes that’s what I had in mind basically, something along the lines of `important_function -- -g ’*.{c,h}’, folder2`, to be able to quickly look at `important_function` uses only in implementation and header files of a C project, and then be able to filter the results by folder in my selectrum prompt

**Comment by minad** [comment]
@gagbo Please try it and let me know if it works as you expect!
