### ISSUE TITLE
consult-org-heading and consult-outline doesn't unfold and highlight 

### ISSUE THREAD

**Issue by ArchGalileu** [minad/consult#1153]
Hello,

I can't manage to solve the unfold, reveal, of and heading after consult-org-heading or consult-outline

Any advice

Best regards

**Comment by minad** [comment]
See https://github.com/minad/consult/commit/eb26bdd008c4c92b1d79e49e2df71acc2a42faa3. Just set `org-fold-core-style` to `overlays` before loading Org.
