### ISSUE TITLE
Customizable consult-line preview jump behavior

### ISSUE THREAD

**Issue by walseb** [minad/consult#117]
Currently when using `consult-line` with `consult-preview-mode` it recenters the screen on the selected line regardless of the previous position of the screen. This, atleast for me leads to pretty choppy movements when looking at a bunch of search candidates in close proximity as I have to think about where the preview threw me now in relation to where it was last time.`swiper` has a behavior much closer to `isearch` which to me works a lot better, where it only moves the screen if the selected line is outside of the screen. This could probably just be fixed by not touching the screen and just moving the cursor to the selected line and letting emacs deal with the screen movements, however it wouldn't hurt to make this customizable with a variable containing a function like this: `(lambda (selected-line) (goto-line selected-line))`. Maybe this isn't how the preview works though?

**Comment by minad** [comment]
Did you try to set the `consult-after-jump-hook` to something else? Maybe disable it completely? Right now it uses `recenter` by default.

**Comment by minad** [comment]
@walseb I guess this can be closed. Please let me know if setting the hook works for you!

**Comment by walseb** [comment]
> Did you try to set the `consult-after-jump-hook` to something else? Maybe disable it completely? Right now it uses `recenter` by default.

Ah thanks! That solves my problem
