### ISSUE TITLE
Allow using non-punctuation characters as initial separators

### ISSUE THREAD

**Issue by antifuchs** [minad/consult#118]
I've got some really difficult-to-shake finger memory from using space (` `) to separate bits in file names that I'd love to carry over to `consult-fdfind`. Would it make sense to have a user-provided `consult-async-split-string` variable that does the string-splitting based on a rule that a user could provide?

**Comment by minad** [comment]
@antifuchs We could offer a configurable split function if there is no large increase in complexity (PR welcome). But I would prefer to not supply different splitting functions out of the box. The perl style regexp splitting avoids escaping issues. You can use /grep-regexp/filter-string or #grep-regexp#filter-string. See #100 for the escaping discussion.

**Comment by minad** [comment]
But note that space won't work well, since we also split at " -- " for grep arguments. See #115. So maybe it really doesn't make sense to provide an an option to configure this.

Many punctuation characters are very easy to reach on standard keyboard layouts, and the initial character is automatically entered so I don't see a large win here tbh.

This is probably a bit disappointing for someone coming over from another ecosystem, but the goal is not to replicate things exactly. From my experience it is pretty easy to retrain muscles for minor things like this. We are not talking about an evil emacs keybinding switch ;)

**Comment by antifuchs** [comment]
Hm, hm, hm, I see what you mean. Maybe I'm running into a tension between in-band and out-of-band signaling here: I personally prefer having an out-of-band way to tell the system that I want to have it match another way / show me different kinds of matches.

This thought actually makes me wonder if what we're doing here is like narrowing in a way: Staying with the example of fdfind: First I'm telling it to list all things matching a string. Then, narrowing down the results given in the first bit.

**Comment by minad** [comment]
Yes, it is all a single search string, a single narrowing giving you the power of both grep and the Emacs filtering at once. There has been a very long discussion in #91 and #100. I am happy with the design, but there has been some disagreement about it, e.g., by @hmelman. But we didn't find a better design- For users familiar with Perl/Ruby, the syntax should also look very familiar.

**Comment by minad** [comment]
@antifuchs I decided to close this. But please feel free to experiment and propose a PR if you find a solution which works better for you and which may makes sense to have here! From my perspective, we are in some kind of local optimum which is hard to improve upon without significant costs - the alternatives we discussed in #91 and #100 were all more complicated on both the UI side and the code side.

**Comment by antifuchs** [comment]
Thanks for the thoughtful replies! I'll take a look at the preceding discussion & see where I can take this (:

**Comment by minad** [comment]
@antifuchs Please do! I am always interested in input!

**Comment by jixiuf** [comment]
```
(defun vmacs-minibuffer-space ()
  (interactive)
  (if (and (string-prefix-p consult-async-default-split (minibuffer-contents))
           (= 2 (length (split-string (minibuffer-contents) consult-async-default-split))))
      (insert consult-async-default-split)
    (insert " ")))

(define-key icomplete-minibuffer-map (kbd "SPC") 'vmacs-minibuffer-space)
```

**Comment by minad** [comment]
@jixiuf Note that this binding will conflict with the space key bound for narrowing in Consult. But the solution would certainly work! Another option would be to fset/advice the consult--async-split-string function.
