### ISSUE TITLE
consult-ripgrep set initial directory

### ISSUE THREAD

**Issue by mclearc** [minad/consult#120]
I use a wrapper around a rg function to search through my setup files. Here's a version I use for consult (slightly modifed from helm)

```
(defun cpm/search-setup-config-files ()
  "use ripgrep to search all config files"
  (interactive)
  (consult-ripgrep cpm-setup-dir))
```

Unfortunately, this doesn't work as expected. It searches in the buffer's home directory rather than the specified directory for the function---i.e. the dir set in `cpm-setup-dir`. Perhaps this is something wrong with my function, but it might also be a bug.

**Comment by minad** [comment]
Please check if #108 applies to you. Mac? Emacs28?

**Comment by minad** [comment]
In particular this: https://github.com/minad/consult/issues/108#issuecomment-753571335

**Comment by mclearc** [comment]
Yes -- MacOS and emacs 28.

this seems to work as expected: 

```
(defun cpm/search-setup-config-files ()
  "use ripgrep to search all config files"
  (interactive)
  (let ((default-directory cpm-setup-dir))
    (consult-ripgrep)))
```

**Comment by minad** [comment]
Yes, okay. So that's a known issue. Emacs 28 is broken. I can either fix this now or fix it after a broken Emacs 28 has been released (I hope not). 

I wonder why so many people are using an unstable Emacs version. Emacs 27.1 is not that old and outdated and I don't see benefits in using Emacs 28 yet. I will probably switch when gccemacs hits master since then I would have a strong incentive.

**Comment by minad** [comment]
I mean there is certainly a reason to use Emacs 28 - for example if you contribute upstream or want to contribute testing/bug reports. But I am also using Emacs, not only making packages and elisp fiddling. So I need something solid...

**Comment by mclearc** [comment]
re: emacs 28. I largely agree about the problems that come with using developing software. In my case I had consistent freeze problems with emacs 27 and emacs 29 has been largely bug free. But I should have indicated that version first. In some ways this is an indication of how stable it has been for me that I forgot to think of that as a root problem! Thanks again for the quick response.

**Comment by minad** [comment]
Okay! Thank you for the response. I guess on mac there are some ready made builds available for 28 which lead to a more widespread distribution of nightlies. In particular if there are stability issues with the currently "stable" version. Or it is in homebrew. For debian there is a repository, but generally on Linux it means compiling the stuff myself.

**Comment by mclearc** [comment]
Yeah I use https://github.com/d12frosted/homebrew-emacs-plus or sometimes https://github.com/daviderestivo/homebrew-emacs-head, both of which allow easily built emacs 28 via homebrew.
