### ISSUE TITLE
consult-ripgrep + embark occur: jump to match does not work

### ISSUE THREAD

**Issue by mpenet** [minad/consult#122]
Hi, 

I am giving a try to counsult-ripgrep this morning, first of all hats off, it's quite smooth! 

When I use embark-occur on the results it does show all the matches on a separate buffer, but when I try to RET on a result it doesn't navigate to it. If I act on one of the candidates once (in the embark buffer) it then works for all candidates. Seems like something lazy under the hood might be preventiing use the first time on a embark-occur buffer. 

/cc @oantolin 

you can see my conf here : https://github.com/mpenet/emax/blob/master/init.el#L327-L362
I just added `("C-x C-g" . consult-ripgrep)` and removed counsel-rg binding.

**Comment by minad** [comment]
Thanks. This was an embark issue https://github.com/oantolin/embark/issues/80. Then there is also https://github.com/oantolin/embark/issues/79. If the issue persists, please open an issue on the embark tracker!

**Comment by oantolin** [comment]
As @minad did, this is supposed to be fixed now, so if it persists after updating Embark, please file an issue.

Also, just to publicize it: you might prefer to use embark-export with consult-ripgrep, instead of embark-occur. Export attempts to give you a type specific buffer for the things you are working with. In the case of consult-ripgrep, it gives you a grep-mode buffer. Not only can you press RET to navigate to a result there, but you can use next-error and previous-error to jump among the results, and if you have the wgrep package you can even edit them in place.

**Comment by minad** [comment]
Why do we have the export/occur distinction after all? I guess there are some cases where you want the raw form. But generally it seems better to me to always use export by default. Is there also live-export or is that impossible?

**Comment by oantolin** [comment]
Oh, and @mpenet, I took a look at your configuration and your Selectrum/Embark integration needs to be updated for the latest Embark version. You can find an up to date version on the Selectrum wiki.

**Comment by minad** [comment]
Basically raw/export is just another parameter of the embark buffer, together with live/snapshot and ephemeral/persistent.

**Comment by mpenet** [comment]
thanks for the crazy quick feedback, I ll have a look at all this :)

**Comment by oantolin** [comment]
> Why do we have the export/occur distinction after all? I guess there are some cases where you want the raw form.

Well, they just are distinct. For one thing, calling occur for consult-buffer gives you a mixed type buffer listing files, buffers and bookmarks together, giving you the correct actions for each entry. Export by its nature only works for homogenous collections. 

Plus, and this is maybe a little silly, but occur had grid and zebra views.

> But generally it seems better to me to always use export by default.

Then use export! Problem solved! :)

I like grid view for files and buffers, so I do sometimes use occur over export even though dired and ibuffer are great.

> Is there also live-export or is that impossible?

There's isn't any yet. It's not impossible, but I kind of think a live updating dired buffer would feel weird.

**Comment by mpenet** [comment]
There is one difference I notice between -occur and -export, the later opens candidates in the same window for ripgrep while -occur was opening in in "other" (or something, basically the side window for me).

**Comment by oantolin** [comment]
Also the export buffers just look different l from one another. I wouldn't want that inconsistency in my completion UI.

But if you don't use Embark occur as your completion UI, it might make more sense to always use export. There's not a lot of exporters: it does fallback to occur almost always. There's just dired, ibuffer, grep-mode and package-list-mode. I'm always on the look out for more sensible exporter opportunities, please let me know of you notice any.

**Comment by oantolin** [comment]
> There is one difference I notice between -occur and -export, the later opens candidates in the same window for ripgrep while -occur was opening in in "other" (or something, basically the side window for me).
> Other than that export is perfect.

Oh, I didn't realized they differed that way. I would assume what export is doing is standard behavior for grep mode.
