### ISSUE TITLE
Customizable find/grep command variables

### ISSUE THREAD

**Issue by protesilaos** [minad/consult#123]
Hello Daniel!

I was just trying `consult-fdfind` and noticed that the name of the executable is set to `fdfind`.  On my system that executable does not exist, whereas Bash's `command -v fd` returns `/usr/bin/fd`.

Could it be possible to add a `defcustom` for the name of the executable?  Then tweak `(defvar consult--fdfind-cmd '("fdfind" "--color=never" "--full-path"))` to use that?

Also, what do you think about customising the flags for fd?

Thanks again for your contributions!

**Comment by minad** [comment]
Yes, we should make these variables customizable at some point. I haven't done that yet since I don't want to make everything public right away until it is more stabilized. See also #119.

On my system the executable is called fdfind and I prefer to use the longer names, like ripgrep. Furthermore the name fd is really a problematic one from my perspective, there is floppy disc, there is file descriptor... Therefore the longer variant.

**Comment by minad** [comment]
@protesilaos I also considered removing consult-fdfind due to the naming/configuration nprobkem. You can always write your own consult-fdfind by wrapping consult-find and setting the consult--find-command in a let. What is your opinion about this?

For me fd doesn't really cut it. The name is not standardized, it has some other issues. This is in contrast to ripgrep which really has big advantages for me.

**Comment by protesilaos** [comment]
> You can always write your own consult-fdfind by wrapping consult-find and setting the consult--find-command in a let. What is your opinion about this?

That is fine by me.  I just thought I would bring this issue to your attention.

**Comment by minad** [comment]
I removed consult-fdfind now and added an ecample tonthe readme.

**Comment by protesilaos** [comment]
Thank you!  I ended up writing this wrapper, which seems to work as intended:

```elisp
(defcustom prot-consult-fd-flags '("fd" "-i" "-H" "-a" "-c" "never") ...)

...

;;;###autoload
(defun prot-consult-fd-find-file (&optional arg)
  "Use `consult--find' to search for files using the FD executable.

The search is performed against the root of the current version
controlled project or, if none is available, from inside the
`default-directory'.

With optional prefix ARG (\\[universal-argument]) search for
directories instead."
  (interactive "P")
  (let* ((cmd (if arg
                  (append prot-consult-fd-flags (list "-t" "d"))
                (append prot-consult-fd-flags (list "-t" "f"))))
         (default-directory (or (vc-root-dir)
                                (locate-dominating-file "." ".git")
                                default-directory))
         (prompt (format "Find in %s: " (propertize default-directory 'face 'bold))))
    (consult--find prompt cmd)))
```

**Comment by minad** [comment]
@protesilaos Great! Note that you can also overwrite consult-project-root-function. I would recommend that over setting the default-directory here!

**Comment by minad** [comment]
And one more - it is a good idea to use the prefix argument for tweaking. I like that. The consult commands use the prefix args for the directory by default. Just letting you know - there is also the possibility to pass arguments to find/grep.

#filename -- -t f#filter

**Comment by protesilaos** [comment]
> Note that you can also overwrite consult-project-root-function. I would recommend that over setting the default-directory here!

I see.  Still need to familiarise myself with a large part of what Consult offers.  There is always something else I need to do and find little time to properly study this one.  It will happen eventually.

> Just letting you know - there is also the possibility to pass arguments to find/grep. [...]

Yes, that is cool!

**Comment by minad** [comment]
I just checked - in my config I only set those things:

* consult-project-root-function for consult-buffer/grep/find
* consult-narrow-key to <
* comsult-view-*-functions for views in consult-buffer
* And the keybindings obviously

That's all and should give the most benefit in terms of customization.

**Comment by protesilaos** [comment]
> I just checked - in my config I only set these things:
> + consult-project-root-function for consult-buffer/grep/find

Do you have any pro tips for that one?  Is what I did okay?

```elisp
(or (vc-root-dir)
    (locate-dominating-file "." ".git")
    default-directory)
```

> That's all and should give the most benefit in terms of customization.

Do you happen to have any hints about setting up orderless for some Consult commands?  For example, I prefer a flex style by default, but for `consult-{outline,imenu}` I would prioritise literal strings.  No need to share code---just if you happen to know of some docs I could read.  If not, no worries: I will find it.

**Comment by inigoserna** [comment]
My version if you need some inspiration:

``` emacs-lisp
  (defun isr/consult--guess-initial-dir (&optional askdir)
    "Returns root directory for use in `consult' searching functions.
    If ASKDIR is not `nil' prompt the user for the inital directory,
    else use simple logic: first try `project', then `projectile',
    and defaults to `default-directory'."
    (expand-file-name
     (if askdir
         (read-directory-name "Initial directory: ")
       (cond
        ((and (fboundp 'project-current) (project-current))
         (project-root (project-current)))
        ((and (fboundp 'projectile-project-root) (projectile-project-root))
         (projectile-project-root))
        (t default-directory)))))


  (setq consult-project-root-function 'isr/consult--guess-initial-dir)

  (defun isr/consult-fd (&optional dir)
    (interactive "P")
    (let ((consult-find-command '("fd" "--color=never" "-H" "--exclude='.st*'" "--exclude=.hg" "--exclude=__pycache__")))
      (consult-find dir)))
```

**Comment by minad** [comment]
@protesilaos 

The project directory expression you have looks good!

It is an interesting idea to use different orderless styles for commands (note that I overwrite the style for async commands locally). I am not sure what the best way is to achieve this. There are multiple ways. Probably @oantolin can tell much better than me!

But I think I prefer to not have different completion styles per command and rather have sth consistent.

I don't use flex by default since it is slow and matches too match for my taste. I have an additional orderless style dispatcher.

* ~ suffix for flex
* = suffix for literal
* ! prefix for without literal (@oantolin just added that recently at my request)

**Comment by minad** [comment]
@inigoserna note that you can get rid of the read-directory in your project root function. This feature is build already into the consult--directory-prompt helpers

**Comment by inigoserna** [comment]
> @inigoserna note that you can get rid of the read-directory in your project root function. This feature is build already into the consult--directory-prompt helpers

Yup, thanks. I need to update my config.

**Comment by protesilaos** [comment]
> It is an interesting idea to use different orderless styles for commands (note that I overwrite the completion style for async commands locally). I am not sure what the best way is to achieve this.

I am not sure either, so I employed my super sophisticated technique of quick, dirty, yet effective wrappers:

```elisp
(defcustom prot-orderless-alternative-styles
  '(orderless-literal
    orderless-prefixes
    orderless-strict-leading-initialism
    orderless-regexp)
  "Alternative list for `orderless-matching-styles'.

Unlike `prot-orderless-default-styles', this variable is intended
for use on a case-by-case basis, with the help of the function
`prot-orderless-with-styles'."
  :type 'list
  :group 'prot-orderless)
  
[...]

(defun prot-orderless-with-styles (cmd &optional styles)
  "Call CMD with optional orderless STYLES.

STYLES is a list of pattern matching methods that is passed to
`orderless-matching-styles'.  Its fallback value is that of
`prot-orderless-alternative-styles'."
  (let ((orderless-matching-styles (or styles prot-orderless-alternative-styles))
        (this-command cmd))
    (call-interactively cmd)))
    
[...]

(defun prot-consult-outline ()
  "Run `consult-outline' through `prot-orderless-with-styles'."
  (interactive)
  (prot-orderless-with-styles 'consult-outline))
```
