### ISSUE TITLE
Org imenu is broken with invalid headlines

### ISSUE THREAD

**Issue by minad** [minad/consult#127]
Example:

~~~
** No toplevel
*** Sub
~~~

This reports a nil error, since the generated imenu is invalid. Report upstream org mode bug.

**Comment by oantolin** [comment]
Wow, this is crazy. I can believe this has never come up before. I also noticed yesterday that imenu does nothing in an eww buffer (there is an external package shrface that adds imenu support plus a ton of other things).

**Comment by oantolin** [comment]
> Note that this is not a consult issue, `imenu` also doesn't work.

Right, I know, that's why I said it's crazy it hasn't come up before. If it were just an issue with the extremely new `consult-imenu` command, it would be normal that it hadn't been noticed until now. 😄

**Comment by oantolin** [comment]
> But maybe I am the only one who writes broken org files?

I certainly don't do that, I would have noticed, since I've been navigating them with `imenu` for a long time. Oh, unless `flimenu` fixes the nils as a side effect? In that case it's possible I wouldn't have noticed: before `consult-imenu` I used `imenu` with `flimenu`.

**Comment by minad** [comment]
> Oh, unless flimenu fixes the nils as a side effect? In that case it's possible I wouldn't have noticed: before consult-imenu I used imenu with flimenu.

No, imenu is really broken. Or returns `'(nil)` for those broken org files. Otherwise I would obviously fixed this up somehow here.

**Comment by oantolin** [comment]
> It returns `'(nil)` for those broken org files.

😆 OK, that's definitely broken.

**Comment by minad** [comment]
Btw @oantolin, there is consult-project-imenu which merges the imenus of all files in the current project/repository of the same mode. You might like that in case you split up certain projects ;)

**Comment by minad** [comment]
This bug is org mode specific and is only triggered when the `imenu-create-index-function` is set to `org-imenu-get-tree`. This function returns nil for the invalid headlines, which is okay.

But then `imenu--make-index-alist` contains this code, which is only triggered with 'noerror.

~~~
   (or imenu--index-alist
      (setq imenu--index-alist (list nil)))
~~~

This means return a `'(nil)` is somehow intensional, but I don't understand what this means.

**Comment by minad** [comment]
I see two possible improvement proposals which could be reported upstream:

*  `org-imenu-get-tree` could be made more relaxed such that it also returns an imenu for invalid nesting
* `imenu--make-index-alist` could be modified such that it does not return `'(nil)`, but maybe there is a purpose for this behavior after all.

I am closing this since the issue is fixed on the side of Consult.
