### ISSUE TITLE
Is there a way for consult-yank-pop to turn off prescient's sorting?

### ISSUE THREAD

**Issue by hmelman** [minad/consult#129]
I'm not sure if this is a consult issue or something else, but let me describe it.   I'm using `consult` with `prescient`.  `consult-yank-pop` shows the kill ring but it is sorted by prescient and I'd prefer to see it in its natural mru order.  I believe the way to do that is to set `prescient-sort-length-enable` to `nil` for this command (usually with a let binding).  I could write my own command doing this, but is there way for consult to do it (doubtful keeping its independence) or provide a hook for me to do it with a simple configuration one-liner?

**Comment by minad** [comment]
@hmelman I think this might be a prescient issue. `consult--yank-read` already requests unsorted completiong, see `:sort nil`. This seems not to be a consult bug. For me, the kill ring order is kept. Please check without prescient, if it persists, please reopen this bug. If not, please ask on the prescient issue tracker!

**Comment by minad** [comment]
@hmelman In case you want precise control over the consult--read configuration there is now `consult-config`. See https://github.com/minad/consult/commit/36c9f20ce6788707901474034008d183394544bc. This feature is more intended for expert users since it also relies on the consult--read api.

**Comment by hmelman** [comment]
Hmm, I can't reproduce it now and neither can a friend who saw it.  We'll be on the lookout for it and report on prescient if we see it again.
