### ISSUE TITLE
consult-buffer doesn't find candidate in bookmark

### ISSUE THREAD

**Issue by azzamsa** [minad/consult#131]
I can't find it using `consult-buffer` → m → SPC → "song":

![image](https://user-images.githubusercontent.com/17734314/103630538-625d1480-4f74-11eb-9468-11f70dabb7d3.png)

But, It's there using `consult-bookmark:

![image](https://user-images.githubusercontent.com/17734314/103630568-70129a00-4f74-11eb-8a10-bbb735940346.png)

```
(use-package consult
  :after selectrum
  :bind (("s-m m" . consult-buffer)
         ("s-m o" . consult-outline)
         ("s-m r" . consult-mark))
  :config
  (consult-preview-mode)
  )

(use-package consult-selectrum
  :after consult
  :demand t)
```

GNU Emacs 28.0.50 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-12-28

**Comment by minad** [comment]
Which completion style are you using? Prescient, orderless or some built-in style? Can you please try to reproduce this with `emacs -Q` and only load `consult`, `selectrum` and `consult-selectrum`?

**Comment by minad** [comment]
This is actually a recently introduced selectrum bug, see https://github.com/raxod502/selectrum/issues/320

**Comment by azzamsa** [comment]
So far it only affect the bookmark.

The behavior is strange. If I use `consult-bookmark` then use `consult-buffer` again. It appears:

![image](https://user-images.githubusercontent.com/17734314/103639942-bfab9280-4f81-11eb-9c1c-851c5a8677ce.png)

I need to invoke `consult-bookmark` before using `consult-buffer` to fix this issue.

**Comment by minad** [comment]
We have to sort out the changed behavior in selectrum first, see https://github.com/raxod502/selectrum/issues/320. Then we will see if there is still some bug in consult (I don't think so).

**Comment by minad** [comment]
@azzamsa I am not seeing this. Can you please try this on `emacs -Q` in order to ensure that it is not some unrelated issue. Only load selectrum, consult and consult-selectrum. It could also be an Emacs 28 bug, I am not sure. Can you cross check with stable Emacs 27.1?

**Comment by azzamsa** [comment]
Using `emacs -Q` on the same version works:

![image](https://user-images.githubusercontent.com/17734314/103653265-dc9e9080-4f96-11eb-89c1-c00590ef3ce7.png)

So, maybe the error above is related to my config (or straight.el)

**Comment by minad** [comment]
Okay, if you find the issue, please report it here for reference!

**Comment by azzamsa** [comment]
My current workaround for this error:
1. call `consult-bookmark` using `C-x r b`
2. call `consult-buffer` with b (bookmark) filter

I need to do the first step in each of emacs restart, otherwise, I got the same error as above.
