### ISSUE TITLE
Exclude certain buffer in consult-buffer

### ISSUE THREAD

**Issue by azzamsa** [minad/consult#132]
Hi.

Is there any equivalent feature of `helm-boring-buffer-regexp-list`. E.g

``` elisp
  (setq helm-boring-buffer-regexp-list
        '("\\` " "\\*helm" "\\*helm-mode" "\\*Echo Area" "\\*Minibuf"
          "\\*Messages" "*magit-" "magit" "*vterm" "vterm" "^:" "*Occur"
          "*format-all-error"))
````

It will exclude those matched buffer name to helm-buffer. I can toggle (show/hide) using C-a.

Thanks.

**Comment by minad** [comment]
I also thought about adding something like a `consult-buffer-exclude-list`. The question is if the excluded buffers should be shown in the list of ephemeral buffers. I am filtering these out right now and you can show them if you press `SPC` as first character. I would probably display all excluded buffers in that list. Another alternative would be to have some kind of hard exclusion list for buffers which should never be shown, but this is probably overkill.

PR for such a feature is welcome, but the list should only include some standard buffers by default. I think I wouldn't want to see `*Messages*` in that list by default.

**Comment by oantolin** [comment]
> I think I wouldn't want to see `*Messages*` in that list by default.

I wouldn't either, I **love** the `*Messages*` buffer: in the best buffer competition it's tied for first place with `*scratch*` and `*help*`. But still, having it excluded wouldn't be too terrible: I never switch to it via `switch-to-buffer` or `consult-buffer`, but with `C-h e`, `view-echo-area-messages`.

**Comment by minad** [comment]
> I never switch to it via switch-to-buffer or consult-buffer, but with C-h e, view-echo-area-messages.

I wasn't even aware of this :rofl: But in my case, the help is banned to F1.

**Comment by azzamsa** [comment]
`(setq consult-buffer-filter '("^ " "*Messages*"))`

I have them excluded in `ephemeral` buffer.

![image](https://user-images.githubusercontent.com/17734314/103814360-199c7d00-5094-11eb-9f9a-a68953a2f724.png)

But, how can I hide them in 'normal' consult-buffer?

![image](https://user-images.githubusercontent.com/17734314/103814387-28832f80-5094-11eb-9532-736ffd6bd51b.png)


Sorry, I have look throughout the changes, but can't get the idea. Thanks.

**Comment by minad** [comment]
@azzamsa "*Messages*" is not a regular expression. See https://www.gnu.org/software/emacs/manual/html_node/emacs/Regexps.html. You should write `(setq consult-buffer-filter '("^ " "\\*Messages\\*"))`.

**Comment by azzamsa** [comment]
![image](https://user-images.githubusercontent.com/17734314/103815145-7f3d3900-5095-11eb-854a-85287cf13e62.png)

doesn't work either.

**Comment by oantolin** [comment]
Didn't you change the indicator from "[Ephemeral]" to "[Hidden]", @minad? If so, I think the screenshot @azzamsa showed with "[Ephemeral]" indicates he's not running the updated version.

**Comment by minad** [comment]
Thanks @oantolin! Yes, @azzamsa is not running the current Version.

**Comment by azzamsa** [comment]
Oh, my bad. I rust to try without invoking `straight-pull-package` as usual. Sorry it was 1 AM here :).

**Comment by prosoitos** [comment]
> I wasn't even aware of this 🤣 But in my case, the help is banned to F1.

For info (not relevant to this issue though), accessing the `*Messages*` buffer can also be done with a `<mouse-1>` in the echo area (which runs `view-echo-area-messages`). Using the mouse is not always convenient or practical, but I thought I would mention it in case it is useful to someone.

I really like having my buffer list kept to a minimum and access other open buffers through this and other tricks. So thank you for `consult-buffer-filter` 🙂
