### ISSUE TITLE
consult-ripgrep: Error running timer

### ISSUE THREAD

**Issue by azzamsa** [minad/consult#133]
Hi.

I try to use `consult-ripgrep` but I get: `Error running timer: (wrong-number-of-arguments #<subr selectrum-exhibit> 1)`

![image](https://user-images.githubusercontent.com/17734314/103643169-cee10f00-4f86-11eb-8b76-666932d174e6.png)

```
GNU Emacs 28.0.50 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-12-28
```

But, using `emacs -Q` and only consult loaded. It works:

![image](https://user-images.githubusercontent.com/17734314/103643904-0a300d80-4f88-11eb-8045-f2ee95ac162b.png)

Any suggestion?

**Comment by minad** [comment]
Please be a bit more patient and always try the newest upstream versions, instead of opening five bugs. You seem to have the newest consult version, but an outdated selectrum version.

**Comment by azzamsa** [comment]
reported this, because I believe these are not related.

**Comment by minad** [comment]
@azzamsa Yes, it is not related. Please continue to send bug reports. I just had a few cases of "false reports", where things have been misconfigured or where outdated versions were used. I try to update the docs in those cases to make things more clear. In this case - did the update to the newest versions fix the problem?

**Comment by azzamsa** [comment]
I updated my emacs to the latest revision. I've also updated selectrum and consult.

```
8ad983c4ac (HEAD -> feature/native-comp, origin/feature/native-comp) 17 hours ago * test/src/comp-tests.el (cond-rw-1, not-cons, 45576): Rename three tests. (Andrea Corallo)
```

It works now on `emacs -Q`:

![image](https://user-images.githubusercontent.com/17734314/103653793-9c8bdd80-4f97-11eb-8c23-5c4179c500f7.png)

also works with my config:

![image](https://user-images.githubusercontent.com/17734314/103653946-d230c680-4f97-11eb-8f4a-a98be78ba0f2.png)
