### ISSUE TITLE
Add `consult-find-file` with backward directory tree navigation mapped to backspace key

### ISSUE THREAD

**Issue by marcora** [minad/consult#134]
I know it's easy to just M-backspace with the standard find-file, but having a consult-find-file that offers the single key shortcut would be great!

**Comment by minad** [comment]
This is out of scope for this project for multiple reasons:

* It violates the principle (of the consult, embark, marginalia, selectrum/icomplete-vertical, ... package suite) that we want to reuse existing commands if possible.
* This is not a concern of consult but of the consult, but rather of the completion system
* The benefits are marginal over find-file and I won't add commands which only provide marginal benefits.
* You can probably modify the minibuffer keymap of your completion system to give you the desired behavior.

**Comment by minad** [comment]
On 10/14/23 00:38, Faraz wrote:
> this is a bit of a major inconvience for me - moving from
> counsel-find-file to consult-find-file.
> 
> I have to keep counsel package around this for just the find-file command

I wonder if this issue hasn't been long resolved by
`vertico-directory-delete-char` and `vertico-directory-delete-word`. See
the Vertico README for details.

**Comment by brtholomy** [comment]
There's also `vertico-directory-up` for anyone interested.

https://github.com/minad/vertico/wiki#additions-for-moving-up-and-down-directories-in-find-file

I bind it to the same as `dired-up-directory` for muscle memory.

**Comment by nurdann** [comment]
How would you rebind a key to be specific to `find-file` minibuffer? Because remapping in `vertico-map` ends modifying keybind for any prompt with vertico.

**Comment by brtholomy** [comment]
Yes that's right. Just map it to something that makes sense in all prompts. I use "C-M-u", which is `backward-up-list` globally by default.

**Comment by oantolin** [comment]
Just bind `vertico-directory-delete-word` in `vertico-map`: that command checks if you are completing files and if not behaves the same as `backward-kill-word`.
