### ISSUE TITLE
consult-buffer: Configurable virtual buffer sources

### ISSUE THREAD

**Issue by marcora** [minad/consult#135]

**Comment by minad** [comment]
This makes sense, some kind of `consult-virtual-buffer` customizable variable or some way to configure the completion sources used by `consult-buffer`. I won't implement this myself since I wouldn't need it, but I will accept a PR providing this functionality.

**Comment by oantolin** [comment]
What would each source need? I'd say a nice string name, a single character for narrowing, a symbol for the real category (for embark actions), a function of no arguments that produces the list of them, and a function of one argument that says how to switch to that virtual buffer. Does that cover everything?

You know, that sounds very general: it could be used for any sort of muilt-source situation.

**Comment by minad** [comment]
Yes, something like this. It is a bit more complicated since there is also the mess with other-window/other-frame. And then there is special casing for ephemeral buffers. Consult-buffer is a bit of a mess right now, but by externalizing the sources I think we can improve it.

**Comment by minad** [comment]
@rileyrg proposed in #155 to add the file-name-history to consult-buffer as a buffer source instead of/additional to recentf.

**Comment by minad** [comment]
@leungbk proposed to add terminal prompts to consult-buffer in #130, this is comparable to [helm-selector](https://github.com/emacs-helm/helm-selector)
