### ISSUE TITLE
Evil mode: residual highlighting in preview mode

### ISSUE THREAD

**Issue by dawranliou** [minad/consult#141]
Hi maintainers, I'm using emacs 27.1 on Mac. I've seen the same issue on several emacs distributions: emacs-plus 27.1, emacs-plus 28.0.50 and emacs macport 27.1. In short, when I use evil-mode I with `consult-line` and other commands like `consult-ripgrep` and `consult-outline`, I can see residual highlights that don't go away. Below is a demo of the problem I saw only when I have the evil mode turned on. This might offer some clue but for some reason, this issue only shows up when I do the `consult-line` command the second time. I think this might also be true for other commands as well but I haven't done a lot of testing on the others.

![out](https://user-images.githubusercontent.com/4307599/103854796-44b2bb00-50ec-11eb-8031-dbc04f6a8e58.gif)

Here is the minimal config I used with `emacs -Q` in the demo above:

```
(add-to-list 'load-path "~/.emacs.d/straight/build-27.1/evil")
(add-to-list 'load-path "~/.emacs.d/straight/build-27.1/consult")
(require 'consult)
(consult-preview-mode)

(require 'evil)
(evil-mode t)
```

Thank you in advance and keep up the great work!

**Comment by minad** [comment]
Oh okay. This is weird. Could you ask on the evil issue tracker too? I am not an evil user and I wonder what is going on here. These highlights overlays and should be deleted in any case due to an unwind-protect.

Ping @leungbk

**Comment by dawranliou** [comment]
Hey @minad thanks for responding! I've filed an issue on the evil issue tracker. 🙏 🙏 🙏

**Comment by leungbk** [comment]
I have encountered this issue for a while now, but at the time of writing, with the latest rev of Consult, I no longer have any issues. Do you still encounter this problem, @dawranliou?

**Comment by minad** [comment]
@leungbk any idea what the issue could be? If it is gone now it could have been the fault of consult. Bit I didn't change the preview code for a while.

**Comment by wakira** [comment]
@minad I bisected it. It was commit 44d0eaa9ecfbcbc6b582c95c0bb835828beb0be3 that fixed the issue

**Comment by minad** [comment]
@wakira but this commit breaks #152.

**Comment by minad** [comment]
I believe that this bug is related to #152. Evil-mode does not reset the post-command-hook correctly.

**Comment by dawranliou** [comment]
Thanks! Confirmed that I no longer encounter this error with the latest rev of Consult. 🙇‍♂️

**Comment by minad** [comment]
@dawranliou Don't thank me! I am not sure if the bug has actually been fixed, but I am not sure what I could do about it from the side of Consult- It seems there is a serious bug in Evil, so I cannot promise that everything should work as it should. Please take a look at #152. Can you try the small snippet I posted there?

~~~ elisp
(minibuffer-with-setup-hook
    (lambda ()
      (add-hook 'post-command-hook (lambda () (message "HOOK %s" this-command)) nil t))
  (completing-read "Test: " '(a b c)))
~~~

If you run this, it will show HOOK for every key pressed during the completing-read session. But even after exiting completing-read, the next time you open the minibuffer you will see HOOK again. Can you reproduce this in your setup?
