### ISSUE TITLE
manual preview mode

### ISSUE THREAD

**Issue by minad** [minad/consult#143]
It would be interesting to be able to specify a global default preview mode (off, manual, auto) and a preview mode per command. Manual preview would require a keybinding to trigger. Cc @clemera

**Comment by minad** [comment]
@clemera This has been incredibly easy to implement. It is really a good addition in my perspective. This way you can always have manual previews enabled by default bound to a key. And then maybe enable per command automatic previews where it is desired!

**Comment by clemera** [comment]
Really great, thanks!
