### ISSUE TITLE
Add index to info manual

### ISSUE THREAD

**Issue by hmelman** [minad/consult#145]
I tend to use the index feature of emacs info manuals to find things, often via the command `info-lookup-symbol` on `C-h S`.  It would be nice if the consult manual (and others) had an index and worked with these features.

**Comment by minad** [comment]
How is this possible?

**Comment by hmelman** [comment]
See the "Indices" section of the texinfo manual.  Basically you annotate the text with several kinds of `@Xindex` functions.

**Comment by minad** [comment]
@hmelman And how can I do this. I won't edit the texinfo file manually. It is generated from the org file. I can surely research this myself, but it would certainly be helpful if you have some hints on how to do this or where to look.

**Comment by hmelman** [comment]
I don't know about the way you're generating it from the org file.  I only know how to do it when editing texinfo directly.

**Comment by minad** [comment]
There is an org texinfo export :)

**Comment by hmelman** [comment]
I assumed.  I haven't used it, nor do I know the details.  As I remember there have been several discussions on emacs-devel about changing the manual source to something more modern, like org, and maintaining indexes is one of the arguments for sticking with texinfo.  I don't know if org added facilities since then.

**Comment by minad** [comment]
See https://orgmode.org/manual/Texinfo-Export.html. There is also https://orgmode.org/manual/Indices.html :tada:
