### ISSUE TITLE
explicitely specify directory to find

### ISSUE THREAD

**Issue by omar-polo** [minad/consult#146]
Hello,

here's another compatibility issue, this time with find.  I don't know what POSIX requires, but on OpenBSD (and on FreeBSD too based on a quick testing) you have to explicitly pass the directory to find.  This is different from GNU find that defaults to ".".  i.e. `find -iname Makefile` fails with "unknown option -- i".

A very quick and dirty but working solution may be something like this:

```diff
diff --git a/consult.el b/consult.el
index 0f972be..3e5483c 100644
--- a/consult.el
+++ b/consult.el
@@ -2409,7 +2409,7 @@ CMD is the find argument list."
   (find-file
    (consult--read
     prompt
-    (consult--find-async cmd)
+    (consult--find-async (nconc (list (car cmd) ".") (cdr cmd)))
     :sort nil
     :require-match t
     :initial (concat consult-async-default-split initial)
```

but it feels ugly.

What about splitting `consult-find-command` in two?  I'm thinking something like `consult-find-command` that contains the `find` executable, and `consult-find-arguments` with the list of flags to pass to find.  Then still you have to `(nconc (list consult-find-command ".") consult-find-arguments)` or similar, but at least is more descriptive and has the additional benefit that it's easier to change only the find command (i.e. using gfind?) or only the arguments.

**Comment by minad** [comment]
Why not just put it directly in consult-find-command? We always run it in the current directory.

**Comment by omar-polo** [comment]
You're absolutely right!  I haven't thought about that.  Seems the best solution.

**Comment by omar-polo** [comment]
Thanks!

**Comment by minad** [comment]
I don't recall why I originally didn't do this - maybe I thought that I will pass the directory as argument at some point, but in the end I used default-directory which is the more robust solution.
