### ISSUE TITLE
consult-goto-line no longer works

### ISSUE THREAD

**Issue by mpenet** [minad/consult#148]
on bb92e1661874f588d4d180cc946e8116461d05ae

When I try using it it never seems to accept numbers and returns "Please enter a number" without triggering any preview either.

You can see my conf here: https://github.com/mpenet/emax/blob/master/init.el#L330 (nothing exotic)

**Comment by minad** [comment]
@mpenet Thank you for reporting. This could be due to the recent breaking preview changes. See https://github.com/minad/consult/commit/86e506537fdfa73fda88d89d161c25d179141054. I will take a look.

**Comment by mpenet** [comment]
you rock, thanks!

**Comment by minad** [comment]
Thanks!
