### ISSUE TITLE
consult-selectrum wrong type arg error?

### ISSUE THREAD

**Issue by emacsomancer** [minad/consult#149]
Using the default config, I seem to be getting an error:

`Error (use-package): consult-selectrum/:catch: Wrong type argument: number-or-marker-p, nil `

**Comment by minad** [comment]
Which commit are you using, can you please try the most recent commit: https://github.com/minad/consult/commit/1ca1ca683fe40b233272ac23f46193d968e03b28

**Comment by emacsomancer** [comment]
I'm still on the 'parent' https://github.com/minad/consult/commit/cd474331644e75eb760f039492705aec1c6eef54 (as that's the latest to hit MELPA so far)

**Comment by minad** [comment]
@emacsomancer Yes, this version has a bug. Please try the most recent commit in order to confirm that you are not observing a different problem.

**Comment by emacsomancer** [comment]
Yes, the newer commits fix this.
