### ISSUE TITLE
consult--with-preview-1 problem with Evil

### ISSUE THREAD

**Issue by leungbk** [minad/consult#152]
Starting at commit 44d0eaa, after I use some `consult` command with a preview action and then use a `completing-read`-based command that does not rely on consult (say, `C-h v`), I get the following error:

``` elisp
 Error in post-command-hook (#[0 "\301\303 \240\210\300\304=\204,\0\305 \306\307\310\311\312\313!\314\"\315\316%\300<\203$\0\300\202&\0\300C\"\262\205:\0\317\320!\211\2058\0
\301\242\"\262\207" [any ("") consult--preview-function minibuffer-contents-no-properties any this-single-command-keys seq-find make-byte-code 257 "\301!\300\232\207" vconcat vector [vconcat] 3 "

(fn X)" run-hook-with-args-until-success consult--completion-candidate-hook] 8]): (void-function nil)
Quit
```

I can reproduce with the following `init.el`:

``` elisp
(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package selectrum
  :straight (:host github :repo "raxod502/selectrum")
  :config
  (setq selectrum-show-indices t)
  (selectrum-mode 1)

  (define-key global-map (kbd "C-x C-z") #'selectrum-repeat))

(use-package consult)
(use-package consult-selectrum
  :straight (:host github :repo "minad/consult"))

(use-package evil
  :config
  (evil-mode 1))
```

Interestingly, the problem only manifests after turning on `evil-mode` for the first time.

Reverting the commit fixes the problem. But using stuff like `cl-letf` or `let` with `consult--preview-function` doesn't seem to help. Seems like some obscure scoping issue may be at work.

**Comment by minad** [comment]
@leungbk This could be related to #141.

**Comment by minad** [comment]
@leungbk It seems that this is an evil-bug. Evil messes up the buffer-local post-command-hook. The post-command-hook stays active even after the minibuffer is closed. Then when the next command opens the minibuffer, the post-command-hook is still there. Can you please open an issue on the Evil bugtracker?

~~~ elisp
(require 'package)
(package-initialize)
(require 'evil)
(evil-mode)

(minibuffer-with-setup-hook
    (lambda ()
      (add-hook 'post-command-hook (lambda () (message "HOOK %s" this-command)) nil t))
  (completing-read "Test: " '(a b c)))
~~~

**Comment by minad** [comment]
Related evil bug https://github.com/emacs-evil/evil/issues/1261

**Comment by minad** [comment]
I create a bug report: https://github.com/emacs-evil/evil/issues/1406

**Comment by minad** [comment]
@leungbk @dawranliou @wakira @jixiuf @mohkale I pushed a workaround, see https://github.com/minad/consult/commit/8091d70e8da7694353f4a73d149895ef8fd2fdc2. I am always using symbols for hooks and advices now in order to avoid the problems with lambdas, also regarding introspectability of lambdas. This should ensure that Consult previews work flawlessly with Evil now. Please test it!

**Comment by dawranliou** [comment]
Thank you @minad! I'm confirming that this is fixed for my use case. Really appreciate it! 🙏 🙏 🙏

**Comment by minad** [comment]
@dawranliou Thank you for confirming that it works now!
