### ISSUE TITLE
Ripgrep doesn't seem to update candiates immediately [OSX]

### ISSUE THREAD

**Issue by jojojames** [minad/consult#154]
emacs -q (caveat: I forgot to clear my elpa folder so technically the packages were already installed..)
```
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(use-package selectrum
  :ensure t
  :config
  (selectrum-mode))

(use-package prescient
  :ensure t
  :config
  (prescient-persist-mode +1)
  (setq prescient-filter-method '(literal fuzzy)))

(use-package selectrum-prescient
  :ensure t
  :config
  (selectrum-prescient-mode))

(use-package projectile :ensure t)

(use-package consult
  :ensure t
  :config
  (setq consult-project-root-function #'projectile-project-root)
  (setq consult-async-min-input 0))
```

Video:
https://www.dropbox.com/s/mtm4o595b5nvqhx/consult%20ripgrep%202021-01-11.mov?dl=0

Description:

1. M-x consult-ripgrep (sorry of this isn't the right name, doing it from memory)
2. Type the letter 'a'
3. See the '*' indicator next to prompt.
4. Leave prompt/text/emacs alone for a few seconds
5. Expect to see results populated but none come up
6. Type another letter, results are now populated but with results from the first entry (e.g. type "ab", get results from rg "a")

Extra notes:

Equivalent counsel/ivy rg function works as expected, list shows up immediately on key press.
This issue seems to affect the other async modes for me (like find).

Side comment / bug report:

Looks like projectile is implicitly required, I ran into projectile not bound error when trying to repro this.

**Comment by protesilaos** [comment]
Hello @jojojames!  I am not the maintainer, though I just wish to inform you of the customisation option `consult-async-min-input`.  From its doc string, we get:

```
consult-async-min-input is a variable defined in ‘consult.el’.
Its value is 3

  You can customize this variable.

Documentation:
Minimum number of letters needed, before asynchronous process is called.

This applies to asynchronous commands, e.g., ‘consult-grep’.
```

**Comment by jojojames** [comment]
Hi @protesilaos , thanks for looking. I've set it to 0 above as an example:

```
(setq consult-async-min-input 0)
```

The behavior repros at any count for me though.

**Comment by minad** [comment]
I will check this. The projectile error is due to misconfiguration. Note the autoload in the example configuration.

**Comment by minad** [comment]
@jojojames Can you please try the newest commit https://github.com/minad/consult/commit/4c16a9b7d34deb9b232ec2cb47c14b92eadf53ba?

You can also try this configuration to force more timely updates:
~~~ elisp
(setq consult-async-min-input 0)
(setq consult-async-input-debounce 0.01)
~~~

**Comment by jojojames** [comment]
> @jojojames Can you please try the newest commit 4c16a9b?

Same behavior.

> The projectile error is due to misconfiguration, since projectile-project-root is not autoloaded. Note the autoload in the example configuration.

Right, I see.

**Comment by minad** [comment]
@jojojames I pushed another small correction (https://github.com/minad/consult/commit/f0cb07c422ffc4f2407cd732983f9995dbf76589). I don't see anything unexpected anymore. I tried these very aggressive settings:

~~~ elisp
 (setq consult-async-min-input 0
         consult-async-input-debounce 0.01
         consult-async-input-throttle 0.01)
~~~

**Comment by jojojames** [comment]
Looks like melpa hasn't updated, I manually applied that change^ above and re-evaled the same function and then used this config:

```
(setq consult-async-min-input 0
         consult-async-input-debounce 0.01
         consult-async-input-throttle 0.01)
```

> Which emacs version are you using?

27

Ripgrep version:

```
elpa/ $ rg --version
ripgrep 12.1.1
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

OSX Catalina

> Please also check the "_consult-async-stderr" buffer (with leading space) and maybe paste the log here.

```

consult--async-process: ("rg" "--null" "--line-buffered" "--color=always" "--max-columns=500" "--no-heading" "--line-number" "." "-e" "a")

Process rg stderr finished
consult--async-process sentinel: killed: 9

consult--async-process: ("rg" "--null" "--line-buffered" "--color=always" "--max-columns=500" "--no-heading" "--line-number" "." "-e" "ab")

Process rg stderr finished
consult--async-process sentinel: finished

consult--async-process: ("rg" "--null" "--line-buffered" "--color=always" "--max-columns=500" "--no-heading" "--line-number" "." "-e" "a")

Process rg stderr finished
consult--async-process sentinel: killed: 9

consult--async-process: ("rg" "--null" "--line-buffered" "--color=always" "--max-columns=500" "--no-heading" "--line-number" "." "-e" "ab")

Process rg stderr finished
consult--async-process sentinel: finished

consult--async-process: ("rg" "--null" "--line-buffered" "--color=always" "--max-columns=500" "--no-heading" "--line-number" "." "-e" "a")

Process rg stderr finished
consult--async-process sentinel: killed: 9

consult--async-process: ("rg" "--null" "--line-buffered" "--color=always" "--max-columns=500" "--no-heading" "--line-number" "." "-e" "ab")

Process rg stderr finished
consult--async-process sentinel: finished
```

Video:

https://www.dropbox.com/s/r7kbcg1fcdiq1i2/Consult%202.mov?dl=0

**Comment by minad** [comment]
Are you missing consult-selectrum?

**Comment by jojojames** [comment]
That looks to be it!

When I read the code snippet:

```
;; Enable Consult-Selectrum integration.
;; This package should be installed if Selectrum is used.
(use-package consult-selectrum
  :after selectrum
  :demand t)
```

I assumed "should" just implied some extra, optional goodies/integration between consult/selectrum and not that it was required but I guessed I missed this part:

```
NOTE: If you are using Selectrum, you MUST install the packages selectrum, consult and consult-selectrum!
```

Thanks!

Last question, I wonder how to use consult without selectrum? With selectrum-mode on without consult-selectrum, it is displayed like in the video^ but without selectrum on, it doesn't work at all. I just see a prompt with no results (ivy).

**Comment by minad** [comment]
Ivy support is not complete unfortunately. While consult is based on completing-read, for advanced features like narrowing, preview and async a tiny bit of integration code is needed. This is exactly what consult-selectrum provides. However there is no such integration code for ivy yet. If there is interest, someone could write a PR for ivy.

**Comment by aaronjensen** [comment]
FWIW, I have this same issue when I'm using selectrum-prescient. If I disable that, it works. Regardless of whether or not I require `consult-selectrum`

**Comment by minad** [comment]
@aaronjensen Are you using the newest package versions of consult, selectrum, prescient etc? Do you have an outdated consult-selectrum package installed from MELPA - please run `M-x package-delete RET consult-selectrum RET`?

**Comment by aaronjensen** [comment]
I think I had some outdated packages. I got it working with orderless (it wasn't before). i'll try again w/ prescient. Thanks!

**Comment by minad** [comment]
Please always update before reporting bugs or making comments. In particular if you comment on a closed bug report, the probability is high that the bug has already been fixed. See also https://github.com/minad/consult#bug-reports.

**Comment by aaronjensen** [comment]
I'm sorry. I thought I had updated as I just installed it this morning. I forgot that straight keeps the repos around when uninstalling (which I had done a while ago when trying it out the first time.)
