### ISSUE TITLE
consult-buffer doesn'tuse savehist-mode file list

### ISSUE THREAD

**Issue by rileyrg** [minad/consult#155]
There seems to be some overlap between recentf and savehist. savehist is the more generic "save things" mode so ideally, I would like to disable recentf and rely on the file-name-history history that savehist-mode maintains. I see ctrlf-search-history uses savehist mode persistence.

**Comment by minad** [comment]
Okay I see. That could work. But note that recentf does a bit more, it also cleans up this list from time to time for example. I advise against disabling recentf. But we could certainly offer the possibility to also display savehist file-name-history items in consult-buffer. I added this proposal to #135.
