### ISSUE TITLE
consult-goto-line shows line numbers globally

### ISSUE THREAD

**Issue by protesilaos** [minad/consult#158]
Hello Daniel! I have noticed that `consult-goto-line` will show line numbers in all buffers.  I believe this is not the intended behaviour, given that `display-line-numbers` becomes buffer-local.

Here is what I mean (focused window has a yellow modeline---don't ask: just me testing things):

![Screenshot from 2021-01-13 12-09-44](https://user-images.githubusercontent.com/12828033/104438093-466ef980-5598-11eb-98bc-8770cef479e2.png)

![Screenshot from 2021-01-13 12-09-40](https://user-images.githubusercontent.com/12828033/104438084-440c9f80-5598-11eb-9aa5-7d42bc259620.png)

**Comment by minad** [comment]
Thanks!

**Comment by protesilaos** [comment]
You are welcome!
