### ISSUE TITLE
Narrowing to project and opening a recent file not invoked from project's root

### ISSUE THREAD

**Issue by jaor** [minad/consult#160]
Hi! I have a consult-project-root-function configured (same thing can be reproduced using e.g. 'vc-root-dir), so when i call consult-buffer  and press `p SPC`, as expected, my candidate list gets narrowed to buffer and recent files in the project.  However, two (perhaps unexpected) things happen with the latter: first, the marginalia metadata is lost; second, their path, which is a full path without narrowing, switches to a relative path (e.g., instead of seeing "/path/to/project/subdir/foo.el", with narrowing one sees "subdir/foo.el"),  That's not bad and of itself, but when now one wants to open the selected recent file, emacs will try to open the file `subdir/foo.el` relative to the current default-directory, which doesn't need to be the project's root.  In case that has any influence, i am using selectrum.  Thanks!

**Comment by minad** [comment]
Thank you for the report. I fixed the first issue regarding opening the file in the wrong directory. Regarding the Marginalia issue, this is very much related but I still have to find a good way to fix it. Showing the relative path is actually a feature, the path does not switch but it only shows the candidates with project relative paths. If you scroll over all candidates without narrowing you will also find the project files with relative paths right from the start.

**Comment by minad** [comment]
I applied a better fix. Now Marginalia should work and opening the files should work too. I kept the behavior to show the relative path only.

**Comment by jaor** [comment]
On Wed, Jan 13 2021, Daniel Mendler wrote:

> Thank you for the report. I fixed the first issue regarding opening
> the file in the wrong directory.

Just checked and it's working for me too. Thanks a lot!

> Showing the relative path is actually a feature, the path does not
> switch but it only shows the candidates with project relative paths.
> If you scroll over all candidates without narrowing you will also find
> the project files with relative paths right from the start.

Yes, that makes perfect sense.

**Comment by jaor** [comment]
> I applied a better fix. Now Marginalia should work and opening the
> files should work too. I kept the behavior to show the relative path
> only.

yes, working here too.  thanks!

**Comment by minad** [comment]
Thank you for checking!
