### ISSUE TITLE
Unicode tofu in consult-buffer

### ISSUE THREAD

**Issue by astoff** [minad/consult#161]
Using pretty much the standard minibuffer, I type `M-x consult-buffer RET mes TAB` and see this:

![image](https://user-images.githubusercontent.com/6500902/104612683-c4113300-5686-11eb-9e81-737f0ac5154c.png)

(Probably well known to you, but one can sneak arbitrary metadata into a string using text properties)

**Comment by minad** [comment]
Yes this is a known, unavoidable issue and I have no good idea if anything can be done about it.

The problem is that I need a character to disambiguate candidates, since `completing-read` removes properties from its return value. I am not sure if object identity is retained either. Furthermore the following problem remains: If the user types the candidate exactly, the completion system may return this newly created string instead of the corresponding candidate from the list. In this case neither disambiguation via a text property nor via the object identity would work.

You are using using Ivy or Icomplete? In Selectrum I never observe this. The tofu is hidden using a `'display ""` property, but for some reason the display property is stripped away or ignored by Icomplete when forcing completion using TAB.

**Comment by astoff** [comment]
The screenshot above is with the good old minibuffer. I've just tested with Ivy: I still see the tofu if I type `M-i` (to insert the current candidate), but nowhere else.

But yeah, that's a tricky issue then. It's hard to argue outright it's a bug in completing read, but only because it overloads two functions: reading an arbitrary value with suggestions and selecting a value from a list. When a match is required, it should be possible to guarantee one of the entries of the provided collection is returned.

Now, I understand why you need to sneak those characters for consult-line. But what's the ambiguity possible in buffer names? Virtual buffers?

**Comment by minad** [comment]
I made a quick experiment. We can add the following tofu fix to the minibuffer-setup-hook in consult--read. Please try it! I am a bit wary about such hacks though...

~~~ elisp
         (add-hook 'after-change-functions (lambda (&rest _)
                                             (save-excursion
                                               (goto-char (point-min))
                                               (while (not (eobp))
                                                 (when (> (elt (buffer-substring (point) (1+ (point))) 0) #x100000)
                                                   (put-text-property (point) (1+ (point)) 'display ""))
                                                 (forward-char))))
                   nil t)
~~~

@oantolin @clemera What do you think?

> But what's the ambiguity possible in buffer names? Virtual buffers?

Yes.

**Comment by astoff** [comment]
Sure, I'll test it.

I don't think it's too bad to make a virtual buffer inaccessible if an actual buffer with the same name open. This point is relevant, I think, because if the tofu trick was only ever needed when completing-reading with match required, then one could argue that completing-read should be changed. But then again, there may be a legitimate performance reason why completing-read works that way. Sorry, just thinking out loud.

**Comment by minad** [comment]
> I don't think it's too bad to make a virtual buffer inaccessible if an actual buffer with the same name open.

Sure we could also do that. But since I am already using the disambiguation for consult-line, it does not hurt much to use it here too.

> then one could argue that completing-read should be changed.

Yes, I thought about that before. In the case with match-required the API could be changed such that in this case completing-read MUST retain the text properties. One could even use a stronger requirement, where when a candidate is returned which is string= to an existing candidate in the list, then properties MUST be retained. I think Emacs 28 fixes some things in that direction using some customizable variables but I am not sure if they do it in the way I just described.

> But then again, there may be a legitimate performance reason why completing-read works that way. Sorry, just thinking out loud.

Maybe, but I think it is much more probable that when the completing-read API was envisioned, this use case was not considered. The completing-read API is pretty baroque and has been extended over time.

**Comment by clemera** [comment]
> I think Emacs 28 fixes some things in that direction using some customizable variables but I am not sure if they do it in the way I just described. @clemera knows more about that

The variable is called `minibuffer-allow-text-properties`. Only the properties for the part you completed are preserved, see [here](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=14486c44885ffe4532118676aaa6e3783a0417bb).

**Comment by minad** [comment]
@clemera Do you now what this is supposed to solve? This does not sound useful to me.

**Comment by clemera** [comment]
I have no idea, it is indeed not fixing the general problem :(

**Comment by minad** [comment]
Regarding the tofu after-change-function it seems to actually work well. Maybe I add something like this which will be activated when using default-completion, icomplete etc. But I would like to hear the opinions of @oantolin and @clemera regarding that. Do you think this could have some bad side-effects?

See the branch https://github.com/minad/consult/tree/tofu-hack

**Comment by clemera** [comment]
I don't know, when it works it works ;)

**Comment by clemera** [comment]
It might be a bit confusing when you copy the string, as the unicode char is still there and you won't notice it before, I just noticed you have that problem with Selectrum, too.

**Comment by minad** [comment]
> Maybe filter-buffer-substring-function could be set to improve that.

Is the filter-buffer-substring-function used when copying strings?

**Comment by astoff** [comment]
Nice, the workaround doesn't look so bad after all :smiley:

**Comment by clemera** [comment]
> Is the filter-buffer-substring-function used when copying strings? But I suspect that this could have other bad side effects. I am not sure if copying is such a common use case in contrast to seeing the tofus all the time when pressing tab.

Usually yes, by setting it locally things should be fine, though I agree it is not that important but it might confuse users from time to time.

**Comment by oantolin** [comment]
Is displaying them as spaces really better than just making them invisible? Is the idea to remind the user that there is some character there?

**Comment by minad** [comment]
@clemera 

> Usually yes, by setting it locally things should be fine, though I agree it is not that important but it might confuse users from time to time.

I agree that it could be confusing. But I think we are *mostly* fine now. Let's wait and see if it comes up as a bug report. Obviously, people participating in this thread are disallowed to send such a report :grinning: 

@oantolin 

> Is displaying them as spaces really better than just making them invisible? Is the idea to remind the user that there is some character there?

I originally had them hidden. But I observed some issue when jumping to the beginning. Then the cursor was somehow hidden too.

**Comment by oantolin** [comment]
> I originally had them hidden. But I observed some issue when jumping to the beginning. Then the cursor was somehow hidden too.

Maybe this would be good to do always then. They also behave weirdly when put in an embark collect buffer. I often use `C-f` to move past the initial character to avoid this.

**Comment by minad** [comment]
@oantolin Do I have to do something here or is this an Embark exporter issue?

**Comment by oantolin** [comment]
> @oantolin Do I have to do something here or is this an Embark exporter issue?

I think it might be better addressed in Consult, but I'm not sure how. I haven't really looked into what's going. Let me look into it and I'll report back.

**Comment by oantolin** [comment]
First let me describe exactly the "weird behavior". Run `consult-buffer`, then `embark-collect-snapshot`. Switch to the snapshort buffer, and move to the beginning if not there already. Now if you press `n`, `C-n` or `<down>`, instead of ending up at the beginning of the second line, you end up at the end of the second line.

**Comment by oantolin** [comment]
If instead for moving straight down you move forward one (invisible) character, moving down does just move you vertically down without sending you to the end.

**Comment by minad** [comment]
> First let me describe exactly the "weird behavior". Run consult-buffer, then embark-collect-snapshot. Switch to the snapshort buffer, and move to the beginning if not there already. Now if you press n, C-n or <down>, instead of ending up at the beginning of the second line, you end up at the end of the second line.
> If instead for moving straight down you move forward one (invisible) character, moving down does just move you vertically down without sending you to the end.

Yes, I think I've noticed this before. Do you think I can fix this by formatting the candidates in a slightly different form?

**Comment by oantolin** [comment]
> Do you think I can fix this by formatting the candidates in a slightly different form?

I hope so, I'm looking in to it right now.

**Comment by oantolin** [comment]
Oh, you format the entries in a `defsubst`! I have to recompile everything to test changes. 😄

**Comment by minad** [comment]
> Oh, you format the entries in a defsubst! I have to recompile everything to test changes. smile

eval-buffer usually does it.

**Comment by oantolin** [comment]
It seems that using `'invisible t` instead of `'display ""` fixes it.

**Comment by oantolin** [comment]
Probably `'invisible t' also should be used in the fry tofu function.

**Comment by oantolin** [comment]
Yes, much better: do not use `'display ""` or `'display " "`, just use `'invisible t` for both cases.

**Comment by minad** [comment]
@oantolin Okay it seems to work. But there is a bug in Selectrum due to that. I think I will report that separately to the Selectrum tracker.

**Comment by oantolin** [comment]
When will I learn to **always test in Selectrum too*?

**Comment by minad** [comment]
> When will I learn to always test in Selectrum too?

I will change this nevertheless to 'invisible since this is the cleaner solution. I believe this can be fixed in Selectrum then.

**Comment by tinglycraniumplacidly** [comment]
I have Tofu with icomplete.

**Comment by Vonfry** [comment]
I meet the same issue with `icomplete-mode`. And I found a solution to dismiss them.
```
  (let ((tofu-range
         (cons consult--tofu-char (+ consult--tofu-char consult--tofu-range)))
        (font (font-spec :family "Your Blank PUA Font")))
  (set-char-table-range standard-display-table tofu-range [])
  (set-fontset-font t tofu-range font nil 'append))
```
 But I don't think this is a great method. I'll be happy that consult can fix this internally.
