### ISSUE TITLE
consult-buffer f SPC nor consult-recent-file don't work as described

### ISSUE THREAD

**Issue by doolio** [minad/consult#163]
My `consult` configuration for now due to #162 is as follows:

```
(use-package consult
  :bind ("C-x b" . consult-buffer)
  :config
  (require 'consult-selectrum))
```

But pressing `f SPC` does not filter on open (or recently opened) files. `b SPC` and `m SPC` work as described. I've not got `projectile` installed to test `p SPC`. Executing `M-x consult-recent-file` also states no recent files. Note, before installing `consult` I had configured `recentf` but I removed that configuration when I saw `consult` `require`s `recentf`. In addition, I use `no-littering` which stores my `recentf-save.el` file in `~/.emacs.d/var/`.

**Comment by minad** [comment]
> I had configured recentf but I removed that configuration

Do you have recentf-mode activated? Consult does not activate recentf-mode by itself.

**Comment by minad** [comment]
Regarding #162, did you put the symlink there manually? Otherwise I don't understand why `(require 'consult-selectrum)` works. Without that require line you see the error message that consult-selectrum is missing?

**Comment by doolio** [comment]
> Do you have recentf-mode activated? Consult does not activate recentf-mode by itself.

Right, you are! I had assumed it activated it.

> did you put the symlink there manually? Otherwise I don't understand why `(require 'consult-selectrum)` works. Without that require line you see the error message that consult-selectrum is missing?

No, I didn't add the symlink manually. But checking again the symlink is now present! I did logout and back in again (more than once) so one of those must have forced `straight` to rebuild `consult` again. I can remove the `require` line now as well. I will close #162.

Sorry for the noise.
