### ISSUE TITLE
consult-buffer doesn't respect read-{buffer,file-name}-completion-ignore-case

### ISSUE THREAD

**Issue by unhammer** [minad/consult#165]
It seems like `completion-ignore-case` is respected by consult-buffer (or presumably just by whatever completion system one uses), but if I do
```

(setq completion-ignore-case nil
      read-buffer-completion-ignore-case t
      read-file-name-completion-ignore-case t)
```
then I can no longer  match uppercase buffers/files by typing lowercase substrings. 

I see the emac read-buffer just does     `(let ((completion-ignore-case read-file-name-completion-ignore-case) …`

**Comment by minad** [comment]
This is not a Consult issue but rather an issue of Selectrum. As far as I know Selectrum does not support this yet. Please confirm this by trying Icomplete as alternative - disable selectrum-mode, enable icomplete-mode. Can you please ask on the Selectrum tracker?
