### ISSUE TITLE
Is the nil option missing from consult-preview-key?

### ISSUE THREAD

**Issue by doolio** [minad/consult#166]
Or should set as nil with the `string` option? Excuse my elisp ignorance.

**Comment by minad** [comment]
Thanks!

**Comment by doolio** [comment]
No problem. Might I suggest `nil` be the default value. I found it quite jarring initially to see the live preview with each key stroke. Please ignore if your preference or that of other early users is to have the current default.

**Comment by minad** [comment]
Yes, I prefer it like this. Maybe it is not useful to have preview enabled for everything but you can configure this individually per command.

**Comment by doolio** [comment]
Ah I see this variable controls the live preview globally. Yes, then the current default makes sense. When I said jarring it was really only for the `consult-buffer` command.

**Comment by minad** [comment]
For consult-buffer I originally felt the same but I got quickly accustomed to it and now it feels faster ;)
