### ISSUE TITLE
Add option to avoid jumping to project-root in grep like commands.

### ISSUE THREAD

**Issue by mohkale** [minad/consult#169]
Something I never quite liked about the `counsel` class of commands was how `counsel-rg` and several other commands would automatically jump to the root of the current project directory before starting. This is because:

1. If your current directory is in your .gitignore then no matches from it downwards will take place. For example my `emacs` config puts elpa repositories into `lisp/elpa/` and I frequently use jump to the definition of commands in this directory. Then when I like to rg through it I get no search results ever.
2. It doesn't match the behaviour of performing a ripgrep directly. If I open a new shell in the same directory as my current buffer, ripgrep will give different results compared to within emacs.
3. If your project is massive a relatively quick grep for a tiny subdirectory of it can grow to take in all files in the repo.

Therefore I'm asking for the abilitiy to disable this. Perhaps add an option like `consult-grep-jump-to-project-root`. I believe we should define seperate commands (See [counsel-projectile](https://github.com/ericdanan/counsel-projectile)) for when we specifically want to ripgrep our entire project.

**Comment by minad** [comment]
You can specify the directory to search in by pressing `C-u M-g r` if `consult-grep` is bound to `M-g r`.

**Comment by mohkale** [comment]
@minad 

I'm aware, this is the same behaviour as counsel, but then you also have to explicitly recieve a popup to specify a directory which you just hit Enter on immeadiately cause u just want the cwd. To clarify avoiding the root shouldn't be the same as specifying the cwd IMO.

**Comment by minad** [comment]
Yes, in that case, please write your own wrapper function. I do not want to blow up the number of commands unnecessarily to cover every possible use case. The way to go here is to write your own small command which wraps consult-ripgrep and sets the directory to the default directory.

**Comment by mohkale** [comment]
@minad 

Roger. Thanks for hearing me out.

**Comment by minad** [comment]
Maybe I should make it more clear in the readme that it is encouraged to write wrappers. The rule is somehow if a wrapper would be just a single line and just setting an argument, it shouldn't be added here. There is this fd example function in the readme. If something else comes up please let me know!

**Comment by minad** [comment]
Btw, do you still have this evil-issue https://github.com/emacs-evil/evil/issues/1406. I would love to see that sorted out, but I am not using evil myself.

**Comment by mohkale** [comment]
@minad 

Yeah. I understand the desirability for wrappers. It's just I find the default behaviour unexpected/out-of-the-ordinary and in situations like that I feel it makes more sense to provide direct workarounds in the package rather than have end users continually side-step them. It's not all bad though, you should see the madness I use to get around this same issue with `counsel`.

> Btw, do you still have this evil-issue emacs-evil/evil#1406? I would love to see that sorted out, but I am not using evil myself.

Wow, weird coincidence, I'm bisecting evil right now to find it. Looks like this has probably been an issue since v1.0.0

**Comment by minad** [comment]
> Yeah. I understand the desirability for wrappers. It's just I find the default behaviour unexpected/out-of-the-ordinary and in situations like that I feel it makes more sense to provide direct workarounds in the package rather than have end users continually side-step them.

In this case it is a matter of preference. And my preference is different than yours. Generally, I try to find a good default and if many people dislike the current behavior we can also change it. But Emacs is about configurability/extensibility and you can easily tweak it in the way you want, it is not a big deal :)

> Wow, weird coincidence, I'm bisecting evil right now to find it. Looks like this has probably been an issue since v1.0.0

Thank you very much for looking into this! I really wonder about this issue, since evil is so widely used.
