### ISSUE TITLE
consult-buffer sometimes broken after update

### ISSUE THREAD

**Issue by hmelman** [minad/consult#179]
I update `consult` via melpa and `list-packages` (well `paradox-list-packages` but I doubt that matters). A few times (maybe every time?) in the past week or so, when I update `consult`, `consult-buffer` fails.  When invoked, it does nothing, no prompt, it just returns `nil`.  Restarting emacs fixes it.  I'll try debugging it next time it happens (I have to wait for an update), but I wanted to mention it now.

**Comment by minad** [comment]
This is probably a compilation issue. Compilation is unreliable in Emacs unfortunately. There is nothing I can do here. You should always restart after updates. But I hope it works reliably after restarting?

See also https://www.reddit.com/r/emacs/comments/l3pylf/ann_reliable_packageupgrade_without_broken/

**Comment by hmelman** [comment]
I read the stuff at that link and I'd like to understand this specific case a bit more.  The standard problem with package compilation is because of outdated macro definitions or package dependencies.  I don't think macros are a problem here since `consult-buffer` isn't using any I can see from another non-builtin package.  As for dependencies, I'm not sure which would come into play here.  Is it perhaps due to the fact that I'm using `selectrum` and perhaps it's also being updated in these failing cases?  Otherwise I'm not sure what other packages `consult-buffer` is using that causing it to fail.  Maybe the project stuff, but at least reading the code (until I can step through a failure in the debugger) it looks ok.

**Comment by minad** [comment]
Yes, I don't know what the reason is - and as I said we cannot do anything about it. However Selectrum changed significantly today, for example https://github.com/raxod502/selectrum/pull/305. This introduced such a breakage for me as you described. But after restarting the issue has also been fixed for me.

**Comment by hmelman** [comment]
With all due respect, if you don't know what the reason is, you don't know that there's nothing you can do about it.  I'm currently looking at the advice setup by `consult-selectrum`.  That would be broken by reloading Selectrum and could possibly be fixed by changes like new hooks in Selectrum.

**Comment by minad** [comment]
Well, I know that I will not do anything in order to prevent miscompilations or failures due to mismatched package versions or multiple package versions being active at the same time in a running Emacs instance.

**Comment by hmelman** [comment]
FWIW, I just did another update and currently have the problem.  The update was just the packages consult and magit.  Since it's unlikely to be magit, it seems just updating consult itself can cause it.

**Comment by minad** [comment]
For me the package usually keeps working after an update and I am also regularly pulling the updates from MELPA for testing. If you are interested in investigating this further please do.

**Comment by hmelman** [comment]
I will.  So I discovered I had a `~/.emacs.d/elpa/consult-selectrum/` directory from Jan 12.  I'm assuming that's cruft as there's a `consult-selectrum.el` in my latest `~/.emacs.d/elpa/consult/` directory and I don't see a consult-selectrum on melpa.

**Comment by minad** [comment]
Yes, consult-selectrum is cruft. This package should be removed.

**Comment by minad** [comment]
Maybe I should have called consult-selectrum.el somehow differently in order to avoid clashes in this case. But it seems that Emacs usually picks up the correct version.

**Comment by hmelman** [comment]
Not sure, and I suspect the problem is limited to those that installed it while it existed separately.  It's not clear to me that it is the source of my problem (I have to wait until I update again to test), but a Jan 12th date does kinda match to the increased frequency of me seeing problems.  Regardless checking for and removing this separate package might be worth an FAQ entry somewhere.

**Comment by minad** [comment]
I pushed a fix which should help preventing problems if the obsolete package is still around.

**Comment by hmelman** [comment]
I did one update of (just) consult to get this and `consult-buffer` still worked.  I'll keep an eye out for the next week for any more problems.

**Comment by hmelman** [comment]
I've done several updates, both consult alone and with other packages and haven't had the problem of `consult-buffer` breaking so I think is fixed.  So thanks for helping to find the underlying cause and making a change to the code to fix it.
