### ISSUE TITLE
Load Order conflict with Selectrum Prescient?

### ISSUE THREAD

**Issue by okamsn** [minad/consult#18]
I've tested enabling `consult-annotate-mode` by adding it to `selectrum-prescient-mode-hook`, but it still sets `consult--selectrum-highlight-candidates` to the default highlighting function.

I need to manually re-set it to `#'selectrum-prescient--highlight` for the highlighting to work correctly. Filtering still works correctly.

Is there a better way to load these packages?

**Comment by minad** [comment]
Yes annotate mode init is fragile and load order dependent. I think about it. Maybe use a selectrum-mode-hook instead? Or maybe use an advice instead of overwriting the function. There was also the Infinite recursion bug #13 and the load order bug #15

**Comment by minad** [comment]
Alternatively remove the mode and replace by manual configuration...

**Comment by minad** [comment]
@okamsn Does https://github.com/minad/consult/commit/40d0af672793baaad96b7e50fccd61be4be457f7 fix this for you?

**Comment by minad** [comment]
The conflict should be gone. Please notify me if it does not work for you!

**Comment by okamsn** [comment]
This is fixed for me. Thanks!
