### ISSUE TITLE
How to pass additional paths to consult-ripgrep

### ISSUE THREAD

**Issue by ambihelical** [minad/consult#181]
I would like to programmatically be able to supply rip-grep with multiple paths in order to search a dynamic set of notes directories.  I was able to trick counsel-rg into doing this using its extra-rg-args parameter like below, but I haven't figured out anything similar with consult-ripgrep.  Is there a way to do this that I'm missing?

``` 
(defun me:search-notes ()
    (interactive)
    (let* ((dot-notes (expand-file-name "Notes" me:data-directory))
           (proj-notes (me:project-path "Notes"))
           (home-notes (expand-file-name "Notes" "~"))
           (proj-notes-path (if (file-exists-p proj-notes) proj-notes ""))
           (home-notes-path (if (file-exists-p home-notes) home-notes "")))
      (counsel-rg (thing-at-point 'symbol) dot-notes (concat " -- " home-notes-path " " proj-notes-path " " dot-notes) nil)))
```
This is my latest failed attempt, which searches for "--" instead of the string I enter:

```
  (defun me:search-notes ()
    (interactive)
    (let* ((dot-notes (expand-file-name "Notes" me:data-directory))
           (proj-notes (me:project-path "Notes"))
           (home-notes (expand-file-name "Notes" "~"))
           (proj-notes-path (if (file-exists-p proj-notes) proj-notes ""))
           (home-notes-path (if (file-exists-p home-notes) home-notes ""))
           (all-paths (list " -- " home-notes-path proj-notes-path dot-notes))
           (consult-ripgrep-command (append consult-ripgrep-command all-paths)))
      (consult-ripgrep dot-notes (thing-at-point 'symbol))))
```

**Comment by minad** [comment]
You can append locally to the consult-ripgrep-command variable for example. Or use consult--grep and pass your own argument string.

**Comment by ambihelical** [comment]
Sorry I thought it was clear that I was doing that in my failed attempt.  What happens is the -e on the end of the existing command causes all following args to be treated as the regexp to be matched.   I've tried with and without "--", both fail to interpret the extra paths correctly. 

Ripgrep needs additional paths to be provided after any flag-type arguments, so I can't just put the paths before the -e. 

consult--grep will not help, consult-ripgrep just passes the same parameters to it.

**Comment by minad** [comment]
In that case you should probably split the arguments using split-string-and-unquote and insert the directories at the right position. `consult--grep` would help too since you can pass an arbitrary command string tailored to your needs.

**Comment by ambihelical** [comment]
This works. I was confused by the ripgrep documentation which led me to think that paths needed to be after all other flag arguments. I inserted the paths before the "-e", and that works fine.
