### ISSUE TITLE
Align consult-isearch with isearch-edit-string

### ISSUE THREAD

**Issue by minad** [minad/consult#184]
* [x] Bind C-s and C-r in the keymap, there should probably be a consult--read :keymap option now. I considered having additional keymaps before.
* [x] Ensure that isearch-string is used as initial input, or use it always as default such that it is not as intrusive, but then it is less comfortable and not a drop-in
* [x] Propose to bind `consult-isearch` to `M-s e` both in the global and in the isearch map
* [x] Ensure that sorting direction is unchanged (suggestion by @oantolin)
* [ ] Highlighting while scrolling through candidates (suggestion by @astoff)

**Comment by astoff** [comment]
We can probably also make highlighting of the current input work, if you find that interesting. I would need to tinker a bit to figure it out.

**Comment by minad** [comment]
You mean isearch style highlighting of the currently selected candidate? That would be very polished :)

**Comment by minad** [comment]
@astoff I looked into this and I am unsure if the highlighting can be implemented easily since we are in a suspended isearch. Any ideas? Otherwise I would say that this issue can be closed since the current state of `consult-isearch` is good enough.

**Comment by astoff** [comment]
@minad I agree. Being in a suspended Isearch is not a blocker, since there is a (documented, even) way to keep the highlight in the buffer. But it would need a post-command hook to update those highlights, and then we would have to fine tune this hook to avoid flicker, etc. It can be done I guess, but it's a bit of work.

**Comment by minad** [comment]
> Being in a suspended Isearch is not a blocker, since there is a (documented, even) way to keep the highlight in the buffer. But it would need a post-command hook to update those highlights, and then we would have to fine tune this hook to avoid flicker, etc. It can be done I guess, but it's a bit of work.

Okay, in that case I would like to have it. We don't need a `post-command-hook` in our case, since it is all readily setup if you use the `:preview` option of `consult--read`. Is there a function like `isearch-update-highlight-string` which can be called even when the search is suspended and which just does the right thing?

**Comment by minad** [comment]
I tried to add something like this, but it does not work. I guess one has to dig deeper into the isearch source. Do you know how to do this?

~~~ elisp
            :preview
            (lambda (cand restore)
              (unless restore
                (setq isearch-lazy-highlight-last-string cand)
                (isearch-lazy-highlight-start)))
~~~

**Comment by astoff** [comment]
Take a look at `isearch-mb--post-command-hook` in https://github.com/astoff/isearch-mb/blob/main/isearch-mb.el. (By the way, what to you think of that sketch package?)

**Comment by minad** [comment]
Your package sounds like a great idea. I always wondered why isearch is so weird and before you contributed `consult-isearch` here I didn't understand why it is like it is :) Using the minibuffer should be more robust!

I am glad I asked before trying to figure this out better myself. I will give it a try with the code from your post-command-hook!

**Comment by minad** [comment]
I added an 27.1 fboundp check since Consult requires only Emacs 26.1 as of now. I looked into the Emacs source but it wasn't obvious to me when the update from properties function was introduced. Probably the update from properties code could just copied verbatim instead of using the function.

**Comment by astoff** [comment]
It may just be that the function to do this task is new — there is a lot of repeated code snippets in isearch.el that could become functions. I wouldn't know without installing Emacs 26 if the annotations of the `search-ring` entries were there already.

**Comment by minad** [comment]
Actually storing the isearch properties within the search string is an Emacs 27 invention.
