### ISSUE TITLE
Add Icomplete annotation support

### ISSUE THREAD

**Issue by minad** [minad/consult#19]
In principle from the side of consult everything is there. But Icomplete simply does not implement this. I have not yet found a point where I could hook into to make it work until there is upstream support.

See also https://github.com/oantolin/icomplete-vertical/issues/16

**Comment by oantolin** [comment]
I've implemented display of annotations for `icomplete-vertical`. Do you think (horizontal) icomplete should display annotations? I personally think it shouldn't, since it's hard enough to read as is. I'd say probably nothing more needs to be done on the consult side for this.

**Comment by minad** [comment]
Horizontal, please no. When I added this in consult I was aiming for icomplete-vertical to show annotations. I will check both consult and marginalia with icomplete-vertical after you added support!

**Comment by minad** [comment]
@oantolin added support in https://github.com/oantolin/icomplete-vertical/commit/272e525494f47bb1d290a216ac687e7e52e08d0e :tada:
