### ISSUE TITLE
No consult-ripgrep or consult-grep results in a fresh Doom Emacs config

### ISSUE THREAD

**Issue by arozbiz** [minad/consult#190]
I'm trying to incorporate consult-ripgrep into my Doom Emacs config, but I don't get any results when using consult-ripgrep (or consult-grep). I've tested on a fresh Doom Emacs install, but no results. On vanilla Emacs (`emacs -q`) it works.

**Comment by minad** [comment]
Which configuration are you using in Doom? Do you have Selectrum enabled?
