### ISSUE TITLE
Remove which-key delay for consult-narrow-key

### ISSUE THREAD

**Issue by juliocc** [minad/consult#191]
Consult takes `which-key-idle-delay` seconds to display the guide-key menu after pressing `consult-narrow-key`. Would it be possible to show the guide-key menu immediately?

As a possibility, embark integrates with guide-key using `which-key--show-keymap` which displays the popup right away[1]. I checked Consult's code but I'm not sure where to call it.

[1] https://github.com/oantolin/embark/wiki/Additional-Configuration#use-which-key-like-a-key-menu-prompt

**Comment by minad** [comment]
The mechanism used by embark is different. Embark uses a real command `embark-act` while for narrowing we only have `consult-narrow` bound to the various keys, `< b`, `< f` in `consult-buffer` for example. There is no keymap you could show.

The following works but has the ugly side effect to reduce the delay for all keypresses in the minibuffer and even the keypresses in recursive minibuffers.

~~~ elisp
(advice-add #'consult--read :around #'reduce-which-key-delay)

(defun reduce-which-key-delay (fun &rest args)
  (unwind-protect
      (let ((which-key-idle-delay 0.01))
        (which-key--start-timer)
        (apply fun args))
    (which-key--start-timer)))
~~~

It would be better to only invoke the which-key trigger when the narrow prefix key has been pressed.

**Comment by minad** [comment]
More robust version:

~~~ elisp
(advice-add #'consult--read :around #'reduce-which-key-delay)

(defun reduce-which-key-delay (fun &rest args)
  (let ((timer (and consult-narrow-key
                    (memq :narrow args)
                    (run-at-time 0.01 0.01
                                 (lambda ()
                                   (when (eq last-input-event (elt consult-narrow-key 0))
                                     (which-key--start-timer 0.001)))))))
    (unwind-protect
        (apply fun args)
      (when timer
        (cancel-timer timer)
        (which-key--start-timer)))))
~~~

Please give it a try!

**Comment by juliocc** [comment]
Thanks for the quick response. I tried timer version and it works perfectly for my use case. 

Feel free to close this issue.
