### ISSUE TITLE
Multiple Sources doc tweaks

### ISSUE THREAD

**Issue by hmelman** [minad/consult#194]
`:open` is not documented.
`:narrow` is documented twice

I'm guessing that `:items` should say that they must be in the format that `:open` expects.  I'm thinking of an example with files in a directory to be opened with `find-file` and needing to be full paths or relative to `default-directory`

I think `:annotate` could use more of a description or a pointer to what an annotation function does.

**Comment by minad** [comment]
`:open` is not documented since it is `consult--buffer` specific. It is not part of the `consult--multi` source definition but defined by `consult--buffer`.
