### ISSUE TITLE
Configuration examples

### ISSUE THREAD

**Issue by revrari** [minad/consult#197]
Suggestion:

Include a configuration example for those who do not use `use-package`. The same applies to `marginalia`.

**Comment by minad** [comment]
No, I don't want to duplicate the configuration example. This suggestion has been made before. But it is easy enough to derive the plain configuration from use-package. It is not much more than some define-keys. You can use macroexpand if you want to see the code generated by use-package.

**Comment by minad** [comment]
You may want to check out Protesilaos' dotmacs. He recently moved away from use-package. See https://protesilaos.com/dotemacs/.

**Comment by revrari** [comment]
I feel the issue has also to do with software freedom and the imposition of certain schema onto the user. Consult is a package also that relies heavily on other packages, and that increases the learning curve and time spent configuring things. Yes, it is easy enough to reconfigure the example you have provided but it does take up extra time and there is always the possibility of user error. In any event, I will check out check out Protesilaos' dotemacs. Thank you.
