### ISSUE TITLE
Only get horizontal listing of project files in some projects

### ISSUE THREAD

**Issue by thepreacher** [minad/consult#199]
I'm not sure this it the right place to post this so please feel free to tell me to go away. For all Elixir projects that I've created for the past couple of days using `mix new projectname`, when I open Emacs and do `C-c p p` for switch project and then hit `RET`, I get the project's directory content listed horizontally with `\n` between the file names like below:

<img width="1013" alt="Screenshot 2021-02-03 at 14 03 58" src="https://user-images.githubusercontent.com/219075/106770350-ccc9a900-6635-11eb-87e2-b099951d1024.png">

However, when I `git init` in the project directory, and repeat the project switch command again I get what I was expecting:

<img width="725" alt="Screenshot 2021-02-03 at 14 05 37" src="https://user-images.githubusercontent.com/219075/106770544-013d6500-6636-11eb-9aa8-42d0dc8c28aa.png">

If I remove the `.git` directory the issue returns. Now the `mix new projectname` command generates a `mix.exs` file which projectile is supposed to recognise as project root plus I also have the following in my `init.el`:

```
  (use-package consult
    :init
    ;; Optionally configure a function which returns the project root directory
    (autoload 'projectile-project-root "projectile")
    (setq-default consult-project-root-function 'projectile-project-root)
```

and projectile itself is configure like so:

```
(use-package projectile
  :init
  (add-hook 'after-init-hook 'projectile-mode)
  (when (executable-find "rg")
    (setq-default projectile-generic-command "rg --files --hidden"))
  :bind (:map projectile-mode-map
              ("C-c p" . projectile-command-map))
  :config
  ;; Use Selectrum (via `completing-read') for Projectile instead of
  ;; IDO.
  (setq projectile-completion-system 'default))
```

I've not made any changes to my config in while however I'm not sure how long this has been the case since it's a habit to `git init` all my projects as soon as it's created so I haven't noticed this in the past.

**Comment by minad** [comment]
On my setup projectile works flawlessly. But since you are invoking `projectile-switch-project` using `C-p p` this is not a Consult issue. It could either be a Projectile or a Selectrum issue. The Consult project configuration you are doing above should not interfere with Projectile in any way. Please ask on the respective Projectile or Selectrum issue trackers and try to reproduce the issue when running `emacs -Q` and only loading Selectrum+Projectile in order to ensure that no other part of your configuration makes problems.
