### ISSUE TITLE
Displaying which-key choices in consult

### ISSUE THREAD

**Issue by revrari** [minad/consult#201]
As I understand it, I see the narrowing choices of `which-key` in `consult` by pressing "`.`" The results then display in the mini-buffer. Are there any other options for displaying `which-key` choices when using `consult`? I would prefer to see an overview of the choices than have to scroll through them.

**Comment by minad** [comment]
Yes this happens automatically after the which-key delay. See also #191 if you want to see the which-key popup immediately.

**Comment by revrari** [comment]
I am not seeing any popup.

**Comment by minad** [comment]
Did you set `consult-narrow-key` to "."? Then when you press "." in `consult-buffer` the which-key popup/menu should appear after `which-key-idle-delay` (If you don't want to have a delay you can use the configuration described in #191). Does this work in your configuration? If not please run `emacs -Q` and load a minimal configuration, only consult+which-key, nothing else, see the README for that.

**Comment by revrari** [comment]
Yes. `which-key` works in `consult-buffer` and have applied also the code to speed it up, which works very well. I was expecting a pop up buffer when I invoke `M-x`, after I type (for example) `org` followed by `"."`. What I get instead is a list of org- candidates which narrows. Is this the expected behaviour? I.e. no popup above the `mini-buffer` when invoking `M-x`.

**Comment by minad** [comment]
I don't understand what you want to achieve. This "narrowing" feature is consult-specific, this means it only works for consult commands which have it, e.g., consult-buffer, consult-imenu, consult-bookmark. There is no such support for Emacs builtins like M-x.

If you press "org." in M-x, the completion system will show you all entries matching the string "org.". The interpretation depends on your completion-style. I recommend to use `(setq completion-styles '(substring orderless))` or `(setq completion-styles '(basic substring orderless))`.

**Comment by revrari** [comment]
Thank you. That is very helpful. I am sorry but I expected `which-key` to behave in the same way as it does when one uses the default minibuffer in Emacs. As in the following example:

https://drive.google.com/file/d/1DNm-RHo_Lvy8w2k4xChXFaUKlWkR7NQb/view?usp=sharing

**Comment by minad** [comment]
This is not which-key but the `*Completions*` buffer. This is the default Emacs completion system.

**Comment by revrari** [comment]
Thank you. My apologies. I am getting used to the all the new programs and how they work together.
