### ISSUE TITLE
consult-buffer narrow to dired buffers?

### ISSUE THREAD

**Issue by hmelman** [minad/consult#206]
I had several buffers open, some visiting .el files and a couple that were `dired` buffers.  I wanted to switch to one of the `dired` buffers using `consult-buffer` but the directory name was short and similar to some of the files. I thought it would be nice to narrow these somehow to just the dired ones but didn't see a way to do that.  Is there a way?

**Comment by minad** [comment]
You can create special consult buffer sources which filter for dired/non-dired. See consult--source-buffer and the README for how sources are written. I hope that we get https://github.com/oantolin/orderless/issues/30 at some point which will provide a way to filter on metadata. This will allow to provide this feature more easily and more flexibly.

**Comment by liuyinz** [comment]
```elisp
(defvar dired-buffer-source
    `(:name     "Dired"
      :narrow   ?d
      :category buffer
      :state    ,#'consult--buffer-state
      :items    ,(lambda ()
                   (mapcar #'buffer-name
                           (seq-filter
                            (lambda (s)
                              (eq (buffer-local-value 'major-mode s) 'dired-mode))
                            (buffer-list))))))
  (add-to-list 'consult-buffer-sources 'dired-buffer-source 'append)
```

**Comment by minad** [comment]
@hmelman We will add annotation matching to Orderless in https://github.com/oantolin/orderless/pull/162. Then one can type @Dired in consult-buffer + Marginalia.
