### ISSUE TITLE
The consult info manual no longer has an index

### ISSUE THREAD

**Issue by hmelman** [minad/consult#207]
There used to be one, but I'm not finding it with builds of 2/4 or 2/5 (today).  

Same for Embark, I can open a bug for it there if it isn't the same fix.

**Comment by minad** [comment]
Yes, I am aware. Unfortunately I don't know the reason.

**Comment by oantolin** [comment]
I'm a little confused: if by index you mean a list of symbols linking to their documentation, like the built-in manuals have, I don't think embark ever had one (nor do I recall seeing one for consult, but maybe I missed it). If you mean more like a table of contents (which people sometimes call an index, too), both manuals still seem to have one.

**Comment by minad** [comment]
I added findex to the README.org and this should somehow be picked up. It seems that an index is generated from that information but it is not anymore? @hmelman When did the index stop working?

**Comment by hmelman** [comment]
@oantolin  I mean a texinfo index usable with Info-mode's `Info-index` command typically bound to `i`.  I knew that `consult.texi` had one, enabled by use of various `@Xindex` commands, I assumed embark had one too.  If not, I'll open a bug that the embark info manual should have indexes.

@minad I update the "iceberg" package :) virtually every day. I noticed it yesterday, but I'm not sure when the previous time I had used it was, it had been at least a couple of days since I tried.

**Comment by oantolin** [comment]
OK, now I see how it's done, `#+cindex:` and `#+findex:` markup in the org file. Embark's manual definitely has never had an index, but I will add one when I get the chance.

**Comment by hmelman** [comment]
Yes, function and variable indexes are really useful for looking those up. These manuals might be a little small to benefit from a concept index, but I use it all the time in the emacs and elisp manuals.

**Comment by minad** [comment]
The index is now present in the info file, but it is still not possible to `info-lookup-symbol` the Consult functions. But my motivation to figure out this arcane info system is low. Therefore I consider this a "wontfix". But if someone figures it out, a contribution is welcome.

**Comment by hmelman** [comment]
I can confirm that the `Info-index` command works for me in the consult manual.

**Comment by minad** [comment]
Great, that's already something :+1:

So to summarize one needs these cindex and findex org tags and the :index: properties under some index headline (cc @oantolin). I also commented out the headlines via `#+html: <!--` which seems to work for the github page.

**Comment by hmelman** [comment]
I don't use `info-lookup-symbol` a lot (I use `helpful.el`) but I hadn't thought much about it accessing info files other than emacs or elisp or occasionally cl.  It seems it's not uncommon for this not to work, magit, org and dired-x symbols don't work with it either.  tramp does via `tramp-integration.el`.  The key seems to be a `info-lookup-maybe-add-help` call as listed at the bottom of `info-lookup.el`, though the obvious attempt for consult didn't work for me.

Regardless, could you add a variable index to the consult manual?  It's useful for all the user exposed customization variables.

**Comment by minad** [comment]
> Regardless, could you add a variable index to the consult manual? It's useful for all the user exposed customization variables.

I am not sure if it is really useful to have this. I don't like that I have to duplicate all the information. You can look at all variables via describe-variable. I rather considered removing the variable view from the README, but it is also nice for a quick overview on the web.

**Comment by hmelman** [comment]
I agree the current info manual doesn't offer much over describe-variable or customize.  The table of customization variables isn't enough to warrant it.  I do think that there are a couple of places currently in the Special Features section where you describe variables like `consult-preview-key` or `consult-narrow-key` that would be useful in a variable index.

**Comment by minad** [comment]
Yes, if you really want them, I would not reject a PR, but I don't want to spend more time on the info manual. I don't really like it. For example it doesn't even properly render URLs, they will appear with the full URL in the text. Info just seems to have fallen out of time. It does not integrate with the rest of the self documentation I think. There has been this attempt #128 but it turned out that this is not easy to implement something to parse the info buffer properly, since info is a bad format.
