### ISSUE TITLE
Possible isearch improvements

### ISSUE THREAD

**Issue by minad** [minad/consult#209]
Tracking/reminder issue for possible isearch improvements, not necessarily part of the Consult package. See https://github.com/astoff/isearch-mb/blob/main/isearch-mb.el by @astoff. Basically I would like to have consult-isearch to behave more like the minibuffer prompt in isearch-mb. And I would also like to have the isearch-mb multibuffer interaction. It is not clear how to proceed with this.

Many possibilities:

1. Keep consult-isearch but change it such that it is more similar to isearch-mb. But it would differ from isearch-edit then.
2. Add a consult-isearch like history command to isearch-mb. This would duplicating preview logic in isearch-mb.
3. Make isearch-mb depend on consult or create a new consult-isearch package which has @astoff's minibuffer mode
4. ...

**Comment by astoff** [comment]
It seems a bit tricky to make `consult-isearch` (the current one) work with `iseach-mb-mode`. At the very least, an advice to allow recursive minibuffers would be needed. On the other hand, `consult-history` just works during an `isearch-mb` session.

As you can see from isearch-mb, adding something like that to Consult would cost 150 to 200 lines of somewhat hacky code. It's not terrible, nor is it as nice as other parts of Consult.

**Comment by minad** [comment]
I am not really sure what I would like to have. It would be nice to have a minibuffer mode for isearch - I like your idea, it seems more robust, but since it is an extra mode and since it deviates from the default ways too much it should not be part of the main consult package. It could be a small isearch-minibuffer package distributed separately but depending on consult. This package would profit from consult since it could use the consult--read and consult--prompt function which make it a bit easier to create the preview. Furthermore consult--read has narrowing which is used in consult-isearch. The consult-isearch function should then be moved to this package in order to provide the enhanced history with narrowing. Alternatively it could be a fully freestanding package as I mentioned. Another option which would be consult compatible is to not use advices or modes but just provide commands which offer the alternative minibuffer interface to isearch. But this would not be as all encompassing as a mode and you could still trigger normal isearch which would not result in a consistent interface. Too many options and no clear solution.

Other opinions? cc @oantolin

**Comment by minad** [comment]
Currently no plans to add something here, I hope some of @astoff's improvements land either in a package or in Emacs itself.
