### ISSUE TITLE
Make consult-outline account for folding

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/consult#21]
If the headline you choose for consult outline is folded, consult outline does not do what I would expect. If I choose the headline, I'd expect it to unfold the minimal amount necessary to view the headline. Instead, I'm taken to the top level headline. I can create a pull request on this as I do have code that worked for me to fix this.

**Comment by minad** [comment]
Yes, please show the code! As of now thr consult outline is simply presenting a flat list of the available headings. It does not yet interact with folded code in any way. But I agree it would be nice if unfolding would work during preview and when jumping to the line after selection.

**Comment by minad** [comment]
@Luis-Henriquez-Perez I should add - even if you don't have perfectly polished code you can push it here as a draft PR. I am not sure how to integrate folding with consult, since I didn't look how folding is implemented behind the scenes. Some draft code would in case be helpful!
