### ISSUE TITLE
Highlighting remains after consult-grep/git-grep/ripgrep

### ISSUE THREAD

**Issue by glucas** [minad/consult#211]
Not sure if this is the expected behavior, but after jumping to a location with one of the grep commands the matching text seems to remain permanently highlighted. I don't see a way to clear it other than font-lock-fontify-buffer.

**Comment by minad** [comment]
This is unexpected behavior. Please try to follow the instructions https://github.com/minad/consult/#bug-reports and try to reproduce the bug with emacs -Q. Please provide more information.

**Comment by minad** [comment]
Wait - I think I spoke too soon. I thought I have not seen this issue, but I also see remaining highlights now. This must be related to some very recent refactoring I made to improve file preview. Thank you for the report!

**Comment by minad** [comment]
Should be fixed now. Please give it a try. Thanks again for the report.

**Comment by manuel-uberti** [comment]
FWIW it's working good for me here: no highlight leftovers any more.

**Comment by glucas** [comment]
Working great - thanks for the very quick turnaround on that!
