### ISSUE TITLE
Make `C-s M-n` search for word at point (consult-line)

### ISSUE THREAD

**Issue by MicahElliott** [minad/consult#215]
It presently loads the whole line into the search, but this seems rarely useful.

**Comment by minad** [comment]
Please don't open a separate issue for this. This is basically the same question as #214.

**Comment by minad** [comment]
But to answer here too - `C-s M-n` accesses the future history. This is shows the current line by the definition of Emacs, we cannot change that. If you want a `consult-line-word-at-point` command you can write it yourself by passing the word at point as the initial argument to `consult-line`.

**Comment by MicahElliott** [comment]
Thanks for your work on consult and for the help! I'll take a stab at writing that.

**Comment by minad** [comment]
Oh okay, I just added this to the wiki: https://github.com/minad/consult/wiki#start-consult-line-search-with-symbol-at-point

**Comment by oantolin** [comment]
Just in case you didn't know, `consult-line M-n M-n` does use the symbol at point (a second `M-n`).

**Comment by MicahElliott** [comment]
That's good to know, thanks!

~~I tend to use [symbol-overrlay](https://github.com/wolray/symbol-overlay) to bounce around, and it uses `M-n` for similar jumping (to next symbol). So I'll have to think a bit about how to use both. But will probably resort to minad's suggestion above.~~

Oh, I see! So once in `consult-line`, `M-n M-n` does seem to do what's intended/wanted. Yay!

**Comment by minad** [comment]
I also played around with symbol-overlay at some point and I wonder if it is really useful. It seems to me that the tasks you can perform with symbol-overlay can be solved as well using the more generic search/replace facilities.

**Comment by minad** [comment]
But what I find neat about symbol-overlay - it uses overlay keymaps, which I have rarely seen. Having such local keymaps is a bit like Embark's context dependent actions.

**Comment by MicahElliott** [comment]
I don't know embark yet but looking forward to getting into it. But right, the symbol-overlay keymaps are really neat (though surprising at first). And it's pretty great visually for seeing 3+ highlights at a time. Also saves some keystrokes for things like jump-to-definition (alternative to dumb-jump and cider-find-var) and replace.

**Comment by minad** [comment]
You should really try Embark, it is great! It also has jump to definition as an Embark action if you are on a symbol. Since it provides these context local menus it is very general, this is somehow what I meant when I say that symbol-overlay nearly does not have a place anymore in my setup. Then there is also highlight-symbol-at-point, `M-s h .`.
