### ISSUE TITLE
Add consult-completion-in-region-styles

### ISSUE THREAD

**Issue by minad** [minad/consult#219]
This variable should overwrite the completion-styles for completion-in-region. Selectrum has that too. See https://github.com/raxod502/selectrum/issues/82#issuecomment-778841582

**Comment by oantolin** [comment]
I think I don't see the need for this variable. I imagine that for each category, I'd want exactly the same completion styles whether we are talking region or not. Why would I want to complete symbols differently in `C-h f` than in a lisp buffer?

**Comment by minad** [comment]
Because of TAB completion and cycling fewer candidates, see my comment https://github.com/raxod502/selectrum/issues/82#issuecomment-778851974.

**Comment by oantolin** [comment]
I see.
