### ISSUE TITLE
consult-man fails for aggregate entries

### ISSUE THREAD

**Issue by sdevlin** [minad/consult#223]
`consult-man` builds a list of candidates using `man -k`. It uses a regexp to parse the results. Basically, it is expecting results that look like this:

    name(section) - description

It parses out `name(section)` and passes that to the `man` function from man.el, which knows how to handle it.

The issue is that some results aggregate multiple names on one line, like this:

    name1(section), name2(section), name3(section), ..., namex(section) - description

(For an example of this, try `man -k builtin`.)

In this case, `consult-man` parses everything before the hyphen as a single name, and man.el doesn't know how to handle it.

I'm not certain what the correct behavior should be. Maybe consult-man should recognize entries like that and transform them into multiple rows like:

    name1(section) - description
    name2(section) - description
    ...
    namex(section) - description

And then just pass the single `name(section)` that is selected on to `man`.

Alternately, `consult-man` could leave the aggregates intact and sanitize them on selection (e.g. maybe it would just pass `name1(section)` to `man` in all cases).

**Comment by minad** [comment]
Thank you for the report. Fixed in 9c0310eb90bb66c870201117fb24252dd3bfe275. I decided to retain the format of the aggregate entries. Please give it a test.

**Comment by sdevlin** [comment]
Works perfectly!
