### ISSUE TITLE
consult-buffer preview: problem with tramp buffers and slow/unreachable hosts

### ISSUE THREAD

**Issue by jave** [minad/consult#224]
Edit a file using ssh on a remote host with tramp. consult-buffer works smoothly as long as the remote host is up.

If the remote host goes down, the situation changes. As soon as consult-buffer tries to preview the remote buffer emacs hangs.
This happens a lot when changing buffers.

Granted, this is also a tramp problem, but perhaps things could be done in consult buffer to alleviate the situation, by detecting that the remote host is down and not trying to preview it in that case.

**Comment by minad** [comment]
Thank you for the report. It is a known problem that "problematic buffers" do not work well with Consult preview. A similar problem occurred for example with EXWM buffers (#204). The solution for EXWM buffers is to exclude those from the preview by configuring your own buffer sources, see https://github.com/minad/consult/wiki#do-not-preview-x-windows-exwm in the wiki. However in contrast to EXWM, tramp is a built-in Emacs problem, so we could feel more inclined to offer this configuration in Consult out of the box. On the other hand, if you have multiple open buffers with unreachable hosts it will lead to problems anyway, so we could also decide to not fix anything here. Another option is to disable preview for consult-buffer and use a manual preview key instead. Is this answer helpful?

**Comment by jave** [comment]
Thanks. I'm also in contact with the tramp maintainer, who is very helpful.
I'm wondering why previewing a tramp buffer is problematic at all. If a link down situation is detected, tramp buffers should be "frozen" i think, from a user standpoint at least, until they can be "unfrozen". Tramp does not do this, but expects to be given reasonable calls from the above layers. The tramp maintainer is at least willing to consider an "freeze/unfreeze" aproach.

regarding the exwm solution, how would a similar solution look for tramp? If we have a workaround it would be easier to think about the more general solution.

**Comment by minad** [comment]
> The tramp maintainer is at least willing to consider an "freeze/unfreeze" aproach.

That's good to hear.

> regarding the exwm solution, how would a similar solution look for tramp? If we have a workaround it would be easier to think about the more general solution.

The EXWM solution filters the buffers depending on the EXWM mode. For TRAMP we could do a similar thing - e.g., filter remote buffers, such that they are never previewed. I think I would like to keep Consult as is, requiring users to configure their own buffer sources for such cases instead of adding a configuration layer on top which filters the candidates.

~~~ elisp
   (defun consult-buffer-state-no-tramp ()
     "Buffer state function that doesn't preview X buffers."
     (let ((orig-state (consult--buffer-state))
	     (filter (lambda (cand restore)
		       (if (or restore
			       (let ((buffer (get-buffer cand)))
				 (and buffer
				      (not (file-remote-p (buffer-local-value 'default-directory buffer))))))
			   cand
			 nil))))
	 (lambda (cand restore)
	   (funcall orig-state (funcall filter cand restore) restore))))


   (setq consult--source-buffer
	   (plist-put consult--source-buffer :state #'consult-buffer-state-no-tramp))
~~~

**Comment by minad** [comment]
I close this issue since I don't see how we can solve this problem differently than with the proposed buffer filtering solution. I added the snippet to the [wiki](https://github.com/minad/consult/wiki#do-not-preview-exwm-windows-or-tramp-buffers).

**Comment by jave** [comment]
thanks!

**Comment by xdavidel** [comment]
> > The tramp maintainer is at least willing to consider an "freeze/unfreeze" aproach.
> 
> That's good to hear.
> 
> > regarding the exwm solution, how would a similar solution look for tramp? If we have a workaround it would be easier to think about the more general solution.
> 
> The EXWM solution filters the buffers depending on the EXWM mode. For TRAMP we could do a similar thing - e.g., filter remote buffers, such that they are never previewed. I think I would like to keep Consult as is, requiring users to configure their own buffer sources for such cases instead of adding a configuration layer on top which filters the candidates.
> 
> ```emacs-lisp
>    (defun consult-buffer-state-no-tramp ()
>      "Buffer state function that doesn't preview X buffers."
>      (let ((orig-state (consult--buffer-state))
> 	     (filter (lambda (cand restore)
> 		       (if (or restore
> 			       (let ((buffer (get-buffer cand)))
> 				 (and buffer
> 				      (not (file-remote-p (buffer-local-value 'default-directory buffer))))))
> 			   cand
> 			 nil))))
> 	 (lambda (cand restore)
> 	   (funcall orig-state (funcall filter cand restore) restore))))
> 
> 
>    (setq consult--source-buffer
> 	   (plist-put consult--source-buffer :state #'consult-buffer-state-no-tramp))
> ```

This doesn't seem to work at all...
How about using an advice for the preview function instead?

**Comment by nurdann** [comment]
I had to change the function to open recently visited file without preview
```elisp
(defun consult-buffer-state-no-tramp ()
  "Buffer state function that doesn't preview recentf and remote files"
  (let ((orig-state (consult--buffer-state))
	    (filter (lambda (cand restore)
		          (if (or (string-equal "return" cand)
                       restore
			              (let ((buffer (get-buffer cand)))
				            (and buffer
				                 (not (file-remote-p (buffer-local-value 'default-directory buffer))))))
			          cand
			        nil))))
	(lambda (cand restore)
	  (funcall orig-state (funcall filter cand restore) restore))))
```
