### ISSUE TITLE
Error in post command hook running project-find-file

### ISSUE THREAD

**Issue by codygman** [minad/consult#231]
I don't think it matters specifically that I'm running project-find-file, but mentioned it just in case. This is related to #13 I think, but I should have the fix from https://github.com/minad/consult/commit/97dc8718cb6d3953673d15e3bb3400e777a3fb05 because I use revision 4b7830f620e93f74608abb537229f2034d95a40a.

Here is my latest error:

```
Error in post-command-hook (#[0 "\301\303 \240\210\300\304=\204,\0\305 \306\307\310\311\312\313!\314\"\315\316%\300<\203$\0\300\202&\0\300C\"\262\205:\0\317\320!\211\2058\0
\301\242\"\262\207" [any ("~/flk/profiles/develop/emacs/config/") consult--preview-function minibuffer-contents-no-properties any this-single-command-keys seq-find make-byte-code 257 "\301!\300\232\207" vconcat vector [vconcat] 3 "

(fn X)" run-hook-with-args-until-success consult--completion-candidate-hook] 8]): (void-function nil)
Error in post-command-hook (#[0 "\301\303 \240\210\300\304=\204,\0\305 \306\307\310\311\312\313!\314\"\315\316%\300<\203$\0\300\202&\0\300C\"\262\205:\0\317\320!\211\2058\0
\301\242\"\262\207" [any ("~/flk/profiles/develop/emacs/config/") consult--preview-function minibuffer-contents-no-properties any this-single-command-keys seq-find make-byte-code 257 "\301!\300\232\207" vconcat vector [vconcat] 3 "

(fn X)" run-hook-with-args-until-success consult--completion-candidate-hook] 8]): (void-function nil)
Quit
Mark saved where search started [2 times]
Quit
Error in post-command-hook (#[0 "\301\303 \240\210\300\304=\204,\0\305 \306\307\310\311\312\313!\314\"\315\316%\300<\203$\0\300\202&\0\300C\"\262\205:\0\317\320!\211\2058\0
\301\242\"\262\207" [any ("") consult--preview-function minibuffer-contents-no-properties any this-single-command-keys seq-find make-byte-code 257 "\301!\300\232\207" vconcat vector [vconcat] 3 "

(fn X)" run-hook-with-args-until-success consult--completion-candidate-hook] 8]): (void-function nil)
```

I did notice however I'm getting a company-capf error which might be causing all of this:

```
Company: An error occurred in auto-begin
Company: backend company-capf error "Args out of range: "", 1, nil" with args (prefix)
```

I don't have time to reproduce with vanilla emacs at the moment though.

**Comment by minad** [comment]
This bug report is insufficient: Please read https://github.com/minad/consult#bug-reports and ensure that you are using the newest versions. I have to insist that you try to reproduce it in a minimal environment or at least paste the relevant parts of your configuration. I am sorry that this is time consuming but it is not only your time that is consumed. Thank you.

**Comment by minad** [comment]
This bug could be related to evil (#141, #152). But these issues have all been fixed in a robust way as far as I can tell. Please reopen if you manage to reproduce it a minimal setup. The minimal setup can also include evil and other packages if this is necessary to trigger the bug.
