### ISSUE TITLE
How do I turn off new grouping support for consult-multi

### ISSUE THREAD

**Issue by hmelman** [minad/consult#236]
So how do I turn off the new grouping feature of consult--multi when using selectrum?  I can see wanting it for some commands but not others.  At first I thought it screwed up prescient's MRU sorting for consult-buffer but I guess that's not true since the buffer group is first.  But for my notes package, I definitely don't want notes grouped because it does screw up MRU sorting.

**Comment by minad** [comment]
~~~ elisp
(setq consult-config '((consult-buffer :title nil)))
~~~

**Comment by hmelman** [comment]
Great.  I searched for group since the commit talked about x-group and didn't connect it to title.  Can I suggest something like the following for the `consult--read` docstring:

    TITLE a function passed a candidate string to return a grouping title
	
The old one didn't tell me anything:

    TITLE is the title function, called for each candidate string.
