### ISSUE TITLE
keyboard quit problem: Residual highlighting with consult-line in preview mode

### ISSUE THREAD

**Issue by travitch** [minad/consult#24]
If I initiate a search with `consult-line` with live previews enabled and then hit `C-g` to cancel it, the last line highlighted by the live preview stays highlighted until I initiate another `consult-line`. Is this an unexpected behavior?

I'd assume that this happens to other commands besides `consult-line`, but I haven't tried yet.

**Comment by minad** [comment]
Good catch. I will check. I may have missed some unwind-protect or made a mistake when removing the overlays.

**Comment by minad** [comment]
@travitch I cannot reproduce this. I would have noticed something severe like this. Maybe I misunderstood you? Please describe your setup. Emacs version etc, anything special? Can you try with emacs -Q and only loading consult+selectrum?

**Comment by travitch** [comment]
Oh boy, thanks for looking. I can't reproduce with a `-Q`, so I'll have to track down the culprit.  I do not use icomplete, but I do have a bunch of other packages in play. Let me try to narrow it down.

**Comment by minad** [comment]
Ok cool, I guess it is your setup approaching Emacs bankruptcy ;) Would be great if you can come back to me here such that we can sort out any potential incompatibilities or at least document those. Note that preview is kind of an intrusive feature in how it is implemented, so I don't yet except it to be fully robust.

**Comment by travitch** [comment]
Okay, I managed to get a small reproducing example that doesn't make much sense to me.

Using `emacs -nw -Q`:

1. Pasting the following into `*scratch*` and evaluating them just to load up selectrum, consult, and enable `consult-preview-mode`:
```
(add-to-list 'load-path "~/.emacs.d/straight/build/selectrum")
(add-to-list 'load-path "~/.emacs.d/straight/build/consult")
(require 'selectrum)
(require 'consult)
(selectrum-mode +1)
(consult-preview-mode)
```
2. Split the frame (`C-x 3`)
3. Load another file into either frame (e.g., `C-x C-f ~/.emacs.d/init.el`)
4. In that frame, run `M-x consult-line` and hit `C-g` without typing anything

Given the current versions of selectrum and consult (the latest of both, I believe), I see the first line of the buffer stay highlighted. I suppose the key was just that split somehow.

- Selectrum hash 945f8fe18933a53b2012a1d179587d90a70bb536
- Consult hash a5660577385b4b6edeb6b3c1966c20b0558b47b4

**Comment by minad** [comment]
Ok, I guess I've being unfair towards your config ;) Taking a closer look now!

**Comment by travitch** [comment]
No worries, there are all sorts of shady things in my config that were likely culprits

**Comment by minad** [comment]
Not so fast...

**Comment by minad** [comment]
Now I have shady things going on in my own config ;) Please check if https://github.com/minad/consult/commit/a62ed9191fba0256353b0a2df74d75f58f38720e fixes this for you!

**Comment by travitch** [comment]
That did fix the problem for me, thanks! With that I've managed to completely replace ivy/swiper/counsel in my config

**Comment by minad** [comment]
Works for me too, now I had shady things going on in my config too - heap dump...

Thank you for the report! 

> With that I've managed to completely replace ivy/swiper/counsel in my config

This is amazing to hear! I've been an ido user for a long time and used a more barebone Emacs - never really used Ivy. Therefore this won't be an exact clone. But if you are missing something which would makes sense, let me know or even better, open a PR :)
