### ISSUE TITLE
Selecting indexed candidates in Selectrum is off when using newly-added Consult headers 

### ISSUE THREAD

**Issue by leungbk** [minad/consult#240]
``` elisp
(use-package selectrum
  :demand t
  :config
  (selectrum-mode 1)
  (setq selectrum-show-indices t))

(use-package consult
  :demand t
  :config
  (defvar consult-org-buffer-source
    `( :name     "Org"
       :narrow   ?o
       :category buffer
       :items    ,(lambda ()
                    (require 'org)
                    (mapcar #'buffer-name (org-buffer-list)))))
  (add-to-list 'consult-buffer-sources 'consult-org-buffer-source))

(use-package consult-selectrum
  :demand t)
```

Repro: 

1. Load the above `init.el` and `C-x C-f` some `test.org` file.
2. `M-x consult-buffer` and `C-u 3 RET`.

I notice that the selected candidate corresponds to the displayed Selectrum index 2, instead of 3.

**Comment by minad** [comment]
Oh, okay. This is a Selectrum issue but it is my fault since I provided the patch for the grouping. It should be fixed there. Please move the issue there. CC @clemera.

**Comment by minad** [comment]
I created the Selectrum issue myself, we will also provide a fix for this soon. Thank you for the report @leungbk!

**Comment by minad** [comment]
Quick temporary workaround, for everyone observing this issue:

~~~ elisp
(setq consult-config '((consult-buffer :default-top nil)))
~~~

**Comment by minad** [comment]
The issue has been fixed now, see https://github.com/raxod502/selectrum/commit/375a8ac5d75e054a5d5d78bfb831cb57143062dc

**Comment by leungbk** [comment]
Thanks for the quick fix, and sorry for not being clearer with my repro steps.

**Comment by minad** [comment]
You have been clear, I just didn't try with the added source first. You could have emphasized that the bug occurs only with the custom source. It actually only occurred since you added the source in front of the default buffer sources. Because I wondered why nobody had issues before.
