### ISSUE TITLE
consult-yank-pop doesn't work for vterm

### ISSUE THREAD

**Issue by dalgong** [minad/consult#242]
Not sure if this is technically for vterm issue or not but since we all suffer this issue, I'm creating one anyway.
For counsel, vterm has a solution: https://github.com/akermu/emacs-libvterm#counsel-yank-pop-doesnt-work

It would be nice if we have similar fix for consult-yank-pop.

**Comment by minad** [comment]
The counsel workaround should also work for consult. The workaround replaces insert-for-yank with the vterm specific vterm-send-string function. Did you try that?

**Comment by dalgong** [comment]
Advice doesn't work because `consult-yank-pop` command has `(interactive "*p")` which fails because `vterm` buffer is read-only.  While looking at `vterm` code, I figured that `vterm` already provides these and all we have to do is to update the example configuration in README file as follows:

```elisp
...
         ([remap yank-pop] . consult-yank-pop)                ;; orig. yank-pop
...
```

**Comment by minad** [comment]
You can write a small wrapper to disable the interactive spec.

~~~ elisp
(defun my-yank-pop ()
   (interactive "p")
   (consult-yank-pop))
~~~
