### ISSUE TITLE
Better docstring needed for consult-keep-lines

### ISSUE THREAD

**Issue by hmelman** [minad/consult#244]
The docstring for `consult-keep-lines` needs to be clearer about what it does, delete lines from the buffer.  Here's the entire current docstring:

	Select a subset of the lines in the current buffer with live preview.

	The lines selected are those that match the minibuffer input.
	This command obeys narrowing.
	FILTER is the filter function.
	INITIAL is the initial input.

As opposed to the first liine of the docstring of the builtin command it replaces, `keep-lines`:

    Delete all lines except those containing matches for REGEXP.

I'd make a suggestion but I don't really understand what the args are.  FILTER isn't a function, it's some pattern that's mostly a REGEXP but I guess it can also begin with "! " for negation.  Or it's not a REGEXP but some input matching pattern based on the completion packages you're using like prescient or orderless.  I have no idea what INITIAL is when used interactively.  At the least it should begin with something like:

    Delete all lines except those matching FILTER pattern.
	
I know this terminology isn't well defined.  orderless talks about "patterns" mentioning "filtering" twice in its README and prescient talks about "filters" not mentioning "pattern" at all.  The completion api docs talk about "predicates", "matches", "strings" and rarely "filter".  The emacs manual when talking about completion refers to narrowing alternatives to those that "match".  And I know this is all dependent on what completion styles are in effect.
	
It would be nice if at least this set of packages could agree on terminology and make it consistent throughout.  The consult README mentions "filter" a fair number of times, but doesn't really define it and doesn't apply it everywhere (just in search and grep commands docs).  Given consult's use of narrowing, and the interpretation of the input to the grep-like commands, "matching FILTER pattern" or something like it (you could use any of those three words as an argument name) seems like the right direction.

**Comment by hmelman** [comment]
Any particular reason you chose not to change the first line of the docstring?  I think it should say it deletes lines.  If you're trying to remember which command does what, this isn't all that helpful.

<img width="975" alt="Screen Shot 2021-03-12 at 8 33 21 AM" src="https://user-images.githubusercontent.com/1999190/110947103-ba661d80-830d-11eb-8e5d-ad2f93ed0221.png">

**Comment by minad** [comment]
No particular reason. I think it is clear like this. Improvements are always welcome. I would generally appreciate a review of all the docstrings, ideally in combination with suggested changes in patch form, such that I can easily apply it.
