### ISSUE TITLE
Not able to see the last recent file of consult-buffer

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#246]
I noticed an issue in `consult-buffer` with recent files and I am wondering if anyone else is seeing this.

See the gif below:

![consult](https://user-images.githubusercontent.com/17233936/110708390-84804680-81f2-11eb-86cf-04f3f7f3b845.gif)

I have one recent file in this case that I can only see when I type `f SPC` but not before. If there are more than one recent file, I cannot see the last one.

**Comment by minad** [comment]
This seems to be a resizing issue of Selectrum (see also https://github.com/raxod502/selectrum/issues/435). It seems the file entry exists on the last line, but is not visible. You see the file if you enter a filter string like `ideas`?

**Comment by haji-ali** [comment]
I do see the file when I enter the string `ideas`. 

I am not sure what the source of the error is. The proposed fix of setting `selectrum-fix-vertical-window-height` to non-nil did not work for me and I just found out that actually the last two entries are hidden out of view.

Before enabling consult, I was always able to scroll see all the entries which is why I thought consult might be the culprit (perhaps related to the `---buffer---` and `---files---` entries).

**Comment by minad** [comment]
I moved the issue to Selectrum: https://github.com/raxod502/selectrum/issues/491
The group headers are generated by the Consult commands but are displayed by Selectrum, therefore it must be fixed in Selectrum.

As a workaround you can disable the grouping headers with `(setq selectrum-group-format nil)`.
