### ISSUE TITLE
Troubleshooting consult commands `consult-ripgrip` and `consult-find`

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#247]
I am trying to get consult to work in my configuration. Most commands work out of the box. However, two commands `consult-ripgrip` and `consult-find` do not work.

Running them and inputting any pattern results in zero matches. No error messages are printed so I am not sure what the issue is. The only visual indication that something might be wrong is from `consult-ripgrip` where a red `!` is displayed in the minibuffer next to the prompt.

Note that `consult-grep` works as expected and I have `ripgrep` installed. Here's my consult config

```elisp
(use-package consult
  :init
  (setq register-preview-delay 0
        register-preview-function #'consult-register-format)
  (advice-add #'register-preview :override #'consult-register-window)
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
  :config

  (require 'consult-selectrum)

  (recentf-mode)

  (setq consult-narrow-key "<") ;; (kbd "C-+")

  (autoload 'projectile-project-root "projectile")
  (setq consult-project-root-function #'projectile-project-root)
)
```

If I set `(setq consult-project-root-function nil)` then `consult-ripgrip` and `consult-find` work as expected.

I also check `(projectile-project-root)` it returns the correct project root.

**Comment by minad** [comment]
Please check the `_*consult-async-log*` (note the space, it is a hidden buffer). There you also find the ripgrep command, which is executed in the project directory. You can manually try the command in the shell for comparison.

**Comment by haji-ali** [comment]
Thanks! Indeed that buffer the info I was looking for.

Turns out that `consult-find` does not descend into hidden directories hence it was not finding the files in `.emacs.d` directory. `rg` has the same behaviour.

**Comment by minad** [comment]
You can adjust this behavior by modifying consult-ripgrep-command etc.
