### ISSUE TITLE
Jump to a directory 

### ISSUE THREAD

**Issue by linwaytin** [minad/consult#248]
Sometimes I want to quickly open a directory in `dired` or `deer`.
I found a function like `counsel-fd` is useful.
The idea is using `fd` to get all directories under `~/` and narrowing down to the wanted directory. 
Is there a similar function in `consult`?

**Comment by minad** [comment]
There is `consult-find` and you can also configure it to use `fd`. Please take a look at the README (https://github.com/minad/consult#grep-and-find) and the wiki. You can configure it also such that the command only finds directories.

**Comment by linwaytin** [comment]
Thanks. Set `INITIAL` to `".#"` is kind of what I want.
Thanks!
