### ISSUE TITLE
refactoring with consult

### ISSUE THREAD

**Issue by WorldsEndless** [minad/consult#249]
With Helm and with Ivy, you might do a grep on a project, save the results to a buffer, then use wdiff to make a replacement to all the result files (e.g. `replace foo1 foo2`). Is there a workflow for refactoring with Consult?

**Comment by oantolin** [comment]
Not with Consult alone (by design), but if you use it together with the Embark and wgrep packages, you can use `embark-export` from `consult-grep`, `consult-git-grep` or `consult-ripgrep` to get a grep-mode buffer, which you can put in wgrep-mode to edit.

**Comment by minad** [comment]
The workflow described by @oantolin works symmetrically to the single-file workflow: Running `consult-line` + `embark-export` gives you an `occur-mode` buffer. This buffer can then be turned into an `occur-edit-mode` buffer for editing.

Furthermore the workflow is the same if you use the Emacs builtin `grep` for editing.

Wgrep is mentioned in the README, see https://github.com/minad/consult/#recommended-packages and https://github.com/minad/consult/#embark-integration. Maybe the workflow should be documented more prominently?

**Comment by WorldsEndless** [comment]
Brilliant! I am very pleased with this answer. Yes, it definitely is outside the consult design, and I'm glad to see that design kept true. I'm also glad to FINALLY understand what embark export is for! This works perfectly.
