### ISSUE TITLE
Is there an option to initially narrow?

### ISSUE THREAD

**Issue by antifuchs** [minad/consult#251]
I would love to use `consult-buffer` with a setup similar to what `bufler` workspaces do (limiting the selection of buffers to the buffers "in" the workspace in my frame -- usually the active projectile project). That means that when I invoke `consult-buffer`, I'd love to have the selection of buffers already pre-narrowed to the current projectile project.

So far, I've tried:

```elisp
(setq consult-config '((consult-buffer :initial "p ")))
```

But that only inserts the literal string "p " on the input field.

This felt interesting, but results in no narrowing (and you can't narrow at all afterwards):
```elisp
(setq consult-config
      '((consult-buffer :narrow '(consult--source-project-buffers))))
```

So - is what I would like to accomplish possible with consult?

**Comment by antifuchs** [comment]
It just occurred to me that I wished for something similar with `consult-flycheck` also: I'd love to set it up such that if there are errors, it's narrowed to the errors in the files initially.

**Comment by minad** [comment]
Initial narrowing is supported with a little bit of configuration effort (https://github.com/minad/consult/wiki#start-command-with-initial-narrowing). See also the prior discussion in #203.

**Comment by minad** [comment]
There is only one downside of the current approach - if you are not in a project, you probably don't want to narrow down to the empty list :laughing:  This means a little bit of additional logic is needed.

**Comment by antifuchs** [comment]
Thanks so much - I entirely missed this section in the wiki. That's exactly what I wanted & agreed about the additional logic. I'm writing that up now (-:

**Comment by antifuchs** [comment]
In case anyone else wants a similar thing as me, here's what I did to get flycheck errors narrowed to errors only, if there are any:

``` elisp
(defun asf--consult-initially-narrow-buffers ()
  (let ((buffer (if (minibufferp)
                    (window-buffer (minibuffer-selected-window))
                  (current-buffer))))
    (cond
     ;; Narrow buffers to "F" ones (bufler):
     ((eql this-command 'consult-buffer)
      (setq unread-command-events (append unread-command-events (list ?F 32))))

     ;; Narrow flycheck diagnostics to errors if there are any:
     ((and (eql this-command 'consult-flycheck)
           (with-current-buffer buffer
             (cl-find 'error flycheck-current-errors :key 'flycheck-error-level)))
      (setq unread-command-events (append unread-command-events (list ?e 32)))))))

(add-hook 'minibuffer-setup-hook #'asf--consult-initially-narrow-buffers)
```

**Comment by billop** [comment]
Thanks @d1egoaz, I was spending a lot of time trying to add live preview to `project-switch-to-buffer` and this has been a great workaround for me.

**Comment by oantolin** [comment]
@d1egoaz: that function you wrote uses the same strategy as the snippet from the wiki, and is a perfectly valid approach. The only reason that wiki snippet is slightly more complicated is because it provides a more flexible interface: it provides a variable where you can configure initial narrowings for multiple commands.

**Comment by sg-qwt** [comment]
> Hey @minad
> 
> I wanted to create a new function to get a list of consult buffers narrowed by project `p`, the idea is to replace `projectile-recentf`.
> 
> I was looking at this code and the wiki https://github.com/minad/consult/wiki#start-command-with-initial-narrowing , however I accomplished what I wanted only doing:
> 
> ```lisp
>   (defun diego/consult-buffer-for-project ()
>     (interactive)
>     (setq unread-command-events (append unread-command-events (list ?p 32)))
>     (consult-buffer))
> ```
> 
> I wonder if I'm doing something wrong here or am I missing something as the wiki example looks more complicated. Or I misunderstood the example, and the example code is trying to achieve something different.
> 
> Thanks

After spending so **much** time digging, I finally found what I want with your snippet. The example in the wiki [start-command-with-initial-narrowing](https://github.com/minad/consult/wiki#start-command-with-initial-narrowing) is extremely confusing to beginners like me. What most people want this case is just a one time alias function to start some consult function with a narrowed view. 

Eg: 
 * I want a my-consult-buffer-project function with consult-buffer narrowed to ?p, so I can bind that function to some keybinding
 * I want a my-consult-bookmark-org function with consult-bookmark narrowed to org file, so I can bind that function to some keybinding
 etc etc..
 
The wiki example ultimately changed the behavior of consult funtion with its initial narrow, that's not flexible for common use case. I believe this snippet deserve its own place in the wiki. Unless there're other better ways to achieve this that I'm not aware of. cc @minad 

cross reference https://github.com/minad/consult/issues/484
