### ISSUE TITLE
What does this code mean?

### ISSUE THREAD

**Issue by linwaytin** [minad/consult#252]
Thanks for your suggestions on writing the label function. 
The references you gave are very useful.
I've gotten a function which can return a list like 
```lisp
((#("left dyson" 0 10 (fontified t face (font-lock-constant-face font-latex-math-face) font-lock-multiline t)) . 7656) ... )
```
where the last number means the position. 

I think the next step is a function like `consult-line`, but I cannot fully understand the code.
The first few lines are 
```lisp
  (let ((candidates (consult--with-increased-gc (consult--line-candidates))))
    (consult--read
     (cdr candidates)
```
What is the result of `consult--with-increased-gc`?
I thought it would give the same candidate list, but `(cdr candidates)` seems giving only the rest of the list, not including the first element?
Why do we have `cdr` here?

**Comment by minad** [comment]
The function `consult--line-candidates` returns a pair of default value and the list of lines. Therefore there is a `cdr` there. `consult--with-increased-gc` is a macro wrapping the computation, increasing the gc around the computation temporarily to optimize for throughput.

But note that this is not a support forum here. It is an issue tracker. May I suggest you ask your questions to https://www.reddit.com/r/emacs/ or some other support forum/irc channel?

**Comment by linwaytin** [comment]
Thanks for answering my question. 

Sorry for messing up the issue tracker. I will ask questions in Reddit in the future.
Thanks a lot.
