### ISSUE TITLE
Docstring overhaul/readme sync

### ISSUE THREAD

**Issue by minad** [minad/consult#255]
The problem is that some information is present in the readme, but not in the docstrings. This duplication is unfortunate but probably necessary, since different people look at different places. Maybe it would work out to import the docstring to the README via some org-babel/org-mode trickery. However the readme must render cleanly on github. It could be that automation would require an unreasonable effort, in that case go manually over all commands.

**Comment by hmelman** [comment]
IMHO the docstrings should include everything you'd use at runtime.  If there's some major configuration feature, I'd appreciate a mention of the user option in the docstring so I could follow the generated link to it, but otherwise I'd expect detailed config things in the manual (or README).  Same for generalized package features like preview; it's nice if the docstring mentions that a command supports preview but the details of that feature I'd expect to find in the manual (again a link would be great but optional).  Lastly I've been thinking that all the consult commands that are basically enhanced versions of other commands (like `consult-keep-lines` is an enhancement of `keep-lines`) should mention the original command in the docstring so that there are easy to follow links to it.

I might make a pass at overhauling docstrings, but I'm going to be busy for a few weeks.

**Comment by minad** [comment]
These are all good points. I am a bit worried about keeping everything up-to-date and synchronized. But I guess Consult has reasonably stabilized by now such that it would be worth to work on polishing the docstrings. If you find time to help with this, it would be greatly appreciated!

**Comment by hmelman** [comment]
Here's a first attempt at cleaning up the docstring for `consult-keep-lines`.  As I look at other commands I'm sure I'll find other patterns that cause me to update this, but I figured this was worth initial discussion to see if I'm on the right track.  I started from the docstrings of `consult-keep-lines` and `keep-lines`.  

```emacs-lisp
(defun consult-keep-lines (&optional filter initial)
  "Delete all lines in the buffer except those matching FILTER.

This is a consult enhanced version of the `keep-lines' command.

When called interactively the buffer is updated while typing to
remove lines that do not match FILTER according to the current
`completion-style' (rather than just matching a regular
expression).  The lines are not actually deleted until the
command completes.

If the FILTER begins with \"! \", the sense is reversed and the
matching lines are deleted (similar to `flush-lines').

Interactively, in Transient Mark mode when the mark is active,
the filtering is restricted to all lines which contain a portion
of that region, otherwise it is applied to the entire accessible
buffer (not just lines after point).

When called from Lisp, FILTER should be a function that takes two
arguments, an input string and list of candidates, and returns a
list of just the matching candidates.  The function is
responsible for reversing the sense of the filter if the input
begins with \"! \".

The optional argument INITIAL is the initial input for the command 
which can be configured with `consult-config'."
  ;; Use consult-location completion category when filtering lines
  (interactive (list (consult--completion-filter-dispatch 'consult-location 'highlight)))
  (consult--forbid-minibuffer)
  (barf-if-buffer-read-only)
  (consult--with-increased-gc
   (consult--prompt
    :prompt "Keep lines: "
    :initial initial
    :history 'consult--keep-lines-history
    :state (consult--keep-lines-state filter))))
```

I'm using old style symbol quoting because I think that's what consult.el currently uses.  I personally prefer it, and I'm not sure if support for the new style was added in Emacs 26 or 27.

I'm not sure everything is technically correct, but I tested all the interactive uses mentioned.  I don't love the last sentence about INITIAL, but it's the most useful thing I could think to say about it.  From the current docstring I removed the note about using it in an embark collect buffer because it seemed like too much of a specific example for a docstring.  It's something I think is more suited to the README.  Also I removed the line "This command obeys narrowing." because I don't think it does.

**Comment by hmelman** [comment]
Ping @minad I'd love some comments on the above before I work on all the consult docstrings.

**Comment by minad** [comment]
This is low priority for me right now. Please proceed if you are interested in this. But I would prefer a PR as I have mentioned before. I am not sure about this yet, but maybe I will move this package to ELPA, requiring copyright assignment.

**Comment by hmelman** [comment]
I was planning on making this my first PR, though I haven't done a copyright assignment which is why I've deliberately not contributed code so far.  I know it's not needed for documentation contributions, I'm not sure if that applies to docstrings.

**Comment by minad** [comment]
> I know it's not needed for documentation contributions, I'm not sure if that applies to docstrings.

I would prefer if you get the assignment just to be on the safe side. Or you could ask on the mailing list.

> I'd love some comments on the above before I work on all the consult docstrings.

I should add this - I prefer a more time efficient approach. Instead of commenting on all small changes step by step I would like to have your changes in bulk. You can add notes where you are unsure or where further clarification is needed. Then I will read over everything, apply correction, address your notes and pull it as once. Then you can apply further refinements if you like.

**Comment by hmelman** [comment]
> I would prefer if you get the assignment just to be on the safe side. Or you could ask on the mailing list.

I'm considering both.

> > I'd love some comments on the above before I work on all the consult docstrings.
> 
> I should add this - I prefer a more time efficient approach. Instead of commenting on all small changes step by step I would like to have your changes in bulk. You can add notes where you are unsure or where further clarification is needed. Then I will read over everything, apply correction, address your notes and pull it as once. Then you can apply further refinements if you like.

I prefer a more time efficient approach too.  I wasn't intending to send each one, one at a time, but before I worked on about 40 different docstrings, I thought I could get some feedback on the first (and I think representative) one.

**Comment by minad** [comment]
> I prefer a more time efficient approach too. I wasn't intending to send each one, one at a time, but before I worked on about 40 different docstrings, I thought I could get some feedback on the first (and I think representative) one.

Okay, I think the sample you wrote above looks good.

> I'm using old style symbol quoting because I think that's what consult.el currently uses. I personally prefer it, and I'm not sure if support for the new style was added in Emacs 26 or 27.

Is there a reason to stay with the old style? What's better about the new style?

> I'm not sure everything is technically correct, but I tested all the interactive uses mentioned. I don't love the last sentence about INITIAL, but it's the most useful thing I could think to say about it. From the current docstring I removed the note about using it in an embark collect buffer because it seemed like too much of a specific example for a docstring. It's something I think is more suited to the README. Also I removed the line "This command obeys narrowing." because I don't think it does.

Let's address the technical details when the time has come. I will then make all the corrections and clarifications if needed.

**Comment by hmelman** [comment]
> Okay, I think the sample you wrote above looks good.

Great, thanks.

> Is there a reason to stay with the old style? What's better about the new style?

The old style sticks with the ascii single quotes, the new style uses the unicode curly quotes directly in the source.  Emacs has facilities to display old style as new and also to help entering new style, I just haven't used them yet.  There were big controversial discussions on the emacs devel mailing list when it was done.  If you support a version of emacs before new style support was added, then you need old style.  I tried looking for when it was added but as I said, I couldn't figure out if it was added in 26 or 27 and consult says it supports Emacs 26.

> > Also I removed the line "This command obeys narrowing." because I don't think it does.

On this one, was this line meant to refer to emacs' use of the term narrow (as in `narrow-to-region`) or to consult's meaning (narrowing to groups)?  When I said "I don't think it does" I was thinking of consult's meaning.  If it refers to emacs' meaning, I think what I have above is the right way to do this as it's similar to what other emacs commands do.

**Comment by minad** [comment]
Okay, no unicode please.

> Also I removed the line "This command obeys narrowing." because I don't think it does.

I was referring to Emacs narrowing. It is unfortunate that we have the overlap here. Maybe we should always explicitly say "narrowing to region".

**Comment by hmelman** [comment]
> I was referring to Emacs narrowing. It is unfortunate that we have the overlap here. Maybe we should always explicitly say "narrowing to region".

I'll check, but I think emacs docstrings generally assume that `narrow-to-region` will constrain a command's behavior and not comment on it unless there's something unusual about it.

Thanks for the feedback.

**Comment by minad** [comment]
I have no plans to work on documentation as of now. @hmelman If you are still interested in proposing improvements, pull requests are welcome.

**Comment by hmelman** [comment]
I will, still need a few weeks before I can get back to it.
