### ISSUE TITLE
Can't use consult-line with selectrum in pure emacs.

### ISSUE THREAD

**Issue by Gaeric** [minad/consult#257]
Reproduce:
emacs -Q
Add selectrum and consult to load-path
(selectrum-mode) to enable selectrum
exec consult-line
Type in minibuffer, the candidate will be empty.

Emacs 27.0.50 on Windows and gcc Emacs 28.0.50 on Archlinux.

It is normal in consult-buffer with selectrum and consult-line with fido.

I am not sure here is suitable for this issue.

**Comment by minad** [comment]
I cannot reproduce this issue. You have to configure the `completion-styles` properly. See https://github.com/minad/consult#bug-reports. You can use `substring` for testing. But I recommend to use `orderless` instead. Another problem could be that the Selectrum minibuffer is not resizing properly, see https://github.com/raxod502/selectrum/issues/435.

**Comment by minad** [comment]
I just gave it another try with `emacs -Q` and the **newest versions** of all packages. This works for me:

~~~ elisp
;; Execute in *scratch* buffer
(package-initialize)
(selectrum-mode)
(setq completion-styles '(orderless))
(require 'consult)
~~~

Run `M-x consult-line`...

**Comment by oantolin** [comment]
If I had to bet @Gaeric's problem is `completion-styles`. The default value is `(basic partial-completion emacs22)`, so type a letter `x` in `consult-line` will only match if some line begins with `x`. @Gaeric, try typing `*x` which uses a wildcard to match lines with an `x` anywhere in them (the wildcard are a nice feature of `partial-completion`).

**Comment by minad** [comment]
@oantolin Yes, that's probably the case. For this reason the bug reports section uses the `substring` for `completion-styles`. Maybe I should state this even more explicitly.

**Comment by Gaeric** [comment]
>The default value is `(basic partial-completion emacs22)`, so type a letter `x` in `consult-line` will only match if some line begins with `x`.

Content of buffer: 
```
4 5 6
1 2 3
```
when i use consult-line and type `4`, i can't get the line `4 5 6`
when i type `*4`, i can match this line.

**Comment by minad** [comment]
@Gaeric Okay, thank you for reporting back. The issue is the setting of the `completion-styles` variable. Consult has the requirement that you use a completion style which matches substrings, you can either use `substring` or `orderless` for example. `consult-line` is incompatible with the `basic` completion style. My strong recommendation is to give the excellent orderless package by @oantolin a try! See also the updated bug reports section for reference https://github.com/minad/consult#bug-reports.

**Comment by Gaeric** [comment]
My problem is solved, thanks a lot

**Comment by oantolin** [comment]
What happened in your example matching `4` against with `4 5 6` is that `consult-line` adds an invisible character to the beginning of each line to distinguish between identical lines, so the completion candidate corresponding to the line `4 5 6` doesn't start with `4` but with some weird unicode character.

**Comment by minad** [comment]
See also https://github.com/minad/consult/issues/237 where the `basic` completion style has been discussed.
