### ISSUE TITLE
consult-buffer is suddenly very slow when it includes recentf

### ISSUE THREAD

**Issue by jaor** [minad/consult#258]
Since a couple days ago, consult-buffer takes several seconds to display candidates when recentf mode is
enabled.  I've tried running only the items collector, and it's almost immediate; so is consult-recent-file, and marginalia doesn't
seem to have any effect.  The delay seems to appear only when the recentf candidates are collected as part of
a multi-source collection.  Anyone else experimenting this behaviour?  Thanks!

**Comment by jaor** [comment]
(i am seeing the same behaviour with emacs 27.1, emacs 28, and emacs 28 with native compilation)

**Comment by minad** [comment]
Please try the newest version. I reverted a recent commit, where I tried to make some file checking more robust. But I missed that the function indeed accesses the filesystem, which can be arbitrarily slow, e.g., tramp.

**Comment by jaor** [comment]
On Sat, Mar 20 2021, Daniel Mendler wrote:

> Please try the newest version. I reverted a recent commit, where I
> tried to make some file checking more robust. But I missed that the
> function indeed accesses the filesystem, which can be arbitrarily
> slow, e.g., tramp.

@minad, yup, that fixes the problem for me.  thanks a lot!

**Comment by minad** [comment]
Thanks!

**Comment by codygman** [comment]
> Please try the newest version. I reverted a recent commit, where I tried to make some file checking more robust. But I missed that the function indeed accesses the filesystem, which can be arbitrarily slow, e.g., tramp. See [6ced33a](https://github.com/minad/consult/commit/6ced33ac555dc8852a3fc14811bb745fad19f3c7). Hopefully this fixes the slowdown issue?

Ah, just this morning I profiled consult thinking it felt slower and saw lots of file calls.

I'll try updating too.
