### ISSUE TITLE
consult-line with initial is broken in 20210328.1105

### ISSUE THREAD

**Issue by bogolisk** [minad/consult#260]
version: 20210328.1105
commit: 3b032d17e5a9355821222ed5b732d956b3c65d81

typing in "foobar" after calling:
`(consult-line)`
is ok. calling:
`(consult-line "foobar")`
keeps saying "Match required"

**Comment by minad** [comment]
I don't see this. For me the initial argument works as expected. Maybe you did not configure the `completion-styles`?

Please try to reproduce your issue with `emacs -Q` with the configuration described in https://github.com/minad/consult#bug-reports.

**Comment by minad** [comment]
I don't see what consult-xref has to do with this? Please report back if it is possible to reproduce this with a minimal configuration.
