### ISSUE TITLE
Experiment with completion boundaries for async filtering

### ISSUE THREAD

**Issue by minad** [minad/consult#261]
After Selectrum got support for completion boundaries, I can test this. See https://github.com/raxod502/selectrum/pull/532

**Comment by minad** [comment]
The downside of using completion boundaries is that the resulting candidate includes the prefix. For this reason boundaries are not semantically the correct thing.

**Comment by oantolin** [comment]
I don't understand: why is it a problem that (full) candidates include the prefix? Isn't that part of the meaning of the word "prefix"?

**Comment by minad** [comment]
Sure, but in this case I am talking about separating the async-prefix from the completion-string, as in `#async-prefix#completion-string`. The result will then be `#async-prefix#the-selected-candidate`. This is different from file completion where you have `/dir-prefix/the-selected-candidate`. This is not a strong argument, I am just not so sure if completion boundaries are the correct solution to the problem or if a modified completion style is the better solution (as I have now).

**Comment by oantolin** [comment]
Oh, I see.

**Comment by minad** [comment]
I don't plan to do this for now. Closing.
