### ISSUE TITLE
Question: less candidates displayed in selectrum with grep and locate commands

### ISSUE THREAD

**Issue by noctuid** [minad/consult#266]
This may be a dumb question or an issue with selectrum, but I'm not exactly sure what's going on. I have `selectrum-num-candidates-displayed` set to 20, and most consult commands work, but the async commands (e.g. grep and locate) seem to display 10-13 candidates even though there are more. Do you have any idea why this might be happening?

**Comment by minad** [comment]
This sounds like a bug in Selectrum. Can you try the setting `selectrum-max-window-height` instead?

**Comment by noctuid** [comment]
Yes, it works fine then.

**Comment by noctuid** [comment]
I'm also seeing strange behavior with `marginalia-mode` enabled. For example, `describe-variable` only show a couple candidates until I start typing. Changing `selectrum-max-window-height` doesn't matter here. Do you think marginalia could be at fault, or should I go ahead and make an issue on the selectrum repo?

**Comment by minad** [comment]
There are multiple ways to approach this - I assume you updated everything to the newest versions and checked with emacs -Q? You can also use my Vertico package to cross check. In any case you may want to ask on the Selectrum tracker and describe your problem precisely. I have not seen like this before, sorry. I would have expected that such bugs are sorted out by now!
