### ISSUE TITLE
consult-ripgrep when trying to add globs

### ISSUE THREAD

**Issue by iyefrat** [minad/consult#268]
I want to use consult to to ripgrep around a project file, including hidden files, but not the `.git` directory. To this end, I want to use 
this command (with `prompt`, `directory` and `input` replaced with something sensible):

```lisp
(consult--grep prompt "rg --null --line-buffered --color=ansi --max-columns=250 
  --no-heading --line-number --hidden -g '!.git' . -e ARG OPTS" directory input)
```
However, the output of this is just 0 matches. If I try this command in a terminal it works as expected. If i get rid of the `-g '!.git'` then it works fine, so I'm pretty sure the problem has to be with globbing. I have tested this on vanilla emacs with just `selectrum` and `consult` installed.

Thank you for all your work on this plugins and others!

**Comment by minad** [comment]
This works:

~~~ elisp
(consult--grep "Grep" "rg --null --line-buffered --color=ansi --max-columns=250 \
--no-heading --line-number --hidden -g \"!.git\" . -e ARG OPTS"
               default-directory "")
~~~

You can always check the `_*consult-async-log*` buffer for debugging as documented in the README. Note the space at the beginning of the buffer name, the buffer is hidden.

**Comment by iyefrat** [comment]
Thank you for the quick response! I did check `_*consult-async-log*`, it just didn't have any information other than 
```
consult--async-process started ("rg" "--null" "--line-buffered" "--color=ansi" "--max-columns=250" "--no-heading" 
"--line-number" "--hidden" "-g" "'!.git'" "." "-e" "defun")

Process rg stderr<1> finished
consult--async-process sentinel: event=exited abnormally with code 1 lines=0
```
and I wasn't quite sure how to proceed. No clue why the first time around I thought I had to quote the glob, probably got on that when trying to solve something else. Sorry for the fuss!
