### ISSUE TITLE
consult--read with an alist

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#269]
I am trying to use consult--read for my own command and enable preview. However, it seems that it does not work with an alist, while `completing-read` does. Is there a reason for this?

As a MWE, consider:
```elisp
(consult--read
 '(("A" . "AA")
   ("B" . "BB")
   ("C" . "CC"))
 ;;'("A" "B" "C")  ;; This works on the other hand
 :prompt "Test: "
 :history t
 :sort nil
 :category 'consult-yank
 :require-match nil
 :lookup #'consult--lookup-member
 :state
 (consult--region-preview (point) (point)
                          'consult-preview-yank))
```

If you run the previous code, the list of candidates appear, but the live preview does not work and the returned value is `nil` regardless of the selected candidate.

**Comment by minad** [comment]
It works if you use the correct lookup function, in this case `consult--lookup-cdr`.
