### ISSUE TITLE
Preview based on prompt

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#270]
Is there a way to enable preview based on the prompt as well as the candidates?
When I run this code

```elisp
(consult--read
 '("A" "B" "C")
 :prompt "Test: "
 :history t
 :sort nil
 :category 'consult-yank
 :require-match nil
 :lookup #'consult--lookup-member
 :state
 (consult--region-preview (point) (point)
                          'consult-preview-yank))
```

If I select one of the candidates, the preview works. However, I input a non-matching candidate in the prompt and select the prompt the preview state function is not called. 

How can I enable the preview for the prompt when it is non-matching?

**Comment by minad** [comment]
The same answer as in #269, by adjusting the lookup function. In this case you don't need a lookup function at all. You can also write your own lookup functions which do whatever you like given the input string, candidate list and current candidate. Please don't open separate issues for such discussions, we can continue the discussion here or in the previous issue #269. I usually close issues, which I consider resolved. But this does not mean that we cannot continue the discussion in the particular issue.
