### ISSUE TITLE
consult--jump-preview restores narrowing of a growing buffer

### ISSUE THREAD

**Issue by jakanakaevangeli** [minad/consult#271]
To reproduce, make a growing buffer, for example, execute
`while sleep 1; do date; done` in a shell buffer.
Now execute `consult-bookmark` and cancel it with C-g after some time.
The buffer gets narrowed in spite of it not being narrowed before.

Perhaps the saved `point-max-marker` should have its insertion type set to `t`.

**Comment by minad** [comment]
This should be easy to fix. What is different between `save-restriction` and the `consult--jump-preview` restoration. I assume `save-restriction` gets this right?

**Comment by minad** [comment]
~~~ c
      /* END must move forward if text is inserted at its exact location.  */
      XMARKER (end)->insertion_type = 1;
~~~

**Comment by minad** [comment]
I wasn't aware that insertion type is a thing. But this is the exact difference as you already pointed out. Thanks.

**Comment by jakanakaevangeli** [comment]
Thank you!
