### ISSUE TITLE
Must (require 'consult) to switch to *messages*

### ISSUE THREAD

**Issue by hmelman** [minad/consult#273]
I load consult (and other packages) using `package.el`.  I have the following in my init:

``` emacs-lisp
(require 'consult) 			; not really needed, but can't switch to *Messages* w/o?
(custom-set-variables
 '(consult-after-jump-hook '(reposition-window xref-pulse-momentarily))
 '(consult-locate-command "mdfind -name OPTS ARG")
 '(consult-find-command '("fd" "--color=never" "--full-path"))
 '(consult-config '((consult-register :initial "^")
		    (consult-line :default nil)
		    (consult-buffer :preview-key nil)))
 '(consult-narrow-key "|")		; Consult suggests < or C-+ but use | for filtering
 '(register-preview-delay 0)
 '(register-preview-function #'consult-register-preview)
)
```

My understanding is that the `(require 'consult)` isn't needed because of the package initialization mechanism.  So I commented it out, saved, byte-compiled and restarted emacs.  BUT if I use `consult-buffer` the candidates do NOT include `*Messages*` or `*Scratch*`.  The other 50 candidates (recentf and bookmarks) are the same.  If in this session I do `M-: (require 'consult)` they still do NOT appear.

I configure embark after this in my init.  Most of my config is the suggested stuff, predominantly keybindings and a couple of add-advice commands. What can I do to track down the problem?

Emacs 27 and the latest versions of the packages from melpa

**Comment by minad** [comment]
I have not seen such an issue before. Can you create a minimal reproducible with emacs -Q? Requiring consult is not needed because of autoloading the commands.

Note that using `custom-set-variables` like this per package is wrong. I think only a single call to `custom-set-variables` is allowed in the whole init.el file.

**Comment by hmelman** [comment]
> I have not seen such an issue before. Can you create a minimal reproducible with emacs -Q? Requiring consult is not needed because of autoloading the commands.

I haven't succeeded reproducing with `-Q`.  It's difficult because I have to do the package-initialize myself and then other config stuff.  I'm quite certain that just commenting out that one require changes the behavior I see.  I'd like to approach it from the other side and see what consult is doing internally.

> > Note that using `custom-set-variables` like this per package is wrong. I think only a single call to `custom-set-variables` is allowed in the whole init.el file.

I don't see anything documenting this limitation and it's worked fine for a while.

**Comment by hmelman** [comment]
Nevermind, my user error.  I had an experimental consult-buffer-source for dired buffers (so I could narrow to them) and accidentally redefined `consult--source-buffer`.  What's weird is that this has been in my init for 6 weeks, I'm not sure how/why the behavior changed today (I was definitely switching to *Messages* yesterday).

**Comment by minad** [comment]
It could be a weird side effect of that 4d0a8b9b5a7f76e7055726fb79ed73d01a49aa01. But you confirm that you don't see an issue with the unmodified buffer sources variable?

**Comment by hmelman** [comment]
> But you confirm that you don't see an issue with the unmodified buffer sources variable?

I do.
