### ISSUE TITLE
consult-goto-line behaves differently than goto-line when the buffer is narrowed

### ISSUE THREAD

**Issue by hmelman** [minad/consult#275]
`consult-goto-line` behaves differently than `goto-line` when the buffer is narrowed.  To see this, create a buffer with 10 lines, and then narrow it to say lines 4-6 and try to move to lines before and after the narrowed area.  `goto-line` will move point to the beginning or end of the region as if it were doing a best attempt.  If you then widen the buffer point stays at the best attempt instead of being at the actual asked for location.  `consult-goto-line` generates an error "Line number out of range" and doesn't move point.  I'm not sure if this is intended behavior or not.

**Comment by minad** [comment]
Thank you for noticing, I am unsure if I even checked `consult-goto-line` against `goto-line`. But yes, the current behavior is intended. I don't think the "best effort" makes much sense, maybe it is merely a result of not checking properly and moving the point until the boundary is hit. The point of this command is to move to a precise location. If the location is invalid, don't move. I think this is reasonable - I would say we keep it as is.

**Comment by hmelman** [comment]
Agreed.  I'll just follow up here, is it meant not to be called interactively?  Unlike `goto-line` the line number is not an argument, it's read in the body of the command.  So it doesn't really work if called from Lisp (fine) but also doesn't work when called with a numeric argument, which I think would be nice.

**Comment by minad** [comment]
Yes, you are right about that.
