### ISSUE TITLE
Can't see current candidate in consult-buffer with icomplete-vertical.

### ISSUE THREAD

**Issue by s-kostyaev** [minad/consult#278]
On emacs with native compilation. It is still useful for opened buffers, because I can see it by the preview, but useless with recent files. Maybe it's not working correctly with multi sources because of titles.
![consult-buffer](https://user-images.githubusercontent.com/8576745/115182096-931c2080-a103-11eb-8357-8f364b6d8451.png)

BTW, I can see selected candidate with vertico instead of icomplete-vertical. Also I can see selected candidate with icomplete-vertical and single source.

**Comment by minad** [comment]
I don't understand this issue. Please be more precise. Did you use emacs -Q? What exactly does not work?

The function `consult-preview-mode` has been removed, please remove it from your config. Do you use the most recent version of all packages?

**Comment by minad** [comment]
Ah, I understand now. This is a bug in icomplete-vertical, see oantolin/icomplete-vertical#33.

**Comment by oantolin** [comment]
I believe I fixed the bug in oantolin/icomplete-vertical@4e3955b07be1f837f13125fcf3dc29218fc73dbd.
