### ISSUE TITLE
`consult-grep` failed to work on tramp

### ISSUE THREAD

**Issue by condy0919** [minad/consult#280]
<kbd>C-x C-f</kbd> `/ssh:remote:` then `M-x consult-grep` still searchs on localhost.

When on `tramp`, the `default-directory` can be `/ssh:remote-host.com:/home/user/proj/src/`

`(consult--format-directory-prompt "prompt" default-directory)` returns `("prompt: " . "/ssh:remote-host.com:/home/user/proj/src/")`, it's okay.

But in `consult--grep` function, even the `default-directory` is the `cdr` of the result, it still spawns a grep process locally.

**Comment by minad** [comment]
> But in consult--grep function, even the default-directory is the cdr of the result, it still spawns a grep process locally.

Why does it do that? Shouldn't the default-directory determine where the process is spawned?

**Comment by condy0919** [comment]
Yes, I'm still confused why

**Comment by condy0919** [comment]
I found `grep` correct on tramp. willing to help you ;-)

**Comment by minad** [comment]
I know that `M-x grep` is supposed to work with tramp and it does. But `consult-grep` just uses `make-process` which should also work with tramp. If it does not, some setting is wrong. Maybe `:connection-type`, you can try adjusting the `make-process` arguments.

**Comment by condy0919** [comment]
Well done bro
