### ISSUE TITLE
consult-buffer minibuffer broken when lots of exwm windows open quickly

### ISSUE THREAD

**Issue by codygman** [minad/consult#282]
This is meant more as a warning to other exwm users and I don't necessarily think it's a consult bug (but I guess it could be).

Basically when say 100 windows are restored by qutebrowser under exwm then the consult-buffer window will be much smaller than usual. You can sometimes fix it by either:

1) pressing `C-n` until the highlighted item is well of the screen (but not visible)
2) typing some stuff and causing some sort of refresh I guess?

Then the consult-buffer minibuffer becomes normal size if one of those worked and things work as expected. Sometimes it's not possible to fix it and you have to restart emacs and exwm.

This happens even with a minimal config:

<details>
  <summary markdown="span">minimal selectrum+consult+exwm config</summary>

```emacs-lisp
;; -*- lexical-binding: t -*-

(set-frame-font "DejaVu Sans Mono-16")
(load-theme 'modus-vivendi t)

(require 'use-package)

(use-package selectrum
  :config
  (setq selectrum-refine-candidates-function #'orderless-filter)
  (setq selectrum-highlight-candidates-function #'orderless-highlight-matches)
  ;; I think this shouldn't be necessary because of
  ;; https://github.com/raxod502/selectrum/commit/a09ecdea6609fe69144c44959dd016b32d14bf03
  ;;(setq selectrum-fix-vertical-window-height t)
  (selectrum-mode +1)
  )

(use-package orderless
    :ensure t
    :config
    (setq orderless-skip-highlighting (lambda () selectrum-is-active))
    (setq selectrum-highlight-candidates-function #'orderless-highlight-matches)
    :custom (completion-styles '(orderless)))

(use-package consult
  :init
  ;; Configure register preview function.
  ;; This gives a consistent display for both `consult-register' and
  ;; the register preview when editing registers.
  (setq register-preview-delay 0
        register-preview-function #'consult-register-format)

  ;; Configure other variables and modes in the :config section, after lazily loading the package
  :config
  (setq consult-preview-key 'any)
  (defun consult-buffer-state-no-x ()
  "Buffer state function that doesn't preview X buffers."
  (let ((orig-state (consult--buffer-state))
          (filter (lambda (cand restore)
                    (if (or restore
                            (let ((buffer (get-buffer cand)))
                              (and buffer
                                   (not (eq 'exwm-mode (buffer-local-value 'major-mode buffer))))))
                        cand
                      nil))))
      (lambda (cand restore)
        (funcall orig-state (funcall filter cand restore) restore))))

(setq consult--source-buffer
        (plist-put consult--source-buffer :state #'consult-buffer-state-no-x))
  ;; (setq consult-preview-key nil)

  :custom-face
  (consult-preview-cursor ((t (:inherit nil)))))

(use-package app-launcher)

(use-package exwm
  :init
  (setq exwm-input-global-keys
        `(([?\s-r] . exwm-reset)
          ([?\s-i] . exwm-input-release-keyboard)
          ;; convenience keybinding, meant to mimic `esc' in Vim bindings
          ([?\s-\ ] . app-launcher-run-app)
          ([?\s-n ] . next-buffer)
          ([?\s-p ] . previous-buffer)
          ([?\s-b ] . consult-buffer)
          ([?\s-\[] . exwm-reset)))
  (defun exwm-rename-buffer ()
    (interactive)
    (exwm-workspace-rename-buffer
     (concat exwm-class-name ": "
             (if (<= (length exwm-title) 150) exwm-title
               (concat (substring exwm-title 0 149) "...")))))

  ;; Add these hooks in a suitable place (e.g., as done in exwm-config-default)
  (add-hook 'exwm-update-class-hook 'exwm-rename-buffer)
  (add-hook 'exwm-update-title-hook 'exwm-rename-buffer)
  :config
  (exwm-enable))

```
</details>

My workaround is just to disable session restoration or use lazy loading (when qutebrowser fixes it).

**Comment by minad** [comment]
Could this be related to https://github.com/raxod502/selectrum/issues/536 or https://github.com/raxod502/selectrum/issues/435? Selectrum has a few resizing issues. You may want to try my [Vertico package](https://github.com/minad/vertico] to check if you also see the resizing problem here. However this could also be an underlying Emacs bug (The Vertico and Selectrum resizing code does not differ by much). Note that I am not suggesting to switch away from Selectrum; Vertico is more experimental.

Anyways I close this here since I can assure you that this is not a Consult issue. Consult only generates the candidates, the UI does the rest, in particular the minibuffer resizing.

**Comment by minad** [comment]
> Basically when say 100 windows are restored by qutebrowser under exwm then the consult-buffer window will be much smaller than usual. You can sometimes fix it by either:

Two more things: A screenshot may be useful. And then I wonder if you only see this for `consult-buffer`? Then it could be related to the grouping, you can disable that by setting `selectrum-group-format` to `nil`. There is also a small issue in Selectrum related to that (https://github.com/raxod502/selectrum/issues/491).

**Comment by codygman** [comment]
Thanks for the help!

This actually happens just after opening a few windows of qutebrowser I found out this morning. I'll try setting `selectrum-group-format` to nil.

> You may want to try my Vertico package to check if you also see the resizing problem there. However this could also be an underlying Emacs bug. The Vertico and Selectrum resizing code does not differ by much. Note that I am not suggesting to switch away from Selectrum; Vertico is more experimental.

I've been eyeing it since after trying corfu, I'll try it later if I can just to see if the error is present.

**Comment by minad** [comment]
Just to make sure - could the issue have something to do with `consult-buffer` previewing, can you set the preview-key to nil? And not install custom sources?

**Comment by minad** [comment]
Just out of interest, do you see the bug with Vertico? Or didn't you try this?
