### ISSUE TITLE
Conflict with mini-frame?

### ISSUE THREAD

**Issue by BooAA** [minad/consult#286]
When using mini-frame, sometimes calling `consult-buffer` (or `consult-buffer-other-window`) makes minibuffer input and candidates disappear.

Version: Emacs28 native-comp commits: 062e599
OS: Debian/Sid
Config:
```emacs lisp
(use-package selectrum
  :custom (selectrum-max-window-height '15)
  :hook (after-init . selectrum-mode))

(use-package selectrum-prescient
  :hook ((selectrum-mode . selectrum-prescient-mode)
         (selectrum-prescient-mode . prescient-persist-mode)))

(use-package marginalia
  :hook (after-init . marginalia-mode))

(use-package consult
  :custom (consult-async-refresh-delay 0.1)
  :bind (("C-c h" . consult-history)
         ("C-c m" . consult-mode-command)
         ("C-c b" . consult-bookmark)
         ("C-c k" . consult-kmacro)
         ("C-x M-:" . consult-complex-command)
         ([remap switch-to-buffer] . consult-buffer)
         ([remap switch-to-buffer-other-window] . consult-buffer-other-window)
         ([remap switch-to-buffer-other-frame] . consult-buffer-other-frame)
         ([remap apropos] . consult-apropos)))

(use-package mini-frame
  :defer nil
  :custom ((mini-frame-show-parameters '((top    . 0.2)
                                         (width  . 0.8)
                                         (left   . 0.5)
                                         (left-fringe . 4)
                                         (right-fringe . 4)
                                         (height . 15)))
           (mini-frame-color-shift-step 6))
  :hook (after-init . mini-frame-mode))
```

I'm not sure which packages listed above actually make this issue. `switch-to-buffer` and `switch-to-buffer-other-window` with mini-frame doesn't have this problem. Consult with normal minibuffer also works well. So I guess maybe there are some conflicts between consult's preview feature and how mini-frame handle frames and windows. If necessary, I can open same issue at mini-frame as well.

Demo video:

https://user-images.githubusercontent.com/32809182/115949645-06a99d80-a509-11eb-81f5-0ea80e67fc35.mp4

**Comment by minad** [comment]
Yes, there are miniframe issues - but these issues are due to miniframe. I don't recommend miniframe in its current form since it is problematic. If you want to use miniframe, you can disable the Consult preview.

**Comment by minad** [comment]
See also #204, #178, https://github.com/muffinmad/emacs-mini-frame/pull/29.

**Comment by minad** [comment]
In case you open another issue on the miniframe issue tracker - the problem is with high probability that Consult makes assumptions about how the minibuffer behaves. Functions like `minibuffer-active-window` and `minibuffer-selected-window` should work, then the `post-command-hook` should be called in the correct context (the minibuffer context) and so on. If any of those assumptions is subtly violated, Consult previews may not work. Maybe some of the assumptions made in Consult can be relaxed, but generally I think it would be better to improve the "minibuffer emulation" of miniframe.
