### ISSUE TITLE
Propose a few commands for inclusion in Emacs itself

### ISSUE THREAD

**Issue by minad** [minad/consult#289]
* `consult-multi-occur` (drop in for `multi-occur`)
* `consult-apropos` (drop in for `apropos`)
* `consult-complex-command` (drop in for `repeat-complex-command` in simple.el, see also `command-history` in chistory.el)
* `consult-file-externally` (discussed previously as `dired-open`)
* `consult-history` (general history browsing command)

**Comment by hmelman** [comment]
I assume the first two are basically getting the builtins to use some form of completing-read, that would be great.

FYI for `consult-file-externally`, I think it such a command should be in emacs but there have been previous discussions about a similar `dired-open` command which many have implemented but never seem to make it into vanilla emacs ([bug14119](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=14110) and [bug18132](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=18132)).

**Comment by minad** [comment]
Well, these are from 2013 and 2014. It is time for another try ;)

**Comment by hmelman** [comment]
Absolutely!

**Comment by astoff** [comment]
The register load/store commands don't even have anything to do with completing read, right?

**Comment by minad** [comment]
@astoff That's right. However they share a bit of the register formatting code with `consult-register`, which uses `completing-read`. And then these commands invent a bit their own interface, which is probably difficult to get into Emacs proper. In contrast, I am convinced that the commands mentioned above should really be part of Emacs. They are simpler and fix some deficiencies of the existing commands. For me personally, it will also depend a bit on how the current discussions on emacs-devel develop and how well I can work with the Emacs development model. In case you want to make proposals yourself to Emacs, feel free to do so and feel free to propose commands from here. I appreciate that you are also proposing the isearch mb improvements.

**Comment by minad** [comment]
No plans on doing this right now.
