### ISSUE TITLE
Completion in region breaks if completion-styles is buffer local

### ISSUE THREAD

**Issue by astoff** [minad/consult#291]
This happens in my setup with Orderless in an Eglot-managed buffer, since Eglot sets `completion-styles` locally. The following advice solves the problem:

```elisp
(advice-add 'consult-completion-in-region
            :around
            (lambda (&rest args)
              (cl-letf* (((default-value 'completion-styles) completion-styles))
                (apply args))))
```

PS: I'm wondering if Eglot is doing the most appropriate thing here. Based on [this discussion](https://github.com/minad/corfu/issues/5), it seems justified to override the completion style (LSP doesn't provide a reliable way to infer the completion prefix, among other issues). But wouldn't it be better to set a `completion-category-overrides`, which can be done globally, and provide a category in the completion table?

**Comment by minad** [comment]
There is this line in `consult-completion-in-region`:

~~~ elisp
(completion-styles (or (plist-get config :completion-styles) completion-styles))
~~~

If you don't set `:completion-styles` in the config the value is not overwritten. This means Eglot's override is in effect. If you want Eglot to stay out of this there is the `eglot-stay-out-of` variable. What exactly does not behave here according to your expectations?

Regarding the PS - what Eglot is doing is certainly dubious. I haven't yet investigated Eglot closer but I am pretty sure there is a better solution (See my comments in https://github.com/minad/corfu/issues/5). And your suggestion of using an eglot category and using an override seems better.

**Comment by minad** [comment]
Weird. I think I forgot the semantics of let-bound buffer-local values. The let-bound value will then only be effective locally. See also my macro `consult--local-let` :see_no_evil:

**Comment by astoff** [comment]
`cl-letf` seems to accept `(buffer-local-value ...)` as a place to assign to.

**Comment by minad** [comment]
Yes, I could use that instead of `consult--local-let`. I think I wrote `consult--local-let` before I was aware of how these gv expanders work. However using `cl-letf` with `buffer-local-value` has a small flaw, it leaves buffer local variables behind.

~~~ elisp
(macroexpand '(cl-letf (((buffer-local-value 'test (current-buffer)) 123)) body))
~~~

~~~ elisp
(let*
    ((v
      (current-buffer))
     (old
      (buffer-local-value 'test v)))
  (unwind-protect
      (progn
        (with-current-buffer v
          (set
           (make-local-variable 'test)
           123))
        body)
    (let*
        ((v old))
      (with-current-buffer v
        (set
         (make-local-variable 'test)
         v)))))
~~~

This means the let is not side-effect free, since if the variable is setq afterwards it will setq the local value and not the global value if it would be side-effect free. This is actually an Emacs bug. Maybe I should report it.

**Comment by minad** [comment]
Small reproducible:

~~~ elisp
(defvar global-var 1)
(cl-letf (((buffer-local-value 'global-var (current-buffer)) 2)) (ignore))
(setq global-var 3)
(default-value 'global-var)
~~~
