### ISSUE TITLE
Minibuffer not scrolling through all results with consult-ripgrep

### ISSUE THREAD

**Issue by ashton314** [minad/consult#294]
# Summary
`consult-ripgrep` is working fine; I get all the results I expect to see. There is one problem, and that is when I use the arrow keys to scroll down through the list of results, there are some results at the end of the list that I can navigate to, but do not show up in the minibuffer—it's like the cursor scrolls out under the minibuffer's window.

# Screen shots

Starting out:
<img width="707" alt="Screen Shot 2021-04-27 at 15 51 08" src="https://user-images.githubusercontent.com/2874507/116317386-808f9000-a770-11eb-98ad-5a0fac362bc3.png">

Scrolled down so that I'm on what appears to be the last result:
<img width="707" alt="Screen Shot 2021-04-27 at 15 51 26" src="https://user-images.githubusercontent.com/2874507/116317501-a321a900-a770-11eb-9e8b-982014a9771b.png">

But pressing down one more time…
<img width="707" alt="Screen Shot 2021-04-27 at 15 51 31" src="https://user-images.githubusercontent.com/2874507/116317536-ae74d480-a770-11eb-8c43-735de4713c61.png">

# Example config

Minimum configuration to get this to manifest:

```elisp
(defvar bootstrap-version)
(setq straight-repository-branch "develop")

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package consult
  :bind (("s-r r" . consult-ripgrep))
  :init
  (setq register-preview-delay 0
        register-preview-function #'consult-register-format)
  :config
  (autoload 'projectile-project-root "projectile")
  (setq consult-project-root-function #'projectile-project-root))

(use-package selectrum
  :config
  (selectrum-mode +1))

(use-package projectile
  :config
  (setq projectile-completion-system 'selectrum))
``` 

# Version information

Emacs version: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H15)) of 2021-01-14
OS: macOS 10.15.7

I ran this from the root of my [dotfiles](https://github.com/ashton314/.dotfiles) repo, but it's manifested elsewhere, so the specific repo shouldn't be important.

**Comment by minad** [comment]
I can reproduce this with Selectrum but not with Vertico. I think this is a resizing bug/problem with the group headers. See https://github.com/raxod502/selectrum/issues/491.

**Comment by ashton314** [comment]
Thanks—sorry about the dupe; didn’t know how else to describe this. I ❤️ this package so much; stay awesome!

**Comment by minad** [comment]
Thanks!
