### ISSUE TITLE
Help menu on narrow key shows ranges

### ISSUE THREAD

**Issue by gagbo** [minad/consult#298]
Hello,

As I shortly listed [here](https://github.com/gagbo/consult-lsp/issues/9), I think there's an issue with the which-key popup that appear when hitting the narrow key. It looks like all keys that are consecutive in ascii codes get merged into some ranges, and it doesn't show all the possibilities because of it. The shorter example shown in `consult-lsp-diagnostics` shows the `h` for "Hints" and `i` for "Infos" being merged and shown as "Infos" with a special and different color (`which-key-command-description-face` instead of `which-key-local-map-description-face`)

![LSP Diagnostics narrow](https://user-images.githubusercontent.com/10496163/116622342-d1f07880-a944-11eb-8c75-f15dcf7af22d.png)

And the other image on the issue shows a case with a lot more hits for `consult-lsp-symbols` categories. Is there something I misconfigured to have this behaviour instead of 1 entry per narrow category ?

**Comment by minad** [comment]
Yes, I am aware of this issue. I don't know if I have a chance to do anything about it, except by changing the implementation of narrowing in Consult, by using separate narrow commands `consult-narrow-a`, `consult-narrow-b`, etc. Consult uses a single `consult-narrow` command for each of the narrow keys and looks up the `last-input-event`. 

Maybe https://github.com/justbur/emacs-which-key/pull/282 will help which-key to distinguish different menu items. I am unsure about the status of this PR. In any case it is worth a bug report on the which-key tracker. Different which-key-pseudo-keys and different menu-items should not be merged like this.

I have stopped using which-key in the meantime. Instead, I set `prefix-help-command` to `embark-prefix-help-command`. Then I can trigger the key help using `C-h` as usual. Embark opens a `completing-read` interface which is the perfect UI to search for keybindings and commands (Similar to counsel-descbinds). I find this better than which-key in two ways - I have to trigger the popup manually, which I prefer of the timer based trigger and more importantly I can search for the command and key.

**Comment by minad** [comment]
I am currently binding the key and a which-key-pseudo-key. I hope that I can change this to use standard Emacs menu items as soon as https://github.com/justbur/emacs-which-key/pull/282 gets merged.

https://github.com/minad/consult/blob/7480f020e57036ef14c2fda1d83c830583b2a53b/consult.el#L757-L768

In case you want to improve the behavior you can adjust this function accordingly, by generating unique command names.

**Comment by gagbo** [comment]
I was mostly wondering if there was anything I could do to change this, I actually don't use narrow key too much (usually I know what I'm looking for so I use the prefix)

**Comment by minad** [comment]
> I was mostly wondering if there was anything I could do to change this, I actually don't use narrow key too much (usually I know what I'm looking for so I use the prefix)

Yes, by disambiguating the command name somehow like this:

~~~ elisp
(let ((sym (intern (format "consult-narrow-%c" key))))
  (fset sym #'consult-narrow)
  (define-key map ... sym))
~~~
