### ISSUE TITLE
List of symbols forbidden in consult--read

### ISSUE THREAD

**Issue by angrybacon** [minad/consult#302]
Since this commit f19d9a3148ce0992781930d0e02ebdf4650de19d it is no longer possible to use `face-list` as a source for candidates directly. 

My consult command looks like this: 

```lisp
(defun me/consult-faces ()
  "Search for faces.
Default to the face at point using `get-text-property'."
  (interactive)
  (let* ((candidates (consult--with-increased-gc (face-list)))
         (faces (get-text-property (point) 'face))
         (face (if (listp faces) (car faces) faces)))
    (consult--read candidates
                   :category 'face
                   :default face
                   :lookup (lambda (_input _candidates match) (describe-face match))
                   :prompt "Face: ")))
```

> Both (functionp '(lambda)) and (functionp '(closure)) returns t.

It's not clear to me what the commit message is referring to and what it is trying to prevent by forbidding symbol lists.

With the following change 

```diff
   (cl-assert (or (functionp candidates)     ;; async table
                  (obarrayp candidates)      ;; obarray
                  (hash-table-p candidates)  ;; hash table
                  (not candidates)           ;; empty list
                  (stringp (car candidates)) ;; string list
-                 (symbolp (car candidates)) ;; symbol list
                  (and (consp (car candidates)) (stringp (caar candidates)))   ;; string alist
                  (and (consp (car candidates)) (symbolp (caar candidates))))) ;; symbol alist
```

The assert from `consult-read` (obviously) fails and I'm not sure what the expected format for the list of candidates should be in my case.

> consult--read: Assertion failed: (or (functionp candidates) (obarrayp candidates) (hash-table-p candidates) (not candidates) (stringp (car candidates)) (and (consp (car candidates)) (stringp (caar candidates))) (and (consp (car candidates)) (symbolp (caar candidates))))

**Comment by minad** [comment]
Symbol lists are not allowed by `completing-read`, since `completing-read` has to distinguish lists from functions, since both functions and lists can be passed as `collections` argument. `(lambda)` is recognized as a symbol list *and* as a function. Symbol lists work only by accident, therefore I have them forbidden now.

**Comment by angrybacon** [comment]
Oh ok thanks for the clarification.

> You can convert the candidate list to strings before passing them

Where does the `:category 'face` magic happen? I was surprised `marginalia` was still able to provide information about faces with my change:

```diff
 (defun me/consult-faces ()
   "Search for faces.
 Default to the face at point using `get-text-property'."
   (interactive)
-  (let* ((candidates (consult--with-increased-gc (face-list)))
+  (let* ((candidates (mapcar 'symbol-name (face-list)))
          (faces (get-text-property (point) 'face))
          (face (if (listp faces) (car faces) faces)))
-    (consult--read candidates
+    (consult--read (consult--with-increased-gc candidates)
                    :category 'face
                    :default face
                    :lookup (lambda (_input _candidates match) (describe-face match))
                    :prompt "Face: ")))
```

![image](https://user-images.githubusercontent.com/5608624/116999857-86d9bb00-ace0-11eb-9d7e-0250b8fa791f.png)

**Comment by minad** [comment]
See `marginalia-annotate-face`, there the candidate string is converted to a symbol. What is the command of yours doing in contrast to `describe-face`?
