### ISSUE TITLE
Supporting `delete-selection-mode`

### ISSUE THREAD

**Issue by okamsn** [minad/consult#304]
`delete-selection-mode` is a built-in feature that allows commands to remove text in the region before operating.

For supporting `consult-yank` and `consult-yank-pop`, all that was needed for me was

``` elisp
(put 'consult-yank-pop     'delete-selection 'yank)
(put 'consult-yank         'delete-selection 'yank)
```

However, neither types `t` nor `yank` worked for me with `consult-yank-replace`.  This command doesn't seem to be mentioned in the README. Is it meant to be used?

The documentation of the function `delete-selection-helper` states

> Delete selection according to TYPE:
> - `yank`: For commands which do a yank; ensures the region about to be deleted isn't immediately yanked back, which would make the command a no-op.
>
> - `supersede`: Delete the active region and ignore the current command, i.e. the command will just delete the region.  This is for commands that normally delete small amounts of text, like a single character -- they will instead delete the whole active region. 
>
> - `kill`: kill-region is used on the selection, rather than delete-region.  (Text selected with the mouse will typically be yankable anyhow.)
>
> - FUNCTION: For commands which need to dynamically determine this  behavior.  FUNCTION should take no argument and return a value acceptable as TYPE, or nil.  In the latter case, FUNCTION should itself do with the active region whatever is appropriate.
>
> - Other non-nil values: The normal case: delete the active region prior to executing the command which will insert replacement text.

Please consider adding support for this feature.

**Comment by minad** [comment]
I reworked the commands slightly to align them with Emacs 28 and added the delete-selection properties. Please give it a check.

Regarding `consult-yank-replace`, I am not sure how to proceed. This is a variant of `consult-yank-pop`, which allows replacing the yanked text with a selected item from the kill ring. Maybe the delete-selection property as I have put it now does not make sense?

This command is mainly useful if you put the yank commands in a hydra (see my documentation https://github.com/raxod502/selectrum/wiki/Useful-Commands#yank-ring-menu).

**Comment by okamsn** [comment]
> I reworked the commands slightly to align them with Emacs 28 and added the delete-selection properties. Please give it a check.

Thank you. It works for me.

> Regarding `consult-yank-replace`, I am not sure how to proceed. This is a variant of `consult-yank-pop`, which allows replacing the yanked text with a selected item from the kill ring. Maybe the delete-selection property as I have put it now does not make sense?

I think that is does. Both `consult-yank-replace` and `consult-yank-pop` can work alone without first calling `yank`, inserting text like `yank`. For that usage (as far as I can tell), they are not different from `consult-yank` and have no reason to differ in the ability to paste over a region of text.

I myself use `yank` and `consult-yank-pop`, but it is easy for someone else to prefer `yank` with `consult-yank-replace` instead. It is good for all versions of the command to have the "pasting over" ability.
