### ISSUE TITLE
Select initial input by default

### ISSUE THREAD

**Issue by ktfleming** [minad/consult#306]
I sometimes use `consult-ripgrep` with the symbol at point as initial input, and sometimes use it with no initial input, just typing in the text I want to search for. I have these mapped to separate keys, but I thought I could reduce a bit of friction by combining them into one command. The behavior I was thinking of was: always use the symbol at point as initial input, but upon typing any character, delete the initial input and insert text into the minibuffer as normal.

I don't necessarily think that this should be added to consult itself, but I thought I could get what I wanted by using hooks and/or advice to automatically set the region to the initial input upon calling `consult-ripgrep` and then temporarily turning on `delete-selection-mode`, but I can't find any obvious place to hook into `consult--read` in order to set the region. Do you think this kind of behavior is possible to set up? Thanks!

**Comment by oantolin** [comment]
Just to make sure you know: if right after starting `consult-ripgrep` you press `M-n` it searches for the symbol at point!

If that's not enough and you do want _exactly_ the interface you described (although I'd recommend sticking with `M-n` since many Emacs commands arrange for it to insert something useful in the minibuffer), you could do this:

```elisp
(defun my-consult-ripgrep ()
  "Run consult grep with symbol at point as default.
The symbol at point will be the contents of the active region and
`delete-selection-mode' will be on."
  (interactive)
  (minibuffer-with-setup-hook
      (lambda ()
        (when-let ((symbol (with-minibuffer-selected-window
                             (thing-at-point 'symbol))))
          (set-mark (point))
          (insert symbol)
          (unless delete-selection-mode
            (delete-selection-mode)
            (add-hook 'minibuffer-exit-hook
                      (lambda () (delete-selection-mode -1))))))
    (consult-ripgrep)))
```

**Comment by ktfleming** [comment]
@oantolin I didn't know about `M-n`, thanks for letting me know! That does indeed seem useful, I'll try it out. And thanks for the help on the function as well, it looks like `minibuffer-with-setup-hook` was what I was missing.
