### ISSUE TITLE
Preview when moving in the *Completions* buffer

### ISSUE THREAD

**Issue by minad** [minad/consult#309]
Update the preview when moving around in the *Completions* buffer. This requires some setup of the post-command-hook in the *Completions* buffer.

This also affects Embark, in particular the `embark-preview-minor-mode`. The implementation of that preview mode should be very similar to the implementation for the *Completions* buffer, the only difference is that Embark uses the tablist and the current completion candidate must be obtained differently. cc @oantolin

**Comment by minad** [comment]
~~~ elisp
(add-hook 'completion-list-mode-hook #'consult--default-completion-preview-setup)

(defun consult--default-completion-preview-setup ()
  (add-hook 'post-command-hook #'consult--default-completion-preview-update nil 'local))

(defun consult--default-completion-choice ()
  (let (beg end cand)
    (cond
     ((and (not (eobp)) (get-text-property (point) 'mouse-face))
      (setq end (point) beg (1+ (point))))
     ((and (not (bobp))
           (get-text-property (1- (point)) 'mouse-face))
      (setq end (1- (point)) beg (point))))
    (when (and beg end)
      (setq beg (previous-single-property-change beg 'mouse-face))
      (setq end (or (next-single-property-change end 'mouse-face)
                    (point-max)))
      (buffer-substring-no-properties beg end))))

(defun consult--default-completion-preview-update ()
  (when-let* ((cand (consult--default-completion-choice))
              (win (active-minibuffer-window))
              (buf (window-buffer win))
              (fun (buffer-local-value 'consult--preview-function buf)))
    (with-selected-window win
      (funcall fun (minibuffer-contents-no-properties) cand))))
~~~

**Comment by minad** [comment]
@oantolin Why do we need `embark-consult-preview-minor-mode` after all? Do you see much value in this over offering an `embark-consult-preview-setup` function which can be added to the `embark-collect-mode-hook`, similar to the function above which I add to the `completion-list-mode-hook`?

**Comment by oantolin** [comment]
> Why do we need `embark-consult-preview-minor-mode` after all?

It doesn't _need_ to be a minor mode, of course. On the other hand, the function `embark-consult-preview-minor-mode` is exactly what you are asking for: a function that users can add to `embark-collect-mode-hook`! 😛 

The reason I went with a minor mode rather than a plain function is to make it easy to toggle and to get a lighter, in case someone wants it. The amount of extra code required to make it a minor mode over a plain function is minimal, as you can imagine. Is there any advantage to not taking a few extra lines to make this into a minor mode?

**Comment by oantolin** [comment]
The reason `embark-consult-preview-mode` is a little more complicated than the code you posted above is that it provides both the minor mode for automatic previewing and a function to manually trigger previews for those who don't want it automatic, does extensive checking to print friendly error messages in case you try to use it in an embark collect buffer that is not linked to active minibuffer running a Consult command that has preview functionality, and also does some caching to avoid previewing the same item many times in a row (in my tests pressing down `C-f` moving inside a single candidate was a little slow).

**Comment by oantolin** [comment]
> This also affects Embark, in particular the embark-preview-minor-mode. The implementation of that preview mode should be very similar to the implementation for the Completions buffer, the only difference is that Embark uses the tablist and the current completion candidate must be obtained differently.

I don't understand: are you saying you changed internals in Consult so that the current implementation of `embark-consult-preview-at-point` and of `embark-consult-preview-minor-mode` will no longer work?

**Comment by minad** [comment]
> and also does some caching to avoid previewing the same item many times in a row (in my tests pressing down C-f moving inside a single candidate was a little slow).

This should not happen. Consult already caches internally. You may want to remove this caching again in Embark and if the issue persists I should fix it properly in Consult.

**Comment by minad** [comment]
> I don't understand: are you saying you changed internals in Consult so that the current implementation of embark-consult-preview-at-point and of embark-consult-preview-minor-mode will no longer work?

No, nothing was changed. I was wondering if `embark-consult-preview-minor-mode` should be implemented in a similar way as such a functionality for the default completions buffer. Maybe they could share some code.

**Comment by oantolin** [comment]
So you are saying it is _not_ implemented in a similar way to what you wrote for the default completions buffer? Other than the caching, which I could remove, and the error checking, which I'd rather keep, what would you like me to change? The embark-consult code just calls `consult--preview-function` in the `post-command-hook`. Isn't that what you do for the compeltions buffer?

**Comment by minad** [comment]
I don't want you to change anything (except maybe simplifying the caching https://github.com/oantolin/embark/pull/221). I am also not suggesting anything. I was only wondering if there is more code to be shared between Embark preview and default completions preview. But from what I see now, it seems the Embark Consult preview is as simple as its gets.

**Comment by minad** [comment]
Note that the issue creation happened before pasting the default completion code snippet in https://github.com/minad/consult/issues/309#issuecomment-841605378. Maybe that's what lead to confusion here.

**Comment by oantolin** [comment]
Thanks for the PR removing the caching! I wonder if maybe there was a time when Consult didn't cache the last thing previewed? I seem to remember adding the cache because it did make a difference...

**Comment by oantolin** [comment]
Do you think it's worth porting some of the embark-consult features to this Completions buffer code? Here are the differences:

- If you turn `consult--default-completion-preview-setup` into a minor mode, people can still put it on the `completion-list-mode-hook` as shown now, but you also gain the option of binding it to a key to toggle automatic preview on or off, and people who do often toggle, might appreciate having a lighter in the mode line.
- If you make `consult--default-completion-preview-update` interactive, people who don't want the preview to be automatic, can still bind this function to a key for manually triggered previews.

**Comment by minad** [comment]
> Thanks for the PR removing the caching! I wonder if maybe there was a time when Consult didn't cache the last thing previewed? I seem to remember adding the cache because it did make a difference...

Probably. But I think if I had this like that I only had it for a short time since I wanted to make the `consult--preview-function` somehow comfortable to use for external users like Embark. Also the Consult-internal preview trigger does not have to do the check this way.

> Do you think it's worth porting some of the embark-consult features to this Completions buffer code? Here are the differences:

This completions buffer code is not yet part of Consult, so I am wondering what I should do about it. The whole point of this issue is to somehow figure out how the feature looks and if we can align it nicely with Embark. For example there could be a single `consult-completion-preview-mode` which works in both Embark collect buffers and in default completion buffers.

**Comment by oantolin** [comment]
> For example there could be a single `consult-completion-preview-mode` which works in both Embark collect buffers and in default completion buffers.

Definitely. All it would take is modifying the way the candidate is computed. If we use `embark--target` it would work in both embark collect buffers and the completions buffer automatically (well, I'd have to relax the error checking to admit completion-list-mode as well as embark-collect-mode).

**Comment by oantolin** [comment]
So, with minimal changes I could make the code in embark-consult also works for the `*Completions*` buffer. But maybe you wouldn't want the Embark dependency for people who just want to use Consult with the `*Completions*` buffer...

Another option would be to put this code into Consult (or to split it off into a separate package), leaving a hook for the candidate computation. Then embark-consult would only give that hook a value.

**Comment by minad** [comment]
Okay, interesting. Maybe it makes sense to add the *Completions* buffer functionality to Embark-Consult. I didn't think of that option. My initial thought was to add something to Consult, where Embark-Consult hooks into, which is better dependency-wise as you noted. I will have to experiment a bit to find the best approach.

**Comment by oantolin** [comment]
Considering the total code, namely Consult + Embark + embark-consult, it would be cheapest to put this into embark-consult, since then we can use `embark-target-completion-at-point` instead of having what is basically a duplicate: `consult--default-completion-choice`. If you don't mind duplicating that one function, from the point of view of dependencies probably the best option is to put this in Consult, with a little hook for retrieving the candidate. If you do that I'd like the analogue of `consult--default-completion-preview-update` to be interactive, so people can opt for manually triggered completion, but I would not insist on the automatic preview being a minor mode.

**Comment by minad** [comment]
Sounds reasonable. I have to try it, right now I don't have a strong opinion. I consider the dependency a problem though, Consult alone could do better if the `*Completions*` buffer is used. It is not that I am recommending to avoid Embark, quite the contrary.

Regarding the code duplication - I think one should add a `completion-get-current-candidate` function to simple.el at some point, which can be extracted from `choose-completion`. Such a function came already up in the discussion on emacs-devel with @monnier. We would still have the duplication or triplication for the foreseeable future, but I am not too worried with having to duplicate upstreamed functions verbatim. I just have to produce a patch for upstream and hope that it gets merged at some point.

**Comment by oantolin** [comment]
Well, let me know what you decide. I'll happily remove code from embark-consult if possible.

**Comment by minad** [comment]
I added the preview-at-point code here to Consult. Seems like a clean solution. See also https://github.com/oantolin/embark/pull/224.
