### ISSUE TITLE
consult-buffer preview got stuck in with lsp-deferred

### ISSUE THREAD

**Issue by liuyinz** [minad/consult#311]
I use lsp-mode with settings
```elisp
(use-package
  :hook (js-mode-hook . lsp-deferred))
```
however, when the preview option became default in consult-buffer [file] , the js file preview is quite slow because it must wait after lsp started. 

how can I turn off the preview option or set it not start lsp when just preview? I just begin use emacs so thanks !!

**Comment by minad** [comment]
The commit message mentions that a manual preview key should be configured: https://github.com/minad/consult/commit/6e3626361a4f672b9255fd914f3018267dac3028

See also the recommended configuration: https://github.com/minad/consult#use-package-example

~~~ elisp
  (consult-customize
   consult-ripgrep consult-git-grep consult-grep consult-bookmark consult-recent-file
   consult--source-file consult--source-project-file consult--source-bookmark
   :preview-key (kbd "M-."))
~~~

**Comment by liuyinz** [comment]
Solved !! Thanks for the great consult plugin !!
