### ISSUE TITLE
consult-theme bug on emacs 28

### ISSUE THREAD

**Issue by iyefrat** [minad/consult#313]
On emacs 28, when using `consult-theme`, changing (or previewing) only works the first time in an emacs session, and any subsequent attempt to change/preview the same theme again previews the default theme. On emacs 27 `consult-theme` works as expected.

To reproduce, use emacs 28 from the latest commit (nix-community/emacs-overlay@5df3462) of the nix emacs overlay (although the exact commit shouldn't matter too much, this has been a problem for a while), launch `emacs -Q` and eval the following:

```emacs
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)
(package-install 'consult)
(require 'consult)
```
do `M-x consult-themes` and try loading any theme, loading a different one, and then loading the first one again, you should see the default theme loaded instead. I should note that previewing the theme is enough to trigger this effect, presumably because previewing is just loading the theme but staying in the minibuffer.

**Comment by minad** [comment]
Oh wow, that's weird. I know something has change in Emacs 28 regarding theme loading it is probably related to that.

**Comment by iyefrat** [comment]
I realized that the first paragraph still had text left over from when I thought this had something to do with vertical completion frameworks, I edited it now, but I'm writing this to make sure that it's clear that the problem doesn't have anything to do with that and is solely contained in `consult-theme`.

**Comment by minad** [comment]
The problem is in Emacs 28. The semantics of `enable/load-theme` have changed in incompatible ways. I found quite a few related commits.

**Comment by minad** [comment]
I reported this upstream http://debbugs.gnu.org/cgi/bugreport.cgi?bug=48736

**Comment by minad** [comment]
Fixed upstream

**Comment by iyefrat** [comment]
Thanks!
