### ISSUE TITLE
Q: consult-line : possible to default to symbol-at-point?

### ISSUE THREAD

**Issue by rileyrg** [minad/consult#314]
The current M-n behaviour in my setup is "line at point". I need to hit M-n twice to get symbol at point after involing consult-line. I had a brief look through customisation. My understanding is that you push symbol at  point and line at point to history which are then available to M-n:-next-history-element, can this be reversed so symbol-at-point is the first fetched value?

**Comment by minad** [comment]
No unfortunately not. The default value will come before the first added history value. Emacs forces this.

Two alternatives:
1. Set :default to nil for consult-line, see consult-customize
2. Define consult-line-symbol-at-point, see wiki

Hope this helps!

**Comment by rileyrg** [comment]
Hi, I'm being dim but 

I can't find a reference to consult-line-symbol-at-point on the wiki .

**Comment by rileyrg** [comment]
The doc string for consult-customize says

> ARGS is a list of commands or sources followed by the list of keyword-value pairs.

but your example on the wiki shows no such lists:-

```
(consult-customize
          consult-ripgrep consult-git-grep consult-grep consult-bookmark consult-recent-file
          consult--source-file consult--source-project-file consult--source-bookmark
          :preview-key (kbd "M-."))
```
Would you mind explaining how this works? isnt this just a single list of values.

**Comment by minad** [comment]
> but your example on the wiki shows no such lists:-

ARGS is a rest argument, so everything is a single big list of commands, kv-pairs, commands, kv-pairs, ...
This should probably be clarified in the docstring.

This should work too:

~~~ elisp
  (consult-customize
   consult-line 
   :default nil
   consult-ripgrep consult-git-grep consult-grep consult-bookmark consult-recent-file
   consult--source-file consult--source-project-file consult--source-bookmark
   :preview-key (kbd "M-."))
~~~

> I can't help thinking setting the :default to nil so M-n brings up symbol-at-point should be a little more accessible maybe even via a defcustom. 

Yes, this is non-obvious. It should be at least documented on the wiki. The point of this consult-customize is to avoid the explosion of configuration options. With `consult-customize`you can configure every setting of a consult command (using `consult--read`). Take a look at the accepted settings of `consult--read` and `consult--multi` sources.

**Comment by rileyrg** [comment]
Thanks for addressing my Qs.
