### ISSUE TITLE
[Question] how to customize `preview-key` for `consult-xref`?

### ISSUE THREAD

**Issue by yuezhu** [minad/consult#322]
I would like to manually trigger preview for `consult-xref`, because its candidate list may get very large and I don't want to preview each candidate while moving over the list. So, I tried to set `preview-key` for `consult-xref` via `consult-customize` as the other commands:
```elisp
  (consult-customize 
                     consult-xref
                     :preview-key (kbd "C-<return>"))
```
However, I got a warning and it does not work as expected:
```
Error (use-package): consult/:config: Not enough arguments for format string Disable showing Disable logging
```

So, I was wondering what the correct way is to customize `consult-xref`.

**Comment by minad** [comment]
Thank you for the report. This was a bug! Your code snippet from above should be possible now.
