### ISSUE TITLE
consult-recent-file's preview sometimes loses saveplace's location

### ISSUE THREAD

**Issue by stevenbagley** [minad/consult#323]
The `saveplace` package saves the location of the point and restores it when that file is reopened. However, sometimes the preview shown in `consult-recent-file` loses the stored location. 

To reproduce: open file in Emacs, move point somewhere, close Emacs. Restart Emacs, load file (using that consult function), and the location has been lost, so the point moves to the beginning of the buffer. The relevant entry has actually disappeared from the `places` file.

As far as I can tell, this only happens with larger org mode files. 

I can solve the problem by deleting the line `:state (consult--file-preview)` from `consult-recent-file`, although of course then the previews are gone.

If you need more information, I'll try to create the smallest reproducible example, although I've failed on this so far.

**Comment by stevenbagley** [comment]
On further experimentation, the problem has nothing to do with org files.

The problem arises when `consult--temporary-file` calls `find-file-no-select` with `rawfile` set. 

Setting `consult-preview-raw-size` to a very big number gets around the problem.

**Comment by minad** [comment]
Ah okay, this is a downside of the preview. In order to make preview fast we have to open files as raw above a certain size. But my current recommendation is to use manual preview for files instead of automatic preview, see the example configuration in the readme:

~~~ elisp
  (consult-customize
   consult-ripgrep consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   consult--source-file consult--source-project-file consult--source-bookmark
   :preview-key (kbd "M-."))
~~~

This means we could also relax the preview-raw-size criterion or even remove this altogether and never open files as raw. What do you think?

**Comment by stevenbagley** [comment]
The current behavior is a compromise, but a mostly reasonable one. The only quirk is that until today, when I looked at the code, I was confused because sometimes previews were shown processed and sometimes raw, and it was never clear why. (Now it is.)

I think users will want some control over preview mode. I'm fine with using the size cutoff for this, although maybe an explicitly named variable would be better. The current raw threshold is probably too low, based on my experience. I have a 2.5 million character org mode file that previews just fine.

I personally don't have much need for a binding that invokes the preview, although others might like this. With recentf, because these are recently used files, I know what is in them and just want to get back to them with the least amount of typing. In this circumstance, the preview is nice, but far from necessary. Previews are better when I am unlikely to be familiar with file contents, such as with find-file.

**Comment by minad** [comment]
> ...although maybe an explicitly named variable would be better. 

What do you mean by that? Do you suggest another name for `consult-preview-raw-size`?

**Comment by stevenbagley** [comment]
Sorry, I wasn't clear. The raw-size variable is exactly the right name for what is does. My point was that a naive user looking to turn the preview option on or off entirely might not think of using the raw-size variable for that purpose. Anyhow, I don't feel strongly about this, and the current situation is fine for my purposes.

**Comment by minad** [comment]
I think we could and should document it a bit better. There is a preview section in the README which should be expanded with the lessons learned.

1. Difference between preview and opening via embark action (previewed files are closed)
2. Recommend manual preview. This seems to work generally better in heavier setups. But having automatic preview can also be fine as you say.
3. Document these cutoffs, e.g., `consult-preview-raw-size`
