### ISSUE TITLE
consult-buffer virtual buffer previews trigger yes-or-no queries and pinentry dialogs

### ISSUE THREAD

**Issue by tsdh** [minad/consult#324]
I have many dotfiles like my `~/.emacs` being just symlinks to files in my configuration git repository.  When I use `consult-buffer` and the `~/.emacs` virtual buffer entry happens to become selected (by scrolling over it or by it being the first candidate for my input), I'm asked the question "Symbolic link to Git-controlled source file; follow link? (y or n)" which is very annoying because my buffer name typing or scrolling is interrupted.  Only if I confirm (no matter if y or n), the "preview" of my `~/.emacs` is displayed.

This query comes from `vc-refresh-state` which is in `find-file-hook` as shown in this backtrace.
```
  vc-refresh-state()
  run-hooks(find-file-hook)
  after-find-file(nil nil)
  find-file-noselect-1(#<buffer .emacs-custom.el> "~/.emacs-custom.el" nowarn nil "~/Repos/configs/dot-emacs-custom.el" (10881294 2052))
  find-file-noselect("~/.emacs-custom.el" nowarn nil)
  #f(compiled-function (&optional name) #<bytecode -0x660606989d4c8c7>)("~/.emacs-custom.el")
  #f(compiled-function (cand restore) #<bytecode -0x1a5ed909d5f1581c>)("~/.emacs-custom.el" nil)
  #f(compiled-function (cand restore) #<bytecode 0x1b392fd111de3e3e>)("~/.emacs-custom.el" nil)
  #f(compiled-function (arg0 restore) #<bytecode 0x805561e732683e>)(("~/.emacs-custom.el" :name "File" :narrow 102 :category file :face consult-file :history file-name-history :state consult--file-state :enabled #f(compiled-function () #<bytecode 0x82b03a1d81f9>) :items #f(compiled-function () #<bytecode -0x8563e28af862b28>)) nil)
  #f(compiled-function () #<bytecode 0x14352686d9b2ab98>)()
  consult--preview-post-command()
```

So I guess you might want do let-bind `find-file-hook` when showing previews of virtual buffers to omit such queries.

Similar queries are triggered for encrypted files like my `~/.authinfo.gpg` where trying to find them triggers some pinentry dialog.  Whereas in the symlink case, the answer to the query makes no difference to the preview, with encrypted files, there cannot be a preview without passphrase.  However, I'd rather omit the preview instead getting interrupted during completion.  (Since I use the gpg-agent, the pinentry dialog will pop up just once and then be gone for some hours in contrast to the symlink/VC query which seems to happen always.)

**Comment by minad** [comment]
Good idea, how can w avoid this? I was always looking for some flag which tells Emacs to open the file **non-interactively**. I prefer if it fails in that case. This is better for preview.

You say let-bind `find-file-hook` - can you elaborate on that and give an example?

**Comment by tsdh** [comment]
Yes, I've player a bit and the following seems to cater for both the "symlink to VC-controlled file" query and for encrypted files (which signal a user-error with the `epg-pinentry-mode` binding which I catch and ignore).

``` elisp
(condition-case var
    (let ((find-file-hook nil)
          (epg-pinentry-mode 'cancel))
      (find-file-noselect "~/.emacs")
      (find-file-noselect "~/.authinfo.gpg"))
  (user-error
   ;; epg signals a user-error "Wrong passphrase: No secret key" which is
   ;; expected.  Re-signal all other errors.
   (unless (and (cadr var)
                (string-match-p "Wrong passphrase" (cadr var)))
     (user-error (cadr var)))))
```

**Comment by minad** [comment]
Hmm, this is not good since it is not general - in particular the epg-specific handling. I hope there is a better way to say that we want to open a file without any interaction. I think overwriting `find-file-hook` is not as bad.

Another idea is to filter out certain file types from preview. We could introduce a regexp filter, where we list files like gpg.

**Comment by oantolin** [comment]
You can try using the `non-essential` variable, here's its docstring:

Whether the currently executing code is performing an essential task.
This variable should be non-nil only when running code that should not
disturb the user.  E.g., it can be used to prevent Tramp from prompting
the user for a password when we are simply scanning a set of files in the
background or displaying possible completions before the user even asked
for it.

**Comment by minad** [comment]
Oh, I am aware of non-essential. I think it is not respected anywhere really.

**Comment by oantolin** [comment]
Oh. That's a shame.

**Comment by minad** [comment]
@tsdh I've added `consult-preview-excluded-hooks` to prevent some hooks from being executed. I added the epa hook here for now and also the recentf hook. Adding the recentf hook here simplifies things a bit. Therefore this variable is a good addition. Please give it a test!

**Comment by tsdh** [comment]
@minad That's fine.  I'll add the symlink-querying `vc-refresh-state` there, too.  (Maybe it should be there by default?)

**Comment by tsdh** [comment]
@minad BTW, I think @oantolin's point of binding `non-essential` to `t` is corret, too.  It might not be used by many right now but `icomplete` also binds it in its `icomplete-pre/post-command-hook`s with the comment "don't prompt for password".  So it's surely not wrong and might become more effective in the future.

**Comment by minad** [comment]
Okay, I made these adjustments. I believe the issue can be closed?
