### ISSUE TITLE
Most graceful way to replace :customize (consult-config) in use-package now?

### ISSUE THREAD

**Issue by WorldsEndless** [minad/consult#327]
As per instructions elsewhere in the issue history here, I need to avoid pop-ups in certain consult situations and so customized consult-config. Now that variable is gone, so with a little digging I found a work-around. I worry that it's a little hackish and might be more likely to break for me, though. Here's my use-package entry for consult; is this ok, or is there a more appropriate solution in my use-package management than customizing `consult--read-config`? 

```lisp
(use-package consult
    :straight (consult :type git :host github :repo "minad/consult")
    :bind ;;stuff
    :custom
; formerly this:
    ;; (consult-config `((consult-bookmark :preview-key nil)
    ;; 		      (consult-buffer :preview-key ,(kbd "M-p"))))
    (consult--read-config `((consult-bookmark :preview-key nil)
			    (consult-buffer :preview-key ,(kbd "M-p"))))
    :config
    (fset 'multi-occur #'consult-multi-occur))
```

**Comment by minad** [comment]
There exists the `consult-customize` macro now. I hope this answers your question.

**Comment by WorldsEndless** [comment]
I'm aware of consult-customize, but my question was about whether there's a graceful solution in use-package, since the usual customizer options can be configured nicely with `:custom`, which is what my original example shows. It looks like the consult configuration is no longer available via emacs built-in customizer?

**Comment by minad** [comment]
That's right, consult-config is not exposed as customizable anymore. I suggest using  `consult-customize` in the :config section of `use-package` as shown in the readme. The difference is only syntactical in contrast to using `:custom`.
