### ISSUE TITLE
How to override the state in e.g. consult-ripgrep

### ISSUE THREAD

**Issue by jwijenbergh** [minad/consult#328]
Hey Minad, thanks for the great package.

I am currently trying to get a posframe/child frame preview for ripgrep and am looking to override the state of the `consult-ripgrep` command to allow for this custom preview function. Is this easily possible without completely redefining `consult--grep` (which defines the state function that is used)? Sorry if this is a dumb question as I'm new to elisp.

I think it would be cool to preview the ripgrep candidate live in a posframe as this is nicer visually to me and I could even go as far as to integrate it with bat/cat and vterm to not slow down emacs as much on big files (this provides something similar to fzf's preview window).

It doesn't seem to be the same process as changing the state for `consult-buffer` sources (as explained in the wiki). Am I missing something obvious?

**Comment by minad** [comment]
This sounds like a cool idea. There is no other way than replacing the state functions entirely, or rather the part of the state functions which displays the buffer (consult--buffer-display iirc).

If you want to use bat/cat instead there is no other way than an entire replacement since in that case you don't even want to open the buffer yourself.

Of course I could rework some of the internals slightly to allow easier replacement of the preview display code for buffers to allow writing a consult-posframe-preview package.

**Comment by jwijenbergh** [comment]
Thanks for the quick response!

I figured, I made something quickly that uses bat, vterm and posframe to preview the grep candidates. See [here](https://github.com/jwijenbergh/consult-posframe-preview), I can maybe turn this into a full fledged package if people find this useful. 

Gif after `M-x` `consult-posframe-preview-mode`:
![consultposframepreview](https://user-images.githubusercontent.com/46386452/121235576-506dfd80-c895-11eb-97c7-42d72f9ebfe8.gif)

**Comment by minad** [comment]
Great. If you need a few non-intrusive changes to Consult, this can of course be considered. In particular if the existing state functions should be decomposed a bit to allow reuse by your package. Why do you need a vterm? I would use ansi-term for the preview which is more lightweight and built-in. It can still display the ansi escape sequences as required by bat. Maybe consult-bat would be a good name for the package :)

**Comment by minad** [comment]
> I'm guessing something like xterm-color.el is needed. 

Ah, I guess `bat` is using more than the simple ansi escape sequences. Maybe you can configure `bat` to use fewer colors instead of xterm 256 colors, such that `ansi-term` will work.

> Agreed, however it might make sense to extend my package as otherwise other packages will have the same code that just sets up the posframes and states.

Okay, if child frame previews are a general thing you are of course right.

**Comment by jwijenbergh** [comment]
> 
> 
> > I'm guessing something like xterm-color.el is needed.
> 
> Ah, I guess `bat` is using more than the simple ansi escape sequences. Maybe you can configure `bat` to use fewer colors instead of xterm 256 colors, such that `ansi-term` will work.

Yeah `bat --theme=ansi-dark` or `ansi-light` seem to work pretty fine so might switch to ansi-term anyways. For now this package is mostly for myself but I hope it's useful for others as well. Even nicer would then be to drop the dependency on posframe as most of the functionality in there is not really needed. That way the only dependency would be consult and an emacs version that supports child frames.

> > Agreed, however it might make sense to extend my package as otherwise other packages will have the same code that just sets up the posframes and states.
> 
> Okay, if child frame previews are a general thing you are of course right.

Indeed. Thanks for your help!

**Comment by minad** [comment]
I was about to suggest dropping the posframe dependency too. My mini-popup and corfu packages use child frames directly and it is not significantly more complicated than posframe.
