### ISSUE TITLE
How to disable group titles of consult grep commands?

### ISSUE THREAD

**Issue by powellb** [minad/consult#330]
Using base configuration of `consult-git-grep` produces different style of results than shown in the animation in the README. The animation shows that it produces results in the recognized standard form of:

filename1:LINE1:result
filename1:LINE2:result
filename2:LINE:result
filename3:LINE:result

When I start `emacs -Q` and then initialize:
```
(package-initialize)
(require 'consult)
(require 'selectrum)
(selectrum-mode)
(setq completion-styles '(substring))
```

Performing a `consult-git-grep` produces an inferior style of results:

```
_________filename1___________
LINE1    result
LINE2   result
_________filename2___________
LINE     result
_________filename3___________
LINE     result
```
This is harder to parse, takes more space in the minibuffer, and makes it very difficult when there are many files with one result each.

How can I configure consult to produce grep consistent results like those shown in the README animation?

**Comment by minad** [comment]
~~~ elisp
(consult-customize consult-grep consult-git-grep consult-ripgrep :group nil)

;; Or globally

(setq selectrum-group-format nil)
~~~
