### ISSUE TITLE
setup consult-git-grep group nil

### ISSUE THREAD

**Issue by velkyel** [minad/consult#331]
hello,
```
(consult-customize consult-buffer :group nil)
(consult-customize consult-git-grep :group nil)
```
it works on consult-buffer but seems that doesn't affect consult-git-grep result.  I'd like to have it the same as Fig. 1: Command consult-git-grep on https://github.com/minad/consult.  Am I doing something wrong?

**Comment by minad** [comment]
The following works for me in emacs -Q:

~~~ elisp
(package-initialize)
(vertico-mode)
(consult-customize consult-git-grep :group nil)
~~~

and then `M-x consult-git-grep RET` in a git repository. 

This is an issue in your configuration. You are binding a lambda to the keybinding. 

https://github.com/velkyel/dotfiles/blob/085553045f2c170df1dd1b1eb5e1ff41736712c0/.emacs#L322-L324

`consult-customize` uses `this-command` internally to associate the configuration with the command. You should define a proper function `(defun velkyel/git-grep () ...` and then `(consult-customize velkyel/git-grep ...`.
