### ISSUE TITLE
Consider waiting a bit before displaying previews

### ISSUE THREAD

**Issue by lucasvreis** [minad/consult#333]
Hi, first let me thank you for this package.

When switching between buffers and themes, my experience with the live preview has been not so great as consult tries to display every selected item immediately. So when I'm typing a word, there is a delay between each letter that I type, and when I'm scrolling with the arrow keys it is even worse as it (seemingly) tries to display everything in quick succession.

My suggestion is to allow setting a small delay, so that the preview only appears after a few milliseconds. This would allow for one to type or scroll fast and only the final item would be shown.

**Comment by minad** [comment]
Not a bad idea. One could add a :preview-debounce option and a consult-preview-debounce customizable variable. If set to nil, no delay will be used.

**Comment by minad** [comment]
See https://github.com/minad/consult/tree/preview-debounce for a prototype

**Comment by jwijenbergh** [comment]
This is very useful. I was already doing something similar in the child frame preview package for consult which is still WIP. Testing that branch however, it doesn't seem to work as expected. My preview key is so to 'any (default) but the following check doesn't seem to pass:

https://github.com/minad/consult/blob/f5f513006f8caa433f8b5df6e3c8f0a2bbf0bbc9/consult.el#L1088

Any reason why you're even check for key any here anyways? When I remove the check for any and just leave in 
```lisp
(if preview-debounce.....
```
 it works as expected

**Comment by minad** [comment]
The current status is here: https://github.com/minad/consult/tree/preview-debounce2

One can configure a debounce delay per preview-key. For example "any key" triggers an automatic debounced preview and M-. triggers an immediate preview.

~~~ elisp
(setq consult-preview-key `(,(kbd "M-.") :debounce 0.2 any))
~~~

**Comment by lucasvreis** [comment]
I'm testing it and it feels way better in terms of responsiveness!

One minor issue I noticed is that the "pending preview" is not cancelled when deleting characters:

<img src="https://user-images.githubusercontent.com/4229115/121729797-3e72a180-cac5-11eb-8b97-0b019bbfaf8b.gif" width="400"/>

**Comment by minad** [comment]
Why should it be cancelled? 0.2s after the last input, the candidate is previewed. This is standard debouncing.

**Comment by lucasvreis** [comment]
Yes, maybe I should have said it is not "updated" (i.e., the preview shows something different from what is selected). And the same issue happens when inserting, not only deleting.

**Comment by minad** [comment]
Should be fixed in https://github.com/minad/consult/commit/f06b1438bda8c7272dd89ce5b7d7dc512d11abf9

**Comment by minad** [comment]
You may also want to test the interaction of any key plus another preview key, if this works as expected. 

~~~ elisp
(setq consult-preview-key `(,(kbd "M-p") :debounce 1 any))
~~~

**Comment by lucasvreis** [comment]
Tried many different things and it seems to be working perfectly.

**Comment by minad** [comment]
Thank you for checking! Perfect is just good enough for Consult ;)

**Comment by lucasvreis** [comment]
Thanks for implementing it! 🙂
