### ISSUE TITLE
Consult find file using regex

### ISSUE THREAD

**Issue by slayer152** [minad/consult#334]
How do i use regular expressions to search for files using the consult fd command.

E.g. I have two files abcdxyz.txt and xyz.txt and I only want to search and find xyz.txt.

With fd command in any shell, i can search for `fd ^xyz`.

But when I use `^xyz` in the consult fd prompt, neither of the files is matched.

**Comment by minad** [comment]
There is no consult-fd command ootb. It all depends on how you configure consult-find-command. Probably you have full path search activated. If you disable this it should work. I hope this helps!

**Comment by slayer152** [comment]
Thank you. 

I needed to use '\b' word boundary (\bxyz instead of ^xyz) to get what I want.
