### ISSUE TITLE
inherit-input-method for consult-line

### ISSUE THREAD

**Issue by abcdw** [minad/consult#335]
I find it very useful that `isearch-forward` use the same input method as current buffer.

Also, I found that it's possible to pass `inherit-input-method` to argument to `completing-read`.

Is there a way to make `consult-line` also inherit input method from current buffer?

P. S.
Thank you for all the great packages!)

**Comment by minad** [comment]
Are you using Selectrum or Vertico? It seems that Selectrum ignores the argument `inherit-input-method` (https://github.com/raxod502/selectrum/issues/558), but I don't know why that's the case.

**Comment by abcdw** [comment]
Vertico.

> We could add support for inherit-input-method to consult--read. Then one could configure the setting per command.

Yep, will work for me perfectly!)

I use cyrillic input method to write emails or other stuff and sometimes want to search/navigate the content of the buffer with consult-line and in most cases it make sense to use the same input method as the one used inside current buffer.  I write in russian and would like to search in russian, but it doesn't make sense to inherit input-method for `M-x` or other minibuffer related commands, so yes per-command configuration of inheritance is a very good idea!

**Comment by minad** [comment]
Okay, thank you. Sorry for my ignorance. I am not familiar how different alphabets are handled in Emacs. Bye, how does this work in non-Emacs programs? For example when you navigate the shell and enter commands in Latin, but your files have Cyrillic names.

**Comment by abcdw** [comment]
> For example when you navigate the shell and enter commands in Latin, but your files have Cyrillic names.

You can use some kind of autocompletion or switch "system layout" and type cyrillic characters.

You can use the system keyboard layout approach in Emacs, but it will break all the hotkeys and you either typing cyrillic characters or have access to your keybindings.  Actually, it breaks keybindings not only in Emacs, depends on the implementation of hotkeys handling logic in various apps.

I use dvorak for english layout and jcuken for russian layout and when I switch system layout in Emacs and try to type `M-f` I get `M-н is undefined`, which is not really cool)

So I have two options:
1. Use input-methods, which when activated changes only the way characters are inserted in the buffer with self-insert-command, but everything else is still the same, so keybindings doesn't get broken.
2. Use another system layout and map all the cyrillic variants of keybindigs (can be automated by reverse-im package).

I quite like the idea of input methods and would like to use inherit capabilities for minibuffer in some cases like `consult-line`. 

Hope this info provides some clarity)

**Comment by minad** [comment]
Thank you for the extensive answer! This is very helpful. I've also seen the reverse-im package before but haven't looked into how it works.

Regarding this issue - as I mentioned before, I will add this `:inherit-input-method` argument to `consult--read` in order to support your use case.

**Comment by abcdw** [comment]
Thank you very much!)

You do a great job on Emacs completion ecosystem!
