### ISSUE TITLE
How to show count/number of results as shown in screenshots

### ISSUE THREAD

**Issue by MicahElliott** [minad/consult#336]
Sorry, I just can't figure out what's wrong with my config that there is no results count showing up in any of my consult commands. I've had to turn this on manually in the past with ivy and selectrum settings, and I can't see any consult customization indicating `number` or `count`. I see in the consult screenshots at the front of the search prompt there is always something like `(3/42)`. I don't have that and can't figure out how to get it! Maybe this is worth a FAQ mention, or maybe it's just me.

(I'm also using icomplete-vertical)

![image](https://user-images.githubusercontent.com/159047/121968952-23ec3280-cd28-11eb-8998-4ffc17cf3ca6.png)

**Comment by oantolin** [comment]
Some completion UIs show the number of candidates and some do not. Icomplete-vertical does not show that number, but Vertico and Selectrum do.

**Comment by MicahElliott** [comment]
Ah, thanks Omar. I've been getting a lot of mileage out of icomplete-vertical (thank you!), but I guess I should try vertico for this case. I've been struggling with not having this count, since I'm often using consult-ripgrep on a large project and getting sometimes tens or hundreds of results and have no idea which (magnitude).

**Comment by oantolin** [comment]
I highly recommend Vertico, I think it's nicer than my version of icomplete-vertical (I won't say anything about the new built-in icomplete-vertical in Emacs 28, since I have nothing to do with it and have not even tried it yet).

**Comment by oantolin** [comment]
Somehow I've never wanted a count displayed. I'm usually either (a) looking for a specific result in which case I keep typing until I see it, then select it and never care how many others were displayed along the way, or (b) I need to do something with every occurrence of some search term, in which case I use all the results (usually via embark-collect-snapshot or embark-export) and also don't care how many there are since I need all of them anyway.

**Comment by MicahElliott** [comment]
Good to hear your perspective. I think the case I hit a lot is just for when the hunt is exploratory and maybe over a large (somewhat unfamiliar) code base. But I'd also think it's useful for searching data sets. Though I agree that it's nice to just keep typing to narrow till you see a few of what you're looking for.

**Comment by oantolin** [comment]
Oh, I see, for exploration I agree it would be handy.
