### ISSUE TITLE
Consult command for eval-expression

### ISSUE THREAD

**Issue by MicahElliott** [minad/consult#338]
It'd be nice to have a command that would do nice completing for `eval-expression` (`M-:`). 

Or some workaround instructions for not having to use the default `*Completions*` buffer after `TAB TAB`. Pretty sure this worked well with a prior Ivy setup. Seems like I don't even have icomplete set up with `eval-expression` now, though I do have a nice config using consult with vertico/orderless for several other commands. So maybe this is more of a vertico question.

I do see that there's already `consult-complex-command`, but it seems only for history.

**Comment by minad** [comment]
You are looking for a minibuffer completion for `completion-at-point` (TAB). You have to set up a `completion-in-region-function`, for example `consult-completion-in-region`. Otherwise the default function opens a `*Completions*` buffer. I hope this helps!

**Comment by MicahElliott** [comment]
Yes, that's what I was looking for. Thx @minad!
