### ISSUE TITLE
consult-grep: ignore file name with filter string

### ISSUE THREAD

**Issue by ftzm** [minad/consult#342]
It seems that the `consult-grep` family of commands will look for the filter string in file names as well as file lines. To give a concrete example, if I have a file named `bar.txt` containing the line `foo`, and I do a `consult-grep` search for `#foo#bar`, the line `foo` will show up as a match, even though the string `bar` only occurs in the file name. Is there a way to limit filter string matches to file lines alone?

**Comment by minad** [comment]
Yes, this is possible, but it is quite involved. For example you can define your own completion style, which ignores everything before the colons (the `file:line:` part). If your completion style supports regular expressions, e.g., Orderless, you can enter a filter expression `:.*filter`.

**Comment by ftzm** [comment]
Thank you for the quick response. The Orderless example you provided does provide the correct matches, but the fact that you need to prepend `:.*` to every space-separated string, as well as the fact that match highlighting starts from the beginning of the line due to matching on `:` means that it isn't an ideal solution. I had hoped that the file name could be somehow excluded from the matching process entirely, but if that's not feasible then I'll happily look for/hack up an alternative solution.

**Comment by minad** [comment]
I could always exclude file names from the matching, but this is not always desired. I think this should be solved on the level of a custom completion style. Completion styles are not particularly hard to write, look at `completion-styles-alist`. You need two functions a `try-` and an `all-completion` function. Then if you have defined your style, you can configure it for grep in `completion-category-overrides`.

**Comment by minad** [comment]
Here is an custom completion style which can be used as a starting point. It only matches the part after a colon.

~~~ elisp
(defun custom-all-completions (string table pred _point)
  ;; prefix filter string with :.*
  (let* ((pattern (regexp-quote string))
         (completion-regexp-list (list (concat ":.*" pattern))))
    (mapcar
     (lambda (str)
       ;; add highlighting
       (when (string-match pattern str (string-match-p ":" str))
         (setq str (copy-sequence str))
         (add-face-text-property (match-beginning 0) (match-end 0) 'highlight nil str))
       str)
     (all-completions "" table pred))))

(defun custom-try-completion (string table pred _point)
  ;; prefix filter string with :.*
  (let ((completion-regexp-list (list (concat ":.*" (regexp-quote string)))))
    (try-completion "" table pred)))

(add-to-list 'completion-styles-alist
             '(custom
               custom-try-completion custom-all-completions
               "Custom completion style."))
~~~

**Comment by ftzm** [comment]
Thanks for your help!
