### ISSUE TITLE
Is there a way to transform 'ARG' before it passed to cmd?

### ISSUE THREAD

**Issue by wsw0108** [minad/consult#343]
For `transform`, I mean things like encode 'ARG' to OS native text.

Like in `counsel-locate-cmd` under Windows.

https://github.com/abo-abo/swiper/blob/040d458bce4a88f37359192061bcea5ebe87007c/counsel.el#L2657

**Comment by minad** [comment]
No, such a transformation is not possible. It should either happen in `consult--command-args` or `consult--async-process`. From my perspective this is an Emacs bug or a bug in the Emacs process abstraction. Emacs fails to properly encode the arguments when executing another process. See also the related issue #317. I close this issue in favor of #317, which collects all the windows process problems.

**Comment by wsw0108** [comment]
Finally, I got it works by specify the coding system of 'es.exe'.
```
(add-to-list 'process-coding-system-alist '("es" gbk . gbk))
```
