### ISSUE TITLE
consult-customize requires commands to be defined

### ISSUE THREAD

**Issue by purcell** [minad/consult#345]
It seems natural to use a single `consult-customize` form to customise all desired commands, but currently that form throws an error if called before all the commands have been loaded - even if autoloads exist for them. For example:
```el
     (consult-customize
       consult-ripgrep
       affe-grep
       consult-git-grep consult-grep
       consult-bookmark consult-recent-file consult-xref
       consult--source-file consult--source-project-file consult--source-bookmark
       :preview-key (kbd "M-P")))
```
Here, this form fails if `affe` is not yet loaded. It seems clunky to have multiple `consult-customize` forms each wrapped in a `with-eval-after-load` form, to make this not throw an error, but that's what I've had to do locally. Probably better if `consult-customize` is a bit more liberal, or perhaps it should just look for autoloaded commands instead of using `functionp`?

**Comment by minad** [comment]
> Probably better if consult-customize is a bit more liberal, or perhaps it should just look for autoloaded commands instead of using functionp?

Autoloaded functions are already `functionp`. I don't see a way to make this more liberal except removing the check.

**Comment by minad** [comment]
@purcell I am closing this since I don't see how the status quo can be improved. If you have an idea please let me know.

**Comment by purcell** [comment]
Thanks. It's really weird, I don't know why I was seeing this breaking in my CI with `affe-grep` autoloaded. :-(
