### ISSUE TITLE
misleading grouping

### ISSUE THREAD

**Issue by bogolisk** [minad/consult#348]
`consult-xref--candidates` binds `xref-file-name-display` to `'nondirectory`, which is **nice most of the times**. However, with source code such as linux-kernel, there are multiple definitions of the same identifier in different paths with _same file name_. 

Example:

the generic version of `__smp_mb` is defined in `include/asm-generic/barrier.h` while the arm-specific version is defined in `arch/arm/include/asm/barrier.h`. With `'nondirectory`, consult-xref misleadingly shows both definitions of `__smp_mb` as if they were all defined in a _same_ `barrier.h` file.

**Comment by minad** [comment]
Okay, I guess the right thing is to not bind this setting such that the users have the ability to configure this themselves.
