### ISSUE TITLE
support subtypes of xref-file-location in consult-xref

### ISSUE THREAD

**Issue by bogolisk** [minad/consult#349]
I have a custom `xref` backend which returns locations as instances of a subtype of `xref-file-location`. As such, such _location_ can be used anywhere an instance of `xref-file-location` was expected.

However, for previewing a location of type `xref-file-location`, `consult-xref--preview` only supports instances of `xref-file-location` class but not instances of its subtypes.

In `consult-xref--preview`, is it possible to change the line

    (xref-file-location-p loc)

to

    (cl-typep loc 'xref-file-location)

?

**Comment by bogolisk** [comment]
another possibility is to use `cl-typecase`

    (defun consult-xref--preview (display)
      "Xref preview with DISPLAY function."
      (let ((open (consult--temporary-files))
            (preview (consult--jump-preview)))
        (lambda (cand restore)
          (cond
           (restore
            (funcall preview nil t)
            (funcall open nil))
           (cand
            (let ((loc (xref-item-location cand))
                  (consult--buffer-display display))
              (funcall preview
                       (cl-typecase loc
                         (xref-buffer-location (xref-location-marker loc))
                         (xref-file-location (consult--position-marker
                                              (funcall open (oref loc file))
                                              (oref loc line)
                                              (oref loc column)))
                         (t (message "No preview for %s" (type-of loc))))
                       nil)))))))

**Comment by minad** [comment]
I assume the canonical way to do this is to use `xref-file-location-child-p`?
