### ISSUE TITLE
consult-kmacro: Hide counter and format if possible

### ISSUE THREAD

**Issue by minad** [minad/consult#35]
Ping @okamsn 

* Hiding counter and default format for commands which do not use the counter
* **DONE** ~Please recheck the comments in https://github.com/minad/consult/commit/6e4b699ec35679456409c47d43eae20cb042705c~

**Comment by minad** [comment]
See also original discussion in the PR #23

**Comment by okamsn** [comment]
I have made a PR #36.

**Comment by minad** [comment]
Closed in favor of #36, discussion continues there.
