### ISSUE TITLE
In consult-buffer, candidates are not recognized correctly in embark

### ISSUE THREAD

**Issue by dalgong** [minad/consult#351]
_Not sure if this is embark issue or consult issue but help me resolve this._

During the buffer selection after `M-x consult-buffer`, `embark` shows default keymap with `M-x embark-act`. I was expecting buffer specific keymap (`embark-buffer-map`) for buffer candidate. Since `consult-buffer` supports multiple sources, it would be ideal if we can make `M-x embark-act` to get the correct type depending on current candidate.

What would be the best way to achieve this? Do we need to advice `emark--target` or configure `embark-target-finders`?

**Comment by dalgong** [comment]
Looks like the following works:

```
(defun my-consult-multi-target ()
  (let ((c (embark-target-top-minibuffer-completion)))
    (when (and c (eq 'consult-multi (car c)))
      (get-text-property 0 'consult-multi (cdr c)))))
(add-to-list 'embark-target-finders #'my-consult-multi-target)

```

**Comment by oantolin** [comment]
Are you loading the embark-consult library? This functionality is impmemented there.

**Comment by dalgong** [comment]
Thanks. Yes, I'm using `embark-consult`. The following is my configuration. I guess this is because it's on demand (because of `:hook`) and didn't loaded yet.

```
(use-package embark-consult
  :ensure
  :after (embark consult)
  :hook (embark-collect-mode . embark-consult-preview-minor-mode))
```
