### ISSUE TITLE
Question about keybinding for consult--read

### ISSUE THREAD

**Issue by sach2** [minad/consult#355]
Hi,
I find consult commands very useful. I rolled a few of my own functions using `consult--read`.
I use orderless, so in most of the commands, I don't see I use `dot` in completing buffer. Instead of pressing `RET` I wanted to use `dot` to select option from list.

Is that possible? If yes, how can I do it?

**Comment by minad** [comment]
You can bind keys in the `vertico-map` (Vertico), `minibuffer-completion-local-map` (default UI) or in the `selectrum-minibuffer-map` (Selectrum), depending on the UI you are using.

~~~ elisp
(define-key vertico-map "." #'vertico-exit)
~~~

Does this answer your question?

**Comment by sach2** [comment]
Yes, perfect.
Thanks.
