### ISSUE TITLE
consult-buffer p doesn't include shell or dired buffers

### ISSUE THREAD

**Issue by xendk** [minad/consult#357]
Unlike `projectile-switch-to-buffer`, `consult-buffer` `p` doesn't list shell buffers. Projectile checks if the buffers `default-directory` is inside the root of the project while `consult--source-project-buffer` checks the buffer file name. Shell buffers doesn't have a file name, but still have a default-directory (which is afaik the current directory of the shell).

Same goes for dired buffers.

Would be nice if `consult-buffer` would do the same.

**Comment by minad** [comment]
Indeed, it is better to check the default directory.
