### ISSUE TITLE
Consult-buffer will affect the result of post-command-hook

### ISSUE THREAD

**Issue by Eason0210** [minad/consult#359]
Hi @minad ,

I implemented a trivial function, when switching between different input methods, the color of the cursor can be changed automatically. For example, English is the default color, and German use Orange. When using the default `switch-to-buffer` function, everything is good. But if you use the `consult-buffer `with `(global-set-key [remap switch-to-buffer]'consult-buffer)`,  you will get the wrong cursor color result when switch to different buffer with German input method. 
Is there any way to fix this issue?

You can reproduce this issue with the snippets as bellow:

```
(package-initialize)
(require 'consult)
(require 'vertico)
(vertico-mode)
(setq completion-styles '(substring))

(global-set-key [remap switch-to-buffer] 'consult-buffer)


(defvar input-method-cursor-color "Orange"
  "Default cursor color if using an input method.")

(defun get-frame-cursor-color ()
  "Get the cursor-color of current frame."
  (interactive)
  (frame-parameter nil 'cursor-color))

(defvar default-cursor-color (get-frame-cursor-color)
  "Default text cursor color.")

(defun change-cursor-color-on-input-method ()
  "Set cursor color depending on whether an input method is used or not."
  (interactive)
  (set-cursor-color (if current-input-method
                        input-method-cursor-color
                      default-cursor-color)))

(add-hook 'post-command-hook 'change-cursor-color-on-input-method)
```
Platform:  Windows 10 and Mac OS 11.4
Emacs version: 28.0.50 native comp.

**Comment by minad** [comment]
You can try to adjust the priority of the hook such that it will be executed in the correct order with the consult preview post command hook.

**Comment by Eason0210** [comment]
> You can try to adjust the priority of the hook 

sorry, I have no idear how to adjust the priority of a hook. Can you give me some hint?

**Comment by minad** [comment]
`C-h f add-hook RET C-s depth`

**Comment by Eason0210** [comment]
I try ` (add-hook 'post-command-hook 'change-cursor-color-on-input-method -90)`，no effect.  and  my function is always after consult--preview-post-command.
below is the result of `C-h v`  , post-command-hook with `consult-buffer`:
```
post-command-hook is a variable defined in ‘C source code’.

Its value is (vertico--exhibit consult--preview-post-command t)
Local in buffer  *Minibuf-1*; global value is 
(change-cursor-color-on-input-method global-font-lock-mode-check-buffers global-eldoc-mode-check-buffers )
```

**Comment by minad** [comment]
I think you should use `(add-hook 'post-command-hook 'change-cursor-color-on-input-method 90)`. Did you check that your hook runs after `consult--preview-post-command`?

**Comment by Eason0210** [comment]
use `(add-hook 'post-command-hook 'change-cursor-color-on-input-method 90)` is the same behavior. I checked that my hook exactly runs after consult--preview-post-command, so I think it is not because of the priority of hooks.   

when my hook runs after exit the minibuffer, it read the wrong `current-input-method` which is the one in minibuffer.

**Comment by minad** [comment]
Ah okay, of course. You should then check the original buffer such that the correct current-input-method is read.

~~~ elisp
(if (minibuffer-window-active-p (selected-window))
    (buffer-local-value 'current-input-method (window-buffer (minibuffer-selected-window)))
  current-input-method)
~~~

**Comment by Eason0210** [comment]
sorry, I just go back to home.
I try the snippets above, but the issue still exist.
I also notice that `consul-buffer` will affect most packages which use post-command-hook. such as the [smart-cursor-color-mode](https://github.com/7696122/smart-cursor-color).

You can install this package to  reproduce the issue by the below snippet:
```
(package-initialize)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "https://elpa.gnu.org/packages/")))
(require 'consult)
(require 'vertico)
(vertico-mode)
(setq completion-styles '(substring))

(global-set-key [remap switch-to-buffer] 'consult-buffer)

(require 'smart-cursor-color)
(smart-cursor-color-mode +1)

```
This package may be more easy for you to understand the issue.

**Comment by minad** [comment]
> I also notice that consult-buffer will affect most packages which use post-command-hook.

Yes, it may affect packages, but there is no other way than using a `post-command-hook` for the preview. I am closing this issue, since I don't see a Consult issue here. For me changing the cursor color is not affected by Consult in any way.

~~~ elisp
(defvar default-cursor-color (frame-parameter nil 'cursor-color))

(defun change-cursor-color ()
  (set-cursor-color (if (cl-evenp (line-number-at-pos)) "Orange" default-cursor-color)))

(add-hook 'post-command-hook #'change-cursor-color)
~~~

**Comment by minad** [comment]
Hmm, I think I understand now what you mean.

~~~ elisp
(package-initialize)
(require 'consult)
(require 'vertico)
(vertico-mode)
(setq completion-styles '(substring))

(global-set-key [remap switch-to-buffer] 'consult-buffer)
;;(setq consult-preview-key nil)

(defun print-current-buffer ()
  (message "CURRENT BUFFER %S" (current-buffer)))

(add-hook 'post-command-hook 'print-current-buffer)
~~~

**Comment by minad** [comment]
@Eason0210 This was actually a tricky effect of how the preview functions are destructed. I hope there are not more such issues, but it could happen if one introduces custom buffer sources (`consult-buffer-sources`). Thank you for discovering this!

**Comment by Eason0210** [comment]
@minad  Greate!  It works perfect now. Thank you for your help.

**Comment by minad** [comment]
> Greate! It works perfect now. Thank you for your help.

Thanks, for giving it another check!
