### ISSUE TITLE
How do I edit the results of consult-ripgrep and reflect the modifications to the files?

### ISSUE THREAD

**Issue by yamatakau08** [minad/consult#360]
I execute consult-ripgrep in dired buffer to search the pattern in files under the the directory,

After the pattern in SOME FILES is matched, I want to replace that pattern in the files with the new one.
So I execute embark-export,then type 'e' in *Embark xport Grep* , but that is not available.

How do I edit the results of consult-ripgrep and reflect the modifications to the FILES?

**Comment by minad** [comment]
wgrep - it is documented in both the Embark and the Consult README.
