### ISSUE TITLE
switch consult-ripgrep from minibuffer to compilation buffer

### ISSUE THREAD

**Issue by fgeller** [minad/consult#362]
hi! thanks for this awesome compilation of tools! 
is the title possible? ie, sometimes there are too many results and i'd prefer to switch to a compilation buffer where i then might use wgrep. thanks for your time in advance!

**Comment by iyefrat** [comment]
For that you want to use `embark-export` in the [embark](https://github.com/oantolin/embark) package. Make sure you load `embark-consult` as it says in the readme. Check out the [recommended packages](https://github.com/minad/consult#recommended-packages) section if you haven't yet, there's some good stuff there.

**Comment by minad** [comment]
By compilation I think you mean a grep buffer, since the grep-mode is derived from the compilation buffer mode. As @iyefrat pointed out, `embark-export` is the solution.
