### ISSUE TITLE
Live preview customization for wrappers

### ISSUE THREAD

**Issue by BlankSpruce** [minad/consult#368]
Consider this snippet:
```elisp
(use-package consult
  :config
  (defun my-consult-ripgrep-wrapper ()
    (interactive)
    (consult-ripgrep)) ;; simple enough for the sake of demonstration

  (consult-customize
   consult-ripgrep
   :preview-key (kbd "M-.")))
```

If you invoke `M-x consult-ripgrep` live preview is manual as expected. However wrapper function doesn't inherit this setting. It seems that possible workarounds are:
```elisp
(consult-customize
 consult-ripgrep
 my-consult-ripgrep-wrappper
 ;; and
 ;; any
 ;; other
 ;; wrapper
 :preview-key (kbd "M-."))
```
or (I'm not sure though what are the unintended effects here):
```elisp
(defun my-consult-ripgrep-wrapper ()
  (interactive)
  (let ((this-command 'consult-ripgrep))
    (call-interactively 'consult-ripgrep)))
```
Given the first solution simply works maybe it's not a bug per se but a potential for quality of life improvement. Practical use-case would be such wrapper:
```elisp
(defun my-consult-ripgrep-project ()
  (interactive)
  (consult-ripgrep (projectile-project-root)))

(defun my-consult-ripgrep-other-project ()
   (interactive)
   (let ((projectile-switch-project-action 'my-consult-ripgrep-project))
     (projectile-switch-project)))
```

**Comment by minad** [comment]
The correct approach is to write a separate consult-customize specification for each wrapper command. There is no inheritance. This is intentional for simplicity and in order to allow writing wrappers/aliases specifically for the purpose of using different a different customization. Overwriting this-command is not a good idea in general. I hope this answers your question.

**Comment by BlankSpruce** [comment]
In the hindsight your explanation makes a lot of sense that customization for wrappers should be done separately. However it's not obvious what are restrictions for wrappers so that customizations work. Consider the following:
```elisp
(defun foo-1 (directory)
  (interactive
   (list (read-directory-name "Directory: ")))
  (consult-ripgrep directory))

(defun foo-2 ()
  (interactive)
  (let ((directory (read-directory-name "Directory: ")))
    (consult-ripgrep directory)))

(defun foo-3 ()
  (interactive)
  (consult-ripgrep (read-directory-name "Directory: ")))

(consult-customize
 foo-1
 foo-2
 foo-3
 :preview-key (kbd "M-."))
```

Is there a reason why only `foo-1` respects manual live preview? I'm using GNU Emacs 27.2 with consult `20210731.1407`

**Comment by minad** [comment]
Oh, this is a serious issue. `consult-ripgrep` itself has this problem since it reads a directory name. By doing that, it overwrites `this-command` which is used to detect the configuration. Thank you for reporting this. This needs a fix!

**Comment by minad** [comment]
I fixed `consult-ripgrep` by ensuring that `this-command` is preserved. For custom commands I recommend the `foo-1` form for now.
