### ISSUE TITLE
Async: Decouple the process indicator from the process source

### ISSUE THREAD

**Issue by minad** [minad/consult#370]
Add a status action to the async functions. When an async function is called with a list of the form `(status :key value...)`, it should append its status information to the plist and return the updated status information. This way status information can propagate up and down through an async pipeline.

* The process indicator can be separated from the process source.
* The throttler could benefit from the process runtime information and adapt its delays accordingly.
* Non-process backends can reuse the indicator overlay, e.g., a web backend.

cc @tecosaur

**Comment by tecosaur** [comment]
Taken from Discord
1. [ ] Create `consult--async-indicator`, take the overlay code from `consult--async-process`,
2. [ ] Remove the overlay code from `consult--async-process`,
3. [ ] Add an `'report` (or call it `'status`?) action to the async functions (see all actions in the docstring of `consult--async-sink`). When an async function is called with the `'status` argument it should probably return a plist.

**Comment by minad** [comment]
Putting this on hold for now as discussed.
