### ISSUE TITLE
Fix character folding in `consult-line`

### ISSUE THREAD

**Issue by salutis** [minad/consult#372]
Searching for`Bezier` finds `Bézier` in Emacs when `search-default-mode` is `char-fold-to-regexp`. When searching with `consult-line`, that is not the case.

**Comment by minad** [comment]
This depends on the completion style your are using, probably Orderless. Please ask on the Orderless issue tracker or maybe @oantolin can chime in here. Maybe some completion style tweak allows the desired folding?

**Comment by oantolin** [comment]
`consult-line` uses whatever completion styles you have configured to do the matching, and this probably best addressed at the level of completion styles. For example, if you are using orderless, you can simply add `char-fold-to-regexp` to `orderless-matching-styles`. (See oantolin/orderless#69)

**Comment by minad** [comment]
@oantolin Thanks, for coming here so quickly. Easier than I expected!

**Comment by salutis** [comment]
@oantolin 

Wow! I am pretty sure that the president of the US does not have this good software support. 3 minutes, from the question to solution. What is this, some NASA mission critical team, waiting for Emacs users to encounter problems?

Thank you!

For future readers:

```
(add-to-list 'orderless-matching-styles 'char-fold-to-regexp)
```
