### ISSUE TITLE
The docstring for consult-menu mentions the non-existent consult-imenu-project

### ISSUE THREAD

**Issue by oantolin** [minad/consult#376]
I only noticed because the byte-compiler complains about consult-imenu-project when compiling embark-consult.

**Comment by oantolin** [comment]
Also there is an obsolete function alias for `consult-project-imenu`, with project and imenu swapped.

**Comment by minad** [comment]
Oh okay. Let me check!

**Comment by minad** [comment]
The swap is because this was the old-old name. I changed it in quick succession, so it is okay like this.
