### ISSUE TITLE
Feature like `isearch-yank-word-or-char`

### ISSUE THREAD

**Issue by Lenbok** [minad/consult#378]
I'm not sure if this belongs here or in vertico / selectrum. Let me know if I should open this elsewhere.

In isearch I use `C-w` to pull in the word at point into the search term (and ivy similarly has `ivy-yank-word`). It would be great if `consult-isearch` and `consult-line` supported this feature as well. (or if it's already there can you point me at how to enable it).

Cheers!

**Comment by minad** [comment]
Yes, there already exist multiple ways to do this. You can also search through the issue tracker or the Consult wiki.

1. `consult-line`, then twice `M-n` to access the symbol at point in the future history. You can also bind `C-w` `(define-key vertico-map "\C-w" "\M-n\M-n")`.
2. `embark-act` on the symbol at point, then `C l` to run `consult-line`.
3. Write your own `consult-line-symbol-at-point` command (see the wiki).

I hope this helps!

**Comment by oantolin** [comment]
To be fair, none of those techniques substitutes for isearch's C-w in full generality. You can press C-w more than once, and you can even move to a different match between C-w's.

For example, if point is right before `foo bar`, a little later in the buffer there is a `foo baz` and you want to search for `foo baz` you can go `C-s C-w C-s C-w`. If in the same example you want to search for `foo bar` (i.e, `C-s C-w C-w`), that you can also do with embark-act: just mark `foo bar` and then use the `C l` action.

**Comment by minad** [comment]
Yes, but should also note that `consult-line` does not aim to replace Isearch. I use both search commands and this is also what I recommend. `consult-line` is only a simple line based search, like a grep in Emacs to filter the current buffer. On the plus side, `consult-line` allows you to use you favorite completion style and depending on the completion UI you get a live updating list of the search results.

**Comment by oantolin** [comment]
Me too! Even before `consult-line`, back when I used Ivy, I tried using swiper instead of isearch and didn't get used to it. I think isearch is best for getting the point to some location, while swiper and consult-line are better at browsing and getting an overview.

**Comment by oantolin** [comment]
> depending on the completion UI

It was nice of you to throw that in their, but I don't mind it when people talk as if default completion didn't exist. 😛

**Comment by minad** [comment]
> I think isearch is best for getting the point to some location, while swiper and consult-line are better at browsing and getting an overview.

I agree fully with that. And for quick and short jumps avy is also a solution.

**Comment by Lenbok** [comment]
Thanks for the tips. 

Personally I use avy for getting the point to a location when it's on the visible screen, and for locating matches in the wider buffer I've been using `swiper-isearch` which is like `isearch` but with a visual overview. 

I regularly use the `C-s C-w C-s C-w` type of functionality for refinement (often via `C-s C-w`, ...scroll through match list..., `C-w` to pull in more pattern from where the point is, repeating as required) - it seems this "pull in from where point is now" would need to be done via a custom function - can you suggest how can I get that?

**Comment by minad** [comment]
Okay I see. Swiper-isearch is out of scope for this package, since I want to avoid the overlap with Isearch.

To access the word at point in the original buffer switch to the original buffer with `minibuffer-with-selected-window`. Then you can obtain the string at point and use it to update the search string. But I am unsure if this will lead to a satisfactory solution. Consult-line filters lines and you cannot jump between multiple matches at point.

**Comment by kent-engstrom** [comment]
I found this ticket when searching for a solution to one of the few things that I miss after upgrading from swiper to consult-line. The thing that is stuck in my fingers, and I cannot find a good replacement for is a situation where want to search for a few consecutive words. Like when a file contains lines like:

> See the quick brown fox run.
> 
> And later, watch the quick brown fox jump higher.

and I am at the first line, before "the", and can search for "the quick brown fox", by just doing C-s C-w C-w C-w C-w. Finding out about double M-n solves some of my problems (searching for a single word/symbol).
