### ISSUE TITLE
Possible orderless support for grep patterns

### ISSUE THREAD

**Issue by minad** [minad/consult#381]
In order to support this the functions `consult--compile-regexp` and `consult--convert-regexp` must be replaced by Orderless/Pcre2el or an alternative more powerful converter.

https://github.com/minad/consult/blob/d9e7a6bc10f57b420f25365f278ca75f3652b020/consult.el#L593-L611

See also the discussion in #380.

**Comment by minad** [comment]
This seems to work already:

~~~ elisp
(advice-add #'consult--compile-regexp :before-until #'consult-orderless-regexp)
(defun consult-orderless-regexp (input type)
  (pcase type
    ((or 'extended 'lookahead)
     (mapcar #'consult--emacs-to-extended-regexp (orderless-pattern-compiler input)))
    ('emacs
     (orderless-pattern-compiler input))))
~~~

cc @oantolin

**Comment by minad** [comment]
This seems to work well. Documented in the wiki for now: https://github.com/minad/consult/wiki#use-orderless-as-pattern-compiler-for-consult-grepripgrepfind

**Comment by oantolin** [comment]
Why do you limit the matching styles to only literal and regexp in `consult-orderless-regexp`? If it's just those, I don't think there's much point to doing this at all. The only thing you gain is the ability to match literals without explicit quoting.

For me the attraction would be to be able to use my normal orderless configuration. Do the other styles usually generate regexps that are hard to translate or something?

**Comment by minad** [comment]
The Orderless matching styles are not a problem. The translation covers everything we need. I temporarily had `char-fold-to-regexp` in my config by default, but removed it again due to its complex regular expressions. I think if you use literal+regexp by default and opt-in to fancy other styles (char folding and other custom transformations) via style dispatchers it is no problem to use Orderless by default for grepping. Please give it a try!

If it turns out that the configuration of Orderless is a good default setting (needs more testing), I can recommend it in the README. Maybe a hook would then make sense, but the advice I am currently using is also not too bad. 

It would be great if Orderless could do a little bit better regarding the regular expressions it generates (see https://github.com/oantolin/orderless/issues/73).

**Comment by minad** [comment]
There is one more limitations I should mention. Currently for each command you can specify a :highlight function which transforms the input to a list of regular expressions. I implemented it this way since for each candidate you may only want to highlight a substring of the candidate (e.g. the part after `file:line:` in grep). Unfortunately we lose the different faces by doing that. A better approach would be to have a `highlight-function : string -> (string -> int -> int -> ())`, which first takes the input and then returns a function which adds the faces to the candidates, but only in the given range. This requires a modification of the Orderless highlighting API `orderless--highlight`. I think `orderless--highlight` can be optimized a little bit by not allocating the `match-data`. The problem is that for `consult-grep` the faces are not applied lazily but for all returned results as they come in. The grep candidate transformation is a bottleneck of `consult-grep`.

**Comment by minad** [comment]
I overhauled the infrastructure once more. The way to integrate orderless is now this:

~~~ elisp
(defun consult--orderless-regexp-compiler (input type &rest _config)
  (setq input (orderless-pattern-compiler input))
  (cons
   (mapcar (lambda (r) (consult--convert-regexp r type)) input)
   (lambda (str) (orderless--highlight input str))))
(setq consult--regexp-compiler #'consult--orderless-regexp-compiler)
~~~

**Comment by minad** [comment]
I found that `orderless-without-literal` does not work with `consult-ripgrep`, when the pcre engine is not used, since then the regexps will be concatenated using `.*`, e.g., `regexp1.*regexp2`. It works if pcre lookahead concatenation is used.
