### ISSUE TITLE
Quit, with focus off of minibuffer

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#382]
In a long running `consult-line` or similar, sometimes you end up navigating away from the minibuffer into one of the previewed buffers consult has pulled up to poke around.  It would be nice if `C-g` in that buffer quits the consult session as well.  This would emulate a progressive isearch, which has point in the buffer, but which `C-g` can quit.

**Comment by minad** [comment]
Thanks for the proposal! My opinion is that changing the quitting behavior of recursive minibuffers is out of scope of Consult. You can however write your own command based on `(abort-recursive-edit)`, `(keyboard-quit)`, `(keyboard-escape-quit)`, `(abort-minibuffers)`, `(minibuffer-keyboard-quit)` or any other appropriate quitting function and temporarily bind it to `C-g`. The question is also if you want to quit all existing recursive minibuffers or only the inner-most. I lost track of which function to use in which case, but I am sure there is one which gives the desired behavior :)

**Comment by oantolin** [comment]
I think `abort-recursive-edit` (bound by default to `C-]`) does this out of the box.

**Comment by jdtsmith** [comment]
That does work and is what `C-g` is bound to in the mini-buffer.  In fact I'm considering doing this "everywhere":

```elisp
;; Abort recursive edit on C-g
(defun my/quit-abort ()
  (interactive)
  (if (> (minibuffer-depth) 0)
      (abort-recursive-edit)
    (keyboard-quit)))
(bind-key "C-g" #'my/quit-abort)
```

Any issues you can envision?

**Comment by minad** [comment]
I guess the downside is that it does what it does. You may want to press `C-g` and *not* quit the recursive editing session. ;)

You could also bind this temporarily only for `consult-line` as you initially proposed.

**Comment by jdtsmith** [comment]
I was searching for a specific example of wanting to "quit without also quitting an active recursive editing session". I can't think of any off-hand, but maybe you already have such an example in mind!
