### ISSUE TITLE
Latest update brakes consult-grep, consult-git-grep and consult-rip-grep

### ISSUE THREAD

**Issue by sinauq** [minad/consult#384]
Hi, 
First of all this package is brilliant, thank you @minad.
I just updated consult from melpa and I ran into error when trying to grep or git-grep on a directory.

With grep:
`‘consult-grep’ uses a deprecated command configuration \"grep --null --line-buffered --color=always --extended-regexp   --exclude-dir=.git --line-number -I -r . -e ARG OPTS\"`

With git-grep:
`‘consult-git-grep’ uses a deprecated command configuration \"git --no-pager grep --null --color=always --extended-regexp   --line-number -I -e ARG OPTS\"`

With rip-grep:
`‘consult-ripgrep’ uses a deprecated command configuration \"rg --null --line-buffered --color=ansi --max-columns=1000   --no-heading --line-number . -e ARG OPTS\"`

I'm on Emacs 27.2 and Consult 20210806.214 also since I don't use ripgrep don't know

**Comment by minad** [comment]
Thank you for the report! Did you customize these variables? I introduced new configuration variables, deprecating the old ones and made the error messages more instructive.

**Comment by sinauq** [comment]
I don't recall customizing them. But I think I should've read the
documentation more closely before reporting it.
