### ISSUE TITLE
`consult-imenu` is different from all other narrowable multi-consult commands

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#385]
The group title searchable/non-searchable asymmetry between `consult-imenu` and `consult-buffer` (for example) has been bugging me. 

First I thought: it must be a deep and unavoidable part of the imenu backend, but I can work around this.  I searched for a predicate based solution to trim out any candidates which match _only_ in their prefix (like `Functions`), but that's not easy, since completing-read predicates operate only _well before_ candidate matching occurs (e.g. with orderless).  I could extend `vertico--highlight-function` or advise `orderless-highlight` for example, but that's fairly remote from the origin of the issue.  I.e. all rather ugly & brittle solutions.

Then it occurred to me that the most robust approach would be to alter/advise `consult-imenu` to be **tofu-based**, just like `consult-buffer`.  This looks straightforward with `tofu-get` and `tofu-append`, but less clear is the suitable place to transform an imenu-generated candidate (stripping "Functions"/"Variables"/etc.).  

But then, looking deeper into it, I discovered that `consult-imenu` is _itself prepending the category name to the candidates_!  Given that, I don't understand why `consult-imenu` isn't tofu-based, like all other multi-category narrowable consult commands (buffer, bookmarks, registers, commands, ...).   Unless I'm missing something, the imenu categories could have just as easily (even more easily?) been _encoded as a tofu derived from the narrowing key_ instead of using a pre-pended string.

Put another way, in `consult-buffer` I cannot start typing the word "Buf" and have it filter only to buffers; in `consult-bookmark` I cannot start typing "Fil" and filter to File-based bookmarks.  But in `consult-imenu` I can type "Fun" and have it match "Functions" across the board (whether I want that or not). 

I've long used imenu from a mouse popup, where it looks like:

![image](https://user-images.githubusercontent.com/93749/128607775-79453df7-8cf0-4bf3-8c4c-be588d582bf2.png)

I.e. categories are simply _groupings_, not an intrinsic part of the candidate itself.  To me, bringing `consult-imenu` in line with the rest of the narrowable multi commands (using tofus and simply narrowing keys for category refinement) just seems like the right thing to do,  both for consistency, and the "principle of least surprise" for the user. 

Thanks for all your work on consult: it's getting more excellent by the day!

**Comment by minad** [comment]
@jdtsmith You are confusing/mixing multiple things here. Let's look at this on a higher level. You are bugged by the asymmetry regarding the searchability of the imenu/buffer type? Which behavior do you prefer, both searchable or both non-searchable?
@jdtsmith

**Comment by minad** [comment]
consult-imenu is the odd one out since the prefix is generated by the backend itself, as you observed. For example if you have an org file, the topmost title will be prepended to all subtitles. If the backend decides to generate topmenus like "Function" these will be shown as is by consult-imenu. The oddity which consult-imenu adds on top is grouping and narrowing. You can also disable the narrowing/grouping by adjusting consult-imenu-config, or by overwriting :group via consult-customize only for consult-imenu.

**Comment by jdtsmith** [comment]
I'd advocate for all non-searchable (like the vast majority of narrowable consult commands including `consult-buffer`).  In this context, key narrowing would be the solitary method for category refinement.  But making all searchable like `consult-imenu` would also satisfy the consistency issue.

**Comment by minad** [comment]
Okay, I don't want to make them searchable generally. If you want to make the prefix non-searchable for consult-imenu, then it is not easy to achieve this unfortunately. You can rewrite consult-imenu--flatten.

**Comment by jdtsmith** [comment]
I see.  If I understand correctly, you're saying that all the other multi-consults gather info from known, disparate sources, whereas imenu returns an unconstrained categorized list of grouped (or top-level) values, which can vary by major mode, etc.  

If one mode groups into "Functions", "Variables", etc. and another adds "Classes" and "Signatures" or whatever, and another doesn't provide groups at all... all of this can still be disambiguated with narrowing keys and tofus, yes?  Or is the concern that imenu in some mode will provide an _unforeseen_ category that consult doesn't (yet) know about?  So that if you just prepend it, you can't use narrowing keys, but at least you can "search-narrow" it?

**Comment by minad** [comment]
Yes, if we remove the prefixes if some setting we would require tofus for disambiguation. Fruthermore as you rightly observed, if we remove unknown prefixes we would not have any means to narrow to those.

Btw there is another asymmetry. consult-grep post-filtering allows to search the prefix too. So the claim that only consult-imenu is inconsistent with the rest is false.

**Comment by oantolin** [comment]
It's probably worth thinking about the org mode case for imenu: there the "categories" returned by imenu are the top level headings and the imenu "items" are the second level headings. I would not want to pick a top level heading by narrowing (what would the narrowing key even be? the first character in the head line and I take care to not use the same first character in my org files?).

**Comment by jdtsmith** [comment]
> Furthermore it is not reasonable to provide this as an option because grouping/group titles may not be available at all. Therefore we cannot just remove the prefix.

I.e., for an imenu backend that provides no grouping?  In that case, you'd need no tofus (and have no ability to append them anyway), and don't need any narrowing.  So that becomes super simple.

**Comment by minad** [comment]
@oantolin Exactly consult-imenu is consistent with consult-imenu to not remove the prefixes. Therefore it is not done here.

**Comment by oantolin** [comment]
> > Furthermore it is not reasonable to provide this as an option because grouping/group titles may not be available at all. Therefore we cannot just remove the prefix.
> 
> I.e., for an imenu backend that provides no grouping? In that case, you'd need no tofus (and have no ability to append them anyway), and don't need any narrowing. So that becomes super simple.

I think @minad meant that not every completion UI has grouping support, @jdtsmith. The default completion doesn't, nor does the built-in icomplete-vertical-mode in Emacs 28 (I think, I'm not following that closely). Nor does embark collect, yet (it's planned).

**Comment by minad** [comment]
> I.e., for an imenu backend that provides no grouping? In that case, you'd need no tofus (and have no ability to append them anyway), and don't need any narrowing. So that becomes super simple.

No, I meant if grouping/group titles are not available/disabled by the frontend. In that case you have no visual distinction between the different groups anymore and also no means to search. You only have narrowing, but this is only available if properly configured and will break if unknown imenu prefixes occur.

**Comment by minad** [comment]
@oantolin The default UI has grouping support. I added this to Emacs 28. But you are exactly right, I meant that grouping may not be available by the UI.

**Comment by jdtsmith** [comment]
> It's probably worth thinking about the org mode case for imenu: there the "categories" returned by imenu are the top level headings and the imenu "items" are the second level headings. I would not want to pick a top level heading by narrowing (what would the narrowing key even be? the first character in the head line and I take care to not use the same first character in my org files?).

Aha. I'm not an org-mode user (despite knowing Carsten D. well), but that's a very good point.  So these are not foreseen or foreseeable categories at all, and never will be.  In fact, they are not "categories" but really a hierarchy nested items.  I hadn't appreciated that.  

But for many modes, the imenu categories _are_ fixed and foreseeable.  For those, it might be nice to treat them like other fixed category consult-multi's (with tofus).

**Comment by jdtsmith** [comment]
> @jdtsmith
> 
> > I.e., for an imenu backend that provides no grouping? In that case, you'd need no tofus (and have no ability to append them anyway), and don't need any narrowing. So that becomes super simple.
> 
> No, I meant if grouping/group titles are not available/disabled by the frontend. In that case you have no visual distinction between the different groups anymore and also no means to search. You only have narrowing, but this is only available if properly configured and will break if unknown imenu prefixes occur.

I see.  But how do all the other commands which use tofus for category and/or disambiguation deal with this?  Don't they have the same issue in non-groupable UI's?

**Comment by minad** [comment]
> I see. But how do all the other commands which use tofus for category and/or disambiguation deal with this? Don't they have the same issue in non-groupable UI's?

They have the same problem. But as far as I see it the only problematic command is `consult-buffer`. If you disable `marginalia-mode` and disable group titles you will see annotations, which show the group type.

**Comment by jdtsmith** [comment]
> Btw there is another asymmetry. consult-grep post-filtering allows to search the prefix too. So the claim that only consult-imenu is inconsistent with the rest is false.

That's a good point, but grep also includes a special `##` format for async grep regex vs. list narrowing, so it was special already :).

**Comment by jdtsmith** [comment]
I just tried `consult-imenu` in an org file and this is now 100% clear to me why you certainly will need a prepending approach in `consult-imenu`.

If a mode is specified with `:types` in `consult-imenu-config`, does that imply its types/categories are fixed and complete?  If so, any mode (like `emacs-lisp-mode`) configured that way could be treated with narrowing+tofus, and otherwise they could use the prepend method.

**Comment by oantolin** [comment]
> The default UI has grouping support. I added this to Emacs 28. But you are exactly right, I meant that grouping may not be available by the UI.

@minad, sorry I forgot about that! But I would phrase it in future tense: "In Emacs 28 the default completion UI _will_ have grouping support". (I think I don't have it yet, for example, not even on my Windows machine where my Emacs 28 is recent enough to have native compilation.) Does the built-in icomplete-vertical-mode have it too?

> I just tried `consult-imenu` in an org file and this is now 100% clear to me why you certainly will need a prepending approach in `consult-imenu`.

@jdtsmith I also have a vague recollection that some major mode for an object-oriented language used class names as categories, and method names as items, but I may be misremembering. Even if no current major mode does that, I think that would be a good idea.

**Comment by minad** [comment]
@jdtsmith 

> If a mode is specified with :types in consult-imenu-config, does that imply its types/categories are fixed and complete?

No, this does not mean that it is complete. You as a user would have to make sure that it is complete.

>  If so, any mode (like emacs-lisp-mode) configured that way could be treated with narrowing+tofus, and otherwise they could use the prepend method.

Yes, one could consider this, but this is all too much special casing for me. It may not look like this, but my general goal with Consult and related packages is to keep things simple.

@oantolin 

> "In Emacs 28 the default completion UI will have grouping support". (I think I don't have it yet, for example, not even on my Windows machine where my Emacs 28 is recent enough to have native compilation.)

I think you should have a sufficiently recent Emacs around, if you updated your installation not too long ago (Didn't you do this to test the other PR about post-command-hook/macros?). But you have to enable it explicitly.

> Does the built-in icomplete-vertical-mode have it too?

No. Someone would have to write a patch for that. But icomplete-vertical-mode in Emacs 28 seems to be much in flux.

**Comment by jdtsmith** [comment]
@minad , @oantolin 
Thanks for a robust discussion.  I'll seek another workaround and report back if I find something simple.

**Comment by oantolin** [comment]
> I see. But how do all the other commands which use tofus for category and/or disambiguation deal with this? Don't they have the same issue in non-groupable UI's?

As a person guilty of using a UI without grouping, I can answer this, @jdtsmith. For commands like `consult-grep`, the grouping moves the file name to the group title position; but when your UI does not support grouping, you instead see normal looking grep results with the file name prepended to each match. As @minad said, the only consult command where the information from the grouping is not normally visible in the candidates is `consult-buffer`. I find I don't need that information at for `consult-buffer`: the whole point of that command for me is that it list things that I want to switch to _as if they were open buffers_, so if they aren't, I don't care and don't need to know _what_ they are.

**Comment by minad** [comment]
@oantolin 

> I find I don't need that information at for consult-buffer: the whole point of that command for me is that it list things that I want to switch to as if they were open buffers, so if they aren't, I don't care and don't need to know what they are.

This is a good argument!

**Comment by oantolin** [comment]
In general I view grouping as a UI trade-off: are you willing to sacrifice vertical space in exchange for reduced clutter? I think I probably prefer to keep my vertical space and don't think that, say, grep results, look particularly ugly. To me grouping definitely looks significantly prettier, but that prettiness doesn't fully make up for the lost vertical space. (But of course, I'm also the nut case that doesn't use Vertico or Selectum mostly because they don't have a dense grid view.)

**Comment by jdtsmith** [comment]
Though they are fairly minor commands, things like `consult-mode-command` and `consult-bookmark` also have grouping that isn't prepended (though perhaps also "ignorable" for many users, as for you with `consult-buffer`).  

I agree about the vertical space tradeoff.  Maybe I'm a sucker for pretty ;).  But I also like grouping because it confers at a glance _what kind of narrowing_ I can do. (BTW, idea that just occurred: consult could underline the first letter of the group title that matches its narrowing command letter, so you don't have to remember them).

**Comment by jdtsmith** [comment]
> I find I don't need that information at for `consult-buffer`: the whole point of that command for me is that it list things that I want to switch to _as if they were open buffers_, so if they aren't, I don't care and don't need to know _what_ they are.

I also like this argument.  But do you use tramp?  There can be a pretty big distinction between open buffer and recent file when over a slow multi-hop link!

**Comment by oantolin** [comment]
I do use TRAMP, but I'm somehow usually aware of whether a file is remote or not. At least I don't remember being surprised by a remote file taking a long time to open: I usually expect it to take a long time. For me it's not even just TRAMP, for example ORg takes a long time to load, and I just expect that the first time in an Emacs session that I use consult-buffer to switch to a recent org file I'll have to wait several seconds.

**Comment by minad** [comment]
@jdtsmith 

> (BTW, idea that just occurred: consult could underline the first letter of the group title that matches its narrowing command letter, so you don't have to remember them).

This idea has come up a few times already. I even have a prototype in the branch [title-keys](https://github.com/minad/consult/tree/title-keys). I haven't added this since it feels very unnecessary and noisy. I would switch it off immediately.

**Comment by jdtsmith** [comment]
OK, my workaround is as follows, for orderless only.  It's not _nearly_ as simple as hoped, but it seems to work well.  The idea is to patch orderless within consult-imenu (only) to prepend a regexp of all the possible category names (if any) at the start of each and every compiled pattern.  This forces the user-entered patterns to match text _after_ the category names, which are always there.  I also had to patch the highlighter to show the first match _after_ the `consult--type` category (_without_ the categories regexp in front).  I have to look out for and replace `\\'` in the compiled patterns (e.g. `orderless-without-literal`) since I'm already tying the category names to the start of the string. 

```elisp
(defun my/consult-imenu-around-advice (ci-orig &rest r)
    "Patch orderless to inhibit matching group categories in consult-imenu."
    (if-let* ((config (cdr (seq-find (lambda (x) (derived-mode-p (car x)))
				     consult-imenu-config)))
	      (types (plist-get config :types))
	      (types-regex (rx-to-string
			    `(and line-start (or ,@(mapcar #'cadr types)) ? ))))
	(cl-letf* ((of-orig (symbol-function 'orderless-filter))
		   ((symbol-function 'orderless-filter) ;patch pattern compiler within filter
		    (lambda (&rest r)
		      (cl-letf* ((opc-orig (symbol-function 'orderless-pattern-compiler))
				 ((symbol-function 'orderless-pattern-compiler)
				  (lambda (&rest r)
				    (mapcar (lambda (x) ;replace beginning-of-string
					      (if (string-match (regexp-quote "\\`" ) x)
						  (concat types-regex
							  (replace-match "\\b" nil t x))
						(concat types-regex ".*?" x)))
					    (apply opc-orig r)))))
			(apply of-orig r))))
		   (oh-orig (symbol-function 'orderless--highlight))
		   ((symbol-function 'orderless--highlight)
		    (lambda (regexps string)
		      (if-let* ((pref
				 (next-single-property-change 0 'consult--type string)))
			  (cl-letf* ((sm-orig (symbol-function 'string-match))
				     ((symbol-function 'string-match)
				      (lambda (re str)
					(funcall sm-orig re str (1+ pref)))))
			    (funcall oh-orig regexps string))
			(funcall oh-orig regexps string)))))
	  (apply ci-orig r))
      (apply ci-orig r)))
			   
  (advice-add #'consult-imenu :around #'my/consult-imenu-around-advice))
```

Thoughts, feedback, or yuck emoji welcome.

**Comment by minad** [comment]
The idea to adjust the completion style is a good one. See also https://github.com/minad/consult/issues/342#issuecomment-868380340.

**Comment by jdtsmith** [comment]
Thanks.  I had considered a custom (meta-)style, but I want to have the full flexibility of dispatchers and arbitrary styles list that I can later change.  I could have advised the general orderless dispatcher to wrap each and every style it reports (including defaults) with something that prepends the category matcher, but I'd _still_ have to check for `\\'`.  So sadly this seemed the simplest approach (though I'm probably missing something!). 

BTW, any thought on how to (programmatically) turn _off_ the group name formatting you restored, to make it consistent again with groups in other consult commands — _ducks_ :) ?

**Comment by minad** [comment]
I am not sure I understood you correctly. You can replace group function individually per command via consult-customize.

**Comment by jdtsmith** [comment]
Sorry I should have been more clear.  You restored the highlighting of group names in [vertico#39](https://github.com/minad/vertico/issues/39).  That's now unnecessary for me with my orderless "ignore the group names" hack.

**Comment by jdtsmith** [comment]
Also a (mostly off-topic) coding tip request.  I often find myself doing _conditional wrapping_, like:

```elisp
(if some-condition
    (let ((some-var t))
      (apply original-function some-arg rest-args))
  (apply original-function some-arg rest-args))
```

Do you know of an idiomatic elispy way to avoid repeating oneself here?

**Comment by jdtsmith** [comment]
I've added my hack to the [wiki](https://github.com/minad/consult/wiki#make-consult-imenu-ignore-fixed-group-titles-when-searching-with-orderless).

**Comment by minad** [comment]
> Sorry I should have been more clear. You restored the highlighting of group names in vertico#39. That's now unnecessary for me with my orderless "ignore the group names" hack.

I don't think there is an easy way. You can replace the entire vertico format/arrange candidates function.

**Comment by minad** [comment]
> Do you know of an idiomatic elispy way to avoid repeating oneself here?

I am not sure there is a better way. If you have only a function call inside the conditional, the amount of duplication is already minimal. You can of course write a macro.

**Comment by hmelman** [comment]
> Do you know of an idiomatic elispy way to avoid repeating oneself here?

If you're just temporarily changing the value of `some-var` this could work.  Not so much if you don't want `some-var` bound at all.
```elisp
(let ((some-var (if some-condition t some-var)))
  (apply original-function some-arg rest-args))
```

**Comment by minad** [comment]
@jdtsmith I changed the description of the imenu hack slightly in the hope to reduce confision, see https://github.com/minad/consult/wiki#make-consult-imenu-ignore-group-titles-when-searching-with-orderless. Please let me know if it still makes sense to you.

**Comment by jdtsmith** [comment]
> Please let me know if it still makes sense to you.

Looks good, thanks.  I fixed a grammatical mistake and added a few subordinate phrases to make it clearer.

**Comment by jdtsmith** [comment]
> > Do you know of an idiomatic elispy way to avoid repeating oneself here?
> 
> If you're just temporarily changing the value of `some-var` this could work. Not so much if you don't want `some-var` bound at all.
> 
> ```emacs-lisp
> (let ((some-var (if some-condition t some-var)))
>   (apply original-function some-arg rest-args))
> ```

Thanks.  I was being simplistic in my example.  What I'm typically doing (as in the above case of advising orderless) is `cl-letf`'ing a function to override it (or not, depending on some condition(s)).  I could use a variant of your method, but would have to first save the symbol function and then reset it.  Maybe not too terrible:

```elisp
(cl-letf* ((old (symbol-function func))
	   ((symbol-function func)
	   (if condition
	       (lambda (&rest r)
		 (do-something-first r)
		 (apply old r))
	     old)))
  (apply original r))
```

There is also the method of _always_ advising the original function and just testing for some (global) condition in it, which I think the elisp manual recommends.

I was hoping there was some pre-existing macro that would expand `(conditional-temporary-bind x y z f)` to:

```elisp
(if x
    (cl-letf* ((old-y (symbol-function y))
	       ((symbol-function y) z))
      (apply f rest))
  (apply f rest))
```

where `z` could also call `old-y`.
