### ISSUE TITLE
Update which-func on preview jump

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#387]
I have `which-func` in my modeline, but consult preview does not update it, because the idle timer which does so never runs.  I fixed this with:

```elisp
(add-hook #'consult-after-jump-hook #'which-func-update)
```

Perhaps worth adding by default?

**Comment by minad** [comment]
No, this is not a good default setting. which-func-mode can be very slow. I don't enable it anymore in my configuration. Perhaps the configuration should be mentioned in the wiki?

**Comment by jdtsmith** [comment]
> Perhaps the configuration should be mentioned in the wiki?

Could do so.  

> which-func-mode can be very slow.

That's likely why an idle timer is used by which-func itself.  Is it possible to allow idle timers to run if consult is awaiting input? That would make the above suggestion unnecessary.

**Comment by minad** [comment]
As far as I know Consult does not prevent idle timers to run.

**Comment by minad** [comment]
Probably the issue is that while you are in the minibuffer which func does not update since you are in the minibuffer.
