### ISSUE TITLE
consult and org

### ISSUE THREAD

**Issue by mclearc** [minad/consult#392]
This is unlikely a bug, but I was wondering why initially calling any consult function loads org? This isn't great for me since it takes several seconds to load org for the first time. It would be nice to defer loading until I load org intentionally (e.g. by loading an org file or calling something like `consult-org-agenda`, etc.)

**Comment by minad** [comment]
This is a bug in your configuration. Consult does not load Org. The only package which loads Org is `consult-org`, this means only `consult-org-agenda` etc load Org, which is of course unavoidable.

You can try to debug your configuration with code like this:

~~~ elisp
(advice-add 'require :before (lambda (feat &rest args)
                               (message "%s" feat)
                               (if (eq feat 'org) ;; Print a backtrace when loading org
                                 (backtrace))))
~~~

**Comment by minad** [comment]
There is also the consult preview which may load org, but I assume you are aware of this. See https://github.com/minad/consult#use-package-example and the consult-customize setting which disables automatic preview for recent files.

**Comment by oantolin** [comment]
Preview in consult-buffer is my new standard way of loading org, in fact. 😉
