### ISSUE TITLE
[Question] Asking about some changes in the behaviour of Consult's regex matching

### ISSUE THREAD

**Issue by mohamed-abdelnour** [minad/consult#393]
Hello, @minad!

I have a few questions regarding some changes in the behaviour of Consult's regex matching. I'll be comparing Consult `main` (as of b54ea2dbf68cd6c7c585ad8cc572109195a5596f) and Consult 0.8. None of these are really "issues", thankfully, I'm just pointing this out in case something isn't working as expected. :)

I tested everything with both my config and `emacs -Q` with Vertico and Consult manually added to `load-path` and required. I explicitly tested `consult-grep` and `consult-ripgrep`.

The examples are run in a directory with one single file containing the following:

```txt
aaaa bbbb
bbbb aaaa
aaaa xxxx bbbb
aaaa
bbbb

axxx
bxxx
```

### Matching a literal `SPACE` character

With an input of `"aaaa bbbb"`:

- `main`:

  - Generated pattern: `"-e" "^(?=.*aaaa)(?=.*bbbb)"`
  - Matches:
    - `aaaa xxxx bbbb`
    - `bbbb aaaa`
    - `aaaa bbbb`

- v0.8:
  - Generated pattern: `"-e" "aaaa bbbb"`
  - Matches:
    - `aaaa bbbb`

`main` matches a string including _both_ `aaaa` and `bbbb` in either order and with "anything" (`.*`) between them, while v0.8 matches `aaaa bbbb` literally.

Personally, I would expect `aaaa bbbb` to either be matched literally or maybe match either `aaaa` or `bbbb`. The current behaviour seems a little odd to me, though.

Also note that, with `main`, the highlighting is potentially misleading. Only `aaaa` and `bbbb` are highlighted, so one may assume that it's matching either `aaaa` or `bbbb`.

![2021-08-09-11-48-46](https://user-images.githubusercontent.com/68501778/128698674-0940b2a5-9c4f-4646-83c0-7cb8527615a1.png)

There are ways of forcing `main` to match a space literally; the one I can think of is providing a pattern that would never match anything followed by the one we want, like this: `.^ -- -e "aaaa bbbb"`. But that's a little cheating. ;) Note that this only works with double quoting, and `main` doesn't highlight this properly while v0.8 does so just fine.

![2021-08-09-12-34-45](https://user-images.githubusercontent.com/68501778/128698943-87f0cc3c-bf04-40a5-ba3e-96b9dc044670.png)

![2021-08-09-12-35-40](https://user-images.githubusercontent.com/68501778/128698964-bcd21c4f-406e-4e17-84db-b9dacac6e7b6.png)

### Extended regex special characters

Let's say we want to match `a` **OR** `b` followed some number (greater than zero) of `x`'s. With v0.8, we could use `[ab]x+` or `(a|b)x+`, for example. They both get passed literally, so we don't need to worry about escaping any characters. With `main`, `[ab]x+` works properly, because it doesn't use any extended regex special characters. However, `(a|b)x+` doesn't work; we'd have to use `\(a\|b\)x+` instead.

Also note that with `main`, `\(a\|b\)x+` is not highlighted correctly.

![2021-08-09-13-05-53](https://user-images.githubusercontent.com/68501778/128699151-ea8f0e96-b7c7-4d63-97a7-6c2d037672e9.png)

Is that the expected behaviour with both of these, or do you think there is something to improve upon?

I'd be happy to try to help (if I can) if there's anything you want to work on. Looking forward to getting your feedback!

**Comment by minad** [comment]
Yes, it is all expected and correct.

* Space is either replaced by `.*` if the regexp engine is too weak or by lookahead patterns if pcre if available or by --and arguments for git grep or find. The general idea is to allow orderless style matching.
* Only capturing groups are highlighted.
* There is currently indeed no easy way for literal space matching. This is a deficiency. Maybe we should improve this.
* The escaping of parentheses is necessary since the pattern compiler assumes Emacs regexp syntax and translates it to pcre internally. This is done for consistency with all of Emacs, where this syntax is pervasive.
* The match highlighting is done now entirely by Emacs based on the input regexp for flexibility. This also allows to use highlighting for commands which don't highlight themselves.
* You can of course turn off all this magic by replacing consult--regexp-compiler with a simpler function which essentially passes the input through. Look at the docstring of the variable for details.
* furthermore it is possible to use orderless as consult--regexp-pattern-compiler.

I hope this answers all your questions. I think all this should be documented a bit better in any case.

**Comment by mohamed-abdelnour** [comment]
> Yes, it is all expected and correct.

Glad to know that!

> I hope this answers all your questions. I think all this should be documented a bit better in any case.

Thank you, as always, for giving such a detailed response. That does answer all my questions, yes.

**Comment by minad** [comment]
If you have improvement proposals please let me know. I think the current behavior is reasonable. However I am not very happy with the degradation to "ordered" regular expressions if pcre is not available.

**Comment by mohamed-abdelnour** [comment]
> The general idea is to allow orderless style matching.

I also think the current behaviour is reasonable; I thought it was a little odd at first because I didn't realise that the goal was to achieve orderless-style matching; once you mentioned that, it all made sense.

I don't know of a good way of replicating the same behaviour if PCRE is not available. Obviously the best solution would be to have boolean operations similar to `git grep`; I just checked, and that's how you're doing it with `consult-git-grep`. With `grep` or `rg`, the "standard" way of achieving this, as far as I know, is to use piping: `rg aaaa | rg bbbb`, for example. This doesn't seem like a particularly good idea, though: it's less performant than using the PCRE engine, and I wouldn't be surprised if handling piping or buffering of some sorts from inside Emacs would introduce unnecessary complexity. Off the top of my head, the only advantage for piping I can think of would be if we cared about what the pattern is actually matching: `rg aaaa | rg bbbb` matches `aaaa` and `bbbb` while `rg -P '^(?=.*aaaa)(?=.*bbbb)'` technically just matches the start of a line, `^`. Fortunately, we don't given that the highlighting is now being handled inside Emacs. There's been a feature request over on the ripgrep repo for boolean expressions for quite some time now, BurntSushi/ripgrep#875. Having the power of `git grep`'s boolean expressions with the performance of `rg` would be incredible!

Of course, we can always generate all possible permutations of the input regexes, add `.*` between them and search for each one! ;) Jokes aside, if I ever have a good proposal for this, I'll be sure to let you know.

**Comment by minad** [comment]
Yes, there is no good way unfortunately - permutations are not a good idea of course. I tried this ;)

But now that you mention it again I think we should reconsider. Maybe permutations for up to three elements is exactly the way to go. And for more than three elements we print a warning and just IGNORE the additional elements? This will solve the common cases and the user can and should use post filtering to specify a fourth term.

**Comment by minad** [comment]
For additional trickery the splitting style could switch automatically to post filtering - but this is  maybe a bit too magical...

**Comment by mohamed-abdelnour** [comment]
I mentioned the permutations idea as a joke, but your suggestion actually sounds really good!

That sounds like it would be an interesting feature to have: Consult matches up to 3 elements using an orderless style, and for more than three elements, it automatically switches to a different style. We can either pass elements after the third one to post filtering; that way the results will have three elements matched "orderlessly" and the rest as filters, or we can completely switch to "ordered" matching if the user inputs more than three elements. I think either approach is good, we can discuss which one we want to implement if we decide to go through with the idea.

> Furthermore the splitting style could switch automatically to post filtering - but this is maybe a bit too magical…

It is magical, but in a good way, I think. I feel like if it is implemented and well-documented, it would be a really nice feature to have. I think that automatically switching to a different style is a more interesting solution than printing a warning and ignoring the rest of the elements, too.

Actually, we could even have a variable users can set to decide the maximum number of elements that are matched "orderlessly". 3 is a good default, but maybe someone would want to bump it a little higher. More interestingly, setting that variable to 1 should mean that Consults matches multiple elements in an ordered style; that would be an easy way to disable some of this magic for those who don't like it. It wouldn't disable all the magic, literal spaces would still be converted to `.*` or something, but it would definitely be less magical. ;)

Looking forward to hearing your thoughts!

**Comment by oantolin** [comment]
One more radical thing I've been wondering is whether maybe the `#args#filter` split is still necessary: with the increased power of the `args` part, now the `filter` part is less useful.

**Comment by minad** [comment]
@mohamed-abdelnour 

> That sounds like it would be an interesting feature to have: Consult matches up to 3 elements using an orderless style, and for more than three elements, it automatically switches to a different style. We can either pass elements after the third one to post filtering; that way the results will have three elements matched "orderlessly" and the rest as filters, or we can completely switch to "ordered" matching if the user inputs more than three elements. I think either approach is good, we can discuss which one we want to implement if we decide to go through with the idea.

I think only the switch to post filtering is a good idea or *ignoring* more than three inputs. Otherwise your search will suddenly get much less powerful when you enter the fourth term. Switching to post filtering seems like a simple idea, we can implement this as a `count` splitting style. 

@oantolin I don't think we should get rid of post filtering. It is quite useful to refine searches over larger projects, where the grep process has finished. I am considering to deprecating/removing the `space` splitting style, since it seems problematic now.

**Comment by oantolin** [comment]
> I consider deprecating/removing the `space` splitting style, since it seems problematic now.

Yes, probably a good idea.

**Comment by minad** [comment]
One more argument why splitting styles are a good idea - we can use Consult as a general interface to commands, websearch, etc. The backend could use its own query language. By providing the splitting style we can seamlessly integrate this with Emacs filtering.

**Comment by oantolin** [comment]
Excellent point!

**Comment by minad** [comment]
Let's keep this issue open for now.

**Comment by mohamed-abdelnour** [comment]
> I think only the switch to post filtering is a good idea or ignoring more than three inputs. Otherwise your search will suddenly get much less powerful when you enter the fourth term.

I agree, the search would get a lot less powerful with the fourth regex, but it would just be more consistent (not that consistency is always a good thing). 3 elements are all matched with an orderless style, while 4+ are all matched with an ordered style. That being said, I also think that using post filtering is great, as long as it's documented so that users expect the behaviour.

**Comment by mohamed-abdelnour** [comment]
> One more argument why splitting styles are a good idea - we can use Consult as a general interface to commands, websearch, etc. The backend could use its own query language. By providing the splitting style we can seamlessly integrate this with Emacs filtering.

That sounds fantastic!

**Comment by minad** [comment]
I am quite happy with the recent changes. Please give it a try. These points should still be addressed:

* Escaping space with `\`, currently you can write `[[:space:]]`, which is a bit verbose :D
* Introduce a `count` splitting style. I haven't done this yet since it is not a good general splitting style for commands with its own query language. Maybe we can come up with a better idea.

**Comment by mohamed-abdelnour** [comment]
> I am quite happy with the recent changes. Please give it a try.

The new changes are excellent, thank you! I think that the combination of being able to set `consult--*-regexp-type`, having the new `nil` splitting type and deprecating the `space` splitting style makes the current behaviour fantastic and very easily customisable.

> Escaping space with \, currently you can write `[[:space:]]`, which is a bit verbose :D

The downside to `[[:space:]]` is that it matches a whitespace character not just a space; in our case, that means it also matches a tab character. I don't think that's too big of a problem, though; I'm happy with that. We can always use `\s` instead; the results won't be properly highlighted because of the differences in Emacs's regex syntax, but again; I'm happy with that. If we _really_ want to fix the highlighting with `\s`, I think we can convert `\s` to `\s-` before applying the highlighting and that should work, correct? I'm not sure if doing that is justified, though; it may be a lot of work for something quite minor. And if someone ever wants to match literal spaces **only** and no other whitespace characters, something like `.^ -- -e "aaaa bbbb"` still works. The only other solution I can think of is implementing something similar to Vim's magic system, see https://vimhelp.org/pattern.txt.html#%2Fmagic. Similar in the sense that we could have a prefix character dictate how spaces and/or other special characters are handled. Again, I'm not sure if it'd be worth implementing something like that for the sake of literal spaces only but maybe if we have other use cases for it.

> Introduce a `count` splitting style. I haven't done this yet since it is not a good general splitting style for commands with its own query language. Maybe we can come up with a better idea.

Just to be sure, what were you thinking of with the `count` style exactly?

**Comment by mohamed-abdelnour** [comment]
While experimenting with the new changes I ran into something quite funny though. I don't think it's a big deal, but I'm going to point it out. :)

This is with `(setq consult--ripgrep-regexp-type 'extended)` and `(setq completion-styles '(orderless))`. It _can_ happen with other completion styles, but it's easier to demonstrate with `orderless`.

I have a file, `demo.txt` (the name is important), that contains the following:

```txt
a b c d
a b c e
a b c f
```

We can match up to 3 regexes and then use post-filtering. What's funny is that using post-filtering with `d` or `e` (to get `a b c d` or `a b c e`) doesn't filter the results, because the post-filtering matches the `d` or `e` in the filename `demo.txt`. :)

![2021-08-10-13-35-41](https://user-images.githubusercontent.com/68501778/128863588-384d37c5-cbe2-46d7-a82f-bb6fecc4ec5f.png)

Post-filtering with `f` works as expected, though.

![2021-08-10-13-36-03](https://user-images.githubusercontent.com/68501778/128863620-debedc21-66e6-4a39-a1b0-6a9dbc167af0.png)

Again, I don't think this is a big deal; it's just funny!

**Comment by minad** [comment]
This is actually a feature. Post filtering applies to the whole candidate. See #342.

**Comment by mohamed-abdelnour** [comment]
> This is actually a feature. Post filtering applies to the whole candidate. See #342.

Good to know! I should've looked at the issues first.

**Comment by minad** [comment]
I added space escaping. I close this now, since I don't want to change more things for now regarding how consult-grep etc works. If you have other remarks feel free to comment here or create another issue.

**Comment by mohamed-abdelnour** [comment]
That's excellent—thank you.
