### ISSUE TITLE
[help] How to exclude certain directories/files from counsel-git-grep search? 

### ISSUE THREAD

**Issue by avatar-lavventura** [minad/consult#395]
I have advised to open a request here.

-------

Related to a question on [Emacs StackExchange](https://emacs.stackexchange.com/q/68018/18414):
- swiper-issues: https://github.com/abo-abo/swiper/issues/2903

Here I don't want to see matches in `.gitignore` file:
[![How to exclude ceraa][2]][2]

I have tried adding `':(exclude).gitignore'` to the following line but it gives `error code 128` message.

```el
(setq counsel-git-grep-cmd-default "git --no-pager grep -F -n --no-color -I -e \"%s\"")
```

Would it be possible to exclude certain directories/files from [`counsel-git-grep`][1] search, such as `.gitignore`?

Related: https://stackoverflow.com/a/30084612/2402577

---

I have been advised to ask my question here.

@dalanicolai:
> What you have tried looks correct to me, since it works correctly on the command line. Also, you can see that counsel 'formats it correctly' by printing the `funcall in counsel-git-grep-function`. So I suggest that you open an issue for it (you might add a link to your post here). Also, maybe remind them that the `':(exclude).gitignore'` should be placed after the search pattern. 
>
> I would suggest that you open a request at consult also.  But really, consult looks very promising, and I think he will fix it for you quickly. 

  [1]: https://github.com/abo-abo/swiper
  [2]: https://i.stack.imgur.com/aOEhh.png

**Comment by minad** [comment]
`consult-git-grep` already ignores files you put in .gitignore. In order to exclude additional files you can write on the consult prompt

~~~
#foo -- :!*.org
#foo -- :!.gitignore
~~~

This will search for `foo` and ignore `*.org` files or the file `.gitignore`.

**Comment by avatar-lavventura** [comment]
For hard code into `.emacs` file, if you could give an simple example for to adjust variable `consult-git-grep-args`, like for file `.gitignore` that will be helpful.

**Comment by oantolin** [comment]
Is @avatar-lavventura talking about _Counsel_? This is the Consult repo.

**Comment by avatar-lavventura** [comment]
@oantolin Yes sir its related to `Counsel`, I am sorry for any rahatsizlik. I was just advices to reach @minad on the comment section of my main question at [emacs-stackoverfow.](https://emacs.stackexchange.com/q/68018/18414)


> As @minad developed the package himself (AFAIK), it would probably be easy for him to implement this.

**Comment by dalanicolai** [comment]
@oantolin Although this question was about `counsel`, it [turned out to be not so straightforward](https://github.com/abo-abo/swiper/issues/2903) to implement a solution there. But as I am myself experimenting/trying out consult, and because I expected a solution would be easy to implement here (I first looked for this feature in the consult docs/code, but could not find it), I advised to look at consult (and create a request) for an 'alternative' solution. And it turns out the package is promoting itself (I mean... it already works :)

**Comment by avatar-lavventura** [comment]
@dalanicolai I have switch to using `consult` :-)

**Comment by avatar-lavventura** [comment]
> -- :!*.org

I have tried:

```
(setq consult-git-grep-args "git --no-pager grep -F -n --no-color -I -e \"%s\" -- \"./*\" \":(exclude).gitignore\"")
```
I am not sure why but, but seems like I was not able to make it properly work.

**Comment by minad** [comment]
@avatar-lavventura The `consult-git-grep-args` string you used is invalid. Why is there a `%s`? The search expression is appended to this string. You can check the `*consult-async-log*` to debug, there you see which command is executed. And then you can test this command on the command line and check if it works there. The async log is documented in the README.

**Comment by avatar-lavventura** [comment]
I just tried to convert the `counsel` solution into `consult`. I think I found a solution here https://github.com/abo-abo/swiper/issues/1176#issuecomment-325907067 // and try to make it work for `consult`.  But I get lost along the way.

> Setting counsel-git-grep-cmd-default to "git --no-pager grep --full-name -n --no-color -i -e \"%s\"" solved my problem. 

I believe I kept `\"%s\""` regarding it may copy the word where the cursor is on. Let me try without `\"%s\"` hopefully it solves my wrong approach.

Please note that, I completley switch into using `consult`. It is a golden tool.

**Comment by minad** [comment]
I looked into this and it is indeed not easily possible to add such exclude specifications, since `git-grep` expects the path specifications after `--` and `consult--git-grep-builder` appends the search pattern after `consult-git-grep-args`. In order to make this work you have to write your own `consult-git-grep-builder` or overwrite it with an advice.

**Comment by avatar-lavventura** [comment]
During `consult-git-grep` search, matches in `.gitignore` always shows up at the top. 

If I can list results for the hidden folder/files at last order that could also work in my end, I believe it will be simplier solution.

**Comment by minad** [comment]
> If I can list results for the hidden folder/files at last order that could also work in my end, I believe it will be simplier solution.

No idea, if this is easily possible.

If you dig a bit into the code it is also not complicated to replace the `consult-git-grep-builder` with your own command line builder, which creates a command line string in your desired format, `git grep args... -e input... -- file/exclude-pathspec...`.

**Comment by avatar-lavventura** [comment]
OK as I understand I will have to play around with the following function: https://github.com/minad/consult/blob/a07ca383318cdce6935a370f1d17687ba9f225c3/consult.el#L4175

**Comment by santiagopim** [comment]
This works for me, maybe a pitfall, use at your risk:

```lisp
(defun consult--git-grep-make-builder (paths)
  "Create grep command line builder given PATHS."
  (let ((cmd (consult--build-args consult-git-grep-args)))
    (lambda (input)
      (pcase-let* ((`(,arg . ,opts) (consult--command-split input))
                   (flags (append cmd opts))
                   (ignore-case (or (member "-i" flags) (member "--ignore-case" flags))))
        (if (or (member "-F" flags) (member "--fixed-strings" flags))
            (cons (append cmd (list "-e" arg) opts paths)
                  (apply-partially #'consult--highlight-regexps
                                   (list (regexp-quote arg)) ignore-case))
          (pcase-let ((`(,re . ,hl) (funcall consult--regexp-compiler arg 'extended ignore-case)))
            (when re
              (cons (append cmd
                            (cdr (mapcan (lambda (x) (list "--and" "-e" x)) re))
                            (list ":!*.po" ":!*.pot")    ; <<< Added to exclude translation files
                            opts paths)
                    hl))))))))
```

**Comment by nicolasdespres** [comment]
Hello,

Why does consult-git-grep append a "." argument at the end of the command line, when I type `#defalias -- :lisp` ? I am trying to filter directory where git-grep is searching.

```
consult--async-process started: args=("git" "--no-pager" "grep" "--null" "--color=never" "--extended-regexp" "--line-number" "-I" "-e" "defalias" ":lisp" ".")
```

I have package version 20241117.2113
