### ISSUE TITLE
Integration with orderless

### ISSUE THREAD

**Issue by liuyinz** [minad/consult#396]
Config
```elisp
;; orderless
(setq orderless-matching-styles '(orderless-literal orderless-regexp orderless-strict-initialism))
(setq completion-styles '(orderless)))
;; consult
(setq consult-async-min-input 1)
(setq consult-async-split-style 'perl)
```
Problem:
The perl-style grep and filter don't succeed.
when I use `#defun# `, it seems to match literally, including `#defun#`, rather than `defun`.

**Comment by minad** [comment]
I cannot understand this bug report. `consult-grep` with the perl splitting style and orderless works fine. Please try to reproduce your problem with emacs -Q. See also https://github.com/minad/consult/#bug-reports.

**Comment by liuyinz** [comment]
@minad I see the problem...
```elisp
;; orderless
(setq orderless-matching-styles '(orderless-literal orderless-regexp orderless-strict-initialism))

(defun use-orderless-in-minibuffer ()
   (setq-local completion-styles '(orderless)))
 (add-hook 'minibuffer-setup-hook #'use-orderless-in-minibuffer)

;; consult
(setq consult-async-min-input 1)
(setq consult-async-split-style 'perl)
```

after I set global value of `completion-styles` , I find it doesn't match from beginning in company-mode, see https://github.com/purcell/emacs.d/issues/778 , so I `setq-local` in `minibuffer-setup-hook`.  When I debug, I forgot that.

After I remove the hook, it's OK.

It seems local-value is not compatiable with async grep command. So, could you give some advice on company-mode matching from beginning (like '^') when I use with orderless ?
