### ISSUE TITLE
[help] Would it be possible to search while typing?

### ISSUE THREAD

**Issue by avatar-lavventura** [minad/consult#397]
In order to do search, I have to `enter`.

```
#Driver [enter]  
```

=> Instead is it possible to do search while typing? Similiar feature exist in `counsel-git-grep`, where it applies search, while typing.

**Comment by minad** [comment]
Yes this is possible. Install Vertico+Consult. See the Vertico README for a basic getting started guide. Note that this is an issue tracker and not a help forum. Please read the manuals first.

**Comment by avatar-lavventura** [comment]
@minad I am sorry I won't bother you any more.
