### ISSUE TITLE
[help] Matching keys are unable to read due to matching background and foreground colors

### ISSUE THREAD

**Issue by avatar-lavventura** [minad/consult#398]
I am using `icicle`(icy-mode) along with dracula theme:

```
(load-theme 'dracula t)

(add-to-list 'load-path "~/.emacs.d/lisp/icicles")
(require 'icicles)
(icy-mode 1)
(add-hook 'icicles-mode-hook (lambda ()
                                (local-set-key (kbd "C-p") 'nil)))
```

During my searchs I am not able to see the find words, where background anda foreground color is same:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/18537398/129323764-78f9778a-64c6-48fd-89be-f5fb788b4f62.png">

[Q] How could I change customize-face for consult? Is there any recommended dark-theme for it?

---------

Instead of `(icy-mode 1)` i have tried `(ivy-mode 1)`, but not is says `0    Grep (match required): #Driver` and does not return anything :-( 

What would be recommended setup for its used `incremental completion and selection narrowing framework`. Live i have tried: `ivy-mode`, `helm-mode` but they did not work along with `consult` :-(

**Comment by minad** [comment]
Please take a look at the readme. My recommended completion UI is vertico and my recommended themes are the modus themes.
