### ISSUE TITLE
Is it possible to grep for the word under the cursor with just one key binding?

### ISSUE THREAD

**Issue by honk4hope** [minad/consult#399]
Assume my cursor in on the word `hello`. When I apply `consult-git-grep`, by default is it possible to pass `hello` word into `consult`?  Ex:```Git-grep: #hello```. If possible afterwards, I can continue to do any edit.

Related issue in `swiper`: https://github.com/abo-abo/swiper/issues/1068#issuecomment-318124861

**Comment by minad** [comment]
Yes, the word at point is available via the future history. The future history is mentioned in the Readme. See also the wiki for the command consult-line-symbol-at-point. You can write a similar command for consult-grep. Does this answer your question?

**Comment by honk4hope** [comment]
@minad Thank you sir sir. After doing `consult-git-grep` when I do `M-n` I am able to see the word where cursor is on top of. This feature is golden.

Can `M-n` applied by default? , like can `consult-git-grep` start with `M-n` is already returned its result?

**Comment by manuel-uberti** [comment]
As @minad pointed out, the Wiki might help you with that: https://github.com/minad/consult/wiki#start-consult-line-search-with-symbol-at-point

**Comment by honk4hope** [comment]
@manuel-uberti I have tried following, but did not help:

```
(defun consult-git-grep-symbol-at-point ()
  (interactive)
  (consult-git-grep (thing-at-point 'symbol)))
```

**Comment by honk4hope** [comment]
@manuel-uberti Please see https://emacs.stackexchange.com/questions/68236/how-to-exclude-certain-directories-files-from-consult-git-grep-search

**Comment by BrodyJackson** [comment]
Hi @honk4hope 

I got this working today by using the following

```
(defun get-project-root ()
  (when (fboundp 'projectile-project-root)
    (projectile-project-root)))

;; Ripgrep the current word from project root
(defun consult-ripgrep-at-point ()
  (interactive)
  (consult-ripgrep (get-project-root)(thing-at-point 'symbol)))

```

**Comment by ratnesh1729** [comment]
Hello Consult users, and authors, 
Thank you for this wonderful library!. 

I am trying to achieve similar but wherein I can choose directory. 

I made up this code:

```
(defun consult-ripgrep-at-point ()
 "Ripgrep the current word from a specified directory."
 (interactive)
 (let* ((default-directory (or (get-project-root) default-directory))
     (directory (read-directory-name "Search in directory: " default-directory))
     (thing (thing-at-point 'symbol)))
  (consult-ripgrep directory thing)))
```

However, code behaves interstingly, If I have to quit I have to add a `space` and then C-g.
I do not want to add space and I do not know why it needs space?

**Comment by ratnesh1729** [comment]
Maybe this is just a false alaram. Restarting emacs is not having above issue :-)
