### ISSUE TITLE
consult-line category

### ISSUE THREAD

**Issue by s-kostyaev** [minad/consult#40]
Can we add some `category` to `consult-line`? I would like to be able to change completion style for `consult-line` without changing the default one.

**Comment by minad** [comment]
This must be resolved at some point, see also the discussions in #29 and https://github.com/minad/marginalia/issues/7.

**Comment by minad** [comment]
See https://github.com/minad/consult/commit/b00527ed75427fc1b1fb1f51f79b517d05be587c

**Comment by s-kostyaev** [comment]
Perfect, thank you.
