### ISSUE TITLE
Command-local keybinding documentation might be out of date

### ISSUE THREAD

**Issue by kings2u** [minad/consult#401]
I am trying to create a command specific to the context of a `consult-line` search as documented at https://github.com/minad/consult/wiki#add-command-local-keybinding. However, the code there doesn’t seem to work. For reference, here it is:

```
(defvar my-consult-line-map
  (let ((map (make-sparse-keymap)))
    (define-key map "\C-s" #'previous-history-element)
    map))

(consult-customize consult-line :keymap my-consult-line-map)
```

Instead, the global `C-s` keybinding remains in effect even though I’m inside a `consult-line` search. I’m using lexical binding in my config so I don’t believe that is the issue. Thanks for any help!

**Comment by minad** [comment]
I cannot reproduce this on emacs 27 with Vertico/Selectrum. Please try to reproduce the issue with emacs -Q, see https://github.com/minad/consult/#bug-reports.

**Comment by kings2u** [comment]
Apologies, I should have tested with emacs -Q as you said before posting. I discovered the cause of my problem: I was calling `consult-line` from within my own small wrapper function, which prevented `my-consult-line-map` from taking effect. The solution: either (1) include `(setq this-command 'consult-line)` in my wrapper function, or (2) rewrite my wrapper function as `advice-add` to `consult-line`. Thanks again!

**Comment by minad** [comment]
~~~ elisp
(consult-customize my-consult-line-wrapper :keymap my-consult-line-map)
~~~
