### ISSUE TITLE
Consult-ripgrep/consult-grep results are sorted in reverse line order

### ISSUE THREAD

**Issue by deejayem** [minad/consult#403]
The results shown by consult-ripgrep and consult-grep are in reverse line order - i.e. if a file has matches on lines 3, 7, 9 and 21, those appear under the filename in the opposite order: 21, 9, 7 then 3. I would expect them to appear in the order that they appear in the file (3, 7, 9, 21).

To me this seems like a minor/cosmetic bug, but I'll understand if you think it's a non-issue.

**Comment by minad** [comment]
Thanks for the report.

**Comment by deejayem** [comment]
Thank you for fixing it so quickly.
