### ISSUE TITLE
consult-ripgrep and consult-find does not work in fido-vertical-mode

### ISSUE THREAD

**Issue by Jackson-soft** [minad/consult#405]
![image](https://user-images.githubusercontent.com/3928114/129829847-f63520d4-5067-4b86-b481-dd8dcb4a71c6.png)

[fido-vertical-mode](https://github.com/emacs-mirror/emacs/blob/6d3455eb144e30f4cc4f56eb3454f4ad785e411d/lisp/icomplete.el#L663)

![image](https://user-images.githubusercontent.com/3928114/129830875-d9c148d7-7f2c-4d73-ba6d-dfbc99a65945.png)

**Comment by minad** [comment]
Yes, this is a known issue since fido mode overwrites the completion styles. Therefore we cannot support it in Consult. You can use icomplete-vertical-mode as an alternative and set the completion styles yourself.
