### ISSUE TITLE
[Question] How to keep consult session after selected the item?

### ISSUE THREAD

**Issue by yamatakau08** [minad/consult#406]
I wrote the following my own sample code using consult--read.

```
(defun my-consult-sample ()
  "sample function using consult"
  (interactive)
  (let* ((cands '(("google" . "http://google.com/")
  		  ("yahoo"  . "http://yahoo.com/")))
  	 selected
  	 url)
    (setq selected (consult--read cands))
    (setq url (cdr (assoc selected cands)))
    (browse-url-default-browser url)))
```

Even if I selected “google” or “yahoo”, I’d like to keep session choices of consult. 
Is there any parameter of consult—read to archive that?

**Comment by minad** [comment]
> Even if I selected “google” or “yahoo”, I’d like to keep session choices of consult.
Is there any parameter of consult—read to archive that?

No, there is not. Define your own global variable which keeps the selected value across the session.
