### ISSUE TITLE
`consult-git-grep` Does not apply its search from the root directory of the git repo

### ISSUE THREAD

**Issue by honk4hope** [minad/consult#408]
I observe that `consult-git-grep` Does not apply its search from the root directory of the git repo.

```
$ tree hello
hello
├── file.txt
└── world
    └── test.txt
$cat hello/file.txt
hello
````

If I am inside the `world/tesxt.txt` file and apply `consult-git-grep` to search `#hello`, it does not find the `hello` line that is located inside the `hello/file.txt` (located in parent folder). Would it be possible to make `consult-git-grep` to search in the git repo?

**Comment by honk4hope** [comment]
Adding following solved the issue:

```
 (setq consult-project-root-function
        (lambda ()
          (when-let (project (project-current))
            (car (project-roots project)))))
```

**Comment by andcarnivorous** [comment]
> consult-project-root-function
>         (lambda ()
>           (when-let (project (project-current))
>             (car (project-roots project))))

Thanks, this worked for me as well, perhaps since `project.el` is built-in it should probably be the default function for this...
