### ISSUE TITLE
[feature-request] match annotations

### ISSUE THREAD

**Issue by natask** [minad/consult#409]
It would be useful if search results also matched annotations provided by `marginalia`. Then more context can be provided for a candidate to match to.  For example, searching for a variable in `helpful-variable` can match the description of the variable. or match the keybinding of a command in `execute-extended-command`.

**Comment by minad** [comment]
Filtering by annotations is not directly possible. See https://github.com/oantolin/orderless/issues/30#issuecomment-898196817 where I outline a possible solution. One could implement a general query language which can be used to filter arbitrary candidates, similar to org-ql.

**Comment by minad** [comment]
We will add annotation matching to Orderless in https://github.com/oantolin/orderless/pull/162. The `@pattern` will match pattern in the annotation.
