### ISSUE TITLE
Idea: let-bind a variable during `consult--temporary-files`

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#412]
Consult preview is a killer feature, but many things are inappropriate to run during a consult preview of files.  `consult-preview-excluded-hooks` is a good option to prevent `find-file` hooks from running, but many packages get activated in other ways.  For example, the LSP aware mode `eglot` suggests, e.g.  `(add-hook 'python-mode-hook #'eglot-ensure)`.  Since (for small enough files) consult preview activates the major mode, this causes `eglot` to spool up and connect to an external LSP server for `.py` file previewed.  I can fix this by:

```elisp
  (add-hook 'python-mode-hook
	    (lambda ()
	      (if enable-dir-local-variables
		  (eglot-ensure)))))
```

but that's a bit brittle and excludes other uses of `enable-dir-local-variables`.  

Perhaps let-binding a variable like `consult-temporary-file-preview` in `consult--temporary-files` would be helpful, to provide users a fine-grained way to disable features you don't want activated by preview.  So then I'd write:

```elisp
  (add-hook 'python-mode-hook
	    (lambda ()
	      (unless consult-temporary-file-preview
		  (eglot-ensure)))))
```

**Comment by minad** [comment]
Currently you can write something like this:

~~~ elisp
(defun consult--preview-p ()
  (when-let (win (active-minibuffer-window))
    (not (eq nil (buffer-local-value
                  'consult--preview-function
                  (window-buffer win))))))
~~~

**Comment by minad** [comment]
Closing since I don't want to introduce global state and as mentioned the consult--preview-function is already available in the active mb.

**Comment by minad** [comment]
For reference, preview got more efficient in https://github.com/minad/consult/commit/3b0d745a480220d3eb8367fe73e8bf1321034a4e. See https://github.com/minad/consult/issues/538#issuecomment-1087964040 for details.
