### ISSUE TITLE
Feature Request: Add a face to the list position indicator

### ISSUE THREAD

**Issue by t-e-r-m** [minad/consult#413]
http://0x0.st/-wbL.png

If the "6/21" had a customizable face, it would be much more visible.

**Comment by minad** [comment]
Thanks for the suggestion! The indicator is provided by Vertico or Selectrum. In Vertico you can adjust the `vertico-count-format` strings and attach an appropriate face. By default the count is formatted using the prompt face. It is intentionally non-obtrusive - I don't want the position indicator to stand out. Therefore I don't want to introduce an extra face.

**Comment by t-e-r-m** [comment]
Sorry, I didn't realize it was provided by Vertico.

Thanks for the quick reply!
