### ISSUE TITLE
Silent consult--bookmark-preview?

### ISSUE THREAD

**Issue by protesilaos** [minad/consult#414]
Hello Daniel!

I am experimenting with some additional handlers for bookmarks.  Example:

```elisp
(add-to-list 'consult-bookmark-narrow `((?v "VC Dir" ,#'vc-dir-bookmark-jump)))
```

I noticed that when I call `consult-bookmark` it produces a message (per `consult--bookmark-preview`):

```
No preview for vc-dir-bookmark-jump
```

I understand why it is there, but maybe we can silence it regardless?

Thanks once again for Consult!

**Comment by minad** [comment]
Yes, it makes sense to introduce a consult-preview-quiet flag.

**Comment by protesilaos** [comment]
Hello Daniel!

> I looked into this and I am not so convinced anymore that hiding some
> messages is a good idea. It is not clear where to draw the line. I
> think some preview error messages should be kept and I don't want to
> introduce a complicated logging system with different message
> priorities.

I understand: that's okay.  Besides, this is not a major issue that
would merit the added code complexity.

> In my personal configuration I have an advice which filters out
> certain messages globally via regular expressions to make Emacs a bit
> more quiet here and there. I use this filter for all kinds of messages
> coming from packages or Emacs. What do you think about using such a
> mechanism for your use case too?

Sounds good, please share!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
>> In my personal configuration I have an advice which filters out
>> certain messages globally via regular expressions to make Emacs a bit
>> more quiet here and there. I use this filter for all kinds of messages
>> coming from packages or Emacs. What do you think about using such a
>> mechanism for your use case too?
> 
> Sounds good, please share!
It would be great if Emacs would have such a built-in mechanism to
silence some of the verbose messages (log levels or just some
regexp-based filter). I have the following code in my config. It works
well but one has to be careful. If the message code is broken thanks to
an advice, Emacs will be barely usable.

(defconst +suppressed-messages
  '("\\`Mark \\(set\\|activated\\|deactivated\\|saved\\)"
    "\\`Back to top level\\'"
    ;; "No other windows to delete" "No other window to select"
    ;; Some commands use message instead of the command-error-function!
    "\\`\\(Beginning\\|End\\) of buffer\\'"
    ;; TODO this messages can be supressed with
server-client-instructions=nil on 28
    "\\`When done with this frame, type"))

(defconst +suppressed-errors
  '(beginning-of-buffer end-of-buffer))

(defun +message-adv (fun fmt &rest args)
  (catch '+suppressed
    (when (and fmt (not (string= fmt "")))
      (let ((msg (if args (apply #'format fmt args) fmt)))
        (dolist (suppressed +suppressed-messages)
          (when (string-match-p suppressed msg)
            (throw '+suppressed msg)))))
    (apply fun fmt args)))

(defun +command-error-default-function-adv (fun data &rest args)
  (unless (memq (car data) +suppressed-errors)
    (apply fun data args)))

(advice-add #'message :around #'+message-adv)
(advice-add #'command-error-default-function :around
#'+command-error-default-function-adv)

**Comment by protesilaos** [comment]
>>> In my personal configuration I have an advice which filters out
>>> certain messages globally via regular expressions to make Emacs a bit
>>> more quiet here and there. I use this filter for all kinds of messages
>>> coming from packages or Emacs. What do you think about using such a
>>> mechanism for your use case too?
>> 
>> Sounds good, please share!
> It would be great if Emacs would have such a built-in mechanism to
> silence some of the verbose messages (log levels or just some
> regexp-based filter).

There exists such functionality on Emacs28+ for warnings/errors, though
I never looked into it.  Maybe it would suit your needs.  The idea is
that in the warnings' buffer (or buffers like the Flymake log) each
entry has two buttons: one to disable showing the message, another to
disable logging it altogether.

A very quick grep yields this from warnings.el:

    (define-button-type 'warning-suppress-warning
      'action #'warning-suppress-action
      'help-echo "mouse-2, RET: Don't display this warning automatically")
    (defun warning-suppress-action (button)
      (customize-save-variable 'warning-suppress-types
                               (cons (list (button-get button 'warning-type))
                                     warning-suppress-types)))
    (define-button-type 'warning-suppress-log-warning
      'action #'warning-suppress-log-action
      'help-echo "mouse-2, RET: Don't log this warning")
    (defun warning-suppress-log-action (button)
      (customize-save-variable 'warning-suppress-log-types
                               (cons (list (button-get button 'warning-type))
                                     warning-suppress-types)))

Though I still need to investigate it.

> I have the following code in my config. It works well but one has to
> be careful. If the message code is broken thanks to an advice, Emacs
> will be barely usable.

Thank you!  I will experiment with it.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
@protesilaos Did you find a satisfactory solution in your configuration to disable undesired messages? I think my arguments in https://github.com/minad/consult/issues/414#issuecomment-935878529 still hold to keep the consult messages as is.

**Comment by protesilaos** [comment]
On 2021-12-21, 04:53 -0800, Daniel Mendler ***@***.***> wrote:

> @protesilaos Did you find a satisfactory solution in your
> configuration to disable undesired messages? I think my arguments in
> https://github.com/minad/consult/issues/414#issuecomment-935878529
> still hold to keep the consult messages as is.

No, I did not do anything as this was a minor issue and I could not test
your code (still on my to-do list).

I am fine that you closed this.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
Thanks! If you come up with something please let me know.

**Comment by protesilaos** [comment]
> Thanks! If you come up with something please let me know.

Yes, sure!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
@protesilaos I changed my opinion on this one - I removed the preview messages in common situations, e.g., like the bookmark preview. The messages occur way too often for users of non-file bookmark types.

**Comment by protesilaos** [comment]
I see.  Thank you @minad!
