### ISSUE TITLE
Category Specific Minibuffer Keybindings Problem

### ISSUE THREAD

**Issue by deejayem** [minad/consult#415]
The example code here https://github.com/minad/consult/wiki#add-category-specific-minibuffer-keybindings works great in some scenarios, but in other cases it causes issues. The difference seems to be whether or not there are any minibuffer specific bindings for the key.

For example, if I defun define-minibuffer-key as in the wiki page, and then run `(define-minibuffer-key (kbd "RET") 'file #'vertico-directory-enter)`, hitting return will work fine for files (i.e. it's bound to `vertico-directory-enter`), but for everthing else in the minibuffer it's bound to `newline`, rather than `vertico-exit`, as it was before.

Is there a way round this? I couldn't find a complete list of categories, but one way would be to list all of the others apart from file (and project-file). Some kind of catch-all, or tweak to the logic of define-minibuffer-key would be nicer though.

**Comment by minad** [comment]
It should suffice to unbind the existing keybinding first, or to rebind it to `#'ignore`. Then bind the `menu-item`s. Alternatively you can change the `menu-item`s such that they return the desired catch-all command if `(plist-get ...)` returns nil, e.g., `(or (plist-get ...) #'my-catch-all-command)`. I hope this helps.

**Comment by deejayem** [comment]
I'm not sure how unbinding would help. `RET` is bound to `newline` in `global-map` and, after loading vertico it is bound to `vertico-exit` in `vertico-map`. So far so good, but after calling `define-minibuffer-key`, it no longer sends `vertico-exit` in the minibuffer when not completing files, but sends `newline` instead. All three bindings are needed.

Passing in a default/fallback command to the function (or using `lookup-key`) should work though, thank you.
