### ISSUE TITLE
cons: Wrong type argument: listp, t

### ISSUE THREAD

**Issue by alexei-28** [minad/consult#416]
Linux Mint 20.2
Emacs 27.1
Install package **consult ver. 0.11**

`M-x consult-yank-from-kill-ring`

![Screenshot from 2021-09-07 22-16-28](https://user-images.githubusercontent.com/303539/132399314-06f1455c-36a2-4d27-b797-e500a9ced46f.png)

But I get error:

`cons: Wrong type argument: listp, t`

![Screenshot from 2021-09-07 22-16-43](https://user-images.githubusercontent.com/303539/132399365-adcdcb6f-3bc5-4567-9eb2-2d9fb5e47328.png)

**Comment by minad** [comment]
It seems you are using Ivy as your mode-line indicates. Ivy is unsupported. See also https://github.com/minad/consult#bug-reports.
