### ISSUE TITLE
Better isearch integration

### ISSUE THREAD

**Issue by minad** [minad/consult#42]
@s-kostyaev You contributed https://github.com/minad/consult/pull/20. Now I wonder if the isearch integration could not be improved even more. Would it make sense for `consult-line` to overwrite the isearch string always? Or maybe it would make more sense to rename `consult-line-from-isearch` to `consult-isearch`, which is just `consult-line` with taking the isearch string as initial input and overwriting the isearch string on the go such that one can switch seemlessly between `consult-isearch` and `isearch`. Does that make sense?

**Comment by s-kostyaev** [comment]
I think `consult-line` should not overwrite `isearch-string` at all. It should have their own history. This command `consult-line-from-isearch` is great for add it to `isearch-mode-map` like this:
```elisp
(leaf isearch
  :bind ((isearch-mode-map
	  ("M-i" . consult-line-from-isearch))))
```
or to use it with [`ace-isearch`](https://github.com/tam17aki/ace-isearch). But switching back and forward sounds neat. Name convention also from `ace-isearch`.

**Comment by minad** [comment]
@s-kostyaev I think overwriting would be okay since it would only happen for `consult-isearch`, thus being triggered explicitly by the user. I tried this. But so far the experiment did not go well. If you would like to play around with this a bit it could be cool, but we don't have to do this. It was just an idea. Thanks for the isearch-mode-map example. I agree, that makes sense. Maybe this should be added to the readme.

**Comment by s-kostyaev** [comment]
I think if we will provide `consult-isearch` it should be aware of other isearch options like `search-whitespace-regexp`, `isearch-lax-whitespace`, `isearch-regexp-lax-whitespace`, etc. Also, it should use the same completion style as `isearch`. That's why I've created #40 to be able to overwrite default completion style for `consult-line` only.

**Comment by minad** [comment]
@s-kostyaev Here is what I tried for now. As I said, does not work yet unfortunately.

~~~ elisp
;;;###autoload
(defun consult-isearch ()
  "Search by lines, using and updating the `isearch-search-string'."
  (interactive)
  (minibuffer-with-setup-hook
      (lambda ()
        (add-hook 'post-command-hook
                  (lambda ()
                    (setq
                     isearch-regexp nil
                     isearch-string (minibuffer-contents-no-properties)))))
    (consult-line isearch-string)))
~~~

**Comment by s-kostyaev** [comment]
Also, can `consult-line` search for regexp as `isearch` can?

**Comment by minad** [comment]
> Also, can consult-line search for regexp as isearch can?

Depends on the completion style. If the completion style recognizes regexps, I think yes. But this is all a bit fuzzy. I am not deep into this. I am using orderless.

**Comment by s-kostyaev** [comment]
> I am using orderless.

Same as me. But looks like `orderless` has its own completion styles. And, AFAIK, that styles are global.

**Comment by s-kostyaev** [comment]
> @s-kostyaev Here is what I tried for now. As I said, does not work yet unfortunately.
> 
> ```emacs-lisp
> ;;;###autoload
> (defun consult-isearch ()
>   "Search by lines, using and updating the `isearch-string'."
>   (interactive)
>   (minibuffer-with-setup-hook
>       (lambda ()
>         (add-hook 'post-command-hook
>                   (lambda ()
>                     (setq
>                      isearch-regexp nil
>                      isearch-string (minibuffer-contents-no-properties))
>          nil t)))
>     (consult-line isearch-string)))
> ```

This is a bad idea to use hook with lambda. You will add this lambda to that hook every time you call this command. Use named function instead.

**Comment by minad** [comment]
It is okay to do it like this here, but this is a matter of taste. And no, it is not added every time. The hook is added locally.

**Comment by minad** [comment]
> Same as me. But looks like orderless has its own completion styles. And, AFAIK, that styles are global.

Probably you can overwrite them locally, like the hooks. But I would have to look into this.

**Comment by oantolin** [comment]
Yep, using `setq-local` on `orderless-matching-styles` should work.

**Comment by s-kostyaev** [comment]
> Yep, using `setq-local` on `orderless-matching-styles` should work.

Should I set it inside some hook?

**Comment by oantolin** [comment]
Well, you should set it when the minibuffer is the current buffer. So if you are already using `minibuffer-with-setup-hook`, do it in the function you pass to it.

**Comment by oantolin** [comment]
But, I for one don't like people messing with my matching styles, maybe others feel the same way.

I think a better solution is education: just explain clearly in the docstrings that consult-line uses whatever kind of completion you have and is not the same thing as isearch, regexp isearch or lax whitespace isearch.

**Comment by s-kostyaev** [comment]
I prefer different completion styles for in file search and commands for example. I like Emacs because I can make it my own tool with my own rules. So why should I learn the tool instead of configure it for exact my purpose? Kind of philosophical question.

**Comment by s-kostyaev** [comment]
> Yep, using `setq-local` on `orderless-matching-styles` should work.

There is better solution - `orderless-transient-matching-styles`

**Comment by minad** [comment]
@oantolin 

> But, I for one don't like people messing with my matching styles, maybe others feel the same way.
> I think a better solution is education: just explain clearly in the docstrings that consult-line uses whatever kind of completion you have and is not the same thing as isearch, regexp isearch or lax whitespace isearch.

I agree with this sentiment, but such behavior could be made configurable and it could be restricted to only few commands for which this is an explicitly stated feature. But I am not sure if something like `consult-isearch` can be made or makes much sense. As I said it was just an idea based on the simpler command we already have `consult-line-from-isearch`.

**Comment by s-kostyaev** [comment]
I think I can now achieve the behavior I need. Maybe `consult-line-frome-isearch` is enough.

**Comment by oantolin** [comment]
> There is the better solution - `orderless-transient-matching-styles`

Oh, that's right! I completely forgot. Thank goodness there is at least one expert on embark in this conversation. 😛

**Comment by s-kostyaev** [comment]
This one works for me:
```elisp
  (defun my-consult-line-from-isearch ()
    (interactive)
    (minibuffer-with-setup-hook
	(lambda ()
	  (setq orderless-transient-matching-styles '(orderless-prefixes)))
      (consult-line-from-isearch)))
```

**Comment by oantolin** [comment]
Out of curiosity, @s-kostyaev: what styles do you normally use?

**Comment by s-kostyaev** [comment]
> Out of curiosity, @s-kostyaev: what styles do you normally use?

```elisp
(orderless-matching-styles '(orderless-regexp orderless-initialism orderless-flex))
```

**Comment by oantolin** [comment]
I, see, that makes sense.

**Comment by minad** [comment]
@oantolin @s-kostyaev As far as I see, we don't have to do anything here? If you disagree, please reopen or ping me!

**Comment by WorldsEndless** [comment]
I'm new to Consult, but I don't see the solution -- how to I connect consult to my isearch results when I press `M-i` if I'm not using orderless?

**Comment by minad** [comment]
@WorldsEndless What do you want to achieve exactly? You can access the last isearch input in the future history of `consult-line`. This is pretty much it, very limited. But there is also the proposal to make the isearch history accessible, see #171. But in that case it would not connect to `consult-line`, but would only allow to restart an old isearch session.

**Comment by minad** [comment]
@WorldsEndless For reference, regarding ace-isearch I answered here - https://www.reddit.com/r/emacs/comments/l2sata/finding_replacements_for_switching_to_selectrum/gk80veh?utm_source=share&utm_medium=web2x&context=3
