### ISSUE TITLE
consult-grep fails with wrong-type-argument

### ISSUE THREAD

**Issue by 0x28** [minad/consult#420]
Hi,

the commands `consult-grep` (and `consult-ripgrep`, `consult-git-grep`) fail with the following output when the input is ` --`:

![image](https://user-images.githubusercontent.com/12886563/132984666-ce20dac1-6ed0-4124-9ce9-537780afa2e2.png)

When I eval the expression `(consult--grep-builder " --")` directly I get the following stack trace:
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("\\\\\\\\\\|\\\\ " #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_48> nil fixedcase literal)
  consult--split-escaped(nil)
  consult--default-regexp-compiler(nil pcre)
  consult--grep-builder(" --")
  (progn (consult--grep-builder " --"))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)
```
I'm using emacs 28 and can reproduce the issue with `emacs -Q`.

**Comment by minad** [comment]
Thanks!
