### ISSUE TITLE
consult-ripgrep doesn’t work when specified files in consult-ripgrep-args on Consult Version 0.10 or above. 

### ISSUE THREAD

**Issue by yamatakau08** [minad/consult#421]
This is related issue https://github.com/minad/consult/issues/407 .

To simplify that issue, 
Firstly. I focus on conslut-ripgrep on Mac.

```
emacs-version
"27.1"
```

```
/tmp> uname -a
Darwin MacBook-Air.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
/tmp> rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

prepare the following files.

```
/tmp> cat log1
foo
bar
baz
/tmp> cat log2
aaa
bbb
baz
```

Open the directory /tmp.
Then marked the files log1 and log2
in /tmp dired buffer, execute the following function

```
  (defun my-consult-dired-ripgrep ()
    "Search for regexp in files marked dired mode, this works on only mac"
    ;; https://github.com/minad/consult/issues/407#issuecomment-905342672
    ;; https://github.com/minad/consult/issues/384#issue-962479625
    (interactive)
    (let ((consult-ripgrep-args ; above Version 0.10 doesn't work at all
	   ;; "rg --line-buffered --color=never --max-columns=1000 --path-separator --smart-case --no-heading --line-number ." ; original
	   ;; replace '.' with "%s" (files) and add "-e ARG OPTS"
	   (format "rg --line-buffered --color=never --max-columns=1000 --path-separator --smart-case --no-heading --line-number %s -e ARG OPTS"
		   (mapconcat #'shell-quote-argument (dired-get-marked-files) " ")))
	  (consult-ripgrep-command ; Version 0.9 works
	   ;; "rg --null --line-buffered --color=ansi --max-columns=1000 --no-heading --line-number . -e ARG OPTS" ; original
	   ;; replace '.' with "%s" (files)
	   (format "rg --null --line-buffered --color=ansi --max-columns=1000 --no-heading --line-number %s -e ARG OPTS"
		   (mapconcat #'shell-quote-argument (dired-get-marked-files) " "))
	   ))
      (consult-ripgrep)))
```

and put the pattern “baz” is common log1 and log2 in consult-ripgrep prompt.
That can’t ripgrep the pattern “baz”

On the other hand, on consult Version 0.9, that can ripgrep the pattern “baz” and works fine.

So I assume the consult-ripgrep of Consult Version 0.10 or above is something wrong.

For example, the consult-ripgrep-args and consult-ripgrep-command are slightly different. 
So I set consult-ripgrep-args `"rg --null --line-buffered --color=ansi --max-columns=1000 --no-heading --line-number %s -e ARG OPTS"` which works on Consult Ver 0.9.
Then evaluate the above function, It doesn’t work.

That’s why Consult Ver 0.10 or above has something wrong on consult-ripgrep.

**Comment by minad** [comment]
The command format changed from 0.9 to 0.10. `consult-ripgrep-args` should contain the strings ARG and OPTS. See the original `consult-ripgrep-args` string for reference.

**Comment by yamatakau08** [comment]
@minad 

> The command format changed from 0.9 to 0.10. 
I understand it.

>consult-ripgrep-args should contain the strings ARG and OPTS. 
Yes, I understand that too.

So I aleady added ARGS and OPTS in consult-ripgrep-args. 
With the data files I posted in this issue, then could you execute the following function?
You can see this doesn't work.
I suspect the cause in  @consult.

```
(defun my-consult-dired-ripgrep ()
  (interactive)
  (let ((consult-ripgrep-args ; Version 0.10 or above doesn't work at all
	 ;; replace '.' with "%s" (files) and add "-e ARG OPTS"
	 (format "rg --line-buffered --color=never --max-columns=1000 --path-separator --smart-case --no-heading --line-number %s -e ARG OPTS"
		 (mapconcat #'shell-quote-argument (dired-get-marked-files) " "))))
    (consult-ripgrep)))
```

**Comment by minad** [comment]
> So I aleady added ARGS and OPTS in consult-ripgrep-args.

It should *NOT* be there.

**Comment by yamatakau08** [comment]
@minad 

Thank you for reply.

> It should NOT be there.

Could you provide the sample code which works with the data files in https://github.com/minad/consult/issues/421#issue-994870343

**Comment by minad** [comment]
You have to write your own `consult--ripgrep-builder` which creates the command line. Take a look at `consult-ripgrep` and `consult--ripgrep-builder`.

**Comment by yamatakau08** [comment]
@minad 
Thank you for supporting!

I found my mistake in my code.
I forgot to put '/' after --path-separator option.

The following function fixed that works fine.

```
(defun my-consult-dired-ripgrep ()
  (interactive)
  (let ((consult-ripgrep-args ; Version 0.10 or above works
	 ;; replace '.' with "%s" (files) and add "-e ARG OPTS"
	 (format "rg --line-buffered --color=never --max-columns=1000 --path-separator / --smart-case --no-heading --line-number %s -e ARG OPTS"
		 (mapconcat #'shell-quote-argument (dired-get-marked-files) " "))))
    (consult-ripgrep)))
```
