### ISSUE TITLE
How to exclude certain directories/files from counsel-git-grep search in hard code configuraiton?

### ISSUE THREAD

**Issue by avatar-lavventura** [minad/consult#422]
I was not able to find solution regarding to this issue. Any help would be appreciated.

I want to exlude certain files such as `.gitignore` in [`consult-git-grep`][1] search.

- `consult-git-grep` works find with following defualt setup:

`(setq consult-git-grep-args "git --no-pager grep -F -n --no-color -I -e '%s')` 

I have updated `consult-git-grep-args` definition where `-- '(exclude).gitignore'` is added at the end, but it crashes. How could I make it work?

**init.el**

```
(require 'consult)
```
Followed by:

`(setq consult-git-grep-args "git --no-pager grep -F -n --no-color -I -e '%s' -- '(exclude).gitignore'")`

---------------

Related: [How to exclude certain directories/files from counsel-git-grep search?][2]

> `consult-git-grep already` ignores files you put in `.gitignore`. In
> order to exclude additional files you can write on the
> `consult-git-grep prompt`:
> 
> `#foo -- :!*.org` `#foo -- :!.gitignore` This will search for foo and
> ignore `*.org` files or the file .gitignore. If you want to hard code
> these settings adjust the variable `consult-git-grep-args`, which is
> similar to `counsel-git-grep-cmd-default`.

  [1]: https://github.com/minad/consult
  [2]: https://github.com/minad/consult/issues/395#issuecomment-897901286

----------

Related:

- https://github.com/minad/consult/issues/395
- https://emacs.stackexchange.com/questions/68236/how-to-exclude-certain-directories-files-from-consult-git-grep-search

**Comment by minad** [comment]
Duplicate #395.

**Comment by avatar-lavventura** [comment]
@minad Your answer on #395 does not work in hard code.
