### ISSUE TITLE
Don't suggest `xref-pulse-momentarily` in `consult-after-jump-hook` docstring

### ISSUE THREAD

**Issue by hmelman** [minad/consult#425]
The docstring of `consult-after-jump-hook` suggests using `xref-pulse-momentarily`.  This was designed to use an xref item and if there isn't one just falls back to pulsing the current line.  Also since it's not autoloaded if you use a consult jump command before some xref function you get an error in the messages buffer.

There isn't a good alternative before it but in Emacs 28, `pulse-momentary-highlight-one-line` can be used.
See [Emacs Bug #50642](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=50642).  

I'm not sure the best way to formulate the docstring, but I think this info is accurate.

**Comment by woolsweater** [comment]
Since the `pulse` command just needs point, it should work to wrap it, I would think.

```elisp
(defun my-consult/highlight-after-jump ()
  (pulse-momentary-highlight-one-line (point)))
(add-hook 'consult-after-jump-hook #'my-consult/highlight-after-jump)
```

Side note, you can add your own autoloads in your startup files, like so: `(autoload #'xref-pulse-momentarily "xref")`
