### ISSUE TITLE
consult-completion-in-region, should change exit-status from 'finished to 'sole?

### ISSUE THREAD

**Issue by TxGVNN** [minad/consult#426]
Come from `selectrum`, I see `selectrum-completion-in-region` doesn't insert a space after the result because the exit-status is 'sole. And the emacs default did not insert space after result. 

Should we change or have an option for user customize?

https://github.com/minad/consult/blob/f154d6bd800d8d12e88cb9abdc3b24c3c30a455f/consult.el#L2319

Thanks.

**Comment by minad** [comment]
As far as I understand `consult-completion-in-region` works correctly as is. According to the documentation of `completion-extra-properties`, the `:exit-function` may return these values:

~~~
     finished - text is now complete
     sole     - text cannot be further completed but
                completion is not finished
     exact    - text is a valid completion but may be further
                completed.
~~~

**Comment by minad** [comment]
@TxGVNN I added a check if the completion is indeed finished. Please give it a try.

**Comment by TxGVNN** [comment]
Thank you very much. It works perfect!
