### ISSUE TITLE
consult-locale not found file in Download folder

### ISSUE THREAD

**Issue by alexei-28** [minad/consult#427]
Linux Mint 20.2
Emacs 27.2
consult            20210919.1618

I has file **webinars.txt** in the Temp folder. 
And to find it I use it in folder Temp. 

`M-x consult-locale  webinars.txt`

And here result:
![1](https://user-images.githubusercontent.com/303539/134219026-bdbe59d9-47b7-46c2-9612-f5d233f20d13.png)

Nice. The file success found.

A also has file **webinars.txt** in folder **Download**. I go to folder Download and use the same command

`M-x consult-locale  webinars.txt`

And here result

![2](https://user-images.githubusercontent.com/303539/134219200-88761e57-5b96-4dcf-9e39-1afa4026d829.png)

As you can see the `consult-locale` found **webinars.txt** ONLY in the **Temp** folder. 
But not found it in the folder **Download**

P.S. I also create folder **Temp2** and copy file **webinars.txt** to it. But  ` consult-locale` again find **webinars.txt** ONLY in the **Temp** folder.

P.P.S. Command `consult-find` success find file **webinars.txt** in the folder **Download**

**Comment by minad** [comment]
The Unix `locate` command requires you to update the database of files regularly with `updatedb`. Please read the manual of `locate` and `updatedb`.
