### ISSUE TITLE
Can't find match by consult-isearch

### ISSUE THREAD

**Issue by alexei-28** [minad/consult#428]
Linux Mint 20
Emacs 27.1
consult

In some buffer I has a text:

```
emacs
Emacs
emacs-27
emacs-26
GNU Emacs
Emacs-28

```

Match those that end with a number.

I use regexp `[0-9]$` for this and use built-in Emacs function

`isearch-forward-regexp`

Result
![1](https://user-images.githubusercontent.com/303539/134401152-95394875-8f6a-413b-9557-f9511dd21b1e.png)

As you can see it success find 3 matches. Nice.

Now I want to do same by consult. I use command:

`consult-isearch`

Result:
![2](https://user-images.githubusercontent.com/303539/134401763-660ba449-4596-41a8-ae37-4be41817ec90.png)
![3](https://user-images.githubusercontent.com/303539/134401786-a6a7bd61-15e3-424a-b1f2-5c705dab1c52.png)

As you can see nothing found.

**Comment by minad** [comment]
`consult-isearch` has a different purpose, the command allows you to select a search string from a previous search. It is supposed to be a replacement for `M-s e`. The docstring of `consult-isearch` documents this.
