### ISSUE TITLE
preview-key setting doesn't apply to consult-ripgrep when called from lisp?

### ISSUE THREAD

**Issue by ave-63** [minad/consult#429]
Hi, I'm using embark and consult together with this function I made:

    (define-key embark-file-map (kbd "g") 'ben/consult-rg-here)
    (defun ben/consult-rg-here (file)
      "consult-ripgrep in this directory."
      (let ((default-directory (if (f-directory-p file)
                                   file
                                 (file-name-directory file))))
        (consult-ripgrep))))

I also have the `preview-key` set as suggested in the readme:

    (consult-customize
     consult-ripgrep consult-git-grep consult-grep
     consult-bookmark consult-recent-file consult-xref
     consult--source-file consult--source-project-file consult--source-bookmark
     :preview-key (kbd "M-."))

The problem is that when I call `ben/consult-rg-here`, which calls `consult-ripgrep` from lisp, the `preview-key` acts like `any`, just previewing everything as I scroll through the matches in the minibuffer. This also happens when I `M-: (consult-ripgrep "/foo/bar" "sometext")`. 

When I call `consult-ripgrep` directly using the keybinding `M-s r`, the `preview-key` acts as it should, with `M-.`.

Is this something that needs to be fixed? Or is there a way I can call `consult-ripgrep` from lisp, but still activate `interactive` to get around the problem?

**Comment by hmelman** [comment]
If it helps there's the function: `call-interactively`

**Comment by ave-63** [comment]
@hmelman Excellent suggestion, but unfortunately it doesn't work. `M-: (call-interactively 'consult-ripgrep)` behaves the same way as `M-: (consult-ripgrep)`. I have no idea why and I'm not very good at debugging lisp. Maybe I can try debugging tonight when I have more time.

**Comment by minad** [comment]
There are two possible resolutions:

1. You should define `ben/consult-ripgrep-here` as interactive command.
Furthermore the customization must use the name of the command, in
this case `ben/consult-ripgrep-here`.

~~~ lisp
(defun ben/consult-ripgrep-here (file)
  (interactive "G")
  ...)
(consult-customize ben/consult-ripgrep-here :preview-key (kbd "M-."))
~~~

We could avoid the interactive specification if Embark would set
`this-command` to the action function even if the function is
non-interactive. Currently Embark does not do this. During the action
`this-command` has the value `embark-act`.

2. Overwrite `this-command` in `ben/consult-ripgrep-here`.

~~~ lisp
(defun ben/consult-ripgrep-here (file)
  (let ((this-command 'consult-ripgrep))
     ...))
(consult-customize consult-ripgrep :preview-key (kbd "M-."))
~~~

**Comment by oantolin** [comment]
> We could avoid the interactive specification if Embark would set `this-command` to the action function even if the function is non-interactive. Currently Embark does not do this. During the action `this-command` has the value `embark-act`.

The current behavior of Embark seems correct to me: command means interactive. On the other hand I don't have any problem with setting `this-command` "incorrectly" to the non-interactive function if (1) it doesn't break anything and (2) it is helpful.

**Comment by ave-63** [comment]
@minad The first option fixed the problem. Looking at the Embark documentation's examples I see that I should have made these commands interactive, and I see no reason why not to, even though I don't think I'll be calling them as commands outside of Embark.

**Comment by minad** [comment]
@oantolin

> The current behavior of Embark seems correct to me: command means
> interactive. On the other hand I don't have any problem with setting
> |this-command| "incorrectly" to the non-interactive function if (1) it
> doesn't break anything and (2) it is helpful.

Yes, it is correct. I don't think we should change it since it wouldn't
really help and only introduce potential side effects. I only mentioned
this since this-command is needed by the consult-customize mechanism and
this-command is only set for interactive commands.
