### ISSUE TITLE
Reopen previous completion

### ISSUE THREAD

**Issue by mgraham** [minad/consult#433]
Is there a way of opening the last consult buffer regardless of what type it was?  I'd like to hit a key to get me back to the same completion list without having to stop and remember what kind of completion it was.

Also, when returning to a really long list (e.g. a consult-ripgrep session) is there a way of entering the previous search and also starting with the consult buffer scrolled to the same place in the results?

**Comment by minad** [comment]
Vertico provides the command `vertico-repeat`, which restores the last session. But I am not very fond of this functionality and don't encourage its use. I think it is better to export the ripgrep results to an Embark collect buffer and proceed from there in case you want to access multiple results. Furthermore there is a minibuffer history which allows you to restore the latest input. Given the minibuffer history and Embark collect, `vertico-repeat` feels pretty much unnecessary. But it is still provided in case one forgets to persist the search results via Embark collect and to support a quick restart. I am not sure if it will scroll to the right position for `consult-ripgrep`, since for this command the results come in asynchronously and the search is restarted. Probably not. At the point the session is restored, the results haven't arrived yet. Does this answer your question?

**Comment by mgraham** [comment]
> Vertico provides the command `vertico-repeat`, which restores the last session. 

Thank you!  I've installed it and it's great!

> But I am not very fond of this functionality and don't encourage its use. I think it is better to export the ripgrep results to an Embark collect buffer and proceed from there in case you want to access multiple results.  

I was not aware of the Embark collect feature - that makes a lot of sense, especially for long ripgrep searches.  Thank you.

I do think there is a place for `vertico-repeat` for quickly getting back to the previous search.  I'll play around with both approaches.

> Furthermore there is a minibuffer history which allows you to restore the latest input. 

This is also great, but it does not restore cursor position of course.

> I am not sure if it will scroll to the right position for `consult-ripgrep`, since for this command the results come in asynchronously and the search is restarted. Probably not. At the point the session is restored, the results haven't arrived yet. 

Yes, confirmed, it doesn't restore cursor position 😞.  

I think probably I should avoid getting myself into a situation where I have to scroll 1000 lines through a ripgrep search in the minibuffer.  I should probably either get better at narrowing my searches or use the Embark collect feature as you suggest.

> Does this answer your question?

Yes, thank you very much for the quick reply!  

(And sorry I posted this in the issue tracker for consult instead of vertico.  This is the second time I've gotten it wrong :grin:)

**Comment by minad** [comment]
> (And sorry I posted this in the issue tracker for consult instead of vertico. This is the second time I've gotten it wrong grin)

No right or wrong here. The issue fits both issue trackers :)

**Comment by Atemu** [comment]
Embark collect is nice and does somewhat solve the issue if you think of using it but I have really gotten used to just being able to resume ripgrep searches in Ivy.

Would it be possible to wait for n results to come in asynchronously and then restore position n?  
The order should stay the same and if there was a change in between resumes, you'd at least be close to where you were before.  
The perfect solution would be to save the candidate line + file and search for it in the results but I don't think that's necessary.

**Comment by minad** [comment]
@Atemu I won't implement this and I won't accept a patch since it is inefficient and doesn't fit the design. But you can of course implement such a command in your user configuration which waits conditionally only for consult-(rip)grep.

**Comment by Atemu** [comment]
@minad that's fair.

Could you point me towards the function that is called when async results come in where I'd need to hook into?

**Comment by minad** [comment]
@Atemu 

I had another idea - you could also try to restore the entire Vertico state. I believe this is what Ivy does when repeating. In contrast vertico-repeat only stores the input and the candidate, see vertico-repeat-history. This makes it possible to cheaply store the history across Emacs sessions.

> Could you point me towards the function that is called when async results come in where I'd need to hook into?

vertico--exhibit is called when no candidates come in to update the display.

**Comment by Atemu** [comment]
> you could also try to restore the entire Vertico state. I believe this is what Ivy does when repeating. In contrast vertico-repeat only stores the input and the candidate, see vertico-repeat-history. This makes it possible to cheaply store the history across Emacs sessions.

I think that's a good property to keep. There's a reason I'm trying to move away from Ivy and I highly appreciate your more minimal approach.

> vertico--exhibit is called when no candidates come in to update the display.

What do you mean by that? Do you mean that it's called once when the last candidate has come in asynchronously?

I'm more looking for the function that updates the list of candidates whenever a batch of new results comes in.

**Comment by minad** [comment]
> I'm more looking for the function that updates the list of candidates whenever a batch of new results comes in.

There was a typo. vertico--exhibit is the function you are looking for.

**Comment by amosbird** [comment]
I wonder if we can reuse something from recursive-edit and exit-recursive-edit to implement a full-fledged restore feature.

**Comment by minad** [comment]
@amosbird Yes, it is a good idea. I have a basic implementation for Vertico. We are discussing it at https://old.reddit.com/r/emacs/comments/1686ujn/switching_from_helm_to_vertico_and_friends/.

~~~ elisp
(defvar-local vertico-suspend--wc nil)

(defun vertico-suspend ()
  (interactive)
  (if-let ((win (active-minibuffer-window))
           (buf (window-buffer win))
           ((buffer-local-value 'vertico--input buf)))
      (cond
       ((minibufferp)
        (unless (frame-root-window-p win)
          (window-resize win (- (window-pixel-height win)) nil nil 'pixelwise))
        (overlay-put vertico--candidates-ov 'after-string "")
        (move-overlay vertico--count-ov (point-min) (point-max))
        (overlay-put vertico--count-ov 'before-string "")
        (overlay-put vertico--count-ov 'invisible t)
        (set-window-parameter win 'no-other-window t)
        (setq vertico-suspend--wc (current-window-configuration))
        (dolist (w (get-buffer-window-list buf))
          (unless (eq w win) ;; vertico-buffer window
            (delete-window w)))
        (other-window 1))
       (t
        (select-window win)
        (when vertico-suspend--wc
          (overlay-put vertico--count-ov 'invisible nil)
          (set-window-parameter win 'no-other-window nil)
          (set-window-configuration vertico-suspend--wc nil t)
          (setq vertico-suspend--wc nil))))
    (user-error "No Vertico session to suspend or resume")))

(keymap-global-set "M-S" #'vertico-suspend)
~~~

**Comment by amosbird** [comment]
@minad I’ve been using this feature for half a day, and it works smoothly. Thank you!

**Comment by minad** [comment]
Unfortunately there are still a few open issues noted on the wiki page. It seems to me that recursive minibuffers in Emacs are somewhat artificially limited, which hurts the experience.
