### ISSUE TITLE
BUG Use `C-g` to escape `consult-completing-read-multiple`

### ISSUE THREAD

**Issue by carlosperezm** [minad/consult#434]
Hi!
I am using the `consult-completion-read-multiple` interface through bibtex-actions and noticed that it is not possible to escape using `C-g`, only `ESC` works. (mentioned in https://github.com/bdarcus/bibtex-actions/issues/317#issuecomment-933606458) Is this intended behavior?
This is not really a major annoyance, but it would be a nice-to-have for consistency.
Thanks in advance!

**Comment by minad** [comment]
> I am using the |consult-completion-read-multiple| interface through
> bibtex-actions and noticed that it is not possible to escape using
> |C-g|, only |ESC| works.

This issue has been introduced by Emacs 28, which somehow changed the
way the minibuffer is aborted. I haven't looked into these changes yet.
Hopefully @jakanakaevangeli can help, since I believe he introduced
these changes? The issue is that consult-completing-read-multiple
catches exit and continues depending on the value. Probably some other
special exit value must be handled?

**Comment by jakanakaevangeli** [comment]
Yes, see the string of `recursive-edit` in Emacs 28. This patch should fix
this.

```diff
diff --git a/consult.el b/consult.el
index 6672276..ab1a621 100644
--- a/consult.el
+++ b/consult.el
@@ -2454,7 +2454,8 @@ (defun consult-completing-read-multiple (prompt table &optional
                                     (format " (%s selected): " (length selected)))))
                    (delete-minibuffer-contents)
                    (run-hook-with-args 'consult--completion-refresh-hook 'reset))))
-              ('t (throw 'exit t)))))
+              ('continue nil)
+              (other (throw 'exit other)))))
     (fset hook (lambda ()
                  (when (and this-command (= depth (recursion-depth)))
                    (setq command this-command this-command wrapper))))
```

**Comment by carlosperezm** [comment]
Can confirm it works! thanks for the prompt reply!
