### ISSUE TITLE
[question] call vanilla xref display function while in consult-xref 

### ISSUE THREAD

**Issue by thanhvg** [minad/consult#438]
Hi,

I like both `consult-xref` and the vanilla one. When the result set is small the former is enough but  when it is large I want the later one. I know embark export can do it but the exported buffer is a dead one compared to  the built-in `xref-show--xrefs-function` can. 

What I want is while I am in `consult-xref` browsing the results I can call a function that exit `consult-xref` and call the built-in xref display function and it will show the current search result in `*xref*` buffer. I did some testing and it is possible to cache the current `fetcher` and `alist` and pass them back to `xref--show-xref-buffer` which gets `*xref*` buffer show up. And then I can add that function to `consult-xref` keymap. The problem is that I can't exit `consult-xref` properly. I think because  in the code https://github.com/minad/consult/blob/main/consult-xref.el#L90  `xref-pop-to-location` is waiting on `consult--read` to return a selection. So it seems more complicated than I expected, it would involve a bunch of tricks like `embarks` is doing. Do you have any suggestions?

Thanks.

**Comment by oantolin** [comment]
I think that maybe instead of that a better fix would be to improve the Embark export functionality for this case.
