### ISSUE TITLE
RPC for PR: add preview functionality to non-consult commands 

### ISSUE THREAD

**Issue by iyefrat** [minad/consult#439]
Hey minad! My FSF assignment finally went through. With this in mind I have a PR I want to make to consult, but I'd like to hear your thoughts before I start working on it.

Being able to preview things with consult is very useful, but it's unfortunately limited to commands defined with `consult--read`. I'd like to try and add this functionality to non-consult commands. Is this something you're interested it?

Currently I sort of do this in the doom module by binding this:
```emacs
(defun +vertico/embark-preview ()
  "Previews candidate in vertico buffer, unless it's a consult command"
  (interactive)
  (unless (bound-and-true-p consult--preview-function)
    (save-selected-window
      (let ((embark-quit-after-action nil))
        (embark-dwim)))))
```
to the preview key on `vertico-map`, but this is not a good solution, since it pollutes the buffer space with the preview buffers. Since this is already a solved problem on the consult side, I think it would be a good idea to write something that adds this behavior to more functions. Perhaps by having a setting you can turn on that matches `completing-read` function categories with state functions that would be a good fit. What do you think? Is this a good fit for consult? Or maybe only as a separate library that depends on consult?

**Comment by minad** [comment]
@iyefrat Did you make further experiments?
