### ISSUE TITLE
How do consult- lines sort normally, from top to bottom?

### ISSUE THREAD

**Issue by e190** [minad/consult#440]
As in the picture, consultant-lines always sorts from the current line downwards.I tried to press <up> to see the match above , but I couldn't.
![1633688365(1)](https://user-images.githubusercontent.com/39932163/136540956-7676137a-8dfc-4895-aae2-5b24ed34ea36.jpg)

I want to be like Swiper

![图片](https://user-images.githubusercontent.com/39932163/136541115-1187235b-d4ea-4602-af74-bee5cac9f83a.png)

**Comment by minad** [comment]
You can only sort downwards from the current line with wrap around or from the top, see also the configuration option consult-line-start-from-top. See also #287 for some previous discussion.
