### ISSUE TITLE
consult-yank-pop ignores system clipboard

### ISSUE THREAD

**Issue by floli** [minad/consult#443]
Hello!

I use `consult-yank-pop` by means of `use-package` and `([remap yank-pop] . consult-yank-pop)`. My other setup is Emacs 27.1, vertico, orderless, marginalia, embark and consult-20211009.1756 on Linux.

consult-yank-pop seems to be ignoring stuff from the system clipboard, e.g. I do
1. Mark something in the X11 terminal and right click -> copy.
2. Invoke M-y (consult-yank-pop) in Emacs -> it's not there
3.  Call `M-x yank` -> expected text is inserted.
4. Try M-y again -> expected text is shown at the top of the kill-ring.

Setting `save-interprogram-paste-before-kill` to `t` doesn't change anything.

Any ideas how I can make consult/Emacs honor the external clipboard, like plain `(yank)` does it?

Thanks!

**Comment by minad** [comment]
This advice should also solve the issue:

~~~ elisp
(defun save-interprogram-paste ()
  ;; copyied from kill-new
  (let ((interprogram-paste (and interprogram-paste-function
                                 (funcall interprogram-paste-function))))
    (when interprogram-paste
      (dolist (s (if (listp interprogram-paste)
                     ;; Use `reverse' to avoid modifying external data.
                     (reverse interprogram-paste)
		   (list interprogram-paste)))
	(unless (and kill-do-not-save-duplicates
		     (equal-including-properties s (car kill-ring)))
	  (push s kill-ring))))))

(advice-add #'consult--read-from-kill-ring :before #'save-interprogram-paste)
~~~
