### ISSUE TITLE
`consult-completing-read-multiple` does not clean up `crm-separator` from selected

### ISSUE THREAD

**Issue by natrys** [minad/consult#448]
Hello, thanks a lot for Consult.

Am I correct in assuming that `consult-completing-read-multiple` should be compatible with `completing-read-multiple`? If so, I observe that consult isn't trimming the `crm-separator` from the end of selected candidates, unlike original implementation. Consider:

```emacs-lisp
(let ((crm-separator ","))
  (completing-read-multiple
   "prompt: "
   '("abc," "def," "ghi,")))
```
For the original implementation, the result of this expression could be `'("abc" "ghi")` whereas for same choices consult produces `("abc," "ghi,")`.

**Comment by minad** [comment]
Yes, it does not. But I don't think it should. This cleaning of the separator is an implementation detail of the original crm implementation. Duplicate #410.

**Comment by minad** [comment]
@natrys Out of interest, where do you observe this issue? So far the problem occured only with notmuch.

**Comment by natrys** [comment]
@minad Actually yeah I also just arrived from `notmuch`. I should have searched for past issues, but my premise being you were aiming for compatibility was wrong.

Fwiw, I agree with your reasoning now. And indeed it should be a simple fix from `notmuch` side.

**Comment by minad** [comment]
In the other issue there is a simple fix via an advice. But it would probably be good if you ping the notmuch maintainers again. I think the patch didn't get applied and the discussion somehow died off.

**Comment by natrys** [comment]
For posterity, this was recently fixed in [notmuch](https://github.com/notmuch/notmuch/commit/20b2150406e1f80af6417ac601ff366de7eb804b).
