### ISSUE TITLE
consult-register: Add support for file registers

### ISSUE THREAD

**Issue by jobor** [minad/consult#449]
It's possible to assign a file to a register:
`(set-register ?a '(file . "~/.emacs.d/init.el"))`

`consult-register` does not display a "header" for it, nor is narrowing supported.

This can be mitigated by extending `consult-register-narrow` like this:

```
;; Add support for file registers.  Use narrowing key f.
(push `(?f "File" ,(lambda (x) (and (listp x) (eq (car x) 'file)))) consult-register-narrow))
```
The f narrowing key is unfortunately already taken by frameset registers.
We need to come up with something else.

Personally, I have changed the narrowing key for framesets to t:
```
;; Change the narrowing key for frameset registers to t.
(setcar (seq-find (lambda (x) (equal "Frameset" (cadr x))) consult-register-narrow) ?t)
```
More that's missing:
- support in `consult-register-store`
- a somewhat nicer preview

**Comment by minad** [comment]
> It's possible to assign a file to a register:
> |(set-register ?a '(file . "~/.emacs.d/init.el"))|

These file register values are legacy values as far as I can tell. There
are the more precise file-query register values which are created from
markers, when buffers are closed. Which package produces file register
values in your setup?

**Comment by oantolin** [comment]
I don't think any package produces the file register values, I think people who use them write the command to set them themselves in their `init` file. It's a relatively common tip to use file register for single letter access to important files.

**Comment by jobor** [comment]
I'm creating these registers manually to switch between buffers of related files in a project. The important thing for me is that file registers do not store a buffer position. So when switching between the files, the position within the file is maintained.

I think I've found the tip here at some point:
https://www.emacswiki.org/emacs/Registers#toc4
