### ISSUE TITLE
Info manual is missing

### ISSUE THREAD

**Issue by oantolin** [minad/consult#451]
I'm not sure what happened but the Consult info manual seems to be missing. I still have info manuals for Vertico and Corfu.

**Comment by minad** [comment]
Yes, observed this too. The info manual is supposed to be built by ELPA. But tbh I don't miss the info manual, opening the readme in org makes so much more sense. Info has fallen out of time :-P

**Comment by minad** [comment]
The info manual is installed if Consult is installed from GNU-devel. These days I recommend the following package manager setup. This way you get the newest nightly builds from all sources, while the versioning is still correct (for GNU/NonGNU ELPA).

~~~ elisp
(setq package-archives '(("gnu-devel" . "https://elpa.gnu.org/devel/")
                         ("nongnu-devel" . "https://elpa.gnu.org/nongnu-devel/")
                         ("melpa-devel" . "https://melpa.org/packages/"))
      package-archive-priorities '(("gnu-devel" . 2)
                                   ("nongnu-devel" . 1)
                                   ("melpa-devel" . 0))
      package-archive-column-width 14
      package-version-column-width 26)
~~~

**Comment by hmelman** [comment]
I'm running 28.2 and don't see `package-archive-priorities` is it an Emacs 29 addition?
