### ISSUE TITLE
keep minibuffer open with consult-grep

### ISSUE THREAD

**Issue by grolongo** [minad/consult#458]
Hello,

When using `consult-grep` the minibuffer showing the results disappears after pressing `<RET>` over one candidate.
I have to repeat the whole command and type my keyword (or use `M-p`) each time to visit other files.

Is there a way to make it so when pressing `<RET>` the buffer stays up?

**Comment by mohkale** [comment]
You can use vertico-repeat (or there should be a binding in whatever completion framework you're using to restore it). Alternatively you can hit `prev-line` in the minibuffer and it should insert whatever was last in there from your history. Lastly, pretty sure this is what embark-act is for. You can configure embark not to exit after running an action so make embark run the default action and you'll be placed back in your minibuffer.

**Comment by minad** [comment]
@grolongo First I recommend `embark-collect-snapshot` or `embark-export` instead of `vertico-repeat`. In particular `embark-export` yields a `grep-mode` buffer which can be edited using `wgrep`. Then @mohkale is right that you can use `embark-act` (with the setting `embark-quit-after-action=nil`) to perform an action, in particular also the default action. Furthermore there is a third way - since Consult has preview (automatic or manual) you can simply rely on the preview and go to the other window (C-x o), do your edits and go back afterwards. There are many ways! Does this answer your question?

**Comment by oantolin** [comment]
I was going to recommend just keeping the minibuffer open, as @minad says. If you bind other-window to something more convenient than `C-x o`, like `M-o`, say, and if you also set `enable-recursive-minibuffers` to `t` so you can easily run other commands, then just leaving the minibuffer open until you are done with it can be pretty convenient.

**Comment by minad** [comment]
`enable-recursive-minibuffers=nil` is such an odd setting. Why does it even allow you to move to another window? There should be a variable `lock-me-into-the-minibuffer` :-P

**Comment by grolongo** [comment]
Thank you all for your suggestions. Really appreciate it.

I disabled virtual buffers entirely (even in `consult-buffer` and `consult-recent-file`) even though this is a cool feature, as it is a real distraction to me.

Having all those buffers flashing their content rapidly on my screen even when I don't need them when I'm doing `C-n` or `C-p` really gets me confused and a bit dizzy. Maybe my workflow is weird or I'm a bit too sensitive, probably both ;).

Don't get me wrong though, this is a great feature and I'm not bashing it, it's just not for me unfortunately.

I thought about Embark like you guys mentioned as I have it installed too. Yet I'm having weird issues:

after doing `M-x consult-grep` --> search for `foo` --> `Embark-act` --> `embark-export`
I'm getting the `Embark-collect` buffer with the results from `consult-grep` as expected.
But when I'm pressing `<RET>` on one result this is the error message I have:
`Error running timer ‘consult--async-after-change’: (buffer-read-only #<buffer *Embark Collect*>)`

Using `embark-collect-snapshot` instead gives the same error message.

My embark-consult config is very basic:
```
(use-package embark-consult
  :ensure t
  :bind ("C-;" . embark-act)
  :custom (prefix-help-command #'embark-prefix-help-command))
```

**Comment by minad** [comment]
> Having all those buffers flashing their content rapidly on my screen even when I don't need them when I'm doing C-n or C-p really gets me confused and a bit dizzy. Maybe my workflow is weird or I'm a bit too sensitive, probably both ;).

There are multiple options - you can debounce the preview or even make it completely manual. Configuring the preview as manual is my usual recommendation for expensive previews like files in consult-buffer and consult-recent-file. But for commands like consult-line I definitely want automatic preview.

> I'm getting the Embark-collect buffer with the results from consult-grep as expected.

Did you install embark-consult? Maybe your packages are also outdated? I've not seen such an error or any error with embark-collect-snapshot for quite some time.

**Comment by grolongo** [comment]
> There are multiple options - you can debounce the preview or even make it completely manual. Configuring the preview as manual is my usual recommendation for expensive previews like files in consult-buffer and consult-recent-file. But for commands like consult-line I definitely want automatic preview.

That's a good option, I might end up using this, thank you.

About Embark:

embark-consult:
Version: 20211031.1522
Commit: 810544f9fcb8e0ddf0d9b89682c208e2127f8f13

consult:
Version: 20211027.1058
Commit: e10775aab1cd4ee4af1e610128508b81288dadca

And I'm definitely not getting a grep-mode buffer, only `Embark-collect` ones. :/

**Comment by oantolin** [comment]
This definitely sounds like `embark-consult` isn't being loaded in time. With the `use-package` form you posted above, `embark-consult` won't be loaded until you run `embark-act` for the first time. If you do that from `consult-grep` it's too late for that invocation to export to grep, but then the next time you run `consult-grep` you should get the grep export. I hope.

**Comment by grolongo** [comment]
Unfortunately this isn't happening. Before going further I'll bisect and use a minimal config to see what happens.

**Comment by grolongo** [comment]
@oantolin simply `:demand t` fixed it, but using `embark-act` once and twice doesn't load `embark-consult` like you suggested. Not sure if that's normal.

**Comment by oantolin** [comment]
I'm glad `:demand t` fixed it!

> but using `embark-act` once and twice doesn't load `embark-consult`

I think that's not quite what I meant, I was talking about running `consult-grep` twice, not just `embark-act`. What I meant is that when you do:

`consult-grep` -> `embark-act` -> `embark-export`

the `use-package` declaration you have arranges for `embark-consult` to be loaded when you run `embark-act`, but that is too late for the export to be configured for that call to `consult-grep`. If you run `consult-grep` again, I believe that this second time the grep export should work.
