### ISSUE TITLE
consult-rg/ag/grep?

### ISSUE THREAD

**Issue by liebkne** [minad/consult#46]
Thanks for the great package. Is there any plan to implement search functions like `consult-rg/ag/grep`?

**Comment by minad** [comment]
This is already on the wishlist. There is a roadblock though which prevents me from implementing this right now (see #10). But I am sure this will be resolved at some point. Furthermore I wonder why the other grep/rg packages do not fit the bill. I've read about live preview etc. But if other excellent packages already provide the functionality perfectly we may not implement it here.
