### ISSUE TITLE
consult-recent-file shows red ^M s

### ISSUE THREAD

**Issue by notuntoward** [minad/consult#464]
I really like the file preview in` M-x consult-recent-file`.  But one problem with it is that, for some files, the preview is cluttered by red ^M s (screenshot).  If I open one of those files, the ^M s aren't shown, so it looks like a display step is missing in the preview.  This is on GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26

![image](https://user-images.githubusercontent.com/3851891/140654344-01fdaa36-ba5e-4fc5-b516-9580417e7874.png)

**Comment by oantolin** [comment]
I think what happens is that the file preview, to speed things up, visits the file literally when it is larger than some threshold. This means the preview has no syntax highlighting and also that Emacs doesn't do its usual line ending processing.

Maybe there's a way of just turning off the fontification and keeping the line ending stuff. I don't know.

**Comment by minad** [comment]
> visits the file literally when it is larger than some threshold

That's correct. The energy.bib file is larger than the default threshold.

**Comment by notuntoward** [comment]
Thanks for the reply.  Are #465 and this WON'T FIX then?

**Comment by minad** [comment]
You can "fix" it in your configuration by adjusting `corfu-preview-raw-size`. But this will have downsides during preview, slowdown etc. My recommendation is to disable automatic preview for recent files, see https://github.com/minad/consult#live-previews.

**Comment by oantolin** [comment]
> corfu-preview-raw-size

I think you meant consult-preview-raw-size

**Comment by minad** [comment]
Subconsciously smuggling in some Corfu advertisement for you ;)

**Comment by notuntoward** [comment]
Got it.  Thanks.
