### ISSUE TITLE
Question: ripgrep with context: -C, -A, -B flags 

### ISSUE THREAD

**Issue by agzam** [minad/consult#466]
I just recently switched to Doom and have found that searching with context flags not working.

*Please excuse my lack of experience, I'm very new to this entire completion framework and Doom, etc. I wasn't sure if this is the right place to ask this question, I tried searching for issues in Doom repo, found tons of things related to search, tried digging up a bit, and it felt to me like an upstream issue that may need to be addressed here and not in Doom.*

I can't perform searches similar to `rg foo -C5` in Emacs for some reason. I'm not sure why, maybe because ripgrep adds empty lines and "--". Maybe `consult-async-split-styles-alist` needs to be tweaked, or something like that. 

I'm trying to type for search `"foo -- -C5"` and it's not working

Could someone shed some light to this, please?

**Comment by minad** [comment]
> Could someone shed some light to this, please?

It's a bug. Thanks for the report!

**Comment by agzam** [comment]
Oh, thank you for fixing it so quickly. I'm surprised no one has bothered with this before. I just started using these tools, and I have to say - they are amazing. No wonder everyone keeps talking about them. I was hesitant first: "urgggh, I just switched to Ivy like yesterday; do we really need another completion framework? Really?" I'm so glad though I tried. Incredibly well done. Thank you for this gift to the community. Emacs is awesome not only because its technological foundation is great, but mainly because of phenomenal programmers like you. Thank you for making my world a better place.

**Comment by minad** [comment]
Thank you!

> urgggh, I just switched to Ivy like yesterday; do we really need another completion framework? Really?

Come on! Emacs is moving fast these days. And Ivy is already 5 years old. ;)

> I'm surprised no one has bothered with this before.

I guess it is not so widespread to use this feature in the context of completion, since many people (ab)use these commands as a jumper. But it is certainly a nice feature in particular in combination with embark-collect/embark-export.

I pushed a small improvement to the context handling - https://github.com/minad/consult/commit/bd0e74d026d721c5f8ed71e98ba54d4605002e1c. Please let me know what you think!

**Comment by agzam** [comment]
Whoa! This is awesome. I didn't even have to add a face. So cool. Thank you!

**Comment by agzam** [comment]
https://twitter.com/iLemming/status/1458689963588046856
