### ISSUE TITLE
:lookup seems to be ignored by consult--multi

### ISSUE THREAD

**Issue by Hugo-Heagren** [minad/consult#470]
The `consult--multi` docstring suggests that all keyword options are passed onto `consult--read`. I wanted to specify a lookup function in my use of `consult--multi`. Now, this works, in that it presents `one`, `two`, `three` but return 1, 2 or 3 respectively:

```elisp
(defvar test-source '(:name "test source"
		      :items (("one" . 1)
			      ("two" . 2)
			      ("three" . 3))))

(consult--read (plist-get test-source :items)
		:prompt "test"
		:history t
		:sort nil
		:require-match t
		:lookup #'consult--lookup-cdr)
```

This appears to be the equivalent for the following. But that doesn't work:

```elisp
(defvar test-source '(:name "test source"
		      :items (("one" . 1)
			      ("two" . 2)
			      ("three" . 3))))

(consult--multi '(test-source)
		:prompt "test"
		:history t
		:sort nil
		:require-match t
		:lookup #'consult--lookup-cdr)
```

This gives me an error complaining that `(wrong-type-argument listp 1)`. Is this intentional? If so, is there an alternative for situations like this (where I want to complete over candidates generated from a list, but return a member of the original list, not a candidate)?

**Comment by minad** [comment]
You can attach text properties to the candidates and extract your data from there. Alternatively you can specify an :action argument in the source.
