### ISSUE TITLE
Consult find won't find files that are in dot directories

### ISSUE THREAD

**Issue by sethen** [minad/consult#472]
I don't know if there is a configuration option or something I am missing but `consult-find` will not find any file in a dot directory.

Considering the following example:

```
-> parentDirectory
--> .emacs.d/
---> sethen-file.el
--> sethen-another-file.el
```

Using `consult-find` and typing `sethen` I will get `sethen-another-file.el` in my search results but not `sethen-file.el`.  Moving `sethen-file.el` from the `.emacs.d` directory into the parent will make it show up.  What am I missing here?

**Comment by minad** [comment]
Hidden files are filtered out by default: https://github.com/minad/consult/blob/69bc425c59414ece0a49dfa8e3f2d9759a13748c/consult.el#L250. You can change this configuration variable.

**Comment by sethen** [comment]
@minad Sorry I am new to elisp -- what do I have to set to make this look at hidden files?

**Comment by minad** [comment]
~~~ elisp
(setq consult-find-args "find .") 
~~~

**Comment by sethen** [comment]
@minad Actually this doesn't seem to be working for some reason... Here is my code

```
(require 'use-package)

(use-package consult
  :config
  (setq consult-find-args "find ."
		consult-project-root-function
		(lambda ()
		  (when-let (project (project-current))
			(car (project-roots project)))))
  :commands
  (project-roots))

(provide 'sethen-consult)
```

I am using emacs 29 and just recently updated the packages.  Still can't search for things in a directory like `.emacs.d` for whatever reason.

**Comment by minad** [comment]
When I run `find . -iregex ".*foo.*"` on the command line, `find` looks into hidden directories. With `consult-find` it works for me if I set `(setq consult-find-args "find .")`. You may want to look into the `_*consult-async*` log buffer.

**Comment by sethen** [comment]
@minad How do I access that buffer?

**Comment by minad** [comment]
> How do I access that buffer?

With consult-buffer ;)

It is documented in the readme. The buffer is ephemeral (a space prefixed hidden buffer). We seem to have problems here with hidden things ;)
