### ISSUE TITLE
Windows: Consult-ripgrep and non-ascii characters

### ISSUE THREAD

**Issue by mrc16** [minad/consult#475]
i'm trying to search on russian with `consult-ripgreg` (M-s r) command but nothing happens.
If I search directly on the command line using a `rg` with russian language, everything works. Also, built-in regex search (C-M-s) with russian language as input handles well.

How can this be fixed?

**Comment by minad** [comment]
I don't know, but maybe @abcdw can help you?

**Comment by abcdw** [comment]
I have consult and ripgrep packages installed with Guix.

![image](https://user-images.githubusercontent.com/1218615/144091335-dbd7f52f-41c0-4e5e-b3ff-5753b6f8e68b.png)

Seems ok to me.

Don't see anything special in my configuration:
https://git.sr.ht/~abcdw/rde/tree/master/rde/features/emacs.scm

**Comment by mrc16** [comment]
Sorry, i'm on windows ) GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)

**Comment by minad** [comment]
It seems that Emacs on Windows is broken. For example Counsel manually encodes the arguments. It is unclear to me why the encoding is not applied by the underlying Emacs process implementation.

https://github.com/abo-abo/swiper/blob/1c6b3da377a840e898b14020133f59fca9ceea1c/counsel.el#L2655-L2662

**Comment by mrc16** [comment]
If you apply same patch, maybe it will work?

**Comment by minad** [comment]
I don't know. I don't use Windows and I am not familiar with Emacs on Windows. If someone prepares a patch and confirms that it works, I am happy to merge the fix - of course it should not affect the operation of Consult on Unix.

**Comment by mrc16** [comment]
After a some investigations, I added follow code to my init.el:
```
(add-to-list 'process-coding-system-alist 
             '("[rR][gG]" . (utf-8-dos . windows-1251-dos)))
```
I don't know how it works, but does. Might help someone else.

**Comment by minad** [comment]
Duplicate #317

**Comment by chu-** [comment]
> I don't know. I don't use Windows and I am not familiar with Emacs on Windows. If someone prepares a patch and confirms that it works, I am happy to merge the fix - of course it should not affect the operation of Consult on Unix.

I test on my MacOS in Chinese and Russian characters.

Firstly, consult-grep.
Then type following characters.
It doesn't work, same as above issue and no response:
1. #测试
2. 测试
3. #Л
4. Л
 
It works:
1.'测试‘
2."测试"
3.'Л'
4."Л"

**Comment by abcdw** [comment]
@chu- This is cause of threshold and probably not related to the issue above:

```
consult-async-min-input is a variable defined in ‘consult.el’.

Its value is 3

Minimum number of letters needed, before asynchronous process is called.

This applies to asynchronous commands, e.g., ‘consult-grep’.
```

**Comment by chu-** [comment]
> @chu- This is because of threshold and probably not related to the issue above:
> 
> ```
> consult-async-min-input is a variable defined in ‘consult.el’.
> 
> Its value is 3
> 
> Minimum number of letters needed, before asynchronous process is called.
> 
> This applies to asynchronous commands, e.g., ‘consult-grep’.
> ```
Exactly. You are right, thank you! It works, when I type at least 3 characters such as 测试中.
