### ISSUE TITLE
consult-grep/ripgrep don't match regular expressions

### ISSUE THREAD

**Issue by memeplex** [minad/consult#476]
I may be misunderstanding something, but the documentation of these functions:

> Search for regular expression in files.

>  If you enter multiple regular expressions separated by space only lines matching all regular expressions are shown.

Implies that `#regexp` should work. But I'm unable to use any trivial `.*`, `.` wildcard (which perfectly work when calling grep and rg from a shell). Only literal matches are working. For example, I search for `title` and get five results, I search for `tit.e` or `.*tle` and get none.

**Comment by memeplex** [comment]
The problem seems to happen when fido-mode is enabled, at least it's working in a saner way with icomplete, I've not tried another completion framework yet.

**Comment by minad** [comment]
You should try a completion style like `orderless`. The `flex` completion style of `fido-mode` does not support regular expressions. Please follow https://github.com/minad/consult/#bug-reports.

**Comment by memeplex** [comment]
Sorry I don't understand what the completion style has to do with regex support. I've now tried both icomplete and vertico with flex and both work fine with regexs. Well, not completely fine, I still can't see why I have to escape parens with pcre2 nor why some lookahead expressions like `\(?=a\)\(?=b\)` fail, while they work just fine with the same cli args from a terminal, but I've this problem with orderless also.

**Comment by memeplex** [comment]
BTW, there are some quirks with icomplete, like the fact that `?` is already bound to a completion command. Also left/right arrows are captured in fido-mode to scroll through results (the same than up/down). Overall the initial experience has been poor with builtin frameworks, so I probably will use vertico.

**Comment by minad** [comment]
> Well, not completely fine, I still can't see why I have to escape parens with pcre2 nor why some lookahead expressions like \(?=a\)\(?=b\) fail, while they work just fine with the same cli args from a terminal, but I've this problem with orderless also.

Good point. I clarified this in the README. `consult-grep` uses Emacs regular expressions for a uniform search experience. If you dislike this you can adjust the `consult--regexp-compiler`. Note that the regexp compiler also supports orderless-style patterns, e.g., `#first second` searches for both `first` and `second` in any order.

> BTW, there are some quirks with icomplete, like the fact that ? is already bound to a completion command. Also left/right arrows are captured in fido-mode to scroll through results (the same than up/down). Overall the initial experience has been poor with builtin frameworks, so I probably will use vertico.

You have to rebind and configure the completion framework properly in your user configuration. This is not the job of Consult. Consult stays out of the way. This does not mean that it works poorly.

**Comment by minad** [comment]
> Sorry I don't understand what the completion style has to do with regex support. I've now tried both icomplete and vertico with flex and both work fine with regexs. Well, not completely fine, I still can't see why I have to escape parens with pcre2 nor why some lookahead expressions like \(?=a\)\(?=b\) fail, while they work just fine with the same cli args from a terminal, but I've this problem with orderless also.

To go more into detail about this - as I mentioned the problem is that `fido-mode` overwrites the completion style with the flex completion style. Consult has to manipulate the completion style to support its prompt input format `#async#sync` where the async string is passed to grep. It seems that the `fido-mode` flex setting happens too late, such that it interferes with Consult, which is unfortunate.

**Comment by memeplex** [comment]
> You have to rebind and configure the completion framework properly in your user configuration. This is not the job of Consult. Consult stays out of the way. This does not mean that it works poorly.

Sorry, I wasn't implying that consult works poorly, just that the interaction with builtin frameworks is not as polished as with vertico, which is to be expected. I do think that this diminishes the advertised "works with every icomplete framework" to some extent, but they're just rough edges that may be overcome with some effort, nothing essential.

**Comment by memeplex** [comment]
>  If you dislike this you can adjust the consult--regexp-compiler.

Nah, it's fine. Emacs syntax is cumbersome but I understand this is intended for coherence. And I prefer not to deal with `--` stuff.

> Note that the regexp compiler also supports orderless-style patterns, e.g., #first second searches for both first and second in any order.

Cool. But AFAICS these are passed to rg as different `-e` arguments, so they have an "at least one", not "both",  semantics?
