### ISSUE TITLE
consult-ripgrep not finding lines in dot directories

### ISSUE THREAD

**Issue by sethen** [minad/consult#479]
I actually was asking the wrong question in #472 -- it's not `consult-find` that isn't working -- that gives me files in dot directories no problem.  It's `consult-ripgrep` is not able to find any sort of lines in dot directories.  `consult-grep` is able to find these things just fine.  I've tried changing the `consult-ripgrep-args` to something like `rg --hidden` but it doesn't work.  What do I need to do to enable searching in hidden files for `consult-ripgrep`?

**Comment by sethen** [comment]
To solve this I just copied what was in the source code and I just added `--hidden` ... seems like this should be by default tho

**Comment by minad** [comment]
> seems like this should be by default tho

No this is not a gooddefault. With this setting ripgrep will also search through version control directories like `.git` which is a big mess. Maybe there is a way to ignore fewer problematic directories and to not generally ignore hidden directories.

**Comment by sethen** [comment]
> > seems like this should be by default tho
> 
> No this is not a good default. With this setting ripgrep will also search through version control directories like `.git` which is a big mess. Maybe there is a way to ignore only a few problematic directories and to not generally ignore hidden directories.

Ah, I didn't think about that -- yeah you're right.
