### ISSUE TITLE
Disabling preview for recent files in consult-buffer

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#481]
I like the preview feature of consult when opening a buffer with `consult-buffer`, but previewing recent files is sometimes slow because it packages might need to be loaded.
Is there a way to disable previews of recent-files but not of buffers in `consult-buffer`?

**Comment by minad** [comment]
This is documented in the README.

**Comment by haji-ali** [comment]
Thanks @minad, and apologies for not adding more details.

I think the documentation might be outdated. The default behaviour of consult seems to be to preview the recent files (in the README it seems to say the opposite). Also the documentation says to customize `consult--source-recent-file` and `consult--source-project-recent-file`, when I tried these before posting it didn't work. I now found out that the name is `consult--source-file` and `consult--source-project-file`. In any case, I now do

```
(consult-customize
 consult--source-file consult--source-project-file consult--source-bookmark
 :preview-key nil)
```

and the previews are correctly disabled.

**Comment by oantolin** [comment]
> previewing recent files is sometimes slow because it packages might need to be loaded.

That's typically how I load Org mode and AUCTeX! 🤣 [Relevant xkcd](https://xkcd.com/1172/).

**Comment by minad** [comment]
Fortunately Consult allows you to use recent file package loading and also to disable it! The situation is way better than for the poor users of space heating. You can have your workflow!

**Comment by minad** [comment]
For reference, preview got more efficient in https://github.com/minad/consult/commit/3b0d745a480220d3eb8367fe73e8bf1321034a4e. See https://github.com/minad/consult/issues/538#issuecomment-1087964040 for details.
