### ISSUE TITLE
Consult-imenu select current index-item

### ISSUE THREAD

**Issue by ngharrison** [minad/consult#482]
I'm trying to have the nearest index-item above the current buffer cursor position be automatically selected when running `consult-imenu`. Is there a correct or recommended way to get this information?

**Comment by minad** [comment]
There is no easy way unfortunately. `consult-imenu` is not meant to be used in this way. You have to iterate over all the items and find the nearest item. You could then use this item as the `:default` for the completion.

Alternatively you could split the list of imenu items, and wrap it around, such that the nearest item is at the beginning. If you use vertico, you can then set `vertico-cycle=t`. You could start with the following snippet.

~~~ elisp
(defun my-consult-imenu ()
  (interactive)
  (consult-imenu--select "Go to item: " (my-items-wrap-around (consult-imenu--items)))))
~~~

And then write a function `my-items-wrap-around` which determines the nearest item and wraps around the list. I hope this helps! Let me know if you have further questions.
