### ISSUE TITLE
Feature request: consult-line backward

### ISSUE THREAD

**Issue by salutis** [minad/consult#483]
I got used to `consult-line` as a replacement for `isearch-forward`, but I miss a replacement for `isearch-backward`.  I imagine `consult-line-backward` to work just like `consult-line` (no changes in the list of lines), but it would jump to the first match backward instead of forward.

**Comment by minad** [comment]
There are two ways to implement this:

1. Reverse the candidates, such that the candidates appear in reverse order. You can implement this via an advice. However I suspect that such a command would be confusing overall with the list in reverse.
2. Use a keyboard macro (or a small function). For example if you use Vertico, you can set `vertico-cycle=t` and then run `consult-line` an press `<up>`. This will take you to the matching line right before the current line. With other UIs you can write corresponding macros.

Note that I consider `consult-line` as an in-buffer grep command (line-based) not as an exact Isearch repacement where you can jump from match to match. Given that you can add such a backward command to your configuration with minimal effort, I am not in favor of adding it here. However I would welcome an addition to the wiki!

**Comment by salutis** [comment]
@minad Thank you for taking the time to reply.  I also consider `consult-line` as an in-buffer grep command, but then, I often need to grep backward. (It boggles my mind that others always grep forward.) I fail to see how pressing `<up>` could work, given that `consult-line` searches (forward) as I type. The reversal of the candidates could work, though!

**Comment by minad** [comment]
It works if you enable cycling, see `vertico-cycle`!

**Comment by salutis** [comment]
@minad Thank you for guiding me. I have the following:

```emacs-lisp
(defun my/consult-line-forward ()
  "Search for a matching line forward."
  (interactive)
  (define-key vertico-map (kbd "C-r") #'vertico-previous)
  (define-key vertico-map (kbd "C-s") #'vertico-next)
  (unwind-protect (consult-line)
    (define-key vertico-map (kbd "C-r") nil)
    (define-key vertico-map (kbd "C-s") nil)))

(defun my/consult-line-backward ()
  "Search for a matching line backward."
  (interactive)
  (advice-add 'consult--line-candidates :filter-return #'reverse)
  (define-key vertico-map (kbd "C-r") #'vertico-next)
  (define-key vertico-map (kbd "C-s") #'vertico-previous)
  (unwind-protect (consult-line)
    (progn
      (advice-remove 'consult--line-candidates #'reverse)
      (define-key vertico-map (kbd "C-r") nil)
      (define-key vertico-map (kbd "C-s") nil))))

(global-set-key (kbd "C-s") 'my/consult-line-forward)
(global-set-key (kbd "C-r") 'my/consult-line-backward)
```

Everything works great except one little detail: When I press `C-r`, `consult-line` highlights the previous line instead of the current line.  (This is before I type the search string.)

**Comment by salutis** [comment]
All right, I figured out the current line issue:

```emacs
(defun my/consult-line-forward ()
  "Search for a matching line forward."
  (interactive)
  (define-key vertico-map (kbd "C-r") #'vertico-previous)
  (define-key vertico-map (kbd "C-s") #'vertico-next)
  (unwind-protect (consult-line)
    (define-key vertico-map (kbd "C-r") nil)
    (define-key vertico-map (kbd "C-s") nil)))

(defun my/consult-line-backward ()
  "Search for a matching line backward."
  (interactive)
  (defun filter (candidates)
    (cons (car candidates) (reverse (cdr candidates))))
  (advice-add 'consult--line-candidates :filter-return #'filter)
  (define-key vertico-map (kbd "C-r") #'vertico-next)
  (define-key vertico-map (kbd "C-s") #'vertico-previous)
  (unwind-protect (consult-line)
    (progn
      (advice-remove 'consult--line-candidates #'filter)
      (define-key vertico-map (kbd "C-r") nil)
      (define-key vertico-map (kbd "C-s") nil))))

(global-set-key (kbd "C-s") 'my/consult-line-forward)
(global-set-key (kbd "C-r") 'my/consult-line-backward)
```

@minad Any comments? (I do not write Emacs lisp in professionally.)

**Comment by oantolin** [comment]
> I do not write Emacs lisp in professionally.

I don't think anyone does, @salutis!

(But if you just meant @minad's code is superb and you'd like some pointers from him, I fully agree.)

**Comment by salutis** [comment]
All right, I added the above to wiki.

Thank you @minad for your help and wise guidance.

**Comment by minad** [comment]
Lol, Omar didn't we agree that Consult is a professional system? For Emacs consultants and academics 😄 

@salutis Thanks for adding your solution to the wiki. I would propose these improvements:

* Don't use nested defuns (bad style)
* Don't modify the vertico-map. Instead specify a :keymap via consult-customize. See for example consult-isearch-history.
* Well and I think reversing the candidates is a bad solution. I already wrote that above. It is better to use vertico-cycle and jump to the end.

**Comment by oantolin** [comment]
> I think reversing the candidates is confusing

Maybe not. Imagine you type a little, then maybe move through some candidates, the type some more. If you don't reverse the candidates, the moment you type some more you're not really doing a reverse search anymore. 

> Omar didn't we agree that Consult is a professional system? For Emacs consultants and academics

🤣 Right, I forgot!

**Comment by minad** [comment]
@oantolin Makes sense!

**Comment by salutis** [comment]
> @salutis [...] I would propose these improvements:
> 
> * Don't use nested defuns (bad style)
> * Don't modify the vertico-map. Instead specify a :keymap via consult-customize. See for example consult-isearch-history.

Done. I updated the wiki page as well.

```emacs-lisp
(defun my/consult-line-forward ()
  "Search for a matching line forward."
  (interactive)
  (consult-line))

(defun my/consult-line-backward ()
  "Search for a matching line backward."
  (interactive)
  (let ((target 'consult--line-candidates)
        (filter 'reverse))
    (advice-add target :filter-return filter)
    (unwind-protect (consult-line) (advice-remove target filter))))

(global-set-key (kbd "C-s") 'my/consult-line-forward)
(global-set-key (kbd "C-r") 'my/consult-line-backward)

(defvar my/consult-line-forward-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-r") #'vertico-previous)
    (define-key map (kbd "C-s") #'vertico-next)
    map))

(defvar my/consult-line-backward-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-s") #'vertico-previous)
    (define-key map (kbd "C-r") #'vertico-next)
    map))

(with-eval-after-load 'consult
  (consult-customize my/consult-line-forward
                     :keymap my/consult-line-forward-map)
  (consult-customize my/consult-line-backward
                     :keymap my/consult-line-backward-map))
```

**Comment by salutis** [comment]
FYI for future readers: I updated the wiki with a new version that uses `vertico-reverse-mode`. (As of now, I have no idea how to enable `vertico-reverse-mode` just for `consult-line-backward`, so that recursive minibuffers work well.)

**Comment by minad** [comment]
@salutis See `vertico-multiform-mode` with examples here: https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category.

**Comment by salutis** [comment]
> @salutis See `vertico-multiform-mode` with examples here: https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category.

OMG, that looks _amazing_. Waiting for MELPA release...

**Comment by oantolin** [comment]
I think those extensions come with Vertico, you don't need to install a separate package.

**Comment by salutis** [comment]
> I think those extensions come with Vertico, you don't need to install a separate package.

Note: At the time of my comment above, the new Vertico with `vertico-multiform-mode` had not reached MELPA yet. I re-tried today, and all works! I will experiment with the new modes shortly.

**Comment by Lenbok** [comment]
> FYI for future readers: I updated the wiki with a new version that uses the `vertico-reverse-mode`. (As of now, I have no idea how to enable `vertico-reverse-mode` just for `consult-line-backward` so that recursive minibuffers work as expected.)

The version in the wiki no longer works (no `vertico-reverse-mode` any more as far as I can tell)

**Comment by minad** [comment]
@Lenbok That's incorrect. `vertico-reverse-mode` still exists.

**Comment by Lenbok** [comment]
@minad correct you are. I simply tried the example wiki code at https://github.com/minad/consult/wiki#isearch-like-backwardforward-consult-line and it exploded. Gah - it seems I need to find the right incantation to make use-package under straight find vertico extensions and then load the vertico-reverse extension to make it work. (I've made a note on the wiki entry)
