### ISSUE TITLE
show a narrowed consult-buffer 

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#484]
Is it possible to call consult-buffer already narrowed to some source?

I tried
```
(minibuffer-with-setup-hook
      (lambda () (consult-narrow 32))
    (consult-buffer))
```
Which seems to work but has `[nil]` in the prompt rather than `[Hidden Buffer]`. Also, I am not sure how to auto-select the first candidate like the normal `consult-buffer` does.

On a related question.  Is there a way to un-narrow candidates?

**Comment by minad** [comment]
Yes, to both your questions. Please take a look at the README and the wiki. Note that this is an issue tracker not a support forum. I am also willing to help out here, but I've already spend quite some time to document everything.

**Comment by haji-ali** [comment]
Thank @minad and apologies for failing to check the wiki first. I see now that there's a way to narrow the consult view to one of the sources.

I also wanted to always select the first candidate after narrowing (as opposed to what happens now where the first candidate is selected only if the source has the first buffer in the list of candidates). I did this by use a function from the completion framework. Not sure if there's a better way of doing this

```
(advice-add 'consult-narrow :after (lambda (&rest _) (vertico--goto 0)))
```

**Comment by minad** [comment]
Yes, this is a good way. You can also set :default=nil via consult-customize. Then the first candidate will be selected automatically.

**Comment by minad** [comment]
> Then the first candidate will be selected automatically. The only reason the first candidate is not selected is the non-nil default which leads to prompt selection in Vertico.

I've addressed the issue with the prompt selection in consult-buffer, see #714.
