### ISSUE TITLE
`occur-edit-mode` & `wgrep` cannot take effect in `embark-export` buffer

### ISSUE THREAD

**Issue by wangggong** [minad/consult#485]
```
emacs -Q
```

In raw emacs:

```
(package-initialize)
(require 'consult)
(require 'vertico)
(require 'embark)
(require 'wgrep)
(global-set-key (kbd "C-x c") 'embark-export)
(vertico-mode)
(setq completion-styles '(orderless))
```

Open `consult-line`, and `embark-export` the result; then `occur-edit-mode` it.

```
M-x consult-line<RET>require ;; Here we get 4 results.
C-x c ;; And open a `Embark Collect` buffer
M-x occur-edit-mode<RET>
```

Just edit a line, then comes an error: `occur-after-change-function: Wrong type argument: markerp, nil`

Make a file: a.txt

```
$ echo "I came\nI saw\nI conquered" > a.txt
$ cat a.txt
I came
I saw
I conquered
```

Open `consult-grep`, and `embark-export` the result; then `wgrep` it.

```
M-x consult-grep<RET>saw ;; a result
C-x c ;; And open a `Embark Collect` buffer
M-x wgrep-change-to-wgrep-mode<RET>
```

Then comes an error: `Invalid search bound (wrong side of point)`

Emacs Version: `GNU Emacs 28.0.90 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.14.2, Xaw scroll bars) of 2021-12-03`
OS: `Linux 9c4593b5699a 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by oantolin** [comment]
The functionality for exporting to occur-mode or grep-mode buffers from consult search commands is in the library `embark-consult`. If you also `(require 'embark-consult)` that should fix the problem.
