### ISSUE TITLE
Find and replace from `consult-ripgrep`

### ISSUE THREAD

**Issue by sethen** [minad/consult#489]
I feel like I am missing something.  Obviously `consult-ripgrep` gives me back the correct matches when I want to search through them.  Is it possible to change all of the matches I found with some sort of find and replace function?  I can't seem to find this in the documentation.

**Comment by minad** [comment]
🧐

**Comment by sethen** [comment]
> 🧐

I'm going to take this as a no?  lol

**Comment by sethen** [comment]
Oh, maybe I missed this the first time because it doesn't explicitly say this -- does Embark offer this in conjunction with Consult?

**Comment by minad** [comment]
There is no special find and replace function, but you can use wgrep to edit the matches. See https://github.com/minad/consult#embark-integration. Did you try this workflow?

**Comment by sethen** [comment]
> There is no special find and replace function, but you can use wgrep to edit the matches. See https://github.com/minad/consult#embark-integration. Did you try this workflow?

Not yet, let me give this a shot.  Thank you!
