### ISSUE TITLE
Browsing history for comint, eshell, shell

### ISSUE THREAD

**Issue by leungbk** [minad/consult#49]
It would be nice if `consult` had functions for browsing their respective history files.

**Comment by minad** [comment]
I think consult-history does what you want? It was just added yesterday!

**Comment by leungbk** [comment]
Thanks @minad, I did not notice that.

Would you be interested in a PR like https://github.com/abo-abo/swiper/commit/69fedaa67b6df93db899184d33cb225148b6c7b8? The purpose is to add support for the `C-c C-x` commands in `comint` and `eshell`.

**Comment by minad** [comment]
@leungbk Can you describe please what you want to do? I took only a quick look to the link, but it is not immediately obvious.

**Comment by leungbk** [comment]
If my `eshell` history contains:

``` sh
echo old
echo newer
echo newest
```

Right now, if I call `consult-history`, then select `echo old` and hit `RET`, there is no way to quickly retrieve its successor, `echo newer` in the history list; I would have to either call `consult-history` again or mash `M-p` until finding it.

The `comint`-like modes all contain a command bound to `C-c C-x` for retrieving the successor; in `eshell` it's called `eshell-get-next-from-history`.

Right now, `consult-history` does not do the bookkeeping required to update the information used by `eshell-get-next-from-history`. The commit I posted above did that for `counsel`'s relevant commands, and I'd now like to write something analogous here in `consult`.

**Comment by minad** [comment]
@leungbk Ok, I see. This sounds good! Looking forward to a PR!
