### ISSUE TITLE
Add auto-load for `consult-preview-at-point-mode` (maybe?)

### ISSUE THREAD

**Issue by salutis** [minad/consult#491]
Currently, the following ...

```emacs-lisp
(add-hook 'embark-collect-mode-hook #'consult-preview-at-point-mode)
```

... causes ...

```
run-hooks: Symbol’s function definition is void: consult-preview-at-point-mode
```

I adapted the hook from Embark `README`:

```emacs-lisp
(use-package embark-consult
  :ensure t
  :after (embark consult)
  :demand t ; only necessary if you have the hook below
  ;; if you want to have consult previews as you move around an
  ;; auto-updating embark collect buffer
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))
```

Should we auto-load `consult-preview-at-point-mode`?

**Comment by oantolin** [comment]
You can just wait until Consult is loaded to add the hook:

```elisp
(with-eval-after-load 'consult
  (add-hook 'embark-collect-mode-hook #'consult-preview-at-point-mode))
```

**Comment by minad** [comment]
@salutis What I don't understand here - doesn't :hook generate an automatic `autoload` if it does not exist yet? See https://jwiegley.github.io/use-package/keywords/

**Comment by minad** [comment]
Closing, `consult-preview-at-point-mode` and `consult-preview-at-point` aren't sensible entry points to the Consult package. A Consult command must first.

**Comment by salutis** [comment]
> @salutis What I don't understand here - doesn't `:hook` generate an automatic `autoload` if it does not exist yet? See https://jwiegley.github.io/use-package/keywords/.

I apologize for the lack of clarity. I do not use `use-package`. The plain old `add-hook` fails, which surprised me. I thought I would ask before adding `with-eval-after-load` to my config.
