### ISSUE TITLE
consult line doesn't search ampersand 

### ISSUE THREAD

**Issue by natask** [minad/consult#498]
searching for `&` within a file using consult line doesn't narrow down to lines that contain "&". 

# Test
- create new buffer
- copy the following into the buffer
```
& doesn't narrow
second line 
third line
```
- run `consult-line` and enter `&` in the prompt.
expect that only the first line matches but all lines match.

**Comment by minad** [comment]
Check your completion styles. See https://github.com/minad/consult#bug-reports.
