### ISSUE TITLE
consult-locate-args default value using regexp does not work with GNU locate on Ubuntu

### ISSUE THREAD

**Issue by jayrajput** [minad/consult#499]
I see that argument regexp is used as default argument for consult-locate-args which causes the consult-locate to fail on my system using Ubuntu as locate argument should be regex (and not regexp). I am not sure if regexp is a typo, or a valid option applicable to some other setup. The error is also cryptic saying "Match Required" giving an impression that there are no files with that regex. 

https://github.com/minad/consult/blob/b33cb2ef098b0f212d035e2677afdd7f04340765/consult.el#L256

**Comment by oantolin** [comment]
This probably yet another example of younger programs failing to use Emacs's established terminology. 😛

**Comment by minad** [comment]
We should probably remove `consult-locate` if such issues are not found for a long time. Not many people seem to use it.

**Comment by thdox** [comment]
On latest debian stable (bullseye), I had to set consult-locate-args to "plocate --ignore-case" to make it work. Indeed, this is plocate that is installed by default, and the plocate 1.1.8 do not have --existing option. 
If I do not do it, I get the error "Match Required" that was cryptic to me.
