### ISSUE TITLE
Use affixation-function metadata if possible?

### ISSUE THREAD

**Issue by minad** [minad/consult#5]
Allows prefix and suffix annotations in Emacs 28. This will help us avoid the 'display prefix hack. See also #4.

**Comment by Hugo-Heagren** [comment]
I know this is closed, but would just like to say this would be really useful for me and my [project](https://github.com/Hugo-Heagren/consult-emms)!

**Comment by minad** [comment]
This is an old issue. The `:annotate` function of `consult--read` supports both annotations and affixations by now depending on if you return a string or a list. See `consult--line-prefix` for the affixation function used by `consult-line`, which displays the line numbers.
