### ISSUE TITLE
consult-async: Refresh support for Mct

### ISSUE THREAD

**Issue by minad** [minad/consult#501]
We should provide a `consult--completion-refresh-hook` for Mct, see:

https://github.com/minad/consult/blob/0127b52a97da30e30fea9605cf8f7e156052f366/consult-icomplete.el#L52

cc @protesilaos @jaor

**Comment by protesilaos** [comment]
> We should provide a `consult--completion-refresh-hook` for Mct, see:
>
> https://github.com/minad/consult/blob/0127b52a97da30e30fea9605cf8f7e156052f366/consult-icomplete.el#L52
>
> cc @protesilaos @jaor

Thank you!  Beside the Icomplete-specific forms, this looks like it
would work without any further tweaks.  Though I am wondering...  Is
acceptable to just call `minibuffer-completion-help'?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
> Thank you!  Beside the Icomplete-specific forms, this looks like it
> would work without any further tweaks.  Though I am wondering...  Is
> acceptable to just call `minibuffer-completion-help'?

This is what I had in mind (may need some further tweaks):

    (defun consult-mct--refresh ()
      (unless (or (null mct-live-completion)
                  (memq (mct--this-command) mct-completion-blocklist))
        (minibuffer-completion-help)))

    (add-hook 'consult--completion-refresh-hook #'consult-mct--refresh)


-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
What about this? You introduce a single function `mct--live-completions-refresh` and apply the following patch to Mct?

~~~ diff
From cd33fb4ee93f4ae8dc4e3c360e8a581b0e1f7d91 Mon Sep 17 00:00:00 2001
From: Daniel Mendler <mail@daniel-mendler.de>
Date: Fri, 21 Jan 2022 05:21:47 +0100
Subject: [PATCH] Introduce mct--live-completions-refresh

The function is used as `after-change-function'. Furthermore it can be called
asynchronously from outside of Mct, e.g., by asynchronous Consult commands like
`consult-grep'.
---
 mct.el | 39 +++++++++++++++++++++------------------
 1 file changed, 21 insertions(+), 18 deletions(-)

diff --git a/mct.el b/mct.el
index 18a340f..8e8883f 100644
--- a/mct.el
+++ b/mct.el
@@ -265,9 +265,8 @@ See `mct-minimum-input'."
 
 ;; Adapted from Omar Antolín Camarena's live-completions library:
 ;; <https://github.com/oantolin/live-completions>.
-(defun mct--live-completions (&rest _)
-  "Update the *Completions* buffer.
-Meant to be added to `after-change-functions'."
+(defun mct--live-completions-refresh-immediately ()
+  "Update the *Completions* buffer immediately."
   (when (minibufferp) ; skip if we've exited already
     (while-no-input
       (if (or (mct--minimum-input)
@@ -283,19 +282,25 @@ Meant to be added to `after-change-functions'."
 (defvar mct--timer nil
   "Latest timer object for live completions.")
 
-(defun mct--live-completions-timer (&rest _)
-  "Update Completions with `mct-live-update-delay'."
-  (when-let* ((delay mct-live-update-delay)
-              ((>= delay 0)))
+(defun mct--live-completions-refresh (&rest _)
+  "Update the *Completions* buffer with a delay.
+Meant to be added to `after-change-functions'."
+  (when (and
+         ;; Check that live completions are enabled by looking at
+         ;; after-change-functions. This check is needed for Consult
+         ;; integration, which refreshes the display asynchronously.
+         (memq #'mct--live-completions-refresh after-change-functions)
+         ;; Update only visible completion windows?
+         (or (not (eq mct-live-completion 'visible))
+             (window-live-p (mct--get-completion-window))))
     (when mct--timer
       (cancel-timer mct--timer)
       (setq mct--timer nil))
-    (setq mct--timer (run-with-idle-timer delay nil #'mct--live-completions))))
-
-(defun mct--live-completions-visible-timer (&rest _)
-  "Update visible Completions' buffer."
-  (when (window-live-p (mct--get-completion-window))
-    (mct--live-completions-timer)))
+    (if (> mct-live-update-delay 0)
+        (setq mct--timer (run-with-idle-timer
+                          mct-live-update-delay
+                          nil #'mct--live-completions-refresh-immediately))
+      (mct--live-completions-refresh-immediately))))
 
 (defun mct--this-command ()
   "Return this command."
@@ -304,16 +309,14 @@ Meant to be added to `after-change-functions'."
 (defun mct--setup-live-completions ()
   "Set up the completions' buffer."
   (cond
+   ((null mct-live-completion))
    ((memq (mct--this-command) mct-completion-passlist)
     (setq-local mct-minimum-input 0)
     (setq-local mct-live-update-delay 0)
     (mct--show-completions)
-    (add-hook 'after-change-functions #'mct--live-completions nil t))
-   ((null mct-live-completion))
+    (add-hook 'after-change-functions #'mct--live-completions-refresh nil t))
    ((not (memq (mct--this-command) mct-completion-blocklist))
-    (if (eq mct-live-completion 'visible)
-        (add-hook 'after-change-functions #'mct--live-completions-visible-timer nil t)
-      (add-hook 'after-change-functions #'mct--live-completions-timer nil t)))))
+    (add-hook 'after-change-functions #'mct--live-completions-refresh nil t))))
 
 (defvar-local mct--active nil
   "Minibuffer local variable, t if Mct is active.")
-- 
2.20.1
~~~

This way we reduce the moving parts between Mct and Consult to a minimum. I would prefer this, since everything will just continue to work even if you make changes to Mct, and no Mct internals are accessed here, besides the single function. Since Mct just uses default completion, no further integration code is needed besides:

~~~ elisp
(add-hook 'consult--completion-refresh-hook #'mct--live-completions-refresh)
~~~

**Comment by protesilaos** [comment]
On 2022-01-20, 20:27 -0800, Daniel Mendler ***@***.***> wrote:

> What about this? You introduce a single function
> `mct--live-completions-refresh` and apply the following patch to Mct?

Thank you!  Applied it.

> This way we reduce the moving parts between Mct and Consult to a
> minimum. I would prefer this, since everything will just continue to
> work even if you make changes to Mct, and no Mct internals are
> accessed here, besides the single function.

Yes, this is better.

> Since Mct just uses default completion, no further integration code is
> needed besides:
>
> ~~~ elisp
> (add-hook 'consult--completion-refresh-hook #'mct--live-completions-refresh)
> ~~~

Should we include this hook in the documentation then?  Or there will
still be a consult-mct.el with just it?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
Since the integration is barely more than a single line, I added it to consult.el. The fboundp check go away in the future.

**Comment by protesilaos** [comment]
> Since the integration is barely more than a single line, I added it to
> consult.el.

That was quick.  Thanks!

> The fboundp check go away in the future.

I just pushed version 0.4.1 to trigger the rebuild.  Now we wait.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
>> The fboundp check go away in the future.
>
> I just pushed version 0.4.1 to trigger the rebuild.  Now we wait.

The new version is available: <https://elpa.gnu.org/packages/mct.html>.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by minad** [comment]
Thanks!

**Comment by jaor** [comment]
just a quick note that mct live refreshing for async consult is working
for me with this change too.  thanks!
