### ISSUE TITLE
search through previous history of eval-expression

### ISSUE THREAD

**Issue by titaniumbones** [minad/consult#505]
I may be remembering this wrong, but I thought I had previously had a way to search through the history of `eval-expresison` (`M-:`). Now, however, if I try e.g. `consult-line` (`C-r`) I get a message

```
consult--forbid-minibuffer: ‘consult-line’ called inside the minibuffer
```
I am clearly doing something wrong. Is it possible for me to search through my history while in the minibuffer?

**Comment by minad** [comment]
The problem is that you have bound C-r to `consult-line`. I recommend to keep the Isearch bindings (C-s and C-r) and bind `consult-line` to M-s r (or alternatively C-c c l).

**Comment by titaniumbones** [comment]
thank you, this is very helpful.  I have just added 
```lisp
:map minibuffer-mode-map
         ("C-s" . isearch-forward)
         ("C-r" . isearch-backward)
```
to my consult `use-package declaration and the issue is fixed.

How though I wish I could send the isearch results to corfu and use embark-export.  I know I'm asking here in the wrong package, but would that already be possible?  I am somewhat new to corfu and embark.

**Comment by minad** [comment]
You can use `occur` to turn isearch into a buffer. This is built-in functionality.

**Comment by oantolin** [comment]
You can also use `consult-history` to search through history with completion. I bind it in `minibuffer-local-map`. You can run `embark-collect-snapshot` from the `consult-history` prompt.

**Comment by minad** [comment]
Ah, I misunderstood. To search or export the history you should use consult-history as mentioned by @oantolin.

**Comment by minad** [comment]
Since you also mentioned Corfu, I have this in my configuration (added to the `completion-at-point-functions` or added to a separate key (C-c p h):

~~~ elisp
  (defun +cape-history (&optional interactive)
    (interactive (list t))
    (if interactive
        (cape--interactive #'+cape-history)
      (when-let (history (ignore-errors (consult--current-history)))
        (list (point) (point) (cape--table-with-properties history :sort nil)))))
~~~

This function could be part of [Cape](https://github.com/minad/cape), but it currently isn't since it uses `consult--current-history` and I don't want to duplicate this function and its configuration in Consult and Cape.
