### ISSUE TITLE
consult-buffer error: consult--source-file is neither a Consult command nor a Consult source

### ISSUE THREAD

**Issue by moonpole** [minad/consult#508]
I'm using Purcell's emacs.d config (https://github.com/purcell/emacs.d). After updated Emacs packages today, the command `consult-buffer` will not work. Emacs shows an error: `consult--source-file is neither a Consult command nor a Consult source`

I also called `consult-imenu`, it shows the same error. Restart Emacs and reinstall consult package will no help.

Work around:

1. call `consult-imenu`, Emacs will show the same error
2. then `consult-line` and `consult-buffer` work as expected

My Emacs version is: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2021-01-18, modified by Debian
OS: Ubuntu 21.10

BTW, I don't know how to display useful logs.

**Comment by minad** [comment]
Yes, the source has been renamed/deprecated. It is now called consult--source-project-file. 

The problem is the line https://github.com/purcell/emacs.d/blob/72715575f08cbee7651b4e318321854a4385f7e9/lisp/init-minibuffer.el#L31.

**Comment by moonpole** [comment]
> Yes, the source has been renamed/deprecated. It is now called consult--source-recent-file.
> 
> The problem is the line https://github.com/purcell/emacs.d/blob/72715575f08cbee7651b4e318321854a4385f7e9/lisp/init-minibuffer.el#L31.

Thanks :)
