### ISSUE TITLE
`consult-locate-args` does not work under macOS Big Sur

### ISSUE THREAD

**Issue by stardiviner** [minad/consult#511]
The default `consult-locate-args` is `"locate --ignore-case --existing --regex"`. But it does not work under macOS. macOS command `locate` does not have those options. I suggestion to use a smart condition.

```elisp
(setq consult-locate-args (pcase system-type
                                       ('gnu/linux "locate --ignore-case --existing --regex")
                                       ('darwin "locate -i")))
```

**Comment by minad** [comment]
You can configure consult-locate-args in your user configuration. Consult assumes the gnu version of locate. I've also heard that on Mac you may want to use mdfind instead?

**Comment by stardiviner** [comment]
I see. Thanks for suggestion.
