### ISSUE TITLE
`consult-org-heading` - do not disable sorting

### ISSUE THREAD

**Issue by contrapunctus-1** [minad/consult#514]
The call to `consult--read` in `consult-org-heading` has `:sort nil` , which disables sorting. I greatly preferred the behavior of commands like `imenus` - a flat list of headings[^1] in the buffer, sorted by history, with the result that frequently my desired candidate would just be in the top 3 choices without even typing anything.

Removing `:sort nil` made the command behave as I like. If disabling sorting is desired by others, perhaps they could configure it via `vertico-multiform` ? With `:sort nil`, even my `vertico-multiform-commands` setting (`(consult-org-heading (vertico-sort-function . vertico-sort-history-length-alpha))`) was ignored :confused: 

[^1]: Unfortunately `imenus` only shows terminal headings rather than all headings, which I don't like, and is fortunately not the case with `consult-org-heading`.

**Comment by minad** [comment]
Use `consult-customize`, see https://github.com/minad/consult#fine-tuning-of-individual-commands.

**Comment by contrapunctus-1** [comment]
Thanks. I'm not entirely sure how `:sort` behaves - I've tried `(consult-customize consult-org-heading :sort t)` (with the `vertico-multiform-commands` config above) as well as `(consult-customize consult-org-heading :sort #'vertico-sort-history-length-alpha)` ...but the candidates (before I type anything) are still sorted by their order in the file. The sorting seems to be happening after I start typing.

Is there any way to get `consult-org-heading` candidates sorted using `vertico-sort-history-length-alpha` before one types anything i?

**Comment by minad** [comment]
`(consult-customize consult-org-heading :sort t)` works for me.
