### ISSUE TITLE
Consult register actions (M-p, M-w, ...) do not work in terminal

### ISSUE THREAD

**Issue by Ergus** [minad/consult#518]
Hi:

Recently I found that Modified keys are not working in consult properly when using emacs form the terminal (-nw).

Commands like `consult-register-save` receive `w` instead of `M-w`, `f` instead of `M-f` and so on. Before I had ivy and it worked properly; and xterm is sending the right bindings because the rest of emacs gets them.  And when I do `M-x C-h k M-w` it shows the help for `M-w`... so this seem to be something specific in Consult??? BTW I use `Vertico` in case you need to know.

Thanks in advance, Ergus

**Comment by oantolin** [comment]
The problem is that graphical Emacs and terminal Emacs read `M-w` differently: in graphical Emacs if you evaluate `(read-key)` and press `M-w` you get `#x8000077`, which is `?w = #x77` plus a modifier of `#x8000000` which consult `xor`s off; but in terminal Emacs `M-w` is actually two separate keys: first `ESC`, i.e., `27`, and then `?w = #x77`. It shouldn't be too hard to test for `ESC` and if found read a second character.

**Comment by minad** [comment]
> shows the help for M-w... so this seem to be something specific in Consult

Yes, this is a Consult feature.

@oantolin is right that there is an issue with regards to the interpretation of the keys. PR welcome which fixes this. I am personally not using terminal Emacs very much.

**Comment by Ergus** [comment]
As I am new in consult I thought that this was less critical.. I just figured out that this also affects the preview key as expected... which is actually more critical for common day use.

**Comment by minad** [comment]
> I just figured out that this also affects the preview key as expected

Which preview key? For candidate preview. It should also be possible to configure another key which works in the terminal. But ideally we get this fixed such that keys like `M-.` work in terminal too.

**Comment by oantolin** [comment]
I did the simplest thing I could imagine: if read-key returns 27 and last-input-event is a character, pretend last-input-event is `#x8000000` plus the character. It seems to work in the terminal without changing the behavior in graphical Emacs but maybe needs a little more testing.

**Comment by Ergus** [comment]
> I did the simplest thing I could imagine: if read-key returns 27 and last-input-event is a character, pretend last-input-event is `#x8000000` plus the character. It seems to work in the terminal without changing the behavior in graphical Emacs but maybe needs a little more testing.

Hi:

I just see the change, very thanks but the problem with that is that this does not solve the issue in general. As I just said using `M-.` for preview doesn't work either..  
What you did actually may be simpler with `read-key-sequence-vector` but maybe it is not even needed the when condition using the `read-key-sequence` directly to bind....
What do you think?

**Comment by minad** [comment]
@Ergus These issues are unrelated. @oantolin fixed `consult-register-load/save` actions in #520. For candidate preview we need a separate fix.

**Comment by oantolin** [comment]
Oh, I finally understood! @Ergus doesn't mean preview *for* `consult-register-save` (which is hard coded to be triggered by help-char and *does* work in the terminal!), but means instead preview in other Consult commands that use a configurable preview key! I was very confused. 😅

**Comment by Ergus** [comment]
> Oh, I finally understood! @Ergus doesn't mean preview _for_ `consult-register-save` (which is hard coded to be triggered by help-char and _does_ work in the terminal!), but means instead preview in other Consult commands that use a configurable preview key! I was very confused. sweat_smile

My apology for my bad explication... Should I open a new issue then?

**Comment by minad** [comment]
@Ergus Yes, please create a separate issue.
