### ISSUE TITLE
`M-.` does not work as preview key (Terminal Emacs)

### ISSUE THREAD

**Issue by Ergus** [minad/consult#521]
Hi:

When using `(setq-default consult-preview-key (kbd "M-."))` on emacs terminal (-nw) it just doesn't work. It seems like `M-.` is well captured but emacs, but not  processed by consult.

`C-h b` shows:  `M-.		ignore`

**Comment by oantolin** [comment]
Oh, I think the only problem here is that `(kbd "M-.")` returns specifically the key sequence for _graphical Emacs_! If you use `(setq-default consult-preview-key (kbd "ESC ."))` instead it works fine in the terminal.

**Comment by oantolin** [comment]
And I think the preview key can actually be a list, so `(setq-default consult-preview-key (list (kbd "M-.") (kbd "M-.")))` should work in both graphical and terminal Emacs.

**Comment by oantolin** [comment]
Slightly off-topic but these pair of issues have made me wonder if I should pick more terminal-friendly key bindings. I felt really lost in the terminal because several of my most used key bindings don't work there.

**Comment by Ergus** [comment]
> Oh, I think the only problem here is that `(kbd "M-.")` returns specifically the key sequence for _graphical Emacs_! If you use `(setq-default consult-preview-key (kbd "ESC ."))` instead, then it works fine in the terminal.

Hi:

I still think there is a more fundamental issue. `(kbd "M-.")` is a very standard function and if it doesn't work cleanly then there is a problem somewhere else. The users may not be exposed to this kind of tricks.

**Comment by oantolin** [comment]
I guess you could call it a bug in `kbd`, then. It's not really Consult's fault that `M-x (read-key-sequence nil) RET M-.` does *not* return the same thing as `(kbd "M-.")` in terminal Emacs!

**Comment by minad** [comment]
Hmm, but it wouldn't be a good idea to have different kbd results for terminal and ui. The problem is that Consult accesses the primitive keyboard events, so we could also normalize this there?

**Comment by Ergus** [comment]
> I guess you could call it a bug in `kbd`, then. It's not really Consult's fault that `M-x (read-key-sequence nil) RET M-.` does _not_ return the same thing as `(kbd "M-.")` in terminal Emacs!

Actually not. Emacs handles such situations throw the translation maps... I don't really know why consult is different.

**Comment by oantolin** [comment]
Oh, here's a fix: change the key comparison in `consult--preview-key-pressed-p` from `(equal (vconcat (car x)) keys)` to

```elisp
(lookup-key `(keymap (,(vconcat (car x))  . ignore)) keys)
```

That does the same type of comparison normal key bindings use.

**Comment by oantolin** [comment]
(You could of course also make a single keymap with all the normalized preview keys and use a single `lookup-key` call instead.)

**Comment by oantolin** [comment]
I think the lookup-key fix is probably good enough.

**Comment by Ergus** [comment]
> Oh, here's a fix: change the key comparison in `consult--preview-key-pressed-p` from `(equal (vconcat (car x)) keys)` to
> 
> ```emacs-lisp
> (lookup-key `(keymap (,(vconcat (car x)) . ignore)) keys)
> ```
> 
> That does the same type of comparison normal key bindings use.

This actually seems like a more canonical solution....  if preview-key had a keymap format, we don't really need any comparison. `lookup-key` may do the work out of the box...
