### ISSUE TITLE
Make consult-ripgrep selection expand full width of minibuffer

### ISSUE THREAD

**Issue by zwpdbh** [minad/consult#523]
Currently, when I use consult-ripgrep works great. 

But when I move selection, the visual effect is not easy to notice for some theme. 
If the selection in the minibuffer could be configured to expand full width, that will solve this problem. 
Right now, the selection in the minibuffer only has the same length as the candidate's. 

Is there any configuration to make selection highlight-background expand full width of the minibuffer?

**Comment by minad** [comment]
Closing since this is a theming issue. Please open an issue on the theme repository. I recommend the [modus-themes](https://protesilaos.com/emacs/modus-themes), which display Vertico, Consult, etc. correctly and also support many other packages.
