### ISSUE TITLE
consult--source-recentf-file couldn't filter files which have been opend

### ISSUE THREAD

**Issue by liuyinz** [minad/consult#524]
```elisp
(defvar consult--source-recent-file
  `(:name     "File"
    :narrow   ?f
    :category file
    :face     consult-file
    :history  file-name-history
    :state    ,#'consult--file-state
    :enabled  ,(lambda () recentf-mode)
    :items
    ,(lambda ()
       (let ((ht (consult--buffer-file-hash))
             (filter (consult--regexp-filter consult-recent-file-filter)))
         (mapcar #'abbreviate-file-name
                 (seq-remove (lambda (x)
                               (or (gethash x ht)
                                   (and consult-recent-file-filter (string-match-p filter x))))
                             recentf-list)))))
  "Recent file candidate source for `consult-buffer'.")
```
When I setting like this:
```elisp
 (add-to-list 'recentf-filename-handlers 'abbreviate-file-name)
```
`recentf-list` return paths which starts with "~", and in `consult--source-recentf-file`, ` (gethash x ht)` would faile to filter opened file.how could I fix this?

**Comment by minad** [comment]
> how could I fix this?

You can adjust the `consult--buffer-file-hash` via an advice to additionally add the abbreviated names to the full names. Then you can be sure that nothing breaks and abbreviated names are filtered out too. Alternatively replace the `:items` value of `consult--source-recent-file` with a lambda which uses gethash on the expanded file name, ee `expand-file-name`. Does this answer your question?

**Comment by liuyinz** [comment]
Thanks!

**Comment by minad** [comment]
I thought a while about this and I don't really see a good solution. Using canonical/expanded file names for the recentf-list is the best solution. This means that users should set the handlers to nil in their configuration - this is also the more efficient solution. The only downside is that sharing your recentf-list across multiple hosts won't work. In that case one could use separate lists recentf-list-host1, recentf-list-host2, ...

~~~ elisp
(setq recentf-filename-handlers nil)
~~~

**Comment by wdkrnls** [comment]
On Emacs 28.2 this same block of code is failing for me with the result that the consult-buffer cannot see my recentf files. I copied the function into my init.el and commented out the hash table business to make it work correctly like the dedicated recentf interfaces.
