### ISSUE TITLE
consult-ripgrep highlighting wrong when not using --smart-case

### ISSUE THREAD

**Issue by luveti** [minad/consult#525]
I have `consult-ripgrep-args` set to the following:
`rg --null --line-buffered --color=never --max-columns=1000 --path-separator / --no-heading --line-number .`

Given the following source code in `test.js`:

```js
function doSomethingWithFoo(foo) {
	console.log(foo)
}
```

Running `consult-ripgrep` shows the following:

![image](https://user-images.githubusercontent.com/4952718/155465433-755aab12-4b26-4a50-aafd-d705ca34db57.png)

While ripgrep itself shows the following when running:

`rg --line-buffered --max-columns=1000 --path-separator / --no-heading --line-number --hidden foo`

![image](https://user-images.githubusercontent.com/4952718/155465809-50252cfe-7662-445b-8c55-9df883db441f.png)

**Comment by minad** [comment]
Thanks, that's a good find!
