### ISSUE TITLE
About commit d0261c0

### ISSUE THREAD

**Issue by Ergus** [minad/consult#527]
Hi:

I see that the comment in that commit says that `add-hook` is broken in emacs 28 (which is intended to release soon...) could you please report the issue or mention what's wrong and I will report it as soon as possible??

**Comment by minad** [comment]
No worries, I am continuously exchanging mails with Stefan Monnier. If you monitor the Emacs 29 development branch, there should be a recent change to the hook infrastructure.

**Comment by minad** [comment]
No it is an issue of all Emacsen < 29. My commit message was unclear.
