### ISSUE TITLE
counsel-xref breaks dired-do-find-regexp-and-replace

### ISSUE THREAD

**Issue by martenlienen** [minad/consult#528]
Hey,
thanks a lot for this great package! One thing I have noticed several times and decided to investigate today is that counsel-xref breaks dired-do-find-regexp-and-replace (what is bound to `S-q` by default in dired). Usually, it would show you the matches one after another and ask if you want to replace it (and more things). With counsel-xref I just get shown a list of the matches which I can then pick one of to jump to. This of course, defeats the whole purpose of the command. I think this problem could be related to [this issue with ivy-xref](https://github.com/alexmurray/ivy-xref/issues/2).

My current workaround is just not to set `counsel-xref` as my `xref-show-xrefs-function`, but maybe there is a better way?

Best,
Marten

**Comment by minad** [comment]
Wrong repository? See https://github.com/abo-abo/swiper.

**Comment by martenlienen** [comment]
Sorry, I mixed them up because I used ivy and swiper before switching to consult, selectrum etc. I have fixed the issue title and description. So the problem actually occurs with `consult-xref`.

**Comment by minad** [comment]
I miss some information here, see https://github.com/minad/consult#bug-reports. I don't observe issues with `consult-xref` and `dired-do-find-and-regexp-and-replace`. But I use Emacs 28 which comes with a recent version of xref.el. Therefore I suspect that this is a bug of xref.el. If you use Emacs 27 you should upgrade to a newer version of xref.el from ELPA. Please try the following: Start emacs -Q, use the newest consult from ELPA (or MELPA), the newest xref from ELPA and then check if the problem persists.
