### ISSUE TITLE
'consult-project-root-function' internal usage incompatible with suggested config

### ISSUE THREAD

**Issue by woolsweater** [minad/consult#529]
[`consult-project-root-function` was recently "brought back"](https://github.com/minad/consult/commit/94224d0f91c6eddb073c812805ea3f7eaf7ed458). In that commit the sample configuration also restored the suggestion to use `projectile-project-root` (among other options).

However, a following commit [to add a prompt](https://github.com/minad/consult/commit/aa93dca652daa48c243100e1d3c8367c27e2eced) made that suggestion incorrect. `projectile-project-root` does take 1 argument, but it expects a directory, not the [`maybe-prompt` flag that is actually passed](https://github.com/minad/consult/commit/aa93dca652daa48c243100e1d3c8367c27e2eced#diff-f5a84ba2f501aa963898f4185aece1ea6eba0c084be8ed36ac936b2a30dc8017R860). This causes a type error when invoking a command like `consult-project-buffer` when `consult-project-root-function` is set to `projectile-project-root`.

I think this is just a documentation issue; easily fixed. Although it was nice to be able to use `projectile-project-root` directly as the `consult-project-root-function`, rather than having to wrap it to catch the flag.

**Comment by minad** [comment]
Oh, that's unfortunate. I had hoped there is a seamless upgrade path. I will introduce an improved error message and improve the documentation.

**Comment by woolsweater** [comment]
Sounds good, thank you!
