### ISSUE TITLE
Run hook on previewing buffer

### ISSUE THREAD

**Issue by northgaard** [minad/consult#535]
Hi, and thanks for this excellent package!

Would it be feasible to add a hook variable that would be run on previewing buffers, ideally with the previewed buffer passed to the hook functions, so that on could inspect things like active minor modes and what not.

My intended use case is that I use the built-in which-func mode to show the function containing point in the mode line, but it does not update when previewing files with consult-xref, which would be quite useful. (Unfortunately, at $job, very long functions are quite common.) If there was a hook variable it would be a simple matter to force an update when previewing buffers.

What do you think?

**Comment by minad** [comment]
There is already the `consult-after-jump-hook`. Does that work for you?

**Comment by northgaard** [comment]
Huh, I don't know why I didn't come across this when searching for consult hooks. That works like a charm, my apologies for the noise!
