### ISSUE TITLE
Question: How to tweak the sorting of buffers in `consult-buffer`?

### ISSUE THREAD

**Issue by indigoviolet** [minad/consult#536]
I was unable to figure this out from the documentation - I see functionality for grouping and narrowing,  but  wasn't able to find how to specify sort order with `consult` + `vertico` (for which my config is currently the default provided by doom emacs).

**Comment by minad** [comment]
You can change the order of the sources, see consult-buffer-sources. Besides that you can adjust the sorting of each source individually, by overwriting the :items function of the source. Is there something else you have in mind? What do you want to achieve precisely?

**Comment by minad** [comment]
Closing. Please let me know if you have further questions or improvement proposals!

**Comment by indigoviolet** [comment]
Sorry to come back to this after so much time -- I use consult-buffers to switch buffers, but the sort order in my experience is not clear to me: I'd like it to be based on frecency or recency. The breakdown by buffer/file also mostly doesn't add anything: when I'm switching buffers or opening files, I don't find that a useful slicing. I'm surprised that this is not a more common complaint, am I using it incorrectly or missing some configuration?

(as always, thank you for the work on these packages, they are awesome -- specific feedback is not reflective of my overall sentiment)

**Comment by minad** [comment]
You can also try `(consult-customize consult-buffer :sort t :group nil)`. But besides that I cannot help you. I think `consult-buffer` works well as is for most users and most users value the buffer/file/other sources distinction. You could also decide to not use `consult-buffer` and just rely on plain `switch-to-buffer`. All the commands are optional.

**Comment by oantolin** [comment]
It sounds like you _read_ the list of candidates that `consult-buffer` produces, @indigoviolet. I don't! I usually don't even look at it until after I've typed 2 or 3 letters. By then, very often the buffer I want is being previewed, so I just press `RET` without ever having glanced at the minibuffer! If after 2 or 3 letter the buffer being previewed is not the one I want, then I look at the minibuffer where there are often only a few candidates left. I sometimes use the arrow keys to select the one I want, I sometimes type a little more to narrow further.

**Comment by hmelman** [comment]
I suspect disabling grouping as @minad suggests will satisfy you.

    (consult-customize consult-buffer :sort t :group nil)

I think it would be good to put the above explicitly in the README in the "Narrowing and grouping" section as an example.

If you use Marginalia you might also want a less detailed annotation function so the candidates look more uniform (or you may prefer the visual distinction to indicate the type of candidate)..

I think it's a perfectly reasonable config.  You get the benefit of the other `consult-buffer` sources with a single recency sort.  I agree with @oantolin that typing more to narrow the candidates is a good habit to get into, but particularly with code, files often have similar names, so sorting can help (so can using a `completion-style` that makes it easy to enter a file extension).  I used this for a while and recently re-enabled grouping.  I like the way grouping looks but I like the way a non-grouping behaves, at least intellectually, in practice I'm not noticing a huge difference, but I'm not working on projects with many similarly named files.

**Comment by minad** [comment]
I forgot to mention - if you use Vertico you can also override the sort function per command or per completion category via `vertico-multiform-mode`, see https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category. But you still have to disable grouping if you want the groups to mix `(consult-customize consult-buffer :group nil)`.

**Comment by indigoviolet** [comment]
Thanks for all your advice. I put together https://github.com/indigoviolet/vi-consult-buffers/blob/main/vicb.el, which I can further customize for my needs. It is probably overkill for what I'm doing, but I haven't written any elisp prior to this, so a lot of it is just me doing more for the heck of it.
