### ISSUE TITLE
Stupid question - save-mode and consult-buffer not playing nice when it comes to my org file (always goes to the top if browsed with consult-buffer)

### ISSUE THREAD

**Issue by servytor** [minad/consult#541]
So I am using save-mode, and I assume it is doing it's job competently. But in this case, I do not know what is going on. I have a 2000 line org-mode file, and if I browse buffers and select it to open (and it has not been opened) it defaults to going to the top of the org file. If I open it via C-x C-f it goes to the right place like normal. I think this can be solved with advice and calling a private non-exported function, #'save-place-find-file-hook, but I am bad at programming.

Am I the only one suffering this, and it's my config? Or is this something other people have encountered as well?

Thank you so much for working on something like this. I really appreciate how fast and fully featured your projects are, and they achieve exactly what I have been looking for in Emacs. Thank you!

**Comment by minad** [comment]
Duplicate #465. save-place-mode has a bug.

**Comment by minad** [comment]
See https://github.com/minad/consult/issues/465#issuecomment-1002588067 for a workaround.

**Comment by servytor** [comment]
Thank you, that code fixed my problem.
