### ISSUE TITLE
consult-buffer: No applicable method: project-root

### ISSUE THREAD

**Issue by ghowoo** [minad/consult#543]
I am trying consult and it works well on my Windows machine. However, on my Linux machine, consult-buffer doesn't work:

"No applicable method: project-root, (vc . "~/folder/subfolder/")"

Meanwhile, other consult functions work well such as consult-line consult-goto-line.

Could you point out a way to solve the problem? Thanks for help.

**Comment by minad** [comment]
I assume that your project.el version is outdated. You can install the newest project.el package from GNU ELPA to fix the issue. If you use Emacs 28 or 27 I think it should also work well out of the box.

If this doesn't work you can disable the project integration

~~~ elisp
(setq consult-project-function nil)
~~~

or use a different project function as described in the README. See https://github.com/minad/consult#use-package-example.

**Comment by ghowoo** [comment]
Thanks for the prompt response. Adding the line (setq consult-project-function nil) works.

Updating project.el seems no working and I may have other issues with the updated project. I am using Emace 27.1.
