### ISSUE TITLE
How to asynchronously get candidates using an Elisp function?

### ISSUE THREAD

**Issue by rdrg109** [minad/consult#544]
# Prologue

I've been getting more familiar with consult and I've been able to come up with this minimal working example (see code block below) which asynchronously generates candidates by using the `seq` command line tool. If the user types 100, then the candidates are the numbers from 1 to 100. If, during the same prompt, the user inserts 1000, then the candidates are the numbers between 1 to 1000.

When the last sexp, the `let` sexp is evaluated then the completion list that I've described above is shown.

```elisp
(defun my/consult--format (lines)
  (let ((candidates))
    (save-match-data
      (dolist (str lines)
        (when (string-match "\\`\\([0-9]+\\)\\'" str)
          (let ((number (match-string 1 str)))
            (push number candidates)))))
    (nreverse candidates)))

(defun my/consult--builder (input)
  (list :command (list "seq" "1" input)))
```
```elisp
;; For experimentation purposes, consult-async-min-input has been set
;; to 1, thus the command, that is used for generating the candidates,
;; is executed even when inserting 1-digit numbers.

(let ((consult-async-min-input 1))
  (consult--read
   (consult--async-command #'my/consult--builder
     (consult--async-transform my/consult--format))))
```

As we can see above, the candidates are obtained from an external command (in this case, we are using `seq`). Now, I'm interested in knowing how to do this by not using external commands (i.e. just Emacs Lisp functions).

# The question

How to asynchronously get candidates from an Emacs Lisp function so that they can be shown in the prompt shown by `consult--read`?

The function shown below does the same that `seq` does: generates a sequence of number from 1 to any number, so under this scenario, my question can be understood as: How I could use this function to asynchronously show candidates in the completion list?

```elisp
(defun my/function (input)
  (number-sequence 1 input))
```

# Additional context

Please note that my question on using `my/function`  is a minimal working example. Actually, I want to do the same for a function that retrieves information of an API by using the `request.el` package, but I didn't mention it so that the question is easier to analyze and answer.

The function that I want to use is shown below. It retrieves information from an API and format it as a property list.

```elisp
(defun wikidata-fetch (input)
  "Fetch suggestions for INPUT from XML buffer."
  (when (and input (not (equal input "")))
    (request-response-data
     (request "https://www.wikidata.org/w/api.php"
       :sync t
       :params `(("action" . "wbsearchentities")
                 ("search" . ,input)
                 ("format" . "xml")
                 ("errorformat" . "plaintext")
                 ("type" . "item")
                 ("language" . "en")
                 ("uselang" . "en")
                 ("limit" . "5"))
       :parser (lambda ()
                 (cl-loop
                  with result-alist = (xml-get-children
                                       (assq 'search
                                             (cdar
                                              (xml-parse-region (point-min) (point-max))))
                                       'entity)
                  for i in result-alist collect
                  (list
                   'id
                   (alist-get 'id (cadr i))
                   'label
                   (alist-get 'label (cadr i))
                   'description
                   (alist-get 'description (cadr i)))))))))
```

```
ELISP> (wikidata-fetch "foss")
((id "Q506883" label "free and open-source software" description "software that is both free (as in freedom) and open-source")
 (id "Q16870001" label "Foss" description "family name")
 (id "Q2735700" label "Foss" description "human settlement in Washita County, Oklahoma, United States of America")
 (id "Q344945" label "Foss" description "Wikimedia disambiguation page")
 (id "Q40614" label "fossil" description "preserved remains or traces of organisms from a past geological age"))
```
```
ELISP> (wikidata-fetch "firefox")
((id "Q698" label "Firefox" description "web browser developed by the Mozilla Foundation")
 (id "Q1418932" label "Firefox" description "1982 American spy film directed by Clint Eastwood")
 (id "Q225156" label "Firefox" description "Wikimedia disambiguation page")
 (id "Q381753" label "Firefox" description "novel written by Craig Thomas")
 (id "Q3072842" label "Firefox" description "1984 arcade video game"))
```

I want consult to use the function `wikidata-fetch` to asynchronously show candidates. For example, if the user types `foss`, then the completion list would look as shown below

```
Label: free and open-source software
Description: software that is both free (as in freedom) and open-source
Label: Foss
Description: family name
Label: Foss
Description: human settlement in Washita County, Oklahoma, United States of America
Label: Foss
Description: Wikimedia disambiguation page
Label: fossil
Description: preserved remains or traces of organisms from a past geological age
```

and when the user selects an option, then the returned value is the corresponding identifier of the option as reported by Wikidata (i.e. Q506883, Q16870001, Q2735700, Q344945 and Q40614).

If, during the same prompt, the user types `firefox`, then the completion list would look as shown below. Again, the returned value of the function would be the corresponding identifier of the option as reported by Wikidata.

```
Label: Firefox
Description: web browser developed by the Mozilla Foundation
Label: Firefox
Description: 1982 American spy film directed by Clint Eastwood
Label: Firefox
Description: Wikimedia disambiguation page
Label: Firefox
Description: novel written by Craig Thomas
Label: Firefox
Description: 1984 arcade video game
```

Any help is appreciated. Please let me know if you have some questions about the issue.

**Comment by minad** [comment]
> How to asynchronously get candidates from an Emacs Lisp function so that they can be shown in the prompt shown by consult--read?

It is not possible. Emacs is not multithreaded (it has threads but there is a global interpreter lock). Therefore we cannot concurrently generate candidates in the background and asynchronously pass them to the main thread.

> The function that I want to use is shown below. It retrieves information from an API and format it as a property list.

Isn't the answer kind of obvious? If you inspect your code closely there is a `:sync t` which forces `request` to perform a *synchronous request*. Instead you should instruct `request` to operate asynchronously.

**Comment by minad** [comment]
See also https://github.com/minad/consult/commit/7542ae1ac842c3023759de877ec1e5be29972072 where I implemented a basic websearch prototype. Then there are also the consult-notmuch, consult-recoll and consult-spotify packages which also use the asynchronous API to perform asynchronous web requests. You can take a look at those for inspiration.

**Comment by rdrg109** [comment]
@minad Thank you! I'll definitely check out those packages.
