### ISSUE TITLE
Narrow keys for `consult--source-project-buffer` and `consult--source-project-recent-file` are clashing

### ISSUE THREAD

**Issue by isamert** [minad/consult#545]
Both of these sources are using same key for narrowing which makes it not possible to use one of them as both of them are hidden by default.

https://github.com/minad/consult/blob/e9fa6ab2258f015fad3d3e87764872125bc57374/consult.el#L4112

https://github.com/minad/consult/blob/e9fa6ab2258f015fad3d3e87764872125bc57374/consult.el#L4128

Maybe one of them can use "P" instead of "p".

**Comment by minad** [comment]
This is intentional, such that you can narrow to both sources together. But feel free to change this in your configuration via `consult-customize`.

**Comment by isamert** [comment]
It only shows one for me when I hit `p` but I'm not on the latest version or maybe I'm missing something. I'll try it out after updating it and let you know. Thanks for the quick response!
