### ISSUE TITLE
consult-buffer-other-window will change the original buffer

### ISSUE THREAD

**Issue by Eason0210** [minad/consult#547]
Hi @minad ,

With latest commit of consult, `consult-buffer-other-window` will change the original buffer to the target buffer.

steps to reproduce:

1. start emacs with only one window A ( let's say the buffer name is`bufferA`)
2.  <kbd>M-x</kbd> `consult-buffer-other-window`, input `bufferB`, <kbd>RET</kbd>
3. will create window B with `bufferB`, and windows A will change to `bufferB` as well.

With `git bisect`, I find that this behavior was introduced by[ commit b50118f ](https://github.com/minad/consult/commit/b50118f), maybe it would be help.

```bash
b50118f6e9ddf296c48e052d8b8d6dc6fa419e6f is the first bad commit
commit b50118f6e9ddf296c48e052d8b8d6dc6fa419e6f
Author: Daniel Mendler <mail@daniel-mendler.de>
Date:   Fri Apr 8 01:31:57 2022 +0200
    Simplify consult--buffer-preview again
 consult.el | 7 ++++---
```

Tested on macOS, emacs 29

**Comment by minad** [comment]
Thanks for the report. I think the preview was even broken for longer in the case where both recent files and buffer are previewed. It should be fixed now by explicitly restoring the window configuration.

**Comment by minad** [comment]
Unfortunately getting the window restoration right is quite hard in the presence of switch-to-buffer-obey-display-actions and a display-buffer-alist configuration. Therefore I reverted to the more primitive (and flawed) restoration technique. @oantolin @astoff Do you have a better idea?

**Comment by astoff** [comment]
I seem to have an even more basic issue. On `emacs -Q`, if I maximize my frame and run `consult-buffer-other-window`, each preview causes some window to be split, until somehow Emacs decided the windows are all small enough and shouldn't split further. I believe this already happened before the recent changes.

**Comment by minad** [comment]
@astoff Oh yes this can happen too. I think preview for other windows will never work except if we reset the window configuration before each preview of the next buffer. But this has the bad side effects described in https://github.com/minad/consult/commit/4be77d450fd8d408a70ef17a83bba045362172a6:

1. It messes with the minibuffer
2. It messes with the `*Completions*` buffer (doesn't affect Vertico)

**Comment by minad** [comment]
For now I disabled preview for `consult-buffer-other-window`. I think there are two possible solutions:

1. A simple solution using `set-window-configuration`, which only works on Emacs 28 and with the Vertico minibuffer display.
2. A complicated one which manually selects (or creates) an other window and manually previews the buffer there.

**Comment by Aankhen** [comment]
I’m experiencing the same issue. Disabling the preview in bbb5301 doesn’t seem to have any effect. Neither does d30213a (nor the current trunk, af452dc). I don’t know whether it’s related but the problem only started a couple of days ago after I upgraded from Emacs 27.2 to 28.1. (Windows 10, 64-bit, official Emacs build.)
