### ISSUE TITLE
Update to the exclude EXWM buffer from previous functions

### ISSUE THREAD

**Issue by jsilve24** [minad/consult#548]
The following code (which I coppied from the wiki) was working great for me for the past 6 or so months. However the new change the the state protocol seems to have broken it. Is there a simple fix?

```
;; dont' preview exwm buffers
  ;; see: https://github.com/minad/consult/wiki#do-not-preview-exwm-windows-or-tramp-buffers
  ;; TODO: may be able to fix this by modifying or advising consult--buffer-preview to figure out
  ;; where X window is currently displayed and put it back when done
  (defun consult-buffer-state-no-x ()
    "Buffer state function that doesn't preview X buffers."
    (let ((orig-state (consult--buffer-state))
	  (filter (lambda (cand restore)
		    (if (or restore
			    (let ((buffer (get-buffer cand)))
			      (and buffer
				   (not (eq 'exwm-mode (buffer-local-value 'major-mode buffer))))))
			cand
		      nil))))
      (lambda (cand restore)
	(funcall orig-state (funcall filter cand restore) restore))))

  (setq consult--source-buffer
	(plist-put consult--source-buffer :state #'consult-buffer-state-no-x))

```

Thank you so much for all your help!

**Comment by minad** [comment]
I've already updated some of the code in the wiki. No guarantees that it works but please check it out. Did you try to adjust your snippet according to the documentation of consult--with-preview?

**Comment by jsilve24** [comment]
Thanks for directing me to consult--with-preview. I am going to read through that now. Just as an update, the wiki was not updated for this function -- what is currently listed on the wiki does not work.

**Comment by minad** [comment]
> Just as an update, the wiki was not updated for this function -- what is currently listed on the wiki does not work.

No, it was updated, see https://github.com/minad/consult/wiki#do-not-preview-exwm-windows-or-tramp-buffers. However it may still not work since I didn't test it as I am not an EXWM user.

**Comment by jsilve24** [comment]
Alright ultimately I think this simple fix solves my problem: essentially Just test of cand is nil and if so don't evaluate the get-buffer form. 

```
  ;; see: https://github.com/minad/consult/wiki#do-not-preview-exwm-windows-or-tramp-buffers
(defun consult-buffer-state-no-x ()
  "Buffer state function that doesn't preview X buffers."
  (let ((orig-state (consult--buffer-state))
        (filter (lambda (action cand)
                  (if (or (eq action 'return)
			  (if cand
                              (let ((buffer (get-buffer cand)))
				(and buffer
                                     (not (eq 'exwm-mode (buffer-local-value 'major-mode buffer)))))))
                      cand
                    nil))))
    (lambda (action cand)
      (funcall orig-state action (funcall filter action cand)))))

(setq consult--source-buffer
      (plist-put consult--source-buffer :state #'consult-buffer-state-no-x))
```

Unless I am mistaken this is a bug in the code on the wiki and not something specific to my configuration. Could I suggest that this be updated on the wiki to help others avoid this error?

**Comment by bbigras** [comment]
I had a similar problem:

```
Debugger entered--Lisp error: (wrong-type-argument stringp setup)
  get-buffer(setup)
  #f(compiled-function (cand restore) #<bytecode 0x1655005d5d5b60f7>)(setup nil)
  #f(compiled-function (cand restore) #<bytecode 0x1541f21ad5bdeb9d>)(setup nil)
  #f(compiled-function (action arg0) #<bytecode 0x2e9bf769d374b55>)(setup nil)
  #f(compiled-function () #<bytecode 0x5e98ca4539ebbcd>)()
  consult--minibuffer-setup()
  completing-read-default("Switch to: " #f(compiled-function (str pred action) #<bytecode -0x137b2e9fe2c13d3a>) #f(compiled-function (&rest args2) #<bytecode -0xae2d3bb24cbc7ff>) confirm-after-completion nil consult--buffer-history #("*Messages*�����" 10 11 (invisible t consult-strip t)) nil)
  completing-read("Switch to: " #f(compiled-function (str pred action) #<bytecode -0x137b2e9fe2c13d3a>) #f(compiled-function (&rest args2) #<bytecode -0xae2d3bb24cbc7ff>) confirm-after-completion nil consult--buffer-history #("*Messages*�����" 10 11 (invisible t consult-strip t)) nil)
  #f(compiled-function () #<bytecode 0xff01729f3204fa9>)()
[...]
```

Using your `consult-buffer-state-no-x` seems to fix it. thanks!

**Comment by minad** [comment]
I recently switched to EXWM. Instead of replacing the :state function I use a separate source for EXWM buffers, see https://github.com/minad/consult/wiki#exwm-buffers.

**Comment by vslavkin** [comment]
Hello @minad I've been looking at the exwm issues and to the wiki, where you use a regexp for 'consult-buffer-filter' to remove exwm buffers from the "common pool of buffers" and show it only on the EXWM source.
Is there a way to do the same but checking the major-mode instead of a regexp. I've set exwm to change the name of the buffer to whatever app it is, and, altough I could add "\*EXWM\*" at the start of the name of the buffer, I think I prefer it this way.

**Comment by minad** [comment]
@vslavkin No, that's not directly possible with `consult-buffer-filter`, which is regexp only. But if you don't mind writing a little bit of code, you can use a custom predicate if you write your own `:items` function of the `consult--buffer-source`. See `consult--buffer-query`.
