### ISSUE TITLE
How to show multiple candidates that share the same `car`?

### ISSUE THREAD

**Issue by rdrg109** [minad/consult#549]
# The problem

When I evaluate the following sexp

```elisp
(consult--read
 '(("foo" . "abd@abc.com")
   ("foo" . "abc@def.com")))
```

A single candidate is shown in the completion list. I think this happens because the `car` is the same between those two candidates. I would expect two candidates to be shown.

# Additional information

`ivy.el` is capable of showing candidates with the same `car` (see minimal working example below) and successfully act on the additional information (in the example shown below, the additional information would be the `cdr`), with "successfully act" I mean that when the first `foo` is selected in the completion list, `abc@abc.com` is inserted and when the second `foo` is selected, `def@def.com` is inserted.

```elisp
(ivy-read
 "Prompt: "
 '(("foo" . "abc@abc.com")
   ("foo" . "def@def.com"))
 :action
 (lambda (&rest args)
   (insert (cdar args))))
```

# The question

How to make `consult--read` show multiple candidates regardless whether they have the same `car`?

**Comment by minad** [comment]
> How to make consult--read show multiple candidates regardless whether they have the same car?

This is not possible. Completion candidate strings must be unique for `completing-read` and `consult--read`. You have to disambiguate candidates by appending a suffix, e.g., `foo (1)`, `foo (2)`. However there is a trick - you can use an *invisible* disambiguation suffix, but this is a route I do not recommend since it creates more problems than it solves.

**Comment by oantolin** [comment]
Notice that for the user of any function that did this it would be frustrating to be shown two "foo"s without anyway of knowing which is which! Definitely don't do this and disambiguate the candidates instead.
