### ISSUE TITLE
Question: Input string splitting

### ISSUE THREAD

**Issue by aikrahguzar** [minad/consult#550]
Hi @minad, I am working on a hoogle front end using consult here: https://github.com/aikrahguzar/consult-hoogle and it uses quite a few private functions but the basic setup is working pretty nicely (at least for me the only current user). One of the things I wanted to implement was restricting the search to the module  and/or package of the current selection using hoogle's +Module +package or else excluding the module or package with -Module -package etc. This requires modifying the async part of the input which is determined by the `consult-async-split-style`. I see `consult-async--split-perl` and friends but nothing that does it according to the user settings. Is there a way to quickly modify the async part?

This is pretty unusual and wrapping the different splitting styles isn't so bad since there are only 4 of them but if there is a direct way I would rather use that.

**Comment by aikrahguzar** [comment]
> I am not sure I understand the question. What is wrong with `#-module +package async#sync`?

Sorry it is not very clear. But `#-module +package async#sync` works only if the splitting style is `perl`. Basically we start with input being `s1 async s2 async` where `s1` and `s2` depend on the value of `consult-async-split-style` and I want to change the input to `s1 +package -module async s2 sync`. Is there an easy way of determining what `s1` `async` `s2` and `sync` are taking into account `consult-async-split-style`?

**Comment by oantolin** [comment]
Oh, so you want to add `+package` and `-module` parameters that are not present in the user's input? If so, just do it right before sending the string off to hoogle.

**Comment by aikrahguzar** [comment]
> Oh, so you want to add `+package` and `-module` parameters that are not present in the user's input? If so, just do it right before sending the string off to hoogle.

Yes, but they are added by a user action so should be part of the user input and not part of the hoogle command. The intent is to allow the user to refine the search depending on the currently selected candidate, i.e we start with `s1 async s2 async`, the user presses a key sequence and input changes to `s1 +package async s2 sync` where `package` depends on the current selection.

**Comment by oantolin** [comment]
I think I understand now. It sounds like you could easily insert these at the very beginning, just lookup the `:initial` string, skip over it if non-nil, then insert your argument. To lookup the `:initial` string just do:

```elisp
(plist-get
 (alist-get consult-async-split-style consult-async-split-styles-alist)
 :initial)
```

**Comment by aikrahguzar** [comment]
> I think I understand now. It sounds like you could easily insert these at the very beginning, just lookup the `:initial` string, skip over it if non-nil, then insert your argument. To lookup the `:initial` string just do:
> 
> ```emacs-lisp
> (plist-get
>  (alist-get consult-async-split-style consult-async-split-styles-alist)
>  :initial)
> ```

Thanks that works! I want to be able to add and remove these strings so I need to lookup the `:separator` too but works the same way.
