### ISSUE TITLE
Recoll vs ripgrep when finding files, not lines

### ISSUE THREAD

**Issue by AtomicNess123** [minad/consult#555]
I was wondering what the differences are between these two. Is it that recoll find files and not lines that satisfy all keywords? For instance, if I want to find all files that contain A, B and C, ripgrep will not find files but only lines that contain A, B, and C. Is recoll what I need for my purpose of finding files?

**Comment by minad** [comment]
I don't know, I don't use recoll. Ripgrep is just a grep variant. Maybe you find answers on the recoll website or the consult-recoll issue tracker?
