### ISSUE TITLE
consult-yank-from-kill-ring doesn't insert the selected candidate

### ISSUE THREAD

**Issue by dr-scsi** [minad/consult#556]
First of all, many thanks for this package.

For a couple of days now, I have the issue that `consult-yank-from-kill-ring` doesn't insert the selected candidate into buffer.  I can reproduce this with:

 1. emacs -Q
 2. eval `(package-initialize)`
 3. eval `(vertico-mode 1)`

Copy some items into kill-ring with <kbd>M-w</kbd> and try <kbd>M-y</kbd> somewhere in the buffer, select an item (with <kbd>down</kbd>)  and hit  <kbd>RET</kbd>, it is inserted.

Now eval this line:

 4. `(global-set-key (kbd "M-y") #'consult-yank-from-kill-ring)`

Hit <kbd>M-y</kbd> again and select an item which is shown as preview in the buffer, but hitting <kbd>RET</kbd> doesn't actually insert it.

I'm using Emacs 29 with consult-20220420.2202 package.  I observed this also with the last package release.

**Comment by Nathoufresh** [comment]
Facing the same issue

**Comment by dr-scsi** [comment]
Thanks for the quick fix.

**Comment by minad** [comment]
Thanks for the report!
