### ISSUE TITLE
project-ignore-buffer-conditions should be used in consult-project-buffer

### ISSUE THREAD

**Issue by Dickby** [minad/consult#558]
I just try to get rid of the *-buffers in consult-project-buffer and i think that function should respect project-ignore-buffer-conditions.

**Comment by minad** [comment]
No, the consult--source-project-buffer is not necessarily tied to project.el. You can use different project root finding functions, e.g., vc or locate-dominating-file. As such it wouldn't make sense to respect this variable. But you can easily adjust the sources to your liking and write your own filter functions.
