### ISSUE TITLE
Consult line ignoring matches

### ISSUE THREAD

**Issue by jsilve24** [minad/consult#559]
First off thank you for all your hard work on this excelent package!

Here are a few lines of text that I am searching through in a buffer. 

```
report_dates <- fread('data/report_dates.csv')
report_dates[,date:=as.POSIXct(`Announcement Date`,format='%m/%d/%Y')]
report_dates[`Announcement Time`>'16:00'| `Announcement Time`=='Aft-mkt',date:=date+1]
plot_value_qtd <- function(ticker,report_dates.=report_dates,man_date=NULL){
    r=report_dates[Symbol==ticker]
    report_impact=TRUE
```

I run consult-line and then search for the string "report_dates" only the first three lines are returned. 

Ok I figure that perhaps the default is to not search for report dates in the 4th and 5th lines because they are in the middle of a continuous block of non-whitespace characters (e.g., in the middle of a word). 

But that logic doent hold because if I search "mpact" then a bunch of lines matching "impact" show up...

Why is the 4th and 5th lines not matching?

**Comment by minad** [comment]
The reason is probably that you didn't configure your `completion-styles` properly.

When I try this with emacs -Q `consult-line` works properly.

~~~ elisp
(package-initialize)
(global-set-key (kbd "M-s l") 'consult-line)
(vertico-mode)
(setq completion-styles '(orderless))
~~~

Also the `substring` style works well:

~~~ elisp
(setq completion-styles '(substring))
~~~

However the `basic` style, which is the Emacs default, does not workl:

~~~ elisp
(setq completion-styles '(basic))
~~~

See https://github.com/minad/consult#bug-reports

**Comment by minad** [comment]
> But that logic doent hold because if I search "mpact" then a bunch of lines matching "impact" show up...

I cannot explain this either, but I need a more detailed bug report with a recipe based on emacs -Q to tell you more.

**Comment by oantolin** [comment]
Oh, this *is* quite confusing @minad. You're right about `'(orderless basic)` being better than `'(basic orderless)`. (I'm still sticking with `'(orderless)` with some overrides for files and am quite happy with that).

**Comment by minad** [comment]
@oantolin One could also prioritize `orderless` only for the `consult-location` category via `completion-category-overrides` but overall I believe that `(orderless basic)` is the best general purpose configuration. This should work almost everywhere, if the loss of TAB completion is acceptable. If one wants to preserve TAB completion and still wants to prioritize orderless, I don't have a good answer. Then a crossover completion style could be a solution as mentioned in https://github.com/oantolin/orderless/issues/111#issuecomment-1098763842, but I haven't really tried this for longer.

**Comment by jsilve24** [comment]
Here is an emacs -Q script

First bootstrap straight:
```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
```
Then run 
`straight-use-package`
type `consult RET` 

Then switch to scratch buffer and paste 
```
report_dates <- fread('data/report_dates.csv')
report_dates[,date:=as.POSIXct(`Announcement Date`,format='%m/%d/%Y')]
report_dates[`Announcement Time`>'16:00'| `Announcement Time`=='Aft-mkt',date:=date+1]
plot_value_qtd <- function(ticker,report_dates.=report_dates,man_date=NULL){
    r=report_dates[Symbol==ticker]
    report_impact=TRUE
```

Then start `consult-line` and type 
`report_dates` 

observed the reported behavior (only first 3 lines are matched).

**Comment by jsilve24** [comment]
Edit @minad is brilliant. Changing completion styles to:
`(setq completion-styles '(orderless partial-completion basic))` fixes it.
