### ISSUE TITLE
Better preview for Emacs default completion

### ISSUE THREAD

**Issue by oantolin** [minad/consult#56]
Currently neither `minibuffer-force-complete` nor tab cycling updates the preview.

For `minibuffer-force-complete` that's just a matter of advising it too, but tab cycling is tricky. The way tab cycling is implemented is that TAB is temporarily redefined via `set-transient-map`, and the command it is redefined to be is a `lambda`, not a named function.

**Comment by minad** [comment]
Yeah. If you have time to clean that up please do. This is a mess. I advise three functions but I have no idea what I am actually doing.

**Comment by oantolin** [comment]
Sure I'll look into it. I think probably just after every change to the minibuffer contents, we should `test-completion`, and if it is a full candidate, update the preview. I'll test that and make a pull request if it seems good enough.

**Comment by oantolin** [comment]
Thanks! You beat me to it. I just tested it and works great, including the tricky case of tab cycling which the previous approach wouldn't work for.

**Comment by oantolin** [comment]
How would you feel about lumping in `embark-completing-read` with the default completion? You can just change `(eq completing-read-function #'completing-read-default)` to `(memq completing-read-function '(completing-read-default embark-completing-read))`.

**Comment by minad** [comment]
@oantolin I guess that would be okay. Btw do you know if there is a better way to distinguish icomplete from default? Icomplete does not overwrite the function.

**Comment by oantolin** [comment]
> @oantolin I guess that would be okay. Btw do you know if there is a better way to distinguish icomplete from default? Icomplete does not overwrite the function.

No, I don't know of a better way. I would have done it the same way you did.

**Comment by minad** [comment]
See here https://github.com/minad/consult/commit/00c820d5bc5cd5093038c5bc65ab0c1e3f4d87c6. I would like if we could find a better way to do this detection, but for now it is okay.

**Comment by oantolin** [comment]
Perfect, thanks! It would be nice to have a cleaner way of detecting the various completion systems, but this isn't too bad.
