### ISSUE TITLE
`consult-keep-lines` destroys window config.

### ISSUE THREAD

**Issue by joostkremers** [minad/consult#564]
Following up on https://github.com/minad/consult/issues/6#issuecomment-1109095876:

I wrote the following command:

``` emacs-lisp
(defun my-copy-buffer-contents ()
  (interactive)
  (let ((buffer (get-buffer-create (string-join (split-string (minibuffer-contents-no-properties) "[^[:alnum:]]" t) "_"))))
    (with-current-buffer buffer
      (insert-buffer-substring-no-properties (window-buffer (minibuffer-selected-window))))
    (display-buffer buffer)))
```

I bound this command to `C-c C-c` in `minibuffer-mode-map`, so I can call it while in the minibuffer during a call to `consult-keep-lines`. I put in the `display-buffer` call in order to show the newly created buffer with the idea that I can easily switch to it after finishing `consult-keep-lines`.

Unfortunately, when I end `consult-keep-lines` by pressing `RET`, the window that popped up to display the new buffer is deleted again.

I took a quick look at the code for `consult-keep-lines` but I'm unable to determine where or how this happens. Is this intentional? Is there a way to prevent it from happening?

**Comment by minad** [comment]
The function `read-from-minibuffer` restores the original window configuration after exiting the minibuffer. Since Emacs 28 it is possible to override this by setting `read-minibuffer-restore-windows=nil`.

**Comment by joostkremers** [comment]
Thanks! Didn't know about this, sorry for the noise.
