### ISSUE TITLE
special handling of `~` for `find-file`

### ISSUE THREAD

**Issue by c-alpha** [minad/consult#569]
I am sorely missing a behaviour with `find-file`, which I liked in `ivy`: whatever the path currently shown at the find file prompt in the minibuffer was, typing `~` would erase it and insert `~/` at the front, effectively taking me back to my home dir, and leaving me in a position where I can directly start typing to generate matches.

Perhaps this is already possible with `consult` and some config (e.g. minibuffer keymap?) I couldn't figure out?

That said, I have let go of company, ivy, etc. and have switched to corfu, consult, and friends. Not regretted it for a moment. Great stuff, and **thanks for making these great packages!**

**Comment by minad** [comment]
Thanks! This feature would fit better into Vertico. But there is almost no point. If you enter ~/ you will already get the change to the home directory. This file path shadowing is an ootb feature of Emacs. See also vertico-directory-tidy to remove the shadowed part of the path.

**Comment by c-alpha** [comment]
`vertico-directory-tidy` was the right pointer. **Many thanks!**
