### ISSUE TITLE
Question about new org buffer source in the readme

### ISSUE THREAD

**Issue by iyefrat** [minad/consult#570]
Hey,
Is there a reason why you changed the org buffer logic for getting the list of org buffers in the `org-source` example in the readme? Wouldn't using `org-buffer-list` like in the [wiki example](https://github.com/minad/consult/wiki#org-buffers) be more robust?

**Comment by minad** [comment]
org-buffer-list has the downside that it will load Org. One could however add an :enabled field and check first if the org feature is loaded before populating the source.

**Comment by iyefrat** [comment]
Thanks!

**Comment by minad** [comment]
I think we can remove the org example from the wiki then? The example in the readme is more powerful since it demonstrates the :new creation of candidates.

**Comment by iyefrat** [comment]
Sounds good. What do you think of adding to the wiki the term/eshell sources that used to be in the readme? those seem useful as well.

**Comment by minad** [comment]
Of course, feel free to update this. But note that the old sources were much more limited. Therefore I updated the README to this single org example.
