### ISSUE TITLE
`consult-ripgrep` can't jump to line which has '\xxx' chars

### ISSUE THREAD

**Issue by lynnux** [minad/consult#572]
Emacs version 29.0.50, win10 x64.
Started as emacs -Q, and only enable vertio, orderless and consult
invoke `consult-ripgrep`, you can't jump to a line which has '\xxx' chars.
I know it's because rg can't normally decode the file, so output '\xxx' chars, but it should not make jump line not working.
see this gif:
![22](https://user-images.githubusercontent.com/367894/167752536-66e71190-7531-43a2-a4e6-568938bb955f.gif)
and the test file:
[test.txt](https://github.com/minad/consult/files/8666048/test.txt)

**Comment by lynnux** [comment]
the config:
```
(use-package vertico
    :load-path "~/.emacs.d/packages/minibuffer/vertico-main"
    :init
    (setq enable-recursive-minibuffers t ; 允许minibuffer里再执行命令
          vertico-cycle t ;; vertico不同于其它的是当前行之前的结果被列在了最后
          vertico-resize nil ;; 让它初始化就固定大小
          vertico-count 20 ;; 高度多少行
          )
    :defer 0.3
    :config
    (vertico-mode 1)
    ;; (enable-minibuffer-auto-search-at-point)

    (define-key vertico-map (kbd "C-s") 'vertico-next) ; 不支持在结果里搜索
    (define-key vertico-map (kbd "C-r") 'vertico-previous) ; 不支持在结果里搜索

    ;; 习惯只要underline，不随主题改变
	(custom-set-faces
	 '(vertico-current ((t (:inherit unspecified :underline t :background nil :distant-foreground nil :foreground nil)))) 
	 '(consult-preview-line ((t (:underline t :background nil))))
	 )

    ;; (global-set-key [f6] #'vertico-repeat) ;; 没什么用，还跟上面这个有冲突，不如用M-n M-p
    
    (use-package orderless
      :defer t ;; 配合load延迟加载，并且不需要设置load path
      :config
      (defun sanityinc/use-orderless-in-minibuffer ()
        (setq-local completion-styles '(substring orderless)))
      (add-hook 'minibuffer-setup-hook 'sanityinc/use-orderless-in-minibuffer)
      )
    (load "~/.emacs.d/packages/minibuffer/orderless")
    )

  (use-package consult
    :load-path "~/.emacs.d/packages/minibuffer/consult-main"
    :commands(consult-ripgrep
              consult-buffer
              consult-line
              consult-buffer-other-window
              consult-buffer-other-frame
              consult-goto-line
              )
    :init
    (setq
     consult-line-start-from-top nil      ;; 默认前面行反而显示在后面
     consult-line-point-placement 'match-beginning ;; 这个有bug啊，它好像用的mark-ring实现的
     )
    ;; https://github.com/phikal/compat.el
    (use-package compat
      :defer t
      :load-path "~/.emacs.d/packages/minibuffer/compat.el-master"
      )
    (defun my-consult-ripgrep()
      (interactive)
      (require 'consult)
      ;; 不忽略ignore，从当前目录开始搜索
      (let  ((consult-ripgrep-args (concat consult-ripgrep-args " --no-ignore")))
        (consult-ripgrep default-directory))
      )
    (global-set-key [f2] 'my-consult-ripgrep)
    (global-set-key (kbd "C-x C-b") 'consult-buffer) ; 含buffer, recentf，bookmark！还带预览功能！
    (global-set-key (kbd "C-s") 'consult-line)
    (global-set-key [remap switch-to-buffer] 'consult-buffer)
    (global-set-key [remap switch-to-buffer-other-window] 'consult-buffer-other-window)
    (global-set-key [remap switch-to-buffer-other-frame] 'consult-buffer-other-frame)
    (global-set-key [remap goto-line] 'consult-goto-line)
    :config
    )
```

**Comment by minad** [comment]
This issue is probably a configuration problem of your encoding settings. I don't use Windows and I am afraid I cannot help you with investigating this. See #317 and #475 where Windows-specific issues where discussed before. The solution mentioned for Cyrillic encoding seems:

~~~ elisp
(add-to-list 'process-coding-system-alist 
             '("[rR][gG]" . (utf-8-dos . windows-1251-dos)))
~~~

I am not sure if this makes sense. Maybe you can adapt this to the encoding used by your installation? There seem to be multiple configuration variables which you could try:

- `process-coding-system-alist`
- `default-process-coding-system`
- `inherit-process-coding-system`

On my system `default-process-coding-system` has the value `(utf-8-unix . utf-8-unix)`, so everything is interpreted as utf-8. It would be interesting to know if you also see similar issues when you run the builtin `grep` commands or `consult-grep`, `consult-git-grep`?

**Comment by minad** [comment]
I close this since I cannot reasonably support Windows. I can only rely on on inspection of the code of grep.el, xref.el and compile.el. A search there for `coding` or `utf-8` turns up nothing. Therefore this must be a global setting and should be fixed globally.

**Comment by lynnux** [comment]
My `default-process-coding-system` is `(undecided-dos . undecided-unix)`
It's working after set
```
(add-to-list 'process-coding-system-alist 
                 '("[rR][gG]" . (utf-8 . gbk-dos)))
```
![image](https://user-images.githubusercontent.com/367894/167790123-29f45e53-6155-425a-8bdc-66fa675a71e8.png)
rg decode the file as utf-8, and output result as utf-8, althrough it can't correctly decode the gbk file, but it's good to jump to the line.
Thanks again!
