### ISSUE TITLE
consult--buffer-query: Symbol’s function definition is void: ensure-list

### ISSUE THREAD

**Issue by titanofold** [minad/consult#574]
Consult is no longer working as of today (May 11, 2022). Upon fresh start of Emacs, executing the usual bind `C-x b` I only get the following message:

    consult--buffer-query: Symbol’s function definition is void: ensure-list

The expected list of buffers is *not* presented.

My Emacs is: GNU Emacs 28.0.50 (build 1, x86_64-w64-mingw32) of 2021-01-15 in Windows 10.

**Comment by minad** [comment]
Your Emacs is outdated (2021-01-15). `ensure-list` has been added quite a while ago. On Emacs 27, `ensure-list` is provided by the `compat` package.

**Comment by titanofold** [comment]
Upgrading Emacs to 28.1 resolved the issue.

Thank you!
