### ISSUE TITLE
How to filter results in consult-regexp, based on file extension

### ISSUE THREAD

**Issue by Crandel** [minad/consult#575]
All my working projects contain a lot of files with different extension, such as go, js, yaml etc.
Everytime I search something in `.go` files I got much more results in js or yaml files

When I try to use ripgrep in terminal it will filter extension correctly

```bash
$ rg -i redeem *.go
scenario_coupon_for_points_test.go
98:     // Redeem coupon on session close and award points equal to session total (20)

referral_usage_limit_test.go
137:                    "action":   dat.ActionRedeemReferral,
265:                    "action":   dat.ActionRedeemReferral,
```

**Comment by oantolin** [comment]
I'm not at my computer right so I might be misremembering slightly, but you can pass arguments to ripgrep after `--`, so your example would be `M-x consult-ripgrep RET #redeem -- *.go`

**Comment by Crandel** [comment]
@oantolin Not working for me(

**Comment by minad** [comment]
You could also filter out other files with `#redeem#!js !yaml`.

**Comment by Crandel** [comment]
Thank you, it works!
