### ISSUE TITLE
Question about buffer naming in consult-buffer

### ISSUE THREAD

**Issue by diegovdc** [minad/consult#576]
Is there a (preferably easy) way to configure `consult-buffer` so that if I first open `foo/core.clj` it will show just the file name, but if I open `bar/core.clj` it will show both the dir names and the file name?
It currently just displays something like:
```
core.clj
core.clj<2>
```
Which is somewhat good I guess, but not as convenient, specially with projects that have plenty of files with the same name in different directories.

**Comment by minad** [comment]
See https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html
