### ISSUE TITLE
consult-fzf

### ISSUE THREAD

**Issue by jgarte** [minad/consult#578]
Hi is there a command similar to `consult-ripgrep` but for recursively searching files in directories? Maybe something like a `consult-fzf` or `consult-skim` but in vanilla elisp?

**Comment by minad** [comment]
https://github.com/minad/affe

**Comment by kohnish** [comment]
I wonder if the support or PR for fzf can be considered. consult-fd is supported, so maybe the support is not that hard?  
counsel-fzf supports remote. Lack of fuzziness for find-find, recentf are my last dependencies for swiper.

**Comment by minad** [comment]
> I wonder if the support or PR for fzf can be considered. 

No. It is out of scope due to the limitations of fzf. The problem is the lack of controlling fzf via a pipe. I've also looked into alternative programs, but I wasn't successful. See for example https://github.com/skim-rs/skim/issues/388.

**Comment by kohnish** [comment]
I see. Thanks a lot for the detailed explanation.

**Comment by antonrogov** [comment]
The following works for me btw with a simple wrapping script (based on https://github.com/minad/consult/pull/189/files), but there're no results until input has at least 3 characters. It probably can be fixed with options, but I haven't dug deep enough into this.

```emacs-lisp
(defun consult-fzf ()
  (interactive)
  (find-file
   (consult--read
    (thread-first
      (consult--async-sink)
      (consult--async-refresh-immediate)
      (consult--async-map (-partial 'string-remove-prefix "./"))
      (consult--async-process
       (lambda (input) (list "fzfp" input))
       :file-handler t)
      (consult--async-split))
    :prompt "Find file: "
    :sort nil
    :require-match t
    :category 'file)))
```

and the `fzfp` script:
```bash
#!/bin/sh

fd -t f | fzf -f "$1" | head -n ${2:-100}
```

**Comment by kohnish** [comment]
@antonrogov Thanks. I might try later. I upgraded to helm instead for now. It also addresses the issue like consult-line not highlighting matches, getting vanilla execute-extended-command and etc.
