### ISSUE TITLE
No search result when using `consult-grep` and `consult-ripgrep`

### ISSUE THREAD

**Issue by searene** [minad/consult#580]
I just installed `consult` and try to use `consult-grep` and `consult-ripgrep`, but neither of them worked. They didn't show any search results to me. Did I use them in the wrong way? How to find out the reason?

No result is shown:

https://user-images.githubusercontent.com/3351317/169674754-e69d7b7f-2a50-45af-9979-fc135e94ace6.mov

Ripgrep worked in the terminal:

https://user-images.githubusercontent.com/3351317/169674828-e23fa222-90e7-43ed-9dde-81925ef0da7c.mov

**Comment by minad** [comment]
See https://github.com/minad/consult#bug-reports
