### ISSUE TITLE
Disabling auto-preview for `consult-project-buffer` works partially

### ISSUE THREAD

**Issue by fredericgiquel** [minad/consult#581]
# Problem

Disabling auto-preview for `consult-project-buffer` only works as expected when the command is launch inside a project.

# Steps to reproduce

- Use Emacs 28 with an empty profile except the following `init.el`:
```elisp
(package-initialize)

(unless (package-installed-p 'consult)
  (package-install 'consult))
(unless (package-installed-p 'vertico)
  (package-install 'vertico))

(require 'consult)
(require 'vertico)

(vertico-mode)
(setq completion-styles '(substring basic))

;; Disable auto-preview for consult-project-buffer
(consult-customize consult-project-buffer :preview-key (kbd "M-."))
```
- Open at least 2 files from a VC repository
- `M-x consult-project-buffer` => **auto-preview is disabled as expected**
- Switch to the `*scratch*` buffer (or any buffer not linked to a project)
- `M-x consult-project-buffer`
- Choose the project used previously => **auto-preview is active for the project buffers**

**Comment by minad** [comment]
Thanks for the report!
