### ISSUE TITLE
state function 'return action doesn't keep text properties for candidate

### ISSUE THREAD

**Issue by dawsers** [minad/consult#582]
I am trying to understand how consult works while developing a small extension. One of the difficulties I found was there is no separable data for a candidate's display and actions. For example, I may want to display the description of a URL, but always act on the URL itself, or some date for a git commit, but act on its commit id. If the candidate kept the associated data (as in an *alist* `(description . url)` or `(date . commit-id)`) throughout its life, this would be easy to achieve. However, it is my understanding, the candidate display in the mini-buffer will take the description and discard the URL/commit-id. To work around this behavior, I saw several extensions that use text properties to embed the actionable data into the displayable data. I used this mechanism to write my extension, integrating some embark actions and a `:state` function for preview. It all works fine that way. However, it seems the `:state` function gets my *"propertized"* candidate for most state actions, so I can retrieve the actionable data for example when doing the ` 'preview`, but when the candidate is selected with `<RET>`, it loses its text properties in the `:state` function `'return` action, and also as the return of `consult--read`. I don't know if this is a bug or the intended behavior, but in a general case it makes a bit hard to write an extension that does something useful with the result when the text shown in the mini-buffer is related but not exactly the data needed for the default action. Could this be happening because of something related to resetting properties for face assignment?

I hope I have been able to explain the problem I have, and I am sure you will be able to educate me on how to make things work. I am still quite green on consult and embark.

Thank you!

**Comment by minad** [comment]
consult--read allows you to specify a :lookup function to retrieve the original candidate or data from the input string.
