### ISSUE TITLE
Support specify the default completion UI

### ISSUE THREAD

**Issue by BooAA** [minad/consult#586]
Hi @minad , thanks for your work.

I want to propose adding an user option for the default completion UI function used by consult. The motivation is that I use Emacs's default tab completion most of the time. When I need more expensive help, I invoke commands like `helm-apropos` or `counsel-describe-function`, which can be called independently without `helm-mode` or `ivy-mode` enable. Under the current ecosystem, I haven't find out how to make consult use some special UI without interfering the remaining part of the system. For example, if I want `consult-imenu` to display candidates vertically, I have to enable `vertico-mode`, than invoke `consult-imenu` and disable `vertico-mode` to make sure I can still use the default tab completion UI in my daily workflow. I think the problems can be solved by adding an addition user option specifing the default UI used by consult's commands. 

My hypothetical scenario works like this:
```emacs lisp
(defcustom consult-default-completing-read #'completing-read)
```

Having this default value makes sure we have maximum compatibility with the default completion system and users can directly enable `vertico-mode` or `selectrum-mode` globally to make every command use their prefered UI.

For user do not want to enable those minor-mode globally and only want commands in consult to have separate UI, they can
```emacs lisp
(setq consult-defualt-completing-read #'selectrum-completing-read) ;; I use selectrum as example since I didn't find out similar function in vertico
```

Now when they directly invoke those `consult-*` commands, they can have the better UI for searching and filter, and the rest of Emacs won't get effected. What do you think?

**Comment by oantolin** [comment]
Not all completion UIs work by providing a `completing-read` function. Icomplete doesn't, for example.

**Comment by BooAA** [comment]
I see. Then my question becomes how can I make consult use vertico's UI but make the rest of Emacs works as normal? A dirty trick I come up is just advicing every consult-* commands to enable `vertico-mode` before and disable it after. I hope we can have better solution.

**Comment by oantolin** [comment]
> I haven't find out how to make consult use some special UI without interfering the remaining part of the system

It's easy: to write a little wrapper that enables whatever completion UI you want, runs the command you want it for, and disables the completion UI. Probably few people actively want an inconsistent, patchwork completion UI, so it's OK if they have to work a little bit harder to get what they want.

By the way, you might enjoy leaving Vertico on all the time, but configuring it to use vertico-unobtrusive-mode (it displays the top completion only)  for most commands. I find seeing 1 completion better than seeing 0, but still unobtrusive. Check out the vertico-multiform extension to configure which mode Vertico uses for different commands or completion categories.

**Comment by minad** [comment]
This feature is out of scope of Consult. I agree with @oantolin that a patchwork completion UI is usually not desired. As a workaround you can advise `consult--read` and redirect `completing-read` to your desired completion function.
