### ISSUE TITLE
Error native compiling consult.el

### ISSUE THREAD

**Issue by ZelenyeShtany** [minad/consult#588]
Hello.

During deferred native compilation I get this error in *Warning* buffer:
`Warning (comp): consult.el: Error: Wrong type argument listp`

When I try to native compile this file directly via native-comp, I get this:
`Debugger entered--Lisp error: (wrong-type-argument "consult.el" listp eshell-history-ring)
  signal(wrong-type-argument ("consult.el" listp eshell-history-ring))
  comp--native-compile("consult.el" nil nil)
  native-compile("consult.el")
  emacs-lisp-native-compile-and-load()
`

Due to this error, native comp tries to recompile this file every emacs startup.

Tried to add `(require 'em-hist)` (where `eshell-history-ring` variable is defined) to consult.el - didn't work.

Is this a common issue? What can I do to solve it? Thank you.

`M-x emacs-version:`
`GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-28`

**Comment by minad** [comment]
I have not seen this issue before. Can you please provide a minimal recipe? See https://github.com/minad/consult#bug-reports.

**Comment by ZelenyeShtany** [comment]
I'm sorry. The issue was related to native-comp-verbose set to 3 which has been causing this error and recompilation on emacs startup.
