### ISSUE TITLE
Is there any mechanism like :dynamic-collection of counsel in consult?

### ISSUE THREAD

**Issue by liuyinz** [minad/consult#590]
@minad I am a fan of  [counsel-jq](https://github.com/200ok-ch/counsel-jq), how should I implement `consult-jq` with mechanism like `:dynamic-collection` in consult? Using async or something else, no idea still. Any advice, thanks!

**Comment by minad** [comment]
There are two ways. You can either use `consult--read` with async (see for example consult-ripgrep, consult-find, consult-notmuch, consult-spotify, affe, ...).

Alternatively you could rely on `completion-table-dynamic` (see https://github.com/minad/vertico/#completion-table-dynamic). See also @alphapapa's org-ql-find which uses a dynamic completion function https://github.com/alphapapa/org-ql/commit/d0acc8cbba63ef50f1c0ecffdf1770792b13592d. See also the discussion and the issue there.

**Comment by eki3z** [comment]
> Late to the party, but there's now https://github.com/elken/consult-jq 😄

Oh, awesome work. I use my own tool now :  https://github.com/eki3z/ddp.el, hope you enjoy it.
