### ISSUE TITLE
consult-autoloads.el doesn't cater for autoloads from consult.el

### ISSUE THREAD

**Issue by dr-scsi** [minad/consult#592]
Hi,

I re-installed consult (20220613.947) from MELPA and in occurred to me that the generated `consult-autoloads.el` doesn't contain the autoloads defined in `consult.el` while the ones from other files like `consult-compile.el` or `consult-flymake.el` are there.  For `consult.el`, the `consult-autoloads.el`  looks like this:

```
;;; Generated autoloads from consult.el

(register-definition-prefixes "consult" '("consult-"))

;;; Generated autoloads from consult-compile.el

(autoload 'consult-compile-error "consult-compile" "\
Jump to a compilation error in the current buffer.
...
```

I can cure the issue with `(require 'consult)` in my init file, but this isn't the way it was intended.  I'm not sure if this is an Emacs or consult issue.  This is with Emacs 29 from master (8fca44da81).  I did the exercise also with `emacs -Q`, same result.

Any hints would be appreciated.

**Comment by minad** [comment]
This is not a Consult issue. Maybe there is a problem in the package manager or in the autoload generation.

**Comment by dr-scsi** [comment]
Thanks for your response.  I will investigate further.
