### ISSUE TITLE
consult-buffer-other-frame breaks when showing preview in other frame

### ISSUE THREAD

**Issue by tarsius** [minad/consult#593]
`consult-buffer-other-frame` shows previews in another frame, causing that frame to be selected. Subsequent user input, which is intended for the minibuffer, is instead inserted into the buffer displaying the preview.

The comment in `consult--buffer-preview` suggests that it is supposed to prevent this from happening, but it does not seem to have the intended effect.

**Comment by tarsius** [comment]
Maybe this is relevant: I am trying to switch to the buffer `*Messages*` but after typing `me`, this command wants to visit the *bookmark* for the file `magit-bookmark.el`.

**Comment by minad** [comment]
Thanks for the report. This is indeed related to the bookmark preview. I will disable preview for consult-buffer-other-frame in a more robust way.

**Comment by tarsius** [comment]
Thanks!

**Comment by minad** [comment]
Thanks. Reverted for now. We hopefully get an improved buffer preview in the future, which works with more complex window configuration setups, see https://github.com/minad/consult/discussions/855.

**Comment by tarsius** [comment]
Thanks!
