### ISSUE TITLE
Feature request: propertize extra information for symbols in consult-imenu.el

### ISSUE THREAD

**Issue by bigodel** [minad/consult#594]
## Description

`lsp-mode` has a custom `imenu-create-index-function` (of course they do), namely `lsp--imenu-create-index`, which adds a couple more information to the symbols, such as a `symbol private` for when the `symbol` is a private one. This LSP function already propertizes the additional information, and `M-x imenu` displays it correctly, but for some reason `consult-imenu` discards the propertization information provided by `(funcall imenu-create-index-function)`, so the feature request would be for `consult-imenu` to either

1. Have its own face; or
2. Try to propertize the item key as it comes from the `imenu-extract-index-name-function`. I find this preferable, this way we don't have to create edge cases for each of the packages that provide extra information.

I tried doing some ad-hoc thing, but couldn't really get Consult to display the propertization that comes from `(funcall imenu-create-index-function)`, and I assume its not complicated, so that's why I thought it'd be better to just create an issue on GitHub :D.

## Steps to reproduce

1. Start Emacs with `emacs -q`
2. Initialize packages (`M-x package-initialize`)
4. Install, if not already installed, `consult` and `lsp-mode`
5. Go to a project for which you have a language server installed
   For this step, I created a stub Clojure project with [`deps-new`](https://github.com/seancorfield/deps-new), i.e. `clojure -Tnew app :name foo`.
6. Add, somewhere inside any source file, a private function.
   For Clojure, I simply used `(defn- foo [] "foobar")`.
7. Ensure LSP is active with `M-x lsp`.
8. Call `M-x imenu` and see that the symbol for the private function (`foo` in my case) is followed by a `.private` with height as 0.8 (it also inherits from `lsp-signature-face` which in turn inherits from `shadow`).
9. Call `M-x consult-imenu` and see that the same symbol appears as `foo private`, all with the same face.

**Comment by minad** [comment]
consult-imenu overwrites the faces. We can change this such that the Consult faces are appended instead. This will preserve backend highlighting. On the other hand the imenu is also displayed in the GUI menu. I have to check if backends are supposed to add faces.

**Comment by bigodel** [comment]
> consult-imenu overwrites the faces. We can change this such that the Consult faces are appended instead. This will preserve backend highlighting. On the other hand the imenu is also displayed in the GUI menu. I have to check if backends are supposed to add faces.

Yeah, I couldn't find anything about faces on the Imenu documentation.
