### ISSUE TITLE
Order consult-line candidates by line

### ISSUE THREAD

**Issue by tarsius** [minad/consult#595]
Have you considered ordering the completion candidates of `consult-line` by line number? That would allow moving through the buffer in a predictable fashion, similar to isearch and swiper (which I used before).

In a similar vain, have you considered not changing point in the buffer being searched when merely typing? I.e. only update point when using `vertico-next` and `vertico-previous`, and maybe a new, "jump to current match" command.

Or is there already another command that behaves as an isearch/swiper replacement?

**Comment by oantolin** [comment]
If you set `consult-line-start-from-top` to `t`, `consult-line` will order lines by line number. By default it also orders them mostly by line number but it starts at the current line and puts the preceding lines at the bottom of the list.

As for not moving the cursor, you can configure this by setting which keys you want to trigger previews with `(consult-customize consult-line :preview-key (list (kbd "key1") (kbd "key2") ...)`. (The default value is the special value `'any`.)

**Comment by minad** [comment]
I don't have to add much to @oantolin's answer. Maybe @tarsius uses flex completion which shuffles the completion candidates?

**Comment by tarsius** [comment]
Thanks for the help. The problem was indeed that I was using a flex-like completion style. I had overridden that in the past for `consult-location`, but some recent refactoring of my init file broke that. I should have realized the two problems I was having were related.

**Comment by minad** [comment]
Okay, you can either overwrite the completion style for the `consult-location` completion category, such that you use a non-reordering completion style there, e.g., `orderless`, `substring`, or continue to use `flex` there but explicitly opt-out via `vertico-sort-override-function`.

**Comment by tarsius** [comment]
I went with `substring` (as I used to). Thanks for the hint about `vertico-sort-override-function`, that might come in handy.

**Comment by oantolin** [comment]
If you like `substring`, @tarsius, I'd recommend giving `orderless` a shot, with `orderless-matching-styles` set to the singleton `'(orderless-literal)`. In my extremely biased opinion it's strictly an upgrade over `substring`.

**Comment by tarsius** [comment]
That's the plan :grinning:
