### ISSUE TITLE
consult-buffer changes current buffer automatically after pressing narrowing keys

### ISSUE THREAD

**Issue by ilupin** [minad/consult#599]
I have disabled the live preview by `(setq consult-preview-key nil)`, but `consult-buffer` changes current buffer automatically when I press narrowing keys.

First, press `consult-narrow-key` (it has been set to '<') after `M-x consult-buffer`, and the current buffer is not changed since preview is disabled, which is expected. Then, press some key, e.g. `b`, to narrow buffer candidates. After a short delay, the current buffer is automatically changed.

If I just press `b SPC` to narrow the list, the buffer is not changed

https://user-images.githubusercontent.com/5555871/175469283-51c56b84-fc1a-4664-9822-471eae39a96d.mp4

.

**Comment by minad** [comment]
Thanks. This was a subtle issue. Please check if the fix works for you.

**Comment by ilupin** [comment]
It works, thank you!
