### ISSUE TITLE
Getting a Buffer exit prompt after consult git-grep selection with recent releases

### ISSUE THREAD

**Issue by mpenet** [minad/consult#602]
Hi, 

I get this `Buffer Preview: foo.clj modified; kill anyway?` prompt after selection when using consult-git-grep now. 
That's something that popped with one of the recent releases, I went from `ca07137fc99d404efc5431e8b01ca1e96ed76644` to `9acf9398ce187829f6afe6d33f0891ba1c07cd0d`. I tried to turn it off but couldn't manage. Any idea how this happened and how it could be fixed?
 
> GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) of 2022-04-07

my config is here in case that helps: https://github.com/mpenet/emax

**Comment by minad** [comment]
Thanks for the report. Does the issue occur for these commits?

* https://github.com/minad/consult/commit/b5af5331c322102f265331fc591d417995402952
* https://github.com/minad/consult/commit/5b7cdb19024857037663e27a4855921e4f368426

Can you try to reproduce the problem on Emacs 28? I don't use 29 yet and I don't observe any issue. Furthermore I need a more precise description of the reproduction steps based on a minimal configuration (emacs -Q), see https://github.com/minad/consult#bug-reports.

**Comment by mpenet** [comment]
Sure, I ll try. I can't do it now tho (I am at work).

**Comment by mpenet** [comment]
on b5af533, selecting a match does nothing (it doesn't select the line on new buffer), nor does it exhibit the problem I mentioned.

on 5b7cdb19024857037663e27a4855921e4f368426 selection works, but the prompt shows up like in my original report

**Comment by mpenet** [comment]
actually b5af5331c322102f265331fc591d417995402952 is ok, after that the pop-up shows (so from cce3e1c1e0e5e192426977768a3830671facd9ca).

**Comment by minad** [comment]
Okay, I reverted the problematic commit https://github.com/minad/consult/commit/cce3e1c1e0e5e192426977768a3830671facd9ca for now.
