### ISSUE TITLE
apply: Symbol’s function definition is void: consult-completing-read-multiple

### ISSUE THREAD

**Issue by arjunkathuria** [minad/consult#603]
Getting this error when trying to set tags in org-mode using `C-c C-q` which seems to be bound to `org-set-tags-command`

Error is the same as the title.

consult version `20220701.1352`

The log:
```
apply: Symbol’s function definition is void: consult-completing-read-multiple
Quit
apply: Symbol’s function definition is void: consult-completing-read-multiple
Mark set
Mark activated
```

**Comment by minad** [comment]
See changelog

**Comment by minad** [comment]
Btw you opened the same issue in #591. Please investigate first before opening issues.

**Comment by arjunkathuria** [comment]
i did, and its still happening for me, on the newest MELPA version (which i assumed should have the fix) or would it not land unless you make a release here?
