### ISSUE TITLE
Restart command in different directory

### ISSUE THREAD

**Issue by indigoviolet** [minad/consult#605]
Similar to #596, is there a way to change the directory of an arbitrary consult command after we have already entered the prompt?

For example, let's say I'm using `consult-find`, I can start it with a prefix to prompt for a directory; but if I've already entered `consult-find`, I can't change the directory I'm searching in.

It would be nice to be able to invoke the directory prompt with some keypress and return to the consult-find command. I can kind of do this via `consult-dir`, by setting `consult-dir-default-command`, but not generically - since I don't know how to get the current consult command.

Any suggestions?

**Comment by minad** [comment]
You can adapt the solution from #596.
