### ISSUE TITLE
consult-xref: No preview for xref-etags-location

### ISSUE THREAD

**Issue by ZeaLot4J** [minad/consult#606]
After setting xref-show-definitions-function as consult-xref, it results in "No preview for xref-etags-location" when I invoke xref-find-definitions at c++ functions with etags, but the *xref* buffer works fine without consult-xref.

![image](https://user-images.githubusercontent.com/24864820/178272642-64a9b400-ef6b-410e-b581-bd1af00ad4e7.png)

emacs version: GNU Emacs 28.1 (build 2, x86_64-w64-mingw32) of 2022-04-09

emacs -q
`
(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
	("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(package-refresh-contents)
(package-install 'consult)
(package-install 'vertico)

(vertico-mode)

(require 'consult)
(setq xref-show-xrefs-function #'consult-xref
         xref-show-definitions-function #'consult-xref)
`

**Comment by ZeaLot4J** [comment]
Your actions are so fast! thanks a lot for your excellent work!

**Comment by ZeaLot4J** [comment]
The similar problem occurs with "No preview for xref-elisp-location": 
![image](https://user-images.githubusercontent.com/24864820/178486077-66a527bf-8078-4005-a466-0dc40fe44896.png)

**Comment by ZeaLot4J** [comment]
Firstly, open builtin project.el and search the function "project-find-file-in", then invoke xref-find-definitions at the "project-files" in the screenshot above, any other config info is as same as my first comment here.

**Comment by minad** [comment]
Thanks. I looked into `xref-elisp-location` again and we can indeed not support it easily. As you see in your screenshot above, the line number is 0, which means that the information is not available. Therefore it would require a lot of effort to implement previewing these locations. One would have to reimplement `xref-location-marker` and `find-function-search-for-symbol` from scratch with preview in mind.

**Comment by ZeaLot4J** [comment]
OK, I got it, anyway thanks for your work
