### ISSUE TITLE
consult command closer to point

### ISSUE THREAD

**Issue by abcdw** [minad/consult#609]
Hi everyone!

How hard is it to implement the following behavior for consult-org-heading, consult-imenu and similiar?

It would be cool to set the current candidate to the one which is closest to the point instead of the first one.

To be more clear, I'll give an example: Imagine I'm on the line 92 in magit.el, my point is on `(defface magit-hash` line and I open consult-imenu. I would like to get the following state:

![image](https://user-images.githubusercontent.com/1218615/178487493-c8358313-8757-4be8-ba45-c4a56894a1e0.png)

but I get:
![image](https://user-images.githubusercontent.com/1218615/178488058-62187605-a9c0-49f8-97e9-33d7e54b1a59.png)

**Comment by minad** [comment]
Moving to the nearest line has been requested a few times for `consult-imenu`, `consult-outline` and `consult-org-heading`. Unfortunately this is not something we get as naturally as in `consult-line`.

In `consult-line` we only support searching from the nearest line by wrapping around the lines of the buffer. We could do the same for the other commands. Still, you won't get to the state you have in your screenshot if we don't add special treatment to both Vertico and Consult, which is conceptually undesired.

The other cheaper approach is to just set `:default` to the nearest line, but this will also not give you the desired result. It will instead move the default candidate to the top in Vertico. See https://github.com/minad/consult/wiki#pre-select-nearest-heading-for-consult-org-heading-and-consult-outline-using-vertico for such an attempt. You can also search the issue tracker for previous discussions.

**Comment by minad** [comment]
Duplicate #366, #462
