### ISSUE TITLE
Can't install using use-package

### ISSUE THREAD

**Issue by veronikazaglotova** [minad/consult#61]
```
(use-package consult
  :straight t
  :bind
  ("C-x b" . consult-buffer)
  ("M-y" . consult-yank-pop))
```
This is the error
```
Debugger entered--Lisp error: (error "Could not find package consult in recipe repositor...")
  error("Could not find package %S in recipe repositories: ..." consult (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))
```

**Comment by SebastienWae** [comment]
`Consult` has been on MELPA for only 2 weeks, have you updated your recipe repositories recently?
[github:straight.el/README.md#how-do-i-update-melpa-et-al](https://github.com/raxod502/straight.el/blob/4656560c49ae7545ee7d6c3847057e03a60c047b/README.md#how-do-i-update-melpa-et-al)

**Comment by minad** [comment]
@veronikazaglotova @SebastienWae Actually it has been on MELPA for only three days - but note that the package has been split recently and MELPA has not pulled the update yet. If you are using straight, you may want to use the git repository directly for now.
