### ISSUE TITLE
Get list of candidates without prompt

### ISSUE THREAD

**Issue by Qkessler** [minad/consult#615]
Hi there Daniel!

I'm currently working on moving my notes from `org-roam` to `denote`. Love the package so far. As part of my workflow, I build my org-agenda with a list of files that have the "project" tag, making the agenda dynamic and fast.

I'm trying to achieve that using `consult-ripgrep` or `consult-find`. Since I'm using the function non-interactively, I'm interested in getting the list of result candidates with an input string and dir, WITHOUT a prompt, for the function to run in the background without any user interaction.

I figured there must be a way to do that already, but I didn't find it in the code easily.

Thank you so much!
Best,
Quique.

**Comment by minad** [comment]
Consult is the wrong tool for that, since Consult is made for interactive use. You should instead use make-process and ripgrep/find directly. The make-process API is also used by Consult behind the scenes.
