### ISSUE TITLE
byte-code: Symbol’s function definition is void: compat--inhibit-prefixed

### ISSUE THREAD

**Issue by arjunkathuria** [minad/consult#617]
Hi @minad,

The entire error is the title. It recently started happening.

i can't switch buffers, search with ripgrep or do other basic tasks.
i searched around a bit and i do have the `compat` package installed

is this already reported or is this a "check your setup" issue?

**Comment by minad** [comment]
Report this on the compat tracker please.

**Comment by arjunkathuria** [comment]
Alright, thanks.

**Comment by oantolin** [comment]
In the meantime, reinstalling `compat` worked for me.
