### ISSUE TITLE
multiple sources - select only tramp buffers or non-tramp-buffers

### ISSUE THREAD

**Issue by fab6** [minad/consult#618]
Hi,
the `multiple sources option for further filtering, e.g. for eshell buffer I could use something like
```
(defvar  eshell-source
  (list :name     "Eshell Buffer"
        :category 'buffer
        :narrow   ?e
        :face     'consult-buffer
        :history  'buffer-name-history
        :state    #'consult--buffer-state
        :new
        (lambda (name)
          (with-current-buffer (get-buffer-create name)
            ;;(insert "#+title: " name "\n\n")
            (eshell-mode)
            (consult--buffer-action (current-buffer))))
        :items
        (lambda ()
          (mapcar #'buffer-name
                  (seq-filter
                   (lambda (x)
                     (eq (buffer-local-value 'major-mode x) 'eshell-mode))
                   (buffer-list))))))

(add-to-list 'consult-buffer-sources 'eshell-source 'append)
```

Now, I would like to only show buffers which are accessed via tramp or vice versa only buffers which are not accessed via tramp. 

Does anyone have a hint how to achieve this?
Thank you in advance!
Fab

**Comment by minad** [comment]
You can filter in the `:items` function similar to the eshell example. Use the `default-directory` of a buffer and check if it is remote. There exists the function `file-remote-p`. Alternatively you could match the directory against a regexp.

**Comment by minad** [comment]
See https://github.com/minad/consult/issues/224 for a similar question where preview is conditionally disabled for tramp buffers.

**Comment by fab6** [comment]
Hi,
thank you for the quick reply!
Actually I did not understand every detail of my `eshell` setup... with your comment and links I am trying this
```
(defvar  tramp-source
  (list :name     "Tramp Buffer"
        :category 'buffer
        :narrow   ?t
        :face     'consult-buffer
        :history  'buffer-name-history
        :state    #'consult--buffer-state
        :new
        (lambda (name)
          (with-current-buffer (get-buffer-create name)
            ;;(insert "#+title: " name "\n\n")
            (tramp-mode)
            (consult--buffer-action (current-buffer))))
        :items
        (lambda ()
          (mapcar #'buffer-name
                  (seq-filter
                   (eq (file-remote-p (buffer-local-value 'default-directory buffer)))
                   (buffer-list))
                  ))))

(add-to-list 'consult-buffer-sources 'tramp-source 'append)
```

The important lines seem to be these
```
(seq-filter
                   (eq (file-remote-p (buffer-local-value 'default-directory buffer)))
                   (buffer-list))
```
which should for my understanding filter the buffer-list; and this filtering should be done via the 2nd line, but this does not work... the resulting list is always empty.
Maybe you have another advice?

**Comment by minad** [comment]
> Maybe you have another advice?

I recommend that you try to understand the eshell source line by line. This applies to any code copied from READMEs, wikis or other platforms. Read the documentation of the functions which are used here. You will profit from good Elisp understanding in the long run if you stick with Emacs. Emacs is Emacs because you can hack it and extend it with your own code - otherwise you could just use another editor.

**Comment by fab6** [comment]
yes, this is certainly right...
