### ISSUE TITLE
consult-fd snippet does not open the selected file

### ISSUE THREAD

**Issue by cfal** [minad/consult#619]
apologies if this is a local config issue - i was trying the snippet at https://github.com/minad/consult/wiki#find-files-using-fd, but when selecting a file, it would just go from the `Fd: ` prompt in the minibuffer to a `Find file:` prompt prefixed with the selected file's directory, without opening the file. I had to remove `call-interactively` from the `find-file` invocation to prevent that from happening:

```
(find-file (consult--find (car prompt-dir) #'consult--fd-builder initial))))
```

**Comment by minad** [comment]
Indeed this snippet does not look correct. Feel free to update the wiki.
