### ISSUE TITLE
FR Add tags to consult-org-heading

### ISSUE THREAD

**Issue by memeplex** [minad/consult#620]
It would be very useful if we could filter headings also by tags. I mean, just adding the tags as part of the heading line. If it makes things easier, this could be restricted to tags directly included in the heading line and not inherited from ancestors. In combination with orderless this would implement very efficient note searching.

**Comment by minad** [comment]
Yes, sounds good.

**Comment by memeplex** [comment]
Thanks!

**Comment by rickalex21** [comment]
Is there a  multi for this? To search all tags in a project?

**consult-org-heading**
Only searches in the current file.

**consult-org-agenda**
Works great but only searches in agenda files, not projects.

A consult-tags and consult-tags-mulit would be nice.

Thanks

**Comment by memeplex** [comment]
What do you mean by "project"? As in project.el or projectile?

**Comment by rickalex21** [comment]
Yea searching projectile projects or passing a list and make the output
look like that of `consult-org-agenda`. 
```lisp
(consult--some-comand (list "~/Documents/foo" "~/Documents/bar"))
```
It looks like the answer "may" be in consult--multi, passing the correct arguments to `consult-org-heading`, or in "Multiple sources" docs. 
Sorry, still fairly new to elisp so I'm not sure. I want to search tags in 
different directories recursively.

consult-org-agenda output
![](https://i.imgur.com/gpy9cgR.png)
