### ISSUE TITLE
my-embark-preview needs some work. 

### ISSUE THREAD

**Issue by harizvi** [minad/consult#627]
In the wiki where my-embark-preview is defined, it used a function _embark-default-action_ which has since been removed. Can you please provide replacement code? 

See here: https://github.com/minad/consult/wiki#manual-preview-for-non-consult-commands-using-embark

**Comment by minad** [comment]
I think this code comes from Doom Emacs - checkout the Vertico module. @iyefrat maintains this module, so he can probably help with this.

**Comment by iyefrat** [comment]
I've updated the wiki with the current version we have on doom, let me know if you have any issues with it

**Comment by harizvi** [comment]
Thanks for updating the wiki, @iyefrat. It will be helpful for others as well. 

IIRC, the previous version of this function acted like a toggle to turn preview on. So as you moved up and down, it showed preview for prev and next entries. Is there a way to achieve that?
