### ISSUE TITLE
fold the result 

### ISSUE THREAD

**Issue by bodnarlajos** [minad/consult#628]
Hi,
first of all, thank you for your work I love the consult :)
How I can fold / unfold the consult-ripgrep command's result ?
Fold the result in the buffer by filename...
The outline-mode was mentioned but I don't know which hook what I need to use and if I use it via embark then the consult buffer start to behave strange.
Do you have any advice ?

**Comment by minad** [comment]
Yes. outline-minor-mode is your best bet. It should be possible to make this work in completions and embark collect buffers. But I haven't tried. I think in Emacs master outline/folding support should be provided ootb in completions buffers.

**Comment by bodnarlajos** [comment]
Thank you for your answer!
I've checked these hooks but maybe I'm looking for an other one.
the consult-ripgrep is open the minibuffer and show the result in the minibuffer as well ...
But the logic with outline-minor-mode is working well with the ripgrep-mode (rg). 
It's enough for me but I'll write an embark action to move to the ripgrep from the consult-ripgrep if it is necessery. it is because the base action to transform the consult-ripgrep buffer is transforming to grep buffer ...

**Comment by minad** [comment]
I don't understand. Folding in the minibuffer, e.g., with Vertico is not possible. Folding in the completions/embark/grep buffer on the other hand should work via outline mode.

**Comment by bodnarlajos** [comment]
I think in this case I should use the original ripgrep mode (rg) and in that case I can use outline-minor-mode in the ripgrep's buffer.
Maybe I need to write a function and use it with embark what can transform our consult-ripgrep search to a ripgrep search ... :)

**Comment by bodnarlajos** [comment]
Thank you for your help!

**Comment by oantolin** [comment]
Folding for consult-ripgrep results in embark collect buffers without any additional configuration.
