### ISSUE TITLE
Previews are still loaded when disabled and function called non-interactively

### ISSUE THREAD

**Issue by geolessel** [minad/consult#630]
First of all, thanks for a great package!

I have an issue though. I followed the README advice for disabling file previews. I use `consult-ripgrep` quite a bit and noticed an oddity. When I disable previews, `M-x consult-ripgrep` results correctly do not show previews. However, if I call `consult-ripgrep` non-interactively either in my own functions or with `eval-expression`/`M-:`, previews still show up.

I don't know if that is intentional or not, but I found it surprising. If it is intentional, is there a good place to document that? If it is not intentional, could that be fixed?

Thanks again!

**Comment by minad** [comment]
This is intentional. If you wrap consult-ripgrep in your own command, you have to disable previews specifically for your own command. The configuration relies on the value of this-command.

**Comment by geolessel** [comment]
Ok, thank you. That worked. Would you be open to modifying that section of the README to expose that information?

**Comment by minad** [comment]
Sure, feel free to open a PR such that the docs are more explicit about this.

**Comment by geolessel** [comment]
https://github.com/minad/consult/pull/631
