### ISSUE TITLE
Project files not listing all projectile files

### ISSUE THREAD

**Issue by pyrareae** [minad/consult#632]
I notice that `consult-buffer` and `consult-project-buffer` both do not seem to be aware of all of the files in a project, just a subset of them and I often need to use other commands such as `helm-projectile` to find what I need if it's not open in a buffer. Is this intended behavior or a bug?

**Comment by minad** [comment]
@pyrareae That's right. consult-buffer only lists recent files belonging to the current project. See consult-buffer-sources and consult--source-project-recent-file.

You can easily fix this if you want to see all files. Either write your own source (see the wiki) or use consult-projectile or consult-project-extra. These packages provide sources listing all files. You could add the source to consult-project-buffer-sources. But be aware that these sources will slow down the buffer switcher significantly for large projects. Iirc projectile at least caches the list of files.

**Comment by pyrareae** [comment]
@minad  Thank you, that completely answers my question!
