### ISSUE TITLE
how to enable modes during a preview

### ISSUE THREAD

**Issue by dppascual** [minad/consult#633]
Hi there, exposing a problem that I have when calling the function `consult-lsp-diagnostic`; it shows all errors reported by the lsp server; moving down between such errors, a preview of the file is loaded and the cursor is focused on the error. These preview doest not load lsp mode, so flycheck starts checking with other checkers (like go-test, etc) instead of lsp (global flycheck mode is enabled); it causes the icon of the flycheck in the modeline reports a different number of errors when previewed than loaded. A workaround is turning off global flycheck mode but I would like to know if it is possible to tell `consult` to enable a set of modes during a preview.

I've tried to set the following statement with no success.

```
(setq consult-preview-allowed-hooks (seq-union consult-preview-allowed-hooks '(lsp column-number))
```

**Comment by minad** [comment]
If you want to allow a certain global minor mode during preview, you can add the corresponding hook to consult-preview-allowed-hooks. For example the hook function global-font-lock-mode-check-buffers is allowed. It ensures that font-lock-mode is enabled in previewed buffers.

See also #542, #538, #515 for prior discussions regarding the mode handling. These discussions were more concerned about *disabling* modes, while you want to make sure that the LSP mode is still enabled.

You can also ask on the consult-lsp issue tracker about this. Ideally consult-lsp should make sure that this problem doesn't occur by allowing the relevant lsp mode hooks.

**Comment by minad** [comment]
@dppascual please always link to issues on other trackers or ping me there.

https://github.com/gagbo/consult-lsp/issues/32

**Comment by dppascual** [comment]
Thanks for your reply. I had already reviewed the prior issues but the variable that is mentioned in such discussions is already deprecated and I've tried with the new one `consult-preiew-allowed-hooks` with no success. 

The following statement doesn't work:

```
(setq consult-preview-allowed-hooks (seq-union consult-preview-allowed-hooks '(lsp column-number)))
```

I will review later on why it is not loaded.

Sorry, I'll ping you next time
