### ISSUE TITLE
Incompatible with Emacs 28

### ISSUE THREAD

**Issue by revcomninos** [minad/consult#635]
When I try to install `consult` in Emacs 28 I see this:

consult  20220807.1302  incompat  Consulting completing-read 

GNU Emacs 28.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-07-15

**Comment by minad** [comment]
I use Consult on 28. It is certainly compatible. 

However I've also observed such installation issues with other packages. I don't know what causes this, some bug in package.el? Can you narrow the issue down a little bit better? Delete all emacs related files and try again. If the issue persists you can report it via report-emacs-bug.

**Comment by revcomninos** [comment]
Removing Melpa “bleeding-edge” repository and replacing it with the stable package fixed the issue.
