### ISSUE TITLE
`consult-line` is very slow in a huge buffer

### ISSUE THREAD

**Issue by akoptelov** [minad/consult#637]
How to reproduce:
Open a huge text file (>1_000_000 lines) in Emacs (it will suggest to open it literally). Then run `M-x consult-line`. Emacs will be very sloppy to give the consult prompt, and it will be quite hard to work with consult as it will pause for second(s) after each change of the search pattern.

Reproducible with vertico/default completion.
Emacs version: 28.1
OS: GNU/Linux Ubuntu 20.04

With ~100 Klines file it takes a moment on my machine to see the command prompt, with 1 Mline text file, this is several seconds.

It looks like consult uses `consult--each-line` macro that has linear complexity to the file size, and only after that it issues the prompt.

I know that this is quite rare case to view such files in Emacs, but with the current issue I need to use something different to search for text in such huge files. It would be great if `consult` would handle this case as well.

**Comment by minad** [comment]
That's okay. You can use `occur` on large buffers for a non-interactive search. See also #487.

**Comment by akoptelov** [comment]
Hmm... I thought about  e.g. `consult-ripgrep` working with much bigger amount of data, but giving it a second thought, it is `ripgrep` that does initial filtering... Yeah, that makes sense. 

Also I was thinking about a warning to be issued if the buffer is bigger than some threshold, that it might not be suitable for interactive search, but I guess this is for higher level of integration, so e.g. `isearch` can be used instead.

**Comment by minad** [comment]
> Also I was thinking about a warning to be issued if the buffer is bigger than some threshold, that it might not be suitable for interactive search, but I guess this is for higher level of integration, so e.g. isearch can be used instead.

Yes, I've also considered that, given that the issue has come up a few times now. I want to keep the simplicity of `consult-line` itself and not change it such that it performs prefiltering as proposed in #417. My idea is to introduce a `consult-line-threshold` variable and a `consult-line-fallback` variable. Then the user can configure the desired behavior in their configuration.

~~~ elisp
(setq consult-line-threshold 100000000)
(setq consult-line-fallback (lambda () (error "Buffer too large"))
(setq consult-line-fallback (lambda () (consult-ripgrep ...))
(setq consult-line-fallback (lambda () (occur ...))
~~~

**Comment by minad** [comment]
Hmm, but then the threshold is hardly sufficient. For example consult-line will probably also have degraded performance for files with long lines. There is no way we can protect against all the edge cases. Overall it is not such a big deal since you can always press C-g. Interestingly there was an issue that Emacs got slow even after C-g of an aborted consult-line (#517), due to marker allocations, since the markers are maintained in a linked list internally in Emacs. We've resolved this issue since then.

**Comment by akoptelov** [comment]
BTW, it's not like C-g always possible. I need to double-check that, probably this is also because of `vertico`, but with my 12Mline file Emacs stuck completely.

**Comment by akoptelov** [comment]
> There is no way we can protect against all the edge cases.
True.... This is just my laziness that prevents me to e.g. use awk or similar for this particular case, and try to do it in Emacs.

**Comment by minad** [comment]
> BTW, it's not like C-g always possible. I need to double-check that, probably this is also because of vertico, but with my 12Mline file Emacs stuck completely.

C-g should be always possible. Vertico also shouldn't prevent that in any way. If not, it is an Emacs bug. I think in your case, Emacs could be stuck in the GC. The Emacs GC definitely needs improvements. But tbh your 12M line fill is just massively over the top. As you wrote, some external scripting is more appropriate.

**Comment by minad** [comment]
The stucking issue of C-g has been fixed in Consult, see https://github.com/minad/consult/issues/517.
