### ISSUE TITLE
ESS, consult-buffer and all-the-icons: 'R' icon not used for ESS[R] buffers

### ISSUE THREAD

**Issue by maxecharel** [minad/consult#638]
When using e.g. `find-file`, the appropriate icon is displayed:
![find-file_r_icon](https://user-images.githubusercontent.com/61969138/187908067-a485ee94-e409-4ff3-8bfc-a10747af0789.png)

This is however not the case with `consult-buffer`:
![consult-buffer_no_r_icon](https://user-images.githubusercontent.com/61969138/187908318-4675a88d-909f-455a-a092-ef9f7d1889a1.png)

My guess is that it is due to the fact that it is an `ESS[R]` (see previous picture) buffer, and that it is not associated with the R icon provided by the `all-the-icons` package (no problem with e.g. Org files and buffers).

I am not sure whether it is the appropriate repo for reporting this issue; sorry in advance if it isn't.  

(Consult 20220831.1135)
(Emacs 28.1)
(Kubuntu 22.04.1 LTS)

**Comment by minad** [comment]
This should be reported to the icons issue tracker. Thanks!

**Comment by maxecharel** [comment]
Ok thanks, I do that right away
