### ISSUE TITLE
Clarify location of consult-{selectrum,flycheck} in README

### ISSUE THREAD

**Issue by aspiers** [minad/consult#64]
Hi, firstly thanks for your awesome work here! I'm excited to be trying out consult for the first time, and just copy-pasted the suggested `use-package` sexps into my config files. However I'm using straight.el, and the sexps for `consult-selectrum` and `-flycheck` didn't work because straight.el didn't know to get them from the `consult` package.  Adding `:straight consult` fixed this:

```elisp
(use-package consult-selectrum
  :straight consult
  :demand t)

;; Install the consult-flycheck command.
(use-package consult-flycheck
  :straight consult
  :bind (:map flycheck-command-map
         ("!" . consult-flycheck)))
```

so I'd suggest mentioning that in the README.

**Comment by aspiers** [comment]
BTW this is slightly offtopic, but I'm also wondering why the `:demand t` was suggested instead of `:after selectrum`?

**Comment by minad** [comment]
@aspiers I don't want to add an additional note to the readme - there is the note in the beginning. You can simply download the files manually. But I hope that melpa pulls the update soon, see https://github.com/melpa/melpa/pull/7287.

**Comment by minad** [comment]
`:after selectrum` would work too, but it does not matter. if you demand the consult-selectrum it will require selectrum and everything will be alright.

**Comment by aspiers** [comment]
Thanks for the quick reply!

[**@minad**](https://github.com/minad) commented on [December 13, 2020 7:02 PM](https://github.com/minad/consult/issues/64#issuecomment-744052914 "2020-12-13T19:02:19Z - Replied by Github Reply Comments"):
> [@aspiers](https://github.com/aspiers) I don't want to add an additional note to the readme - there is the note in the beginning. You can simply download the files manually.

Unfortunately downloading files manually would negate many of the benefits of using a package manager like straight.el.

> But I hope that melpa pulls the update soon, see [melpa/melpa#7287](https://github.com/melpa/melpa/pull/7287).

Ah OK great, that is even better than having to add a `:straight` directive :-)

**Comment by minad** [comment]
> Unfortunately downloading files manually would negate many of the benefits of using a package manager like straight.el.

Yes, sure - this is not what the final user experience will be. But please stay patient. This will soon be on melpa.

**Comment by aspiers** [comment]
Yup understood - my `:straight` workaround is absolutely fine for now so I can wait patiently!  Thanks again :-)
