### ISSUE TITLE
Jump to line without closing the minibuffer

### ISSUE THREAD

**Issue by mattiasdrp** [minad/consult#641]
If I hit enter on a `consult-ripgrep` minibuffer candidate it closes the minibuffer and jumps to the corresponding line. Is there an easy way to jump without closing the minibuffer which would allow me to not have to restart my search (I want to edit multiple lines and the lines below so using `embark-collect-all` doesn't fit my needs)?

**Comment by minad** [comment]
Yes, embark-dwim with embark-quit-after-action=nil. Please take a close look at the relevant READMEs: Vertico, Consult, Embark and Orderless. It should be possible to figure this out from the existing documentation.

**Comment by minad** [comment]
You can also move from the minibuffer to the previewed buffer and back, assuming that you have preview enabled. This is called recursive editing. You can even start another nested/recursive minibuffer session.

**Comment by mattiasdrp** [comment]
I tried with embark-dwim but it does nothing:

![image](https://user-images.githubusercontent.com/5543639/188138678-4633227d-edbc-4a60-8ad7-42bbfc41f8c5.png)

If I understand correctly `embark-dwim` should call `consult-ripgrep` but nothing happens. I guess something is wrong with my config.

Anyway, I bound `C-<up> ` to `other-window` in the vertico map and it works perfectly well.

Sorry for the noise, I tried reading all the READMEs thinking I missed something but looks like the behaviour I have is unexpected.

**Comment by minad** [comment]
Maybe you don't observe anything thanks to the preview? Also did you install embark-consult?

**Comment by mattiasdrp** [comment]
Yes, embark-consult is installed. I just wanted a keybind to jump directly to the preview buffer without closing the minibuffer. `embark-dwim` is not really doing the trick, `other-window` is simetimes buggy but at least it works.

**Comment by minad** [comment]
Ah, your only issue is that you want to execute embark-dwim+other-window. You can use a keyboard macro for that and bind it to a key.

**Comment by mattiasdrp** [comment]
Oh, yeah, that was actually simple instead of binding other-window to a key in the embark keymap :D 

Thanks a lot! Don't know why I didn't think about it :D
