### ISSUE TITLE
Strange "character" when copying from `consult-buffer`

### ISSUE THREAD

**Issue by salutis** [minad/consult#645]
Reproduction steps:

1. `M-x consult-buffer`
2. `M-w` to copy the buffer name
3. `C-y` in some buffer to "paste"

Expected: 

Emacs inserts the buffer name, e.g. `*scratch*`

Actual:

Emacs inserts the buffer name but also some strange "character".

(The strange character also poisons the `savehist` which then cannot save as UTF-8.  The mysterious "character" has code point 2097154.)

Screenshot:

<img width="834" alt="Screen Shot 2022-09-14 at 21 17 42" src="https://user-images.githubusercontent.com/1158274/190243671-000b610e-705a-4d9b-b5c0-428a85a4cf3c.png">

**Comment by minad** [comment]
These are disambiguation tofus, search for tofu in the Consult source. You will observe them when accessing the raw candidate strings. But if you use Embark for copying/inserting they will be removed by some candidate transformation function. The "poisoning" of savehist shouldn't have negative consequences.

**Comment by salutis** [comment]
@minad Thank you for the explanation.  So to copy buffer names without "tofu", I need to install the Embark package?

**Comment by minad** [comment]
Well you could also write your own copy command which strips the tofus. But installing Embark is highly recommended anyway. Embark is a brilliant package.

**Comment by salutis** [comment]
> Well you could easily write your own copy command which strips the tofus. But installing Embark is highly recommended anyway. Embark is a brilliant package.

So I installed Embark, and now I can copy from `consult-buffer` with `M-x embark-act` followed by `w`, but I cannot do the same from `consult-outline`, to create Org links, because there, Embark copies with the "tofu".  I wonder, could `vertico-save` strip the "tofu" when used interactively via `M-w`?

**Comment by oantolin** [comment]
> I cannot do the same from consult-outline, to create Org links, because there, Embark copies with the "tofu".

This sounds like you have not loaded the `embark-consult` library, @salutis. Once you do the tofus should be stripped.

**Comment by oantolin** [comment]
If this is the only thing you use Embark for, you could uninstall it and write advice for `vertico-save` to remove the tofus.

**Comment by salutis** [comment]
Thank you again for getting in touch!  I do not want to swim upstream, so I installed Embark.  I figured that, if something as fundamental as copying text in a text editor relies on some package, I should probably not avoid the package, or I might find myself maintaining a lot of custom code as times goes by.  I surrender the tight coupling.  😄
