### ISSUE TITLE
ability to chain a sequence of ripgrep searches

### ISSUE THREAD

**Issue by edgimar** [minad/consult#647]
Currently the way that `consult-grep` works when searching for `#A#B` is to have ripgrip search in the current folder for `A`, and then to narrow the results by having emacs search these results (i.e. single lines) for `B`.  This is fine if you're looking for two terms in the same line.  It is a problem if you want to find all files that have `A` and `B` in them in different places (potentially on different lines) within the same file.

One more general way of dealing with this problem would be to take the files returned after the ripgrep search for `A`, and pass this file-list as inputs to a second ripgrep search for `B` (where ripgrep only searches the files that matched `A`).  The question is whether it would be possible to have a different kind of `consult-grep` that calls ripgrep for each search term (each term resulting in a narrowed file-set)?  Or maybe there's some other/better way of achieving this kind of a search (for multiple search-terms -- not just 2)?

**Comment by minad** [comment]
Are you looking for a command which finds files or a command which finds lines?

consult-ripgrep is fundamentally a line-based command. But you could use rg and configure it as command to search for files via consult-find. Then it may be possible to search for multiple terms in different lines. Note that you can always write shell scripts which take some argument and produce output in find or grep format. Then this script can be used by consult-(rip)grep or consult-find. See the variable consult-grep-args. I hope this helps and you figure out a way to solve your issue. 

The question goes a bit too far for Consult. Consult aims to wrap commands as a thin layer. Combining multiple commands is out of scope. Therefore I close this. Anyway feel free to comment here or add your solution to the wiki.
