### ISSUE TITLE
consult-preview not working for recent version of org-mode

### ISSUE THREAD

**Issue by theottm** [minad/consult#648]
Hello,

it seems the preview functionality is not working any more in .org files when using the current `main` branch of org-mode (currently `be2246a55`). I downgraded to `release_9.5.5` and the problem was gone.

Concretely the problem arose in the following form: when using consult-line to preview a line which is under a folded headline, the headline stays folded. It seems as if `org-reveal` is not called. I tried myself to call `(progn (goto-line 757) (org-reveal))` and it successfully goes to this line which was hidden and unhiddes it.

This is probably an `org-mode` bug but I thought I would post an issue here because I only encountered this problem using `consult-line` and all my other functions relying on `org-reveal` work fine. So maybe you will have a better idea of which functionality on which `consult` relies could have been broken.

I was able to reproduce the issue with only straight, vertico, consult and org loaded.

The `release_9.5.5` tag is only two weeks and ~40 commits late so there is still the option to just test every single commit to pin down the right one... But honestly if there is an easier way I would be glad :)

**Comment by minad** [comment]
Duplicate #563. I don't support unreleased versions. But I am happy to accept a patch fixing the issue with the new org-fold functionality.
