### ISSUE TITLE
Consult-line initially fails to search in org-mode

### ISSUE THREAD

**Issue by smsegal** [minad/consult#65]
When I try and use `consult-line` in an org file, I get this error:
```
Error during redisplay: (jit-lock-function 228) signaled (error "Invalid face" font-lock-comment-face org-block)
face-attribute: Invalid face: font-lock-comment-face, org-blockError during redisplay: (jit-lock-function 228) signaled (error "Invalid face" font-lock-comment-face org-block)
```
I have custom fonts set for `font-lock-comment-face` with `(set-face-attribute)`, but I don't modify the `org-block` face anywhere. If I repeat the command a few times, it will eventually work. 

I'm running on Emacs27 on linux. Updated to the latest consult (`3471514`) at the time of writing and the issue still occurs. Org version 9.4.2.

Thanks for your help!

**Comment by minad** [comment]
Can you please try without your face modifications? Ideally with emacs -Q. Furthermore a stack trace would be helpful.

**Comment by smsegal** [comment]
Sure, will do. Do you have a convenient way of loading consult/selectrum etc with `emacs -Q`? I'm loading them with straight.el currently. 
Can currently confirm that the issue still occurs when all of my custom font settings are disabled.

**Comment by minad** [comment]
> Do you have a convenient way of loading consult/selectrum etc with emacs -Q?

No. I load the files manually step by step (load "...") etc.

**Comment by minad** [comment]
It would also be helpful if you have a minimal org file around which reproduces the issue, such that I could try to debug this.

**Comment by smsegal** [comment]
Right. Just checked with a minimal config where I load only org, selectrum, and consult. The issue doesn't occur with that setup, which unfortunately means I have to do some config bisecting. I'm out of time tonight but I'll hopefully have some time tomorrow to find a minimal set of steps for reproducing.

**Comment by minad** [comment]
Ok. If you look into this - the relevant function in consult is `consult--fontify`, which does not do much. See here https://github.com/minad/consult/blob/024bf01f0f16c404744e563c9d0be37750a82d1b/consult.el#L251. Maybe some check is missing there, but it could very well be that the issue lies somewhere else.

**Comment by minad** [comment]
I just looked what ivy/swiper does - they have a large list of excluded major modes https://github.com/abo-abo/swiper/blob/ae9b121b834a68d11f79ca27b1e5c8790149ba2f/swiper.el#L458

**Comment by minad** [comment]
@smsegal Any chance to investigate this? From the error message and since you are not seeing the error when loading via emacs -Q, I suspect there is something wrong with the face definitions you are using somewhere.

**Comment by smsegal** [comment]
Found the offensive package! After an arduous bisecting of my config, the package that breaks consult is (drumroll please) [adaptive-wrap](https://elpa.gnu.org/packages/adaptive-wrap.html). With this disabled, there's no problem at all with consult-line or anything else. 

Here's a minimal init file that you can repro with:
```lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)

    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'org)
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package selectrum
  :commands selectrum-next-candidate selectrum-previous-candidate
  :hook
  (after-init . selectrum-mode))
(use-package prescient
  :hook (selectrum-mode . prescient-persist-mode))
(use-package selectrum-prescient
  :hook (selectrum-mode . selectrum-prescient-mode))
(use-package company-prescient
  :hook (company-mode . company-prescient-mode))
(use-package consult
  :straight (:host github :repo "minad/consult")
  :init
  :hook (after-init . consult-preview-mode))
(use-package consult-selectrum)

(use-package adaptive-wrap
    :hook ((prog-mode text-mode) . adaptive-wrap-prefix-mode))
```

**Comment by minad** [comment]
@smsegal Thanks for looking into this. I have to check what the issue is here - never used this adaptive-wrap package. But from the side of consult, we are not doing anything weird here - so it could also be a bug in adaptive-wrap. Never had any issues with it before?

**Comment by smsegal** [comment]
IMO it's a bug in adaptive-wrap. I recently started using org-mode more heavily so that's likely why I haven't noticed before.

**Comment by minad** [comment]
@smsegal This is my suspicion too. Could you file an issue there and report back here?

**Comment by smsegal** [comment]
Well, it's an ELPA package so I'll have to figure out ~M-x report-emacs-bug~ and the mailing list, so might take some time to hear anything. (Also, who's scared of the mailing list? not me thats for sure)

**Comment by minad** [comment]
@smsegal Thank you! Please let me know if something comes up or if you notice something else consult-related.
