### ISSUE TITLE
Using Vi style Regex in Grep and Find commands

### ISSUE THREAD

**Issue by M-Gregoire** [minad/consult#650]
I'm an Evil mode user and heavily rely on `:s/` for search & replace edits in buffers. 

However, when comes the need to make some replacement across a project/multiple files, I use `consult-ripgrep` mostly. The documentation states:
> Always use Emacs regular expressions at the prompt.

Unfortunately, for complex regex, moving between Vim style Regex and Emacs ones is a painful experience. To get a more unified experience, I'd like to use Vim Regex everywhere.

I've seen a `consult--regexp-compiler` variable inside your code but I'm not proficient enough in Lisp to know whether this can be leverage to achieve what I want.

Is there anyway of using Vim regex style? If not, can this be considered a feature request?

Thank you

**Comment by minad** [comment]
Supporting other regexp types  is out of scope of Consult. But to get you started - the simplest "regexp compiler" you could use just passes the input through to ripgrep:

~~~ elisp
(defun pass-through-compiler (input _type _ignore-case)
  (cons
   (list input) ;; List of regexps passed to ripgrep
   nil))        ;; Highlight function
(setq consult--regexp-compiler #'pass-through-compiler)
~~~

The downside with this snippet is that we don't get highlighting. We don't return a highlight function, since the input is in ripgrep regexp format but we need Emacs format. You could then  convert the ripgrep regexp format (PCRE minus some features) to Emacs format. You have to write a function `convert-to-emacs-regexp`.

~~~ elisp
(defun pass-through-compiler (input _type ignore-case)
  (cons
   (list input)
   (let ((regexp (convert-to-emacs-regexp input)))
     (when (consult--valid-regexp-p regexp)
       (apply-partially #'consult--highlight-regexps (list regexp) ignore-case)))))
(setq consult--regexp-compiler #'pass-through-compiler)
~~~

(I disagree that moving between regexp types is difficult. In order to write Elisp you have to learn Emacs (also called extended) regexp syntax anyway and proficiency in Elisp will help you a lot when using Emacs. Emacs is Elisp.)

**Comment by minad** [comment]
I think there has been some discussion to add regexp converting capabilities to Emacs itself such that Isearch and other prompts would accept Perl-style regexps. But as far as I know this hasn't materialized yet in Emacs master. 

There also exists https://github.com/joddie/pcre2el which allows you to convert between different regexp types. If you use that library it should be possible to make the transformations from above. Unfortunately the library seems unmaintained as of now. So far I've avoided adding it to my Emacs configuration despite that I've used Perl quite a bit and also preferred Perl-style regexps for a long time. 

In https://github.com/joddie/pcre2el/issues/10 the author even wrote 8 years ago:

> As you can probably tell, pcre-mode is a bit half-baked so I have been reluctant to advertise it, but I guess it is better to have people use it and report the bugs. ;-)

**Comment by M-Gregoire** [comment]
Thank you @minad for taking the time to make a so well described answer!

I guess I should probably add "Learn Emacs Lisp and Emacs Regex" to my Todo list then. I was reluctant to learn both types of Regex (Sometimes one is hard enough!) but this is probably better than trying to force Vim regex into Emacs...

**Comment by minad** [comment]
The main difference is really only the escaping of parentheses and pipes. In case you are interested, see my conversion function from Emacs regexp syntax to PCRE regexp syntax:

https://github.com/minad/consult/blob/76aab86015c3d7628dbd5f92b2dd8ab9aeadac8d/consult.el#L571-L614

I could have chosen as well to convert in the other direction, but given that Emacs syntax is so prevalent for Emacs commands I went with that. Anyway, I left the backdoor consult--regexp-compiler for people who dislike the Emacs syntax too much. ;)

**Comment by M-Gregoire** [comment]
Hey again @minad ,

I have a somewhat related question, but If you prefer I can open another issue!

I'm trying to match everything between `a` and `z` in the following case:
```
a
g
d
y
z
```

`.*` wouldn't work, as it doesn't match newlines. I've tried matching newlines with `C-q C-j` or the Regular expression recommended by [Emacs Wiki](https://www.emacswiki.org/emacs/MultilineRegexp).

I've also looked on the `rg` side with the `(?s)` flag but all my tries have failed.

Is `consult-ripgrep` able to handle multiline regex? If not, is there could alternatives you could recommend?

Thanks a lot for your help.

**Comment by minad** [comment]
Multiline searches are not supported by consult-ripgrep. The command is fundamentally line based in its current form. But we could extend it somehow if there is interest. See https://github.com/minad/consult/issues/629

**Comment by M-Gregoire** [comment]
Again, thank you for your quick answer! Sorry I missed the issue regarding multi-line regex.

My use case is the following. I have a code which looks somethings like:

```
var1 = "Blabla"

array_definition = [
  "var1"
  "var2"
  "var3"
]

array_definition2 = [
  "var1"
  "var2"
  "var3"
]
```

Let's say I want to prefix all strings in `array_definition` by `test-` but not in `array_definition2` across all files in my project.
As far as I know, using `consult-ripgrep` to multi-line match something like `array_definition = [ (.*(\n))* ]`, then using `embark-export-write` I could easily add the prefix.

I don't see any way of doing this quickly otherwise. If there I not, I things #629 might be of interest.

What do you think?

**Comment by minad** [comment]
Use Emacs keyboard macros?

**Comment by M-Gregoire** [comment]
This might be a edge-case but this type of changes happens quite often in my projects.
Given I might have hundreds of files, and a subset of them would have a similar definition, having the ability to edit all of them at the same time would be a game changer.

In the mean time, I will probably fallback to a `sed` or similar CLI tool.

If you believe this is inline with your vision of `consult`, then please consider multiline regex a feature request as in #629

**Comment by hmelman** [comment]
Use another interface to ripgrep like `rg.el`.  It can do multiline searches and results in a `*grep*`-like buffer which you can then use `wgrep` on and change all the results at once and then save all the files.  IMHO isn't the right use case for `consult-ripgrep`.

**Comment by M-Gregoire** [comment]
Thank you @hmelman !

I've tried `rg.el` with `wgrep` and can confirm It works wonder with multi-line results. This is exactly what I was looking for!

**Comment by woolsweater** [comment]
If you still want to use `consult-(rip)grep`, @M-Gregoire, I have a small package that provides the ability to use PCRE regex as input to those commands: https://git.sr.ht/~woolsweater/uncongregate.el (It doesn't change anything about multiline support, however.)
