### ISSUE TITLE
consult-buffer default entry and sorting order

### ISSUE THREAD

**Issue by ville-h** [minad/consult#651]
Currently `consult-buffer` default entry and sorting order appears to be affected by buffers' visibility in other windows. Similarly how the default `switch-to-buffer` is.

As an example 2-window layout: `window0: buffer0` and `window1: buffer0`. Switch `window0` to display `buffer1`. Trying to switch `window0` back to `buffer0` the entry for `buffer0` is placed somewhere towards the bottom of the list rather than offered as the default entry. Presumably because `buffer0` is already visible in `window1`?

How do I fix consult-buffer to not consider what buffers may be visible in other windows? A helpful individual on irc demonstrated how to do it for the default `switch-to-buffer`:
```
(global-set-key (kbd "C-x b")
                (lambda () (interactive)
                  (let ((b (current-buffer))
                        (prompt "Switch to buffer "))
                  (switch-to-buffer
                   (read-buffer prompt (other-buffer b t))))))
```

**Comment by minad** [comment]
You can modify the buffer source and adjust the sorting, e.g., :sort=nil:

https://github.com/minad/consult/blob/76aab86015c3d7628dbd5f92b2dd8ab9aeadac8d/consult.el#L4171-L4173

**Comment by ville-h** [comment]
Just confirming that you're suggesting I manually edit `consult/consult.el`? I can't do it from my `init.el`? Wouldn't I lose those changes any time the package is updated?

Could this be a configuration setting?

**Comment by minad** [comment]
No, you should modify the value of consult--source-buffer.

**Comment by ville-h** [comment]
Alright managed to beat the mini boss of elisp getting the syntax right?
```
    (plist-put consult--source-buffer :items
        (lambda()
            (consult--buffer-query :sort 'visibility :as #'buffer-name)
        )
    )
```
But it doesn't appear to do what I wished it would. It doesn't present the buffers in most-recently-used order.

**Comment by ville-h** [comment]
Alright think I managed to get it done. Just setting `:sort nil` wouldn't quite do it. It would mean the buffer you're switching away from is offered as the default option. Something like this appears to have done it:
```
(defun consult--buffer-sort-mru(xs)
    (append (cdr xs) (list (car xs)))
)
```
and then:
```
    (plist-put consult--source-buffer :items
        (lambda()
            (consult--buffer-query :sort 'mru :as #'buffer-name)
        )
    )
```
Apparently `consult--buffer-query` looks for functions that begin with 'consult--buffer-sort-' rather than taking the actual function to call. https://github.com/minad/consult/blob/76aab86015c3d7628dbd5f92b2dd8ab9aeadac8d/consult.el#L3999

**Comment by ville-h** [comment]
Seems like my solution doesn't quite work. Right after `kill-buffer` the current buffer ends up as the first candidate for `consult-buffer`. How can I fix this?
