### ISSUE TITLE
How to make `consult--read` return a candidate along with its text properties?

### ISSUE THREAD

**Issue by rdrg109** [minad/consult#652]
- [The context](#orgd20f4e3)
- [The problem](#orgd48f4ae)
- [The question](#org80c5376)
- [Additional information](#orgfd04946)

<a id="orgd20f4e3"></a>

# The context

Suppose that I'm interested in managing my bookmarks within Emacs. I want to be prompted by a bookmark and be able to search them by their titles (I've assigned them beforehand) instead of their URLs. For example, a prompt would look as that shown by evaluating the code block shown below.

```elisp
(completing-read "Bookmark: "
                 '("GNU"
                   "Gentoo"
                   "Python"))
```

The candidate list shown by the code block above is incomplete because the title of each bookmark is not related to an URL. We can relate the title to its URL by embedding the URL as a text property (see below).

```elisp
(let ((titles '("GNU"
                "Gentoo"
                "Python"))
      (urls '("https://www.gnu.org"
              "https://www.gentoo.org"
              "https://www.python.org"))
      candidates)
  (cl-loop
   for i from 0 to (1- (length titles))
   do (progn (add-text-properties 0 1 `(url ,(nth i urls)) (nth i titles))
             (push (nth i titles) candidates)))
  candidates)
```

```
(#("Python" 0 1 (url "https://www.python.org")) #("Gentoo" 0 1 (url "https://www.gentoo.org")) #("GNU" 0 1 (url "https://www.gnu.org")))
```

The main reason why I attach the URL as a text property is because `embark-act` can access the text property of a candidate, so we can use `embark-url-map` to execute actions as if our bookmarks were URLs (even though we are showing their titles).

We can tell `embark` that a bookmark has its URL as a text property. We can do so by using a transformer. This will let `embark` know that a `bookmark-web` should be transformed to a type `url` and that the URL is stored as a text property in the first character, so that we can use all the actions in `embark-url-map`.

```elisp
(defun my/bookmark-web-get-url (type target)
  (cons
   'url
   (plist-get
    (text-properties-at 0 target)
    'url)))

(add-to-list 'embark-transformer-alist '(bookmark-web . my/bookmark-web-get-url))
```

With the following sexp, we are prompted with a bookmark and we can also use `embark-act`.

```elisp
(let ((titles '("GNU"
                "Gentoo"
                "Python"))
      (urls '("https://www.gnu.org"
              "https://www.gentoo.org"
              "https://www.python.org"))
      candidates)
  (cl-loop
   for i from 0 to (1- (length titles))
   do (progn (add-text-properties 0 1 `(url ,(nth i urls)) (nth i titles))
             (push (nth i titles) candidates)))
  (consult--read candidates
                 :category 'bookmark-web)))
```

<a id="orgd48f4ae"></a>

# The problem

The issue is that `consult--read` returns the candidate without its text properties.

The code block below shows that the return value is a string without its text properties.

```elisp
(let ((titles '("GNU"
                "Gentoo"
                "Python"))
      (urls '("https://www.gnu.org"
              "https://www.gentoo.org"
              "https://www.python.org"))
      candidates)
  (cl-loop
   for i from 0 to (1- (length titles))
   do (progn (add-text-properties 0 1 `(url ,(nth i urls)) (nth i titles))
             (push (nth i titles) candidates)))
  (consult--read candidates
                 :category 'bookmark-web)))
```

```
Python
```

Using a `:lookup` function is useless because it seems that the text properties are already stripped off. See what's passed to the lookup function in the code block below.

```elisp
(defun my/lookup-function (&rest r)
  (princ (format "foo: %s" r)))

(let ((titles '("GNU"
                "Gentoo"
                "Python"))
      (urls '("https://www.gnu.org"
              "https://www.gentoo.org"
              "https://www.python.org"))
      candidates)
  (cl-loop
   for i from 0 to (1- (length titles))
   do (progn (add-text-properties 0 1 `(url ,(nth i urls)) (nth i titles))
             (push (nth i titles) candidates)))
  (consult--read candidates
                 :category 'bookmark-web
                 :lookup 'my/lookup-function))
```

```
foo: (Python (Python Gentoo GNU)  nil)
```

<a id="org80c5376"></a>

# The question

1.  How to make `consult--read` return a candidate along with its text properties? Is it possible with the current implementation?
2.  How to make `consult--read` provide the lookup function a candidate with its text properties? Is it possible with the current implementation?

<a id="orgfd04946"></a>

# Additional information

I had previously opened [an issue](https://github.com/oantolin/embark/issues/486) in the embark repository about making `embark-act` act on information that is not visible in the candidate list, because I wanted to make `embark-act` use the `cdr` of a candidate. I'm aware that the `cdr` of a candidate can be accessed with `consult` by specifying `consult--lookup-cdr` as the `:lookup` parameter. In that issue, I also learnt that `embark-act` could access text properties thanks to [a reply](https://github.com/oantolin/embark/issues/486#issuecomment-1093026175) from @minad.

**Comment by minad** [comment]
Returning text properties is not possible. You can use the :lookup function to lookup the candidate in the original candidate list, where the candidates are still propertized. In your case this doesn't seem to happen since you probably use a buggy completion, which modifies the candidate list. But this is a bug of the completion UI. Did you try your example in Vertico or default completion?

**Comment by minad** [comment]
I tried your example in Vertico and it seems that the problem is your lookup function. Try this and the properties should be visible:

~~~ elisp
(defun my/lookup-function (&rest r)
  (princ (format "foo: %S" r)))
~~~

Then I get

~~~
foo: ("GNU" (#("Python" 0 1 (url "https://www.python.org")) #("Gentoo" 0 1 (url "https://www.gentoo.org")) #("GNU" 0 1 (url "https://www.gnu.org"))) "" nil)"foo: (\"GNU\" (#(\"Python\" 0 1 (url \"https://www.python.org\")) #(\"Gentoo\" 0 1 (url \"https://www.gentoo.org\")) #(\"GNU\" 0 1 (url \"https://www.gnu.org\"))) \"\" nil)"
~~~
