### ISSUE TITLE
How to control completion styles used by consult-buffer?

### ISSUE THREAD

**Issue by lynnux** [minad/consult#655]
Hi minad, this config seems not affect `consult-buffer`:
```
(setq completion-category-overrides '((buffer (styles flex))))
```
But `switch-to-buffer` works.  `consult-buffer` only work if `(setq completion-styles '(flex))`

**Comment by minad** [comment]
consult-buffer uses the completion category `multi-category`. You could also adjust the `completion-styles` variable via `vertico-multiform-mode`.

**Comment by vspinu** [comment]
@minad How to do it with multiform? Touching multi-category is a bit of a large stroke.

For completeness this is how one could do ti by customizing multi-category override:

```el
(orderless-define-completion-style orderless-only-literal
    (orderless-matching-styles '(orderless-literal)))

(setq completion-category-overrides
   '((file (styles basic partial-completion))
     (multi-category (styles orderless-only-literal))))
```

**Comment by minad** [comment]
You can adjust variables via vertico-multiform-mode per command. It is documented in the readme. In this case you would override completion-styles.
