### ISSUE TITLE
Consider donation

### ISSUE THREAD

**Issue by M-Gregoire** [minad/consult#657]
Hello @minad,

You seem to spend a lot of time maintaining your projects which benefits of lot of people (660 stars at the moment on `consult` alone!). You also take time answering issues, taking feature requests, etc. I'd love to thank you for those efforts and I'm sure some other person might also want to!

Have you ever considered accepting donations through Github/Paypal/OpenCollectives/Patreon to thank you for your time?

**Comment by minad** [comment]
Thank you for the kind words! I am glad that my packages are useful to you and others! I will look into donation possibilities in the next few days.

**Comment by minad** [comment]
I enabled Github sponsoring on my account. Thank you!
