### ISSUE TITLE
Consult alternative to `icomplete-fido-exit` function?

### ISSUE THREAD

**Issue by 2ver** [minad/consult#659]
Hello, there are more than a few instances in my daily Emacs workflow in which I need to enter something into `consult` that is not one of the completion candidates and have it “accepted” (e.g.: creäting a new directory in Dired, SSHing with Tramp, opening a new file that has part of the name of another file in the same directory, &c).

Is there not a way to quickly accept the current input yet or am I missing something?

Thanks in advance!

**Comment by oantolin** [comment]
That is not something determined by consult, but by the completion UI. For example, if you used consult with fido, you could simply use icomplete-fido-exit. If you are using @minad's Vertico, you can press M-RET.

**Comment by 2ver** [comment]
Well, count me an idiot ‍♂️. I was searching the wrong project’s issues page; no /wonder/ I didn’t find anyöne else with the same question.

Thanks for the quick response. That’s exactly what I needed!
