### ISSUE TITLE
Preview buffer with consult-ripgrep

### ISSUE THREAD

**Issue by p00f** [minad/consult#662]
How do I preview the buffer with the occurrence highlighted like `consult-imenu`? I saw the `consult--with-preview` function but it isn't used anywhere in this package so I'm not sure how to use it (or if it is relevant at all)

**Comment by minad** [comment]
Highlighting the occurrence with consult-imenu preview is not supported. I will try to implement this later and will check if it works well. Note that for Imenu, highlighting the match is not completely natural (in contrast to consult-line/outline), since the Imenu candidate is not a line string.

**Comment by p00f** [comment]
Oh I meant I want `consult-ripgrep` to have a preview in the main window like `consult-imenu` and `consult-lsp-symbols` do

**Comment by minad** [comment]
Okay, consult-ripgrep has preview enabled by default. Do you use a minimal setup?

**Comment by minad** [comment]
See https://github.com/minad/consult/issues/662#issuecomment-1269435447

**Comment by p00f** [comment]
Oh sorry 😓 I copied the example config which set the preview key for some commands to `M-.`
