### ISSUE TITLE
consult-yank-pop: Support yank-from-kill-ring-rotate

### ISSUE THREAD

**Issue by minad** [minad/consult#668]
I have the same kind of problem. I'm used to have the `kill-ring` cycle when using `yank-pop` and can't get this behaviour with `consult-yank-pop`

When using `yank-pop` the value of `kill-ring-yank-pointer` changes. Example, I just killed 1, 2 and 3.

`kill-ring`:

```elisp
(#("3" 0 1
   (fontified t))
 #("2" 0 1
   (fontified t))
 #("1" 0 1
   (fontified t)))
```

`kill-ring-yank-pointer`

```elisp
(#("3" 0 1
   (fontified t))
 #("2" 0 1
   (fontified t))
 #("1" 0 1
   (fontified t)))
```

If I `yank-pop` 3 times it will yank `1` and the value of `kill-ring-yank-pointer` changes:

```elisp
(#("1" 0 1 (fontified t)))
```

When starting from the same initial setup (1, 2 and 3 have been killed) with consult, I can hit `consult-yank-pop` once and select from its menu to chose the value I want to yank. After selecting `1`, the value of `kill-ring-yank-pointer` hasn't changed and if I use `consult-yank-pop` after that the default value will be `3` and not `1`.

It looks like this cycling can be opted in or out:

```elisp
(defcustom yank-from-kill-ring-rotate t
  "Whether using `yank-from-kill-ring' should rotate `kill-ring-yank-pointer'.
If non-nil, the kill ring is rotated after selecting previously killed text."
  :type 'boolean
  :group 'killing
  :version "28.1")
```

But this doesn't seem to be used in consult

_Originally posted by @mattiasdrp in https://github.com/minad/consult/issues/553#issuecomment-1239125862_

**Comment by mattiasdrp** [comment]
I'm sorry, couldn't find the time to work on it. Do you plan on making a PR for it?

**Comment by minad** [comment]
No, but @jdtsmith's recent issue #667 reminded me of this and I took a look if you made some progress. I don't plan to work on this myself, but I will keep it open for a while to see if there is some interest.

**Comment by mattiasdrp** [comment]
I still plan to work on it but I can't provide a time where it'll be done :-)
