### ISSUE TITLE
consult-buffer : how to preview buffers only while ignoring recentf files and others?

### ISSUE THREAD

**Issue by daanturo** [minad/consult#672]
Currently for `consult-buffer`, auto-previewing is enabled for both buffers and `recentf` files, which I think having Emacs opening files while scrolling through the buffer list may lead to slowness and enlarging the size of `buffer-list` as a side-effect.

Is it possible to achieve such asked configuration?

I see it was decided against in #9 (not entirely identical problems as AFAIU it's also doesn't allow explicit previews), but later implemented.

**Comment by minad** [comment]
Did you take a look at the README?

**Comment by daanturo** [comment]
> if you cannot figure out this yourself from the README, please help me improve it

I just didn't expect the needed snippet was located under `Multiple sources`, maybe we should add a line like
"To configure live-previewing for each source of `consult-buffer`, see `Multiple sources`."
Also a note that customized commands, if present, take precedence over their sources.
