### ISSUE TITLE
How to configure consult-line to behave like isearch (consult-line-at-point)

### ISSUE THREAD

**Issue by TatriX** [minad/consult#673]
Hi! I'm trying to setup the following workflow:
1. Run `(consult-line (thing-at-point 'symbol))` in a buffer to see where a symbol is used relative to the current position
2. This should also select current line in the completion list *without* moving the point or recentering anything.
3. `C-p` and `C-n` should move me in the completion list with live-preview relative to the initial position.

I've disabled `consult-after-jump-hook` to stop recentering.
Then I've set `consult-line-start-from-top` to `t`, but then `consult-line` immediatelly jumps to the beginning of the buffer, instead of keeping symbol-at-point as a default choice. If I use`nil` for `consult-line-start-from-top` then I can't use `C-p` to go upwards from the symbol-at-point, since candidates before the point are now in the end of the completion list.

Any help is appreciated, thanks!

**Comment by minad** [comment]
Hi, I don't really understand what you are actually trying to achieve. Is your point that you want to start `consult-line` and *not move right away*? Note that `consult-line` with initial input will select the first matching line either from the top (`consult-line-start-from-top` non nil) or starting from the line you've been at before. Is this behavior unexpected? I you set `consult-line-start-from-top` to nil you can also move to the matches before the current match if you set for example `vertico-cycle` to t. Can you please describe your use case more precisely?

**Comment by TatriX** [comment]
Here's what happens when I invoke `consult-line`
<img width=600 src="https://user-images.githubusercontent.com/703150/196173952-8fd463f6-58b5-4d2a-a716-3e3d8fb3e6b0.png">

Here's what happens when I invoke `swiper-thing-at-point`
<img width=600 src="https://user-images.githubusercontent.com/703150/196174212-aa5a0c8f-5ffd-458b-a066-e1e6deef4cd5.png">

I don't I ever want to search for the whole line, I usually just want to see where this thing under point is defined, that's usually above point, or where it's used, that's usually below.

On the first picture I can clearly see that there is a `things` above, and I naturally want to press `C-p` to get there. I can't figure a way to get this behavior with `consult-line`.

Another way to think about it is using regular isearch, i.e. type `C-s C-w` to start isearch and than yank word at point, from there I can either `C-s` to search forward or `C-r` to search backward.

Both isearch and swiper do nothing to the window, they just highlight matches around.

Hopefully it's a bit clearer. Please let me know if I should describe it in more details.

**Comment by TatriX** [comment]
Oh, I've tried `(setq vertico-cycle t)` and it partially solves the problem, except I don't want it to cycle in general and I'd prefer to have candidates that are above the selected one to be above in the completion list as well.

**Comment by minad** [comment]
Please check that you use the newest version of Consult. Your screenshots indicate otherwise. Then make sure that you try to reproduce the issue starting from emacs -Q, see https://github.com/minad/consult/#bug-reports.

With the following configuration I seem to get the behavior you are asking for:

~~~ elisp
(defalias 'consult-line-thing-at-point 'consult-line)

(consult-customize consult-line-thing-at-point
                   :initial (thing-at-point 'symbol))

(setq consult-line-start-from-top nil)
(setq consult-line-point-placement 'match-beginning)
~~~

> Oh, I've tried (setq vertico-cycle t) and it partially solves the problem, except I don't want it to cycle in general

You can set vertico-cycle only for consult-line, see vertico-multiform-mode. 

> and I'd prefer to have candidates that are above the selected one to be above in the completion list as well.

That's unfortunately not possible by construction of consult-line. This has been discussed a few times before, but the behavior with the wrap around is here to stay since this is the most natural behavior which should work across all completion UIs.

Can you please check again?

**Comment by TatriX** [comment]
I see, thanks for the explanation! Wrapping behavior is a bit unfortunate, because that means there is no way to see matches in the minibuffer that are *around* the thing at point if there are plenty of matches: you can either see what's below or what's above, cause going upward shows you just the end of the list.

I can simply stick to swiper for that particular use case. Again, thank you for all the effort!

**Comment by minad** [comment]
> Wrapping behavior is a bit unfortunate, because that means there is no way to see matches in the minibuffer that are around the thing at point if there are plenty of matches: you can either see what's below or what's above, cause going upward shows you just the end of the list.

I don't feel like this is a big problem but I haven't used Swiper for long. On the other hand I find the wrapping natural. If I want to see the preceding matches I just press `M->` (or `up` if `vertico-cycle` is non-nil). The problem with supporting your described behavior is that we would have to introduce an additional special case in Vertico. 

I think if you enable `vertico-cycle=t` the difference is really only in scrolling. If you press `up`, you will end up at the first preceding match but the selected candidate will be at the very bottom of the minibuffer, while in Swiper the selected candidate will appear at the top or in the middle, right? It should be possible to implement this also in Vertico by adding some setting `vertico-cycle='continue`. It may be worth thinking about this again.

Anyway, if you are very accustomed to certain behavior of Ivy/Counsel/Swiper and want to preserve the behavior completely there is nothing wrong to continue to use it.
