### ISSUE TITLE
Symbol’s function definition is void: consult-customize

### ISSUE THREAD

**Issue by albertfgu** [minad/consult#675]
I added the following snippet following the README
```emacs-lisp
   (consult-customize
    consult-ripgrep
    :preview-key '(:debounce 0.5 any) ;; Option 1: Delay preview
    )
```
At startup, this gives the following error (I'm using Spacemacs, but stripped away most of the other functionalities to isolate the issue):
```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: consult-customize
```

Then, if I select this snippet and run `eval-region`, it works fine and does the customization (i.e. I get the delay on preview).

Any ideas appreciated!

**Comment by minad** [comment]
You should `(require 'consult)` if you want the `consult-customize` macro available. Please ask on the Spacemacs issue tracker about how to do this properly in Spacemacs. See also the use-package example in the [README](https://github.com/minad/consult#use-package-example).

**Comment by albertfgu** [comment]
`with-eval-after-load` did the trick, thanks for the tip!
