### ISSUE TITLE
Disabling live preview when functions are called non-interactively

### ISSUE THREAD

**Issue by ashlineldridge** [minad/consult#676]
The consult grep functions don't seem to obey their `preview-key` setting when they are called non-interactively. For example, I am customizing these functions so that preview is manually triggered:

```lisp
  (consult-customize
   consult-ripgrep
   consult-git-grep
   consult-grep
   :preview-key (kbd "M-."))
```

This has the desired effect when this functions are called via `M-x consult-ripgrep` but when they are called via Emacs Lisp the live preview is always shown. Both of the following invocations will display the live preview:

```
(consult-ripgrep)
(call-interactively 'consult-ripgrep)
```

Am I missing something here? Thanks.

**Comment by minad** [comment]
You have to `consult-customize` the command which is called interactively (`this-command`). This allows us to write code like this:

~~~ elisp
(defalias 'consult-line-thing-at-point 'consult-line)

(consult-customize
 consult-line-thing-at-point
 :initial (thing-at-point 'symbol))
~~~

Note that this is also mentioned in the README, see https://github.com/minad/consult#live-previews.

**Comment by ashlineldridge** [comment]
Ah, I missed that in the doco. Thank you.
