### ISSUE TITLE
consult-theme errors when switching between modus themes

### ISSUE THREAD

**Issue by albertfgu** [minad/consult#677]
I'm seeing a weird error that only happens with `consult-theme` and when switching between `modus-operandi` and `modus-vivendi`. Not sure what's the best way to reproduce this issue and where to report but I figured I'd start here.

1. If I start my Emacs with `modus-operandi` loaded, then upon changing themes with `consult-theme` to `modus-vivendi` I get the below error. If I start with `modus-vivendi` and then change to `modus-operandi` I get the same error.

```
Error running timer: (wrong-number-of-arguments ((modus-themes-custom-variables modus-themes-faces t) (fg-only-bg fg-only-fg mainbg mainfg altbg altfg &optional deuteranbg deuteranfg bg-only-fg) "Color combinations for `modus-themes-diffs'.

FG-ONLY-BG should be similar or the same as the main background.
FG-ONLY-FG should be a saturated accent value that can be
combined with the former.

MAINBG must be one of the dedicated backgrounds for diffs while
MAINFG must be the same for the foreground.

ALTBG needs to be a slightly accented background that is meant to
be combined with ALTFG.  Both must be less intense than MAINBG
and MAINFG respectively.

DEUTERANBG and DEUTERANFG must be combinations of colors that account
for red-green color defficiency (deuteranopia).

Optional BG-ONLY-FG applies ALTFG else leaves the foreground
unspecified." (cond ((eq modus-themes-diffs 'fg-only) (let nil (list :background fg-only-bg :foreground fg-only-fg))) ((eq modus-themes-diffs 'fg-only-deuteranopia) (let nil (list :background fg-only-bg :foreground fg-only-fg))) ((eq modus-themes-diffs 'desaturated) (let nil (list :background altbg :foreground altfg))) ((eq modus-themes-diffs 'deuteranopia) (let nil (list :background (or deuteranbg mainbg) :foreground (or deuteranfg mainfg)))) ((eq modus-themes-diffs 'bg-only) (let nil (list :background altbg :foreground (if bg-only-fg altfg 'unspecified)))) (t (let nil (list :background mainbg :foreground mainfg))))) 4)
Wrote /Users/albertgu/.emacs.d/.cache/undo-tree-history/.!Users!albertgu!.emacs.d!.cache!bookmarks.~undo-tree~
```

2. If I instead change themes with `load-theme` instead of `consult-theme`, I get the following messages in the minibuffer:
```
Loading a theme can run Lisp code. Really load? (y or n) y
Treat this theme as safe in future sessions? (y or n) n
```
The theme then loads properly. Furthermore, after this I can change between the two modus themes freely with no issue using `consult-theme`

3. If I start Emacs with any other theme loaded and then use `consult-theme` to switch to either of the modus themes, it works fine.

**Comment by minad** [comment]
I use Modus and don't have issues. You should try to uninstall Modus and install it again. Let me know if this solves your problem.

**Comment by albertfgu** [comment]
I'm not even sure how to reinstall Modus; doesn't it come shipped with Emacs? I did uninstall and reinstall my Emacs for a different reason and it doesn't fix this particular problem. It's not a big deal since there are the workarounds I described above.

**Comment by minad** [comment]
You can still install the newest Modus from Elpa. But consult-theme should also work with the built-in themes. The issue you are observing doesn't sound consult-theme specific at all. It sounds as if there is something wrong with your customization or particular setup. Did you try to reset your .config/emacs directory? Maybe @protesilaos saw this issue before?

**Comment by albertfgu** [comment]
I'm actually on Emacs 28.2, but I'm also using Spacemacs. I tried to strip everything out to repro this, and I do still get this issue, but it seems hard to track down. It might be a weird interaction between Spacemacs and consult-theme. Just thought I'd ask here in case there were obvious leads, but it's not a big enough issue otherwise. Thanks!
