### ISSUE TITLE
consult-history: Require match

### ISSUE THREAD

**Issue by xFA25E** [minad/consult#678]
Is there any reason for `consult-history` to not have `:require-match t`. I've never had a need to edit history entry before inserting it. I usually insert the history entry and edit it after inserting (in the minibuffer or in shell prompt). Am I missing something?

**Comment by minad** [comment]
REQUIRE-MATCH is mostly useful if non matching input would be invalid. For history insertion, allowing editing doesn't hurt. So it is better to leave this as is.
