### ISSUE TITLE
consult-buffer - any way to avoid previewing the highlighted candidate in a buffer?

### ISSUE THREAD

**Issue by ahungry** [minad/consult#679]
I like the consult-buffer feature, in which it shows buffers, recentf and projects in the same selection, however it's jarring to see my actively opened buffer switching for the live preview - is there a setting or custom to disable this behavior?

Also, one bind I enjoyed from helm was ctrl+o to jump/cycle through categories (although cycling through the narrows vs using a narrow prefix + button like 'f' 'b' or 'p' would also be neat) - maybe this is more muscle memory than anything, but is there any type of support for that?

If the answer to both is "no" - is this something that would be welcomed in consult?

**Comment by ahungry** [comment]
Ok, I found the preview setting (consult-preview-key)

**Comment by minad** [comment]
See also the README.
