### ISSUE TITLE
New :state function for source

### ISSUE THREAD

**Issue by mclearc** [minad/consult#683]
Sorry to bother you with this but I was wondering if I might get a little guidance. I'm trying to create a new :state function to preview denote note files using consult-notes. I can already preview files in consult-notes using the standard `(consult--file-state)` but the integration of denote notes poses a problem because the format of those notes appears as "ID Title #keyword". 

You can see it in action here:
![image](https://user-images.githubusercontent.com/1502422/203643245-d909b232-d502-4cc9-969b-310f13b6f326.png)

I had thought that I could simply write a translate function like so:

```emacs-lisp
(defun consult-notes-denote--file-name (cand)
  (abbreviate-file-name (denote-get-path-by-id (car (split-string cand)))))
```
And then a new preview function like so:

```emacs-lisp
(defun consult-notes-denote--state ()
  (let ((state (consult--file-state)))
    (lambda (action cand)
      (funcall state (consult-notes-denote--file-name cand)))))
```
But this doesn't work -- I seem not to be getting a string for "cand" that I can return as a filename for preview. I've looked through the documentation for the various functions but I'm clearly missing something. Any advice you might have is much appreciated.

**Comment by minad** [comment]
See the docstring of consult--with-preview. The cand argument may be nil sometimes. But besides that your approach should work.
