### ISSUE TITLE
consult-yank-pop: Treat kill-ring as a ring

### ISSUE THREAD

**Issue by astoff** [minad/consult#687]
If I do `C-y M-y M-y M-y ...` then I see the "front" entries of the kill ring, but on the minibuffer `consult-yank-pop` always shows the car of the kill ring as the first candidate.  I'd prefer to see the candidates rotated such that `(car kill-ring-yank-pointer)` is the first candidate.

**Comment by minad** [comment]
Doesn't this work already? See #682.
