### ISSUE TITLE
Avoid sorting heading candidates in consult-outline

### ISSUE THREAD

**Issue by kguidonimartins** [minad/consult#689]
Hi minad! I'm exploring your package, and it is fantastic! 

Is there a way to avoid the sorting of heading candidates when using consult-outline? It seems this function always puts the latest jump in the first position and reorganizes others candidates in a strange order (image below).

![consult-outline](https://user-images.githubusercontent.com/8163542/205441713-680da46a-f198-49f1-b2a7-7b0322c7f228.png)

**Comment by minad** [comment]
Thanks! The order of candidates in the completion UI should be the same as in the buffer. This is likely a configuration issue. See https://github.com/minad/consult/#bug-reports.
