### ISSUE TITLE
Get "Wrong type argument: overlayp, nil" error when using consult's command.

### ISSUE THREAD

**Issue by umiswing** [minad/consult#698]
I install consult from elpa. And configure it using [configuration in Readme.](https://github.com/minad/consult#configuration)
But I got "Wrong type argument: overlayp, nil" typing any consult's command.
emacs --version: GNU Emacs 27.1
consult version: 20221209.1945

**Comment by minad** [comment]
Please follow https://github.com/minad/consult#bug-reports.

**Comment by zilongshanren** [comment]
```
  ;; (consult-customize
  ;;  consult-ripgrep consult-git-grep consult-grep
  ;;  consult-bookmark consult-recent-file
  ;;  :preview-key (kbd "C-SPC"))

```

I fix it by remove these lines. @umiswing

**Comment by umiswing** [comment]
@zilongshanren Thanks! I will try it. :)

**Comment by bbenne10** [comment]
If I am reading the docs right, simply remove the `kbd` call: 
```elisp 
(consult-customize
  consult-ripgrep consult-git-grep consult-grep
  consult-bookmark consult-recent-file
  :preview-key "C-SPC")
```
