### ISSUE TITLE
Question: How to keep fundamental-mode when previewing files within consult-buffer?

### ISSUE THREAD

**Issue by mekeor** [minad/consult#700]
Hello and thanks for consult.

When using consult-buffer (and possibly other consult-* functions that preview files), I'd like it to use fundamental-mode only, instead of launching all associated modes. I hope that that will make consult-buffer snappier. How to achieve that?

**Comment by minad** [comment]
Let's try this. Emacs is self documenting. Check the Consult customization variables. There is one variable which you should set to 0 to achieve your goal. Then there is also a trickier way via another configuration variable. Please let me know how it goes.

**Comment by mekeor** [comment]
@minad, I'm sorry but I don't know which variable you are referring to. I read the docs for all consult-buffer-* and consult-preview-* variables and didn't find what I was looking for.

**Comment by minad** [comment]
There are only three `consult-preview-*` variables with a numeric `:type`. You could try each of them.

**Comment by mekeor** [comment]
i didn't associate "raw form" with fundamental-mode. thank you! 

```elisp
(setq consult-preview-raw-size 0)
```
