### ISSUE TITLE
No results using `M-x consult-ripgrep` on remote host

### ISSUE THREAD

**Issue by BenediktBroich** [minad/consult#701]
When i open a directory/file on a remote host via ssh and start `M-x consult-ripgrep` it does not return any results and does not throw any errors. `M-x consult-grep`, `M-x consult-git-grep` and `M-x consult-find` do return the correct results locally and on the remote `host.` `M-x consult-ripgrep` does work properly on the local system and does return the correct results there.

Ripgrep is installed on the remote host and the search over command line (`rg`) does work.

**Comment by minad** [comment]
It works for me and I also don't see a reason why it shouldn't. `consult-grep` and `consult-ripgrep` are technically not different. My best guess is that this has something to do with incompatible arguments, not supported by the remote binary. In any case, I would need a  very detailed report, see https://github.com/minad/consult#bug-reports. Also you should check that the content of the `*consult-async*` log buffer and make sure that the ripgrep commands succeed locally and remotely when executed in a normal shell. The generated command lines can also be seen in the `*consult-async*` log buffer.

**Comment by BenediktBroich** [comment]
Yes you are right: When i copy the command out of the *Messages* buffer and run in on the remote server i do get an error.

```
> rg --null --line-buffered --color=never --max-columns=1000 --path-separator / --smart-case --no-heading --line-number . -P -e ht
PCRE2 is not available in this build of ripgrep
```

The version was 

```
> rg --version
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

Update rg fixes it. 

```
> rg --version
ripgrep 13.0.0 (rev 7ec2fd51ba)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

**Comment by minad** [comment]
Oh, now I remember this flaw. Consult caches the supported regexp type, see consult--ripgrep-regexp-type, but it should better only cache it per minibuffer session. Besides that Consult would handle different ripgrep versions just fine. It would be good to fix this.
