### ISSUE TITLE
Order of consutlt groups

### ISSUE THREAD

**Issue by Dickby** [minad/consult#702]
I'm trying to change the order of consult-imenu groups.
The only thing i try to achieve is to have "Functions" as the first group i see (top most).
Is there a way to do this?
Thanks

**Comment by minad** [comment]
Sorting is determined by order of the candidates. The first candidate will determine the first group etc. The order of the candidates is provided by the backend. Note that you can also cycle through the groups in Vertico with `vertico-group-next/previous`. Besides that there is no easy way to change the order, but you could of course advise some function in Vertico or the completion UI of your choice.

**Comment by Dickby** [comment]
Thanks for the quick answer.

**Comment by minad** [comment]
I forgot to mention Consult narrowing. You can configure this for consult-imenu and then press f SPC.
