### ISSUE TITLE
Any possiblity to bring the argument of `consult--*-make-builder` back?

### ISSUE THREAD

**Issue by dalugm** [minad/consult#703]
Before 5c8b835, `consult--*-builder` accepts INPUT as the argument.

https://github.com/minad/consult/blob/1ee5d02cb335953adfe789910800f6a2e4588792/consult.el#L4824-L4826

As a non-native English speaker, I have files named in my own native language on my computer. When the argument INPUT exists, I can use an advice to change the behavior of `consult-find`. For example:

https://github.com/dalugm/emacs.simple/blob/37571a1554b418e2045e05efb50eef9ec8e119ec/etc/init-vertico.el#L93-L104

https://github.com/dalugm/emacs.simple/blob/37571a1554b418e2045e05efb50eef9ec8e119ec/etc/init-vertico.el#L129-L135

By using `advice-add`, I can easily search files as I wanted.

After 5c8b835, `consult--*-builder` does not accept INPUT anymore, and I can't use `advice-add` to adjust its behavior. Is there anyway to solve this? thx.

**Comment by minad** [comment]
No, I won't bring them back. But you can still advice the make-builders, wrapping the return value. Note that the return value is a lambda with an input argument.

**Comment by minad** [comment]
Btw, it seems that you modify the way the regexp is treated. My recommendation is to override consult--regexp-compiler instead. This should solve your problem in a more general way, and in the way I actually intended this.

**Comment by dalugm** [comment]
I see, thanks for your advice.
