### ISSUE TITLE
isearch-string not pre-populated in history when using multiform = buffer

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#704]
On initiating an isearch, and from there entering `consult-line`, the highlighted isearch term is neither directly populated, nor does `M-n` bring it in (instead the full current line).  

I have a guess as to why: I use vertico-multiform with `(consult-line buffer)`, and `minibuffer-default-add-function` does not get set locally in the new buffer.

**Comment by minad** [comment]
No, you probably didn't configure consult-line properly as documented in the Consult README.

**Comment by oantolin** [comment]
To grab the isearch-string, consult-line needs to be run while isearch-mode is still active, so you *need* to bind consult-line in isearch-mode-map. If you use your global binding, isearch exits first and then consult-line doesn't grab the isearch-string.

**Comment by jdtsmith** [comment]
> When consult-line is bound to the isearch-mode-map and is invoked during a running Isearch, it will use the current Isearch string.

This works, via `:initial`.  But it isn't my preferred usage (one key binding = preserve brain memory slots!)

> The symbol at point and the recent Isearch string are added to the “future history” and can be accessed by pressing M-n. 

Aha, this is what confused me.  In fact future history includes (in order):

1. The full current line
2. The symbol at point
3. The isearch string

So with 3 `M-n`'s you can get there.  I expected isearch-string first.  In any case, if it's useful for people, just bind `consult-line` to the same keys _twice_, once in your global map, and again in `isearch-mode-map`, and it will initialize with isearch-string if isearch is active.

**Comment by minad** [comment]
@jdtsmith I don't understand your preferred usage. You have to bind the command twice, but you can obviously use the same key binding. If you dislike the mere fact that you have to replicate the binding you could either use a variable or complain to the Isearch developers who came up with this Isearch quirk.

**Comment by oantolin** [comment]
> one key binding = preserve brain memory slots!

I should have been explicit, as @minad, was: you can use the same binding in isearch-mode-map as your global binding, it just needs to be in isearch-mode-map too.

**Comment by minad** [comment]
I looked at isearch.el and it seems one could alternatively add `consult-line` to `isearch-menu-bar-commands`. Yet another alternative would be to `defalias consult-line` and `consult-customize :initial isearch-string` for the alias. Then the aliased command would always pick up the `isearch-string` even when started outside of Isearch.

**Comment by astoff** [comment]
> If you dislike the mere fact that you have to replicate the binding you could either use a variable or complain to the Isearch developers who came up with this Isearch quirk.

This is the awful (albeit beloved by many) behavior whereby you can quit the search by just issuing any non-Isearch command.

**Comment by jdtsmith** [comment]
I was speaking more about the ordering of future history. IMO that would make sense to be _first_ on the list when starting from an active isearch.

**Comment by oantolin** [comment]
> This is the awful (albeit beloved by many) behavior whereby you can quit the search by just issuing any non-Isearch command.

As one of the people that love that behavior, I don't see what's so awful about it, @astoff.

**Comment by astoff** [comment]
It's quite easy to make a small typing mistake and lose the search state. I didn't make that comment entirely seriously, but I do think it's not a good default. Efficient perhaps, but very finicky.

**Comment by oantolin** [comment]
That's true enough. I think I do sometimes exit isearch by accident but not often enough to find it frustrating. Do you still use your isearch-mb package?

**Comment by astoff** [comment]
Yes! It also integrates with consult-line, etc. The Readme explains how.
