### ISSUE TITLE
Error running timer (void-function consult--ripgrep-builder)

### ISSUE THREAD

**Issue by bangedorrunt** [minad/consult#705]
Hi,

I'm trying to migrate some useful doom functions to project.el however I'm running into this error from this snippet in modules/completion/vertico/autoload dir

[(https://github.com/doomemacs/doomemacs/blob/d5ccac5d71c819035fa251f01d023b3f94b4fba4/modules/completion/vertico/autoload/vertico.el#L7-L57)](https://github.com/doomemacs/doomemacs/blob/d5ccac5d71c819035fa251f01d023b3f94b4fba4/modules/completion/vertico/autoload/vertico.el#L7-L57)

So far when I use +vertico/search-project, project.el give me root path to start searching, but when I type to search, it's the last line give me this bug. I am not sure if it is a bug or my own problem, have you got any idea how to fix that? Many thanks!!!!

I'm on emacs-29 branch, fyi

**Comment by minad** [comment]
Can you reproduce this in a minimal setup? See https://github.com/minad/consult#bug-reports.

I've observed such void errors before. The reason is a bug in native compilation, but I am not sure if anyone could pin this down so far. Anyway that's an upstream bug.

**Comment by btuin** [comment]
@bangedorrunt 

Hi, I had the same problem.

The function was modified in commit 5c8b83546c8d4ef77db009bcad5d6e1d28f261cf, and was later renamed in commit 4ff45b378210ce4bc942eb366011ee647f575506.
Meaning you need to replace
```elisp
(consult--grep prompt #'consult--ripgrep-builder directory query)))
```
by
 ```elisp
(consult--grep prompt (consult--ripgrep-make-builder) directory query)))
```
