### ISSUE TITLE
consult-history: Use already written text as query?

### ISSUE THREAD

**Issue by mekeor** [minad/consult#706]
## Reproduction

1. Launch an Emacs instance (assuming Vertico and Consult are in load-path): `emacs -q`
2. Launch Eshell: `M-x eshell RET`
3. Launch Vertico: Type `(use-package vertico :config (vertico-mode))` and press `RET`
4. Launch Consult: Type `(use-package consult)` and press `RET`
5. Type `(use`.
6. Launch Consult-History: `M-x consult-history`.

## Screenshot

![2022-12-28-000957_658x456_scrot](https://user-images.githubusercontent.com/60295641/209837187-f391b671-9ea3-4407-a093-7491e9e1b49f.png)

## Observed Behavior

1. The command-line will look something like `~ $ (use(use-package consult)`. As you can see, the previous input (`(use`) has been ignored and now I have some cumbersome duplication.
2. consult-history's minibuffer does not contain `(use` as query.

## Requested Behaviour

- It'd be nice if `(use` would be moved from Eshells command-line prompt to consult-history's minibuffer as query.
- Is this out of Consult's scope? Should I rather implement it myself with some custom function? Could we implement this as a separate function, e.g. `consult-history-query` or so?

## Trivia

- You don't need Vertico to observe this behavior but using Vertico makes it more obvious/visible.
- I used GNU Emacs version 29.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw scroll bars).

**Comment by minad** [comment]
This is a good idea, implemented in 16b2dc5e34c8a500adbee394b42c0e0d7fd24ad8. Btw, you could also try cape-history+Corfu for in-buffer history completion.

**Comment by oantolin** [comment]
I'm experiencing a [Mandela effect] here: I was pretty sure `consult-history` already did this! 😄

**Comment by minad** [comment]
It did for the minibuffer, so we are more consistent now. In order to restore the old behavior one can set the BOL function to nil.

**Comment by oantolin** [comment]
That must be why I though it did. I do use it outside the minibuffer too, in eshell and comint buffers and in buffer where you edit commit messages, but in all those cases I probably just tend to use it without any input so I didn't notice the difference.

**Comment by minad** [comment]
Yes, you probably used it always without input. I had already considered implementing this a while ago, when I wrote `cape-history`. Now the two commands behave the same way.

**Comment by mekeor** [comment]
Thank you for the quick response and implementation.

**Comment by ovy** [comment]
Hi guys @minad @oantolin -- can we reconsider this, at least for the minibuffer case?  I think we should change the `:initial` to `:default` to be consistent with "I-search backward" and even readline in bash, python, etc.  In all of these, the current text does _not_ participate in the search.

In a bit of recursive irony, it's the _other commands_ that use `initial` that suffer the most from this:   `M-x compile` pops up with the last command, which is 95% of the time the right thing to do so I just hit RET. The remaining 5%, I hit `C-r . consult-history` and I get ... a list of one, which becomes a list of zero if I type anything, until I clear the minibuffer. This is not how default `C-r` in the minibuffer behaves, or as I mentioned libreadline, the search string starts empty.

With `:default`, I get a very pleasant behavior where the current command is selected, but search starts anew. I can still as usual with default do `M-n` to reduce it to the text. I guess it's fair to say that in the current `:initial` impl I could kill the minibuffer text, but 1) the one-line choice is initially disconcerting and 2) it really should match the C-r behavior elsewhere.

This is a 7-character PR that I was about to send before I spotted this issue.  Thought it might be worth discussing first.

We could also make it behave like this only in minibuffer and not in  *shell. I don't use the shells much so I can't comment on what's handy.

**Comment by minad** [comment]
@ovy I prefer the current behavior. Note that you disable the :initial value via consult-customize if you like to start with an empty minibuffer.

**Comment by ovy** [comment]
@minad Indeed I can!   Thank you for that option, it works fine. I thought I would have to maintain a separate consult-history otherwise.

So the behavior of `M-x compile` doesn't bother you?

**Comment by minad** [comment]
It may or may not, but a single broken command should not guide the design of a more general utility. You could bind C-r inside the M-x compile minibuffer, such that the minibuffer is first emptied before calling consult-history.

**Comment by ovy** [comment]
Thanks. I'll leave it as is with consult-customize.  FWIW, I just tested that if one wanted to tell that the minibuffer was untouched by the user, one could look at `(buffer-undo-list)` being nil.
