### ISSUE TITLE
[FR]: provide a way to query the current grep variant for consult-*grep commands

### ISSUE THREAD

**Issue by daanturo** [minad/consult#707]
Recently I have just known about `pcomplete-from-help` so I used it to write a CAPF to complete grep options, like:
```
# def -- -a|
```
Pressing TAB will suggest from the available flags. The simple CAPF itself worked, although I had to make a wrapper around `completion-at-point` that ignores `completion-styles` being `(consult--split)`  (1).

![image](https://user-images.githubusercontent.com/32123754/210353886-e21487c3-9884-438b-ae3f-fdfbfe8bc639.png)

The issue: what to pass to `pcomplete-from-help` isn't dynamically detectable (at least easily),  the above screenshot, I had to make a wrapper around `consult-ripgrep` and hard-code 
`(pcomplete-from-help '("rg" "-h"))` 
there so `consult-git-grep`, `consult-grep` and other wrappers (like Doom's) doesn't benefit from the setup.

If there's such an interface, I can just bind the TAB in `consult-async-map` to the wrapper (at (1)) and dynamically detect the grep variant there.
My idea for a PR: https://github.com/minad/consult/compare/main...daanturo:consult:record-grep-variant-locally?expand=1

**Comment by minad** [comment]
You can `this-command` in a `minibuffer-setup-hook` to detect the current command and then derive the grep variant from there. But I don't think your approach is that useful. It would be better if we add a transient interface for consult-grep/ripgrep etc. What do you think?

**Comment by daanturo** [comment]
Personally I don't like a transient interface for grepping, as we have to maintain curated list of options to expose, for each of the variant. While the options maybe deprecated upstream and/or new options being introduced.
IMO it's better to let the user control a lower level.
But maybe the best would be a dynamically computed transient interface that exposes even the default arguments (in `consult-ripgrep-args`).
For switches that can be specified multiple times like `--glob`, IMO transient is ill-suited for those.

**Comment by minad** [comment]
Sure, transient is a matter of taste. But from what I've heard many people would like it in this context.
