### ISSUE TITLE
consult-kmacro to move to the selected macro

### ISSUE THREAD

**Issue by arialdomartini** [minad/consult#709]
`consult-kmacro` is super convenient for selecting a macro from the macro ring and running it.
It is more handy than `kmacro-cycle-ring-next` followed by `C-x e` (`kmacro-end-and-call-macro`).

One notable difference is that once run, `consult-kmacro` does not update the `last-kbd-macro`. Consequently, `C-x e` would not repeat the selected macro but the previously used one. 

I wonder if updating `last-kbd-macro` with the selected macro would be a nicer default.

**Comment by minad** [comment]
Yes, that's a good point. I also wanted that before.

**Comment by okamsn** [comment]
I think that this would be a good action to have in Embark Consult.

Here are some actions that I made for the Counsel version (re-reading the code again):

- Copy the counter format for a new kmacro
- Copy counter value for new kmacro
- Cycle the ring to the selected candidate (this issue)
- Set the counter for the selected kmacro
- Re-run kmacro N times after prompting for N, counter value, and format (good for mistakes)

**Comment by minad** [comment]
I close this for now. The kmacro API is in flux. It changed in Emacs 29 and it is changing again in Emacs 30 (see #752). But if there is interest in this feature, I'd welcome a PR.
