### ISSUE TITLE
consult-theme but for fonts?

### ISSUE THREAD

**Issue by nrvale0** [minad/consult#710]
Before I even ask for this let me say that I'm looking at whether I could write it and send it in as PR. But my elisp is ... well ... I'm getting there slowly. ;)

It would be super helpful if consult had a function like consult-theme but for previewing fonts instead of previewing themes.

**Comment by minad** [comment]
I am not sure if that would be a good addition to Consult. I think one could instead add a Marginalia annotator, which displays a font sample as annotation. This annotator could then be used for the commands `describe-font`, `set-face-font`, `set-frame-font` and maybe other commands.

**Comment by nrvale0** [comment]
There are a handful of packages out there which allow limited preview of fonts but, like some of the earlier attempts at previewing themes, they don't give quite the same of understanding what to expect that one gets from =consult-theme= auto-preview using open buffers.

I'll spin up a consult ecosystem package to try to hit my use-case and, if I'm successful, open a new Issue to discuss whether it should remain a separate package or be mainlined back into consult itself.

**Comment by minad** [comment]
I understand that real preview would be different from annotators. But still, I think the command would not provide sufficient value to add it here. It is not that I am switching fonts ten times a day, in contrast to other Consult commands.
