### ISSUE TITLE
wrong-type-argument listp special-mode

### ISSUE THREAD

**Issue by tumashu** [minad/consult#711]
when I upgrade to newest consult, show:

Error running timer ‘show-paren-function’: (wrong-type-argument listp special-mode) [4 times]

**Comment by tumashu** [comment]
emacs -q have no more info.

**Comment by minad** [comment]
I run newest Consult without issues. Your bug report is insufficient. In particular, I need a minimal recipe. See https://github.com/minad/consult#bug-reports. Thanks!
