### ISSUE TITLE
Inconsistent auto-selection when narrowing

### ISSUE THREAD

**Issue by Ojd2000** [minad/consult#714]
When narrowing a candidate list to a specific group, I think the first candidate in the list shown should be selected, as would happen without narrowing. This happens, for example, with `consult-imenu` and `consult-minor-mode-menu`, but does not happen with `consult-buffer` if I narrow down to a group which isn't the "Buffer" one (nothing is selected).

I have made no modifications to the behaviour of `consult-buffer` (nor the others).
My completion UI is vertico.

**Comment by minad** [comment]
@Ojd2000 This was an old issue. The old behavior had its reasons and was also somewhat consistent (in a different way), but I revisited this and improved it now.
