### ISSUE TITLE
Project-wide `consult-flymake` fails with "No buffer named ..."

### ISSUE THREAD

**Issue by Tehforsch** [minad/consult#716]
First of all: Thanks for consult, it's awesome.

When I call `(consult-flymake t)` in order to do a project-wide diagnostics listing (which has been implemented in #589 as far as I can tell) and there are any foreign diagnostics in files that are not opened in a buffer, the command will fail with "No buffer named ..." where the filename is any of the files with the foreign diagnostics.

I traced back the error to the `(with-current-buffer buffer ...)` call in `consult-flymake--candidates`. 

I looked into `flymake-show-project-diagnostics`, which does not have this problem and properly lists unopened files. I checked the source code there to find this:

```
   (cond (;; has live overlay, use overlay for position
          (and overlay (overlay-buffer overlay))
          (with-current-buffer (overlay-buffer overlay)
            (save-excursion
              (goto-char (overlay-start overlay))
              (cons (line-number-at-pos)
                    (- (point)
                       (line-beginning-position))))))
         (;; diagnostic not annotated, maybe foreign, check for cons
          (consp (flymake--diag-beg diag))
          (flymake--diag-beg diag))
         (;; may still be a valid foreign diagnostic
          (consp (flymake--diag-orig-beg diag))
          (flymake--diag-orig-beg diag))
         (;; somehow dead annotated diagnostic, ignore/give up
          t nil))
```

which looks to me like the logic to look up the cursor location in the target buffer, but I didn't know how to turn that into a marker. My elisp is pretty terrible so I gave up trying to fix this after a while.

**Comment by minad** [comment]
Thanks. For now I removed support for diagnostics, which come from unopened files, since it seems project-wide flymake support wasn't properly implemented in the first place in #589. I'd welcome a PR which improves this. Maybe @mohkale is interested in this.
