### ISSUE TITLE
Trigger narrowing after the input has been inserted

### ISSUE THREAD

**Issue by vspinu** [minad/consult#717]
I am looking for an easy way to trigger narrowing after the input has been inserted. Currently the only way I see is to delete the input, insert the narrowing character and re-insert the input.

My primary use case is with the hidden buffers. I often don't know if a buffer that I look for is hidden or not beforehand (some log or stderr buffer). So I type the name then I see there are no candidates and I want to switch on the hidden files. 

Ideally I could move to bol, insert the space and get the hidden files, but this "post-filtering" does not happen currently.

FWIW, ido would insert hidden files automatically if there are no matches to the current input.

**Comment by minad** [comment]
See `consult-narrow-key`. Please take a look at the README and the customization variables before opening issues.
