### ISSUE TITLE
Live preview in consult-ripgrep

### ISSUE THREAD

**Issue by 99702** [minad/consult#719]
Hello , 
Is it possible to live preview the buffers list that `consult-ripgrep` shows just like `consult-buffer`

**Comment by minad** [comment]
Please take a look at the README.

**Comment by 99702** [comment]
Hello thank you for making this awesome package. I love it. 
README was quite alot and difficult to understand , though i found solution 

`  (consult-customize
   consult-ripgrep
   :preview-key '(:debounce 0.2 any)
   consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   consult--source-bookmark consult--source-recent-file
   consult--source-project-recent-file
   :preview-key (kbd "M-."))
`
