### ISSUE TITLE
Error installing: compat 29.1.1 not found

### ISSUE THREAD

**Issue by dimas-cyriaco** [minad/consult#720]
I'm trying to install `consult` using the `use-package` snippet provided on the `README` file, but I'm getting this error:

```
⛔ Error (use-package): Failed to install consult: https://elpa.gnu.org/packages/compat-29.1.1.0.tar: Not found
```

Tryed adding a `(require 'compat)`, but it does not work.

How do I fix this?

**Comment by minad** [comment]
Compat is available on GNU ELPA.
