### ISSUE TITLE
Extremly slow consult-line with preview in an org file

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#721]
I just upgraded to the latest version of consult and vertico, and I noticed a significant slow down of `consult-line` which I regularly use. On my main org file with with around 6K lines, `consult-line` takes more than 2 seconds to appear the first time and then I have to wait 2 seconds for every keyboard entry.

Before the update, preview in consult-line was working without any significant slow downs. Unfortunately, I didn't make note of the version that I had of vertico and consult. When I commented out the new `Org 9.6 fold-core API` code in `consult--invisible-open-temporarily`, `consult-line` became normal again. 

I wonder if  a better solution is to widen the buffer while `consult-line` is being called and restore the restriction when it exists.

The is the profiler report
<details>
<pre>
       12602  97% - ...
       12602  97%  - immediate-which-key-for-narrow
       12602  97%   - apply
       12602  97%    - #<compiled 0xbbbe05d8f9ac9dd>
       12602  97%     - apply
       12602  97%      - consult--read-1
       12602  97%       - consult--with-preview-1
       12602  97%        - #<compiled -0x1a3da59c1d1d497>
       12602  97%         - completing-read
       12602  97%          - completing-read-default
       12602  97%           - apply
       12602  97%            - vertico--advice
       12602  97%             - #<subr completing-read-default>
       12602  97%              - read-from-minibuffer
       12602  97%               - apply
       12602  97%                - radian--advice-eval-expression-save-garbage
       12602  97%                 - apply
       12598  97%                  - #<subr read-from-minibuffer>
       12541  96%                   - consult--preview-post-command
       12541  96%                    - #<compiled 0x51eea6d4626551d>
       12541  96%                     - #<compiled -0x1fb7d343f30999b2>
       12541  96%                      - #<compiled -0x12e9aedba36ec8b8>
       12454  96%                       - consult--invisible-open-temporarily
       12399  95%                        - org-fold-core-get-regions
       12127  93%                         - org-fold-core-next-folding-state-change
       12117  93%                            #<compiled 0x17369c7a7a60e36b>
           1   0%                          + #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_25>
           1   0%                            #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_22>
          19   0%                         + org-fold-core-get-region-at-point
          15   0%                         + org-fold-core-get-folding-spec
          31   0%                        + org-fold-show-set-visibility
          61   0%                       + mapc
          10   0%                         run-hooks
          17   0%                   + consult--preview-minibuffer-exit
           7   0%                   + timer-event-handler
           2   0%                   + redisplay_internal (C function)
           1   0%                   + minibuffer-inactive-mode
           0   0%    Automatic GC
</pre>
</details>

**Comment by minad** [comment]
Duplicate #708. This is wontfix until the Org developers provide a better API.

**Comment by haji-ali** [comment]
Thanks! 

Is there a reason to not use the else code in `consult--invisible-open-temporarily` (which is the used code for other modes beside `org-mode`) while waiting for more efficient code. The `else` code seems to be working mostly OK.

**Comment by haji-ali** [comment]
Thanks! I will give it a try. 

Is there a reason why we can't use the code in the `else` part for org-mode as well while waiting for efficient code? It seems to be working OK for me.

**Comment by minad** [comment]
> Is there a reason why we can't use the code in the else part for org-mode as well while waiting for efficient code? It seems to be working OK for me.

Yes.

**Comment by haji-ali** [comment]
Just tested the new changes. Yes, it alleviates most of the problem (except for the initial call, as expected).
