### ISSUE TITLE
Completion behaves differently in *Completion* window

### ISSUE THREAD

**Issue by nurdann** [minad/consult#723]
I have added configuration from README.md
```
    (consult-customize consult-completion-in-region
                       :completion-styles '(orderless basic))

    (setq completion-in-region-function
      (lambda (&rest args)
        (apply (if vertico-mode
                   #'consult-completion-in-region
                 #'completion--in-region)
               args)))
```

However when I press TAB (`completion-at-point`) to complete a command in shell-mode I don't get narrowed results
![image](https://user-images.githubusercontent.com/23486971/213330757-14e2978d-9914-4f23-bf6c-6ca41c71599d.png)

**Comment by minad** [comment]
This is Vertico, not the Completions window. But I cannot reproduce this on Emacs 29. Please follow https://github.com/minad/consult#bug-reports.

**Comment by nurdann** [comment]
Solved by changing completion styles to
```
(consult-customize consult-completion-in-region
                       :completion-styles '(substring orderless basic))
```
