### ISSUE TITLE
Is it possible to give priority to opened file during consult-git-grep's results?

### ISSUE THREAD

**Issue by avatar-lavventura** [minad/consult#724]
I was wondering is it possible to change order of shown files in the output of
`consult-git-grep` , where I just want to give priority to the open buffer first.

For example current opened buffer is Driver.

`consult-git-grep` <import lib> shows a find text in a hidden folder `broker/.TODO.org_archive` first then in Driver.py.
Since its alphebetif `.<folder_name>` always comes first.

```
1/120  Git-grep (Project ebloc-broker): #import lib
     broker/.TODO.org_archive                                                                                                                                                                     $
18:import zlib
     broker/Driver.py                                                                                                                                                                             $
10:from contextlib import suppress
```

Can we change order, where the opened buffer show up first?

**Comment by minad** [comment]
The grep results come in asynchronously. If we order open file before closed files, it would lead to reshuffling while the results come in. This would be quite unexpected and confusing. Therefore I would not implement something like this. But you can of course implement this yourself in your user configuration. You could set an appropriate `vertico-sort-override-function` via `vertico-multiform-mode`.
