### ISSUE TITLE
consult-man does not show any candidates

### ISSUE THREAD

**Issue by ahsanp** [minad/consult#725]
Hello I've been trying to setup `consult-man` . However, using doing `M-x consult-man RET git RET` does not show any candidates.  It just says `[Match Required]` without providing any options or candidates. I would be extremely grateful for any help. 
Thank you!

**Comment by minad** [comment]
It seems you use the default completion UI? Press ? or TAB to see the candidates.

As alternative I suggest to use Vertico, which provides a more intuitive interface.

**Comment by ahsanp** [comment]
Sorry, I think I wasn't able to explain properly. I am using vertico, the following is my configuration:
```
(use-package vertico
  :ensure t
  :init
  (vertico-mode)

  (setq vertico-count 15)
  (setq vertico-resize nil)
  (setq vertico-cycle t)
  (setq vertico-preselect 'directory)

  (defun vertico-directory-delete-entry ()
  "Delete directory or entire entry before point."
  (interactive)
  (when (and (> (point) (minibuffer-prompt-end))
             (eq 'file (vertico--metadata-get 'category)))
    (save-excursion
      (goto-char (1- (point)))
      (when (search-backward "/" (minibuffer-prompt-end) t)
        (delete-region (1+ (point)) (point-max))
        t))))

  (defun my/vertico-insert ()
    (interactive)
    (let* ((mb (minibuffer-contents-no-properties))
           (lc (if (string= mb "") mb (substring mb -1))))
      (cond ((string-match-p "^[/~:]" lc) (self-insert-command 1 ?/))
            ((file-directory-p (vertico--candidate)) (vertico-insert))
            (t (self-insert-command 1 ?/)))))
  :bind (:map vertico-map
              ("C-l" . #'vertico-directory-delete-entry)
              ("/" . #'my/vertico-insert))
  )

(use-package consult
  :ensure t
  :config
  (setq consult-man-args "man")
  :bind (("C-c h i" . consult-imenu)
         ("C-c h o" . consult-locate)
         ("C-c h m" . consult-man)
         ([remap yank-pop] . consult-yank-pop)
         ([remap projectile-ripgrep] . consult-ripgrep)
         ([remap goto-line] . consult-goto-line)
         ([remap switch-to-buffer] . consult-buffer)))
```
Pressing `M-x consult-man RET` opens the vertico prompt in which I type `git`. Pressing `?` or `TAB` does not show any candidates.

**Comment by minad** [comment]
Seehttps://github.com/minad/consult#bug-reports

**Comment by matthew-piziak** [comment]
I have the same issue, reproduced with `emacs -Q`, and the recommended minimal setup:

```emacs-lisp
(package-initialize)
(require 'consult)
(require 'vertico)
(vertico-mode)
(setq completion-styles '(substring basic))
```
Emacs version: 28.2
man version 2.10.2
OS: NixOS 22.11

I see `!/0` in the echo area, presumably indicating "process exited with a nonzero error code". Where can I intercept that error to debug further? It does not appear in `_*consult-async*` for me.

**Comment by minad** [comment]
Maybe you are missing the obvious? `consult-man` is a search command, which can be used to search through man pages and description. You have to enter a search string. If you just want to see a list of man pages use builtin `man`.

**Comment by matthew-piziak** [comment]
Hah yes, good to check, thank you. 

If I enter `echo`, for example (and I do have `echo` on my system), then I see the following: `!/0    Manual entry! #echo`. No results appear.

**Comment by matthew-piziak** [comment]
Ah, whoops, I misread the README a little. The buffer is ` *consult-async*` with a leading space, not a leading underscore. I can see the log now:
```
consult--async-process started ("man" "-k" "echo")
consult--async-process sentinel: event=exited abnormally with code 16 lines=0
>>>>> stderr >>>>>
echo: nothing appropriate.
<<<<< stderr <<<<<
```

**Comment by matthew-piziak** [comment]
Interesting. I get results with `man -K`, i.e. `--global-apropos`, but not `man -k`, i.e. `--apropos`.

**Comment by matthew-piziak** [comment]
Thanks for the help, now that I have the error buffer I can do a bit of sleuthing to figure out why the default args don't work on my system, and I'll report back if I find out anything that can make it more robust for users like @ahsanp and me.

**Comment by matthew-piziak** [comment]
Aha, I figured it out for NixOS. https://nixos.wiki/wiki/Apropos

Manual caches are not created by default. Totally unrelated to `consult-man`. Sorry about the noise!
