### ISSUE TITLE
:lookup support in consult-buffer-sources

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#729]
Is there a way to have `:lookup`-like functionality in sources in `consult-buffer-sources` (similar to `:lookup` in `consult--read`)?
I want to use `consult--jump-state` for one of my sources, but it seems not possible without `lookup` to convert a candidate to a marker (unless I am misunderstanding something). I also have several other states that could be simplified with such functionality (to use the "standard" consult states rather than creating my own).

**Comment by minad** [comment]
You can attach text properties to the candidates.

**Comment by minad** [comment]
Example Consult source:

~~~ elisp
(defun consult-ext--point-register-p (reg)
  "Return non-nil if REG is a point register."
  (markerp (cdr reg)))

(defvar consult-ext-source-point-register
  `(:name     "Point Register"
    :narrow   (?r . "Register")
    :category consult-location
    :state
    ,(lambda ()
       (let ((state (consult--jump-state)))
         (lambda (action cand)
           (funcall state action (and cand (car (consult--get-location cand)))))))
    :enabled
    ,(lambda () (seq-some #'consult-ext--point-register-p register-alist))
    :items
    ,(lambda () (consult-register--candidates #'consult-ext--point-register-p)))
  "Point register source.")
~~~

**Comment by haji-ali** [comment]
Thanks! I did something similar with

```emacs-lisp
(defun my/consult-state-builder (state-fun return-fun lookup-fun)
  (lambda ()
    (let ((state (funcall state-fun)))
      (lambda (action cand)
        (let ((ccand (when cand (funcall lookup-fun cand))))
          (funcall state action ccand)
          (when (and ccand (eq action 'return))
            (funcall return-fun ccand)))))))
```
which I then called with
```emacs-lisp
`(...
   :state ,(my/consult-state-builder
                       #'consult--jump-preview
                       #'consult--jump 
                       (lambda (cand) (car-safe (consult--get-location cand))))
)
```
with this, I am almost done moving my `my/consult-jump-to-org-heading` command to `consult-buffer` using consult narrowing which is much better than having a separate command.

I am still trying to figure out the best way to run some code right before the narrowing to do something like pre-selecting nearest heading as in [here](https://github.com/minad/consult/wiki#pre-select-nearest-heading-for-consult-org-heading-and-consult-outline-using-vertico). It seems that `current-minibuffer-command` is some lambda function when narrowing.

I also had functionality to use an existing window (if a window is already visiting the org-file) instead of the current window. The way I currently do it is as follows:

```emacs-lisp
(let ((cur-wind (selected-window))
        restore-wind)
    (unwind-protect
        (progn (when-let (wind (get-buffer-window (org-get-agenda-file-buffer
                                                   (car (org-agenda-files)))))
                 (setq restore-wind t)
                 (select-window wind))
               (my/consult-jump-to-org-heading)
               (setq restore-wind nil))
      (when restore-wind
        (select-window cur-wind))))
```

but I couldn't figure out how to replicate this functionality when narrowing (it should be done for a particular source rather than for all sources). 

Any ideas?

**Comment by minad** [comment]
No idea, but if you figure out a solution, feel free to add it to the wiki.

**Comment by haji-ali** [comment]
Finally had some time to figure it. I added an advice to "reset" the point when narrowing so that on every narrow, the candidate closest to point is pre-selected. Not sure it's worth putting in the wiki since the use-case is too particular and the solution is similar to what's already there.

```emacs-lisp
(defun consult--set-previous-point ()
  "Save location of point. Used before entering the minibuffer."
  (setq consult--previous-point (list :point (point)
                                      :used nil)))

(defun consult-vertico--update-choose (&rest _)
  "Pick the nearest candidate rather than the first after updating candidates."
  (when (and consult--previous-point
             (memq current-minibuffer-command
                   '(consult-org-heading consult-outline)))
    (setq vertico--index
          (max 0 ; if none above, choose the first below
               (1- (or (seq-position
                        vertico--candidates
                        consult--previous-point
                        (lambda (cand point-pos) ; counts on candidate list being sorted
                          (> (cl-case current-minibuffer-command
                               (consult-outline
                                (car (consult--get-location cand)))
                               (consult-org-heading
                                (get-text-property 0 'consult--candidate cand)))
                             point-pos)))
                       (length vertico--candidates))))))
  (plist-put consult--previous-point :used t))

(define-advice consult-narrow (:before (key) reset-previous-point)
  (unless (eq key consult--narrow)
    (plist-put consult--previous-point :used nil)))
```

The other functionality, where I use an existing window cannot be replicated since all preview functions in consult use a lambda closure to capture the currently selected window, so the preview window cannot change based on what's narrowed.
