### ISSUE TITLE
consult-buffer seems to fail and no preview

### ISSUE THREAD

**Issue by deb75** [minad/consult#731]
Hi

I tried to follow the video tutorial [here](https://www.youtube.com/watch?v=QBvGa0Yg1NI)

When i run `consult-buffer`, I only get : 

```
(fn FILE)"] :enabled #[0 "\205\0	\207" [consult-project-function recentf-mode] 1] :items #[0 "\302 \211\205e\0\211G\303 \304\211\305\301!\205\0	\211\203^\0\211@\211\306H\307=\204(\0\310!\262\311\"\204W\0\312\"\203W\0\211\304O\211\313\232\203F\0\314\262\315\306\316\317\320B%\210\211B\262\210A\266\202\202\0\237)\262\266\204\207" [file-name-handler-alist recentf-list consult--project-root consult--buffer-file-hash nil boundp 0 47 expand-file-name gethash string-prefix-p "" "./" put-text-property 1 multi-category file] 14])] -2097051)
```

The `*Message*` buffer only displays this.

Actually, it did work in the first time, but with weird character at each end of line, like those above.
Also, file preview was not working.

Windows 11/mingw64/emacs 29.0.60

Regards

**Comment by minad** [comment]
Hi! Please follow https://github.com/minad/consult#bug-reports. Maybe you use an unsupported completion UI, e.g., Helm?

**Comment by deb75** [comment]
Hi,

Yes I currently use use `helm`.

Sorry for my misunderstanding, but I do not yet understand how `consult`, `vertico`
and other related packages work together, including `helm`.

Currently, my configuration is as follows, with the completion UI `vertico` :  
```elisp
(use-package vertico
  :init
  (vertico-mode))


(use-package orderless
  :init
  (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))

(use-package consult
  :bind
  ("C-x b" . consult-buffer)
  :hook (completion-list-mode . consult-preview-at-point-mode)
  )

(use-package marginalia)
(marginalia-mode)
``` 

as advocated by the video tutorial.

I will try again after having disabled completely `helm` before, as advocated in the bug-report.

Regard

**Comment by deb75** [comment]
It works, thanks !
