### ISSUE TITLE
consult--display-width: Symbol’s function definition is void: compat-string-width

### ISSUE THREAD

**Issue by anbanpillay** [minad/consult#732]
In Doom emacs, compat is unpinned in packages.el. The  error `consult--display-width: Symbol’s function definition is void: compat-string-width` pops up when doing C-x C-b to list buffers.  `compat` version installed is 29.1.1.0.

**Comment by minad** [comment]
You must unpin Consult. Isn't that obvious after you unpinned Compat? Please don't open Doom-specific issues. There is the Doom discord and Doom issue tracker for that.
