### ISSUE TITLE
Error in post-command-hook (consult--preview-post-command): (wrong-type-argument stringp t)

### ISSUE THREAD

**Issue by joostkremers** [minad/consult#733]
Trying to run `consult-focus-lines` gives me this error:

    Error in post-command-hook (consult--preview-post-command): (wrong-type-argument stringp t)
    
I can still type something at the prompt `"Focus on lines:"`, but no lines are focused and after pressing RET, I get the message "All lines revealed".

`consult-keep-lines` has the same problem.

Emacs version is:

    "GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6) of 2023-01-03"
 
 The error also occurs with `emacs -Q`, loading just `consult` and `compat`.

**Comment by minad** [comment]
Thanks for the report, I will take a look.

**Comment by chriselrod** [comment]
`consult-goto-line` gives me the same error.
