### ISSUE TITLE
consult-imenu returned "invalid function 1"

### ISSUE THREAD

**Issue by milanglacier** [minad/consult#734]
the following code will expand to:

```lisp
(consult--slow-operation "Building Imenu..."
     (consult-imenu--items))

```

```lisp
   (with-delayed-message
    (1 "Building Imenu...")
    (consult--with-increased-gc
     (consult-imenu--items)))
```

More information: I am using emacs28, and it seems that compat does not support `with-delayed-messages`, see its information at `2.5.3`

```
2.5.3 Missing Definitions
-------------------------

Compat does not provide support for the following Lisp features
implemented in 29.1:

   * The command `string-edit' and `read-string-from-buffer'.

   * The function `readablep'.

   * The macro `with-delayed-message' and the function
     `funcall-with-delayed-message'.


```

**Comment by minad** [comment]
Compat 29.1.3.2 supports it.

**Comment by milanglacier** [comment]
> Compat 29.1.3.2 supports it. Did you update everything?

Yes, this is a corner case caused by `straight`.

`straight` uses its own mirror for elpa packages. And maybe its mirror does not get updated timely. the state of `compat` is still on 29.1.1.0.

While `consult` is also on Melpa, so `consult` is at the latest version, which causes the packages to unmatch.

**Comment by minad** [comment]
It seems the Straight ELPA mirror did not update for three weeks. See https://github.com/emacs-straight/compat/commits/master. I suggest to disable the mirror via `straight-recipes-gnu-elpa-use-mirror`. While the the Straight ELPA mirror is well intended, it is unfortunately constantly causing issues.

**Comment by milanglacier** [comment]
> It seems the Straight ELPA mirror did not update for three weeks. See https://github.com/emacs-straight/compat/commits/master. I suggest to disable the mirror via `straight-recipes-gnu-elpa-use-mirror`. While the the Straight ELPA mirror is well intended, it is unfortunately constantly causing issues.
> 
> See also https://github.com/minad/consult#bug-reports.

The straight hosted ELPA has been updated to use latest compat version which solves the confliction with consult.
