### ISSUE TITLE
Recent change in behaviour of consult-lines with `=` in the search string?

### ISSUE THREAD

**Issue by sthesing** [minad/consult#735]
I observed a change of behaviour of `consult-lines` when the search terms contain `=`: 

I have several denote files with names containing `=`, e.g.:
```
20230203T133700==02--foo__foo.org
20230203T133800==02a--bar__bar.org
20230203T133900==04b1--baz.org
20230203T134000--02--no-equal-sign.org
```
## Expected behaviour:
In dired, I used to be able to use `consult-lines` to filter by e.g. 

- `=02` and would see only the first two files in the minibuffer,
- `=02.?-` (appending regex syntax) and see only the first file in the minibuffer.
- `02.?-` and see all but the third file in the minibuffer.

## Observed behaviour:
Now (20230202.1237), when I search for

- `=02`, I see a list of all filenames containing `02`
- `=02.?`, I see no files whatsoever and `!/0` in the search line
- `02.?-` works as expected.

## Question

Was this change intentional? 
If not: then please consider this a bug report. 
If yes: is there a way to restore the previous behaviour in my config?

I'm sorry if I overlooked something...

**Comment by oantolin** [comment]
This is due to a chandelier in orderless'default configuration (suggested by @minad, though!). The `=` at the beginning or end of space-separated component of the input signals the rest of that component should match literally. A few other pieces of syntax were added to the default configuration too (see the orderless Readme, the section about style dispatchers). To get the previous behavior simply `(setq orderless-style-dispatchers nil)`.

**Comment by minad** [comment]
@oantolin That's the downside of setting the dispatcher as default. Maybe we should reconsider that? I initially proposed to not change the behavior. It is likely that many people just use Orderless in its default configuration.

**Comment by oantolin** [comment]
Yeah, maybe I should go back to `orderless-style-dispatchers` being `nil` by default.

**Comment by oantolin** [comment]
I did want to make `!` default syntax for negative literals for a long time, though. Maybe I just waited too long.

**Comment by minad** [comment]
On 2/3/23 14:58, Omar Antolín Camarena wrote:
> I did want to make |!| default syntax for negative literals for a long
> time, though. Maybe I just waited too long.

I think it is good to have no syntax by default except literals and
regexps. Everything on top is more advanced and needs some time to learn
anyway, thus setting a variable does not hurt.

**Comment by sthesing** [comment]
Thanks, @oantolin and @minad ! Not only for these answers, also for your great packages!
