### ISSUE TITLE
consult-line can't jump normally when I push the command evil-visual-line before

### ISSUE THREAD

**Issue by 1925381584** [minad/consult#738]
hi,minad
there is a strange thing here, first I push the command evil-visual-line,then I use the command consult-line searching the symbol and then I push the enter key, but the cursor cannot jump normally. I would appreciate it if you could help me look at this problem

**Comment by minad** [comment]
I don't use Evil, but evil-collection supports Consult. Doomemacs also uses both Consult and Evil. You may find a solution there.

**Comment by 1925381584** [comment]
OK. Thanks for talking to me.
