### ISSUE TITLE
Is there a way search for buffers of a given major mode in consult-buffer?

### ISSUE THREAD

**Issue by JonatanSahar** [minad/consult#739]
Hi,
Sorry to post it here as it's obviously not actually an issue.
I'd like to easily jump to an (e.g.) open dired buffer, and I thought it made sense to be able to extend the fields that are searched to include the major mode - as it's information that is already displayed in the minibuffer of consult-buffer.
Is there away to achieve this without adding a new source virtual buffers (which seems complex for me atm)?

Thanks!
And thanks for all the amazing work too :)

**Comment by minad** [comment]
Thanks! No, that's not possible right now. I have some code which does did by extending the completion filtering, but it didn't materialize as a package yet. See https://github.com/oantolin/orderless/issues/30 and the linked issues for more background. For now you can use embark-export/ibuffer.

**Comment by minad** [comment]
See https://github.com/minad/consult/issues/206 and my https://github.com/minad/consult/issues/206#issuecomment-1947463965. Matching on annotations will soon be available in Orderless.

**Comment by JonatanSahar** [comment]
Thank you for updating!
