### ISSUE TITLE
consult--multi alignment vs marginalia

### ISSUE THREAD

**Issue by haji-ali** [minad/consult#740]
I noticed that marginalia has custom alignment with `marginalia-align`, but `consult--multi` with a custom `:annotate` seems fixed to always align to the right. 
I know that the alignment in consult is more basic than marginalia, but I was wondering if there can be an option to left align at least (the default in marginalia).

**Comment by minad** [comment]
`consult--multi` already aligns to the left taking the candidate width into account:
 https://github.com/minad/consult/blob/d20b238c2fb4d51c833378d438e4f2049bff7c14/consult.el#L2733-L2735

We could add options like `marginalia-align-*` but would should they actually do? Probably the problem in your case is that your candidates are too long. Did you see #713?

**Comment by haji-ali** [comment]
Yes, you're right. The problem seems to be consult considers all candidates on the first view in a `consult--multi` when deciding what the left alignment is. However, the alignment is not recalculated when narrowing to much shorter candidates.

Marginalia doesn't suffer from this, it seems, because the alignment is based on visible candidates only. (I am only speculating, you know better).

 I'll read #713 to see if there's a suggested solution for this.

**Comment by minad** [comment]
@haji-ali Okay, I think I found a good solution to compute the annotation alignment dynamically. The new function `consult--annotate-align` can also be used by other `consult--read` functions, which is quite convenient.

**Comment by haji-ali** [comment]
@minad, fantastic! The new behavior seems to be that the annotation is aligned based on visible entries similar to marginalia!

This is not super important, but is there a way to "reset" the view so that after narrowing to a hidden source, the alignment is recomputed for the new candidates? At the moment, the left alignment seems to only move to the right (if necessary) after narrowing, but never to the left (even when all visible candidates are short). 
I tried setting `consult--annotate-align-width` before narrowing but that didn't work.

**Comment by minad** [comment]
> This is not super important, but is there a way to "reset" the view so that after narrowing to a hidden source, the alignment is recomputed for the new candidates? At the moment, the left alignment seems to only move to the right (if necessary) after narrowing, but never to the left (even when all visible candidates are short).
I tried setting consult--annotate-align-width before narrowing but that didn't work.

That's not possible to do automatically due to the separation of backend and completion UI. Iirc not even Marginalia does that. But you should be able to override the variable with a reset command.

**Comment by haji-ali** [comment]
Oh, I just re-tested and you are right. marginalia alignment doesn't get reset either (it looked like it was being reset compared to the previous behavior of consult).

In any case, `consult` is now much better with alignment IMO. Thank you for taking the time to fix this issue.
