### ISSUE TITLE
How to debug: Invalid preview key according to  ‘key-valid-p’: [67108896]

### ISSUE THREAD

**Issue by holgerschurig** [minad/consult#741]
Hi,

I get this error message from consult for almost every key I enter while consult is open. Can you give me on how to debug this?

I found the string in consult.el, but still don't know why it is triggered. And the comment, that this will become an error, not just a warning, makes me fear for the worst.

Emacs is self-compiled from branch emacs-29. I am using Doom, but in "unpinned" embark consult vertico marginalia orderless so that I have their current git versions, and not the much older versions that Doom maintainers once deemed to be okay.

Therefore, consult is now at git b22a7de62ee4adf766be2f867dee8b6980902bba

**Comment by minad** [comment]
See https://github.com/doomemacs/doomemacs/issues/7064
