### ISSUE TITLE
Getting an error with the new commit regarding cl-with-gensyms

### ISSUE THREAD

**Issue by a3madkour** [minad/consult#742]
Hello, 

I noticed that there was a commit upping the compat dependency and replacing a few line with cl-with-gensyms.

Sorry if this is a noob question, but for some reason I am getting a (void-function cl-with-gensyms) error. 

Where is this function defined? I am using straight and use-package, I would have assumed that what ever the dependency it has would be installed. 

I am running emacs 28.2 btw. 

Thank you

**Comment by minad** [comment]
See https://github.com/radian-software/straight.el/issues/1049 and https://github.com/radian-software/gnu-elpa-mirror/issues/14.
