### ISSUE TITLE
No suggestions buffer running consult-buffer-other-window in vertico-buffer-mode

### ISSUE THREAD

**Issue by alikthename** [minad/consult#744]
When using consult with vertico in vertico-buffer-mode running C-x 4 b launches consult-buffer-other-window command.

this gives me the buffer with the content I had before running above command and buffer with consult previews (the frame is now vertically split), but no buffer with completion suggestions and and entered text

**Comment by minad** [comment]
I fixed this in Vertico by marking the window as dedicated.
