### ISSUE TITLE
"Invalid function: consult--slow-operation" error message 

### ISSUE THREAD

**Issue by Hoboneer** [minad/consult#746]
Hi, following the instructions for bug reports (https://github.com/minad/consult#bug-reports), I ran the following code in `emacs -Q`:

```emacs-lisp
(package-initialize)
(require 'consult)
(require 'vertico)
(vertico-mode)
(setq completion-styles '(substring basic))
```

Running `describe-variable` on `lexical-binding` while in the scratch buffer shows its value is `t`.

Running `consult-org-agenda` (after setting `org-agenda-files`) and `consult-imenu` results in:

- `consult-org-heading: Invalid function: consult--slow-operation`; and
- `consult-imenu: Invalid function: consult--slow-operation` respectively.

Interestingly, copy-and-pasting the definition of `consult-imenu` as `my/consult-imenu` and then re-evaluating it results in the function working as expected without the error message above.

I've read #734.

Relevant package versions:

- consult: 0.32
- vertico: 1.1
- compat: 29.1.3.4

I run the Emacs version on Debian Bullseye with `package.el`.  I installed consult and vertico using `package.el`--not from Debian.

Some guidance would be appreciated.

Cheers

**Comment by minad** [comment]
Just to make sure - can you uninstall and reinstall the packages compat, consult and vertico? It seems like something went wrong during the installation. `consult--slow-operation` is a macro. The macro is defined by consult.el which is required by both consult-imenu.el and consult-org.el. There is nothing obviously wrong here.

**Comment by Hoboneer** [comment]
It works now, thanks!

Yeah, I tried to go through the issue with edebug and macrostep but the code didn't look wrong.

I imagine that re-evaluating the function definition used the correct macro.
