### ISSUE TITLE
Consult-git-grep receives no input

### ISSUE THREAD

**Issue by Dicridon** [minad/consult#750]
Hi Daniel, thank you for bringing Consult to Emacs. I'm new to Consult and have some trouble working with it. I'm not sure how to troubleshoot and wish you could give me some help.

I'm using `consult-git-grep` to find some symbols as shown in the GIF in the readme. When I type `M-x consult-git-grep RET`, the following output shows and I try to type a symbol name, 
![image](https://user-images.githubusercontent.com/24477137/221124436-4076a82a-02fe-4ccd-bff5-0b63367eef3c.png)

however, the minibuffer only accepts input of one character (R in the following figure), if I type more characters, the later ones just overwrite the former ones.
![image](https://user-images.githubusercontent.com/24477137/221124300-073eb11c-e968-4277-89fc-e0a58afa0b11.png)

Then I type `RET`, the minibuffer just shows `match required`
![image](https://user-images.githubusercontent.com/24477137/221124607-dbff922e-ec16-49c3-978d-a381baa67011.png)

`vertico-mode` is already enabled and the above issue also happens when I use `consult-man`, `consult-grep`, and `consult-eglot`. But `consult-imenu`, `consult-flymake`(flymake is enabled), and `consult-project-buffer` work well. Maybe I misunderstood how Consult should be used? Or do you have any idea what I should do to make Consult work?

**Comment by minad** [comment]
Hi! Please follow https://github.com/minad/consult#bug-reports step by step. This will help investigating the issue. Thanks!
