### ISSUE TITLE
Issues with new multi-path code

### ISSUE THREAD

**Issue by rswgnu** [minad/consult#754]
What I have found so far:

1. Need to expand paths with ~ in them; otherwise, commands like grep and find treat this literally and do not match to the home directory.

2. When send a list of paths to consult-ripgrep, it still adds a "." path in to the command, searching the current dir when this should instead just be the set of paths in the list.

**Comment by minad** [comment]
Thanks, should be fixed. But I could not reproduce 2.

**Comment by rswgnu** [comment]
Thanks.  Will test again today.

**Comment by rswgnu** [comment]
#2 was that consult-ripgrep-args was cached and needed to be reset to reflect your updates, so that is a non-issue.
