### ISSUE TITLE
consult-git-grep: fatal: option '-not' must come before non-option arguments

### ISSUE THREAD

**Issue by eaibmz** [minad/consult#756]
Hi,

recently i started getting the following error with consult-git-grep:

```
fatal: option '-not' must come before non-option arguments
```

Consult version: `20230227.906`
git version: `2.39.2`

This seems to be a message returned by `git`.
Any idea what is wrong ?

Regards
Alex

**Comment by eaibmz** [comment]
`consult-grep` and `consult-ripgrep` also stopped working.

**Comment by eaibmz** [comment]
And it also seems to happen after some event only.
It seems to work for some and then for some reason stops working and i get the above error messages.

**Comment by minad** [comment]
In my setup I don't see any issue. There was a recent change to the command line builders. Check out the changelog. Maybe you adjusted the variables `consult-git-grep-args` etc? If this does not resolve it, please provide a minimal recipe.

**Comment by minad** [comment]
Also checkout the ` *consult-async*` log buffer. There you will see the command line and you can analyze what's wrong.

**Comment by minad** [comment]
Found the issue. There was some accidental mutation.
