### ISSUE TITLE
Need Help; how to use selectrum-completion-in-region?

### ISSUE THREAD

**Issue by poulpoulsen** [minad/consult#76]
Hello,
i try to use completion-in-region after read the lines in documentation.
But i think, that i do not understand or use it correct.
I always get the following error after call it from minibuffer.

command-execute: Wrong type argument: commandp, selectrum-completion-in-region
Regards
Poul

**Comment by minad** [comment]
This sounds like a selectrum issue. Are you using the newest version of both consult and selectrum?

**Comment by poulpoulsen** [comment]
Hello,
Yes i use the latest melpa and emacs 28.
No other issues so far.
I will close it here.
