### ISSUE TITLE
Question: auto-select match when only one candidate is available

### ISSUE THREAD

**Issue by sach2** [minad/consult#762]
Hi,
I have been using `consult--read` in my elisp code, it's working out very well for me. I started using this function when I came across this function while reading the consult code.  
**First question** is if I should be using this function in terms of api breaking changes, recommendations, etc.  

Second thing I wanted to achieve is below scenario:  
consult read asks for selections, out of n selections, I filter 1 by typing some characters, then I would hit Enter to select.  
I wanted to **auto-select the candidate** as soon as number of available candidates become 1.  (I should not need to press Enter).
Is this feasible, how to do if so?

**Comment by minad** [comment]
I recommend to use `completing-read` instead of `consult--read`. This way you avoid breaking changes. The auto select is feasible if you add a post-command-hook to Vertico, which exits as soon as there is only a single candidate left.
