### ISSUE TITLE
Some consult commands fail

### ISSUE THREAD

**Issue by enikar** [minad/consult#763]
Hi,

I didn't check for all commands, but at least the commands `consult-buffer` and `consult-bookmark` fail with the error:
`consult--key-parse: [67108907] is not a valid key definition; see ‘key-valid-p’`.

I don't understand why `key-valid-p` returns nil.

That occurs since I upgrade to version 20230228.1346 with emacs 28.2 and 
emacs 29.0.60

I use consult with vertico, marginalia, prescient, orderless and embark.

Anyway, many thanks for your sofware.

**Comment by minad** [comment]
Duplicate #747

**Comment by enikar** [comment]
Well, I wrote this in my config:
```(use-package consult
  :commands (consult-customize) ;; for affe
  :custom (completion-in-region-function #'consult-completion-in-region)
          (xref-show-xrefs-function #'consult-xref)
          (xref-show-definitions-function #'consult-xref)
          (consult-project-root-function #'deadgrep--project-root) ;; ensure ripgrep works
          (consult-preview-key '(:debounce 0.5 any))

  :init (general-def
          "C-x b"    #'consult-buffer
          "C-x 4 b"  #'consult-buffer-other-window
          "C-x r l"  #'consult-bookmark
          "C-x C-f"  #'find-file
          "C-c m"    #'consult-imenu
          "M-y"      #'consult-yank-pop
          "M-s M-i"  #'consult-info
          [remap repeat-complex-command] #'consult-complex-command)
        (general-def
          :states  'normal
          :keymaps 'global
          "C-w b"  #'consult-buffer-other-window)
        (prefix-c-xt    "r"  #'consult-recent-file)
        (leader-ala-vim "/"  #'consult-line
                        "g c" #'consult-ripgrep)
        (setq xref-show-xrefs-function #'consult-xref
              xref-show-definitions-function #'consult-xref)
        (setq register-preview-delay 0.5
              register-preview-function #'consult-register-format)
  :config (setq consult-narrow-key (kbd "C-+"))
          (setq consult-project-function #'(lambda (_) (locate-dominating-file "." ".git"))))```

Should I set the custom variable `consult-preview-key` outside the custom section of
use-package, using consult-customize instead ?

It's not clear for me, sorry.

Well I tried to comment out the setting for `consult-preview-key`, and the error still remains.

**Comment by minad** [comment]
Your `consult-narrow-key` is invalid, you should write `(setq consult-narrow-key "C-+")`.

**Comment by enikar** [comment]
Ok, thanks.

**Comment by oantolin** [comment]
No, you can't blindly remove `kbd`! For example, `define-key` requires it, but the newer `keymap-set` does not. Read the documentation of whatever function or macro you are using with the key binding in each case.

**Comment by enikar** [comment]
Yes I know that. In my emacs 29 config, I replaced all define-key with keymap-set. As well, I use general where it is
possible.

**Comment by oantolin** [comment]
Good. I thought I'd warn you just in case. :)

**Comment by minad** [comment]
The general trend is to move away from the low level key representations to the readable string format. The functions `kbd` or `key-parse` translate from the readable string format to the low-level representation. The new `keymap-*` functions use the readable string format, as does `use-package`, `general` and now Consult and Embark.

**Comment by enikar** [comment]
Oh! embark also use the string format. I'm going to remove the only remaining `kbd` in my config. Nice!
