### ISSUE TITLE
consult-org-heading and consult-org-agenda don't show inherited tags

### ISSUE THREAD

**Issue by scvalex** [minad/consult#765]
When `org-use-tag-inheritance` is true, org headings are supposed to inherit tags from their parents.

To copy the example from [the org manual](https://orgmode.org/manual/Tag-Inheritance.html):
```
* Meeting with the French group      :work:
** Summary by Frank                  :boss:notes:
*** TODO Prepare slides for him      :action:
```

All the headings above have the `work` tag.  And then there's also a way to add tags on a per-file basis.

`consult-org-heading` and `consult-org-agenda` don't include any inherited tags.

![image](https://user-images.githubusercontent.com/2588/224513301-0a173fd8-5b04-4bfe-81d9-48d5f0950a22.png)

I think the problem is that `consult-org--headings` is using `org-heading-components` instead of [`org-entry-properties`](https://orgmode.org/manual/Using-the-Property-API.html#Using-the-Property-API).

`org-entry-properties` returns the following alists for the example:

```
(("CATEGORY" . "???") ("BLOCKED" . "") ("ALLTAGS" . ":work:") ("TAGS" . ":work:") ("FILE") ("PRIORITY" . "B") ("ITEM" . "Meeting with the French group"))
(("CATEGORY" . "???") ("BLOCKED" . "") ("ALLTAGS" . #(":work:boss:notes:" 1 5 (inherited t ws-butler-chg chg fontified t face ... mouse-face highlight keymap ...))) ("TAGS" . ":boss:notes:") ("FILE") ("PRIORITY" . "B") ("ITEM" . "Summary by Frank"))
(("CATEGORY" . "???") ("BLOCKED" . "") ("ALLTAGS" . #(":work:boss:notes:action:" 1 5 (inherited t ws-butler-chg chg fontified t face ... mouse-face highlight keymap ...) 6 10 (inherited t ws-butler-chg chg fontified t face ... mouse-face highlight keymap ...) 11 16 (inherited t ws-butler-chg chg fontified t face ... mouse-face highlight keymap ...))) ("TAGS" . ":action:") ("FILE") ("PRIORITY" . "B") ("TODO" . "TODO") ("ITEM" . "Prepare slides for him"))
```

Note that TAGS is just the tags on the current heading and ALLTAGS is the inherited ones as well.

You can get just the ALLTAGS for the current line with:

```
(let ((tags (org-entry-get (point) "ALLTAGS")))
  (set-text-properties 0 (length tags) nil tags)
  tags)
```

I think the smallest change would be to continue using `org-heading-components` for everything else, and get the tags using something like the above.

If you agree with the above, I can try writing the patch.

**Comment by minad** [comment]
Hi, thanks for the proposal and the analysis! It would be welcome if implement this and propose a PR. My only concern is that your approach leads to performance problems. Are the inherited tags somehow cached, such that `org-entry-properties` doesn't have to walk up the tree all the time? A better alternative is to remember the tags while mapping over the headings. This way we can add the remembered tags to the headings which are more deeply nested. This should ensure that `consult-org--headings` stays as fast as it is.

**Comment by scvalex** [comment]
Ah, that's a fair concern.

We'd need something slightly more complicated than remembering while mapping because org has a way to specify tags at a file level (`#+FILETAGS: :Peter:Boss:Secret:`) and also has a variable to control which tags are inherited and which aren't (`org-tags-exclude-from-inheritance`).

I think what would work is calling `org-get-tags` on the top-level headlines in each file (thus handling `FILETAGS`) and then remembering while mapping for the other headlines in each file.  We could also ignore the tags in `org-tags-exclude-from-inheritence` to get org's current behaviour.  I'm not super keen on this because it feels like re-implementing org internals.

I think `org-agenda` implements this logic in `org-scan-tags`.  Going by variable names in the implementation, it does do some caching.

```
(org-scan-tags 'agenda t nil)
Meeting with the French group              :work:
Summary by Frank               :work::boss:notes:
TODO Prepare slides for him :work:boss:notes::action:
```
But this removes the heading levels and I can't see how to get those back.

Also, `org-get-tags` is an even better function to get just the tags of the current headline, so never mind what I said earlier about `org-entry-properties`.

This is all getting beyond my skill at elisp.

**Comment by minad** [comment]
Maybe using `org-get-tags` is okay. We also use `org-get-outline-path`, which also has to scan backwards or use some cached ancestors. We should check that `org-get-outline-path` and `org-get-tags` are efficient. At least `org-get-outline-path` seems to use some outline path cache.

**Comment by scvalex** [comment]
`org-get-tags` does indeed use a cache which seems to be enabled in all my org buffers.

Let's continue any discussion on the pull request.
