### ISSUE TITLE
Don't close consult minibuffer after hitting <RET>

### ISSUE THREAD

**Issue by wailings** [minad/consult#768]
Hi, when I'm using consult-file or consult-grep, hitting RET on a candidate opens the file and closes the minibuffer.  
Is it possible to have it configured so RET (or maybe M-RET as an alternative) opens the file but keeps the minibuffer with the results alive?

**Comment by minad** [comment]
You can either use preview and move to the other window instead of pressing RET or use embark-act with embark-quit-after-action=nil.
