### ISSUE TITLE
consult--jump-nomark Error?

### ISSUE THREAD

**Issue by kamuycikap9821** [minad/consult#775]
Good evening everyone.

My environment
Ubuntu22.04LLTS
Emacs28.2

When I run consult-ag and type in certain characters, the search results appear in the minibuffer.
After that, when I move the cursor to the search result displayed in the minibuffer and hit the Enter key, I get an error.
I believe the correct behavior is that the relevant line of the relevant file is displayed in the buffer.

Is this a consult-specific problem?
Am I using it incorrectly?

I have already installed ag.
M-x ag search and jump to the relevant section works fine.

The error message indicates that the consult--jump-nomark function is receiving a value that is not of the expected integer or marker type. Specifically, the consult--jump-nomark function is receiving the string #("99-globalkey.el:13:25:(define-key global-map (kbd ..." which is probably an invalid value.

-- emacs emacs --debug-init
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p #("99-globalkey.el:13:25:(define-key global-map (kbd ..." 0 15 (filename "99-globalkey.el" row "13" column "25" face consult-file) 15 16 (filename "99-globalkey.el" row "13" column "25") 16 18 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 18 19 (filename "99-globalkey.el" row "13" column "25") 19 21 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 21 73 (filename "99-globalkey.el" row "13" column "25")))
  consult--jump-nomark(#("99-globalkey.el:13:25:(define-key global-map (kbd ..." 0 15 (filename "99-globalkey.el" row "13" column "25" face consult-file) 15 16 (filename "99-globalkey.el" row "13" column "25") 16 18 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 18 19 (filename "99-globalkey.el" row "13" column "25") 19 21 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 21 73 (filename "99-globalkey.el" row "13" column "25")))
  #f(compiled-function (cand restore) #<bytecode -0x1a88bf9b4373f3b5>)(#("99-globalkey.el:13:25:(define-key global-map (kbd ..." 0 15 (filename "99-globalkey.el" row "13" column "25" face consult-file) 15 16 (filename "99-globalkey.el" row "13" column "25") 16 18 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 18 19 (filename "99-globalkey.el" row "13" column "25") 19 21 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 21 73 (filename "99-globalkey.el" row "13" column "25")) nil)
  #f(compiled-function (cand restore) #<bytecode 0x1498bfb52ef21f76>)(#("99-globalkey.el:13:25:(define-key global-map (kbd ..." 0 15 (filename "99-globalkey.el" row "13" column "25" face consult-file) 15 16 (filename "99-globalkey.el" row "13" column "25") 16 18 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 18 19 (filename "99-globalkey.el" row "13" column "25") 19 21 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 21 73 (filename "99-globalkey.el" row "13" column "25")) nil)
  #f(compiled-function (action cand) #<bytecode -0x168afdfe824d50a4>)(#("99-globalkey.el:13:25:(define-key global-map (kbd ..." 0 15 (filename "99-globalkey.el" row "13" column "25" face consult-file) 15 16 (filename "99-globalkey.el" row "13" column "25") 16 18 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 18 19 (filename "99-globalkey.el" row "13" column "25") 19 21 (filename "99-globalkey.el" row "13" column "25" face consult-line-number) 21 73 (filename "99-globalkey.el" row "13" column "25")) nil)
  #f(compiled-function () #<bytecode 0x5d25a5aa4696494>)()
  #f(compiled-function (action) #<bytecode -0x1ee35812e0e6bf4d>)(refresh)
  #f(compiled-function () #<bytecode -0x1b48be0ed80f788>)()
  apply(#f(compiled-function () #<bytecode -0x1b48be0ed80f788>) nil)
  timer-event-handler([t 25631 42265 359526 0.2 #f(compiled-function () #<bytecode -0x1b48be0ed80f788>) nil nil 340000 nil])
  read-from-minibuffer("Consult ag: : " "#" (keymap (10 . minibuffer-complete-and-exit) (13 . minibuffer-complete-and-exit) keymap (menu-bar keymap (minibuf "Minibuf" keymap (tab menu-item "Complete" minibuffer-complete :help "Complete as far as possible") (space menu-item "Complete Word" minibuffer-complete-word :help "Complete at most one word") (63 menu-item "List Completions" minibuffer-completion-help :help "Display all possible completions") "Minibuf")) (27 keymap (103 keymap (27 keymap (99 . switch-to-completions))) (118 . switch-to-completions)) (prior . switch-to-completions) (63 . minibuffer-completion-help) (32 . minibuffer-complete-word) (9 . minibuffer-complete) keymap (20 . undefined) (26) (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the min...") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuf...") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence "\15" :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (13 . exit-minibuffer) (10 . exit-minibuffer) (7 . abort-minibuffers) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-line-or-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-line-or-history-element) (next . next-history-element) (27 keymap (60 . minibuffer-beginning-of-buffer) (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) nil nil nil nil)
  #f(compiled-function (prompt collection &optional predicate require-match initial-input hist def inherit-input-method) "Default method for reading from the minibuffer with completion.\nSee `completing-read' for the meaning of the arguments." #<bytecode 0x17491aa2d8aca3d5>)("Consult ag: : " #f(compiled-function (str pred action) #<bytecode 0x41a96075b56f099>) nil t "#" nil nil nil)
  apply((#f(compiled-function (prompt collection &optional predicate require-match initial-input hist def inherit-input-method) "Default method for reading from the minibuffer with completion.\nSee `completing-read' for the meaning of the arguments." #<bytecode 0x17491aa2d8aca3d5>) "Consult ag: : " #f(compiled-function (str pred action) #<bytecode 0x41a96075b56f099>) nil t "#" nil nil nil))
  vertico--advice(#f(compiled-function (prompt collection &optional predicate require-match initial-input hist def inherit-input-method) "Default method for reading from the minibuffer with completion.\nSee `completing-read' for the meaning of the arguments." #<bytecode 0x17491aa2d8aca3d5>) "Consult ag: : " #f(compiled-function (str pred action) #<bytecode 0x41a96075b56f099>) nil t "#" nil nil nil)
  apply(vertico--advice #f(compiled-function (prompt collection &optional predicate require-match initial-input hist def inherit-input-method) "Default method for reading from the minibuffer with completion.\nSee `completing-read' for the meaning of the arguments." #<bytecode 0x17491aa2d8aca3d5>) ("Consult ag: : " #f(compiled-function (str pred action) #<bytecode 0x41a96075b56f099>) nil t "#" nil nil nil))
  completing-read-default("Consult ag: : " #f(compiled-function (str pred action) #<bytecode 0x41a96075b56f099>) nil t "#" nil nil nil)
  completing-read("Consult ag: : " #f(compiled-function (str pred action) #<bytecode 0x41a96075b56f099>) nil t "#" nil nil nil)
  #f(compiled-function () #<bytecode 0x59594d95096782>)()
  consult--with-preview-1(any #f(compiled-function (action cand) #<bytecode -0x168afdfe824d50a4>) #f(compiled-function (input cand) #<bytecode 0x1a9e131041340b53>) #f(compiled-function (&rest args2) #<bytecode 0x45d0f3fd3a41c47>) #f(compiled-function () #<bytecode 0x59594d95096782>))
  consult--read-1(#f(compiled-function (action) #<bytecode 0x1a1af59a54ddabcc>) :prompt "Consult ag: : " :lookup consult--lookup-member :state #f(compiled-function (action cand) #<bytecode -0x168afdfe824d50a4>) :initial "#" :require-match t :category file :sort nil :prompt "Select: " :preview-key any :sort t :lookup #f(compiled-function (input cands x) #<bytecode 0x4aac387ed301287>))
  apply(consult--read-1 #f(compiled-function (action) #<bytecode 0x1a1af59a54ddabcc>) (:prompt "Consult ag: : " :lookup consult--lookup-member :state #f(compiled-function (action cand) #<bytecode -0x168afdfe824d50a4>) :initial "#" :require-match t :category file :sort nil :prompt "Select: " :preview-key any :sort t :lookup #f(compiled-function (input cands x) #<bytecode 0x4aac387ed301287>)))
  consult--read(#f(compiled-function (action) #<bytecode 0x1a1af59a54ddabcc>) :prompt "Consult ag: : " :lookup consult--lookup-member :state #f(compiled-function (action cand) #<bytecode -0x168afdfe824d50a4>) :initial "#" :require-match t :category file :sort nil)
  consult-ag()
  funcall-interactively(consult-ag)
  call-interactively(consult-ag record nil)
  command-execute(consult-ag record)
  execute-extended-command(nil "consult-ag" nil)
  funcall-interactively(execute-extended-command nil "consult-ag" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by minad** [comment]
Please report this on the consult-ag issue tracker. Thanks!
