### ISSUE TITLE
`consult-project-buffer-sources` default value

### ISSUE THREAD

**Issue by gusbrs** [minad/consult#776]
This is small technical suggestion. Currently, the user option `consult-project-buffer-sources` is initialized to `nil` and latter set to its actual default value with: 

https://github.com/minad/consult/blob/301ba70eacb8cefa67b7a310ef193f5946a3ce24/consult.el#L4599-L4602

I take it this is done to benefit from the already defined sources for `consult-buffer`. But I think there would be some improvement in defining the individual sources for `consult-project-buffer`, with something like:

```elisp
(defvar consult--source-project-buffer-project
  `(:hidden nil :narrow ?b ,@consult--source-project-buffer))
(defvar consult--source-project-recent-file-project
  `(:hidden nil :narrow ?f ,@consult--source-project-recent-file))
```
and use those to set the default value for `consult-project-buffer-sources` in the defcustom. I see two advantages in so doing. First, the default value of the variable becomes more transparent to users, particularly those who rely more heavily on the customization interface. Second, this would allow users to more easily configure individual sources for `consult-project-buffer`, e.g. by using a `plist-put` on the source, instead of having to redefine the whole `consult-project-buffer-sources`.

**Comment by minad** [comment]
Yes, the downside is that the proposed source names are ugly. Maybe one could turn it around and define consult--source-project-buffer and consult--source-project-buffer-hidden?

**Comment by gusbrs** [comment]
> Yes, the downside is that the proposed source names are ugly.

Yes, I thought the naming difficult, and the one I came up less than ideal.

> Maybe one could turn it around and define consult--source-project-buffer and consult--source-project-buffer-hidden?

I'm not sure I get it. `consult--source-project-buffer` already exists and `consult-project-buffer` has a recent files source, but not a hidden one. But probably you meant to rename the sources for `consult-buffer` and use the current names for `consult-project-buffer`, is that it? The trouble here is that, for consistency, you'll probably also want to rename the other sources for `consult-buffer`. I guess that would be the "best end result". However, even if those are internal variables, given their use is actually to populate a user option, I'd bet they are spread around a good number of init files, so you'll presumably have to live with some deprecation / aliasing, etc. for backward compatibility.

**Comment by gusbrs** [comment]
Ah, got it from the commit. Good idea. And thank you!
