### ISSUE TITLE
Bug? consult-line only show candidates if I move my cursor back to the beginning

### ISSUE THREAD

**Issue by ydzhou** [minad/consult#778]
When I start typing the keyword, consult-line does not show anything. But if I move my cursor to the beginning of my keyword, consult-line is showing up the candidates.

I am using vertico and consult only. No other search/completion plugins.

When cursor at the beginning of the keyword, here is the screenshot showing candidates
<img width="310" alt="cursor back has candidates" src="https://user-images.githubusercontent.com/3310714/228494682-0faef569-6e7a-47bb-b4a2-fd281315f289.png">

When cursor moves to the end of the keyword, or if I keep typing, no candidate shows up
<img width="326" alt="cursor end no candidate" src="https://user-images.githubusercontent.com/3310714/228494860-bf9d6e27-9719-4f2c-9ead-a1e1bd42078f.png">

My config
```
(use-package consult
  :bind (
         ("C-c M-x" . consult-mode-command)
         ("M-g r" . consult-ripgrep)
         ("M-g g" . consult-grep)
         ("M-g l" . consult-line)
         ("M-g f" . consult-find))
  
  :hook (completion-list-mode . consult-preview-at-point-mode)
    ;; The :init configuration is always executed (Not lazy)
  )

(use-package vertico
  :init
  (vertico-mode)
  (use-package savehist :init (savehist-mode)))
```

emacs version: 29.0.60

**Comment by minad** [comment]
@ydzhou You probably didn't configure your `completion-styles` properly. Please follow the steps in https://github.com/minad/consult#bug-reports. Thank you!

**Comment by ydzhou** [comment]
I think mentioninig `completion style` outside of bug reports section will help a lot. I started using consult first so missed the completion styles documentation in vertico.

I think it's a great plugin. Trying to see how we can onboard people more easily. Maybe you can have a quickstart with minimal config to show how consult, vertco and other plugin can work out of the box?

**Comment by minad** [comment]
> I think it's a great plugin. 

Thanks.

> Trying to see how we can onboard people more easily. Maybe you can have a quickstart with minimal config to show how consult, vertco and other plugin can work out of the box?

There are plenty of such configs around. Of course I could provide a minimal one which works out of the box, but there is also a time and resource constraint, in particular if people ask for support. Are you interested in supporting me via [sponsoring](https://github.com/sponsors/minad)? 

Generally there is a lot of information around for Emacs and there are starter kits if one wants to save work. But there won't be a "fast path" to Emacs. One has to dig through a lot of information. If you just copy an out box configuration, you lose the aspect of really learning Emacs. This short [guideline](https://github.com/minad/vertico#complementary-packages) is how I recommend to get started with these completion packages.

**Comment by ydzhou** [comment]
This is a good quick start!
