### ISSUE TITLE
`consult-buffer` perturbs the buffer list before selection

### ISSUE THREAD

**Issue by gnuemacscoin** [minad/consult#779]
I'm used to quickly jumping back and forth between buffers using `previous-buffer` and `next-buffer`. There's some method to the madness of reordering caused by invoking the ordinary `switch-to-buffer` (and things like `lsp-find-definition`) to bring another buffer into focus, but the new `consult-buffer` amplifies the madness by bringing every single preview into focus instead of only the final selection, thus messing up my list.

**Comment by minad** [comment]
Duplicate #354. There is a long discussion there on how this should be fixed by explicitly saving the window buffer list. Please check it out, in particular the possible workarounds. I would welcome a proper patch. Note that you can also disable preview.

**Comment by minad** [comment]
I pushed a potential fix in https://github.com/minad/consult/commit/48f7aa43788286f1413e42672c237270899a4d62. Please check.

**Comment by gnuemacscoin** [comment]
Seems to have done the trick, thanks.
