### ISSUE TITLE
tramp connections and consult-buffer

### ISSUE THREAD

**Issue by sjLambda** [minad/consult#781]
Somewhere in consult-buffer operations, buffers with dormant remote tramp  connections are waking up for authentication.  If I cannot connect to the file or the network for any number of reasons, consult-buffer does not proceed to list the buffers. I get a tramp error message and no buffer list. 

M-x iBuffer and M-x switch-to-buffer do not impose this burden. Even if the buffers have unreachable remote files, they appear in the buffer list. I can even select those buffers and continue editing or viewing them. Only when I try to save the file should it prompt for authentication. 

Is there any reason consult-buffer cannot have the same behavior? Or is my consult config lines doing something non-standard?  Here's my consult config lines:

#+begin_src emacs-lisp
(use-package consult
  :bind
  (("C-x M-:" . consult-complex-command)
   ("C-c h"   . consult-history)
   ("C-c i"   . consult-info)
   ("C-c m"   . consult-mode-command)
   ("C-x b"   . consult-buffer)
   ("C-x B"   . consult-buffer)
   ("C-x C-b" . consult-buffer)
   ("C-x 4 b" . consult-buffer-other-window)
   ("C-x 5 b" . consult-buffer-other-frame)
   ("C-x r x" . consult-register)
   ("C-x r b" . consult-bookmark)
   ("M-g g"   . consult-grep)
   ("M-g M-g" . consult-goto-line)
   ("M-g o"   . consult-outline)       ;; "M-s o" is a good alternative.
   ("M-g l"   . consult-line)          ;; "M-s l" is a good alternative.
   ("M-g m"   . consult-mark)          ;; recommend Consult navigation
   ("M-g k"   . consult-global-mark)   ;; commands under the "M-g" prefix.
   ("M-g r"   . consult-ripgrep)       ;; or consult-grep, consult-ripgrep
   ("M-g f"   . consult-find)          ;; or consult-locate
   ("M-g i"   . consult-project-imenu) ;; or consult-imenu
   ("M-y"     . consult-yank-pop)
   ([remap list-buffers] . consult-buffer)
   :map minibuffer-local-map
   ("M-s" . consult-history))
   :custom
   (consult-narrow-key "<")
   (xref-show-xrefs-function #'consult-xref)
   (xref-show-definitions-function #'consult-xref)
  :config
  (consult-preview-mode))
#+end_src

**Comment by minad** [comment]
The problem is probably the preview of recent files, with remote files among them. You can configure manual preview via `consult-preview-key` or `:preview-key` as documented in the README. See also https://github.com/minad/consult/wiki#do-not-preview-exwm-windows-or-tramp-buffers for a technique to exclude remote files. 

You can probably also use `consult-preview-excluded-files` to exclude them from preview. Personally I do not even add remote files to my list of recent files:

~~~ elisp
  (setq recentf-filename-handlers nil
        recentf-exclude
        (list "\\.\\(gz\\|xz\\|zip\\)"
              "\\.elc\\'"
              "\\.gpg\\'"
              "/COMMIT_EDITMSG\\'"
              "/\\.git/"
              "\\`/[^/|:]+:")) ;; remote
~~~

Duplicate #224

**Comment by sjLambda** [comment]
thanks, that solved the problem in many ways

**Comment by sjLambda** [comment]
Thanks to Michael Albiunus, see the change to the last line. It captures
ALL types of remote files and any future changes to the syntax:

(setq recentf-filename-handlers nil
        recentf-exclude
        (list "\\.\\(gz\\|xz\\|zip\\)"
              "\\.elc\\'"
              "\\.gpg\\'"
              "/COMMIT_EDITMSG\\'"
              "/\\.git/"
              'file-remote-p))   ;; all tramp files
