### ISSUE TITLE
consult-find: How found all files start by "common-infra" and end with ".jar"?

### ISSUE THREAD

**Issue by alexei-28** [minad/consult#784]
Emacs 27.1

package consult ver. 032

Find all files start with **common-infra**
I use command: `consult-find`
here result:

![step1](https://user-images.githubusercontent.com/303539/229631196-32ad05e4-b2c7-4851-9353-52b2181bb021.png)
![step2](https://user-images.githubusercontent.com/303539/229631227-506a7bc7-af93-4a43-a16d-572b7acaa5a6.png)

OK.

But now I want to find all files with name start by **common-infra** and end with **.jar**

I try to use this string:

#common-infra*.jar

But it not help

![step3](https://user-images.githubusercontent.com/303539/229631439-f0d0dfcb-19a2-47dd-ae18-94ec116b6b6a.png)

**Comment by minad** [comment]
The Consult search commands use regular expression syntax instead of wildcards, even for find.
