### ISSUE TITLE
Using different filtering methods for different commands?

### ISSUE THREAD

**Issue by gsingh93** [minad/consult#787]
Sorry if this issue is created on the wrong repo, I'm not sure whether this is about consult, vertico, or prescient.

Coming from `ivy`, I was able to use different filtering methods for different commands:
```elisp
  (setq ivy-re-builders-alist
        '((counsel-rg . regexp-quote)
          (swiper . regexp-quote)
          (swiper-isearch . regexp-quote)
          (t . ivy--regex-fuzzy))))
```

After switching to vertico/consult, I'm now using prescient for filtering and configuring it with this:
```elisp
(setq prescient-filter-method '(literal fuzzy)
```

How can I achieve the same behavior as with `ivy`, where I can set different filtering methods for different commands?

**Comment by minad** [comment]
Check out the vertico readme, see vertico-multiform.
