### ISSUE TITLE
Why not show recent dirs?

### ISSUE THREAD

**Issue by alexei-28** [minad/consult#788]
Emacs 27.1

package "consut" ver. 0.32

![step1](https://user-images.githubusercontent.com/303539/230793706-98408c0e-d429-4dc5-be70-cdfb523d63ba.png)

Input in folder **some_test_folder** (by press ENTER)

![step2](https://user-images.githubusercontent.com/303539/230793741-436a4dc4-07bd-47f4-9c2a-abcecbd95029.png)

`M-x consult-dir (C-x C-d)`

![step3](https://user-images.githubusercontent.com/303539/230793780-021ccc10-e18c-4166-9c78-56052d16a216.png)

Press **r**. As resul show **[Recentf dirs]**

Why not show folder  **some_test_folder** ?
![step4](https://user-images.githubusercontent.com/303539/230793843-cb7ebcab-87a5-4d66-a0bf-c284b3d5c927.png)

**Comment by minad** [comment]
You can add recent directories like this:

~~~ elisp
(add-hook 'dired-mode-hook (lambda () (recentf-add-file default-directory)))
~~~
