### ISSUE TITLE
consult--display-width error: (void-variable string-width) 

### ISSUE THREAD

**Issue by whudwl** [minad/consult#789]
After installing consult, I got the error in the subject.  

I later found out that it's because the definition of consult--display-width has the following expression
```
(setq width (+ width (compat-call string-width string pos nexti)))
 ```
And when the file gets compiled, emacs doesn't know `compact-call` is a macro and incorrectly treats it as a function.  
Not sure if this is something that can be improved in the consult package.   If not, please close.

**Comment by maxchaos** [comment]
I also encountered an issue that might be related to this. When trying to use `consult-bookmark` and `consult-line` on GNU Emacs 28.2 with consult 0.33, I get the following error:
```
consult--key-parse: [67108910] is not a valid key definition; see ‘key-valid-p’
```
where `key-valid-p` is provided by `compat`

**Comment by minad** [comment]
This is an installation issue. Reinstall Compat and Consult.
