### ISSUE TITLE
No annotation

### ISSUE THREAD

**Issue by grolongo** [minad/consult#790]
Hi minad,  

I've a custom `consult-buffer-sources` which doesn't require any annotation for its items/candidates.  
I noticed when there is no `:annotate` specified it returns the `:name` source field instead, but I find it redundant as the group title is already mentioning it.  
Is there a way I can disable it completely? I tried `:annotate nil` to no avail.  

Unrelated but your doc stipulates `:category` is a *required* source field instead of *optional*, I don't have any `:category` for my custom setting and it works just fine.

**Comment by minad** [comment]
> Is there a way I can disable it completely? I tried :annotate nil to no avail.

Try `:annotate #'ignore`.

> Unrelated but your doc stipulates :category is a required source field instead of optional, ...

The field is required if your source is supposed to play nicely with Marginalia and Embark.
