### ISSUE TITLE
Consult-(rig)grep garbled preview

### ISSUE THREAD

**Issue by baums** [minad/consult#791]
When running `consult-grep` or `consult-ripgrep` on UTF-8 files with characters outside the ASCII range, for about half the files the preview is garbled by consult displaying raw byte codes rather than proper characters. My verson of consult is 0.33 on a current Guix system. This behavior also occurs with `emacs -Q`.

Here is a sample file that is consistently garbled:
[https://raw.githubusercontent.com/sarit/SARIT-corpus/master/vatsyayana-nyayabhasya.xml](https://raw.githubusercontent.com/sarit/SARIT-corpus/master/vatsyayana-nyayabhasya.xml)
and here one that is consistently displayed correctly:
[https://raw.githubusercontent.com/sarit/SARIT-corpus/master/patanjalayogasastra.xml](https://raw.githubusercontent.com/sarit/SARIT-corpus/master/patanjalayogasastra.xml)
Put them both in the same directory and search, for instance, for the string `dharm`. The garbled display looks like this:
![bad](https://user-images.githubusercontent.com/8747982/232265700-87083f5e-dd9e-46e3-8f34-448c2393a968.png)
and the correct display like this:
![good](https://user-images.githubusercontent.com/8747982/232265706-75025d45-4ef7-4dff-8c34-907b95bffc4a.png)
Note the modeline indicator `U` in the latter, but not the former, and that the latter was correctly loaded as XML, but the former incorrectly as plain text.

After a problematic file is opened in its own buffer (which always works), future `consult-grep` or `consult-ripgrep` previews are correct for it to.

**Comment by baums** [comment]
My Emacs version is 28.2, and I use vertico for completion. The issue is similar to but not identical with #786: in my case, it is the preview buffer, but not the search results that are (for some, but not all files) garbled. I have `(set-default-coding-systems 'utf-8)` in my init.el. Setting the other variables given at the end of the discussion of #786 did not solve my issue. My `LANG` is set to `en_US.utf8`, and my `LC_ALL` is unset.

**Comment by minad** [comment]
Thanks for the report! I had observed this one before, but hadn't looked into a solution so far. The problem is different than #786. In this case the file is previewed in "raw" mode (see `consult-preview-raw-size`), which unfortunately ignored the encoding until now. I pushed a fix in 41510b59f058d24708112acf4921f4cd61ca0ad9. Please let me know if it works.

**Comment by baums** [comment]
Thank you very much! I tested in `emacs -Q`, and it works.
