### ISSUE TITLE
Is there any way 'consult--read' can retain the duplicated keys but with different values?

### ISSUE THREAD

**Issue by nqminhuit** [minad/consult#794]
Hello,

I have a source similar to this:
```
(setq mmm-source '(("config3.el" . "/bbb")
                   ("config2.el" . "/aa")
                   ("config2.el" . "/22")
                   ("config1.el" . "/bbb")))
```
And my function has consult--read like this:
```
(consult--read mmm-source
               :prompt "find file: "
               :annotate
               (lambda(cand)
                 (consult--annotate-align cand
                                          (cdr (assoc cand mmm-source)))))
```
When I run them, I get the list of suggestion like this:
```
1/3     find file:
config1.el  /bbb
config2.el  /aa
config3.el  /bbb
```
What I need is this:
```
1/4     find file:
config1.el  /bbb
config2.el  /aa
config2.el  /22
config3.el  /bbb
```
Which means the file "config2.el" should appear twice in the suggestion with different directories in the annotation.
Is there any way I can achieve that? The source data structure can be adapted.

Many thanks and great work on Consult!

**Comment by minad** [comment]
The candidate strings must be unique. You can deduplicate them by appending a suffix like (1), (2), ... The suffix can even be made invisible but I recommend that only in special scenarios. For example consult-line uses invisible suffixes.

**Comment by nqminhuit** [comment]
Could you please point me to the code, I don't have much experience with ELisp.

**Comment by minad** [comment]
I am unsure if this is helpful since I don't know what you are looking for exactly. For example the function `consult--location-candidate` adds an invisible suffix and is used by `consult--line-candidates`.

**Comment by nqminhuit** [comment]
after a few hours digging, I finally get it to work, the key function to lookup is `consult--tofu-encode index`
```
(defsubst transform-candidate_ (name index)
  (setq name (file-name-nondirectory name))
  (setq name (concat name (consult--tofu-encode index)))
  name)

(defun file-names_ (l index)
  (setq newM '())
  (while-let ((i (car l)))
    (push (cons (transform-candidate_ i index) (file-name-directory i)) newM)
    (setq l (cdr l))
    (cl-incf index))
  ;; (message "%s" newM)
  newM)


(setq mmm-source '("/bbb/config3.el" "/aa/config2.el" "/22/config2.el" "/bb/config1.el"))

(setq file-names (file-names_ mmm-source 0))

(consult--read file-names
               :prompt "find file: "
               :lookup
               (lambda (selected newM &rest _)
                 (concat
                  (cdr (assoc selected newM))
                  (substring selected 0 (- (length selected) 1))))
               :annotate
               (lambda(cand)
                 (consult--annotate-align cand
                                          (cdr (assoc cand file-names)))))
```

thank you for pointing me to the right direction.
