### ISSUE TITLE
request for consult-line-order-by-lines that starts at the point

### ISSUE THREAD

**Issue by thwh** [minad/consult#795]
I just read about `consult-line-start-from-top` [here,](https://github.com/minad/consult/issues/595#issuecomment-1162187324
) and it's related but doesn't quite do what I'm looking for:

I'd like the line candidates strictly sorted by line number in the minibuffer, while the current line remains highlighted. With `vertico-cycle` on, you get the `previous-line` behavior, but what you don't get is `beginning/end-of-buffer` being mapped to what seems intuitive to me: "go to the first match of this query at the earliest point in the buffer". Cycling in a ring seems very emacsy and I like it, but I still want that ring's order to mirror the line numbers, not the current position.

How hard would this be to implement? I might take a look if you point me in the right direction...

**Comment by minad** [comment]
This has already been discussed in #287, #440 and most recently in minad/vertico#346. There is no plan to add this.
