### ISSUE TITLE
Function cl-with-gensyms is void

### ISSUE THREAD

**Issue by kaofelix** [minad/consult#796]
Hi there!

I updated consult recently, and I'm getting the error `(void-function cl-with-gensyms)` when trying to switch buffers.

Looks like it got introduced here: https://github.com/minad/consult/commit/b22a7de62ee4adf766be2f867dee8b6980902bba

I looked up and the only info I could find about this function was this thread in Stack Exchange: https://emacs.stackexchange.com/questions/14031/name-of-emacs-lisp-library-that-provides-with-gensyms-classic-macro

This leads me to believe the function is not available in any libraries, so maybe it's missing being included somewhere alongside the code for consult?

Edit for more info:
I'm using Emacs 28.2, that might be the reason. I found the [Emacs Wiki](https://www.emacswiki.org/emacs/macro-utils.el) page that contains the macros and it mentions that Emacs 29 plus should include the macros builtin.

**Comment by minad** [comment]
Duplicate #742

**Comment by oantolin** [comment]
This problem with straight is getting annoying.

**Comment by minad** [comment]
Indeed.
