### ISSUE TITLE
consult-ripgrep: Cannot forward-word when point is immediately after "#"

### ISSUE THREAD

**Issue by daanturo** [minad/consult#797]
Steps to reproduce:
1. `(setq consult-async-split-style 'perl)`
2. `M-x consult-ripgrep`
3. Type anything like "foo", or because of initial input.
4. Move back to between "#" and "foo" (no need when initial input) so it looks like this:
```
Ripgrep (...): #|foo
```
5. `M-f` (`forward-word`)

Observed: the cursor doesn't move.

Expected: the cursor moves to the end of "foo".

**Comment by minad** [comment]
Fixed by https://github.com/minad/consult/commit/625edc0274674da64af7c1a4fd5988fece7933b5

**Comment by daanturo** [comment]
> Fixed by [625edc0](https://github.com/minad/consult/commit/625edc0274674da64af7c1a4fd5988fece7933b5)

Thank you.
