### ISSUE TITLE
Feature Request: consult-org-refile

### ISSUE THREAD

**Issue by rickalex21** [minad/consult#800]
Thanks for all the hard work. I noticed you had a brief conversation with
@Luis-Henriquez-Perez about org-refile in Command wishlist #6 . A function consult-org-refile would be nice. I created `consult-org-refile` with some functions but it does need some tweaking.

**Preview**

I could not figure out how to preview the refile headings with `state`. I think it has
something to do with `consult--location-state`.

**Kill Buffers**

Handel `C-g` and kill opened buffers after org-refile. I have a hacky function for this
which is an advice on org-refile but I'm sure there's probably a better option.

**Let**

What's funny is that I can set the `org-refile-target-verify-function` from
my/org-refile but not the org-refile-targets. I think it has something to do with lexical
binding but I don't think it matters since this can be done with `setq-local`.
I need to look more into this.

I think the verify `org-refile-target-verify-function` function is irrelevant because
we are providing rfloc to org-refile.

**Hook**

I am not sure about using a hook since we can accomplish most things with arguments
to `consult-org-refile` or `setq-local`.

**Performance**

I used `consult--with-increased-gc`, not sure if it helps but `org-refile-get-targets`
does take a while depending on the number of files. It needs some performance tweaking.

Probably clear the cache with `org-refile-cache-clear` before calling consult-org-refile?

**Warning**

When testing this warning came up once, it's gone now. I think this is a problem in
my config since I fixed a similar issue recently.

```text
Warning (org-element-cache): org-element--cache: Added org-data parent to non-headline element

```

I'm thinking about changing the consult-org-refile prompt to `Refile New Heading:` when
a heading will become top level, see `TOPLEVEL_HEADING` in the code.

```lisp
;; Prob don't need
(defvar consult-org-refile-hook nil
"This hook is called with the argument of `org-refile-targets'. It should return
the modified version for use with possible refile locations.")

(defun consult-org-refile (&optional ort preview confirm)
"ORT are the locations provided by `org-refile-get-targets'. See `org-refile' for more info.

PREVIEW is a boolean, when non-nil show the refile location.

CONFIRM is a boolean, when non-nill it will confirm before refiling."
(interactive)
(let* ((targets (or ort (consult--with-increased-gc (org-refile-get-targets)) )) 
       (selection (consult--read
                    targets
                    ;; Prob don't need.
                    ;;(run-hook-with-args 'consult-org-refile-hook targets)
                    :prompt "Refile to: "
                    :require-match t
                    ;;:state (consult--location-state )
                    :sort nil))
      (rfloc (nth 0
               (delq nil (mapcar
                           (lambda (x) (when (string= (car x) selection) x)) targets)))))
  (if confirm (when (yes-or-no-p (format "Refile to %s?" (nth 0 rfloc)))
                  (org-refile nil nil rfloc)) 
            (org-refile nil nil rfloc))))

;; Example
(defun my/call-consult-org-refile ()
"Example usage for consult-org-refile"
(interactive)
;; I think the verify function is irrelevant because we are providing rfloc to org-refile.
  (setq-local org-refile-targets '(("~/Documents/org/gtd/next.org" :maxlevel .  5)
                                   ("~/Documents/org/gtd/someday.org" :maxlevel .  5)
                                   ("~/Documents/org/gtd/projects.org" :maxlevel .  5))
              ;; pending
              org-refile-target-verify-function (lambda ()
                                                  ;;(string= (org-entry-get nil "ITEM") "Something" )
                                                  nil
                                                  ))
    (consult-org-refile nil t t ))

(cl-defun my/org-refile (&key ort (preview t) (confirm t))
"Wrapper for consult-org-refile. Uses `my/gtd-set-rfloc' to set RFLOC."
(interactive)
;; Would like to set the refile targets from here with a pcase.
(org-refile-cache-clear)
(let ((org-refile-use-outline-path 'file)
       (org-refile-target-verify-function (lambda ()
                                            (when (org-get-previous-line-level)
                                              (> (org-get-previous-line-level) 0)))))
  (consult-org-refile (my/gtd-set-rfloc (consult--with-increased-gc (org-refile-get-targets)))  preview confirm)))

;; More complex Example: Set RFLOC change my/gtd-files to org-agenda-files to try it.
(defun my/gtd-set-rfloc (&optional cor-hook-args)
"Set refile targets for gtd.

When used with a hook, the COR-HOOK-ARGS should be the output of (org-refile-get-targets)

This function is only useful when all the files have the same headings. In other
cases use `consult-org-refile' or `org-refile'.

Note that the current file is not included.

For example in someday.org

* Personal
** Chores
*** Wash the Car
I need to wash the car and clean the trunk well.

Would bring refile targets, like this. Assuming you have ** Chores in the other files.

next.org/Personal/Chores
projects.org/Personal/Chores

CASES

subheading exists         ⇒ refile in the parent.
subheading does not exist ⇒ normal refile based on org-refile-targets
h1 exists                 ⇒ normal refile based on org-refile-targets
h1 does not exist         ⇒ normal refile based on org-refile-targets
"
;; TODO: Not sure how I'm going to handle inbox.org. Refile at the top, org-reverse-note-order don't work.
(setq-local org-refile-targets
                 (mapcar #'(lambda(filename)
                             (cons filename (cons :maxlevel 6))) my/gtd-files)) 

(let* ((cbuf (file-name-nondirectory (buffer-file-name)))
       (ofiles (delq nil (mapcar ; other gtd files only, don't refile in the current file.
                          (lambda (file)
                            (unless (string= (file-name-nondirectory file) cbuf) file)) my/gtd-files)))
       ;;Don't need use setq-local org-refile-targets
       ;;(rfloc (mapcar (lambda (f)  `(,(file-name-nondirectory f) ,f nil nil)) ofiles)) ⇒("someday.org" "~/gtd/someday.org" nil nil)...
       (query (mapcar
               (lambda (x) (format "%s%s" (file-name-nondirectory x)
                 ;; Get to parent, if heading does not exist or is a level 1 refile as h1 in other files.
                 (condition-case err
                     (let ((parent (concat "/" (mapconcat 'identity (org-get-outline-path) "/")))
                           (h1 (concat "/" (mapconcat 'identity (org-get-outline-path 1) "/"))))
                            
                       ;; normal refile based on org-refile-targets
                       (if (string= parent "/") "TOPLEVEL_HEADING"
                                                 ;; Assume subheading
                                                 parent))
                   (error
                     (when (string-prefix-p "Before first headline" (error-message-string err))
                           (display-warning 'user-error (format "You need to be in a heading to refile."))))))) ofiles))
     (orf (or cor-hook-args (org-refile-get-targets)))
     (results '())) 

    ;; Don't do anything for level 1 headings normal refile based on org-refile-targets
     (unless (string-match-p "TOPLEVEL_HEADING$" (nth 0 query))
        (dolist (q query)
            (dolist ( el orf)
              (when (string= q (nth 0 el)) (push el results)))))
     (when results results)))

;;(add-hook 'consult-org-refile-hook #'my/gtd-set-rfloc)
;;(remove-hook 'consult-org-refile-hook #'my/gtd-set-rfloc)

(provide 'consult-org-refile)

```

Any input is appreciated, thanks.

**Comment by minad** [comment]
Hi, we did not add `consult-org-refile` to Consult since it is overly specific to Org. My hope is that you could reuse `consult-org-heading` with a specific MATCH argument. Then instead of jumping to the selected heading, the headline could be used for refiling. Previewing could still work though. A similar approach is taken for `consult-org-clock`, see https://github.com/minad/consult/wiki#org-clock. I hope this helps!

**Comment by rickalex21** [comment]
I think I'm going about this the wrong way. My elisp knowledge is not very advanced.

>a specific SCOPE argument

I don't understand how you managed to pass `or` to scope `(or scope (thread-last org-clock-history` in the consult-clock-in. Scope should be a symbol (e.g., agenda, file etc..).
The function org-map-entries has a `cond` that checks this unless I'm missing something here.

> the headline could be used for refiling

That's the part I don't understand, as far as I know commenting out `:state (consult--jump-state)` in consult-org-heading allows me to get a marker back and do something
with that. That's probably not the best approach, or is it?

Then the other issue is filtering the headlines, I tried `org-agenda-skip-function`since
consult-org-heading does now allow `SKIP`. However consult--org--headings does.

This is what I came up with in my attempt to use consult-org-heading. Assuming
that in consult-org-heading `:state (consult--jump-state)` is commented out. The function org-agenda-skip-function does not work in this function. I'm sure there's a better way to do this.

```lisp
(defun my-org-refile ()
"Needs work"
  (interactive)
 (let* ((org-agenda-files my/gtd-files)
       (m (my/consult-org-heading t 'agenda )))
       (with-current-buffer (marker-buffer m)
    (let ((bufname (buffer-name))
          (filename (buffer-file-name))
          (hl (progn (goto-char m)(org-entry-get nil "ITEM"))))
          
      (setq-local org-agenda-skip-function (lambda () t))
      (org-refile nil nil (list hl filename nil m))
        ;;(save-buffer)
      ))))

```

**Comment by minad** [comment]
It seems you got the general idea right. You can use `:state
(consult--jump-preview)`. This way the buffer will be previewed but you
will still get a marker (buffer and position) as return value for
refiling. I don't know how the org-agenda-skip-function and the
org-refile function work precisely.

**Comment by rickalex21** [comment]
Do I have to copy the entire `consult-org-heading` only to change the state to
`:state (consult--jump-preview)` ?

I have it working now, the problem now is I'm not sure where the filtering is done.
I don't think I can use `org-refile-target-verify-function` because consult-org-heading
is using the agenda files not the org-refile-targets. The `org-agenda-skip-function`
would be irrelevant here since we are dealing with org-refile.

I think the filtering would need to be done in consult-org-heading which is
pretty much the same thing that did in consult-org-refile.

Can I pass a custom scope to consult-org-heading that would list only
files and heading based on a filter? I can pass the symbol `'agenda` and
pass custom agenda files with let but I would like to filter which headings get shown.

In other words, I want to show only certain headings from certain files as a
refile target location in consult-org-heading.

```lisp
(defun my-org-refile ()
"Needs work"
(interactive)
 (let* ((org-agenda-files my/gtd-files)
       (org-refile-target-verify-function (lambda () t ))
       (marker (my/consult-org-heading t 'agenda )))

 ;; Irrelveant - consult-org-heading deals with agenda files not targets.
 (setq org-refile-target-verify-function
    (lambda () (let ((heading (nth 4 (org-heading-components))))
      (string-match-p "^Tasks$" heading))))

        ;;(save-buffer)
                    ;; RFLOC
(org-refile nil nil (list
               ;; Name
               (org-with-point-at marker (nth 4 (org-heading-components)))
               ;; File
               (buffer-file-name (marker-buffer marker))
               nil
               ;; Pos
               marker))))
```

**Comment by minad** [comment]
> Do I have to copy the entire consult-org-heading only to change the state to
:state (consult--jump-preview) ?

No, you can use `consult-customize` or modify `consult--customize-alist`. Take a look at the README for examples.

> In other words, I want to show only certain headings from certain files as a
refile target location in consult-org-heading.

According to the docstring of `org-map-entries` the SCOPE argument can be a function which does arbitrary filtering.

**Comment by rickalex21** [comment]
In order to use `consult-customize` I would be overriding the the way consult-org-heading
works globally unless I call it again later to set it back to normal. Even if I went that route, The filtering of headings is in the first argument to consult--read. I don't
see a way to use `consult-org-heading` other than directly calling `consult--read`
directly from my function. The function consult-org--headings is the one with the access to org-map-entries.

>According to the docstring of org-map-entries the SCOPE argument can be a function which does arbitrary filtering.

Yes you are correct, something like mapcar which returns a list of files.

 I don't see how I can use org-consult-heading for my needs. Scope would only be a list
 of files the real power is in the manipulation of org-map-entries which is the first
 argument to consult--read.

I created another function that can do this. Here `headings` is the result of calling
`org-map-entries` on multiple files with multiple buffers using cl-loop with consult--with-increased-gc.

```lisp
(consult--read
                      ;; You're Not going to need it: provide a filtering function (or func headings)
                      headings
                      :prompt "Select headline: "
                      :category 'consult-org-heading
                      :require-match t
                      :narrow (consult-org--narrow)
                      :state (when preview (consult--jump-preview))
                      :lookup  (lambda (cand props _ _ ) (car (-keep (lambda (x)
                                                (let ((hl (substring-no-properties (nth 0 x)))
                                                      (m (nth 1 x)) )
                                                (when (string= hl cand) m))) props)))
                      :sort nil)
```

**Comment by lyndhurst** [comment]
Hi @rickalex21 , I am sorry to dig up an old issue. I have recently switched to Doom Emacs, and my `elisp` is still very shaky. I started wriing functions lately (some with help I have to confess), but I am still far from what I am reading here.

I found this thread looking to do exactly what you were trying here. When I read the `Info` about `org-refile` in Doom I saw an argument `RFLOC` supposed to let the user provide a custom way to locate the refile node target. I was hoping it would be as easy as passing `consult-org-agenda` as an argument, but I see it is much harder.

Before I file this task in my ever growing pile of `LATER` org mode related improvments, I thought I would ask if you suceeded in your attempt, and if you would consider sharing your code if you did.

Thanks for your time.

**Comment by rickalex21** [comment]
@lyndhurst  I would try to keep it simple and use with a hydra or plain `org-refile`. I think I over engineered this and now
it needs major refactoring and work.

>I have recently switched to Doom Emacs

org-refile should work the same on doom.

I recommend that you look at what josh did here so you can understand how rfloc or refile works.
You can customize the code to suit your needs. I know it's a hydra but it gives you an idea
of how org-refile works.

https://gist.github.com/mm--/60e0790bcbf8447160cc87a66dc949ab

This may help as well: https://emacs.stackexchange.com/questions/8045/org-refile-to-a-known-fixed-location

**Comment by lyndhurst** [comment]
Thank you @rickalex21 for taking the time to share your experience and some links for me to learn more about the topic.

As a new Emacs user, I am definitely going to leave it for later as it seems to be much harder than simply changing an org node 'picker' for another. I will keep cutting and pasting for now :) Thanks again.
