### ISSUE TITLE
Grep regexps do not pass through word boundary characters

### ISSUE THREAD

**Issue by jwiegley** [minad/consult#801]
If I run `consult-grep` and then use `#\<foo\>`, it finds nothing, even though the whole word `foo` occurs in my file-tree. Neither is `\b` passed down, or even `\\b`. How is one supposed to grep only for whole words?

**Comment by minad** [comment]
That's odd. When I run `consult-ripgrep` or `consult-grep` and enter `#\<foo\>`, then the regexp `\bfoo\b` is passed to grep or rg, such that word boundaries are respected. The command line can be inspected in the hidden log buffer ` *consult-async*`. Do you also see such a line in ` *consult-async*`?

~~~
consult--async-process started ("rg" "--null" "--line-buffered" "--color=never" "--max-columns=1000" "--path-separator" "/" "--smart-case" "--no-heading" "--with-filename" "--line-number" "--search-zip" "-e" "\\bfoo\\b" ".")
~~~

**Comment by hmelman** [comment]
Can confirm `consult-ripgrep` with `\bapp\b` works for me find occurences of `app` and not `append`.  

Note that in ripgrep `\b` is a *word boundary* not a *non-word character* so `\bfoo!\b` won't match " foo! " because `!` isn't a word constituent character so the second `\b` isn't a a word boundary.

**Comment by jwiegley** [comment]
I'm closing this issue, and will debug on my side to find out better what is going on. I'll report back here with my findings, in case searching brings others to this issue in future.

**Comment by jwiegley** [comment]
@minad It works with grep and ripgrep, just not with git-grep:
```
consult--async-process started ("git" "--no-pager" "grep" "--null" "--color=never" "--ignore-case" "--extended-regexp" "--line-number" "-I" "-e" "low\\b" ".")
consult--async-process sentinel: event=exited abnormally with code 1 lines=0
```

**Comment by minad** [comment]
@jwiegley I don't see this. Consult also passes "\\blow\\b" to git grep. The command line processing of consult-grep, consult-ripgrep and consult-git-grep is also mostly identical. What did you try exactly?

**Comment by hmelman** [comment]
I see issues with consult-git-grep "\bapp\b" using git 2.40.0 on macOS 12.6.5.

I'm guessing it has to do with this: https://stackoverflow.com/questions/7607879/git-grep-and-word-boundaries-on-mac-os-x-and-bsd

**Comment by minad** [comment]
@hmelman Any possibility to work around this issue?

**Comment by hmelman** [comment]
Not sure.  Use latest git, add -P to the args?
