### ISSUE TITLE
consult--key-parse: [134217774] is not a valid key definition; see ‘key-valid-p’

### ISSUE THREAD

**Issue by 99702** [minad/consult#802]
Hello, I found bug when running consult command when i run 

(evil-define-key nil 'global (kbd "<leader>wb") 'switch-to-buffer)

Here is debugger for this.
Debugger entered--entering a function:
* consult--key-parse("<")
  consult--narrow-setup(((32 . "Hidden Buffer") (42 . "Modified Buffer") (98 . "Buffer") (102 . "File") (109 . "Bookmark") (112 . "Project")) (keymap))
  consult--setup-keymap(nil nil ((32 . "Hidden Buffer") (42 . "Modified Buffer") (98 . "Buffer") (102 . "File") (109 . "Bookmark") (112 . "Project")) (:predicate #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_173> :keys (any [134217774])))
  consult--minibuffer-setup-hook()
  #<subr completing-read-default>("Switch to: " #f(compiled-function (str pred action) #<bytecode -0x17dda6ddc03f8257>) #f(compiled-function (&rest args2) #<bytecode -0xad549bb4561abff>) confirm-after-completion nil consult--buffer-history nil nil)
  apply((#<subr completing-read-default> "Switch to: " #f(compiled-function (str pred action) #<bytecode -0x17dda6ddc03f8257>) #f(compiled-function (&rest args2) #<bytecode -0xad549bb4561abff>) confirm-after-completion nil consult--buffer-history nil nil))
  vertico--advice(#<subr completing-read-default> "Switch to: " #f(compiled-function (str pred action) #<bytecode -0x17dda6ddc03f8257>) #f(compiled-function (&rest args2) #<bytecode -0xad549bb4561abff>) confirm-after-completion nil consult--buffer-history nil nil)
  apply(vertico--advice #<subr completing-read-default> ("Switch to: " #f(compiled-function (str pred action) #<bytecode -0x17dda6ddc03f8257>) #f(compiled-function (&rest args2) #<bytecode -0xad549bb4561abff>) confirm-after-completion nil consult--buffer-history nil nil))
  completing-read-default("Switch to: " #f(compiled-function (str pred action) #<bytecode -0x17dda6ddc03f8257>) #f(compiled-function (&rest args2) #<bytecode -0xad549bb4561abff>) confirm-after-completion nil consult--buffer-history nil nil)
  completing-read("Switch to: " #f(compiled-function (str pred action) #<bytecode -0x17dda6ddc03f8257>) #f(compiled-function (&rest args2) #<bytecode -0xad549bb4561abff>) confirm-after-completion nil consult--buffer-history nil nil)
  #f(compiled-function () #<bytecode -0x197e14df2fa1c019>)()
  consult--with-preview-1((:predicate #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_173> :keys (any [134217774])) #f(compiled-function (action arg0) #<bytecode -0x17b377f9ad589b9b>) #f(compiled-function (narrow input cand) #<bytecode -0x1849ac57b6ce0e46>) #f(compiled-function (&rest args2) #<bytecode -0x14ac119980e48bff>) #f(compiled-function () #<bytecode -0x197e14df2fa1c019>))
  consult--read-1((#(" *Minibuf-1*�����" 0 12 (face consult-buffer multi-category ...) 12 13 (invisible t consult-strip t)) #(" *Minibuf-0*�����" 0 12 (face consult-buffer multi-category ...) 12 13 (invisible t consult-strip t)) #(" *Echo Area 0*�����" 0 14 (face consult-buffer multi-category ...) 14 15 (invisible t consult-strip t)) #(" *Echo Area 1*�����" 0 14 (face consult-buffer multi-category ...) 14 15 (invisible t consult-strip t)) #(" *code-converting-work*�����" 0 23 (face consult-buffer multi-category ...) 23 24 (invisible t consult-strip t)) #(" *string-pixel-width*�����" 0 21 (face consult-buffer multi-category ...) 21 22 (invisible t consult-strip t)) #(" *code-conversion-work*�����" 0 23 (face consult-buffer multi-category ...) 23 24 (invisible t consult-strip t)) #(" *which-key*�����" 0 12 (face consult-buffer multi-category ...) 12 13 (invisible t consult-strip t)) #("*scratch*�����" 0 9 (face consult-buffer multi-category ...) 9 10 (invisible t consult-strip t)) #("*Async-native-compile-log*..." 0 26 (face consult-buffer multi-category ...) 26 27 (invisible t consult-strip t)) #("*Warnings*�����" 0 10 (face consult-buffer multi-category ...) 10 11 (invisible t consult-strip t)) #("*Messages*�����" 0 10 (face consult-buffer multi-category ...) 10 11 (invisible t consult-strip t)) #("*dashboard*�����" 0 11 (face consult-buffer multi-category ...) 11 12 (invisible t consult-strip t)) #("~/.emacs.d/bookmarks�����" 0 20 (face consult-file multi-category ...) 20 21 (invisible t consult-strip t)) #("~/.emacs.d/elpa-28/tree-si..." 0 81 (face consult-file multi-category ...) 81 82 (invisible t consult-strip t)) #("~/.emacs.d/custom.el�����" 0 20 (face consult-file multi-category ...) 20 21 (invisible t consult-strip t)) #("~/.emacs.d/packages/tree-s..." 0 39 (face consult-file multi-category ...) 39 40 (invisible t consult-strip t)) #("~/Code/acquiring-module/fo..." 0 79 (face consult-file multi-category ...) 79 80 (invisible t consult-strip t)) #("~/.emacs.d/packages/vertic..." 0 43 (face consult-file multi-category ...) 43 44 (invisible t consult-strip t)) #("~/.emacs.d/init.el�����" 0 18 (face consult-file multi-category ...) 18 19 (invisible t consult-strip t)) #("~/.emacs.d/packages/eglot/..." 0 33 (face consult-file multi-category ...) 33 34 (invisible t consult-strip t)) #("~/Code/acquiring-module/fo..." 0 198 (face consult-file multi-category ...) 198 199 (invisible t consult-strip t)) #("~/Code/assignment/Main.jav..." 0 27 (face consult-file multi-category ...) 27 28 (invisible t consult-strip t)) #("~/Code/merchant/merchant-w..." 0 64 (face consult-file multi-category ...) 64 65 (invisible t consult-strip t)) #("~/Code/a.js�����" 0 11 (face consult-file multi-category ...) 11 12 (invisible t consult-strip t)) #("~/.emacs.d/packages/UI/ini..." 0 30 (face consult-file multi-category ...) 30 31 (invisible t consult-strip t)) ...) :require-match confirm-after-completion :prompt "Switch to: " :history consult--buffer-history :sort nil :category multi-category :predicate #f(compiled-function (&rest args2) #<bytecode -0xad549bb4561abff>) :annotate #f(compiled-function (&rest args2) #<bytecode -0xad549bb456aebff>) :group #f(compiled-function (&rest args2) #<bytecode -0xad549bb45272bff>) :lookup #f(compiled-function (&rest args2) #<bytecode -0xad549bb45406bff>) :preview-key (:predicate #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_173> :keys (any [134217774])) :narrow ((32 . "Hidden Buffer") (42 . "Modified Buffer") (98 . "Buffer") (102 . "File") (109 . "Bookmark") (112 . "Project")) :state #f(compiled-function (action arg0) #<bytecode -0x17b377f9ad589b9b>) :prompt ...)
  consult--read((#(" *Minibuf-1*�����" 0 12 (face consult-buffer multi-category ...) 12 13 (invisible t consult-strip t)) #(" *Minibuf-0*�����" 0 12 (face consult-buffer multi-category ...) 12 13 (invisible t consult-strip t)) #(" *Echo Area 0*�����" 0 14 (face consult-buffer multi-category ...) 14 15 (invisible t consult-strip t)) #(" *Echo Area 1*�����" 0 14 (face consult-buffer multi-category ...) 14 15 (invisible t consult-strip t)) #(" *code-converting-work*�����" 0 23 (face consult-buffer multi-category ...) 23 24 (invisible t consult-strip t)) #(" *string-pixel-width*�����" 0 21 (face consult-buffer multi-category ...) 21 22 (invisible t consult-strip t)) #(" *code-conversion-work*�����" 0 23 (face consult-buffer multi-category ...) 23 24 (invisible t consult-strip t)) #(" *which-key*�����" 0 12 (face consult-buffer multi-category ...) 12 13 (invisible t consult-strip t)) #("*scratch*�����" 0 9 (face consult-buffer multi-category ...) 9 10 (invisible t consult-strip t)) #("*Async-native-compile-log*..." 0 26 (face consult-buffer multi-category ...) 26 27 (invisible t consult-strip t)) #("*Warnings*�����" 0 10 (face consult-buffer multi-category ...) 10 11 (invisible t consult-strip t)) #("*Messages*�����" 0 10 (face consult-buffer multi-category ...) 10 11 (invisible t consult-strip t)) #("*dashboard*�����" 0 11 (face consult-buffer multi-category ...) 11 12 (invisible t consult-strip t)) #("~/.emacs.d/bookmarks�����" 0 20 (face consult-file multi-category ...) 20 21 (invisible t consult-strip t)) #("~/.emacs.d/elpa-28/tree-si..." 0 81 (face consult-file multi-category ...) 81 82 (invisible t consult-strip t)) #("~/.emacs.d/custom.el�����" 0 20 (face consult-file multi-category ...) 20 21 (invisible t consult-strip t)) #("~/.emacs.d/packages/tree-s..." 0 39 (face consult-file multi-category ...) 39 40 (invisible t consult-strip t)) #("~/Code/acquiring-module/fo..." 0 79 (face consult-file multi-category ...) 79 80 (invisible t consult-strip t)) #("~/.emacs.d/packages/vertic..." 0 43 (face consult-file multi-category ...) 43 44 (invisible t consult-strip t)) #("~/.emacs.d/init.el�����" 0 18 (face consult-file multi-category ...) 18 19 (invisible t consult-strip t)) #("~/.emacs.d/packages/eglot/..." 0 33 (face consult-file multi-category ...) 33 34 (invisible t consult-strip t)) #("~/Code/acquiring-module/fo..." 0 198 (face consult-file multi-category ...) 198 199 (invisible t consult-strip t)) #("~/Code/assignment/Main.jav..." 0 27 (face consult-file multi-category ...) 27 28 (invisible t consult-strip t)) #("~/Code/merchant/merchant-w..." 0 64 (face consult-file multi-category ...) 64 65 (invisible t consult-strip t)) #("~/Code/a.js�����" 0 11 (face consult-file multi-category ...) 11 12 (invisible t consult-strip t)) #("~/.emacs.d/packages/UI/ini..." 0 30 (face consult-file multi-category ...) 30 31 (invisible t consult-strip t)) ...) :require-match confirm-after-completion :prompt "Switch to: " :history consult--buffer-history :sort nil :category multi-category :predicate #f(compiled-function (&rest args2) #<bytecode -0xad549bb4561abff>) :annotate #f(compiled-function (&rest args2) #<bytecode -0xad549bb456aebff>) :group #f(compiled-function (&rest args2) #<bytecode -0xad549bb45272bff>) :lookup #f(compiled-function (&rest args2) #<bytecode -0xad549bb45406bff>) :preview-key (:predicate #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_173> :keys (any [134217774])) :narrow ((32 . "Hidden Buffer") (42 . "Modified Buffer") (98 . "Buffer") (102 . "File") (109 . "Bookmark") (112 . "Project")) :state #f(compiled-function (action arg0) #<bytecode -0x17b377f9ad589b9b>))
  consult--multi((consult--source-hidden-buffer consult--source-modified-buffer consult--source-buffer consult--source-recent-file consult--source-file-register consult--source-bookmark consult--source-project-buffer-hidden consult--source-project-recent-file-hidden) :require-match confirm-after-completion :prompt "Switch to: " :history consult--buffer-history :sort nil)
  consult-buffer()
  funcall-interactively(consult-buffer)
  command-execute(consult-buffer)

I'm running 
Emacs : GNU Emacs 30.0.50
OS : fedora 38

**Comment by minad** [comment]
Duplicate #747

**Comment by minad** [comment]
@manuel-uberti I guess some remapping is active? You are right of course about trying emacs -Q, but more importantly [old issues should be checked first](https://github.com/minad/consult#bug-reports).

**Comment by 99702** [comment]
Hello yes , i think it was solved. It was because of my old config which didn't worked on new config of consult. After adding new example configuration it ran perfectly.
