### ISSUE TITLE
Please add changes regarding case-fold-search to the changelog

### ISSUE THREAD

**Issue by nbarrientos** [minad/consult#804]
Hi,

I use some custom consult buffer sources, with `:items` using `:include` to narrow down buffers. After upgrading `consult` from MELPA today I noticed (`20230513.1232`) that my custom buffer finders had stopped working. After some debugging I realised that the regexp matching was not case insensitive anymore, which led me to commit https://github.com/minad/consult/commit/511d8c0b072a660009fcba1f461dba9e21bc0cf0. Would it be possible to add this to the CHANGELOG so others in the same situation could potentially save time debugging similar issues?

Thanks.

**Comment by minad** [comment]
Thanks. I updated the changelog.
