### ISSUE TITLE
Disable "org-mode" on preview

### ISSUE THREAD

**Issue by thdox** [minad/consult#807]
Hello,

I checked in past issues, but I was not able to find something related to my issue.

I am using Emacs 28.2 on Windows and Linux. On Linux, the below issue does not occurs. Only on Windows, as there is a know fact that org-mode is very long to initiate.

Scenario to reproduce
- Emacs 28.2 on Windows
- Use consult-recent-file or find-file
- when the cursor is on an "org-mode" file, my emacs is frozen for at least five seconds
- my understanding is that the live-preview tries to load the org-mode file, and by that load the "org-mode" library, and that is frozing emacs

Workaround so far
- I excluded the org-mode files by customizing consult-preview-excluded-files
- this exclude the org mode file of preview

Ideal expected customization 
- I would like that I can still preview the content of the file, that the .org file is treated as a .txt file

Is that something possible ? Out of the box in consult ? Or as a dirty workaround ?

**Comment by oantolin** [comment]
It only happens once per Emacs session, so it's not that bad, is it?

Also, this is how I *load* org in a fresh Emacs session, so https://xkcd.com/1172 applies. 😛

**Comment by minad** [comment]
In Emacs 29 there exists a new variable major-mode-remap-alist. One could bind that variable in consult-preview-variables and remap org-mode to text-mode. I haven't tried this yet.

**Comment by minad** [comment]
~~~ elisp
(add-to-list 'consult-preview-variables
             '(major-mode-remap-alist . ((org-mode . text-mode))))
~~~

**Comment by thdox** [comment]
@minad you are my hero ! Thank you very much.
