### ISSUE TITLE
Add version numbers or last edit date&time in files.

### ISSUE THREAD

**Issue by veronikazaglotova** [minad/consult#81]
What the title says. I wanted to test https://github.com/minad/consult/issues/26#issuecomment-748688481
I ran `M-x straight-pull-all`. Then when it was done, I ran consult-line and saw the old behavior (e.g. go to start of the line). I quickly opened consult.el, and saw no versioning! No need to tell you how important version numbers are.
I solved the issue, but I still think that version numbers would be a great idea.

**Comment by minad** [comment]
Where do you want to see version numbers??

**Comment by minad** [comment]
I think now I understand. You want to see some version in the file. Since the project is git-managed, so versioning is solved by git. No need to bake something on top of that :)
