### ISSUE TITLE
Wrong grep lookahead support detection on remote buffers

### ISSUE THREAD

**Issue by manzaltu** [minad/consult#811]
Consult does not correctly detect grep lookahead support on remote TRAMP buffers. This affects both grep and ripgrep consult commands.
The root cause of this issue is due to the fact that `consult—grep-lookahead-p` uses `call-process-region` which does not execute the command on the remote host when `default-directory` points to another machine.

There might be an additional issue with the detection of the supported regexp type under`consult-find`, where `call-process-shell-command` is used in a similar fashion.

The solution is to use process execution commands that do support remote buffers, such as `process-file`.

**Comment by minad** [comment]
Thanks for the report! Please check if the fix works properly.

**Comment by manzaltu** [comment]
Thank you for your quick response and fix.
Yes, I can confirm that the fix works properly.
