### ISSUE TITLE
Consult-bookmark turns off dired-hide-details-mode

### ISSUE THREAD

**Issue by pseudomyne** [minad/consult#814]
Hi. 
When I `consult-bookmark` in a dired buffer, it turns off `dired-hide-details-mode`. 
Thank you for your help and time (I'm very new to consult).

**Comment by minad** [comment]
Hi, it is not entirely clear to me how to reproduce the issue. Please follow the steps at https://github.com/minad/consult#bug-reports and provide the precise steps necessary to reproduce the problem. Thanks!

**Comment by pseudomyne** [comment]
Alas I  won't have time to do this properly. I will survive the annoyance. thanks.

**Comment by oantolin** [comment]
I think I know what @pseudomyne means. I have `dired-hide-details-mode` in my `dired-mode-hook`, but if I open a directory in dired and bookmark it, and then use either `consult-bookmark` or `consult-buffer` to preview that bookmark, the preview is the dired buffer without any decorations or prettification: the dired details are not hidden and file names are not color coded (i.e., it looks like raw `ls` output). Of course, if you select that bookmark to jump to it, you get a dired buffer with all your settings such as, in my case, `dired-hide-details-mode`.

**Comment by minad** [comment]
Yes, in order to run additional modes/functions during preview you have to use a `find-file` hook (like a globalized minor mode) and enable the hook explicitly in `consult-preview-allowed-hooks`.

**Comment by pseudomyne** [comment]
> Of course, if you select that bookmark to jump to it, you get a dired buffer with all your settings such as, in my case, dired-hide-details-mode.

@oantolin : thanks for the guess. In my case however, my dired buffer does not return to `hide-details-mode`. It still is raw and I need to `revert-buffer` it to hide details again as it was.

**Comment by oantolin** [comment]
Oh, that's interesting, @pseudomyne! If you come up with a recipe to reproduce the problem starting from `emacs -q`, I'm sure @minad will figure it out.

**Comment by ahan98** [comment]
Over a year late, but for other struggling beginners like myself, I believe this is what @minad meant by:

> Yes, in order to run additional modes/functions during preview you have to use a `find-file` hook (like a globalized minor mode) and enable the hook explicitly in `consult-preview-allowed-hooks`.

Here's a snippet that worked for me:

```elisp
;; Enable desired minor modes when previewing dired-mode buffers
(define-globalized-minor-mode global-dired-hide-details-mode
  dired-hide-details-mode (lambda ()
                            (when (derived-mode-p 'dired-mode)
                              (dired-hide-details-mode)
                              (nerd-icons-dired-mode))))

(add-hook 'find-file-hook #'global-dired-hide-details-mode)
(add-hook 'consult-preview-allowed-hooks #'global-dired-hide-details-mode)
```
