### ISSUE TITLE
Consult ripgrep not returning results, displays "match required"

### ISSUE THREAD

**Issue by fkrause98** [minad/consult#815]
Hi! First of all, thanks for this awesome package, it's really great, that being said I have the following issue.

## Issue
When trying to use consult-ripgrep, I'm faced with this:
![image](https://github.com/minad/consult/assets/56402156/f1220f83-96f0-4a15-b7a2-661241fe0ff3)

That is when I'm trying to call it with M-x.

I've also tried calling it from this function definition:
```emacs-lisp
(defun search/project-text-search nil
  (interactive) 
  (consult-ripgrep (projectile-project-root)))
```
But I get the same result.
I see this output on the *consult-async-buffer*, when trying to search for "use-package" on my config.
```
 consult--async-process started ("rg" "--null" "--line-buffered" "--color=never" "--max-columns=1000" "--path-separator" "/" "--smart-case" "--no-heading" "--with-filename" "--line-number" "--search-zip" "-P" "-e" "use-package" ".")
consult--async-process sentinel: event=finished lines=74
```
It would seem that consult does indeed get ripgrep's output?
## Setup
This are my use-package definitions for consult:
```emacs-lisp
(use-package consult
  :defines
  (consult-line
   consult-buffer
   consult-find
   consult-find-project
   consult-ripgrep
   consult-recent-file)
  :straight t
  :bind (("C-s" . consult-line)
         ("C-x b" . consult-buffer)
         ("C-x C-b" . consult-buffer)
         ("C-x C-f" . consult-find)))
(use-package consult-lsp
  :straight t
  :after (consult lsp-mode)
  :bind (:map lsp-mode-map
              ("C-c C-l" . consult-lsp-symbols)))
(use-package consult-projectile
  :straight t
  :after (:all (consult projectile)))
```

**Comment by minad** [comment]
Thanks for the report. Yes, it seems `rg` is indeed producing output. This does not seem to be the cause of the issue. Please check if other commands work properly, e.g., `consult-grep` or `consult-find`, which would then hint at a problem of `rg`. The information you provided so far is unfortunately not sufficient to debug the problem. `consult-ripgrep` and the other commands work fine in my setup and with `emacs -Q` (Emacs 28 on Linux). Please try to create a minimal recipe, see https://github.com/minad/consult#bug-reports.

**Comment by fkrause98** [comment]
Thanks for the quick response, and nice catch! Yes, it was indeed Ivy messing around somehow 😐.
I apologize for not reading the bug-report section, I'll have it in mind if I have to report an issue in the future!.
