### ISSUE TITLE
non-unicode chracter added to the end of history elements

### ISSUE THREAD

**Issue by armindarvish** [minad/consult#817]
I have been having this issue while working on [consult-gh](https://github.com/armindarvish/consult-gh/), where a non-unicode character is added to strings when the selection is saved in a history variable. I was hacking my code to clean this up, but now I realize that this is happening with `consult-buffer-history` and a bunch of other consult-something-history variables as well and here is a screenshot
<img width="922" alt="Screenshot 2023-07-06 at 8 16 09 AM" src="https://github.com/minad/consult/assets/18317557/029291f1-a5b8-4186-bba0-cbec6c811eb5">

I copied the character elsewhere and found out it is this character: � 
I am on MacOS and I tried this in a minimal config (just consult and vertico installed) and this is still happening. 

Any ideas why this is happening?

**Comment by armindarvish** [comment]
But, then how do you clean things up. For example, if I use embark to insert the text or copy, ... emacs throws errors at me because for not having the right encoding in the buffer and no matter what encoding I pick, it keeps throwing errors!

**Comment by minad** [comment]
Embark has the ability to transform candidates and remove the tofu were needed, see https://github.com/oantolin/embark/blob/master/embark-consult.el#L79-L96. If you use `consult--multi`, it should work automatically. I think your mistake is that you specify a `:category` as argument for `consult--multi`, while the category should only be specified per source. See also the doc string of `consult--multi`:

https://github.com/minad/consult/blob/fe49dedd71802ff97be7b89f1ec4bd61b98c2b13/consult.el#L2812-L2816

**Comment by armindarvish** [comment]
@minad I am coming back to fix this issue, and I am opening a new issue in my own repo to track the progress. The issue is with `consult--read`, I don't know how to pass text-properties along with candidate. I have an example script in the issue at my repo: https://github.com/armindarvish/consult-gh/issues/60

I'd appreciate it if you can take a look and let me know what is the best way to achieve this with consult--read?

**Comment by armindarvish** [comment]
with `consult--multi`, I can make sources from different repos and when I select the cnadidate, it returns the entire source including propertized text. As a result I can pass other information along with the candidate (e.g. url, owner of the repo, ...) and use it later for actions, previews, and other purposes. But with `consult-read`, I don't know how to achieve this. If I just pass a list of propertized strings, after selection the properties are not returned!

Here are some snippets to demonstrate the difference:
* using consult--multi:
```emacs-lisp
(let* ((items '(#("armindarvish/consult-gh" 0 23 (:repo "armindarvish/consult-gh" :user "armindarvish" :description "" :visible "public" :version "2023-09-03T20:18:41Z"))
                #("minad/consult" 0 13 (:repo "minad/consult" :user "minad" :description ":mag: consult.el - Consulting completing-read" :visible "public" :version "2023-09-13T09:10:12Z"))))
       (candidates (list `(:items  ,items))))
  (consult--multi candidates
                  :prompt "Select Repositories(s): "
                  :require-match t
                  :sort nil
                  :group #'consult-gh--repo-group
                  :history 'consult-gh--repos-history
                  :category 'consult-gh-repos
                  :sort t
                  :preview-key consult-gh-preview-key
                  )
  )
```
* using consult--read:
```emacs-lisp
(let* ((items '(#("armindarvish/consult-gh" 0 23 (:repo "armindarvish/consult-gh" :user "armindarvish" :description "" :visible "public" :version "2023-09-03T20:18:41Z"))
                #("minad/consult" 0 13 (:repo "minad/consult" :user "minad" :description ":mag: consult.el - Consulting completing-read" :visible "public" :version "2023-09-13T09:10:12Z")))))
  (consult--read items
                  :prompt "Select Repositories(s): "
                  :require-match t
                  :sort nil
                  :group #'consult-gh--repo-group
                  :history 'consult-gh--repos-history
                  :category 'consult-gh-repos
                  :sort t
                  :preview-key consult-gh-preview-key
                  )
  )

```

@minad, Any suggestions on how to pass other info to consult--read?
