### ISSUE TITLE
Kill currently selected buffer in consult-buffer

### ISSUE THREAD

**Issue by walseb** [minad/consult#819]
Hi!

Is there any way to kill the currently selected buffer in `consult-buffer` without leaving `consult-buffer`?

Killing it in an embark exported buffer, or previewing the selected buffer, then killing it by leaving the minibuffer in a recursive edit both have their downsides.

I'd just like a button to kill the currently selected buffer, and update the buffer list so that the killed buffer is no longer there. But I haven't been able to find such a command.

Thanks for any help!

**Comment by oantolin** [comment]
You could kill it using embark-act (instead of embark-export). The kill-buffer action is bound by default to `k`.

**Comment by minad** [comment]
Yes, as @oantolin mentioned, embark-act is the way to go.

**Comment by walseb** [comment]
Thank you!
