### ISSUE TITLE
Different `completion-styles` breaks `consult-line` preview

### ISSUE THREAD

**Issue by HardGraphite** [minad/consult#820]
Hi,

I use different `completion-styles` for minibuffer and normal buffers. In minibuffer I use `orderless`, which provides a better experience for tools like `consult`; while in normal buffers I use `flex` for programming completion.

However, this breaks the highlights in `consult-line` preview. The following screenshot is an example:
![consult-line](https://github.com/minad/consult/assets/64914256/1f9c3d8c-f17a-4250-a7b0-aa5efd71b378)
The highlights in minibuffer work as expected (`orderless`), but highlights in preview use `flex` and show a different result from that in minibuffer (correct:`"a ab abc [abcd]"` vs wrong:`"[a] a[b] ab[c] abc[d]"`).

Is there any solution?

Thanks!

**Comment by minad** [comment]
Yes, this is a known problem. The solution is to configure orderless for the consult-location category via completion-category-overrides.
