### ISSUE TITLE
grep regex style 

### ISSUE THREAD

**Issue by acbits** [minad/consult#821]
From the docs, it appears that only emacs style regex is supported at the prompt. 

Is there a way to enter PCRE style regex at the prompt and _consult_ would pass it verbatim to _grep/ripgrep_?

**Comment by oantolin** [comment]
You can achieve this by setting `consult--regexp-compiler` to a custom function. See the docstring and the default value of that variable, `consult--default-regexp-compiler`.

**Comment by minad** [comment]
It makes sense to document this in the wiki. We already have the Orderless configuration documented there: https://github.com/minad/consult/wiki#use-orderless-as-pattern-compiler-for-consult-grepripgrepfind.

**Comment by acbits** [comment]
This doesn't look like a something an end-user can easily set? I am not an expert in consult internals though I can write elisp. 

From looking at the  function `consult--default-regexp-compiler`, I need to write a function consult-verbatim-regex-compiler that returns the _input_ as it is?

**Comment by minad** [comment]
Yes, you have to write your own function.

**Comment by acbits** [comment]
I added this to my .emacs and seems to work. I can enter the PCRE at the prompt that I enter at the shell prompt. Not extensively tested, but seems OK for now. 
```
(defun consult-verbatim-regexp-compiler (input type ignore-case)
  "Returns the input regex verbatim ignoring the type"
  (setq input (consult--split-escaped input))
  (cons (mapcar (lambda (x) x) input)
        (when-let (regexps (seq-filter #'consult--valid-regexp-p input))
          (apply-partially #'consult--highlight-regexps regexps ignore-case))))

(setq consult--regexp-compiler #'consult-verbatim-regexp-compiler)
```
