### ISSUE TITLE
[Help needed] Porting ivy-point-history to consult

### ISSUE THREAD

**Issue by CsBigDataHub** [minad/consult#828]
I am very novice to emacs. I have migrated from ivy/counsel to vertico/consult.

Reference links  - 

https://github.com/blue0513/point-history
https://github.com/SuzumiyaAoba/ivy-point-history

I am having trouble migrating these two functions from `ivy-point-history` to `consult`. Can someone you help?

```

(defun ivy-point-history--action (point)
  (let* ((buffer-name (get-text-property 0 'point-history-buffer point))
	 (pos-str (get-text-property 0 'point-history-position point)))
    (if (or (null buffer-name) (null pos-str))
	(message "No point at this line.")
      (with-ivy-window
        (let ((buffer (get-buffer buffer-name))
              (pos (string-to-number pos-str)))
          (switch-to-buffer buffer-name)
          (goto-char pos))))))

;;;###autoload
(defun ivy-point-history ()
  "Ivy interface for point-history."
  (interactive)
  (ivy-read "point-history: " (ivy-point-history--list-candidates)
            :preselect (ivy-thing-at-point)
            :require-match t
            :sort nil
            :update-fn 'auto
            :action #'ivy-point-history--action
            :caller 'ivy-point-history))

```

**Comment by minad** [comment]
Hi! You should look at the source of `consult-global-mark`. I believe you can possibly reuse most of the code of it. `consult-global-mark` takes a list of markers, generates the corresponding candidates, previews the locations and finally jumps to the given locations. Maybe you can even call `consult-global-mark` with the point history list as argument. I hope this helps.

(For reference there exist other packages which provide a similar point history. I am aware of - https://github.com/alphapapa/dogears.el, https://github.com/Overdr0ne/gumshoe and https://github.com/gitrj95/trail.el. Maybe Consult integration has been considered or even documented for one of those.)
