### ISSUE TITLE
Equivalent of cousel-search for dynamic web searches

### ISSUE THREAD

**Issue by Sbozzolo** [minad/consult#829]
I could not find an equivalent for `counsel-search` (and I don't know if this would be in the scope of the package). `counsel-search` is a little known function in the ivy/counsel stack for dynamically querying a search engine (e.g., Google). You can roughly see `counsel-search` in action in this [readme](https://github.com/mnewt/counsel-web), with the difference that the web browser opens after a search query is selected and that `counsel-search` has no perceivable latency. 

Is this doable/within the scope of consult?

Thank you in advance.

**Comment by minad** [comment]
Yes, this is possible, but out of scope of Consult. You can look at some of the [auxillary packages](https://github.com/minad/consult#auxiliary-packages), which perform web requests via `url-retrieve`.

**Comment by Sbozzolo** [comment]
Thank you!

Could you please point me to a specific auxiliary package that would be a good starting point?
