### ISSUE TITLE
Wrong customization type

### ISSUE THREAD

**Issue by danielfleischer** [minad/consult#832]
I think all instances of `expression` should be `sexp`, when defining types for customizable variables, for example in https://github.com/minad/consult/blob/7e660440c1636dc28d86b4ce86e9dc20df7e64c2/consult.el#L254-L269. 

Emacs 29.1.

**Comment by oantolin** [comment]
Did the name change or has this always been wrong? And if it changed, that's pretty annoying. Maybe compat can take care of that?
