### ISSUE TITLE
[Q] preview for consult-find and consult-dir

### ISSUE THREAD

**Issue by mhlr** [minad/consult#837]
Is there a way to enable preview for consult-file and/or consult-dir? I have previews working for other functions like consult-grep, but not for consult-file and consult-dir. It would be great to see the beginning of a file when looking among similarly name files.

**Comment by minad** [comment]
For `consult-find` and `consult-fd` you can set the `:state` argument as follows:

~~~ elisp
(consult-customize consult-find consult-fd :state (consult--file-preview))
~~~

For `consult-dir` set the `:state` field to `consult--file-state` and set the `:action` field to nil, but I haven't tried this.

**Comment by wybryk-ananasa** [comment]
I found the solution:
  ```
(defun my-consult-fd()
    (interactive)
    (funcall-interactively #'consult-fd project-path selected-text))
  (global-set-key (kbd "H-f f") 'my-consult-fd)

  (consult-customize
   my-consult-fd
   :state (consult--file-preview)
   :preview-key '(:debounce 0.2 any)
   consult-dir
   :state (consult--file-state)
   :action nil)
```
