### ISSUE TITLE
Make `consult-outline` take a level argument for narrowing like `outline-cycle-buffer`

### ISSUE THREAD

**Issue by hmelman** [minad/consult#839]
I use `outline-minor-mode` for code folding, e.g., in `emacs-lisp-mode`.  This now works well with `outline-cycle-buffer` which takes a numeric argument for the level to show.  `C-u S-TAB` will show all headings up to level 4 which in lisp will show section comments but not defuns (try it in `consult.el`).

`consult-outline` works great and can narrow up to some level of headings using the narrow-key, but I'd like the UI to be the same as `outline-cycle-buffer`, so that `C-u M-g o` lets me select from the same level 1-4 headings I'd see after doing `C-u S-TAB`.  

Currently `consult-outline` doesn't use an argument, so this won't conflict with anything existing, and it seems a reasonable use for the argument (I think it's unlikely something else in the future would want to use it).  Also I'm not proposing changing how narrowing currently works, just another way to do it.

**Comment by minad** [comment]
Nice idea. Added in 0923786304d1dc51c5ae92d27a85c6d8383fbc3d.

**Comment by hmelman** [comment]
Thanks!
