### ISSUE TITLE
Show more context on consult-line

### ISSUE THREAD

**Issue by veronikazaglotova** [minad/consult#84]
Sometimes, it's hard to know the context from just the line on which the candidate is on. For example, 
![screenshot](https://user-images.githubusercontent.com/52463107/102923230-9850c200-44b9-11eb-804c-473d165c279f.png)
I don't know any of these lines is and where it will send me! Maybe we should add an option to show more lines on each candidate, so that the user can see more context?
>inb4: you already have ctrlf

Yes I use ctrlf, consult-line and avy, all for different use cases.

**Comment by minad** [comment]
We could generate candidates with multiple lines each. But this would also would look very weird in the beginning, since everything is repeated. Furthermore with selectrum it would render all the context lines as a single line. But it would work with something like embark-live-occur. Overall I am not sure if this is worth it and increases the usability. Is there a similar option for helm-swoop and swiper?

**Comment by veronikazaglotova** [comment]
IDK, probably not.
>I am not sure if this is worth it and increases the usability.

Tbh I just imagined how it would look like and realized that it's just a waste of time.

**Comment by minad** [comment]
Tbh I also thought about this before and imagined that it wouldn't look good...

**Comment by okamsn** [comment]
If you didn't already know, you can use a prefix argument with `M-x occur` (`M-s o`) to get more context. For example, `3` means to show the 3 lines before and after the match. `-3` means to show the 3 lines before the match. You can set the default with `list-matching-lines-default-context-lines`.

**Comment by oantolin** [comment]
The context lines would look great in Embark live occur with zebra striping, and I could also implement zebra striping for icomplete-vertical. But I don't think context lines are really necessary, for me that's the role of `consult-preview-mode`: providing context.

**Comment by minad** [comment]
@oantolin It would work with Embark live occur, but you would still see repeating lines at least in the beginning (which would look confusing imho), e.g. for abcd

~~~
---
a
b
c
---
b
c
d
---
~~~

Furthermore, like you, I am also happy with how things are now - context via preview!
