### ISSUE TITLE
consult-keep-lines in scrach buffer - org-element--cache warning

### ISSUE THREAD

**Issue by vondravl** [minad/consult#840]
Hi, I', not sure if it is really error in consult or org-mode, but when trying to use consult-keep-lines in scratch buffer I'm getting this warning:
`Warning (org-element-cache): org-element--cache: Org parser error in *scratch*::143. Resetting.
 The error was: (wrong-type-argument integer-or-marker-p nil)
 Backtrace:
nil
 Please report this to Org mode mailing list (M-x org-submit-bug-report).`

It happens only in scrach, in regular buffers it is ok. 

I'm using GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2023-07-31
Org mode version 9.6.6, consult-20230906.2047

**Comment by oantolin** [comment]
Is your scratch buffer in Org mode?

**Comment by vondravl** [comment]
Yes, it is. Shouldn't be?

**Comment by oantolin** [comment]
> Shouldn't be?

It's fine to have the scratch buffer in Org mode. I just asked because if it wasn't in Org mode your issue would be even more mysterious.

**Comment by minad** [comment]
@vondravl I suggest to do this:

> Please report this to Org mode mailing list (M-x org-submit-bug-report)

Maybe `consult-keep-lines` triggers a bug in Org due its modifications? As a workaround it may help to disable the cache, see `org-element-use-cache` and `org-element-cache-persistent`.

As an alternative, did you try `consult-focus-lines`? This command temporarily hides regions, which is probably preferrable in many scenarios.

**Comment by vondravl** [comment]
`consult-focus-lines`  works and fits even better for my purpose. Thank you very much for help!
