### ISSUE TITLE
Narrowing implementation

### ISSUE THREAD

**Issue by minad** [minad/consult#86]
@clemera @oantolin I would like to reconsider the narrowing implementation. As of now, narrowing is implemented using the narrow prefix but this adds clutter at different places, e.g., marginalia. I wonder if it can be avoided by using the predicate instead. Since I am already doing some magic with keymaps, I could also set a flag instead.

The following works with selectrum and icomplete right now.

~~~ elisp
(defvar filter t)

;; selectrum specific
(define-key minibuffer-local-map "\C-q" (lambda ()
                                         (interactive)
                                         (setq filter (not filter))
                                         (when (bound-and-true-p selectrum-mode)
                                           (selectrum-exhibit))
                                         ))

;; icomplete specific
(define-key minibuffer-local-completion-map "\C-q" (lambda ()
                                         (interactive)
                                         (setq filter (not filter))
                                         (setq completion-all-sorted-completions nil)
                                         ))

(consult--read "Prompt: "
               (list "axxx" "bxxx" "cxxx")
               :sort nil
               :predicate (lambda (x)
                            (or filter (string-prefix-p "a" x))))
~~~

**Comment by minad** [comment]
Not sure about this - the goal would be to avoid the narrowing prefix, such that I would not have to strip it in marginalia. But then I guess the predicate check would get more (or potentially too) expensive.

**Comment by clemera** [comment]
If the narrowing prefix could be avoided that would be nice, we also had a use case in Selectrum where we would need to know the prefix isn't part of the candidate. You could probably also adjust `minibuffer-completion-predicate` in the commands which trigger the different prefixes. Updating this variable and triggering an update of the completion UI should also work.

**Comment by minad** [comment]
@clemera Yes, I know. But it won't help with the uniqueness prefixes for consult-line. I am playing around with this proposal now and so far it goes well. 

> You could probably also adjust minibuffer-completion-predicate in the commands which trigger the different prefixes. Updating this variable and triggering an update of the completion UI should also work.

You mean, instead of introducing a variable like `filter` as is done here? Do you think that's better?

**Comment by clemera** [comment]
Sounds great, I haven't looked at it but I wanted to mention it in case you think you can make use of the predicate variable for your purposes.

**Comment by minad** [comment]
> Sounds great, I haven't looked at it but I wanted to mention it in case you think you can make use of the predicate variable for your purposes.

It is a good idea. I have not tried it yet, but I will to see if it makes things simpler. 

Unfortunately I won't manage to get rid of the prefix in the case of the virtual buffers (consult-buffer), since there I need the prefix for annotations and to disambiguate.

Another question - how would you implement the narrowing indicator now? Overlay somehow over the prompt? Is there an example somewhere for this? I think Embark also does sth like this?

**Comment by oantolin** [comment]
> Unfortunately I won't manage to get rid of the prefix in the case of the virtual buffers (consult-buffer), since there I need the prefix for annotations and to disambiguate.

Lines will still need the prefix too, right? 

> Another question - how would you implement the narrowing indicator now? Overlay somehow over the prompt? Is there an example somewhere for this? I think Embark also does sth like this?

Yes, take a look at embark--show-indicator.

**Comment by minad** [comment]
> Lines will still need the prefix too, right?

Yes, lines and consult-buffers. But we can rid of the prefix which is better for commands like #85.

**Comment by minad** [comment]
Please test :)
