### ISSUE TITLE
`:inherit-input-method` option's poor behavior

### ISSUE THREAD

**Issue by SudoerReodus** [minad/consult#861]
When you enable `:inherit-input-method` the minibuffer will inherit its input method from displayed buffer.

However, with this option enabled, you can no longer change your input method while editing inside the minibuffer. (i.e. using `C-\` (`toggle-input-method`))

This is highly undesirable, since you often want to use multiple input methods while editing inside the minibuffer.
For example to enter a mixed English-Chinese/Arabic/... text as search term.

Acceptable behavior would be if consult allowed changing the input method, even with this option enabled (But it would default to the input-method that it inherited from the parent buffer)

Optimal behavior would be if change of input-method inside consult's minibuffer also changed the current input method of the parent buffer, so that when you close the minibuffer and return to parent buffer, you have your last selected input method that you used inside the minibuffer, selected and ready to use inside the parent buffer (not sure if possible)

Thanks

**Comment by minad** [comment]
Please don't open the same issue again, see #860 and #335. Input method handling is not a Consult issue, but a general minibuffer feature.

**Comment by SudoerReodus** [comment]
It's not the same issue though ...!

**Comment by minad** [comment]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Minibuffer-Completion.html

**Comment by SudoerReodus** [comment]
Thanks and sorry for my ignorance, I reported it on Emacs' mailing list.
