### ISSUE TITLE
consult-outline: after starting emacs (sometimes) produces error message on first run

### ISSUE THREAD

**Issue by DivineDominion** [minad/consult#87]
If emacs isn't already open for a week or two, I usually start emacs and then go to an org file for tasks. To go to something I'm currently working on, I hit `M-g o` and then it fails the first time. Not 100% of the time, but  maybe the error I do get is helpful already:

    font-lock-default-fontify-region: Wrong type argument: number-or-marker-p, nil

Will investigate further and report back my findings.

**Comment by minad** [comment]
I need a stack trace, but I suspect that consult has nothing really to do with this. For some reason fontification is somehow not robust, it could very well be a bug in another package.

Consult is not doing much, this is all it does to request a buffer to be fontified:

https://github.com/minad/consult/blob/468bc94087fa064e57c436c332d433ce4c3981fc/consult.el#L310-L318

**Comment by DivineDominion** [comment]
I see! @minad I've just discovered the profiler, and didn't try debugging apart from `--debug-init` -- could you tell me what you'd need and how I can capture that?

**Comment by minad** [comment]
There is the debug-on-errror setting which will will open the debugger in the case of an error.

**Comment by minad** [comment]
@DivineDominion Please create a new issue or let me know if you manage to reproduce this bug using emacs -Q. I strongly suspect it is not due to consult, but rather an issue somewhere else.

**Comment by junyi-hou** [comment]
I have the same problem. It seems like it is because the org file contains some code block in which `font-lock` do not know how to highlight.

In my case, I have a markdown code block in my org file, and this error occurs when `markdown-mode` is not loaded.

**Comment by DivineDominion** [comment]
@junyi-hou Aha, that's an interesting trail! Thanks for sharing
