### ISSUE TITLE
Sorted `consult-line` buffer starting from current line (similarly to `swiper`)

### ISSUE THREAD

**Issue by david-alvarez-rosa** [minad/consult#871]
The configuration variable `consult-line-start-from-top` makes the `consult-line` search start from top if non-nil, but this doesn't fit my needs.

I'd like to have a sorted `consult-lie` buffer and—at the same time—start matching in the same line.  This behavior is the standard in `swiper`.

**Comment by minad** [comment]
Hi! This issue has been discussed a few times, see for example #795. Unfortunately such a sorting is not easily possible to implement given the constraints and the UI agnosticism of Consult. I know that it is not exactly the same, but I think using `vertico-cycle=t` and `consult-line-start-from-top=nil` is almost as good and hopefully sufficient. It may need some time to the get accustomed to the wrap-around however.

**Comment by david-alvarez-rosa** [comment]
Okay I see @minad. Thank you for the suggestion, that's helpful. Will give it a try!
