### ISSUE TITLE
Silencing the compiler

### ISSUE THREAD

**Issue by dr-scsi** [minad/consult#874]
Downloading and compiling the latest version with `package.el` (MELPA 20231019.1759), the compiler says:

```
consult.el:93:12: Warning: in defcustom for `consult-project-function':
  `const' with quoted value: #'consult--default-project-function
```
which is about this line:
https://github.com/minad/consult/blob/3cadc1031495661dc2c884fc307e8d59852f3b54/consult.el#L93

I think it should be:
```
(const :tag "Default project function" consult--default-project-function) 
```

Emacs lisp reference says:

> (const value)
> 
>    The value must be _value_—nothing else is allowed.

**Comment by minad** [comment]
Fuxed
