### ISSUE TITLE
Narrowing when you already entered some text in the minibuffer

### ISSUE THREAD

**Issue by oantolin** [minad/consult#88]
The one thing I don't like about the narrowing system is actually pretty easy to fix. The system is great if you know at the beginning of the line that you intend to narrow. But I often realize after typing a little that I meant to narrow, so I kill the line, do the narrowing, and yank the line again.

I think I'd prefer instead if the beginning of the line received no special treatment (so no fancy rebinding of `SPC`) and instead some command set the narrowing, something like:

```elisp
(defun consult-prompt-narrow (char)
  "Narrow to type CHAR, or widen if CHAR is RET."
  (interactive
   (list
    (read-char (concat (propertize "RET" 'face 'consult-narrow-indicator)
                       " widen "
                       (mapconcat
                        (lambda (x)
                          (concat (propertize 
                                   (single-key-description (car x))
                                   'face 'consult-narrow-indicator)
                                  " "
                                  (cdr x)))
                        consult--narrow-prefixes
                        " ")))))
  (message "CHAR %s" char)
  (consult--narrow-set (if (= char ?\C-m) nil char)))
```

That still needs to refresh the completion system, but you get the idea.

_Originally posted by @oantolin in https://github.com/minad/consult/issues/85#issuecomment-750401687_

**Comment by minad** [comment]
Yeah, fastest close after 30s :)

**Comment by oantolin** [comment]
Sorry! I didn't realize this was already in consult.

**Comment by minad** [comment]
No worries, the readme is a bit of a mess.
