### ISSUE TITLE
Make vertico-directory-tidy (rfn-eshadow) work with consult-find

### ISSUE THREAD

**Issue by KindlyRepeat** [minad/consult#883]
Hi,

The function `vertico-directory-tidy` does not work when `consult-find` is prompting for a directory. 

The variable `minibuffer-completing-file-name` needs to be set for it to work. Here's a minimal working example:
```
(require 'rfn-eshadow)
(require 'vertico)
(require 'vertico-directory)
(add-hook 'rfn-eshadow-update-overlay-hook 'vertico-directory-tidy)
(require 'consult)

(let ((minibuffer-completing-file-name t)) (consult-find (list 4)))
```

Would you consider adding this functionality to consult ?

**Comment by minad** [comment]
No, we cannot add this. The consult-find input is not a file name. The input is a search pattern, e.g., space-separated regexps.

**Comment by minad** [comment]
I think I misunderstood. You only meant the prompt, right? Binding minibuffer-completing-file-name around the whole command would not be right.

**Comment by KindlyRepeat** [comment]
Yes that's what I meant ! Thanks for being so reactive
