### ISSUE TITLE
wgrep doesn't work with embark-export from consult-line

### ISSUE THREAD

**Issue by dalgong** [minad/consult#884]
As title says, the following sequence of command doesn't work:

M-x consult-line RET some-text M-x embark-export RET
Now M-x wgrep-change-to-wgrep-mode doesn't work on the created "*Embark Export: ..." buffer.

**Comment by minad** [comment]
The `consult-line` export buffer is not a grep buffer, but an occur buffer. See https://github.com/minad/consult#embark-integration.
