### ISSUE TITLE
Annotations not showing up with `consult-completion-in-region`

### ISSUE THREAD

**Issue by aikrahguzar** [minad/consult#886]
Hi I am trying to modify the `pcomplete` capf so that `pcomplete-help` properties show up as annotations. Here is the code,

```emacs-lisp
(defun +eshell-pcomplete-annotate (cand)
  (when-let ((ann (and (stringp cand)
                       (get-text-property 0 'pcomplete-help cand))))
    (concat (propertize " " 'display '(space :align-to center)) ann)))

(defun +eshell-pcomplete-completions-at-point ()
  (let* ((res (pcomplete-completions-at-point))
         (table (nth 2 res)))
    (setf (plist-get (nthcdr 3 res) :annotation-function)
          #'+eshell-pcomplete-annotate)
    (setf (nth 2 res)
          (lambda (str pred action)
            (if (eq action 'metadata)
                (let ((metadata (cdr (funcall table str pred action))))
                  (setf (alist-get 'annotation-function metadata)
                        #'+eshell-pcomplete-annotate)
                  (cons 'metadata metadata))
              (funcall table str pred action))))
    res))

```

Trying  to complete in an `eshell` buffer  with `completion-at-point-functions` set to `(+eshell-pcomplete-completions-at-point)` produces the completions but they have no annotations.

I initially though adding `annotation-function` to completion-table metadata wouldn't be needed. But tried it when I couldn't get any annotations. They didn't appear but it lets me check that the annotation function itself is fine. Since `M-: (completing-read "Check" (nth 2 (+eshell-pcomplete-completions-at-point)))` shows the annotations. 

Thanks for the great package.

**Comment by minad** [comment]
Annotations work with `consult-completion-in-region` for example in Elisp mode. Thus this is not a bug here. Iirc `pcomplete-help` should generate annotations by itself, but the functionality is broken right now. I've opened a bug on the Emacs bug tracker about this a while ago.

**Comment by aikrahguzar** [comment]
> Annotations work with `consult-completion-in-region` for example in Elisp mode or also for the Capfs provided by Cape. Thus this is not a bug here. Iirc `pcomplete-help` should generate annotations by itself, but the functionality is broken right now. I've opened a bug on the Emacs bug tracker about this a while ago.

Thanks @minad, due you have the bug number?

`pcomplete-help` is not used for annotations in the default pcomplete capf, it is rather the `pcomplete-annotation` property which is mostly absent from the candidates while `pcomplete-help` is mostly present.

Anyhow experimenting a little more I found that the issue happened because the completion table has `(completion--unquote-requote . t)` in the metadata. I don't know where that parameter enters the completion system but if I remove it annotations show up. I have no idea why that is. I thought it might be due to `unquote` and `requote` functions somehow removing text properties but that doesn't seem like the case.

**Comment by minad** [comment]
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=61283
