### ISSUE TITLE
Require style

### ISSUE THREAD

**Issue by minad** [minad/consult#89]
I wonder about the best style to require libraries. We already require quite a few (heavy?) libraries which may not be loaded by default, should they be loaded via autoload-declaration, or required inside the function instead? The main problem is that the elisp checker does not like/check such declarations in contrast to proper require. Alternatively the consult.el file could be split up in multiple files? Maybe it is not necessary to do anything and just require everything in the main consult.el file. Would still be good to know the current best practices.

Ping @purcell for input

**Comment by purcell** [comment]
Just `require` everything at the top level. That's equivalent to loading with `eval-and-compile`. If you know that you don't need certain libraries to be defined at either runtime or compile-time, you can potentially do things like `(eval-when-compile (require ...))` but this is very rarely the case. Keep it simple. Also, avoid requiring things from within functions.

**Comment by minad** [comment]
Ok, so you are not recommending doing any kind of lazy loading of dependencies?

**Comment by minad** [comment]
Thank you for answering here, today! Merry Christmas!🎄

This the style I am currently using. So you are not recommending doing any kind of lazy loading of dependencies?

**Comment by purcell** [comment]
> So you are not recommending doing any kind of lazy loading of dependencies?

Correct. Usually trying to lazy load things manually is not worth the extra complication, and there is always the option of regular modularisation with generated autoloads.

**Comment by purcell** [comment]
And... Merry Christmas!

**Comment by minad** [comment]
> Correct. Usually trying to lazy load things manually is not worth the extra complication, and there is always the option of regular modularisation with generated autoloads.

Ok, thank you. Right now I am using the keep-it-simple-style, you are describing. I use this kind of autoload modularisation for consult-flymake.el. The other core dependencies are all required directly. Having a separate module only matters for dependencies which should not be loaded by default.

**Comment by purcell** [comment]
`consult-flymake` is a perfect example, yes.
