### ISSUE TITLE
Always prompt for directory when starting consult-ripgrep

### ISSUE THREAD

**Issue by petergaultney** [minad/consult#900]
I wanted to do something like https://github.com/minad/consult/issues/605 but don't have enough ELisp chops (or time in my day) to figure out how to switch directories once a `consult-ripgrep` session has started. I'd like to just drop into the directory picker and then go back to my search.

It would be really cool if `consult-ripgrep` had a more featureful interface (I know @minad prefers composable packages rather than built-in functions) that would allow the user to change the context while inside it.

Anyway, in the absence of that, I will post my hacked-together solution and close this issue so that others might benefit.

**Comment by petergaultney** [comment]
I hacked the following together, which I'm going to swap into the keybinding that I've been using for `consult-ripgrep` itself - I pretty much always want to choose a directory that isn't the project directory, and if I _did_ want the project directory, it's just one additional tap on `Enter`.

```
(defun my/consult-ripgrep ()
  (interactive)
  (run-at-time 0 nil #'consult-ripgrep
     (universal-argument)
    ))
```

I don't really understand why `run-at-time` is necessary here, but it didn't work without it, and I stole that idea from [this other related issue I found](https://github.com/minad/consult/issues/596) while looking around.

**Comment by minad** [comment]
The following should work:

~~~ elisp
(defun consult-ripgrep-always-query-dir ()
  (interactive)
  (consult-ripgrep t))
~~~
