### ISSUE TITLE
get-text-property: Args out of range: 0, 0

### ISSUE THREAD

**Issue by petergaultney** [minad/consult#901]
With `consult-projectile` installed, when running `projectile-find-references`, I get `Args out of range: 0, 0` printed in the minibuffer.

I've tracked it down to line 116 of consult-xref.el (20231202.1021, installed via straight.el):        `(get-text-property 0 'consult-xref (car candidates)))` - `candidates` is nil, which results in a call to `(get-text-property 0 'consult-xref nil`) which errors as shown.

I would like for there to be candidates for this particular reference, but figuring out why there aren't is a separate problem; this just seems like a bug of some sort?

**Comment by minad** [comment]
Can you please open a bug on the consult-projectile issue tracker? This command is not maintained here. See also https://github.com/minad/consult#bug-reports.
