### ISSUE TITLE
[(char-or-string-p nil)] when calling consult--file-preview on certain directories

### ISSUE THREAD

**Issue by WuuBoLin** [minad/consult#903]
When using `find-file` and invoking `consult--file-preview`, certain directories cannot be previewed and display a `[(char-or-string-p nil)]` error, as shown in the image below.

I don't understand why this error occurs, and the directories that cannot be previewed seem random to me.

Additionally, I discovered that this error only appears after Emacs has been running for some amount of time.

![image](https://github.com/minad/consult/assets/78901633/c3902707-de3e-4e79-a936-9f531bf8fdea)

**Comment by minad** [comment]
See https://github.com/minad/consult#bug-reports. Thanks.

**Comment by WuuBoLin** [comment]
After debugging for a while, I found out that uninstalling Affe will fix the problem.
