### ISSUE TITLE
Order consult-lines candidates by line

### ISSUE THREAD

**Issue by dwrz** [minad/consult#910]
Is it possible to have `consult-lines` show candidates in the order they appear in the buffer, rather than relative to the cursor?

```
1 abc
2 def
3 ghi
4 abc
5 jkl
6 mno
7 abc
``` 
 
 I run `consult-lines` with the cursor at 4, and search for `abc`, could the candidate list look like the following:
 
 ```
 1 abc
 4 abc
 7 abc
 ```

Instead of:
```
4 abc
7 abc 
1 abc
```

I know setting `(setq consult-line-start-from-top t)` will keep the candidates ordered, but I don't want the preview to jump to the top of the buffer.

Thank you for your work on all your packages!

**Comment by minad** [comment]
Duplicate #795
