### ISSUE TITLE
consult-line warning in non-org-mode buffer

### ISSUE THREAD

**Issue by ram535** [minad/consult#920]
When doing `M-x consult-line` in non-org-mode buffer it throws this warning.

```
Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer hello.c> (c-ts-mode)
```
In this example consult-line was used in a buffer in c-ts-mode.

GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-11-25

**Comment by minad** [comment]
Please see https://github.com/minad/consult?tab=readme-ov-file#bug-reports.
