### ISSUE TITLE
consult-buffer does not show default candidate in minibuffer

### ISSUE THREAD

**Issue by nordlow** [minad/consult#923]
`M-x consult-buffer` should show default candidate in minibuffer like `M-x switch-to-buffer` does without any user input whatsoever.

The prompt should also say `"Switch to buffer: "` instead of currently just `"Switch to: "`.

Also `M-x consult-buffer` followed by just `RET` should have the same behavior as `switch-to-buffer` instead of currently quitting with message `"No selection"`.

**Comment by minad** [comment]
> M-x consult-buffer should show default candidate in minibuffer like M-x switch-to-buffer does without any user input whatsoever.

You mean as part of the prompt? For `consult-buffer` this is less necessary because of preview.

> The prompt should also say "Switch to buffer: " instead of currently just "Switch to: ".

`consult-buffer` also supports switching to recent files, so "Switch to buffer: " is too narrow.

> Also M-x consult-buffer followed by just RET should have the same behavior as switch-to-buffer instead of currently quitting with message "No selection".

Indeed, this was broken due to a recent commit. Fixed.
