### ISSUE TITLE
Previews don't work with Selectrum

### ISSUE THREAD

**Issue by veronikazaglotova** [minad/consult#94]
I switched to icomplete-vertical and it (at least by default) gives me headaches on how uncomfortable it is, it doesn't even complete by tab

**Comment by minad** [comment]
@veronikazaglotova For me it works with the newest Selectrum and Consult version. Which version of Emacs are you using, which Selectrum commit hash, which Consult commit hash. I thought you had previews working before - did you change your setup?

**Comment by veronikazaglotova** [comment]
> I thought you had previews working before

I never enabled them actually. Either I did a big dumb somewhere and said that previews work or you are confusing me with someone else.

Selectrum 4106b21

consult 1a975bc

Emacs 27.1 (28 is buggy mess)

My setup is as follows:
```
(use-package consult
  :straight (consult :type git :host github :repo "minad/consult" :branch "main")
  :init
  (consult-preview-mode)
  :bind
  ("C-x b" . consult-buffer)
  ("M-y" . consult-yank-pop)
  ("C-," . consult-line)
  :custom
  (consult-line-point-placement 'match-end))

(use-package selectrum-prescient
  :config
  (selectrum-mode +1)
  ;; to make sorting and filtering more intelligent
  (selectrum-prescient-mode +1)

  ;; to save your command history on disk, so the sorting gets more
  ;; intelligent over time
  (prescient-persist-mode +1))

;; Enable richer annotations using the Marginalia package
(use-package marginalia
  :straight (marginalia :type git :host github :repo "minad/marginalia" :branch "main")
  :config
  (marginalia-mode)
  (setq marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light)))
```

**Comment by veronikazaglotova** [comment]
Actually #84 was made because I didn't know consult-line could have previews enabled.

**Comment by veronikazaglotova** [comment]
They don't work on my phone either. Emacs 27, selectrum, marginalia, consult, all old versions (I don't have git installed on my phone).
consult-20201215-1420
marginalia-20201213-2113
selectrum-20201212-957
I'm in GMT+6 time zone if that matters.

**Comment by minad** [comment]
You are missing consult-selectrum. Please read the readme carefully, please only open bug reports when you are very sure that it is an issue - a general guideline - if you find a **very obvious** "bug", like missing previews, it is very certain that it is not a bug, since the developers also use the package.

**Comment by veronikazaglotova** [comment]
thx
