### ISSUE TITLE
Add "future history" to consult commands

### ISSUE THREAD

**Issue by hmelman** [minad/consult#96]
Maybe I'm misunderstanding something but I was trying to make this work and couldn't figure it out.  I'm using selectrum on Emacs 27.1

Invoking `consult-line` and typing `M-n` to use "future history" puts the first candidate in the input field.  I suspect I'll rarely want to use the first line of the buffer this way.  Instead, to avoid binding both commands `consult-line` and `consult-line-symbol-at-point`, I think I'd prefer the "future history" of `consult-line` to be the symbol-at-point.

The elisp manual says future history is set in `read-from-minibuffer` via the `default` argument. I tried changing `consult-line` so that the `:default` argument was `(thing-at-point 'symbol)` but it set a default value I could use with return and not with `M-n`.  Setting it as `:initial` of course did the same thing as `consult-line-symbol-at-point` which isn't what I want.

I realized that the elisp manual only mentions "future history" on `read-from-minibuffer` and not `completing-read` and perhaps I'm misunderstanding something about it.

Is it possible to do what I want with `consult-line`?

Finally I don't understand the use of `:input` in the `:history` option.  And I found that `:history '(:input consult--line-history)` is used for many commands and I thought perhaps some are cut and paste errors like the `consult-mark` commands?

**Comment by minad** [comment]
> Finally I don't understand the use of :input in the :history option. And I found that :history '(:input consult--line-history) is used for many commands and I thought perhaps some are cut and paste errors like the consult-mark commands?

This means that we use the input string as history entry instead of the selected candidate. This is better behavior for search. I am using a shared history for all line based commands for convenience. This is not a copy-and-paste error.

> I realized that the elisp manual only mentions "future history" on read-from-minibuffer and not completing-read and perhaps I'm misunderstanding something about it.

Unfortunately I know nothing about the future history, sounds like an oxymoron :)
If it is configurable we could certainly use this somehow, but from what I know about :default and :initial I don't think it is possible.
If you find a way, please let me know!

Another option would be to bind some keybinding to the minibuffer keymap which loads some default value, but this is nothing I would like to provide as part of consult by default. But you could implement it in a custom command which wraps consult-line. What do you think?

**Comment by hmelman** [comment]
See this for a description: https://engineering.collbox.co/post/working-faster-in-emacs-by-reading-the-future/

**Comment by hmelman** [comment]
> This means that we use the input string as history entry instead of the selected candidate. This is a better behavior for search. I am using a shared history for all line based commands for convenience. This is not a copy-and-paste error.

Ah, I get it, it's just a list and `:input` is symbol to say use the input not the candidate.  Playing with `consult-mark` now I see the value if you type input to select a line, typically I just navigate the candidate list with no input.

**Comment by minad** [comment]
> See this for a description: https://engineering.collbox.co/post/working-faster-in-emacs-by-reading-the-future/

Sure, I also found that blog post. But it does not help us here, or does it?

I guess I close this issue, since I don't see anything actionable here. If you find out something regarding the future-history, if it is possible with completing-read, please let me know!

**Comment by hmelman** [comment]
I think what's supposed to happen is at a prompt, if you use `M-n` to move past the history (typically right after the command is invoked) it should put the default value into the input and allow editing.  I'm not sure why it's not working or if it's a consult or selectrum issue.  `M-n` at the prompt is bound to `next-history-element` which seems right.  `minibuffer-default-add-function` seems to be set to its default value `minibuffer-default-add-completions`.  Perhaps selectrum or consult should be setting it.  Ivy does this:

    (setq-local minibuffer-default-add-function
                  (lambda ()
                    (list ivy--default)))

**Comment by minad** [comment]
@hmelman Ah ok, that's cool. Does it work with both selectrum and icomplete? We could add this to consult--read as an option `:dynamic-history` or something similar. And then this option could be used by `consult-line` etc.

**Comment by hmelman** [comment]
I'm not good with icomplete but I tried enabling it and using consult-line with my change of :default and it did seem to bring the current symbol into the input though consult-line didn't seem happy.  So maybe it's an issue with both.

I think this should just be standard behavior, that M-n at the end of history puts default into the input.  I think it shouldn't need another thing like :dynamic-history.

**Comment by minad** [comment]
> I think this should just be standard behavior, that M-n at the end of history puts default into the input. I think it shouldn't need another thing like :dynamic-history.

Yes, sure. Take a look at the default function for this `minibuffer-default-add-completions`. The question is if we want to override it or add our own elements - this is what you originally proposed, right?

**Comment by hmelman** [comment]
I would think we'd just change `minibuffer-default-add-function` but I really don't know this api well enough to be reliable.

I think consult-line and the other line oriented commands are the main issue for this now.  I can look through the other functions.  AFAIK future history usually just pulls a thing-at-point in, so I don't  know of too many other options.  ffap would do this for files, not sure it should do anything for buffers.  consult-apropos already does symbol-at-point.

**Comment by minad** [comment]
@hmelman 
>

**Comment by hmelman** [comment]
> More precisely, I propose we replace it locally per consult--read invocation.

That seems like the wrong level to me.  As I said, "I think this should just be standard behavior, that M-n at the end of history puts default into the input." AFAICT ivy does it in the framework and not in each counsel command.  And as I asked I don't know if consult should do this or selectrum.  My experiment with icomplete suggest it handles it though maybe consult needs more support. Did you try it with icomplete?

**Comment by minad** [comment]
> That seems like the wrong level to me. As I said, "I think this should just be standard behavior, that M-n at the end of history puts default into the input." AFAICT ivy does it in the framework and not in each counsel command.

No. It is not the wrong level. I won't change any global defaults. If it makes sense to dynamically inject history elements we can change it locally, but that's it. Ivy does the wrong thing.

> And as I asked I don't know if consult should do this or selectrum. 

Consult should do it locally via `consult--read`. The option has nothing to do with consult/selectrum really, it only modifies the `goto-history-element` commands which happen to be bound inside the minibuffer. If we want to use it in consult, we can add an option to `consult--read`.

> My experiment with icomplete suggest it handles it though maybe consult needs more support. Did you try it with icomplete?

I tried both. As I said, it just modifies the command, so it will work everywhere when `goto-history-element` is used.

**Comment by minad** [comment]
Example - this is how this would look like. We could configure it for each command separately if we would like to have this.

`(consult--read "Prompt: " '(candidate1 candidate2...) :future-history '("injected1" "injected2" ...)`

**Comment by minad** [comment]
@hmelman I think I misunderstood you, you just want the default value **always**? We could surely make this the default behavior of `consult--read` if a :default is given and no :future-history.

**Comment by hmelman** [comment]
I've never seen a future history of more than one element but as I've said, I'm no expert.  I'm not what they would be?  Things further from point? :)

**Comment by minad** [comment]
But with selectrum there is no real reason to add the default value as you propose - since if you press RET, the default is returned directly. Furthermore the default is already selected if it appears in the candidate list. So I don't understand why you would want this.

**Comment by hmelman** [comment]
As I said far above " it should put the default value into the input **and allow editing**."

**Comment by minad** [comment]
> I've never seen a future history of more than one element but as I've said, I'm no expert. I'm not what they would be? Things further from point? :)

I think for some commands it makes sense to just provide a list of default values, which could be put into this future history. But this depends on the command. I wasn't even aware that this is possible. It is good to know.

> As I said far above " it should put the default value into the input and allow editing."

Okay, this makes sense.

**Comment by minad** [comment]
>> As I said far above " it should put the default value into the input and allow editing."
> Okay, this makes sense.

Or it doesn't. With selectrum I can press TAB to get the default candidate put into the minibuffer.

**Comment by hmelman** [comment]
> With selectrum I can press TAB to get the default candidate put into the minibuffer.

If I change consult-line's default to (thing-at-point 'symbol) and invoke it, the default value selectrum shows is correct but if I hit TAB the first candidate is put in input, not the default.

**Comment by minad** [comment]
> And what does :default-top do?

Moves the default candidate to the top, see the docstring. This is only used for consult-line such that the default is shown in order with the other lines. Works only on Selectrum.

> If I change consult-line's default to (thing-at-point 'symbol) and invoke it, the default value selectrum shows is correct but if I hit TAB the first candidate is put in input, not the default.

Ah okay, yes. This happens if the default does not appear in the list of candidates.

Now I understand better that it would be worth to have this. Maybe we could remove `consult-line-symbol-at-point` and `consult-line-from-isearch` and instead put the elements inside the future history (first the current symbol, second the isearch string). Then we would not need extra commands for this. I am not sure if I want to offer multiple different ways to achieve the same.
We could even extend more of the commands with thing-at-point behavior (but not via :default, but via :future-history). Ping @s-kostyaev, since he originally added the `consult-line-symbol-at-point` commands.

**Comment by minad** [comment]
My proposal would be the following:

1. Remove consult-line-symbol-at-point and consult-line-from-isearch.
2. Add :future-history to consult--read
3a. if :future-history is not specified and :default is specified, use the :default value as default entry for the future-history.
3b. Alternative: if both :default and :future-history are specified, prepend future-history with default
4. Use :default in commands, where it makes sense (re-check all commands!)
5. Use :future-history in commands, where it makes sense (check all commands!) For example `consult-line` could get the symbol-at-point and the isearch-string as future-history

**Comment by hmelman** [comment]
I'm not sure about `consult-line-from-isearch` (it should do what's natural for isearch and I haven't played with it)  but my OP mentioned wanting to combine `consult-line` and `consult-line-symbol-at-point` :) 

`dired-do-shell-command` seems to possibly support multiple future history items depending on what's in an alist matching the filename.  Otherwise maybe @clemera has thoughts on this, he had commented on future history in ivy [here](https://old.reddit.com/r/emacs/comments/b78e6u/tips_ivy_search_thing_at_point_with_swiper/)

I had missed the docstring of default-top because I searched for :default-top 🤦‍♂️

**Comment by hmelman** [comment]
How would :future-history differ from a :default which is a list of strings (that's the mechanism `read-from-minibuffer` and I assume `completing-read` uses for a future history of more than one item).

**Comment by minad** [comment]
> I'm not sure about consult-line-from-isearch (it should do what's natural for isearch and I haven't played with it) but my OP mentioned wanting to combine consult-line and consult-line-symbol-at-point :)

I think adding the isearch-string to the future history is also somehow natural. I guess there are more possible strings which make sense to add to the future-history. If someone wants this `consult-line-from-isearch` back they could easily add it to their init.el, it is trivial enough. I think it makes more sense to have fewer better designed commands than many special cases.

> dired-do-shell-command seems to possibly support multiple future history items depending on what's in an alist matching the filename. Otherwise maybe @clemera has thoughts on this, he had commented on future history in ivy here

Yes, since it is a lambda, it could probably look at some context. We could also support this, but I would probably make `:future-history` a list to get started in `consult--read`.

> How would :future-history differ from a :default which is a list of strings (that's the mechanism read-from-minibuffer and I assume completing-read uses for a future history of more than one item).

Well, `:default` changes much more - it is the default return value. While having the default in the future-history may always make sense (see point 3b above), there are cases where you might want a future history but not a default value.

If you have time to check the other commands, please do! This would help a lot and then we will could have this earlier. My focus right now is on #91.

**Comment by minad** [comment]
I added `:add-history` to `consult--read`. It works for `consult-line` now! See https://github.com/minad/consult/commit/33a987e06ff166cc25f16323fb9ac82a27b492ea. Furthermore I added symbol-at-point to consult-imenu and consult-outline. For now I didn't find more commands where it makes sense.

@hmelman @oantolin Please let me know, if more commands would profit from tweaking `:add-history`.
