### ISSUE TITLE
Small comments on new grep commands,  and consult-grep fails on mac

### ISSUE THREAD

**Issue by hmelman** [minad/consult#97]
I'm using `M-s g` for my consult-grep command of choice.  Perhaps you'd like that as a default recommendation.  I think it's common to put a grep-like command here.

The README description of `consult-ripgrep` has a sentence fragment: "similarily to consult-grep".

The docstrings of the various consult-grep commands should refer to their command variables.  Since there should be an easy way for the user to customize these, I assume you're going to add some defcustoms and perhaps are waiting until then.

Which brings me to, `consult-ripgrep` and `consult-git-grep` work for me.  `consult-grep` does not.  I type my string, I see a red * added to the prompt, and nothing happens.  I suspect its because I'm on a mac and don't have GNU grep installed, `grep` is apple's `/usr/bin/grep` a BSD grep.  `M-x grep` does work.  So emacs' built-in though baroque grep configuration works, perhaps you could leverage it.

FWIW I had to configure `counsel-grep-base-command` as "grep -z -E -n -e %s %s"  I tried tweaking consult--grep-command similarly but was unsuccessful.

**Comment by minad** [comment]
> I'm using M-s g for my consult-grep command of choice. Perhaps you'd like that as a default recommendation. I think it's common to put a grep-like command here.

Yes, would be possible. The README already recommends to either use M-s or M-g. But "M-g r" is like *gr*ep ;)
Do what you like!

> The docstrings of the various consult-grep commands should refer to their command variables. Since there should be an easy way for the user to customize these, I assume you're going to add some defcustoms and perhaps are waiting until then.

Thanks for finding the typo.

> Which brings me to, consult-ripgrep and consult-git-grep work for me. consult-grep does not. I type my string, I see a red * added to the prompt, and nothing happens. I suspect its because I'm on a mac and don't have GNU grep installed, grep is apple's /usr/bin/grep a BSD grep. M-x grep does work. So emacs' built-in though baroque grep configuration works, perhaps you could leverage it.

I will try a bsd grep here too. What you could do as a first step is checking the buffer ' *consult async stderr*'. Is there some error for consult-grep? I won't leverage the emacs builtin grep facilities. They are seriously lacking in every aspect unfortunately. I tried - but I could not use them.

**Comment by minad** [comment]
@hmelman It turns out there is no easy way to install a bsd grep on my linux, so I cannot debug this right now. But this should be fairly easy to figure out - just check if I am using arguments which are invalid for bsd-grep. And then the output format should look like this: `file\0line:string\n` or `file\0line\0string\n`. Furthermore, matches must be colored by `\e[<digits>m\e[m`.

**Comment by hmelman** [comment]
> But "M-g r" is like grep ;)

This hadn't occurred to me :) 

I found a fix for my grep.  Running it from the command line, I need a `.` between the `-r` and `-e` which makes sense.  I think that should work for GNU grep too, and it's probably a GNU extension to support no directory arg after the `-r`.
