### ISSUE TITLE
Previews do not work with selectrum

### ISSUE THREAD

**Issue by inigoserna** [minad/consult#98]
Hi,

I can't make previews work with selectrum. 

I've tested with emacs 27.1 (from Fedora 33), master, feature/pgtk, and feature/native-comp branches.
Last selectrum, consult, and consult-selectrum packages from MELPA updating every couple of hours since 2 days ago, when I first tried selectrum/consult/prescient.
Last versions tested:
- consult: 20201229.405 - faa18eaaf03fa810c2164218615c252ee4d65781
- consult-selectrum: 20201229.347 - faa18eaaf03fa810c2164218615c252ee4d65781
- selectrum: 20201226.1908 - 4106b216f9b3ccf8960abe89fb9863c570a6f376

Also running with emacs -Q, with only selectrum, consult, and consult-selectrum packages installed.
`consult-preview-mode` is enabled, of course, and every `consult-preview-*` variables is set to `t` as well.
But no way.

I have read #94, that looks similar, but I have consult-selectrum installed in my case.

Any ideas or trouble-shootings steps I could do?

Thanks

**Comment by minad** [comment]
Could you please paste the exact code you are pasting into the scratch buffer if you run emacs -Q?

**Comment by inigoserna** [comment]
Ok. My fault. After a couple of days testing anything I could think of, I've found the problem just when I opened the issue.

I don't use use-package, so it's not enough with installing `consult-selectrum`, I needed `(require 'consult-selectrum)` before anything else.

I will close the issue now. Perhaps it would be useful to add a note to the documentation.

Thanks, and sorry for the noise.

**Comment by minad** [comment]
@inigoserna I don't think there is any order-dependence.

If I load the following in emacs -Q, it works.

~~~ elisp
(progn
(load "~/.config/emacs/elpa/selectrum-20201226.1908/selectrum.el")
(load "~/.config/emacs/elpa/consult-0.1/consult.el")
(load "~/.config/emacs/elpa/consult-selectrum-0.1/consult-selectrum.el")
(selectrum-mode)
(consult-preview-mode)
)
~~~

**Comment by inigoserna** [comment]
```
(progn
  (setq package-user-dir "/tmp/emacs"
	package-archives '(("gnu"   . "http://elpa.gnu.org/packages/")
                           ("melpa" . "http://melpa.org/packages/")))
  (package-refresh-contents)
  (package-install 'consult-selectrum)

  ;; (require 'consult-selectrum)
  (selectrum-mode)
  (consult-preview-mode)

  (consult-line))
```

It works when I uncomment the `require` line.

**Comment by minad** [comment]
Well, your snippet **does not** load consult-selectrum if you are commenting out the relevant line. consult-selectrum is not autoloaded.

**Comment by inigoserna** [comment]
> Well, your snippet **does not** load consult-selectrum if you are commenting out the relevant line. consult-selectrum is not autoloaded.

Yeah, but wouldn't it be autoloaded? 

I mean, if it's installed it should be executed by default without the user explicitly having to do so.
Or better a `consult-selectrum-mode` minor-mode that should be autoloaded, which do the needed stuff, adds the hooks and executes the add-advice.
`selectrum-mode` is autoloaded, why not `consult-selectrum`?

**Comment by minad** [comment]
> Yeah, but wouldn't it be autoloaded?

No.

> I mean, if it's installed it should be executed by default without the user explicitly having to do so.

No, things are generally not autoloaded if installed. They must explicitly request that.

> Or better a consult-selectrum-mode minor-mode that should be autoloaded, which do the needed stuff, adds the hooks and executes the add-advice.
selectrum-mode is autoloaded, why not consult-selectrum?

This would be an option. We could add `consult-selectrum-mode`, which triggers autoloading but would not have any other benefits. I don't see any advantage of using `(consult-selectrum-mode 1)` vs `(require 'consult-selectrum)`.

**Comment by minad** [comment]
It could be an option to rewrite the consult-selectrum library such that it indeed autoloads and autoconfigures itself when selectrum is loaded, but this would involve unnecessary complexity. Furthermore it would only be useful if you manually install the package without mentioning it in your init.el. I recommend to use `use-package` instead.

**Comment by inigoserna** [comment]
Sorry, I don't like `use-package`. But I understand your opinion.
Anyway, I still think that it should be mentioned in the docs.

Thanks!

**Comment by minad** [comment]
> Sorry, I don't like use-package. But I understand your opinion.

I've seen that opinion stated before, but I've yet to encounter a convincing argument regarding the disadvantages of `use-package`.
Only "not liking it" is not a technical argument - I would be interested if there is a reason to not use it. There has been some discussion before if alternative configuration/installation methods should be mentioned in the readme.

 > Anyway, I still think that it should be mentioned in the docs.

What would you like to see? If you would like to use a package you should generally require it. Right now my standpoint is to not clutter the readme with multiple different installation/configuration methods.

**Comment by minad** [comment]
@inigoserna I am thinking about adding an autoload cookie to consult-selectrum to avoid such issues in the future.

**Comment by inigoserna** [comment]
> > Sorry, I don't like use-package. But I understand your opinion.
> 
> I've seen that opinion stated before, but I've yet to encounter a convincing argument regarding the disadvantages of `use-package`.
> Only "not liking it" is not a technical argument - I would be interested if there is a reason to not use it. There has been some discussion before if alternative configuration/installation methods should be mentioned in the readme.

Well... I've tested it some years ago and it didn't provide anything better for my own configuration. It even made it more complex.
My config was evolved since more than 20 years ago and I prefer to group features by categories: UI, devel, email, global key bindings, etc. Then I use `outshine` package to toggle sub/categories, etc.
I also tried keeping it in an org-mode file and using tangle to generate it. A few months later I came back to .el file and outshine.


> > Anyway, I still think that it should be mentioned in the docs.
> 
> What would you like to see? If you would like to use a package you should generally require it. Right now my standpoint is to not clutter the readme with multiple different installation/configuration methods.

What about something like:
"""
Please note that if you are not using `use-package` in your configuration file you ought to add a line like `require 'consult-selectrum` in order to activate it.
"""

**Comment by inigoserna** [comment]
> @inigoserna I am thinking about adding an autoload cookie to consult-selectrum to avoid such issues in the future.
> 
> **EDIT**: I looked into this but it does not seem to be worth the effort. It is just better and simpler to require manually or use use-package declarations.

Ok. No problem.

**Comment by minad** [comment]
> Well... I've tested it some years ago and it didn't provide anything better for my own configuration. It even made it more complex.
My config was evolved since more than 20 years ago and I prefer to group features by categories: UI, devel, email, global key bindings, etc. Then I use outshine package to toggle sub/categories, etc.
I also tried keeping it in an org-mode file and using tangle to generate it. A few months later I came back to .el file and outshine.

Yes okay I see. If you have a config which has grown over a long time with high sophistication you might not get the benefits. In my case, I also had an evolved config, but it wasn't well-structured. With use-package that got significantly better with lazy loading for free.

> What about something like:
"""
Please note that if you are not using use-package in your configuration file you ought to add a line like require 'consult-selectrum in order to activate it.
"""

I am not sure. Such special cases are always hard to cover. It might be better to use:

~~~ elisp
(eval-after-load 'selectrum '(require 'consult-selectrum))
~~~

This would be helpful if you are not always starting with selectrum right away, some users may default to icomplete and only have selectrum for testing. I have both icomplete-vertical and selectrum installed, but mainly use selectrum, so in my case at least it is always loaded.

**Comment by inigoserna** [comment]
> ```emacs-lisp
> (require 'selectrum) ;; alternatively (load "...")
> (require 'consult)
> (require 'consult-selectrum)
> (selectrum-mode)
> (consult-preview-mode)
> ```

But the first 2 lines of code in `consult-selectrum` are the requires for the `selectrum` and `consult` so IMO it's redundant.
A `(require 'consult-selectrum)` is enough.

**Comment by minad** [comment]
@inigoserna Right, but you may want to activate that only optionally.

~~~ elisp
(require 'consult-selectrum)
(selectrum-mode)
(consult-preview-mode)
~~~

~~~ elisp
(require 'icomplete-vertical)
(require 'consult)
(icomplete-vertical-mode)
(consult-preview-mode)
~~~
