### ISSUE TITLE
Add support to display the matched heading's sub-headings also as candidates in the consult-outline's completion

### ISSUE THREAD

**Issue by IceAsteroid** [minad/consult#987]
Is it possible to display the matched heading and plus its sub-headdings as candidates in ```consult-outline```?

For example:
```
* Colors
** Red
*** Apple
** Yellow
*** Banana
* Fruits
** Orange
** Apple
```

Say if I search for ```Colors```, the minibufer's candidates would be:

```
* Colors
** Red
*** Apple
** Yellow
*** Banana
```

If heading level is triggerd, say Level 2, the candidates would be:

```
* Colors
** Red
** Yellow
```

The reason why not to use ```consult-org-heading``` instead, is because it displays subheadings preceded by its parent headings.

When a subheading is deeply nested, the heading can't be displayed correctly as it's truncated at the edge, except its parent headings are shown.

It would be:
```
first-level heading A/subheading1/subheading1.1/subheading1.1.1/sub->
first-level heading B/subheading1/subheading1.1/subheading1.1.1/sub->
```

Any ideas?

**Comment by minad** [comment]
Duplicate https://github.com/minad/consult/discussions/862

**Comment by IceAsteroid** [comment]
@minad The issue of what it's described, is not exactly duplicated with #862

**Comment by IceAsteroid** [comment]
> Duplicate #862

Not exactly duplicate though, the implementations are different. Here I just want consult to be able to display the searched heading and also its sub-headings as cnadidates, nothiing else. No nesting "nested parent titles" like "parent1/parent2/the_subheading" etc

**Comment by IceAsteroid** [comment]
@minad How could I possibly re-open this issue?
